### ISSUE TITLE
Please open docker.io/pai

### ISSUE THREAD

**Issue by lifubang** [Microsoft/pai#1013]
When I deploy a pai cluster, there were some errors:
2018-07-30 09:56:34,889 [INFO] - paramiko.transport : Connected (version 2.0, client OpenSSH_7.2p2)
2018-07-30 09:56:35,048 [INFO] - paramiko.transport : Authentication (password) successful!
2018-07-30 09:56:35,167 [INFO] - k8sPaiLibrary.maintainlib.common : Executing the command on host [172.17.254.24]: sudo ./worker-deployment/kubelet-start.sh worker-deployment
*******************
Unable to find image 'pai/hyperkube:v1.9.4' locally
docker: Error response from daemon: pull access denied for pai/hyperkube, repository does not exist or may require 'docker login'.

I test pull:
docker pull docker.io/pai/hyperkube:v1.9.4
Error response from daemon: pull access denied for pai/hyperkube, repository does not exist or may require 'docker login'

and I visit the website https://hub.docker.com/r/pai/, it returns 404.

Please open it, thx.

**Comment by lifubang** [comment]
I can't visit gcr.io/google_containers in my company network. Who can give me a docker registry which contains necessary kubernetes images in pai cluster.

**Comment by ydye** [comment]
In thie field https://github.com/Microsoft/pai/blob/master/cluster-configuration/kubernetes-configuration.yaml#L31
please set ```docker.io/openpai```

**Comment by lifubang** [comment]
Thx. I think the doc should be improved. see #1017

**Comment by lifubang** [comment]
The doc has been improved. You'll save time when deploy quick-start.
