### ISSUE TITLE
dev-box can be ended by docker restart

### ISSUE THREAD

**Issue by DongZhaoYu** [Microsoft/pai#1037]
https://github.com/Microsoft/pai/blob/cff136d4cb101df6fee21bc8ffbb4cc60addc230/pai-management/k8sPaiLibrary/maintaintool/docker-ce-install.sh#L81

When I test in single dev-box, 
python paictl.py cluster k8s-bootup -p config-path 
fails with this error:
error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.38/exec/ddca13a2d95e53d09d5c6d02e43b343b784c561873e4519f88cf2000d85e4afd/json: read unix @->/var/run/docker.sock: read: connection reset by peer

This is caused by the docker restart here.

**Comment by YitongFeng** [comment]
I encounter the same problem today, if docker installed we shouldn't restart docker. @ydye 
https://github.com/Microsoft/pai/blob/cff136d4cb101df6fee21bc8ffbb4cc60addc230/pai-management/k8sPaiLibrary/maintaintool/docker-ce-install.sh#L37-L39

**Comment by DengZeshuai** [comment]
I meet the same problem today，is there anybody solve this problem?

**Comment by fanyangCS** [comment]
dev-box can not be deployed to any OpenPAI machine. https://github.com/Microsoft/pai/pull/1726
