### ISSUE TITLE
How to change the mount-point?

### ISSUE THREAD

**Issue by ydye** [Microsoft/pai#104]
https://github.com/Microsoft/pai/blob/3288c52c442bc4a1751a1e62b0e39603e462af23/job-tutorial/cntk/cntk-example.sh#L27

After change the data path as a template parameter. I think this ENV should be a template parameter too. Let's solve it.

@abuccts

**Comment by ydye** [comment]
#103

**Comment by abuccts** [comment]
I don't think the hdfs mount point will be influenced by data folder. That mount point is inside docker container and is not related to the host env.

**Comment by ydye** [comment]
Ok, if so I will close this issue. Because the data folder mount point change won't have a influence on your cntk script right? @abuccts

**Comment by abuccts** [comment]
It's specified by user and can locate anywhere inside the docker container.
