### ISSUE TITLE
IP and port‘s unfixing is unfriendly to service users.

### ISSUE THREAD

**Issue by mzmssg** [Microsoft/pai#1040]
Currently, to access service(eg, a nginx server), users need get allocated IP and port manually from PAI website, and it would change when rescheduling. It is unfriendly to service user. Should we provide an uniform mechanism for such service?

**Comment by xwzheng1020** [comment]
Also, changing the SSH key every time is a bit inconvenient

**Comment by mzmssg** [comment]
@xwzheng1020 It would be better to open a new issue for it.

**Comment by fanyangCS** [comment]
this is unfortunately by design, as we cannot fix the port and IP due to server availability and the dynamic nature of port assignment. 

However, through OpenPAI rest api, user can always get the most updated IP/Ports.
