### ISSUE TITLE
关于获取jobConfig

### ISSUE THREAD

**Issue by damon008** [Microsoft/pai#1051]
getJobConfig(userName, jobName, next) {
    const hdfs = new Hdfs(launcherConfig.webhdfsUri);
    hdfs.readFile(
      `/Container/${userName}/${jobName}/JobConfig.json`,
      null,
      (error, result) => {
        if (!error) {
          next(null, JSON.parse(result.content));
        } else {
          next(error);
        }
      }
    );
  }
关于这段代码，请问能否可以同步执行，或者有return返回呢？

**Comment by Gerhut** [comment]
Node.js is designed as [an asynchronous event driven JavaScript runtime](https://nodejs.org/en/about/). Almost all I/O operations (including network I/O) are run asynchronously. Making it runs synchronously will block the main process and prevent it from serving other requests.

May I know what you are looking for so I can give you more advice to achieve them?

**Comment by damon008** [comment]
I want to get for a global variable, out of the function ,I can use the result.

**Comment by damon008** [comment]
@Gerhut   I want to get for a global variable, out of the function ,I can use the result.

**Comment by Gerhut** [comment]
How about storing the result in global just after the function callbacks? Like
```JavaScript
getJobConfig(userName, jobName, (error, result) => {
  if (error == null) global.jobConfig = result
})
```

Or even using a Promise if the result status may be needed before it returns.

```JavaScript
global.jobConfigPromise = new Promise((resolve, reject) => {
  getJobConfig(userName, jobName, (error, result) => {
    if (error) {
      reject(error)
    } else {
      resolve(result)
    }
  })
})
```

**Comment by damon008** [comment]
@Gerhut This method seems not to work.  the second method ，I do not understand

**Comment by fanyangCS** [comment]
no further info. close the issue.
