### ISSUE TITLE
webportal start failed on windows because of envsub can't be installed

### ISSUE THREAD

**Issue by logenBupt** [Microsoft/pai#1054]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! envsub@3.1.0 postinstall: `test -d .git && cp gitHookPrePush.sh .git/hooks/pre-push || true`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the envsub@3.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\anluo\AppData\Roaming\npm-cache\_logs\2018-08-09T11_39_14_038Z-debug.log

**Comment by logenBupt** [comment]
It's ok in wsl. By the way, so if I just want to start a standalone web portal, I also need to assure that the os is Linux, is that right? Thanks.

**Comment by Gerhut** [comment]
`postinstall` script of `envsub` depends on built-in unix shell commands. So any shell compatible with unix shell should works, like [Git BASH](https://gitforwindows.org/#bash) base on msys2.
