### ISSUE TITLE
How to get every container's containerCompletedTimestamp in a job

### ISSUE THREAD

**Issue by weiranzhixin** [Microsoft/pai#1058]
* question is **How to get every container's containerCompletedTimestamp in a finished job**
*the detail is as follows:*
* In my submitted job, there are two containers, I want to get every container's `containerCompletedTimestamp`
* but it was found that one `containerCompletedTimestamp` is `null`
* use command  `curl http://IP:9086/v1/Frameworks/job1` can get the following result:
![image](https://user-images.githubusercontent.com/38908055/43943297-a415d74e-9cad-11e8-85b6-06690439daf0.png)
in the picture, `containerCompletedTimestamp` of `hello_cluster1` is `null` 
my job config is as follows:
```
{
  "jobName": "job1",
  "image": "mxnet:v1.1",
  "gpuType": "",
  "killAllOnCompletedTaskNumber": 1,
  "retryCount": 0,
  "taskRoles": [
    {
      "name": "hello_cluster1",
      "taskNumber": 1,
      "cpuNumber": 1,
      "memoryMB": 512,
      "gpuNumber": 0,
      "command": "echo hello; sleep 10"
    },
    {
      "name": "hello_cluster2",
      "taskNumber": 1,
      "cpuNumber": 1,
      "memoryMB": 512,
      "gpuNumber": 0,
      "command": "echo hello; sleep 10"
    }
  ]
}
```

**Comment by yqwang-ms** [comment]
BTW, if the whole job is completed, please use the frameworkCompletedTimestamp as all null containerCompletedTimestamp.
We may refine it later.

**Comment by weiranzhixin** [comment]
thanks, I have another question:
in the job I mentioned,
IF
*  `hello_cluster1`'s command is `sleep 10` 
*  `hello_cluster2`'s command is `sleep 1000`

How long  can the job run ?  
10< duration < 1000  or duration > 1000 ?

**Comment by yqwang-ms** [comment]
@weiranzhixin , close this now, if you have more questions please go to:
https://github.com/Microsoft/pai/blob/master/docs/stackoverflow.md
:)
