### ISSUE TITLE
Deployment issue (single box deploy)

### ISSUE THREAD

**Issue by Dorumpir** [Microsoft/pai#1070]
I followed [this doc](https://github.com/Microsoft/pai/blob/master/pai-management/doc/cluster-bootup.md#singlebox) to deploy a single node training platform via dev-box on dockerhub. But it seems all of the k8s-deployment and pai-service are  in their pending state:

![image](https://user-images.githubusercontent.com/10161780/44075560-c1c6b6e4-9fcf-11e8-82fd-2dceeaa943f7.png)
![image](https://user-images.githubusercontent.com/10161780/44075498-949c7762-9fcf-11e8-9392-56ce242053e0.png)
![image](https://user-images.githubusercontent.com/10161780/44075692-4e403dde-9fd0-11e8-81c7-693c0e6327c3.png)

While the rest services work well and I can visit pai through <master>:9286

**Comment by YitongFeng** [comment]
Could you please provide other pending deployment's "kubectl describe" message for more info?

Are you the first time to deploy PAI on this single-box?

Could you please provide the return message after run the following commands:
`kubectl get nodes -o yaml | grep '\sname\|cpu\|memory' `
`kubectl get nodes -o json | jq '.items[] | {name: .metadata.name, cap: .status.capacity}' `

**Comment by Dorumpir** [comment]
I am a newcomer to pai, and this is truly my first time deploying.

![image](https://user-images.githubusercontent.com/10161780/44128600-6e96ee10-a076-11e8-8c41-1b1da5ffe038.png)
![image](https://user-images.githubusercontent.com/10161780/44128605-74b88916-a076-11e8-9132-3bf2bc0f5303.png)


And following are the description messages:

![image](https://user-images.githubusercontent.com/10161780/44128612-8288c416-a076-11e8-953a-a43417375411.png)
![image](https://user-images.githubusercontent.com/10161780/44128615-8678c7b0-a076-11e8-8f4f-4d776687a487.png)
![image](https://user-images.githubusercontent.com/10161780/44128630-9e561d24-a076-11e8-9bba-397d7c60357e.png)
![image](https://user-images.githubusercontent.com/10161780/44128639-a295100c-a076-11e8-975d-136ef74273e9.png)

**Comment by YitongFeng** [comment]
Could you please provide some pending pods' info?
` kubectl get pods | grep Pending`
` kubectl describe pod ${your_pod_name} `

**Comment by Dorumpir** [comment]
![image](https://user-images.githubusercontent.com/10161780/44140002-679c0d40-a0ab-11e8-8f9f-314e439c0fe7.png)
![image](https://user-images.githubusercontent.com/10161780/44140016-70e63e20-a0ab-11e8-84fd-a8d30e5a8f28.png)
![image](https://user-images.githubusercontent.com/10161780/44140045-8c4d3fe2-a0ab-11e8-8d61-4d1c011a8f1c.png)
![image](https://user-images.githubusercontent.com/10161780/44140075-9bc78b3a-a0ab-11e8-999a-efcca1f29d8f.png)
![image](https://user-images.githubusercontent.com/10161780/44140088-aa6bd63c-a0ab-11e8-8331-43baaad5336b.png)

**Comment by YitongFeng** [comment]
No error events in these description info.
Can you access the k8s dashboard http://192.168.172.49:9090 , and take a look at the log:
![image](https://user-images.githubusercontent.com/11583225/44140686-627ae5be-a0ad-11e8-94ae-d9b41e5d885f.png)

![image](https://user-images.githubusercontent.com/11583225/44140749-a3e7d5e8-a0ad-11e8-8ac0-ed41e8d3dfce.png)

**Comment by Dorumpir** [comment]
The k8s dashboard is also in pending state
![image](https://user-images.githubusercontent.com/10161780/44141403-9fcf16ae-a0af-11e8-88ce-3ff991babf54.png)
Right now I can only visit through :9286
![image](https://user-images.githubusercontent.com/10161780/44141644-488bc742-a0b0-11e8-96d9-a9037123cd41.png)

**Comment by YitongFeng** [comment]
Could you please run `kubectl get events` ?

If no useful information, please take a look at the kubelet log, **at your host, not your dev-box**, run:
`sudo docker logs kubelet`
to see if there are any error logs?

**Comment by Dorumpir** [comment]
With `sudo docker logs kubelet` command, it turns out that on my pc the kube-schduler image had not been pulled successfully which blocked the following operations. 

Now it works fine as I expected. 

---
While there seems some extra logs in kubelet:
![image](https://user-images.githubusercontent.com/10161780/44185788-32fda100-a148-11e8-8483-afd6822999ce.png)
and there is a completed pod in my cluster, is that normal?
![image](https://user-images.githubusercontent.com/10161780/44187319-12851500-a14f-11e8-8d64-eb6700454310.png)

**Comment by YitongFeng** [comment]
The kubelet message is info, not error or warning.
And the pod is one-time job, it's normal.

**Comment by Dorumpir** [comment]
Sincerely thank you for your patience in answering.
