### ISSUE TITLE
Is the frequent retry of the job normal?

### ISSUE THREAD

**Issue by qyyy** [Microsoft/pai#1072]
I have run a job for about 40 days, and it retried 10 times during the running time. So, is it normal? And another two uses also say that their jobs are retried frequently. The jobs url are following.
http://10.151.40.179/view.html?jobName=kafka_new_server
http://10.151.40.179/view.html?jobName=train_yada
http://10.151.40.179/view.html?jobName=jupyter_server

**Comment by mzmssg** [comment]
Node manager restart frequently because Prod bed suffers diskpressure recently. Can you try it on int bed to verify it?

**Comment by YanjieGao** [comment]
Hi @yqwang-ms ,  how could user get history retry job log to find the root cause of retry?

**Comment by yqwang-ms** [comment]
If the Framework retried many times, check other attempts by searching the FrameworkName in the YARN Web:
![image](https://user-images.githubusercontent.com/32826762/44142508-ef45a79a-a0b2-11e8-9408-2fbc5c78b26b.png)

**Comment by fanyangCS** [comment]
You can find one of the failed job here: http://10.151.40.179:8188/applicationhistory/logs/10.151.40.191:8041/container_e9884_1534124332808_0267_01_000002/container_e9884_1534124332808_0267_01_000002/yuqian/stdout/?start=0

*** longjmp causes uninitialized stack frame ***: /bin/bash terminated

**Comment by YanjieGao** [comment]
Supplement:
YARN page URL: http://master_ip/yarn/ or http://master_ip:8088

**Comment by qyyy** [comment]
The "kafka_new_server" job have retried for 10 times, but why there are only two failed item in yarn page?

**Comment by qyyy** [comment]
In the container log, I found that these jobs are retied because of the following reasons.
kafka_server:
/pai/bootstrap/docker_bootstrap.sh: line 159:   700 Terminated
/bin/bash ./kafka/new_start.sh
*** longjmp causes uninitialized stack frame ***: /bin/bash terminated
train_yada:
/pai/bootstrap/docker_bootstrap.sh: line 159:   704 Terminated              sleep 10000000
*** longjmp causes uninitialized stack frame ***: /bin/bash terminated
[DEBUG] EXIT signal received in docker container, exiting ...
jupyter_server
[DEBUG] EXIT signal received in docker container, exiting ...
[C 05:35:31.797 NotebookApp] received signal 15, stopping
[32m[I 05:35:31.798 NotebookApp](B[m Shutting down 0 kernels

**Comment by yqwang-ms** [comment]
It is the result, not the root cause, as we said before, the retry is because:

> Recently, node manager often restart because Prod bed suffers diskpressure, which would lead job retry. 

![image](https://user-images.githubusercontent.com/32826762/44249844-5dbd2780-a224-11e8-826c-561c183bbe17.png)

**Comment by qyyy** [comment]
So, how to know the reason?

**Comment by yqwang-ms** [comment]
Node diskpressure  -> All the container on the node is killed by k8s or OS -> Your job failed and retried.
For how to debug by yourself, please see YanjieGao's reply.

**Comment by yqwang-ms** [comment]
BTW, you do not need to care about the 

> [ExitType]: TRANSIENT_NORMAL
failures, because it means the failure is transient and mostly due to our platform issues.

**Comment by qyyy** [comment]
I mean, why do we know that the reason is disk pressure other than other reasons, like OOM, etc.

**Comment by yqwang-ms** [comment]
disk pressure mesage is we got from K8S dashboard, i.e. http://10.151.40.179:9090/#!/workload?namespace=default

**Comment by qyyy** [comment]
You mean that we have already known the disk pressure and we have found that my job retry happened just during the same time, so the reason is disk pressure? At least the most possible reason.

**Comment by YanjieGao** [comment]
@qyyy for your question:
We could classify job retry to 2 types (1 openpai system cause (pai operator's duties) 2 job itself cause (job user‘ Duties)):
your job shows is type 1 retry

1 openpai system cause:
identify by below image am log:
![image](https://user-images.githubusercontent.com/5576848/44251784-41bd8400-a22c-11e8-98d0-9990c0c315e1.png)
Solver: pai operator's responsibility to solve this.
If you want to debug and take responsibility.
How to debug: 
Please refer pai this doc to diagnosing the problem of service [refer history log and monitor info]
https://github.com/Microsoft/pai/blob/master/pai-management/doc/cluster-bootup.md#problem

2 job self reason:
This need you to debug job by am log (above image) and each task container log.

**Comment by yqwang-ms** [comment]
Yep, it is known issue. So, we are sure it is retried because of disk pressure.
If you want to debug from scratch see previous YanjieGao reply, maybe you need to check K8S logs and YARN NM logs
