### ISSUE TITLE
Configured for YARN 2.9.0 but 2.7.2 installed

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#1086]
Using the latest master branch, set 'hadoop-version: 2.9.0' in `services-configuration.yaml`, but version 2.7.2 installed.

**Comment by hao1939** [comment]
Hi @mzmssg ,

From my view, configuration should work as expected, or we should remove the configuration entry.

**Comment by wangcan0329** [comment]
1). 'hadoop-version' in services-configuration.yaml means if we can't find hadoop-ai path then we will download An official hadoop with this hadoop-version.
2). And do you build and push hadoop-run:latest image before you deploy service?

**Comment by wangcan0329** [comment]
already remove  'hadoop-version' in services-configuration.yaml.
