### ISSUE TITLE
serving.tensorflow.json example does not work

### ISSUE THREAD

**Issue by scarlett2018** [Microsoft/pai#1087]
https://github.com/Microsoft/pai/blob/master/examples/serving/serving.tensorflow.json

I ran the example with this job: http://10.151.40.179:9286/view.html?jobName=tensorflow-serving-1 and failed.

**Comment by Asakuri** [comment]
some neccesary conponents are not installed in the docker image.

**Comment by Asakuri** [comment]
https://github.com/Microsoft/pai/pull/1109
