### ISSUE TITLE
Azure Support

### ISSUE THREAD

**Issue by BinZone** [Microsoft/pai#1091]
Is there any plan to support Azure or just release Azure X  as a service for us. That would help a lot.

**Comment by BinZone** [comment]
And maybe we could just base on HDInssight to do that.

**Comment by scarlett2018** [comment]
Thanks @BinZone for raising the request, may you be more specific on what's kind of support is needed here? A sample scenario would be great help. Thanks.

**Comment by fanyangCS** [comment]
@BinZone OpenPAI can run on Azure. You can create a set of VMs, and deploy OpenPAI to the VMs as if it is an on-prem cluster. For the Azure X as a service, I assume you would like to have something like Azure quickstart template? As @scarlett2018 says, it would be great to elaborate more in this regard.

**Comment by scarlett2018** [comment]
@BinZone - I'm closing the ticket as the information is too rough to be understand. Please feel free to reopen it with more specific and clear scenario.

**Comment by BinZone** [comment]
> @BinZone OpenPAI can run on Azure. You can create a set of VMs, and deploy OpenPAI to the VMs as if it is an on-prem cluster. For the Azure X as a service, I assume you would like to have something like Azure quickstart template? As @scarlett2018 says, it would be great to elaborate more in this regard.
Sorry for the late of the reply. Basically, we just want to deploy OpenPAI by using the Azure Resource Manager template, or if you would provide OpenPAI in the Azure marketplace. and BTW, when we deployed it to Azure, we found that the dashboard can't display the Grafana information because it using the internal IP address, not the public IP address.
