### ISSUE TITLE
about submit job

### ISSUE THREAD

**Issue by damon008** [Microsoft/pai#1105]
when I submit a job,I hope image is a optional one,not text,is a select label，How can I do?

**Comment by mzmssg** [comment]
I'm not sure whether fully understand your question. Do you mean you want to fill `image` field with a 'radio button' instead of `text`? Please give more info to help resolve it,  an example is better.

**Comment by mzmssg** [comment]
I think you have a few candidate images, and you want user can only choose one from them, rather than use any image as they want?

**Comment by damon008** [comment]
I can provide images，user only can choose one of them,but the page is created by a plug-in, I cannot know how to use a select label

**Comment by damon008** [comment]
@mzmssg ?

**Comment by damon008** [comment]
How can I do?

**Comment by damon008** [comment]
In the Schema,how to give dynamic value to the enum ?

**Comment by Gerhut** [comment]
You could build the schema and the form just after enum items are ready.

**Comment by damon008** [comment]
@Gerhut  
image: {
      type: "string",
      propertyOrder: 101,
      enum:["111","2222"],
      description: "URL pointing to the Docker image for all tasks in the job",
    },
I add enum property, the value:"111","2222", but how can I give dynamic value to the enum?

**Comment by Gerhut** [comment]
You could make the schema as a function, with image options as a parameter, and load the editor after the image options were loaded.

**Comment by fanyangCS** [comment]
no further info in a month. close it.
