### ISSUE TITLE
How about rewrite the templates of rest-server with python?

### ISSUE THREAD

**Issue by xwzheng1020** [Microsoft/pai#1114]
The templates in https://github.com/Microsoft/pai/tree/master/rest-server/src/templates are wrote with shell. Maybe they are too long to maintain and add new features. How about rewrite them with python?

**Comment by fanyangCS** [comment]
can you elaborate more in details about what new features you would like to add?

**Comment by xwzheng1020** [comment]
For example, we want to store the user's public key into mysql and pull it from the database when the sshd service is started.
https://github.com/Microsoft/pai/blob/master/rest-server/src/templates/dockerContainerScript.mustache#L64

**Comment by xwzheng1020** [comment]
Previously, we changed storage from HDFS to NFS, and removed the dependency of users' image on hadoop . In the process, we encountered some bugs that took a lot of effort to find out why.
For us, python will be easier to maintain.

**Comment by fanyangCS** [comment]
ssh key generation will be moved to js implementation in rest-server, so the footprint of the template will be smaller in the future. we welcome contribution, if you want you can go ahead to send PR to us in this part. If you feel some implementation in shell script is complicated, one way is to implement it python can call the python script from shell.

**Comment by xwzheng1020** [comment]
Yes, mixed programming is a better way. We will try, thanks.
