### ISSUE TITLE
the release version of the current deployment

### ISSUE THREAD

**Issue by fanyangCS** [Microsoft/pai#1122]
How does an operator know which pai version the cluster runs on? Can you show version number somewhere in web portal?

**Comment by Gerhut** [comment]
Generally, there are 2 ways for show the version of current project.

1. For shell users, we could overwrite the `Server` header of pylon, currently it's `nginx/1.13.8`, may be set to `pai/a.b.c`.
2. For web users, we could add a version footer or an about page in web portal.

**Comment by fanyangCS** [comment]
Thanks. Please create a work item to track this feature then.
