### ISSUE TITLE
HDFS can't automatically quit 'safemode' after `paictl.py stop ...`, `paictl.py start ...`

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#1128]
Steps:
1. a health PAI cluster
2. uninstall PAI services via `paictl.py stop ...` 
3. reinstall PAI services via 'paictl.py start ...`
4. then launcher can't start, says: 

> Cannot create directory /Launcher. Name node is in safe mode. 
> The reported blocks 390 needs additional 17 blocks to reach the threshold 0.9990 of total blocks 407. 
> The number of live datanodes 9 has reached the minimum number 0. Safe mode will be turned off automatically once the thresholds have been reached.

**Comment by DongZhaoYu** [comment]
Can this happens rarely or often? 
This can be caused by block corruption or the data node is not fully started. 
You can run command "hadoop dfsadmin -safemode leave" to leave safemode forcefully.

**Comment by hao1939** [comment]
I haven't encountered the situation recently.
