### ISSUE TITLE
`hadoop-run` process sleeping cause `paictl.py` hang forever

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#1134]
When I try to run `paictl.py cluster k8s-clean`, I found the script hang forever, and won't response to `ctrl+c' signal.

Here's what I found:
1. running `paictl.py cluster k8s-clean ...`
2. the script hang on the node '10.151.41.18', while executing the cmd `apt-get install -y gawk`

> root@stcal-121:/pai/pai-management# ./paictl.py cluster k8s-clean -p /cluster-configuration
> ...
> 2018-08-23 13:10:47,169 [INFO] - paramiko.transport : Connected (version 2.0, client OpenSSH_7.2p2)
> 2018-08-23 13:10:48,060 [INFO] - paramiko.transport : Authentication (password) successful!
> 2018-08-23 13:10:48,604 [INFO] - k8sPaiLibrary.maintainlib.common : Executing the command on host [10.151.41.18]: sudo ./clean/kubernetes-cleanup.sh
> Reading package lists... Done
> Dependency tree... 50%
> Building dependency tree
> Reading state information... Done
> gawk is already the newest version (1:4.1.3+dfsg-0.1).
> The following packages were automatically installed and are no longer required:
>   linux-azure-headers-4.15.0-1013 linux-azure-headers-4.15.0-1014
>   linux-azure-headers-4.15.0-1018 linux-azure-tools-4.15.0-1013
>   linux-azure-tools-4.15.0-1014 linux-azure-tools-4.15.0-1018
>   linux-headers-4.15.0-1013-azure linux-headers-4.15.0-1014-azure
>   linux-headers-4.15.0-1018-azure linux-image-4.15.0-1013-azure
>   linux-image-4.15.0-1014-azure linux-image-4.15.0-1018-azure
>   linux-modules-4.15.0-1013-azure linux-modules-4.15.0-1014-azure
>   linux-modules-4.15.0-1018-azure linux-tools-4.15.0-1013-azure
>   linux-tools-4.15.0-1014-azure linux-tools-4.15.0-1018-azure
> Use 'sudo apt autoremove' to remove them.
> 0 upgraded, 0 newly installed, 0 to remove and 34 not upgraded.
> 2 not fully installed or removed.
> After this operation, 0 B of additional disk space will be used.
> Setting up scx (1.6.3.659) ...

3. login in the node '10.151.41.18', try `apt-get install -y gawk`, quit because of can't acquire 'apt-lock'.
4. try the `ps -ef`, `sudo docker inspect 873f2e80bdad(The container of hadoop-run)`, the shell hangs forever.
5. try the `strace ps -ef`, it hangs while reading `/proc/12502/cmdline`:

> ...
> stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=127, ...}) = 0
> stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=127, ...}) = 0
> write(1, "root     12385 13134  0 07:54 ? "..., 71root     12385 13134  0 07:54 ?        00:00:00 [nvidia-smi] <defunct>
> ) = 71
> stat("/proc/12502", {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
> open("/proc/12502/stat", O_RDONLY)      = 6
> read(6, "12502 (java) S 11749 11435 11435"..., 2048) = 201
> close(6)                                = 0
> open("/proc/12502/status", O_RDONLY)    = 6
> read(6, "Name:\tjava\nUmask:\t0022\nState:\tS "..., 2048) = 1307
> close(6)                                = 0
> open("/proc/12502/cmdline", O_RDONLY)   = 6
> read(6,

6, try to run `cat /proc/12502/cmdline`, it hangs too.
7. run `cat /proc/12502/status`, found it's a sleeping java process:

> core@paigcr-a-gpu-1112:~$ cat /proc/12502/status
> Name:   java
> Umask:  0022
> State:  S (sleeping)
> Tgid:   12502
> Ngid:   0
> Pid:    12502
> PPid:   11749
> TracerPid:      0
> Uid:    0       0       0       0
> Gid:    0       0       0       0
> FDSize: 512
> Groups:
> NStgid: 12502
> NSpid:  12502
> NSpgid: 11435
> NSsid:  11435
> VmPeak:  6376172 kB
> VmSize:  6310636 kB
> VmLck:         0 kB
> VmPin:         0 kB
> VmHWM:    601844 kB
> VmRSS:    601844 kB
> RssAnon:          578360 kB
> RssFile:           23484 kB
> RssShmem:              0 kB
> VmData:  2544532 kB
> VmStk:       136 kB
> VmExe:         4 kB
> VmLib:     18940 kB
> VmPTE:      1816 kB
> VmSwap:        0 kB
> HugetlbPages:          0 kB
> CoreDumping:    0
> Threads:        146
> SigQ:   97/902715
> SigPnd: 0000000000000000
> ShdPnd: 0000000000000000
> SigBlk: 0000000000000000
> SigIgn: 0000000000000000
> SigCgt: 2000000181005ccf
> CapInh: 0000003fffffffff
> CapPrm: 0000003fffffffff
> CapEff: 0000003fffffffff
> CapBnd: 0000003fffffffff
> CapAmb: 0000000000000000
> NoNewPrivs:     0
> Seccomp:        0
> Speculation_Store_Bypass:       vulnerable
> Cpus_allowed:   ffffff
> Cpus_allowed_list:      0-23
> Mems_allowed:   00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000003
> Mems_allowed_list:      0-1
> voluntary_ctxt_switches:        21
> nonvoluntary_ctxt_switches:     2

8. and we can found the ppid is 11749, then run `cat /proc/11749/cmdline`:
> cat /proc/11749/cmdline
> /bin/bash./start_service.sh

So it's our hadoop-run container process hanging. Don't know the cause now.

**Comment by mzmssg** [comment]
Does it still hangs now, or can be reproduced on that node?

**Comment by YanjieGao** [comment]
Is it the k8s shows the same state? https://github.com/Microsoft/pai/issues/1152
