### ISSUE TITLE
admin can not change another admin's VCs

### ISSUE THREAD

**Issue by xudifsd** [Microsoft/pai#1137]
Since admin will have full access right to all VCs, admin cannot change another admin‘s VC setting.

But I can change it with result 'success', but after refresh, all VC will be back.

I expect either disable change button to other admin or indicate change failed.

**Comment by fanyangCS** [comment]
what do you mean by "change another VCs"? cannot stop the jobs?

**Comment by xudifsd** [comment]
I mean update other user's virtual cluster
![image](https://user-images.githubusercontent.com/665253/44566241-02001a80-a79f-11e8-87cb-a28974154aca.png)

**Comment by Gerhut** [comment]
As every user has their own accessible virtual clusters, admin users' operations will not checking them, so changing admin users' accessible virtual clusters is useless and confusing.
Will disable this API of admin user in REST server.
