### ISSUE TITLE
CancelRequest not implemented

### ISSUE THREAD

**Issue by kenqxcheng** [Microsoft/pai#1158]
![image](https://user-images.githubusercontent.com/4695796/44652195-e5bde100-aa1d-11e8-84af-28a47755a3ef.png)

**Comment by kenqxcheng** [comment]
Singlebox deploy
run command  python paictl.py cluster k8s-bootup  -p ~/pai-config
what reason?

**Comment by YanjieGao** [comment]
this log is shown from  "            res = common.execute_shell_return("kubectl get node", "There will be a delay after installing, please wait.")
"

Seems kubectl's problem
Pls test cmd "kubectl get node" over that node. And the kubectl is pai installed or the node contains previous kubectl.

**Comment by kenqxcheng** [comment]
Hi YanjieGao,
The problem is solved, but a new problem has arisen.
![image](https://user-images.githubusercontent.com/4695796/44702193-d04fc200-aac4-11e8-966c-03fb99097766.png)

**Comment by kenqxcheng** [comment]
yes, but I use cmd  "kubectl delete daemonset kube-proxy -n kube-system" The problem does not appear.
new progblem:
![image](https://user-images.githubusercontent.com/4695796/44702808-c7acbb00-aac7-11e8-93ff-7315a0c33038.png)
I use the same method to delete “kubernetes-dashboard”. retry the deploy, But the first question appears again.

**Comment by YanjieGao** [comment]
please "paictl.py cluster k8s-clean -p /path/to/cluster-configuration/dir" clean all k8s deployment, then retry the deployment of k8s

**Comment by kenqxcheng** [comment]
Thanks,  k8s is running,
but openpai/drivers container not running.
nvidia-drivers-version I change 396.44 ,  Does it work?
![image](https://user-images.githubusercontent.com/4695796/44704671-d3e84680-aace-11e8-85a9-f2e4889fff74.png)

**Comment by kenqxcheng** [comment]
Nvidia drivers logs
![image](https://user-images.githubusercontent.com/4695796/44704978-d6976b80-aacf-11e8-8fbc-6e27e0a98ff6.png)

**Comment by YanjieGao** [comment]
hi @ydye , once i meet this, hands on comment start.sh and stop.sh for driver-one-shot service to avoid driver install. Do we have a better way to work around this?
