### ISSUE TITLE
50070 port took by api-server connection, 'hadoop-name-node is not ready yet. Please wait for a moment!'

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#1160]
1. When run `paictl.py service start ...`, hadoop-name-node keeping restarting.

2. Check hadoop-name-node pod logs, found:

> 18/08/27 09:43:30 ERROR namenode.NameNode: Failed to start namenode.
> java.net.BindException: Port in use: 0.0.0.0:50070
>         at org.apache.hadoop.http.HttpServer2.constructBindException(HttpServer2.java:1015)
>         at org.apache.hadoop.http.HttpServer2.bindForSinglePort(HttpServer2.java:1037)
>         at org.apache.hadoop.http.HttpServer2.openListeners(HttpServer2.java:1094)
>         at org.apache.hadoop.http.HttpServer2.start(HttpServer2.java:951)
>         at org.apache.hadoop.hdfs.server.namenode.NameNodeHttpServer.start(NameNodeHttpServer.java:176)
>         at org.apache.hadoop.hdfs.server.namenode.NameNode.startHttpServer(NameNode.java:889)
>         at org.apache.hadoop.hdfs.server.namenode.NameNode.initialize(NameNode.java:725)
>         at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:953)
>         at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:932)
>         at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1673)
>         at org.apache.hadoop.hdfs.server.namenode.NameNode.main(NameNode.java:1741)
> Caused by: java.net.BindException: Address already in use
>         at sun.nio.ch.Net.bind0(Native Method)
>         at sun.nio.ch.Net.bind(Net.java:433)
>         at sun.nio.ch.Net.bind(Net.java:425)
>         at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
>         at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
>         at org.mortbay.jetty.nio.SelectChannelConnector.open(SelectChannelConnector.java:216)
>         at org.apache.hadoop.http.HttpServer2.bindListener(HttpServer2.java:1002)
>         at org.apache.hadoop.http.HttpServer2.bindForSinglePort(HttpServer2.java:1033)
>         ... 9 more
> 18/08/27 09:43:30 INFO util.ExitUtil: Exiting with status 1: java.net.BindException: Port in use: 0.0.0.0:50070
> 18/08/27 09:43:30 INFO namenode.NameNode: SHUTDOWN_MSG:
> /************************************************************
> SHUTDOWN_MSG: Shutting down NameNode at localhost/127.0.0.1
> ************************************************************/

3. On the node manager host, check the port 50070.

core@k8s-worker02:~$ sudo netstat -anop|grep 50070

> tcp        0      0 10.0.1.6:8080           10.0.1.6:50070          ESTABLISHED 94951/kube-apiserve keepalive (11.89/0/                0)
> tcp        0      0 10.0.1.6:50070          10.0.1.6:8080           ESTABLISHED 95055/kube-schedule keepalive (12.27/0/                0)

Conclusion:
One connection of api-server take the port 50070, so node manager can't listen on the port.

**Comment by hao1939** [comment]
Here's example:
http://40.76.53.138:33080/blue/organizations/jenkins/pai/detail/zimiao%2Fjenkins_fix/9/pipeline/58

This job was hanging on 'hadoop-name-node is not ready yet. Please wait for a moment!', and quit after manually kill the connection which take the port '50070'.

**Comment by hao1939** [comment]
Here's an answer on stackoverflow: https://unix.stackexchange.com/a/106454/118948

> To ensure the kernel won't give out 49000 and 49001 to clients as you wish to use them for your servers on linux.
> 
> sysctl -w net.ipv4.ip_local_reserved_ports = 49000, 49001
> drop it in /etc/sysctl.conf, and then run sysctl -p.

**Comment by YanjieGao** [comment]
is it better each service consider add a container prestart hook to check the static configured port available? Then each self process the port conflict issue
http://jagadesh4java.blogspot.com/2018/05/kubernetes-container-life-cycle.html

**Comment by fanyangCS** [comment]
Here is a related issue. https://github.com/Microsoft/pai/issues/113

**Comment by hao1939** [comment]
We are going to assign a new port for it, for example 5070.

**Comment by DongZhaoYu** [comment]
HDFS ports are changed in https://github.com/Microsoft/pai/pull/1337 to avoid conflicts with k8s.
