### ISSUE TITLE
[watchdog] "python: can't open file '/watchdog.py': [Errno 2] No such file or directory"

### ISSUE THREAD

**Issue by YanjieGao** [Microsoft/pai#1175]
Hi di,

I deploy use lastest or v0.6.1 watchdog image meet this error:

![image](https://user-images.githubusercontent.com/5576848/44702674-21f94c00-aac7-11e8-8248-59777fa02f27.png)

![image](https://user-images.githubusercontent.com/5576848/44702706-4c4b0980-aac7-11e8-918f-2826924642a2.png)

**Comment by xudifsd** [comment]
Which branch are you using when doing deployment, it's incompatible to use latest branch to deploy v0.6.1 branch. Since I cahnged watchdog binary location in [here](https://github.com/Microsoft/pai/commit/cf1b6f2#diff-ce4b4dfe26e056a2b4b8aed33126e40bR53)

**Comment by YanjieGao** [comment]
i use aks-test branch (once folked) and use latest docker image also meet this. is this file will copied to image or use local branch do local copy?

**Comment by YanjieGao** [comment]
I see, i will change the watchdog-ds.yaml's entry python file path

**Comment by xudifsd** [comment]
Oh, I didn't pushed image to docker hub, binary in latest image should still be in `/usr/local`.
