### ISSUE TITLE
What is the purpose of volume “/var/lib/docker” in node-exporter

### ISSUE THREAD

**Issue by ydye** [Microsoft/pai#1185]
Can we remove it?

https://github.com/Microsoft/pai/blob/4af6efa996ed6499751f5027d438335b362c7c1e/pai-management/bootstrap/prometheus/node-exporter-ds.yaml.template#L145

**Comment by YanjieGao** [comment]
gpu-exporter use docker stats / docker inspect cmd. If remove this path these 2 cmd could work, it is better to rm the path

**Comment by ydye** [comment]
I will create a PR to rm all the path from our service configuration.

**Comment by YanjieGao** [comment]
@xudifsd could help to double confirm this

**Comment by ydye** [comment]
#1188 @YanjieGao @xudifsd @hao1939

**Comment by ydye** [comment]
Because every node in the cluster may have a different docker daemon configuration. And its hard to make all pod from a deployment or daemonSet to mount the right path. So I wanna remove them as much as we can.

**Comment by ydye** [comment]
I will write a script to find the correct path on each node for kubelet.sh. I think it’s easy to do that. Because the kubelet container is started by our shell script.

**Comment by ydye** [comment]
@mzmssg To ensure whether this change will block your yarn's docker runtime.

**Comment by xudifsd** [comment]
I checked that the removal for node-exporter is ok.
