### ISSUE TITLE
`paictl.py service start ...` failed, because of `Error from server: etcdserver: request timed out`

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#1189]
It happens several times, here's one: http://40.76.53.138:33080/blue/organizations/jenkins/pai/detail/zhaoyu%2Fhdfs_access/2/pipeline/59

> 2018-08-28 15:39:48,623 [INFO] - paiLibrary.paiService.service_management_start : Begin to generate service hadoop-name-node's template file
> 2018-08-28 15:39:48,623 [INFO] - paiLibrary.paiService.service_template_generate : Begin to generate the template file in service hadoop-name-node's configuration.
> 2018-08-28 15:39:48,623 [INFO] - paiLibrary.paiService.service_template_generate : Create template mapper for service hadoop-name-node.
> 2018-08-28 15:39:48,623 [INFO] - paiLibrary.paiService.service_template_generate : Done. Template mapper for service hadoop-name-node is created.
> 2018-08-28 15:39:48,624 [INFO] - paiLibrary.paiService.service_template_generate : Generate the template file bootstrap/hadoop-name-node/node-label.sh.template.
> 2018-08-28 15:39:48,624 [INFO] - paiLibrary.paiService.service_template_generate : Save the generated file to bootstrap/hadoop-name-node/node-label.sh.
> 2018-08-28 15:39:48,628 [INFO] - paiLibrary.paiService.service_template_generate : Generate the template file bootstrap/hadoop-name-node/hadoop-name-node.yaml.template.
> 2018-08-28 15:39:48,628 [INFO] - paiLibrary.paiService.service_template_generate : Save the generated file to bootstrap/hadoop-name-node/hadoop-name-node.yaml.
> 2018-08-28 15:39:48,632 [INFO] - paiLibrary.paiService.service_template_generate : Generate the template file bootstrap/hadoop-name-node/stop.sh.template.
> 2018-08-28 15:39:48,632 [INFO] - paiLibrary.paiService.service_template_generate : Save the generated file to bootstrap/hadoop-name-node/stop.sh.
> 2018-08-28 15:39:48,634 [INFO] - paiLibrary.paiService.service_template_generate : Generate the template file bootstrap/hadoop-name-node/refresh.sh.template.
> 2018-08-28 15:39:48,635 [INFO] - paiLibrary.paiService.service_template_generate : Save the generated file to bootstrap/hadoop-name-node/refresh.sh.
> 2018-08-28 15:39:48,638 [INFO] - paiLibrary.paiService.service_template_generate : Generate the template file bootstrap/hadoop-name-node/delete.yaml.template.
> 2018-08-28 15:39:48,638 [INFO] - paiLibrary.paiService.service_template_generate : Save the generated file to bootstrap/hadoop-name-node/delete.yaml.
> 2018-08-28 15:39:48,641 [INFO] - paiLibrary.paiService.service_template_generate : The template file of service hadoop-name-node is generated.
> 2018-08-28 15:39:48,641 [INFO] - paiLibrary.paiService.service_management_start : Begin to start service: [ hadoop-name-node ]
> 2018-08-28 15:39:48,641 [INFO] - paiLibrary.paiService.service_start : Begin to execute service hadoop-name-node's start script.
> Error from server: etcdserver: request timed out
> 2018-08-28 15:40:12,270 [ERROR] - paiLibrary.common.linux_shell : Failed to execute the start script of service hadoop-name-node

**Comment by YitongFeng** [comment]
etcd related problem #1153

**Comment by YanjieGao** [comment]
once yundong seems meet etcd overload and throuttle request problem.
Need to view etcd logs to identify the reason.

**Comment by fanyangCS** [comment]
related. https://github.com/Microsoft/pai/issues/1153

**Comment by DongZhaoYu** [comment]
We have enabled users to configure etcd data path in cluster configuration file https://github.com/Microsoft/pai/blob/master/deployment/quick-start/kubernetes-configuration.yaml.template#L46
So users can configure the etcd to store data on an nonos disk. Close this issue.
