### ISSUE TITLE
do not login unconditionally in docker

### ISSUE THREAD

**Issue by xudifsd** [Microsoft/pai#1200]
I am adding alert management command to paictl.py, but I found `cluster_object_model_generate_service` function will log into docker registry unconditionally.

This slows command and output log
```
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded
2018-08-29 17:09:50,130 [INFO] - __main__ : docker registry login successfully
```

which is annoy. Can we add an option for not logging into docker registry?

**Comment by ydye** [comment]
I need it to get the docker credential.

**Comment by xudifsd** [comment]
I mean, we can delay that login, since not all sub command requires docker credential.

**Comment by fanyangCS** [comment]
@xudifsd , how much gain do you have by implementing this feature?

**Comment by xudifsd** [comment]
I'm not sure, maybe a few seconds of executing cmds not requiring login

**Comment by fanyangCS** [comment]
This doesn’t seem like a lot of gain IMO. I will close the issue for now. May reopen if things go otherwise .
