### ISSUE TITLE
[exporter] exporter's log rotation refactor

### ISSUE THREAD

**Issue by YanjieGao** [Microsoft/pai#1217]
Hi Di, as yundong has added log rotation for docker [doc](https://github.com/Microsoft/pai/pull/1216) 

previous workaround for exporter's log rotation could be removed. Then it is easier for operator to use k8s / or container log to debug exporter's issue.
https://github.com/Microsoft/pai/blob/f69396fa20590b66df33f755a6d19f338796d21e/prometheus/exporter/job_exporter.py#L93

**Comment by xudifsd** [comment]
sure
