### ISSUE TITLE
How to load data like code from HDFS to container?

### ISSUE THREAD

**Issue by DengZeshuai** [Microsoft/pai#1244]
For code, I upload the code in HDFS directory `/Home/admin/dcgan`, and submit job with configuration ```"codeDir": $PAI_DEFAULT_FS_URI/Home/admin/dcgan```. After create the container, the code will be copy into `/root/dcgan` in the container.

However, for dataset, I upload the code in the directory `/Home/admin/flowers` of HDFS, and configure the ```"dataDir": "$PAI_DEFAULT_FS_URI/Home/admin/flowers"```, but this dataset will not be copy into container. I want to know how can I load the data into container? 

In addition, in the past version of OpenPAI, I have put the data and code in the same directory of HDFS, and copy the directory into container, and it will work. But in the new version of OpenPAI, it will report anerror ```hdfs://master-ip:9000/Home/admin/dcgan is larger than 200MB, exit.```

**Comment by YanjieGao** [comment]
200mb check is for code dir, you'd better seperate code and data dir
![image](https://user-images.githubusercontent.com/5576848/44973208-5d47bf00-af8e-11e8-9bda-0e0dfba62fbd.png)

**Comment by DengZeshuai** [comment]
yes, in HDFS, I have separate  the code and date in the new version of  API, but the data is not load into container automatically the same as codes. I just want to know how to load data in the HDFS into container. @YanjieGao

**Comment by DengZeshuai** [comment]
I have ask Mr. Yuan Hao to solve my question，that is the data will not load into container automatically, and it need to use command `hdfs dfs -get $PAI_DATA_DIR ./data ` to load data actively.

Thanks for you help. @YanjieGao
