### ISSUE TITLE
how to remove the job "cntk-test"

### ISSUE THREAD

**Issue by boozyguo** [Microsoft/pai#1248]
Hi, I have deploy the PAI system on a single GPU server. 
And the job "cntk-test" periodly auto-submitted to the system, but the job is heavy for computing. 
So, I wonder how to remove the job after depolyed.
Thanks.

**Comment by ydye** [comment]
Remove this folder when deploying. https://github.com/Microsoft/pai/tree/master/pai-management/bootstrap/end-to-end-test

**Comment by ydye** [comment]
I believe this issue has been solved and there is no new repose in this issue for a day. So I will close it.

**Comment by boozyguo** [comment]
Thanks @ydye 
I try “./paictl.py service delete -p /path/2/conf -n end-to-end-test”
the service is stop.
