### ISSUE TITLE
[portal] getting start of dashboard's doc is not the latest version

### ISSUE THREAD

**Issue by YanjieGao** [Microsoft/pai#1252]
Hi @Gerhut @xudifsd 
, bed's doc is not the latest one?

bed's getting start:
![image](https://user-images.githubusercontent.com/5576848/44971159-1aceb400-af87-11e8-80b4-89260e090cfe.png)

master branch doc:
https://github.com/Microsoft/pai/blob/master/docs/job_tutorial.md

**Comment by Gerhut** [comment]
Looks like [docs of v0.7.1 tag](https://github.com/Microsoft/pai/blob/v0.7.1/docs/job_tutorial.md)

**Comment by YanjieGao** [comment]
hi @scarlett2018, the reason is branch v0.7.1 did not merge this new commit 
https://github.com/Microsoft/pai/blob/master/docs/job_tutorial.md
