### ISSUE TITLE
question about job's ports

### ISSUE THREAD

**Issue by boozyguo** [Microsoft/pai#1280]
Hello
when submit job from webportal, there is "portList" parameters in the config file. 
Also, when job's container run, there is "http port" and "ssh port" can be seen at webpage. 
![default](https://user-images.githubusercontent.com/20755762/45078147-cc095180-b121-11e8-8762-b1d5f84933a0.png)

So, the images how to get the portnumber in config file? And the images should map it's 22 port to "ssh port" in config file?

**Comment by hao1939** [comment]
Please refer the doc here: https://github.com/Microsoft/pai/blob/master/docs/job_tutorial.md.

For this example, in container you could access those `port number` via environment parameters:
```
$PAI_CONTAINER_HOST_ssh_PORT_LIST # it should be 14260
$PAI_CONTAINER_HOST_http_PORT_LIST # it should be 14259
```

**Comment by boozyguo** [comment]
Hi, @hao1939  Thank you for your reply.

**Comment by hao1939** [comment]
Hi @boozyguo ,

I will close this issue, feel free to reopen if you have more question.

**Comment by boozyguo** [comment]
Thanks @hao1939
