### ISSUE TITLE
[SingleBox Deploy] Error when boot up Kubernetes

### ISSUE THREAD

**Issue by TobeyQin** [Microsoft/pai#1283]
I tried to deploy PAI singlebox on Ubuntu 16.04 followed the deploy guide. But I met the error when boot up Kubernetes. Command "python paictl.py cluster k8s-bootup -p ~/pai-config" raised this error message: 
**error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.38/exec/cb76d4833f33123a1c5c8402a03bea85fd139caa0318fd8aed0ce6bd7bc33e74/json: read unix @->/var/run/docker.sock: read: connection reset by peer**

Could you help to solve this? Thanks.

**Comment by hao1939** [comment]
Hi @TobeyQin ,

I want to check whether your docker is properly installed.
Please run the command below in dev-box:
`docker info
docker ps`

**Comment by hao1939** [comment]
Hi @TobeyQin ,

For short, currently dev-box should be outside of PAI cluster nodes. So you may need to run dev-box on another machine.

There is a workaround, you could run `paictl` without `dev-box`.
And you should make sure using python 2.6 and have the below packages installed:
```
sudo apt-get -y update
sudo apt-get -y install \
      nano \
      vim \
      joe \
      wget \
      curl \
      jq \
      gawk \
      psmisc \
      python \
      python-yaml \
      python-jinja2 \
      python-paramiko \
      python-urllib3 \
      python-tz \
      python-nose \
      python-prettytable \
      python-netifaces \
      python-dev \
      python-pip \
      python-mysqldb \
      openjdk-8-jre \
      openjdk-8-jdk \
      openssh-server \
      openssh-client \
      git \
      bash-completion \
      inotify-tools \
      rsync \
      realpath \
      net-tools
pip install python-etcd docker kubernetes requests docopt
```

**Comment by hao1939** [comment]
Hi @scarlett2018 , could you take a look and decide whether we should fix this issue?

**Comment by fanyangCS** [comment]
@hao1939 , can you update the document on single-box deployment to clarify that dev-box and the single machine (to be deployed) should not be the same machine?

**Comment by TobeyQin** [comment]
@hao1939 OK. Thanks. I will try to run paictl without dev-box.

**Comment by hao1939** [comment]
@fanyangCS , sure, I create the PR #1298 .
