### ISSUE TITLE
Should we overwirte old kubectl in k8s-bootup

### ISSUE THREAD

**Issue by mzmssg** [Microsoft/pai#1285]
This is my issue:

When update cluster, it repo `unknown command "api-resources" for "kubectl"`. 
`api-resource` is a new command in kubectl 1.11, but in last `k8s-bootup`, an 1.10 kubectl is installed, and we won't install  again if detecting it, then this error occurs.

Suggestion:

Install the newest kubectl in every `k8s-bootup`

**Comment by fanyangCS** [comment]
close this issue and track in #1659.
