### ISSUE TITLE
Do you have plan to run job on K8s cluster directly?

### ISSUE THREAD

**Issue by liudongqing** [Microsoft/pai#1324]
As Spark/Tensorflow/etc support run jobs on K8s directly, do OpenPAI will support to us K8s Cluster as Job clusters (maybe another k8s cluster other than the base one)?

**Comment by fanyangCS** [comment]
We are evaluating this option. Do you have some reason to support this scenario?

**Comment by liudongqing** [comment]
The main reason is that maintaining two kinds of clusters makes the environment more complex.
