### ISSUE TITLE
Strange accidental failure of job

### ISSUE THREAD

**Issue by qyyy** [Microsoft/pai#1333]
error message: 
urllib2.HTTPError: HTTP Error 500: Internal Server Error
job url:
http://10.151.40.179/view.html?jobName=sklearn-mnist_2018-09-11_14-21-29
http://10.151.40.179/view.html?jobName=mxnet-autoencoder_2018-09-11_14-22-09
strange things:
When I run the first time by program through rest server API, the two jobs failed.
But when I submit them manually, nothing wrong.

**Comment by mzmssg** [comment]
Official MNIST data web is unstable, all these jobs failed due to it.

**Comment by qyyy** [comment]
Yes, it's the reason, thanks.

**Comment by mzmssg** [comment]
A workaround: I remember these examples will check the data path existence, you could download them to the specific path when build. Then they should skip the downloads at runtime.

**Comment by qyyy** [comment]
I have checked the unstable examples: sklearn-mnist, keras_cntk_backend_mnist, keras_tensorflow_backend_mnist, mxnet-autoencoder or tensorflow-cifar10, the data they used are all based on hard-code url. What's more, I've also checked the input parameters, there're no additional parameters like data-path. So, it seems impossible to make the data loading process stable unless change the code.

**Comment by mzmssg** [comment]
@qyyy 
Take sklean-mnist as example, it will check the dataset path, only download it when it doesn't exist, related code as below:

![image](https://user-images.githubusercontent.com/11887940/46643539-1cefe800-cbaf-11e8-81e6-86d74f402dad.png)


So you can download the mnist data to `data_home/mldata` to skip runtime download. 


More specifically, for sklearn example, you can pass the `data_home` with a env.
![image](https://user-images.githubusercontent.com/11887940/46643725-ed8dab00-cbaf-11e8-9a47-c7425438890f.png)

**Comment by qyyy** [comment]
done!
