### ISSUE TITLE
change Docker Root Dir from /var/lib/docker to /path/to/anywhere/with/enough/space failed! 

### ISSUE THREAD

**Issue by jimmy0min** [Microsoft/pai#1338]
The default Docker Root Dir is /var/lib/docker, but there is not enough disk space at the root path. 
So I  change the Docker Root Dir to somewhere else. But the cluster fails to bootup with following error:
failed create pod sandbox

the method i change the Docker Root Dir is as follow:

$ docker info
    Root Dir: /var/lib/docker/aufs
Since we're using systemd modifying the DOCKER-OPTS tag within /etc/default/docker to include -g /new/root/dir isn't going to work. There are two options, both require you to edit your docker.service file.

Pro tip: systemctl status docker.service will print the location of this file at the top of the output

Option 1 - Direct edit to docker.service
Edit ExecStart line to look like this ExecStart =/usr/bin/dockerd -g /new/docker/root/dir -H fd://
systemctl daemon-reload
systemctl restart docker
docker info - verify the root dir has updated
Option 2 - Create a systemd drop-in service file (better way)
This option is preferred as directly editing .service files should be avoided. They may be overwritten during an update for example.

vi /etc/systemd/system/docker.service.d/docker.root.conf and populate with:
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd -g /new/docker/root -H fd://
systemctl daemon-reload
systemctl restart docker
docker info - verify the root dir has updated
Note - Existing Containers and Images
If you already have containers or images in /var/lib/docker you may wish to stop and back these up before moving them to the new root location. Moving can be done by either rsync -a /var/lib/docker/* /path/to/new/root or if permissions do not matter, you can simply use mv or cp too.

**Comment by ydye** [comment]
@hao1939  
For the docker environment, maybe we should add an configuration for user to fill in. Cause the situation is too complex.

**Comment by fanyangCS** [comment]
no further input. closed.

**Comment by zlwu** [comment]
docker-machine create --driver generic  --engine-opt data-root=/path/to/your/dock/dir ...
