### ISSUE TITLE
Singlebox deploy problem,Sorry, there is no definition of the argument [config]

### ISSUE THREAD

**Issue by dxysun** [Microsoft/pai#1348]
When I follow the Singlebox deploy documentation to deploy the system,I meet a problem at the Step 2. Generate OpenPAI configuration files. Here is the error.
when I run the command `python paictl.py config generate -i /pai/pai-management/quick-start/quick-start.yaml -o ~/pai-config -f`,reported this error.
`Sorry, there is no definition of the argument [config]`
![screenshot from 2018-09-12 21-58-57](https://user-images.githubusercontent.com/16951972/45430490-018cdc80-b6d8-11e8-8377-f650f9ecba0f.png)
why the the argument [config] is error?
The doc is not right?
https://github.com/Microsoft/pai/blob/master/pai-management/doc/cluster-bootup.md#c-step-2

**Comment by fanyangCS** [comment]
which version do you use? please check out a release branch before deployment. The latest one is: https://github.com/Microsoft/pai/releases/tag/v0.7.2

**Comment by dxysun** [comment]
I use the latest one v0.7.2 version

**Comment by ydye** [comment]
@dxysun   
The command line change isn't included into the branch v0.7.2.
Please use the command following
```
paictl.py cluster generate-configuration ....
```

**Comment by ydye** [comment]
No updates have been performed since my last comment. I will close it.
