### ISSUE TITLE
submit job fail with “porttype”

### ISSUE THREAD

**Issue by boozyguo** [Microsoft/pai#1349]
hello, there is a problem about submit job with "porttype".

I test submit a job with 'porttype', but the webportal reports "bad request":
![default](https://user-images.githubusercontent.com/20755762/45461597-9a524500-b736-11e8-8c42-3760025c3256.png)

If I submit the same job without "porttype", it is ok:

![default](https://user-images.githubusercontent.com/20755762/45461624-c372d580-b736-11e8-902e-35dc8a3b5185.png)

**Comment by Gerhut** [comment]
I reproduced this issue, frameworklauncher logs 

    com.microsoft.frameworklauncher.webserver.LauncherExceptionHandler: Http request failed due to: Bad Request 
    com.microsoft.frameworklauncher.common.exceptions.BadRequestException: javax.validation.ConstraintViolationException: taskRoles[master].taskService.resource: Illegal PortDefinitions: All start fields should be nonzero or zero: PortDefinitions: [{&lt;serverport = 7000,1&gt;, &lt;http = 0,1&gt;, &lt;ssh = 0,1&gt;}]

Ping @yqwang-ms for help

**Comment by fanyangCS** [comment]
@Gerhut , could you please post the REST API log?

**Comment by yqwang-ms** [comment]
@qinchen123 to take a look.
It is by design, and below message is returned from Launcher RestAPI's body, RestServer should show them to user:
com.microsoft.frameworklauncher.common.exceptions.BadRequestException: javax.validation.ConstraintViolationException: taskRoles[master].taskService.resource: Illegal PortDefinitions: All start fields should be nonzero or zero: PortDefinitions: [{&lt;serverport = 7000,1&gt;, &lt;http = 0,1&gt;, &lt;ssh = 0,1&gt;}]

**Comment by qinchen123** [comment]
Hi Gerhut， 
our design of ports support in backend is: if have multi-port labels,  the ports for all labels either random or specified; it don't support some labels are random, some label are specified. 

for your cases, you have specified the serverport 7000,  but the webserver add too random port(http, ssh). the specified and random co-existed casued this BadRequest.  

I suggest you to use a random port for your serverport,  and after job is running, you can get the port number form the job detail view in PAI web site.

**Comment by fanyangCS** [comment]
this is a bug.

**Comment by fanyangCS** [comment]
https://github.com/Microsoft/pai/pull/1402
