### ISSUE TITLE
Support run a bunch of jobs as pipelines/workflows/DAGs. 

### ISSUE THREAD

**Issue by liudongqing** [Microsoft/pai#1357]
Do openpai currently support run jobs as pipelines with dependences among them? I see the job can contain multiple task roles, but all of them will be launched in parallel, right?

Maybe integrate Luigi in？

**Comment by fanyangCS** [comment]
pai is quite flexible, we do leverage PAI to have built some internal pipelines but currently in an ad hoc way. We focus on training experience for the moment and are evaluating the timing to work on this issue. But no official plan yet. Again, we welcome contribution.

**Comment by fanyangCS** [comment]
https://github.com/Microsoft/pai/issues/1433
