### ISSUE TITLE
node-exporter fail

### ISSUE THREAD

**Issue by leonfg** [Microsoft/pai#1366]
OpenPAI version v0.7.2
After PAI services started, the node-exporter run failed. The message is **'Readiness probe failed: python: can't open file '/usr/local/healthy_check.py': [Errno 2] No such file or directory'**.
The images 'prom/node-exporter:v0.16.0' and 'docker.io/openpai/gpu-exporter:latest' exist in each node, and containers of  openpai/gpu-exporter and prom/node-exporter are all running.

**Comment by xudifsd** [comment]
You should use version v0.7.2 in your [docker tag](https://github.com/Microsoft/pai/blob/master/cluster-configuration/services-configuration.yaml#L38), instead of latest. The latest image changes constantly.
