### ISSUE TITLE
watchdog fail

### ISSUE THREAD

**Issue by leonfg** [Microsoft/pai#1367]
OpenPAI version v0.7.2
After PAI services started, the watchdog run failed. The message is **'python: can't open file '/usr/local/watchdog.py': [Errno 2] No such file or directory'**.
The image 'openpai/watchdog' exists in each node, and the container openpai/watchdog is running.

**Comment by xudifsd** [comment]
I suspect you are using latest in your docker tag. Please change it to v0.7.2 in your service config file.
