### ISSUE TITLE
Request feature: Job template/Submit job from existing one.

### ISSUE THREAD

**Issue by liudongqing** [Microsoft/pai#1379]
It's tedious to fill the form or copy/paste json every time, if users can save job json as a template/prototype would help much. Also, we often launch similar job, if there is a button or link in the job view to let user copy the job config into job submit form would be nice.

btw, is there a list of ongoing features/roadmap for openpai?

**Comment by fanyangCS** [comment]
we are working on it. will keep you updated.

**Comment by YitongFeng** [comment]
@liudongqing In our v0.8 release we've implement the "clone job" and "export job config" features. You can see the features at job detail page then.

**Comment by liudongqing** [comment]
@YitongFeng Thanks for keeping me updated, I'd like to have a try once it was released.
