### ISSUE TITLE
duplicated job name

### ISSUE THREAD

**Issue by DongZhaoYu** [Microsoft/pai#1392]
From webportal we enforce the job names cannot be duplicated.
But the jobs submitted from openmind can have duplicated jobs. Following are two jobs they have same name.

job 1:
++[08:51:23] APP_ID=application_1535954247490_2002
++[08:51:23] FRAMEWORK_NAME=nni_edXHp
++[08:51:23] HADOOP_USER_NAME=openmindstudio
++[08:51:23] PAI_TASK_INDEX=0
++[08:51:23] PAI_CONTAINER_HOST_PORT_LIST='http:27131;ssh:27132;'
++[08:51:23] PAI_CONTAINER_ID=container_1535954247490_2002_01_000002
++[08:51:23] PAI_JOB_NAME=nni_edXHp
++[08:51:23] PAI_USER_NAME=openmindstudio
++[08:51:23] PAI_CURRENT_TASK_ROLE_NAME=nni_fei6g
++[08:51:23] PAI_CURRENT_TASK_ROLE_TASK_COUNT=1
++[08:51:23] PAI_CURRENT_TASK_ROLE_CPU_COUNT=2
++[08:51:23] PAI_CURRENT_TASK_ROLE_MEM_MB=8192
++[08:51:23] PAI_CURRENT_TASK_ROLE_SHM_MB=64
++[08:51:23] PAI_CURRENT_TASK_ROLE_GPU_COUNT=0
++[08:51:23] PAI_CURRENT_TASK_ROLE_MIN_FAILED_TASK_COUNT=1
++[08:51:23] PAI_CURRENT_TASK_ROLE_MIN_SUCCEEDED_TASK_COUNT=
++[08:51:23] PAI_CURRENT_TASK_ROLE_CURRENT_TASK_INDEX=0
++[08:51:23] PAI_JOB_TASK_COUNT=1
++[08:51:23] PAI_JOB_TASK_ROLE_COUNT=1
++[08:51:23] PAI_JOB_TASK_ROLE_LIST=nni_fei6g
++[08:51:23] PAI_CONTAINER_HOST_http_PORT_LIST=27131
++[08:51:23] PAI_CONTAINER_HOST_ssh_PORT_LIST=27132
++[08:51:23] PAI_CONTAINER_HOST_PORT=27131
++[08:51:23] PAI_CONTAINER_SSH_PORT=27132
++[08:51:23] PAI_USERNAME=openmindstudio
++[08:51:23] PAI_TASK_ROLE_NAME=nni_fei6g
++[08:51:23] PAI_TASK_ROLE_NUM=1
++[08:51:23] PAI_TASK_CPU_NUM=2
++[08:51:23] PAI_TASK_MEM_MB=8192
++[08:51:23] PAI_TASK_GPU_NUM=0
++[08:51:23] PAI_TASK_ROLE_INDEX=0
++[08:51:23] PAI_TASKS_NUM=1
++[08:51:23] PAI_TASK_ROLES_NUM=1
++[08:51:23] PAI_TASK_ROLE_LIST=nni_fei6g
++[08:51:23] PAI_CURRENT_CONTAINER_PORT=27131

job 2:
++[06:41:12] APP_ID=application_1535954247490_1972
++[06:41:12] FRAMEWORK_NAME=nni_edXHp
++[06:41:12] HADOOP_USER_NAME=openmindstudio
++[06:41:12] PAI_TASK_INDEX=0
++[06:41:12] PAI_CONTAINER_HOST_IP=10.151.40.140
++[06:41:12] PAI_CONTAINER_HOST_PORT_LIST='http:18830;ssh:18831;'
++[06:41:12] PAI_CONTAINER_ID=container_1535954247490_1972_01_000002
++[06:41:12] PAI_JOB_NAME=nni_edXHp
++[06:41:12] PAI_USER_NAME=openmindstudio
++[06:41:12] PAI_CURRENT_TASK_ROLE_NAME=nni_fei6g
++[06:41:12] PAI_CURRENT_TASK_ROLE_TASK_COUNT=1
++[06:41:12] PAI_CURRENT_TASK_ROLE_CPU_COUNT=2
++[06:41:12] PAI_CURRENT_TASK_ROLE_MEM_MB=8192
++[06:41:12] PAI_CURRENT_TASK_ROLE_SHM_MB=64
++[06:41:12] PAI_CURRENT_TASK_ROLE_GPU_COUNT=0
++[06:41:12] PAI_CURRENT_TASK_ROLE_MIN_FAILED_TASK_COUNT=1
++[06:41:12] PAI_CURRENT_TASK_ROLE_MIN_SUCCEEDED_TASK_COUNT=
++[06:41:12] PAI_CURRENT_TASK_ROLE_CURRENT_TASK_INDEX=0
++[06:41:12] PAI_JOB_TASK_COUNT=1
++[06:41:12] PAI_JOB_TASK_ROLE_COUNT=1
++[06:41:12] PAI_JOB_TASK_ROLE_LIST=nni_fei6g
++[06:41:12] PAI_CONTAINER_HOST_http_PORT_LIST=18830
++[06:41:12] PAI_CONTAINER_HOST_ssh_PORT_LIST=18831
++[06:41:12] PAI_CONTAINER_HOST_PORT=18830
++[06:41:12] PAI_CONTAINER_SSH_PORT=18831
++[06:41:12] PAI_USERNAME=openmindstudio
++[06:41:12] PAI_TASK_ROLE_NAME=nni_fei6g
++[06:41:12] PAI_TASK_ROLE_NUM=1
++[06:41:12] PAI_TASK_CPU_NUM=2
++[06:41:12] PAI_TASK_MEM_MB=8192
++[06:41:12] PAI_TASK_GPU_NUM=0
++[06:41:12] PAI_TASK_ROLE_INDEX=0
++[06:41:12] PAI_TASKS_NUM=1
++[06:41:12] PAI_TASK_ROLES_NUM=1
++[06:41:12] PAI_TASK_ROLE_LIST=nni_fei6g
++[06:41:12] PAI_CURRENT_CONTAINER_PORT=18830

The cause:  job name check is done on front end. But in job submit rest api, this check is ignored.

Do we need to fix this to keep consistent behavior?

**Comment by fanyangCS** [comment]
it was due to retry of the same job. will update job page view to link retry jobs
