### ISSUE TITLE
Job container can not access HDFS

### ISSUE THREAD

**Issue by leonfg** [Microsoft/pai#1395]
v0.7.2
Job definition:
{
  "jobName": "generate_minist_tfrecords_gf2",
  "image": "openpai/pai.example.tensorflow",
  "authFile": "",
  "dataDir": "$PAI_DEFAULT_FS_URI/gaofang/data",
  "outputDir": "$PAI_DEFAULT_FS_URI/gaofang/output",
  "codeDir": "$PAI_DEFAULT_FS_URI/gaofang/code",
  "virtualCluster": "default",
  "gpuType": "",
  "retryCount": 0,
  "taskRoles": [
    {
      "name": "generate_minist_tfrecords",
      "taskNumber": 1,
      "cpuNumber": 2,
      "memoryMB": 32768,
      "gpuNumber": 0,
      "command": "pwd && pwd && pwd && pwd && ls -al && ls / && cd $PAI_CODE_DIR"
    }
  ]
}

Execution log：
[INFO] USER COMMAND START

/root
/root
/root
/root
total 28
drwx------ 1 root root 4096 Sep 18 02:11 .
drwxr-xr-x 1 root root 4096 Sep 18 02:11 ..
-rw-r--r-- 1 root root 3106 Oct 22  2015 .bashrc
drwx------ 3 root root 4096 Sep 11 01:13 .cache
-rw-r--r-- 1 root root  148 Aug 17  2015 .profile
drwxr-xr-x 2 root root 4096 Sep 18 02:12 .ssh
drwxr-xr-x 2 root root 4096 Sep 18 02:11 code
alive  boot  etc   lib	  media  opt  proc  run   srv  tmp  var
bin    dev   home  lib64  mnt	 pai  root  sbin  sys  usr
/pai/bootstrap/docker_bootstrap.sh: line 162: cd: hdfs://192.168.11.202:9000/gaofang/code: No such file or directory
[DEBUG] Docker container exit handler: EXIT signal received in docker container, exiting ...

Diagnostics:
 [ExitStatus]: LAUNCHER_EXIT_STATUS_UNDEFINED
[ExitCode]: 177
[ExitDiagnostics]:
ExitStatus undefined in Launcher, maybe UserApplication itself failed.
[ExitType]: UNKNOWN
________________________________________________________________________________________________________________________________________________________________________________________________________
[ExitCustomizedDiagnostics]:
<Raw>[ExitCode]: 1
<Raw>[ExitDiagnostics]:
[2018-09-18 02:12:21.207]Exception from container-launch.
Container id: container_e03_1536915772726_0376_01_000002
Exit code: 1
[2018-09-18 02:12:21.207]
[2018-09-18 02:12:21.208]Container exited with a non-zero exit code 1. Error file: prelaunch.err.
Last 4096 bytes of prelaunch.err :
Last 4096 bytes of stderr :
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
100 4753 100 4753 0 0 394k 0 --:--:-- --:--:-- --:--:-- 394k
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
100 7021 100 7021 0 0 599k 0 --:--:-- --:--:-- --:--:-- 599k
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
[2018-09-18 02:12:21.210]
[2018-09-18 02:12:21.210]Container exited with a non-zero exit code 1. Error file: prelaunch.err.
Last 4096 bytes of prelaunch.err :
Last 4096 bytes of stderr :
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
100 4753 100 4753 0 0 394k 0 --:--:-- --:--:-- --:--:-- 394k
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
100 7021 100 7021 0 0 599k 0 --:--:-- --:--:-- --:--:-- 599k
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
[2018-09-18 02:12:21.210]
________________________________________________________________________________________________________________________________________________________________________________________________________
<Raw>[ExitCustomizedDiagnostics]:
[generate_minist_tfrecords]: [LastCompletedTask]: [TaskStatus]:
{
"taskIndex" : 0,
"taskRoleName" : "generate_minist_tfrecords",
"taskState" : "TASK_COMPLETED",
"taskRetryPolicyState" : {
"retriedCount" : 0,
"succeededRetriedCount" : 0,
"transientNormalRetriedCount" : 0,
"transientConflictRetriedCount" : 0,
"nonTransientRetriedCount" : 0,
"unKnownRetriedCount" : 0
},
"taskCreatedTimestamp" : 1537236676741,
"taskCompletedTimestamp" : 1537236741415,
"taskServiceStatus" : {
"serviceVersion" : 0
},
"containerId" : "container_e03_1536915772726_0376_01_000002",
"containerHost" : "192.168.11.203",
"containerIp" : "192.168.11.203",
"containerPorts" : "http:13546;ssh:13547;",
"containerGpus" : 0,
"containerLogHttpAddress" : "http://192.168.11.203:8042/node/containerlogs/container_e03_1536915772726_0376_01_000002/admin/",
"containerConnectionLostCount" : 0,
"containerIsDecommissioning" : null,
"containerLaunchedTimestamp" : 1537236678467,
"containerCompletedTimestamp" : 1537236741408,
"containerExitCode" : 1,
"containerExitDiagnostics" : "[2018-09-18 02:12:21.207]Exception from container-launch.\nContainer id: container_e03_1536915772726_0376_01_000002\nExit code: 1\n[2018-09-18 02:12:21.207]\n[2018-09-18 02:12:21.208]Container exited with a non-zero exit code 1. Error file: prelaunch.err.\nLast 4096 bytes of prelaunch.err :\nLast 4096 bytes of stderr :\n % Total % Received % Xferd Average Speed Time Time Time Current\n Dload Upload Total Spent Left Speed\n\r 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0\r 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0\n\r100 4753 100 4753 0 0 394k 0 --:--:-- --:--:-- --:--:-- 394k\n % Total % Received % Xferd Average Speed Time Time Time Current\n Dload Upload Total Spent Left Speed\n\r 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0\r 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0\n\r100 7021 100 7021 0 0 599k 0 --:--:-- --:--:-- --:--:-- 599k\nWARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.\n\n[2018-09-18 02:12:21.210]\n[2018-09-18 02:12:21.210]Container exited with a non-zero exit code 1. Error file: prelaunch.err.\nLast 4096 bytes of prelaunch.err :\nLast 4096 bytes of stderr :\n % Total % Received % Xferd Average Speed Time Time Time Current\n Dload Upload Total Spent Left Speed\n\r 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0\r 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0\n\r100 4753 100 4753 0 0 394k 0 --:--:-- --:--:-- --:--:-- 394k\n % Total % Received % Xferd Average Speed Time Time Time Current\n Dload Upload Total Spent Left Speed\n\r 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0\r 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0\n\r100 7021 100 7021 0 0 599k 0 --:--:-- --:--:-- --:--:-- 599k\nWARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.\n\n[2018-09-18 02:12:21.210]\n",
"containerExitType" : "UNKNOWN"
}
[generate_minist_tfrecords]: [LastCompletedTask]: [ContainerLocations]:
ContainerLogHttpAddress: http://192.168.11.203:8042/node/containerlogs/container_e03_1536915772726_0376_01_000002/admin/
ContainerLogNetworkPath: 192.168.11.203:/var/lib/yarn/userlogs/application_1536915772726_0376/container_e03_1536915772726_0376_01_000002
ContainerCacheNetworkPath: 192.168.11.203:/var/lib/hadoopdata/nm-local-dir/usercache/admin/appcache/application_1536915772726_0376/container_e03_1536915772726_0376_01_000002
________________________________________________________________________________________________________________________________________________________________________________________________________
[ApplicationCompletionReason]: [generate_minist_tfrecords]: FailedTaskCount 1 has reached MinFailedTaskCount 1.

**Comment by DongZhaoYu** [comment]
$PAI_CODE_DIR is the code location on HDFS. You cannot use that as a local folder.
PAI will fetch the code from HDFS to you current working dir. In your case, it is "code" dir.

**Comment by leonfg** [comment]
> 
> 
> $PAI_CODE_DIR is the code location on HDFS. You cannot use that as a local folder.
> PAI will fetch the code from HDFS to you current working dir. In your case, it is "code" dir.

There is “code” in /root, but how can I access "data" and "output"?

**Comment by DongZhaoYu** [comment]
You can access the data and output via HDFS command or APIs. You can follow this doc https://github.com/Microsoft/pai/blob/master/docs/hadoop/hdfs.md#access-hdfs-data-
