### ISSUE TITLE
Cannot use ssh even though the color of "View SSH Info" turns to blue

### ISSUE THREAD

**Issue by qyyy** [Microsoft/pai#1406]
I have met a small problem that, when I start a job with multi task roles, I cannot use ssh even though the color of "View SSH Info" has turned to blue, although I can use it after waiting for another some minutes.
I guess it due to some of the task roles has already load ssh but not all. But the system regards all the task roles are ready. Or the color of the "View SSH Info" changed before ssh ready.

Here is an [example](http://10.151.40.179/view.html?jobName=tensorflow-mpi-13)

**Comment by fanyangCS** [comment]
this is because the corresponding containers are in running state, but the ssh service did not start yet. You can see the container log for details.
