### ISSUE TITLE
about prometheus

### ISSUE THREAD

**Issue by damon008** [Microsoft/pai#1426]
I want to ask a question of prometheus，prometheus provide a API for get bandWidth of all jobs for a user, and also get these by time ranges. I find a API:
curl -g http://112.121.3.5:9091/api/v1/query?query=container_NetIn{container_label_PAI_USER_NAME=\"_e2eb9236063744fe84bba63f89f56fad\"},
but this cannot get by time ranges.

**Comment by xudifsd** [comment]
what you mean by `get by time ranges`?

**Comment by damon008** [comment]
yeah,what about the API?

**Comment by xudifsd** [comment]
Well, I mean, I do not know what `get by time ranges` means.

**Comment by xudifsd** [comment]
close due to idle for too long
