### ISSUE TITLE
prometheus-deployment Insufficient memory.

### ISSUE THREAD

**Issue by alvindaiyan** [Microsoft/pai#1454]
I've got a 10 G machine single box for deploy pai, but keep getting 

`
0/1 nodes are available: 1 Insufficient memory.
`
for prometheus deployment.

Also, when I try to start the webportal, I'm keeping get ImageInspectError for some reason. more details are:

`
Failed to inspect image "docker.io/openpai/webportal:latest": rpc error: code = Unknown desc = Error response from daemon: readlink /var/lib/docker/overlay2: invalid argument
`

Do you have any advice?

Thanks in advance

**Comment by hao1939** [comment]
Hi @alvindaiyan ,

Which version are your using?
In our latest code we reserve memory quote for each services, so the SingleBox installation would need at least 64G memory, see [https://github.com/Microsoft/pai/wiki/Resource-Requirement](resource reuqirement).

And here's a workaround, you could set the 'requests' memory for each services, by default, the `request` would equal to `limits`, which is obvious bigger.
Take the `prometheus` as an example:
https://github.com/Microsoft/pai/blob/master/src/prometheus/deploy/prometheus-deployment.yaml.template#L40

        resources:
          limits:
            memory: "256Mi"
# add a 'requests' quote
          requests:
             memory: "26Mi"

**Comment by xudifsd** [comment]
close due to idleness.
