### ISSUE TITLE
YARN's metric "GPUs Total" is wrong and always in change

### ISSUE THREAD

**Issue by YitongFeng** [Microsoft/pai#1467]
http://10.151.40.234/yarn/10.151.40.234:8088/cluster

The "GPUs Total" should be 60, for the INT bed has 63 GPUs in total, but 3 master nodes don't install NM, and there is one GPU on each of master nodes.

So currently the num of "GPUs Total" is wrong, and I found that it is always in change, sometime is 55 sometime is 56. Maybe something wrong with NM or RM?

**Comment by mzmssg** [comment]
Zombie job takes the GPU, so NM doesn't report it.

**Comment by mzmssg** [comment]
Fix in #1475
