### ISSUE TITLE
Zombie docker container

### ISSUE THREAD

**Issue by mzmssg** [Microsoft/pai#1477]
http://10.151.40.234/view.html?username=core&jobName=cntk-test-7281-29045
http://10.151.40.234/view.html?username=core&jobName=cntk-test-32111-16436
http://10.151.40.234/view.html?username=core&jobName=cntk-test-17823-30716
http://10.151.40.234/view.html?username=core&jobName=cntk-test-13837-18133
http://10.151.40.234/view.html?username=core&jobName=job-submit-10782-9665
http://10.151.40.234/view.html?username=core&jobName=cntk-test-7609-30085

All these job hang when exit
![image](https://user-images.githubusercontent.com/11887940/46794389-4741d100-cd7a-11e8-800e-31eff9506ceb.png)

**Comment by mzmssg** [comment]
A new instance:
http://10.151.40.179/view.html?username=core&jobName=cntk-test-23968-15013

Can't `exec` into it, `docker top` shows that only a zombie `hdfs_mount` process exists.
```
core@paigcr-a-gpu-1035:~$ sudo docker top fb194e6b8a75
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
root                27134               26804               0                   00:26               ?                   00:00:07            [hdfs-mount] <defunct>

```

It might relate to this issue:
https://github.com/moby/moby/issues/35910

**Comment by fanyangCS** [comment]
This is due to the OOM issue that we instruct Docker to ignore it. So the system runs into troubles.
