### ISSUE TITLE
hadoop-resource-manager 'Liveness probe failed'

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#1485]
After build and install the latest code, the hadoop-resource-manager `Liveness probe failed`.

`Liveness probe failed: Get https://10.151.41.69:9459/: tls: oversized record received with length 20291
Back-off restarting failed container`

![image](https://user-images.githubusercontent.com/1547343/46929082-5ec9d400-d070-11e8-8801-38bbe69fa9ad.png)

**Comment by YitongFeng** [comment]
Due to the not matched network protocol schema, fixed in PR #1490
