### ISSUE TITLE
end-to-end-test cannot submit cntk test case

### ISSUE THREAD

**Issue by DongZhaoYu** [Microsoft/pai#1494]
After the cluster is deployed, when end-to-end-test is started. 
Rest server is not ready can e-to-e-test cannot get the token. Restart the service can solve this problem after rest server is ready.

**Comment by DongZhaoYu** [comment]
https://github.com/Microsoft/pai/pull/1563

**Comment by fanyangCS** [comment]
closed as it is solved.
