### ISSUE TITLE
Feature request: support job parameters

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#1527]
Add an entry for user customized job parameters, so user can pass parameters to jobs.
For example: 

- batch_size:
- epoch:
- any other custom parameters

**Comment by hao1939** [comment]
Hi @YanjieGao ,

In my opinion, it would be a config entry liking `job_envs`, which are `key-value` pairs defined by user.
PAI only need to source it into envs parameters.

**Comment by fanyangCS** [comment]
https://github.com/Microsoft/pai/issues/604

**Comment by fanyangCS** [comment]
Maybe you can introduce the feature here: https://github.com/Microsoft/pai/blob/master/docs/job_tutorial.md

**Comment by hao1939** [comment]
Update doc in PR #1613.
