### ISSUE TITLE
 retry of job as TRANSIENT_CONFLICT

### ISSUE THREAD

**Issue by YanjieGao** [Microsoft/pai#1533]
- job retry:
![image](https://user-images.githubusercontent.com/5576848/47004751-d1b47700-d164-11e8-85f5-d932dd31dd87.png)

- am log:
![image](https://user-images.githubusercontent.com/5576848/47004722-c2352e00-d164-11e8-933b-c400a600004a.png)

- job config:
![image](https://user-images.githubusercontent.com/5576848/47004769-da0cb200-d164-11e8-9bd2-e78115588960.png)

- task log
![image](https://user-images.githubusercontent.com/5576848/47004795-e85ace00-d164-11e8-9851-b21e9c867f82.png)

**Comment by yqwang-ms** [comment]
The diagnoistic is enough to debug.
For doc please check:
https://github.com/Microsoft/pai/blob/master/subprojects/frameworklauncher/yarn/doc/USERMANUAL.md#exitstatus-convention

https://github.com/Microsoft/pai/blob/master/subprojects/frameworklauncher/yarn/src/main/java/com/microsoft/frameworklauncher/common/model/ExitType.java

**Comment by YanjieGao** [comment]
Append this info to this issue: 
// A special TRANSIENT_NORMAL which indicate the exit due to resource conflict
  // and cannot get required resource to run.
  TRANSIENT_CONFLICT,

**Comment by yqwang-ms** [comment]
I see you specified gpuType fawda.

Have you set up the gpu types in your cluster?
Please check.
http://{LauncherAddr}/v1/LauncherRequest/ClusterConfiguration

And please check (and provide) the AM log to help debug why not enough resource.

**Comment by YanjieGao** [comment]
i am not sure, this is ustc's cluster feedback. They just give us pai access acc

**Comment by YanjieGao** [comment]
@yqwang-ms  from meeting's suggestions, it is better to give user more clear method to debug retry issues.

How about expose the comment like this expose at log? this will make user more clear to identify the root case and avoid to check the source code?
// A special TRANSIENT_NORMAL which indicate the exit due to resource conflict
// and cannot get required resource to run.

**Comment by yqwang-ms** [comment]
The comment is too general, and the diagnostic is already explian all I know:
![image](https://user-images.githubusercontent.com/32826762/47132447-7a361880-d2d6-11e8-9aa4-6a8053ae5434.png)

**Comment by YanjieGao** [comment]
ok
