### ISSUE TITLE
marketplace job cntk_g2p fails

### ISSUE THREAD

**Issue by DongZhaoYu** [Microsoft/pai#1537]
This job cannot run, the error in docker container is:
/usr/local/hadoop/bin/hdfs
[INFO] start ssh service
 * Restarting OpenBSD Secure Shell server sshd       [80G 
[74G[ OK ]
[INFO] USER COMMAND START

/pai/bootstrap/docker_bootstrap.sh: line 187: cd: code: No such file or directory

[DEBUG] Docker container exit handler: EXIT signal received in docker container, exiting ...

**Comment by qyyy** [comment]
Where is the job? I haven't found it in marketplace.

**Comment by qyyy** [comment]
The job has been deleted due to frequent failed.
