### ISSUE TITLE
redundant configuration will make user confused when they configure their cluster-configuration

### ISSUE THREAD

**Issue by ydye** [Microsoft/pai#154]
https://github.com/Microsoft/pai/blob/4fe556bf6714230dde79e2eaa819226e34f58edd/service-deployment/clusterconfig-example.yaml#L104

I don't think each module need configure this IP address. Actually we could get this information through the code following.
```
{%- for host in cluster_config if 'prometheus' in cluster_config[ host ] -%}
    {{cluster_config[ host ]['ip']}}{% if not loop.last %},{% endif %}
{%- endfor -%}
``` 

And many place should remove the redundant configuration too.

**Comment by fanyangCS** [comment]
a part of deployment refinement efforts

**Comment by ydye** [comment]
I think this issue could be closed. Because we have refactored our configuration. And now, it's much easier then that time. @fanyangCS @scarlett2018
