### ISSUE TITLE
Image reuse issue

### ISSUE THREAD

**Issue by ydye** [Microsoft/pai#155]
https://github.com/Microsoft/pai/blob/4fe556bf6714230dde79e2eaa819226e34f58edd/service-deployment/src/grafana/pai-clusterview-dashboard.json.template#L51

This hardcode will make this image unable to be reused in a different cluster.

If these 3 files are not used when building this docker image. I suggest you to create a config-map, and mount them to the pod, when starting grafana.

**Comment by YitongFeng** [comment]
OK, I will have a try.

**Comment by ydye** [comment]
#278
