### ISSUE TITLE
[paictl machine update] compatibility with kubernetes cluster deployed by paictl of old version

### ISSUE THREAD

**Issue by ydye** [Microsoft/pai#1550]
Due to this commit https://github.com/Microsoft/pai/pull/1466, we have enable the feature of machine update.

But if the kubernetes is deployed by the paictl of old version, the node configuration in the kubernetes may be missed, so when the first time you wanna update the machine status with the command ```./paictl.py machine update```, some issue may be happened.

For example, if the node configuration is missing in kubernetes, and admin update the machine list (Remove some machine) in cluster-configuration and perform the machine update operator. And because the node configuration is missing, so paictl will directly get node-configuration from cluster-configuration. And after compare, paictl found the node in node-configuration and cluster-configuration is the same. So the machine should be removed is still in the cluster, but its configuration is already lost in configuration.

**Comment by ydye** [comment]
#2505

**Comment by fanyangCS** [comment]
we decide to remove the support of this command.
