### ISSUE TITLE
[job status] A job shows running in more than 5 minutes, but no resource assigned. 

### ISSUE THREAD

**Issue by YanjieGao** [Microsoft/pai#1553]
a nni test job from int bed
Should it be waiting status?

![image](https://user-images.githubusercontent.com/5576848/47136609-c25d3700-d2e6-11e8-8efc-993e32af5126.png)

**Comment by mzmssg** [comment]
It is by design, this application has been submitted to YARN,  but AM's resource requirements hasn't been meet.

![image](https://user-images.githubusercontent.com/11887940/47138789-e9b70280-d2ec-11e8-98b5-4723cb50ca39.png)

**Comment by mzmssg** [comment]
From AM log, it seems due to there is no free GPU
![image](https://user-images.githubusercontent.com/11887940/47137207-8b882080-d2e8-11e8-85c1-d5c468e714e8.png)
