### ISSUE TITLE
How to use rest-api to build custom portal?

### ISSUE THREAD

**Issue by shawntian90** [Microsoft/pai#1571]
hi,

There are some requirements of my production environment.

Current web portal is a little bit complex for some guys and it would be great help to build up a custom web portal, which may even only contains an `command` or some custom user interactions of PAI, making it much more easier to use in some scenarios.

Throughout the usage of PAI, involving `rest-server` may be good to handle the backend APIs of this custom portal in my opinion.

My questions: 

1. Is there any better way to provide a `custom web portal` instead of developing another complete fresh web portal? Is it possible that make a secondary development or adding a new page of current web portal?
2. Any docs for `rest-server`? e.g. submitting a new job from API instead of web portal.

Thanks for help!
Shawn

**Comment by hao1939** [comment]
Hi @shawntian90 ,

Let's answer your question one by one.
1. Yes, you can modify the portal, but currently it's not so convenience, we are welcome to any suggestion. If you have any good idea, rise it so we can discuss.
2. We have some brief doc about rest-server: https://github.com/Microsoft/pai/tree/master/docs/rest-server.

**Comment by shawntian90** [comment]
thanks so much!
