### ISSUE TITLE
[Ssh Key File] ~ in filename will be replaced by _ in Chrome.

### ISSUE THREAD

**Issue by wangcan0329** [Microsoft/pai#1574]
Now we added namespace as prefix to the jobname and joint with ~,  if we click private key the file will be downloaded but the ~  in file name will be replaced by _ automatically in Chrome. Which will cause the step 3 and 4 failed since the name changed.

**Comment by DongZhaoYu** [comment]
@wangcan0329 can we provide a more efficient way to users by opening a console in webport and connect to the container? So users wouldn't need to download the key file and connect to the container manually.

**Comment by Gerhut** [comment]
I don't think we should rely on filename auto-generating feature of browser / local file system. Instead of rename the URI of the key file I prefer add a notice like "Make sure your downloaded file named *some-key*".

In the future, I propose providing a shell script includes current three commands and encourage user to use the commands like

```shell
$ bash <(curl http://rest-server/v1/api/user/foo/jobs/bar/containers/baz/connect.sh)
```

to connect the container, as well as giving the download link of key file as tech details.

**Comment by wangcan0329** [comment]
@DongZhaoYu  Actually I had a simple test on web ssh tool but didn't get time to have a further investigation. I will consider to add this feature but I don't think this is high priority thing.

**Comment by wangcan0329** [comment]
@Gerhut Agree. We can consider to combine these three commands into one script.

**Comment by wangcan0329** [comment]
Chrome replace the tilde ~ with an underscore _ is **by design** to avoid potential filename issue on Windows . please refer to [Character “~” will be automatically changed to “_” in filename during downloading by Chrome](https://superuser.com/questions/1360571/character-will-be-automatically-changed-to-in-filename-during-downloadin)

**Comment by fanyangCS** [comment]
Can we detect whether the page is rendered by Chrome or not? if yes, we can show a warning in the page.

**Comment by fanyangCS** [comment]
we publish it as a known issue.

**Comment by scarlett2018** [comment]
PAI does not print the url anymore.
