### ISSUE TITLE
cleaner will delete tags of images which are used by running containers

### ISSUE THREAD

**Issue by DongZhaoYu** [Microsoft/pai#1577]
Problem in cleaner

In order to solve the disk pressure problem we have introduced cleaner to automatically clean the dangling images, containers to release the occupied disk space. Currently we use docker command "docker system prune -af" to forcefully clean all the unused images and containers. Recently we found this command behaves weirdly. For used images, if the there are only 1 tag for the image the tag will be kept and wouldn't removed. If there are more than 1 tag on the image, only 1 is kept and others will be removed. Even if those tags used by running containers can also be removed (it is discussed in https://github.com/moby/moby/issues/36295 ). This is not as what we expected before and has  caused following two problems in cleaner so far.
1. When services are deployed, if cleaner is started before other service and it can delete the tag on newly pulled images which used by our service. If this happens before the service is about to start, k8s will fail to start the service and output "image is missing" error.
2. Currently we use docker executor to run the Yarn container script. And the script is executed with hadoop-run image. After cleaner cleans the image tag on hadoop-run. When running the Yarn script, executor will try to pull the image with the specified tag. If the image is stored on a public dockerhub. It will be pulled successfully. Otherwise it will fail and user's job cannot be executed.

Proposed solution

We cannot rely on the docker's system prune command to do clean up. We need to define our ways to clean the docker cache as we expected. The basic idea is we define a set of rules to check if an image, container or volume can be deleted safely. If the rule is satisfied we deleted it. Otherwise we wouldn't. The proposed rules are as following:

Rules for image cleaning:
1. Our service images will be excluded from cleaner. All those images are never cleaned;
2. If an images is used by a running container. The image and all its tags will not be deleted;
3. If an images is used by a dead container. But the container's dead time is within a predefined period of time (see one hour, this is configurable). We will not delete this images to make sure it wouldn't cause problem in case it is restarted;
4. If an images don't match any condition in 1), 2), 3), it will be deleted.

Rules for container cleaning:
1. If a container is dead and the dead time has pass the predefined period of time (configurable). The container will be deleted.

Rules for volume cleaning:
1. If a volume is using by a running container. The volume will not be deleted;
2. If a volume is used by a dead container, And its dead time is with in a predefined period of time. The volume will not be deleted.
3. If a volume is newly created and its created time is with in our predefined period of time. The volume will not be deleted.
4. If a volume doesn't satisfy any condition in 1), 2), 3), it will be deleted.

Condition to trigger cleaning:
Cleaner does cleanup periodically and it checks a condition before executing the cleaning action. The condition is 
total image size + total volume size > threshold

A possible optimization:
During a cleanup, we don't necessarily clean all the permissible images or volumes. We can continuously evaluate the trigger condition and cleanup the chose candidate until the condition turn false. When we choose the candidates, we favor the image or volume with larger size. This can make the cleaning more efficient.

**Comment by mzmssg** [comment]
Closed it 
https://github.com/Microsoft/pai/pull/2119
