### ISSUE TITLE
LauncherAM cannot log file to container dir on Win

### ISSUE THREAD

**Issue by yqwang-ms** [Microsoft/pai#158]
LauncherAM cannot log file to container dir on Win.
This is due to log4j 1.x does not support cross platform env reference. 
![image](https://user-images.githubusercontent.com/32826762/34508414-feedc8f6-f079-11e7-9ac7-39547811c8eb.png)

**Comment by yqwang-ms** [comment]
low priority, backlog it.

**Comment by scarlett2018** [comment]
cleaning old issues,  @yqwang-ms  please help to evaluate whether this is still an issue, thanks.

**Comment by yqwang-ms** [comment]
Resolved by https://github.com/Microsoft/pai/pull/820
