### ISSUE TITLE
can update dev-box docker iamge in docker hub?

### ISSUE THREAD

**Issue by szxdlut** [Microsoft/pai#1591]
i run follow commad :docker pull docker.io/openpai/dev-box
but the latest image is not match offical docs. e.g this iamge do not have folder /pai/deployment but have a /pai/pai-management

**Comment by hao1939** [comment]
Hi @szxdlut ,

Thanks for you feedback!
Actually you should use the latest release version, you can get it here: https://github.com/Microsoft/pai/releases/latest.
In a brief, the latest code is still in developing, not ready for end user.

Here's a duplicated issue #1568 .

**Comment by hao1939** [comment]
Hi @szxdlut ,

I will close it for now, if you have any questions, please reopen.
