### ISSUE TITLE
etcd on master node down due to OOM

### ISSUE THREAD

**Issue by DongZhaoYu** [Microsoft/pai#1599]
On prod bed, the k8s dashboard cannot be accessed. And there are a lot of error on 179 API server :
{"log":"2018-10-26 01:38:52.867267 W | etcdserver: failed to reach the peerURL(http://10.151.40.181:2380) of member 39fdf5236256c15f (Get http://10.151.40.181:2380/version: dial tcp 10.151.40.181:2380: getsockopt: connection refused)\n","stream":"stderr","time":"2018-10-26T01:38:52.867512219Z"}
{"log":"2018-10-26 01:38:52.867294 W | etcdserver: cannot get the version of member 39fdf5236256c15f (Get http://10.151.40.181:2380/version: dial tcp 10.151.40.181:2380: getsockopt: connection refused)\n","stream":"stderr","time":"2018-10-26T01:38:52.867535718Z"}
{"log":"2018-10-26 01:38:53.384567 W | etcdserver: timed out waiting for read index response\n","stream":"stderr","time":"2018-10-26T01:38:53.384745717Z"}
{"log":"2018-10-26 01:38:56.872365 W | etcdserver: failed to reach the peerURL(http://10.151.40.181:2380) of member 39fdf5236256c15f (Get http://10.151.40.181:2380/version: dial tcp 10.151.40.181:2380: getsockopt: connection refused)\n","stream":"stderr","time":"2018-10-26T01:38:56.872540637Z"}
{"log":"2018-10-26 01:38:56.872391 W | etcdserver: cannot get the version of member 39fdf5236256c15f (Get http://10.151.40.181:2380/version: dial tcp 10.151.40.181:2380: getsockopt: connection refused)\n","stream":"stderr","time":"2018-10-26T01:38:56.872574137Z"}
{"log":"2018-10-26 01:38:57.283212 W | rafthttp: health check for peer 39fdf5236256c15f could not connect: dial tcp 10.151.40.181:2380: getsockopt: connection refused\n","stream":"stderr","time":"2018-10-26T01:38:57.283399543Z"}
{"log":"2018-10-26 01:39:00.873428 W | etcdserver: failed to reach the peerURL(http://10.151.40.181:2380) of member 39fdf5236256c15f (Get http://10.151.40.181:2380/version: dial tcp 10.151.40.181:2380: getsockopt: connection refused)\n","stream":"stderr","time":"2018-10-26T01:39:00.873568221Z"}
{"log":"2018-10-26 01:39:00.873454 W | etcdserver: cannot get the version of member 39fdf5236256c15f (Get http://10.151.40.181:2380/version: dial tcp 10.151.40.181:2380: getsockopt: connection refused)\n","stream":"stderr","time":"2018-10-26T01:39:00.87358242Z"}
{"log":"2018-10-26 01:39:02.283376 W | rafthttp: health check for peer 39fdf5236256c15f could not connect: dial tcp 10.151.40.181:2380: getsockopt: connection refused\n","stream":"stderr","time":"2018-10-

on machine 180 and 181 etcd service is down , the error log on 181 is:

{"log":"2018-10-26 02:35:20.219515 I | rafthttp: peer 6f2fc15b95d41a92 became active\n","stream":"stderr","time":"2018-10-26T02:35:20.22342883Z"}
{"log":"2018-10-26 02:35:20.219551 I | rafthttp: established a TCP streaming connection with peer 6f2fc15b95d41a92 (stream Message writer)\n","stream":"stderr","time":"2018-10-26T02:35:20.22343303Z"}
{"log":"2018-10-26 02:35:20.219560 I | rafthttp: established a TCP streaming connection with peer 6f2fc15b95d41a92 (stream MsgApp v2 writer)\n","stream":"stderr","time":"2018-10-26T02:35:20.22343563Z"}
{"log":"2018-10-26 02:35:20.219864 I | rafthttp: established a TCP streaming connection with peer 6f2fc15b95d41a92 (stream MsgApp v2 reader)\n","stream":"stderr","time":"2018-10-26T02:35:20.22343813Z"}
{"log":"2018-10-26 02:35:20.220029 I | rafthttp: established a TCP streaming connection with peer 6f2fc15b95d41a92 (stream Message reader)\n","stream":"stderr","time":"2018-10-26T02:35:20.22344073Z"}
{"log":"2018-10-26 02:35:20.284936 I | raft: raft.node: 39fdf5236256c15f elected leader 6f2fc15b95d41a92 at term 9138\n","stream":"stderr","time":"2018-10-26T02:35:20.285113875Z"}
{"log":"2018-10-26 02:35:20.365265 I | rafthttp: receiving database snapshot [index:167702674, from 6f2fc15b95d41a92] ...\n","stream":"stderr","time":"2018-10-26T02:35:20.36548529Z"}
{"log":"2018-10-26 02:35:20.997145 E | rafthttp: failed to save KV snapshot (write /var/etcd/data/member/snap/tmp167644288: _cannot allocate memory)\n_","stream":"stderr","time":"2018-10-26T02:35:20.9973249

**Comment by hao1939** [comment]
Fixed with #1619.
