### ISSUE TITLE
Node export readiness probe failed

### ISSUE THREAD

**Issue by mzmssg** [Microsoft/pai#1603]
![image](https://user-images.githubusercontent.com/11887940/47545287-06bb8900-d91e-11e8-9dbc-a1515a2c2736.png)

**Comment by xudifsd** [comment]
this is not probe fail, it's indicate the job-exporter didn't update file exported by node-exporter for more than 2 mins. I will look on why it didn't update the file if this happens again.

**Comment by xudifsd** [comment]
added a metrics to aid future investigation of related issues.
