### ISSUE TITLE
Pull request always failed on jenkins build process

### ISSUE THREAD

**Issue by TobeyQin** [Microsoft/pai#1606]
I want to submit pull request, but always failed on Jenkins build process.
Below are the shortcut and pull request ID. Could you help resolve this?

PR: https://github.com/Microsoft/pai/pull/1585

Shortcut:
![image](https://user-images.githubusercontent.com/32830091/47557745-13eb6e80-d944-11e8-891c-1e4a48c090a7.png)

**Comment by hao1939** [comment]
Hi @TobeyQin ,

You will need to rebase on master.
Currently there are breaking changes on master branch, which changes `paictl.py`.

![image](https://user-images.githubusercontent.com/1547343/47627536-8f7b3480-db6b-11e8-910f-6f8cd562c1b9.png)
