### ISSUE TITLE
token生成机制

### ISSUE THREAD

**Issue by damon008** [Microsoft/pai#1610]
请问，jwt.sign({
                    username: user.id,
                    admin: admin,
                }, tokenConfig.secret, {expiresIn: expiration}, (signError, token) =>这个底层是什么样的生成机制呢？ 如果用换成java写的话，怎么写呢？

**Comment by Gerhut** [comment]
Hi @damon008 

<https://jwt.io/> may helps you.

You could paste your JWT token into the page to check the JWT headers and payload.

**Comment by damon008** [comment]
我想请问下，PAI的安全校验是通过token校验了，还是通过用户名与密码来校验呢？
![image](https://user-images.githubusercontent.com/25023599/47627691-6a3af600-db6c-11e8-804b-858004d164b1.png)

**Comment by Gerhut** [comment]
Hi @damon008 
The code you posted is a part of token-generation process.

- Username/password validation is only run in token-generation process.
- Token validation is run in other auth-required processes.

In other words, if you want to access auth-required resources,

1. Provide your username/password to `POST /token` route, to get a valid token.
2. Provide the valid token to other auth-required resources.

**Comment by Gerhut** [comment]
Hi @damon008 

You're right that we use HS256 algo to sign the token, and it could be varified in <http://jwt.io/> (algo is set in jwt header)

**Comment by fanyangCS** [comment]
no further input. closed.
