### ISSUE TITLE
job failure due to "Can not pull Docker image"

### ISSUE THREAD

**Issue by fanyangCS** [Microsoft/pai#1614]
Log Type: stderr 
Log Upload Time: Sun Oct 28 22:19:16 +0000 2018 
Log Length: 957 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100  5009  100  5009    0     0   152k      0 --:--:-- --:--:-- --:--:--  152k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100  7170  100  7170    0     0   524k      0 --:--:-- --:--:-- --:--:--  524k
**Error response from daemon: Get https://registry-1.docker.io/v2/aiplatform/pai.run.cntk/manifests/latest: received unexpected HTTP status: 503 Service Unavailable**

Log Type: stdout 
Log Upload Time: Sun Oct 28 22:19:16 +0000 2018 
Log Length: 280 
[INFO] GPU_ID
3

[INFO] NVIDIA_DEVICES
--device=/dev/nvidiactl --device=/dev/nvidia-uvm --device=/dev/nvidia3

[WARNING] Failed to request info from webhdfs, sleep 20 s ...
2018-10-28 22:18:20
[INFO] User code_dir_size is 19516
Using default tag: latest
**Can not pull Docker image**

**Comment by fanyangCS** [comment]
@mzmssg 
The system treats it as a user error, should we treat it as a system failure and retry automatically?

**Comment by mzmssg** [comment]
For pulling image failure, it is mostly because of user error, such as image name error, credential error. For these errors, treating it as system failure to trigger retry doesn't work. Because it's user's image, I think raising it to user makes sense. 

For this case, I think we can add a pulling retry in our yarn script, if all these pulling attempts fail, we will exit as a user failure.

**Comment by fanyangCS** [comment]
ok. seems like a transient problem from docker hub
