### ISSUE TITLE
start service failed by image pull

### ISSUE THREAD

**Issue by szxdlut** [Microsoft/pai#1616]
when i run cmd:  python paictl.py service start -p ~/pai-config  to start all service 
log show  Successfully start all services

on k8s web portal 
![tim 20181029171430](https://user-images.githubusercontent.com/8004436/47640360-61fbae80-db9e-11e8-921d-4fd3facda8cf.png)

but all image have download like this
![tim 20181029171723](https://user-images.githubusercontent.com/8004436/47640415-85265e00-db9e-11e8-9b02-fdb75c79d644.png)

can service start use locally image , do not download from docker hub again?

**Comment by fanyangCS** [comment]
@szxdlut , you can set up a local docker registry to achieve this.

**Comment by fanyangCS** [comment]
https://github.com/Microsoft/pai/issues/684
