### ISSUE TITLE
why my openPAI page do not have the detai of the GPU?

### ISSUE THREAD

**Issue by UnnnU** [Microsoft/pai#1620]
![image](https://user-images.githubusercontent.com/10185324/47699799-0e956900-dc4f-11e8-8b48-4bb6c2ac3b53.png)

as you can see in the picture, it says my node do not have GPU,  but actually it has!  i don't know why....Help :(
我配置的电脑上是由GPU的，可为什么OpenPAI页面上没显示？求解答

**Comment by ydye** [comment]
How many gpus detected by yarn on your cluster? This could be found at the port 8088

**Comment by lllllwwwwyyyy** [comment]
![image](https://user-images.githubusercontent.com/10185324/47700810-b9f3ed00-dc52-11e8-973c-b41b70376e7a.png)
it show i have 0 GPU. i don't know why?Is there any setting i miss?Actually I follw the readme.md to  deploy the OpenPAI

**Comment by ydye** [comment]
####1
Please ssh to the target GPU node, and execute the command following.
```
# Get container id
sudo docker ps | grep openpai/drivers | awk '{print $1}'

# Go into the container
sudo docker exec -it ${contianer_id}  /bin/bash

# Detect GPU.
nvidia-smi
```
####2
Can you show us the log of the drivers service?

**Comment by lllllwwwwyyyy** [comment]
![image](https://user-images.githubusercontent.com/10185324/47702131-f590b600-dc56-11e8-9155-0a269f51d09a.png)
this?

**Comment by ydye** [comment]
@mzmssg

**Comment by mzmssg** [comment]
could you get into hadoop-node-manager container to verify the gpu status

`sudo docker ps | grep k8s_hadoop-node-manager | awk '{print $1}'`
then exec `nvidia-smi` in  it.

Besides, I notice some running processes take GPU, could you stop them and then restart PAI. This processes will affect our GPU detection logic.

**Comment by lllllwwwwyyyy** [comment]
![image](https://user-images.githubusercontent.com/10185324/47998431-406c6b00-e13a-11e8-8898-25fd2e48a027.png)
I tried this command , but i got this warnings. It can not run the program 'nvidia-smi' because there is no such file or directory.  :( help

**Comment by lllllwwwwyyyy** [comment]
![image](https://user-images.githubusercontent.com/10185324/47999481-a9a1ad80-e13d-11e8-985a-05653cca8a9a.png)
![image](https://user-images.githubusercontent.com/10185324/47999491-aefef800-e13d-11e8-9f09-cc7fa9572b43.png)
I killed this process by command sudo kill <uid> 
But after i restart PAI these process appear again

**Comment by mzmssg** [comment]
Still show 0 GPU in webportal? Could you paste hadoop node manager log to help address this issue?

**Comment by lllllwwwwyyyy** [comment]
i do not know why....:(     
Need I use VPN when I use the OpenPAI's own script to install k8s image and start the container?I didn't use VPN before.And it shows many tasks have filed in the k8s dashboard.

**Comment by lllllwwwwyyyy** [comment]
Is it  download the image from the google image library?Is it inaccessible in China?

**Comment by lllllwwwwyyyy** [comment]
![image](https://user-images.githubusercontent.com/10185324/48185481-100e1200-e370-11e8-9869-ef33bea56fc8.png)

**Comment by mzmssg** [comment]
It's an issue, but not relate to current thread. Let's focus it firstly, could you check this command output 
```
id=$(sudo docker ps | grep k8s_hadoop-node-manager | awk '{print $1}') &&  sudo docker exec $id nvidia-smi
```

**Comment by yunzhongyan0** [comment]
> #### 1
> Please ssh to the target GPU node, and execute the command following.
> 
> ```
> # Get container id
> sudo docker ps | grep openpai/drivers | awk '{print $1}'
> 
> # Go into the container
> sudo docker exec -it ${contianer_id}  /bin/bash
> 
> # Detect GPU.
> nvidia-smi
> ```
> #### 2
> Can you show us the log of the drivers service?



> #### 1
> Please ssh to the target GPU node, and execute the command following.
> 
> ```
> # Get container id
> sudo docker ps | grep openpai/drivers | awk '{print $1}'
> 
> # Go into the container
> sudo docker exec -it ${contianer_id}  /bin/bash
> 
> # Detect GPU.
> nvidia-smi
> ```
> #### 2
> Can you show us the log of the drivers service?

hello, recently I have the same problem. 'drivers'  service can't start，it's said 'No GPU machine in your cluster', what can I do?  " sudo docker ps | grep openpai/drivers | awk '{print $1}'" show nothing

**Comment by ShawnNew** [comment]
> id=$(sudo docker ps | grep k8s_hadoop-node-manager | awk '{print $1}') &&  sudo docker exec $id nvidia-smi

Hi @mzmssg, I met the same problem. And here's my log:
```
id=$(docker ps | grep k8s_hadoop-node-manager | awk '{print $1}') &&  sudo docker exec $id nvidia-smi
OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "exec: \"nvidia-smi\": executable file not found in $PATH": unknown

```
Can you help me out with this?
