### ISSUE TITLE
How is the remote server inbound outbound rule configured?

### ISSUE THREAD

**Issue by NothingLZ** [Microsoft/pai#1622]
Whether to open 8080, 9090, 9286, 80, 50070...

![image](https://user-images.githubusercontent.com/12367891/47704191-bf0a6980-dc5d-11e8-9da2-6eddd18045e1.png)

**Comment by ydye** [comment]
```
8088 - resource-manager,
5070 - name-node
80 - pylon
```

**Comment by NothingLZ** [comment]
Thanks

**Comment by xudifsd** [comment]
@NothingLZ What you want? Ports used by all pai services or port you need to connected from outside of the cluster?

**Comment by NothingLZ** [comment]
yes

**Comment by xudifsd** [comment]
Ports used by all pai services?

**Comment by NothingLZ** [comment]
yes, need to open those ports?  master and work.

**Comment by xudifsd** [comment]
```
3000 - grafana
9091 - prometheus
9100 - node-exporter
9459 - yarn-exporter
9093 - alert-manager
```

Those are ports used by monitoring, if you are configuring security rule controlling which port can be accessed from the outside of the cluster, you may only needs to open `3000` and `9091` ports, other ports are only used inside cluster.

These ports are configurable in `cluster-configuration/service-configuration.yaml`, you can check them.

Maybe @Gerhut can give you the whole list of port that needs to be accessed from the outside of the cluster.

**Comment by NothingLZ** [comment]
Ok, thank you for your answer.
