### ISSUE TITLE
How could job or service get the cluster info? Sharing configuration?

### ISSUE THREAD

**Issue by hao1939** [microsoft/pai#1623]
How could job on PAI get:

- PAI master host:port
- rest-server url

And could PAI provide full support of sharing config between jobs? Now PAI only support sharing port info, which were statically assigned.

**Comment by mydmdm** [comment]
Actually, we met the same requirement when implementing the [SDK and CLI](https://github.com/microsoft/pai/tree/sdk-release-v0.4.00/contrib/python-sdk), here is what we do:

- jobs submitted by the SDK will embed a `json` serialized string, including `pai_uri, user, web_hdfs_uri, ...` in the `secrets.clusters` section of the protocol
- in `deployment` add a command `echo <% secrets.clusters %> > ~/.openpai/cluster.yaml`
- the sdk will leverage the `~/.openpai/cluster.yaml`

**Comment by fanyangCS** [comment]
deferred to pure k8s version.
