### ISSUE TITLE
rest-server api: submit(create) a job should return the created job

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#1629]
As `restful verbs` defined, rest-server should better return the created object for a 'create/update' operation.

Now the submit job api `POST /api/v1/user/:username/jobs` returns:
```
{
  "message": "update job $jobName successfully"
}
```

**Comment by sotetsuk** [comment]
It seems that this is already resolved. (at least on v0.10.0)

**Comment by scarlett2018** [comment]
> As `restful verbs` defined, rest-server should better return the created object for a 'create/update' operation.
> 
> Now the submit job api `POST /api/v1/user/:username/jobs` returns:
> 
> ```
> {
>   "message": "update job $jobName successfully"
> }
> ```

Combine with #2315 which is planned in 0.12.0
