### ISSUE TITLE
Jenkins bed's memory isn't enough.

### ISSUE THREAD

**Issue by mzmssg** [Microsoft/pai#1631]
Currently, Jenkins bed is just enough to deploy PAI. 

But when I add a new container requesting 1G memory, some service can't start due to short of memory. Do we need to expand this bed memory?

![image](https://user-images.githubusercontent.com/11887940/47762980-a780be80-dcf9-11e8-8621-5e2adcb9cf61.png)
![image](https://user-images.githubusercontent.com/11887940/47762989-b2d3ea00-dcf9-11e8-9206-6f2d10dd03f3.png)

**Comment by hao1939** [comment]
What about reducing the 'requests' memory for RM?
Now it's set to 8G.

**Comment by mzmssg** [comment]
So we need to change our master code to pass Jenkins?

**Comment by hao1939** [comment]
You could change it on your branch.

**Comment by fanyangCS** [comment]
memory increased to 128G.
