### ISSUE TITLE
--share-shm param when start container

### ISSUE THREAD

**Issue by chlxydl** [Microsoft/pai#1634]
When training with pytorch, it requires enough shared memory to enable multi data threads. However the default share memory space only 64M, is it possible to added --share-shm param when start docker?

**Comment by fanyangCS** [comment]
pai already supports it. 
Please refer to https://github.com/Microsoft/pai/blob/master/docs/job_tutorial.md#write-a-job-json-configuration-file-

**Comment by chlxydl** [comment]
Yes, I have found this param on the website, however visual studio tools for AI seems still not support it.
