### ISSUE TITLE
Unreasonable crash or be killed when model training

### ISSUE THREAD

**Issue by chlxydl** [Microsoft/pai#1635]
When training model with pytorch(multi-gpus), sometimes the container will be killed, although both cpu, gpu, memory, disk metrics are normally.

**Comment by mzmssg** [comment]
could you offer detailed job log?

**Comment by chlxydl** [comment]
http://10.150.144.225:9286/view.html?jobName=MODEL_TEST_MASKRCNN_final18 
above is one of the link.

**Comment by fanyangCS** [comment]
@chlxydl , it seems someone stopped the job. Not crashed.

**Comment by mzmssg** [comment]
@fanyangCS I think he means the history job

**Comment by mzmssg** [comment]
the same as #1633
