### ISSUE TITLE
[Feature] Make PAI runtime features configurable and well documented the changes made on user's container.

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#1638]
PAI adds some features in user's container, currently the changes are not transparent.

I suggest to have a configure entry in job config, for example:
```
{
     jobName: 'your_job_name',
...
     runtime_addin: ['ssh', 'hdfs', 'cuda8']
}
```
Only enable the features if user selects. And well documented the changes made on user's container.

**Comment by hao1939** [comment]
#1777 is for tracking the disk restriction.

**Comment by fanyangCS** [comment]
are you talking abou this?https://github.com/Microsoft/pai/pull/1544

**Comment by hao1939** [comment]
It's more like the proposal @xudifsd is working on.
Will discuss on the proposal.
