### ISSUE TITLE
prometheus image can't pull

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#1639]
0/18 nodes are available: 1 PodFitsHostPorts, 17 MatchNodeSelector.
Failed to pull image "openpai.azurecr.io/paiclusterint/prometheus:latest": rpc error: code = Unknown desc = Error response from daemon: Get https://openpai.azurecr.io/v2/paiclusterint/prometheus/manifests/latest: no basic auth credentials

![image](https://user-images.githubusercontent.com/1547343/47789320-3c61d700-dd4f-11e8-90d7-e6069905857f.png)

**Comment by hao1939** [comment]
Found a highly related discussion: https://github.com/spotify/docker-client/issues/804#issuecomment-318252699

**Comment by xudifsd** [comment]
Not sure if this is the root cause, it can not explain why other image can be pulled. What's more, I checked several node in int bed, they all have `openpai.azurecr.io` as auth's key not `https://openpai.azurecr.io`.

**Comment by hao1939** [comment]
It's a blocking issue, now can't deploy master branch.

**Comment by xudifsd** [comment]
@hao1939 this affected CICD?

**Comment by xudifsd** [comment]
Also where auth in `~/.docker/config.json` came from? From `docker login`? But when did we logged in in worker nodes?

**Comment by hao1939** [comment]
Blocking PAI deployment, I can't manually deploy, and CI/CD hang.

**Comment by xudifsd** [comment]
After read [official doc](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/), I get the idea.

@hao1939 we didn't configured `imagePullSecrets` field in `prometheus-deployment`. This is due to you changed the image from `prom/prometheus` to our repository. But I also checked secret in int bed, it contains nothing. I think this is also a bug for service deployment, since maybe some node fallback auth from secret to `~/.docker/config.json` which I do not know where these configs came from.

**Comment by xudifsd** [comment]
@ydye Where do we create `clusterinfo["dockerregistryinfo"]["secretname"]`? I could not find.

**Comment by xudifsd** [comment]
ok, I find in [here](https://github.com/Microsoft/pai/blob/master/deployment/paiLibrary/clusterObjectModel/paiObjectModel.py#L560).

**Comment by xudifsd** [comment]
But still not sure why int bed has empty secret.

```
root@stcal-121:/# kubectl get secret paiclusterintsecret --output="jsonpath={.data.\.dockerconfigjson}" | base64 --decode
{}
```

**Comment by ydye** [comment]
@xudifsd Because if you wanna pulling image from dockerhub, the passwd and useraccount are unnecessary.

**Comment by xudifsd** [comment]
@ydye but int bed is not using dockerhub, it using `openpai.azurecr.io`

**Comment by ydye** [comment]
@xudifsd There must be something wrong, because I found all service pull image from dockerhub.

**Comment by xudifsd** [comment]
ok, maybe @DongZhaoYu deployed int bed using dockerhub instead of `openpai.azurecr.io`. Then problem solved. @hao1939 you can just merge #1678 .
