### ISSUE TITLE
Virtual cluster your_virtual_cluster is not found.

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#1640]
![image](https://user-images.githubusercontent.com/1547343/47789733-5819ad00-dd50-11e8-930c-b8838f313360.png)

**Comment by Gerhut** [comment]
Hi @hao1939 

Perhaps `your_virtual_cluster` is a placeholder that asks the users to fill in their own virtual cluster.

Shall we modify it to "default"?

**Comment by hao1939** [comment]
Yeah, you are right.
It's some kind of misleading, the error message looks like system error.

Could we separate user error and system error? It would be more straightforward.

**Comment by scarlett2018** [comment]
I'm not able to reproduce the issue anymore, closing it.
