### ISSUE TITLE
Yarn container script doesn't enter exit handle.

### ISSUE THREAD

**Issue by mzmssg** [Microsoft/pai#1644]
For this retry job
http://*.179/view.html?username=zimiao&jobName=ocr-serving
log:
http://*.179:8188/applicationhistory/logs/10.151.40.185:8041/container_e09_1540808776381_0115_01_000002/container_e09_1540808776381_0115_01_000002/zimiao

![image](https://user-images.githubusercontent.com/11887940/47846210-1ba68980-de02-11e8-828c-e3d5bc616532.png)

This is a serving example, from log, it neither finished nor suicided, so it should be killed by yarn-script.

But our kill command is in yarn-script exit_handle, which doesn't be executed.
//replacing ip with dummy ip

**Comment by fanyangCS** [comment]
maybe this is killed by Docker/OS due to system issue like OOM, disk pressure?

**Comment by mzmssg** [comment]
Please help reopen if meet again
