### ISSUE TITLE
What should I pay attention to when deploying openpai on Azure?

### ISSUE THREAD

**Issue by NothingLZ** [Microsoft/pai#1645]
For example, port rules set network configuration, etc.

**Comment by NothingLZ** [comment]
OS is ubuntu16.04.5TLS  
![image](https://user-images.githubusercontent.com/12367891/47962639-9ff34980-e05a-11e8-9380-6581067c46af.png)

 master：
![image](https://user-images.githubusercontent.com/12367891/47962631-8520d500-e05a-11e8-9a09-6f4c98f119c9.png)
![image](https://user-images.githubusercontent.com/12367891/47962626-79cda980-e05a-11e8-8db8-b3b677d646ac.png)


work:
![image](https://user-images.githubusercontent.com/12367891/47962646-bac5be00-e05a-11e8-932a-1fdcc0125c18.png)
![image](https://user-images.githubusercontent.com/12367891/47962655-c913da00-e05a-11e8-92e3-47e6368ef202.png)

Can this configuration be ok?

**Comment by fanyangCS** [comment]
close this issue. This should go to FAQ.
