### ISSUE TITLE
how does cuda version support?

### ISSUE THREAD

**Issue by squirrelsc** [Microsoft/pai#1652]
if training scripts or hardware depends on different CUDA version, can it co-exists on same deployment? If it can be, there should be some how-to documents.

**Comment by fanyangCS** [comment]
PAI does not specify the CUDA version. User can include any CUDA version in his/her docker image, as long as the GPU driver supports it. For example, if the GPU driver version is 384.111, the platform can support cuda library up to 9.0 (9.1 requires higher version.)

Please consult your platform Admin for the GPU driver version (The default PAI driver version is now 384.111, and we allow customization of it). Please refer to the related NVIDIA websites for the compatibility issues. e.g., https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html#install-linux

**Comment by fanyangCS** [comment]
@YanjieGao , maybe we can add a FAQ for this?

**Comment by scarlett2018** [comment]
this question is also raised by an internal customer, adding the tag
