### ISSUE TITLE
systemctl docker restart fail on some machine

### ISSUE THREAD

**Issue by DongZhaoYu** [Microsoft/pai#1657]
On some machine this command failed with error;
Failed to issue method call: Unit docker.service failed to load: No such file or directory. See system logs and 'systemctl status docker.service' for details.

But the command "service docker restart" can be used. We may need to fix our script to execute this command if systemctl fails.

-----------------
**Resolution**:
+ add a system validation

**Comment by fanyangCS** [comment]
Can you post a link to the related code snippet?

**Comment by DongZhaoYu** [comment]
the code line:
https://github.com/Microsoft/pai/blob/master/deployment/k8sPaiLibrary/maintaintool/docker-ce-install.sh#L87

**Comment by ydye** [comment]
@DongZhaoYu 
Maybe we can change the code like this?
```
systemctl restart docker || service docker restart || exit $?
```

**Comment by fanyangCS** [comment]
a related issue. https://github.com/Microsoft/pai/issues/1231

**Comment by hao1939** [comment]
@scarlett2018 , We could close it. Systemd is a prerequisites, we need it.

**Comment by fanyangCS** [comment]
I hereby close the issue. We assume pai runs on ubuntu, which should come with systemd.

**Comment by scarlett2018** [comment]
@hao1939 @fanyangCS - I'm reopenning the issue. The resolution we discussed the other day is to "add a system check as the first step of installations. If the user is not using ubuntu, instead of checking logs and submit issues to github, we will return an error message directly from the install script." . May we add the validation?

**Comment by hao1939** [comment]
Hi @scarlett2018 , now I add a os 'check' before the installation, within the PR #2520.

**Comment by scarlett2018** [comment]
@hao1939, super! added my review comments, thanks for not only fix this issue but also validated other critia in the PR, that looks great.
