### ISSUE TITLE
Version management in OpenPAI

### ISSUE THREAD

**Issue by DongZhaoYu** [Microsoft/pai#1660]
In OpenPAI version info is used in multiple places. When build a new release we need to manually update all the version infos. This is error prone and hard to maintain.

So a better way is to store the version info in a central place. The version info in all components will come from this central place. This can make the version maintenance more easier and in a consistent way.

**How version info is used currently**

So far we have three components are directly referring version info.
	1) Webportal
	In webportal's package file refer the version info.
	2) Quick-start configuration template
	The version is referred as a docker tag

**The solution**

We add a configure YAML file called version in our source code and put version info into it. Its simplest content would like:

version: v0.8.0          #this is the code version of the new release
Image_tag: latest     #this is the tag for built image

This version info can be consumed in following scenarios.

- Consume the version  info in quick-start configure template

In configuration template the docker-tag need to refer the version. We can change the docker-tag as below:

Docker-tag: {{ clusterinfo['image_tag'] }}

The docker image tag will be substituted by paictl.

- Consume the version info at build time

If service has some configuration files and version is referred in the configuration. The service can define the configuration file as a template. Before the build, generate the configuration file by substituting the version. This is done in following steps:
	1) Pai-build will parse the version file and get the version info;
	2) When start to build a service, pai-build will first to execute the build-pre.sh script. When calling this script, pai-build inject the version info as environment variable to the process running the script; The environment variables would be "VERSION=0.8.0, IMAGE_TAG=0.8.0"
	3) In the build-pre script, it will get the version info from the environment variable and replace the template variable to generate the configuration files;
	4) Pai-build will use the generated configuration file to build images;

Webportal is in this scenario.

- Consume the version info at runtime

If a service doesn't has a configuration file but it has some internal logic depends on the version. It can build this version file into its image and parse the version at runtime.

- Generate docker tag for release

When testing a release, we need version to generate the docker image tag in format v{major}.{minor}.y-{date}-{hash}.  After all tests pass and publish the release, the official image will be build with tag v{major}.{minor}.{patch}. Currently all those steps are manually and each time we do a build we need to change the image tag in the configure file. With this version info file, we can enhance the current build tool to generate the tag automatically.

We add two new parameters in current pai-build tool:
	1) "--release": this flag is to tell the pai-build current build is for a release. Build tool will generate the docker image tag according the to the format specified in our release document. The tag in the configuration file will be ignored.
	2) "--phase [int|prod]" : this parameter is to specify the build release is for integration test or production. The default value is integration test. In int phase, the generated tag format will be v{major}.{minor}.y-{date}-{hash}. In prod phase, the generated tag format will be v{major}.{minor}.{patch}

To build a release, we can follow those steps:
	1) Create a new branch, say branch pai-v0.8.y, and our new release will be v0.8.0. So update the version file to 
	Version: v0.8.0
	Image_tag: v0.8.0
	2) Run build command "python pai-build.py build -c config_path --release --phase int". This command will build the images and generate the tag in format v{major}.{minor}.y-{date}-{hash}.
	3) Run push command "python pai-build.py push -c config_path --release --phase int"
	4) Do tests and fixes
	5) Create and push tag v0.8.0
	6) To build the product image, run "python pai-build.py build -c config_path --release --phase prod". In the command we will check if the tag v0.8.0 is created and current code base is under this tag. Otherwise it will fail.
	7) Push product image by "python pai-build.py push -c config_path --release --phase prod"

After the release, in master branch we change the version file to:
Version: v0.9.0
Image_tag: latest
And we can continue our development to the new release v0.9.0

**Comment by fanyangCS** [comment]
@DongZhaoYu , can we only use "version" in the yaml file? the tag should be the same with the specified version.

For a release branch, the version should be the version of the release. For the master branch, the version should be "latest". 

Does that make sense?

**Comment by DongZhaoYu** [comment]
@fanyangCS If we allow the version value can be latest. It is simple to only use "version" in the yaml file. Yes, that makes sense.

**Comment by fanyangCS** [comment]
close and track in #2498.
