### ISSUE TITLE
kubelet cannot be installed

### ISSUE THREAD

**Issue by NothingLZ** [Microsoft/pai#1661]
![image](https://user-images.githubusercontent.com/12367891/47963370-658fa980-e066-11e8-9f55-8a07a6a3f09b.png)

**Comment by fanyangCS** [comment]
from E1104, k8s stores containers under /, where you mount it using /deb/sda1 and it has only 7.9G available under /,

**Comment by NothingLZ** [comment]
> 从E1104开始，k8s将容器存放在/下，你用/ deb / sda1挂载它，它在/下只有7.9G可用，

There is another problem, I deployed it on azure, then how to configure this IP address?
![image](https://user-images.githubusercontent.com/12367891/47980338-2adb4f00-e102-11e8-8c3f-b9693c0763d0.png)
I configured the ip address of the master node.（Public ip）

**Comment by NothingLZ** [comment]
![image](https://user-images.githubusercontent.com/12367891/47982355-6bd76180-e10a-11e8-80ec-3873e7c1967a.png)

No success, is this a network problem?

**Comment by NothingLZ** [comment]
I think it is necessary to set a availability set and bind a load balance. Then configure the load balancing ip address in the kubernetes-configuration.yaml file.

![image](https://user-images.githubusercontent.com/12367891/47984440-9bd63300-e111-11e8-93b3-65075fe29028.png)

**Comment by ydye** [comment]
> I think it is necessary to set a availability set and bind a load balance. Then configure the load balancing ip address in the kubernetes-configuration.yaml file.
> 
> ![image](https://user-images.githubusercontent.com/12367891/47984440-9bd63300-e111-11e8-93b3-65075fe29028.png)

Yes, you are right. And with the load balance, you could set 3 master in the load balance back end pool to support kubernetes HA mode.

**Comment by ydye** [comment]
And Can you show me the the output of the following command in your master node.
```
sudo docker info
```

**Comment by NothingLZ** [comment]
master:
![image](https://user-images.githubusercontent.com/12367891/48120230-8a755e00-e2ac-11e8-8e4d-783b3f5fe043.png)

work:

![image](https://user-images.githubusercontent.com/12367891/48120240-93fec600-e2ac-11e8-814d-b873dd88edc4.png)

**Comment by NothingLZ** [comment]
by the way , i just seemed to be building it.
![image](https://user-images.githubusercontent.com/12367891/48120318-cad4dc00-e2ac-11e8-8dbb-d89bbe0d8488.png)
![image](https://user-images.githubusercontent.com/12367891/48120348-dc1de880-e2ac-11e8-90dc-75d341290f73.png)

**Comment by ydye** [comment]
congratulations, I'm interested in the solution that you depends on to solve this issue.

**Comment by NothingLZ** [comment]
Haha, thank you, thanks to everyone’s enthusiastic answer.
