### ISSUE TITLE
Support AD/AAD account

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#1663]
raised by MS tech sales team.

Work Break Down:

1. Backend user management including the end2end experience – @ydye @wangdian  #2531 

2. Web portal authentication process with AAD –  @ydye #2532

3. Storage Manager support group configuration  – @wangdian  #2530

When implement also consider the relationship or impact on these items: #2078 #2085 #921.

### Test Case

**Comment by fanyangCS** [comment]
This is a related doc: https://docs.microsoft.com/en-us/azure/aks/aad-integration

**Comment by fanyangCS** [comment]
https://github.com/Microsoft/pai/issues/1811

**Comment by scarlett2018** [comment]
Adding @qfyin for awareness.

**Comment by wangdian** [comment]
Design goal for storage changed. Please refer to #2530

**Comment by fanyangCS** [comment]
done after v0.15
