### ISSUE TITLE
Failed to submit job from VS Code

### ISSUE THREAD

**Issue by scarlett2018** [Microsoft/pai#1664]
problem met by customer

**Customer's env**
1 master node and 1 worker node, end-2-end test job跑成功了

**Problem**
按照github教程通过VScode提交job的时候， 发现上传到默认hdfs失败, 提交任务一直被卡在code uploading. 但是存放code的任务名文件夹可以被建立成功。只是一个python文件， 14k左右.

访问master的50070端口， 开web hdfs界面。 在这里试着上传code， 还是失败.

就是来自官方github的example。如果直接从PAI的web界面提交可以run成功。 但是从VScode提交会一直卡在code上传。

接着上面描述， 访问master的50070端口， 开web hdfs界面。 在这里试着上传code， 还是失败。开network调试发现两个request, 第一个请求看起来像是request上传地址， 但是服务器返回一个内网ip地址。第一个请求看起来像是request上传地址， 但是服务器返回一个内网ip地址。这个10.0.1.6是部署在Azure上worker节点， 而code在我本地， 访问不到.

**Comment by JimEverest** [comment]
谢谢scarlett2018帮我创建ISSUE， 补充一下：
1. PAI的master和worker都部署在Azure上， 我从本地VS code提交job。
2. 从web hdfs尝试上传的时候， 通过network调试发现两个request。 第一个request（http://master_xxxx.westus2.cloudapp.azure.com:50070/webhdfs/v1/admin/mnist-k1_49eb87bc/mnist.py?op=CREATE&noredirect=true）返回的是一个内网地址， 指向worker的ip:10.0.1.6。 
    {"Location":"http://10.0.1.6:5075/webhdfs/v1/admin/mnist-k1_49eb87bc/mnist.py?op=CREATE&namenoderpcaddress=10.0.1.5:9000&createflag=&createparent=true&overwrite=false"}

    而第二个request直接访问这内网地址导致失败。（ 因为我从我本地上传,访问不到这个Azure的内网ip）

**Comment by NothingLZ** [comment]
@JimEverest  
I have encountered some problems with my deployment on Azure VM. The load-balance-ip configuration in the kubernetes-configuration.yaml file is the external network ip or the internal network ip?

**Comment by NothingLZ** [comment]
> > @JimEverest 
> > 我在Azure VM上部署时遇到了一些问题。kubernetes-configuration.yaml文件中的load-balance-ip配置是外部网络ip还是内部网络ip？
> 
> 内部网络IP 10.0.1.5中load-balance-ip配置的值。


First of all, I have two hosts. I use A to deploy B. So in the quick-start.yaml file, is the master's ip an intranet or an extranet?

**Comment by JimEverest** [comment]
I have 3 nodes deployed dev-box, master & worker1 seperately.  both master's ip and worker1's ip are intranet ip in quick-start.yaml .

**Comment by JimEverest** [comment]
I just create a new windows10 VM within the same vpn sub-net on Azure, and managed to upload a txt file via web-hdfs (master:50070), but failed again. Server didn't return any exception message but the UI appears "Cound't upload the file xxx.txt. ". Btw I can access the hdfs nodes through intranet ip  from browser in the windows VM.

**Comment by NothingLZ** [comment]
> 我只是在Azure上的同一个vpn子网中创建一个新的windows10 VM，并设法通过web-hdfs（master：50070）上传一个txt文件，但又失败了。服务器没有返回任何异常消息，但UI显示“Cound't upload the file xxx.txt。”。顺便说一下，我可以通过Windows VM中的浏览器通过Intranet ip访问hdfs节点。

Then can you access the cluster through the external network ip?

**Comment by JimEverest** [comment]
Yes, I can access kubernetes, Pai, webhdfs through external ip in browser, as well as Pai cluster within VS code. However I just can't upload files to Pai hdfs in neither browser nor Vscode.

**Comment by JimEverest** [comment]
I've added all these inbound port rules for master node:
![wechat image_20181106181053](https://user-images.githubusercontent.com/3079297/48057612-66077c00-e1ef-11e8-9c99-b85662e3d2d2.png)

and rules for worker:
![wechat image_20181106181046](https://user-images.githubusercontent.com/3079297/48057678-964f1a80-e1ef-11e8-9f8c-b9b8a0e919b3.png)

Still stuck at HDFS uploading in VScode.
![wechat image_20181106181404](https://user-images.githubusercontent.com/3079297/48057784-d7dfc580-e1ef-11e8-979f-9ae03c71879a.png)

**Comment by NothingLZ** [comment]
Is it necessary to open swap?
![image](https://user-images.githubusercontent.com/12367891/48113398-aa4d5780-e295-11e8-9d83-180c2eb2619a.png)

![image](https://user-images.githubusercontent.com/12367891/48113398-aa4d5780-e295-11e8-9d83-180c2eb2619a.png)

**Comment by DongZhaoYu** [comment]
@NothingLZ , swap is not needed. Can you check if the port 5075 is accessible on worker node?

**Comment by DongZhaoYu** [comment]
The webhdfs data upload works in two step. First the client sends a request to the name node and it will return a uri to a worker node to store the data. Then the client will use the returned uri to put the data. So in Azure environment, the client cannot directly access the worker node. The upload will fail.

**Comment by NothingLZ** [comment]
![image](https://user-images.githubusercontent.com/12367891/48115351-91e13b00-e29d-11e8-898d-2f75b34bc836.png)

**Comment by NothingLZ** [comment]
![image](https://user-images.githubusercontent.com/12367891/48115441-de2c7b00-e29d-11e8-8052-51511dc2c206.png)

**Comment by DongZhaoYu** [comment]
If your data node has external IP, can you have a check why the hdfs always return the interal ip URI?

In our new release v0.8.0, we have configured pylon to redirect the hdfs requests. You can use webhdfs api to create a file:
curl -i -X PUT "http://master_address:80/webhdfs/api/v1/test/test_file?op=CREATE"
The returned URI will be redirected by pylon to the datanode. So internal IP wouldn't be a problem.

**Comment by NothingLZ** [comment]
![image](https://user-images.githubusercontent.com/12367891/48170160-46786c80-e331-11e8-858d-cd496fcfc7ff.png)

**Comment by NothingLZ** [comment]
![image](https://user-images.githubusercontent.com/12367891/48170647-5c872c80-e333-11e8-96f3-8114bb069198.png)


Do you have a small demo and I want to test it.Because of the official demo, it always fails.

**Comment by DongZhaoYu** [comment]
@NothingLZ  you cannot open that URI by web browser. It is a PUT request, not GET.

**Comment by fanyangCS** [comment]
@Gerhut , can you check if this is due to Pylon config issue?

**Comment by Gerhut** [comment]
Hi @fanyangCS 

It seems WebHDFS uploading through pylon(external IP) has not been used yet, so waiting for further reports.

**Comment by fanyangCS** [comment]
Close as no further response.
