### ISSUE TITLE
hadoop ai needs to be deployed separately?

### ISSUE THREAD

**Issue by NothingLZ** [Microsoft/pai#1666]
![image](https://user-images.githubusercontent.com/12367891/48042097-055e4c00-e1bb-11e8-81a8-0b0f31b30c92.png)

**Comment by mzmssg** [comment]
nope, hadoop-ai have only build process, it will be used as base image in yarn and hdfs deployment.

**Comment by NothingLZ** [comment]
Thank you for your answer
