### ISSUE TITLE
provide NVIDIA_VISIBLE_DEVICES environment variable to nvidia-container-runtime

### ISSUE THREAD

**Issue by xudifsd** [Microsoft/pai#1667]
Currently, we use `--device=/dev/nvidia0` to tell docker isolate gpu for jobs. But this parameter seems is ignored by `nvidia-container-runtime`. If we want to achieve same effect of gpu isolation, we should pass NVIDIA_VISIBLE_DEVICES to `docker run` like `-e NVIDIA_VISIBLE_DEVICES=0,1`.

**Comment by YanjieGao** [comment]
supplyment:

currently, pai default marked it with all at job docker base image, later change need consider make this configurable or overwrite this config.
https://github.com/Microsoft/pai/blob/e8e21cda23894224a0c78e44caaedb487bce1042/examples/Dockerfiles/cuda9.0-cudnn7/Dockerfile.build.base#L67

**Comment by xudifsd** [comment]
this variable can be override by `-e` parameter.

**Comment by abuccts** [comment]
@xudifsd 

If you use `nvidia-container-runtime` as Docker runtime to start Docker, the container will be started in `privileged` mode and all gpu devices will be mount into Docker container.

Although `NVIDIA_VISIBLE_DEVICES` can be used to select gpu ids, but it CANNOT be used to isolate gpu devices. User can overwrite the `NVIDIA_VISIBLE_DEVICES` env variable easily to use all gpu devices on the host. In fact, deep learning frameworks may set that env variable to `all` by default.

BTW, why do you need to use `nvidia-container-runtime`? Won't `nvidia-docker2` be better?

**Comment by xudifsd** [comment]
@abuccts Why `NVIDIA_VISIBLE_DEVICES ` can not be used to isolate gpu? This environment variable will be used in yarnScript before `docker run`. User can overwrite the variable, of course, but by the time they can, the nvidia runtime has set gpu isolation already. Am I right?

`nvidia-docker2`'s only value is to provide a [`--runtime=nvidia`](https://github.com/NVIDIA/nvidia-docker/blob/master/nvidia-docker#L14) before call actual `docker run`, the gpu isolation's work is done via `nvidia-container-runtime`. This is why I only install `nvidia-container-runtime` not `nvidia-docker2`. Am I missing something?

**Comment by abuccts** [comment]
`--env` passed to `docker run` is equal to `export` inside a Docker container. After `docker run -e VAR1=value1`, `export VAR1=value2` will change its value inside the container.

**Comment by xudifsd** [comment]
@abuccts So, if user's task image defined `export NVIDIA_VISIBLE_DEVICES=all`, no matter what value of `-e NVIDIA_VISIBLE_DEVICES`, the nvidia-container-runtime will give all gpus to the task? Have you verified this?

**Comment by xudifsd** [comment]
@abuccts I have verified, the -e will override ENV in dockerfile, not other way around.

In a docker configured with `default-runtime=nvidia` and docker image with `ENV NVIDIA_VISIBLE_DEVICES=all`, `docker run -e NVIDIA_VISIBLE_DEVICES=0,1` will still isolate the gpu as expected.

**Comment by xudifsd** [comment]
Because GPU minor number may not necessarily [same](https://github.com/NVIDIA/nvidia-docker/wiki/GPU-isolation-(version-1.0)) with device minor number, we can not pass the same minor number to both --device argument and as NVIDIA_VISIBLE_DEVICES environment. For example, in node with different GPU/device minor number:

```
$ sudo docker run -it --device=/dev/nvidiactl --device=/dev/nvidia-uvm --device=/dev/nvidia0 --volume /var/drivers/nvidia/current:/usr/local/nvidia:ro -e LD_LIBRARY_PATH=/usr/local/nvidia/lib/:/usr/local/nvidia/lib64 --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=0 ubuntu:16.04 /usr/local/nvidia/bin/nvidia-smi -L
GPU 0: Tesla K80 (UUID: GPU-6f233ab5-200d-f809-b2d6-8d9909735d41)
GPU 1: Tesla K80 (UUID: GPU-36a06e86-501a-6f52-3938-13a884435fe0)
```

although we pass `--device=/dev/nvidia0` and `-e NVIDIA_VISIBLE_DEVICES=0`, but they mean different devices to nvidia-container-runtime, so it will mount 2 device into container, this is not what we want. To avoid this, we need to set NVIDIA_VISIBLE_DEVICES to empty, and only relay on --device arguments in case nvidia-container-runtime enabled.

It is important to set NVIDIA_VISIBLE_DEVICES as empty, because if not, image which set NVIDIA_VISIBLE_DEVICES=all will still be able to use all GPUs if the runtime is nvidia-container-runtime:

```
$ for i in `seq 0 3` ; do echo $i; sudo docker run -it --device=/dev/nvidiactl --device=/dev/nvidia-uvm --device=/dev/nvidia$i --device=/dev/fuse --volume /var/drivers/nvidia/current:/usr/local/nvidia:ro -e LD_LIBRARY_PATH=/usr/local/nvidia/lib/:/usr/local/nvidia/lib64 --runtime=nvidia openpai/pai.example.tensorflow /usr/local/nvidia/bin/nvidia-smi -L; done
0
GPU 0: Tesla K80 (UUID: GPU-6f233ab5-200d-f809-b2d6-8d9909735d41)
GPU 1: Tesla K80 (UUID: GPU-0ec71ff9-8bb2-c756-ecad-623cee39da97)
GPU 2: Tesla K80 (UUID: GPU-43ffb100-5348-2276-8ae1-ddc6574f1520)
GPU 3: Tesla K80 (UUID: GPU-36a06e86-501a-6f52-3938-13a884435fe0)
1
GPU 0: Tesla K80 (UUID: GPU-6f233ab5-200d-f809-b2d6-8d9909735d41)
GPU 1: Tesla K80 (UUID: GPU-0ec71ff9-8bb2-c756-ecad-623cee39da97)
GPU 2: Tesla K80 (UUID: GPU-43ffb100-5348-2276-8ae1-ddc6574f1520)
GPU 3: Tesla K80 (UUID: GPU-36a06e86-501a-6f52-3938-13a884435fe0)
2
GPU 0: Tesla K80 (UUID: GPU-6f233ab5-200d-f809-b2d6-8d9909735d41)
GPU 1: Tesla K80 (UUID: GPU-0ec71ff9-8bb2-c756-ecad-623cee39da97)
GPU 2: Tesla K80 (UUID: GPU-43ffb100-5348-2276-8ae1-ddc6574f1520)
GPU 3: Tesla K80 (UUID: GPU-36a06e86-501a-6f52-3938-13a884435fe0)
3
GPU 0: Tesla K80 (UUID: GPU-6f233ab5-200d-f809-b2d6-8d9909735d41)
GPU 1: Tesla K80 (UUID: GPU-0ec71ff9-8bb2-c756-ecad-623cee39da97)
GPU 2: Tesla K80 (UUID: GPU-43ffb100-5348-2276-8ae1-ddc6574f1520)
GPU 3: Tesla K80 (UUID: GPU-36a06e86-501a-6f52-3938-13a884435fe0)
```

But if we set to empty, we can override environments set by image:
```
$ for i in `seq 0 3` ; do echo $i; sudo docker run -it --device=/dev/nvidiactl --device=/dev/nvidia-uvm --device=/dev/nvidia$i --device=/dev/fuse --volume /var/drivers/nvidia/current:/usr/local/nvidia:ro -e LD_LIBRARY_PATH=/usr/local/nvidia/lib/:/usr/local/nvidia/lib64 --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES= openpai/pai.example.tensorflow /usr/local/nvidia/bin/nvidia-smi -L; done
0
GPU 0: Tesla K80 (UUID: GPU-36a06e86-501a-6f52-3938-13a884435fe0)
1
GPU 0: Tesla K80 (UUID: GPU-6f233ab5-200d-f809-b2d6-8d9909735d41)
2
GPU 0: Tesla K80 (UUID: GPU-0ec71ff9-8bb2-c756-ecad-623cee39da97)
3
GPU 0: Tesla K80 (UUID: GPU-43ffb100-5348-2276-8ae1-ddc6574f1520)
```
