### ISSUE TITLE
Config files generation fail in dev-box

### ISSUE THREAD

**Issue by leonfg** [Microsoft/pai#1681]
pai version: 0.8.0
`
python paictl.py config generate -i /pai/deployment/quick-start/quick-start.yaml -o ~/pai-config -f
`
This command will return error message 'ImportError: No module named git'. That means users should install python-git in dev-box before deployment pai.
I think this package should be integrated in dev-box image, or at least add installation procedure in deployment guide document.

**Comment by DongZhaoYu** [comment]
GitPython is required to run the PAI command. This should be installed on dev-box.

**Comment by mzmssg** [comment]
It has been installed 
https://github.com/Microsoft/pai/blob/b75ec9e102b41eb7882ddc261e64d387481aee2f/src/dev-box/build/dev-box.dockerfile#L54

Do you use the latest dev-box？

**Comment by DongZhaoYu** [comment]
checked on openpai/dev-box:v0.8.0 image, the git module can be imported.

**Comment by leonfg** [comment]
> 
> 
> It has been installed
> 
> [pai/src/dev-box/build/dev-box.dockerfile](https://github.com/Microsoft/pai/blob/b75ec9e102b41eb7882ddc261e64d387481aee2f/src/dev-box/build/dev-box.dockerfile#L54)
> 
> Line 54 in [b75ec9e](/Microsoft/pai/commit/b75ec9e102b41eb7882ddc261e64d387481aee2f)
>  pip install python-etcd docker kubernetes GitPython 
> 
> Do you use the latest dev-box？

I am not sure if I reinstalled latest dev-box image yesterday. may be I used old version.
