### ISSUE TITLE
Service problem

### ISSUE THREAD

**Issue by NothingLZ** [Microsoft/pai#1684]
![image](https://user-images.githubusercontent.com/12367891/48239780-3634c000-e40b-11e8-9593-fe70f3dc6c51.png)
![image](https://user-images.githubusercontent.com/12367891/48239825-5bc1c980-e40b-11e8-9ea4-9ecc10a84513.png)

what happened?

**Comment by xudifsd** [comment]
What's wrong?

**Comment by NothingLZ** [comment]
![image](https://user-images.githubusercontent.com/12367891/48324241-f4a25000-e66a-11e8-91ac-eb3fd4886563.png)

**Comment by NothingLZ** [comment]
![image](https://user-images.githubusercontent.com/12367891/48325005-819ad880-e66e-11e8-9015-794cc8e27c56.png)


![image](https://user-images.githubusercontent.com/12367891/48325021-9bd4b680-e66e-11e8-8b1e-f7f29e04b585.png)

**Comment by xudifsd** [comment]
Contents in `cluster-configuration.yaml` please.

**Comment by NothingLZ** [comment]
![image](https://user-images.githubusercontent.com/12367891/48325230-94fa7380-e66f-11e8-8db0-c837ee9f4a40.png)

**Comment by xudifsd** [comment]
do you have hadoop-resource-manager up and running?

**Comment by NothingLZ** [comment]
![image](https://user-images.githubusercontent.com/12367891/48325582-4ea61400-e671-11e8-89c8-2b9c99d93575.png)

**Comment by xudifsd** [comment]
what about prometheus and node-exporter. Do you encountered error when opening virtual clusters page?

**Comment by xudifsd** [comment]
@NothingLZ 0 in virtual clusters means you didn't use any cpu/memory/gpu. That's indicate how much you used, not how much you can use.

**Comment by NothingLZ** [comment]
![image](https://user-images.githubusercontent.com/12367891/48332069-76a37080-e68d-11e8-8415-76e126d51abc.png)

**Comment by NothingLZ** [comment]
![image](https://user-images.githubusercontent.com/12367891/48332113-9d61a700-e68d-11e8-951f-a5d66e33fd22.png)

**Comment by xudifsd** [comment]
Ok, I think this solve your problem?

**Comment by NothingLZ** [comment]
Thank you for your answer, I will study again.

**Comment by xudifsd** [comment]
Ok, I'll close this issue.
