### ISSUE TITLE
job submit

### ISSUE THREAD

**Issue by NothingLZ** [Microsoft/pai#1695]
![image](https://user-images.githubusercontent.com/12367891/48385559-ecf5b080-e729-11e8-8006-45ce8ab4eb67.png)
![image](https://user-images.githubusercontent.com/12367891/48385661-4067fe80-e72a-11e8-8c05-8c56f0bdb312.png)

![image](https://user-images.githubusercontent.com/12367891/48385593-0ac31580-e72a-11e8-949e-533dd9f46730.png)
![image](https://user-images.githubusercontent.com/12367891/48385618-20383f80-e72a-11e8-92d3-54b45acea028.png)

**Comment by NothingLZ** [comment]
![image](https://user-images.githubusercontent.com/12367891/48393242-bf206400-e749-11e8-9ac9-87089f9dddc2.png)


![image](https://user-images.githubusercontent.com/12367891/48393206-9ac48780-e749-11e8-9506-062bf7f34df6.png)

**Comment by NothingLZ** [comment]
![image](https://user-images.githubusercontent.com/12367891/48394169-79fe3100-e74d-11e8-8bcb-76b0920caccb.png)
 

where ???

![image](https://user-images.githubusercontent.com/12367891/48394200-90a48800-e74d-11e8-9913-36d46ea0e2cc.png)

**Comment by NothingLZ** [comment]
![image](https://user-images.githubusercontent.com/12367891/48397596-301b4800-e759-11e8-8438-d8186a401f4b.png)
![image](https://user-images.githubusercontent.com/12367891/48397604-3b6e7380-e759-11e8-8dbb-4cdc4fa494e7.png)
Can this configuration be?

**Comment by fanyangCS** [comment]
no response. close
