### ISSUE TITLE
Resource lost on some node

### ISSUE THREAD

**Issue by mzmssg** [Microsoft/pai#1698]
![image](https://user-images.githubusercontent.com/11887940/48456678-e1be8580-e7fa-11e8-8b4c-73e63c731dae.png)

**Comment by mzmssg** [comment]
These two VMs do be different type.

**Comment by fanyangCS** [comment]
@mzmssg , "These two VMs do be different type." I am not sure I fully understand this. Can you explain it in more details when you have time?

**Comment by mzmssg** [comment]
@fanyangCS  I check our VM list, these 2 VMs are NC6 type, while the others are NC24r. So the resource view is as expected.
