### ISSUE TITLE
Node didn't have enough resource

### ISSUE THREAD

**Issue by shawntian90** [Microsoft/pai#1702]
hi,

When setup a openpai cluster (version `v0.8.0`) with limit resource, which:

- master node: 4 CPU cores, 16 GB Mems
- worker node: 4 CPU cores, 30 GB mems, 1 GPU

When I run bootup command:

```bash
python paictl.py cluster k8s-bootup -p /cluster-configuration
```
It failed, because of following reasons via `docker logs -f kubelet` on master node:

```
I1115 05:47:30.885424    4948 predicate.go:124] Predicate failed on Pod: hadoop-name-node-ds-ff8v6_default(f12ef722-e899-11e8-9014-00163e2e4037), for reason: Node didn't have enough resource: memory, requested: 8589934592, used: 10200547328, capacity: 12764162650
I1115 05:47:31.480108    4948 kubelet.go:1873] SyncLoop (DELETE, "api"): "hadoop-name-node-ds-ff8v6_default(f12ef722-e899-11e8-9014-00163e2e4037)"
I1115 05:47:31.482444    4948 kubelet.go:1867] SyncLoop (REMOVE, "api"): "hadoop-name-node-ds-ff8v6_default(f12ef722-e899-11e8-9014-00163e2e4037)"
I1115 05:47:31.495279    4948 kubelet.go:2061] Failed to delete pod "hadoop-name-node-ds-ff8v6_default(f12ef722-e899-11e8-9014-00163e2e4037)", err: pod not found
I1115 05:47:31.495321    4948 kubelet.go:1857] SyncLoop (ADD, "api"): "hadoop-name-node-ds-nbz4c_default(f18a795a-e899-11e8-9014-00163e2e4037)"
I1115 05:47:31.495455    4948 predicate.go:124] Predicate failed on Pod: hadoop-name-node-ds-nbz4c_default(f18a795a-e899-11e8-9014-00163e2e4037), for reason: Node didn't have enough resource: memory, requested: 8589934592, used: 10200547328, capacity: 12764162650
I1115 05:47:32.080681    4948 kubelet.go:1873] SyncLoop (DELETE, "api"): "hadoop-name-node-ds-nbz4c_default(f18a795a-e899-11e8-9014-00163e2e4037)"
```

I can not upgrade my hardware. Is there any way to ignore this resource requirement ?

I try to edit the file
> src/hadoop-name-node/deploy/hadoop-name-node.yaml.template

and change lines to: 

```
        ....
        resources:
          limits:
            memory: "1Gi" # change this line from 8Gi to 1Gi
```
But it does not work at all.

Thanks for help!

**Comment by hao1939** [comment]
Hi @shawntian90,

You can refer to this page for the resource requirement: https://github.com/Microsoft/pai/wiki/Resource-Requirement.
As you already know, you could change the requirement via editing the code.
So, you should:

1. Figure out which role (master or work) didn't have enough resource. You can refer to the k8s dashboard on http://master_node_ip:9090/, viewing the nodes details.
2. After you change the code, you may need to **delete the services** first. That's maybe your problem.

Regards,
Hao

**Comment by shawntian90** [comment]
I figure it out via:

1. Edit the template file of  `hadoop-name-node`
2.  Run `cluster k8s-bootup`, and ignore any error
3. Run `service start`, and it will generate `xxx.yml` file from `xxx.yml.template`; Then the kubectl will success.

Questions: Why not just generate `*.yml` while run `cluster k8s-bootup`? It will save lot's error log.
