### ISSUE TITLE
OpenPAI page don't show the utilization of the GPU.

### ISSUE THREAD

**Issue by lllllwwwwyyyy** [Microsoft/pai#1719]
![image](https://user-images.githubusercontent.com/10185324/48626437-cfa43900-e9ec-11e8-87da-fa26abefdc0a.png)
![image](https://user-images.githubusercontent.com/10185324/48626444-d29f2980-e9ec-11e8-9806-3f19f0c10236.png)
I run the example job `tensorflow-cifar10`
The config show below:
`{

  "jobName": "tensorflow-cifar10",

  "image": "openpai/pai.example.tensorflow:stable",

  "dataDir": "/lwy/datadir",

  "outputDir": "/lwy/outputdata",

  "taskRoles": [

    {

      "name": "cifar_train",

      "taskNumber": 1,

      "cpuNumber": 1,

      "memoryMB": 32768,

      "gpuNumber": 2,

      "command": "git clone https://github.com/tensorflow/models && cd models/research/slim && python download_and_convert_data.py --dataset_name=cifar10 --dataset_dir=$PAI_DATA_DIR && python train_image_classifier.py --batch_size=64 --model_name=inception_v3 --dataset_name=cifar10 --dataset_split_name=train --dataset_dir=$PAI_DATA_DIR --train_dir=$PAI_OUTPUT_DIR"

    }

  ]

}`
But when it is running,the page do not show the utilization of GPU.

**Comment by lllllwwwwyyyy** [comment]
below is my dir:(in the hdfs webportal)
![image](https://user-images.githubusercontent.com/10185324/48626641-607b1480-e9ed-11e8-849b-8564f2683c4b.png)
![image](https://user-images.githubusercontent.com/10185324/48626650-653fc880-e9ed-11e8-874a-c3958291d4ad.png)

**Comment by lllllwwwwyyyy** [comment]
Below is my datadir :  in the hdfs webportal 
![image](https://user-images.githubusercontent.com/10185324/48626699-86a0b480-e9ed-11e8-9f5e-3321eb2eff53.png)

![image](https://user-images.githubusercontent.com/10185324/48626673-7b4d8900-e9ed-11e8-92a9-0d6ed305c4f4.png)

**Comment by lllllwwwwyyyy** [comment]
![image](https://user-images.githubusercontent.com/10185324/48655126-563d3280-ea4e-11e8-9f33-fdbf76c4125f.png)
Is there a problem with the configuration?

**Comment by mzmssg** [comment]
Could you make sure this job is running with GPU but CPU? You could either `ssh` or `docker exec` into it, then run `nvidia-smi` to verify.


It is very helpful if log is available.

**Comment by lllllwwwwyyyy** [comment]
![image](https://user-images.githubusercontent.com/10185324/48684358-452a2800-ebec-11e8-87cb-853a8d66bd65.png)
I think it is using GPU. I run the cifa-10 example
The log:
![image](https://user-images.githubusercontent.com/10185324/48684387-625ef680-ebec-11e8-92a0-9561127f9c74.png)
![image](https://user-images.githubusercontent.com/10185324/48684401-6d198b80-ebec-11e8-99a6-8a0036746beb.png)

**Comment by mzmssg** [comment]
@xudifsd Seems exporter doesn't collect GPU metrics?

**Comment by lllllwwwwyyyy** [comment]
> 
> 
> @xudifsd Seems exporter doesn't collect GPU metrics?

![image](https://user-images.githubusercontent.com/10185324/48686843-2e3e0280-ebf9-11e8-8e7d-4a84b033733c.png)
K8s has this filed

**Comment by xudifsd** [comment]
what's your job-exporter container's version? 0.8.0?

**Comment by xudifsd** [comment]
Also, can you provide logs of job-exporter?

**Comment by xudifsd** [comment]
Oh, I suspect you got bite by #1704 . job-exporter will hangs on iftop call, which will cause job-exporter failed to create job_exporter.prom file, and readiness probe will throw error `No such file` you mentioned.

Can you check this?

You can ssh into your node and then docker exec into job-exporter container and call iftop directly to see if it uses virtual bridge. You should use `docker exec` instead of `kubectl exec` because we enforced [DenyEscalatingExec](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#denyescalatingexec).

**Comment by lllllwwwwyyyy** [comment]
> 
> 
> what's your job-exporter container's version? 0.8.0?

![image](https://user-images.githubusercontent.com/10185324/48749350-7884b980-ecb5-11e8-9ddc-1c95ec0d3bdb.png)
Yes,v0.8.0

The logs of the job-exporter:
![image](https://user-images.githubusercontent.com/10185324/48749382-b1bd2980-ecb5-11e8-8713-db2872e813fd.png)

I exec the job-exporter container and call iftop.I get this 
![image](https://user-images.githubusercontent.com/10185324/48749511-3b6cf700-ecb6-11e8-8a7e-7994801f9850.png)

**Comment by xudifsd** [comment]
ok, what's `eno1` interface? physical network interface? Could you please execute this command `iftop -t -P -s 1 -L 10000 -B -n -N` in problematic job-exporter container? Is it hangs?

**Comment by lllllwwwwyyyy** [comment]
I use single box deploy and enter the job-container container.  
![image](https://user-images.githubusercontent.com/10185324/48755686-25206480-ecd1-11e8-85c9-119c5d3a6b0a.png)

**Comment by xudifsd** [comment]
Can you list all your network interface? `ifconfig` should output that.

**Comment by lllllwwwwyyyy** [comment]
> Can you list all your network interface? `ifconfig` should output that.

![image](https://user-images.githubusercontent.com/10185324/48759396-ea70f900-ecdd-11e8-9e2d-f91347339052.png)
![image](https://user-images.githubusercontent.com/10185324/48759402-ef35ad00-ecdd-11e8-87e9-8a0be291d207.png)

**Comment by xudifsd** [comment]
@lllllwwwwyyyy Ok, it's because node-exporter hangs on iftop commands. Later we'll add several commits to address this issue. You can delete problematic node-exporter pod via kubectl or k8s dashboard, iftop will select interface randomly, and hopefully it can listen on the interface `eno2`. Or you can modify source code of [job-exporter](https://github.com/Microsoft/pai/blob/master/src/job-exporter/src/network.py#L65) directly, and add `-i eno2` arguments to iftop command, and push images to registry.

**Comment by lllllwwwwyyyy** [comment]
> @lllllwwwwyyyy Ok, it's because node-exporter hangs on iftop commands. Later we'll add several commits to address this issue.
> 
> To mitigate your problem, you can delete problematic node-exporter pod via kubectl or k8s dashboard, iftop will select interface randomly, and hopefully it can listen on the interface `eno2`. Or you can modify source code of [job-exporter](https://github.com/Microsoft/pai/blob/master/src/job-exporter/src/network.py#L65) directly, and add `-i eno2` arguments to iftop command, and push images to registry.
If dev-box:v0.8.1 has fixed this problem?

**Comment by lllllwwwwyyyy** [comment]
> @lllllwwwwyyyy Ok, it's because node-exporter hangs on iftop commands. Later we'll add several commits to address this issue.
> 
> To mitigate your problem, you can delete problematic node-exporter pod via kubectl or k8s dashboard, iftop will select interface randomly, and hopefully it can listen on the interface `eno2`. Or you can modify source code of [job-exporter](https://github.com/Microsoft/pai/blob/master/src/job-exporter/src/network.py#L65) directly, and add `-i eno2` arguments to iftop command, and push images to registry.

If dev-box:v0.8.1 has fixed this problem?

**Comment by xudifsd** [comment]
No, it was scheduled to be fixed in 0.9.x

**Comment by fanyangCS** [comment]
close and track in #1764
