### ISSUE TITLE
node exporter readiness probe failed, maybe race condition

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#1724]
node-exporter readiness failed on int-bed:

![image](https://user-images.githubusercontent.com/1547343/48748513-242c0a80-ecb2-11e8-83e9-c36152b4e6f1.png)
`Readiness probe failed: Traceback (most recent call last): File "/job_exporter/no_older_than.py", line 42, in <module> check_no_older_than(args.paths, args.delta) File "/job_exporter/no_older_than.py", line 33, in check_no_older_than raise RuntimeError("{} was updated more than {} seconds ago".format(path, delta)) RuntimeError: /datastorage/prometheus/job_exporter.prom was updated more than 0:02:00 seconds ago`

It's keeping failure for days.

**Comment by xudifsd** [comment]
The last log entry is
```
2018-11-19 02:32:13,000 - INFO - docker_stats.py:92 - ready to run docker stats
```

which was printed out 1 day ago, the main thread of job-exporter hangs on call of `docker stats`.

**Comment by xudifsd** [comment]
close in favor of #1729
