### ISSUE TITLE
make job-exporter resistant to command hangs

### ISSUE THREAD

**Issue by xudifsd** [Microsoft/pai#1729]
current job-exporter is single threaded model, should add some timeout when calling subcommand, since most of commands called by job-exporter are prone to hangs:
* docker stats --no-stream --format "table {{.Container}},{{.Name}},{{.CPUPerc}},{{.MemUsage}},{{.NetIO}},{{.BlockIO}},{{.MemPerc}}"
* docker inspect $container_id
* docker logs --tail all $container_id
* systemctl is-active docker | if [ $? -eq 0 ]; then echo "active"; else exit 1; fi
* nvidia-smi -q -x
* iftop -t -P -s 1 -L 10000 -B -n -N
* infilter $pid /usr/bin/lsof -I -n -P

related issues:
* #1724 
* #1719 
* #842

**Comment by fanyangCS** [comment]
close and track the problem in #1764
