### ISSUE TITLE
[feature request] Support mount local volume

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#1731]
In case we want to extend PAI, especially run a service on PAI, we will need local volume support.
Currently we have below limitations keeping in mind:

1. Local volume is for services, does not recommend for train job.
2. PAI won't maintain storage HA, and won't guarantee the container and volume on the some node.
3. It's should design as a temporal storage, like a cache.

**Comment by hao1939** [comment]
Hi @ydye ,
I create this issue for tracking, we can sync later about the details.

**Comment by ydye** [comment]
I think the first point is reasonable. I don't want to expose the local disk for the train job.

**Comment by fanyangCS** [comment]
This is a violation of micro-service: the mount point becomes obscure and is not an explicit service end-point. People cannot differentiate local mount from remote mount. and this has been an issue for other latform for a long time.
