### ISSUE TITLE
Improve deployment process, reduce the time cost

### ISSUE THREAD

**Issue by hao1939** [microsoft/pai#1733]
It's a long run task, put it here for tracking.
Will need to break into in detail tasks later.

**Comment by scarlett2018** [comment]
@hao1939 - this is a great topic, we need to have a baseline for this first, and few target metrics.

**Comment by scarlett2018** [comment]
Converting the issue to Epic, so we can break it down to executable sub issues.

**Comment by fanyangCS** [comment]
closed and track in #4022
