### ISSUE TITLE
How I update image inside a contain [User]

### ISSUE THREAD

**Issue by zhuangyueqing** [Microsoft/pai#1738]
I am a user, but I found that it cannot self-update to dock hub. I want to know how to self-update image inside an contains. Thank you!

**Comment by zhuangyueqing** [comment]
The answer is not about my question in stackoverflow, my question is that OpenPAI,  I can only access to the containers because I cannot access to host.  So I want to update my image inside contains to preserve changes.  But it seem that openai have no feature to do that.

**Comment by fanyangCS** [comment]
I am not sure if you can do that at all. A possible way is to keep the change outside of the docker instance (e.g., kept in a persistent storage like hdfs), and update the docker image externally later on.
