### ISSUE TITLE
How to change the NVIDIA driver version in tag.0.8.1 ??

### ISSUE THREAD

**Issue by GeoffreyChen777** [Microsoft/pai#1742]
I use the tag:0.8.1 to deploy my cluster.

I set the `nvidia-drivers-version: 410.73` in `~/pai-config/services-configuration.yaml`

but it is not working. I check the log of drivers-one-shot, and the driver version is 384.111

Is 384.111 the only version in tag:0.8.1 ?

Thanks!

**Comment by ydye** [comment]
Hi @GeoffreyChen777 , sorry about this. But the new drivers version isn't enable at ```v0.8.1```. And in that release, only 384.111 is supported.

**Comment by GeoffreyChen777** [comment]
Got it.
