### ISSUE TITLE
Build yarn-frameworklauncher failed: "Error: Could not find or load main class org.apache.maven.surefire.booter.ForkedBooter"

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#1743]
In short: Surefire manifest jar classloading broken on latest Debian/Ubuntu Java8, so 'mvn test' would faild.

The easiest workaround would be edit the `build.sh` and change the line to  `run mvn -DskipTests clean install`: https://github.com/Microsoft/pai/blob/fd82bb0820127402f8d88aecd637f38de4bb4388/subprojects/frameworklauncher/yarn/build.sh#L45

More details in below threads:
https://issues.apache.org/jira/browse/SUREFIRE-1588
https://stackoverflow.com/a/53016532/500268

**Comment by yqwang-ms** [comment]
It is a recent issue? why did not we find it before?

**Comment by hao1939** [comment]
It's because of recently openjdk-8 update.
CI still working because of docker cache.

**Comment by yqwang-ms** [comment]
Can we do not use this bad openjdk version, it is bug in the openjdk-8 package. We do not need to fix for it if this version is not required.

**Comment by hao1939** [comment]
Locking the jdk version would be a solution.
Currently we sudo `apt-get update` in dockerfile, which will always upgrade jdk.

**Comment by yqwang-ms** [comment]
Sure, please try lock version or avoid bad version first?

**Comment by fanyangCS** [comment]
@yqwang-ms , if this is a build issue, seems you are the one to fix it?

**Comment by wangcan0329** [comment]
I think we can fix the issue by locking jdk version in dev-box docker image.

**Comment by fanyangCS** [comment]
related. https://github.com/Microsoft/pai/issues/157
fixed by fixing the jdk version: https://github.com/Microsoft/pai/pull/2097
