### ISSUE TITLE
how add new machine 

### ISSUE THREAD

**Issue by szxdlut** [Microsoft/pai#1745]
when i add machine use command:  python paictl.py machine add  -p ~/pai-config  -l machine-list.yaml , the new node only run k8s services and openpai services not run.how start openpai services on this node?

is there detail docs

**Comment by fanyangCS** [comment]
which version do you use? I assume you check out a release branch?

**Comment by ydye** [comment]
After the kubernetes node is joined into your cluster, you should do following steps to start pai service on the target node.
- Add the node config into cluster-configuration.yaml
- Run the following command to label the new node according to its role.
```
./paictl.py service start -p /path/to/cluster-config -n cluster-configuration
```

**Comment by szxdlut** [comment]
> which version do you use? I assume you check out a release branch?

version 0.8.0

**Comment by fanyangCS** [comment]
@ydye , maybe you can update the document accordingly.

**Comment by ydye** [comment]
https://github.com/Microsoft/pai/pull/1750

**Comment by ydye** [comment]
The pull request is merged into the release branch.
I will close this issue.
