### ISSUE TITLE
Webportal display the wrong GPU usage ratio: 179% allocated GPUs

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#1748]
![image](https://user-images.githubusercontent.com/1547343/48926928-14f4c900-ef0d-11e8-857a-aca5dcd23584.png)

Here's the dashboard: http://65.52.108.125:86/dashboard.html.

**Comment by xudifsd** [comment]
close in favor of #1749

**Comment by hao1939** [comment]
Hi @xudifsd ,

I want more discussion here.
It makes sense to let user configure all the resource available in a cluster.
But how to support decommission? Are we only support a static cluster?

**Comment by hao1939** [comment]
Great.
I tried to fix the error via `service refresh`, but it doesn't work:

1. After the refresh, grafana and prometheus doesn't work properly, there's some errors.
2. And the node-exporter doesn't restart, so it still displaying the wrong numbers.

Could we fix the `refresh` behavior for those services in the same time? Or how could user fix the configuration mistake?

**Comment by xudifsd** [comment]
[refresh](https://github.com/Microsoft/pai/blob/master/src/node-exporter/deploy/refresh.sh) in node-exporter doesn't do anthing.

**Comment by hao1939** [comment]
Yeah, that's problem, according to the change, it should do something now.

**Comment by xudifsd** [comment]
I'm not sure what we expect from `refresh`, maybe just a shortcut of `stop` & `start`?

**Comment by hao1939** [comment]
Hi @xudifsd ,

Back to the requirement, what we need is some way user could fix the configuration mistake.
`service refresh` is the first idea comes out, we are not sticking to the solution.

**Comment by xudifsd** [comment]
yeah, I was proposing implement `refresh` using `stop` & `start`

**Comment by hao1939** [comment]
After refresh the configuration, I manually `stop then start` node-exporter, it works.

**Comment by hao1939** [comment]
@xudifsd ,
Have we implemented the `refresh` for node-exporter?

**Comment by xudifsd** [comment]
No, could we implement refresh using stop & start?

**Comment by hao1939** [comment]
Yes, I think so.
