### ISSUE TITLE
UI: Job retried several times, but the UI "Retries" still display "0"

### ISSUE THREAD

**Issue by qinchen123** [Microsoft/pai#175]
Job sample: E2E_TEST_64_1_3
Job sample: E2E_TEST_KillAll_128GPU

**Comment by fanyangCS** [comment]
this is because launcher differentiate retries due to different cause (system, user, etc.). need to come up a better way to show user the retry count

**Comment by hwuu** [comment]
Solved in https://github.com/Microsoft/pai/pull/210.
