### ISSUE TITLE
[what to contribute] design of virtual cluster?

### ISSUE THREAD

**Issue by xwzheng1020** [Microsoft/pai#1754]
![image](https://user-images.githubusercontent.com/26718839/48979733-0fa8a180-f0fa-11e8-97f0-a2176af140e9.png)

# admin
1. using vcmod to manage configuration（related issues: #906 ）
2. using vcuser to control accessiblity
3. using vcstat to show statitics of all vcs
# general users
1. know which vc can be accessed
2. know the capacity and load of the vc

**Comment by mzmssg** [comment]
You could refer to this branch api doc, notice it is still in updating. Now it support full `vcmod` and part `vcstat`
https://github.com/Microsoft/pai/blob/zimiao/queue_zookeeper/docs/rest-server/API.md

I will fork a new branch for whole vc updating feature later, we could keep this issue to track it.

**Comment by mzmssg** [comment]
I folk a [new branch](https://github.com/Microsoft/pai/tree/vc_update), we could collabrate on it. You could refer its [doc](https://github.com/Microsoft/pai/blob/vc_update/docs/rest-server/API.md) for your dev

**Comment by xwzheng1020** [comment]
I have push a design [here](https://github.com/Leinao/pai/blob/vc_update/docs/rest-server/design-of-vc-update.md). Need suggestions. thx.

**Comment by fanyangCS** [comment]
Code complete. 
https://github.com/Microsoft/pai/pull/1974
https://github.com/Microsoft/pai/pull/1985
https://github.com/Microsoft/pai/pull/1991
https://github.com/Microsoft/pai/pull/2055
