### ISSUE TITLE
Could Job `Duration` display the `duration of each retry` in addition?

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#1755]
Now the job `Duration` counts from the begin of the job, no matter how many times it retried.
Could we add an addition `latest retry duration`?
Or can we list the `duration` of each retry separately?

For the below screenshot, the `latest retry` started 4 hours again.
![image](https://user-images.githubusercontent.com/1547343/48996123-df0e4980-f185-11e8-9f25-f6448014cbc2.png)

**Comment by fanyangCS** [comment]
if you click the reties count, you will find the details of each retry, including the duration.
