### ISSUE TITLE
when redeployment  the cluster,all job lost from UI

### ISSUE THREAD

**Issue by szxdlut** [Microsoft/pai#1757]
when i redeployment  the cluster,all job lost from UI, but hdfs has those job data. is there other operator to do after redeployment  the cluster?

**Comment by ydye** [comment]
How did you clean your cluster?

**Comment by szxdlut** [comment]
stop and rm all docker containers use docker command

**Comment by fanyangCS** [comment]
rm all docker containers will result in job lost. please use paictl to upgrade pai service or redeployment
