### ISSUE TITLE
Add an email entry in user info

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#1758]
So admin can contact user when needed.

**Comment by YanjieGao** [comment]
it is useful. For this case:hdfs usage very high for a specific folder. need email to contact them.

**Comment by fanyangCS** [comment]
to solve this, we should connect the platform to an AD (e.g., Azure AD).

**Comment by hao1939** [comment]
Hi @fanyangCS ,

AD may be the long term solution.
What ever, there would be benefit to put an email. It could be a mitigate.
How do you think about?

**Comment by fanyangCS** [comment]
let's enforce an operation rule to mitigate this: a user account name should match user alias.
