### ISSUE TITLE
broken link of pai wiki maintain machine & service

### ISSUE THREAD

**Issue by YanjieGao** [microsoft/pai#1763]
https://github.com/Microsoft/pai/wiki/Maintenance-(Service-&-Machine)

such as:
https://github.com/Microsoft/pai/blob/master/pai-management/doc/service-maintain.md#Service_Delete

**Comment by xudifsd** [comment]
can we use broken link check for wiki too?

**Comment by YanjieGao** [comment]
not sure, previous broken link checker seems only could check path inner repo, not check web url.

**Comment by YanjieGao** [comment]
if it can check will be helpful

**Comment by xudifsd** [comment]
The project web site are stored in gh-page branch, I think maybe wiki is also stored in git repo, maybe some branch.

**Comment by scarlett2018** [comment]
@mydmdm - as discussed today, @hzy46 's intern might start with:
- cleaning up some current Wiki?
- summarize best practices for ops in Wiki
