### ISSUE TITLE
Remove ms specially config from example docker images

### ISSUE THREAD

**Issue by hao1939** [microsoft/pai#1771]
Container can't `apt-get update`, because  `/etc/resolv.conf` was misconfigured.

Song create a job using `openpai/pai.example.tensorflow:stable`, but can't `apt-get update` in the container. Below is the `/etc/resolv.conf`.
> search corp.microsoft.com
> 
> nameserver 8.8.8.8
> nameserver 8.8.4.4 

It may inherited from base image.

**Comment by abuccts** [comment]
Docker copies `/etc/resolv.conf` from host, not related to image.
