### ISSUE TITLE
Investigate limit container disk usage

### ISSUE THREAD

**Issue by hao1939** [microsoft/pai#1777]
Do some research and try some experiments.

**Comment by hao1939** [comment]
1. According to docker document, the available drivers for ubuntu are `overlay2`, aufs, `zfs` and vfs. (overylay and devicemapper are deprecated.)  https://docs.docker.com/storage/storagedriver/select-storage-driver/#docker-engine---community:

Linux distribution | Recommended storage drivers | Alternative drivers
-- | -- | --
Docker Engine - Community on Ubuntu | overlay2 or aufs (for Ubuntu 14.04 running on kernel 3.13) | overlay¹, devicemapper², zfs, vfs

2. For PAI, we may choose `overlay2` or `zfs`. Because the `--storage-opt size=120G` option is only available for the devicemapper, btrfs, `overlay2`, windowsfilter and `zfs` graph drivers. https://docs.docker.com/engine/reference/commandline/run/#set-storage-driver-options-per-container.

> This (size) will allow to set the container rootfs size to 120G at creation time. This option is only available for the devicemapper, btrfs, overlay2, windowsfilter and zfs graph drivers. For the devicemapper, btrfs, windowsfilter and zfs graph drivers, user cannot pass a size less than the Default BaseFS Size. For the overlay2 storage driver, the size option is only available if the backing fs is xfs and mounted with the pquota mount option. Under these conditions, user can pass any size less than the backing fs size.

3. Considering the backing filesystems, we could choose `overylay2-xfs` or `zfs-zfs`. https://docs.docker.com/storage/storagedriver/select-storage-driver/#supported-backing-filesystems

Storage driver | Supported backing filesystems
-- | --
overlay2, overlay | xfs with fstype=1, ext4
aufs | xfs, ext4
devicemapper | direct-lvm
btrfs | btrfs
zfs | zfs
vfs | any filesystem

I will take a try.

**Comment by fanyangCS** [comment]
will address in pure k8s version.
