### ISSUE TITLE
Can I deploy NVIDIA 410+ version for some worker node?

### ISSUE THREAD

**Issue by GeoffreyChen777** [Microsoft/pai#1779]
I have deployed many 1080ti worker nodes with v.384 driver and everything looks good. But I have some worker servers with GTX 2080ti that only support v.410+ driver. 

In tag:0.8.1, changing driver version is not supported. I want to know if it is possible to hardcore the 410+ driver for only 2080ti node. 

According to issue #1751, I can hardcore the driver version in https://github.com/Microsoft/pai/blob/pai-0.8.y/src/drivers/deploy/drivers.yaml.template#L35 . But I don’t want to destroy other worker nodes...

**Comment by ydye** [comment]
Hi @GeoffreyChen777 , this feature could be implemented, but now we haven't supported it in OpenPai. I will gave you a solution to walk around. 

1:  Remove the drivers-384.111 from the node with GTX 2080ti

```
kubectl label nodes ${node-name} no-drivers="true"
```
https://github.com/Microsoft/pai/blob/master/src/drivers/deploy/service.yaml#L35
https://github.com/Microsoft/pai/blob/master/deployment/paiLibrary/paiService/service_template_generate.py#L74


2: Write a new folder in the path ````src/drivers-410``` of OpenPai.

1) Copy all the file and directly in ```src/drivers/deploy``` to the new folder.
2) Change the [line](https://github.com/Microsoft/pai/blob/master/src/drivers/deploy/service.yaml#L35) as following.
```
deploy-rules:
  - in: drivers-410
```
3) Hardcode the [line](https://github.com/Microsoft/pai/blob/master/src/drivers/deploy/drivers.yaml.template#L35) with the drivers which you want.

4) Change the following line with the same value. Don't be the same value as the drivers.
https://github.com/Microsoft/pai/blob/master/src/drivers/deploy/drivers.yaml.template#L21
https://github.com/Microsoft/pai/blob/master/src/drivers/deploy/drivers.yaml.template#L25
https://github.com/Microsoft/pai/blob/master/src/drivers/deploy/drivers.yaml.template#L29
https://github.com/Microsoft/pai/blob/master/src/drivers/deploy/start.sh#L28
https://github.com/Microsoft/pai/blob/master/src/drivers/deploy/start.sh#L28

5) Starting the service with the command following.
```
./paictl.py service start -p /config/path -n drivers-410
``` 



## Note
We didn't test this version before. so we do not guarantee whether it will be successfully installed or not.

**Comment by GeoffreyChen777** [comment]
@ydye Thans for the reply.

Does your solution only affect the 2080ti machine? My deplyed 1080ti machine can keep working right?

If it is true, I will try your solution for 410 driver and show the result here soon.

**Comment by ydye** [comment]
Hi @GeoffreyChen777  yes.

**Comment by fanyangCS** [comment]
can you upgrade all nodes to v.410+?

**Comment by fanyangCS** [comment]
addressed in the PR: https://github.com/Microsoft/pai/issues/1719 and https://github.com/Microsoft/pai/pull/1632.
