### ISSUE TITLE
Add node-selector in this ds

### ISSUE THREAD

**Issue by ydye** [Microsoft/pai#178]
https://github.com/Microsoft/pai/blob/327ecd0a4390837d38d4be79e720f2e3420d1ad4/service-deployment/bootstrap/prometheus/node-exporter-ds.yaml.template#L18

Please add node-selector label to this daemonset even it will deploy all the node in the cluster.

**Comment by ydye** [comment]
#179

**Comment by YanjieGao** [comment]
#solved
