### ISSUE TITLE
关于rest-server的日志管理

### ISSUE THREAD

**Issue by damon008** [Microsoft/pai#1785]
你好，关于rest-server的日志，有做格式管理和每天的文件隔离机制吗？比如每天生成的新的日志文件，加上日期标注等.

**Comment by Gerhut** [comment]
Hi @damon008 

Currently, the PAI services are maintained by kubernetes, so the logging system relies on the [kubernetes logging architecture](https://kubernetes.io/docs/concepts/cluster-administration/logging/). There are no more additional logging strategies customized in PAI. So you can customize your own logging strategies in kubernetes layer.

**Comment by fanyangCS** [comment]
@damon008 , we welcome contribution for customized log management. potentially, this could be included in PAI as a custom plugin.
