### ISSUE TITLE
How could I mark a job? For example tag a job with a label '1 gpu', '100g', 'distributed'.

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#1796]
When do experiments, user will change some setting and submit a new job.
For example, increase GPUs count, increase memory, edit scripts.

But there is no way to track the difference.
Could tag works?

**Comment by hao1939** [comment]
But we can't update job name, so:

1. Can't change it if tag it by mistake.
2. Can't add more tags after job submitted, for example: 'best', 'worst' and etc.

**Comment by scarlett2018** [comment]
Adding @qfyin for reference.

**Comment by scarlett2018** [comment]
#2331

**Comment by scarlett2018** [comment]
merged to #2331
