### ISSUE TITLE
k8s could not pull openpai/cleaner images

### ISSUE THREAD

**Issue by lllllwwwwyyyy** [Microsoft/pai#1799]
![image](https://user-images.githubusercontent.com/10185324/49270277-86032600-f4a3-11e8-8ccc-2406b1197a4d.png)

k8s seems to pull cleaner:v0.8.0. actually there has no tag named v0.8.0

**Comment by lllllwwwwyyyy** [comment]
![image](https://user-images.githubusercontent.com/10185324/49270680-6967ed80-f4a5-11e8-9dbf-7bb9a9065b3c.png)

**Comment by wangcan0329** [comment]
Cleaner is disabled now, so PAI won't publish cleaner image. Could you please use our release branch instead of master since it's more stable. Our latest release version is [v0.8.2](https://github.com/Microsoft/pai/tree/v0.8.2)
