### ISSUE TITLE
the CMD and ENTRYPOINT statements in dockerfile

### ISSUE THREAD

**Issue by debuggy** [Microsoft/pai#1803]
Hi, 
    
  I submit job to PAI with a dockerfile which contains CMD and ENTRYPOINT statments, and some strange behaviors happen:

  1. If the dockerfile contains CMD, then all the CMD statements will not be processed in pai job.
  2. If the dockerfile contains ENTRYPOINT, then the ENTRYPOINT statement will be executed and somehow override part of pai procedure.

  I think the reason may be that the docker was started by `docker run <image> <cmd args>` , and it will override some dockerfile contents. Could any one explains that in further details? Thanks.

**Comment by fanyangCS** [comment]
@debuggy , which version are you using?

**Comment by mzmssg** [comment]
In our design, CMD and ENTRYPOINT should both be ignored. 

We will fix ENTRYPOINT issue in next release, you could refer here(#1646 ) to fix it with a little change.

**Comment by debuggy** [comment]
However I see many dockerfiles have CMD and ENTRYPOINT keys [in this repo](https://github.com/jessfraz/dockerfiles)

e.g.  https://github.com/jessfraz/dockerfiles/blob/master/firefox/Dockerfile
https://nodejs.org/en/docs/guides/nodejs-docker-webapp/

I am ok with that design, however is there any alternative for users who added entrypoint in docker image?

**Comment by debuggy** [comment]
practical solution, thanks
