### ISSUE TITLE
Feature Needed: LDAP support for web portal

### ISSUE THREAD

**Issue by rayz0620** [Microsoft/pai#1811]
Currently web portal uses its own account system. With LDAP support it would be more convenient to integrate PAI into enterprise systems.

**Comment by YanjieGao** [comment]
@wangcan0329 ,this is related current user account work

**Comment by fanyangCS** [comment]
we do have a plan to support similar feature in the future.

**Comment by fanyangCS** [comment]
close and track in #1663
