### ISSUE TITLE
QoS has a bad influence on deployment.

### ISSUE THREAD

**Issue by ydye** [Microsoft/pai#1812]
Many user are blocked by QoS policy, we should make a configuration switch for user to enable it or not. We shouldn't force enabling it.

**Comment by ydye** [comment]
https://github.com/Microsoft/pai/issues/1762

**Comment by ydye** [comment]
https://github.com/Microsoft/pai/issues/1727

**Comment by hao1939** [comment]
Hi @ydye ,

Agree with you that it does caused a lot of inconvenience, it's annoying.

In case that we add the `disable switch`, people may still come into the situation before realizing the usage of `disable switch`.
So my proposal would be adding a prerequisite check before installing.

**Comment by fanyangCS** [comment]
isn't the QoS policy supposed to solve this issue? The  message says customer's hardware does not meet the minimum requirement, so the deployment process has to stop there. 
The related issues do raise a problem of clarity: user need to know why the deployment didn't succeed.

**Comment by ydye** [comment]
@fanyangCS, I don't think so. The single-box mode is introduced for newcomer who just wanna a try. And the machine may not have enough capacity, then QoS will block them. Is the QoS policy important? I will say yes. But what if the qos policy is removed? I think pai will still work. And now i have come across several issue in the github, all of them are caused by qos. And each time, we have to cost time to dig the issue. So, I still hold this opion, we should be able to disbale it.

**Comment by ydye** [comment]
@fanyangCS And now the configuration in QoS policy is designed for our internal cluster. It's not an acceptable solution for user to customize the value manually. At least, i will feel frustrated, if i come across this.

**Comment by ydye** [comment]
And I  think QoS policy is not designed for knocking out the hardware which not meet the resource requirement. The policy is design for keeping openpai stable.

**Comment by fanyangCS** [comment]
Let me summarize your points: 
1. You think single-box deployment doesn't need QoS enforce because it is just for evaluation purpose.
2. Currently the QoS setting is fixed, i.e., it works best for a set specific hardware configurations and might not be necessary for other configurations. And user cannot customize them?
3. QoS is designed for system stability, not excluding several hardware configurations.

Is my understanding to your complaints correct? do you have more to add?

**Comment by ydye** [comment]
@fanyangCS  Thanks,  that's all.

**Comment by hao1939** [comment]
@ydye Notice you have added a configuration option. We could close it now.
