### ISSUE TITLE
How to set port range for different application

### ISSUE THREAD

**Issue by weiranzhixin** [Microsoft/pai#1813]
there are two kinds of applications in one container
* application 1:  need 1 port, port range: [10000, 10100]
* application 2: need 3 ports, port range:[10101, 11000]
how to achieve this ?
thanks

**Comment by mzmssg** [comment]
@weiranzhixin Currently, range schedule hasn't been supported.

**Comment by weiranzhixin** [comment]
thanks, another question is, 
* when does node manage reports available ports to resource manager , reporting when  node manager activated or periodically
* if node manager periodically report available ports, how does resource manager deal with it ? 
* does yarn offer CLI to check available port ranges of node

**Comment by mzmssg** [comment]
@weiranzhixin 
NM will periodically report ports info, wrapped by heartbeat. Then RM will update the resource.

You could run command `yarn node -list -showDetails` to get node port info.

**Comment by scarlett2018** [comment]
@mzmssg - may we update FAQ for these 2 questions and close this issue? thanks.

**Comment by mzmssg** [comment]
@scarlett2018 
Most of this issue is about hadoop implementation and usage, I think an issue is enough. We shouldn't include too much hadoop details into our faq.

**Comment by mzmssg** [comment]
Let's close this issue and track port issue in #1983

**Comment by scarlett2018** [comment]
@mzmssg - got it, fair enough.
