### ISSUE TITLE
how to use http:port

### ISSUE THREAD

**Issue by weishuoycbb** [Microsoft/pai#1815]
![image](https://user-images.githubusercontent.com/43461329/49361320-b56d9900-f716-11e8-8c3e-73f3f388c073.png)
how to use this

**Comment by fanyangCS** [comment]
the ssh is the port you use to ssh into the container (e.g., for debug purpose). the http port is the port the container can use for web service. and you can use the http port for other purpose, but the ssh port is reserved for ssh only.
