### ISSUE TITLE
frameworklauncher获取任务信息的性能问题

### ISSUE THREAD

**Issue by damon008** [Microsoft/pai#1817]
frameworklauncher获取任务信息在达到1w个任务左右时，会出现性能问题。 主要需要调用Requestmanager、StatusManager获取数据。这个咱们考虑过分页，或者其他办法吗？

**Comment by yqwang-ms** [comment]
1. please provide the details about the performance issue, such as how many Frameworks and Tasks in total, and what is the slow performance do you mean?

2. frameworklauncher is not used to store too many history Frameworks, it mainly used to managed the running life cycle of the framework. Decrease the frameworkCompletedRetainSec may help you to increase performance:
https://github.com/Microsoft/pai/blob/master/src/yarn-frameworklauncher/deploy/yarn-frameworklauncher-configuration/frameworklauncher.yml#L40

**Comment by damon008** [comment]
总共大概15496个任务，一次性调用查询接口时耗时大概10s

**Comment by yqwang-ms** [comment]
1. 什么是你所说的“任务”？你是指framework的数量还是task的数量？
2. 你打开浏览器的debug mode，看看这10s到底开销在哪里。

关于list在大量framework情况下(>1w)，速度的优化，我们考虑过分页等优化，不过目前还没来得及做。我之前提到的第二点，是将framework保存的数量调低，从而list返回的数据也会减少了。

**Comment by damon008** [comment]
我是指framework，不是指task，您所说的是指减少保存的已完成的framework的时间从而framework的查询数量，这个我想着能不能分页来处理?

**Comment by yqwang-ms** [comment]
1. 恩，是指减少“已完成的framework”的保留时间，以减少list返回的数据。
2. 可以分页处理来优化，但是目前我们还没做
3. 你看看10s里有多少花费在了frameworklauncher产出数据，多少花费在了network传出数据。如用IE：
![image](https://user-images.githubusercontent.com/32826762/49424118-8cabd900-f7d4-11e8-9adf-fd120f2d29d6.png)
4. 还没有批量查询接口。目前只有：
基于username的过滤：
https://github.com/Microsoft/pai/blob/master/subprojects/frameworklauncher/yarn/doc/USERMANUAL.md#get-frameworks
点查询：
https://github.com/Microsoft/pai/blob/master/subprojects/frameworklauncher/yarn/doc/USERMANUAL.md#get-framework

**Comment by fanyangCS** [comment]
@damon008 , your measurement result is inconsistent with ours. we believe 10s of loading happens when the number of frameworks is on the order of 100k. Please provide us a detailed breakdown of the time for us to analyze.

**Comment by xwzheng1020** [comment]
@damon008，如果有10k个任务，而每个任务需要传输的数据超过100Byte，那么每次传输数据量就超过1MB，这个视网速需要耗费时间。我们也可以在master上测试下一次rest-server的请求是多少时间？

**Comment by fanyangCS** [comment]
close as no further response.
