### ISSUE TITLE
Visual Studio Code for AI has changed to Azure Machine Learninig.

### ISSUE THREAD

**Issue by GeoffreyChen777** [Microsoft/pai#1818]
There is no Visual Studio Code for AI in the extension market. How to use the new extension to submit the PAI job?

**Comment by scarlett2018** [comment]
@GeoffreyChen777 - I'm the PM for OpenPAI, thanks for reporting the issue. 

We are in the middle of refine and restructure the tools for AI extensions, the new release of VS code tools for AI will be more focus on the support of Azure ML, while an extension for OpenPAI has been created and is under the process of publishing. This change will make the extensions more focus on its own target audiences. But we have to apologize that the timing for changes has an unexpected gap that the new OpenPAI extension has not yet publish together. We are working on few quick mitigation tasks and will get back to you with a solution soon, stay tuned.

Thanks,
Scarlett

**Comment by scarlett2018** [comment]
@GeoffreyChen777 - new update:
We had put the Tools for AI build in: https://github.com/Microsoft/vscode-tools-for-ai/releases/tag/0.3.2. You can download it and install from local with that build. 

Note: to avoid auto upgrade, please make sure you VS Code had disabled the "Auto Upgrade".

**Comment by scarlett2018** [comment]
I'm closing the issue as the problem had been resolved, we will update the documentation and release note once the OpenPAI extension is officially published. Stay tuned =).
