### ISSUE TITLE
Leverage k8s `local persistent volume` to replace `hostPath` in `data-node`

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#1823]
Since k8s 1.10, `local persistent volume` is available, it could leverage local disks in your StatefulSets.
The `etcd` and `data-node` now are using hard coded volume mounting, which could leverage the new feature.

https://kubernetes.io/blog/2018/04/13/local-persistent-volumes-beta/

> Suitable workloads
> Some use cases that are suitable for local storage include:
> 
> Caching of datasets that can leverage data gravity for fast processing
> Distributed storage systems that shard or replicate data across multiple nodes. Examples include distributed datastores like Cassandra, or distributed file systems like Gluster or Ceph.
> Suitable workloads are tolerant of node failures, data unavailability, and data loss. They provide critical, latency-sensitive infrastructure services to the rest of the cluster, and should run with high priority compared to other workloads.

**Comment by ydye** [comment]
1: etcd is started as the static pod, and it's started at the stage when setup your cluster. At these stage, I don't think persistent volume will take affect.
2: And I don't data-node will benefit from this. Naturally, data node should run as a daemon on each node. And mount the local disk is very reasonable. And by the way, running hadoop on k8s is already very hack.

**Comment by hao1939** [comment]
Hi @ydye ,
Using `local persistent volume`, we could decouple the node filesystem layout.
And we don't need the change `data-node` if the `big disk` is mounted on different path.

**Comment by hao1939** [comment]
In short, we are currently using `hostPath` mounting local volume in pod, and `Local Persistent Volumes` is for `addressing hostPath challenges`.

Here are the benefits: 
1. `Local Persistent Volumes` is a k8s `resource`, so resource scheduling and management works (with some limitations). For example, we could use `nodeAffinity` to schedule pod onto the node with required `storage`.
2. No need to manage local disk topology anymore. User disks may mount on various paths, it makes no difference for pod.
3. Volume capacity management. Pod requires 50Gi disk could claim for a 50Gi capacity `volume`. But there are two limitations for now: a) dynamically creating `Local Persistent Volumes` is still in implementation, b) haven't figure out how k8s would enforce the restriction.

More details see the official doc: https://kubernetes.io/blog/2018/04/13/local-persistent-volumes-beta/

**Comment by fanyangCS** [comment]
etcd is running in static pod, this resolves the circuit dependency of the k8s-depends-on-etcd issue. Not sure if static pod can leverage local persistent volume. My guess is it cannot, because etcd runs before k8s is available yet.

Also, if DataNode doesn't manage the local disk topology, who knows it? K8s is not aware of the semantics of DataNode, it doesn't know which disk DataNode prefers. I don't understand why local persistent volumes help in this case.

**Comment by fanyangCS** [comment]
close it for now. feel free to open it if new justification comes.
