### ISSUE TITLE
Distributed training: Low speed external storage may cause job deadlock

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#1834]
In distributed training, processes sync within fixed period. Download from low speed external storage may block the process and cause job deadlock.

Here's a example: http://10.151.40.179/view.html?username=anbhu&jobName=Vortex-mpi-ADLS-010
> [INFO 2018-12-05 10:14:38] Starting to test on file: adl://relevance-c09.azuredatalakestore.net/projects/vortexproject/share/anbhu/data/uhrs_dt_snippet_reorder
> [INFO 2018-12-05 10:14:38] Running Single Box Trainier
> Worker Thread Count 1 *************************
> 0
> Files to read for worker 0: uhrs_dt_snippet_reorder
> readDirect: FSDataInputStream#read error:
> java.lang.UnsupportedOperationException: Byte-buffer read unsupported by input stream
> 	at org.apache.hadoop.fs.FSDataInputStream.read(FSDataInputStream.java:150)
> readDirect: FSDataInputStream#read error:
> java.lang.UnsupportedOperationException: Byte-buffer read unsupported by input stream
> 	at org.apache.hadoop.fs.FSDataInputStream.read(FSDataInputStream.java:150)
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> WARNING: One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock.

**Comment by fanyangCS** [comment]
I don't see anything OpenPAI in this regard? if the external storage is slow, replace with a higher speed one?
