### ISSUE TITLE
Do I need to remove the hdfs node before deleting a machine from the cluster?

### ISSUE THREAD

**Issue by GeoffreyChen777** [Microsoft/pai#1852]
Does the paictl do the removing process of hdfs data node automatically? Or I need to manually run the command such as `hadoop dfsadmin  -refreshNodes`?

**Comment by ydye** [comment]
paictl only stops the service contianer on the node. You should login into the hdfs container and run ```hadoop dfsadmin -refreshNodes``` manually.

**Comment by ydye** [comment]
@mzmssg Any idea to improve this.

**Comment by ydye** [comment]
An idea is that we could add a sidecar contianer to check the node-list. If a node is remove from the cluster, the sidecar container could execute the command.

**Comment by mzmssg** [comment]
No need, hdfs refresh will only update the white list allowed to connect to namenode. PAI doesn't enable it.

**Comment by ydye** [comment]
I mean, remove the node from the node-list of hdfs. If a node is removed from cluster, we should also remove it from hdfs, rather then left it as a lost node in hdfs.

**Comment by mzmssg** [comment]
I think there are several problems here.
1. HDFS decommission
2. Dead nodes showed in HDFS
3. Residual host data on the removed nodes

@GeoffreyChen777 I think you care 1, @ydye you care more 2?

**Comment by GeoffreyChen777** [comment]
@mzmssg I also care about 2 and 3

**Comment by ydye** [comment]
@mzmssg Will hdfs helps us to migrate the replica if the node is missing？

**Comment by mzmssg** [comment]
@GeoffreyChen777 Currently, paictl will only do a k8s-level remove. So from hadoop view, the remove action looks like a lost node, without any decommissioning. If you want do any hadoop-level matainence( i.e. remove data-node/node-manager, hdfs rebalance, enter/leave safemode, etc.), need to get into corresponding container, and run related command like `hdfs/yarn xxadmin -xxx`.

For current topic, I recommand not to remove massive data-nodes at a same time, hdfs could tolerate a few node loss and migrate the copys to other live nodes.

**Comment by mzmssg** [comment]
@ydye HDFS could handle  a few nodes' lost, but for massive nodes remove, there are definitely lost blocks. 

Another question about 3, dose paictl just stop service when remove a node? Why not delete?

**Comment by ydye** [comment]
The remove node command is desinged for k8s-level maintenance. And hdfs belongs to service level. So we should decouple these 2 concept.

**Comment by fanyangCS** [comment]
close this issue and track it in #349
