### ISSUE TITLE
[deploy] Host preinstall CUDA checking

### ISSUE THREAD

**Issue by YanjieGao** [microsoft/pai#1855]
# Problem
previous IT cluster issue:
# Potential suggestion enhance pai
checking at driver installation or probe to tell deployer to keep clean of host CUDA.
# quick fix for current user
remove cuda and reboot server could temp fix this error
# Our exp:
driver installed by pod or use users
CUDA and cuDNN is installed by in job container dockerfile.

**Comment by fanyangCS** [comment]
not our obligation.
