### ISSUE TITLE
Occasionally failed uploading code to HDFS when NNI submit job to PAI

### ISSUE THREAD

**Issue by leckie-chn** [Microsoft/pai#1868]
```
"errors":[
        "Job management error: java.net.URISyntaxException: Illegal character in authority at index 7: http://{{ host_config['ip'] }}:5075/webhdfs/api/v1/nni/experiments/xRUarOsn/PzsgZ/modeling_dualpath.py?op=CREATE&user.name=test&namenoderpcaddress=10.0.0.4:9000&createflag=&createparent=true&overwrite=true&permission=755"
    ],
    "status":"ERROR"
```

**Comment by fanyangCS** [comment]
looks like "{{ host_config['ip'] }}" didn't replaced properly?

**Comment by Gerhut** [comment]
`{{ host_config['ip'] }}` appears in https://github.com/Microsoft/pai/blob/master/src/hadoop-data-node/deploy/hadoop-data-node-configuration/hdfs-site.xml#L271 and https://github.com/Microsoft/pai/blob/master/src/hadoop-node-manager/deploy/hadoop-node-manager-configuration/yarn-site.xml#L95

Perhaps forget to declare these files as template?

@ydye @mzmssg

**Comment by mzmssg** [comment]
Which bed? I remember we add a machine in a existing cluster recently? 

Because it's a occasinal failure. I think the most possibility is writing files to the new added node?

**Comment by fanyangCS** [comment]
close as no further response
