### ISSUE TITLE
api-server port and http schema configurable and not hard code [also needed for aks or existing k8s env]

### ISSUE THREAD

**Issue by YanjieGao** [Microsoft/pai#1869]
In current PAI object model. For deploy PAI to existing K8s (such as k8s) env, this "http" and "8080" hard code assumption can not be satisfied. It use "https" and "443", so suggest make http-schema and api-server-port as a configuration item in kubernetes-configuration.yaml

![image](https://user-images.githubusercontent.com/5576848/49784427-369cdf80-fd58-11e8-91a7-82142a974e93.png)

https://github.com/Microsoft/pai/blob/master/deployment/clusterObjectModel/mainParser/kubernetes.py#L83

For http and 8080 api-server url configuration usage at offical k8s doc said, is for test purpose. So future deploy pai to existing k8s, maybe also meet this problem.

Ref:
https://kubernetes.io/docs/reference/access-authn-authz/controlling-access/#api-server-ports-and-ips

**Comment by YanjieGao** [comment]
https://github.com/Microsoft/pai/pull/1880

**Comment by ydye** [comment]
PR merged.
