### ISSUE TITLE
Dashboard information incomplete

### ISSUE THREAD

**Issue by Hirosora** [Microsoft/pai#1881]
I deploy the system(Version: latest) on 2 cloud servers, 1 master and 1 worker, with no GPU.

The kubernetes dashboard shows everything works well.
![1544607449 1](https://user-images.githubusercontent.com/21101168/49860346-a1bbe400-fe34-11e8-9767-75d7c4f01e33.png)

But the PAI dashboard shows something wrong:

1. My cluster has 2 nodes(1 master and 1 worker), but dashboard shows total node number is 1.
![1544607020 1](https://user-images.githubusercontent.com/21101168/49860299-8650d900-fe34-11e8-8cb4-6069681e8749.png)

2. On the hardware page, Hardware Utilization only list the master node.

3. When I open hardware page, these errors show up:
     Error when loading CPU utilization data.
     Error when loading disk utilization data (step 1).
     Error when loading ethernet utilization data (step 1).
![1544607505 1](https://user-images.githubusercontent.com/21101168/49860431-c021df80-fe34-11e8-91d7-d50f63a3389b.png)

4. On the job page, a job named cntk-test fails every time, and report "Invalid resource request, requested GPUs < 0, or requested GPUs > max configured, requestedGPUs=1, maxGPUs=0". 

    My cluster has no GPU, is GPU necessary ? Can I set the "requestedGPUs" to 0 ? And how ?
![1544608027 1](https://user-images.githubusercontent.com/21101168/49861047-f875ed80-fe35-11e8-929a-d486e0295b92.png)
![1544608057 1](https://user-images.githubusercontent.com/21101168/49861090-09266380-fe36-11e8-80f3-e43908d63546.png)

**Comment by fanyangCS** [comment]
please deploy the service with our release branch. 0.8.y

**Comment by Hirosora** [comment]
Now I am using version 0.8.2.
When I run "python paictl.py cluster k8s-bootup -p ~/pai-config"
This error occurs:
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.

How to fix it ?

**Comment by fanyangCS** [comment]
please follow the suggestion in the error msg and provide us the detailed log .

**Comment by Hirosora** [comment]
@fanyangCS 
I run the commands on master node, the logs are below:

systemctl status docker.service
```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2018-12-12 19:49:27 CST; 7min ago
     Docs: https://docs.docker.com
  Process: 30548 ExecStart=/usr/bin/dockerd -H fd:// $DOCKER_OPTS (code=exited, status=1/FAILURE)
 Main PID: 30548 (code=exited, status=1/FAILURE)

Dec 12 19:49:27 iZ8vb7cnonj1n8x3fuk5tzZ systemd[1]: Starting Docker Application Container Engine...
Dec 12 19:49:27 iZ8vb7cnonj1n8x3fuk5tzZ dockerd[30548]: unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives don't match 
Dec 12 19:49:27 iZ8vb7cnonj1n8x3fuk5tzZ systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Dec 12 19:49:27 iZ8vb7cnonj1n8x3fuk5tzZ systemd[1]: Failed to start Docker Application Container Engine.
Dec 12 19:49:27 iZ8vb7cnonj1n8x3fuk5tzZ systemd[1]: docker.service: Unit entered failed state.
Dec 12 19:49:27 iZ8vb7cnonj1n8x3fuk5tzZ systemd[1]: docker.service: Failed with result 'exit-code'.

```

journalctl -xe
```
-- 
-- Unit UNIT has begun starting up.
Dec 12 19:49:27 iZ8vb7cnonj1n8x3fuk5tzZ systemd[30511]: Stopped target Basic System.
-- Subject: Unit UNIT has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit UNIT has finished shutting down.
Dec 12 19:49:27 iZ8vb7cnonj1n8x3fuk5tzZ systemd[30511]: Stopped target Timers.
-- Subject: Unit UNIT has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit UNIT has finished shutting down.
Dec 12 19:49:27 iZ8vb7cnonj1n8x3fuk5tzZ systemd[30511]: Stopped target Sockets.
-- Subject: Unit UNIT has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit UNIT has finished shutting down.
Dec 12 19:49:27 iZ8vb7cnonj1n8x3fuk5tzZ systemd[30511]: Stopped target Paths.
-- Subject: Unit UNIT has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit UNIT has finished shutting down.
Dec 12 19:49:27 iZ8vb7cnonj1n8x3fuk5tzZ systemd[30511]: Received SIGRTMIN+24 from PID 30563 (kill).
Dec 12 19:49:27 iZ8vb7cnonj1n8x3fuk5tzZ systemd[30515]: pam_unix(systemd-user:session): session closed for user openpai
Dec 12 19:49:27 iZ8vb7cnonj1n8x3fuk5tzZ systemd[1]: Stopped User Manager for UID 1000.
-- Subject: Unit user@1000.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit user@1000.service has finished shutting down.
Dec 12 19:49:27 iZ8vb7cnonj1n8x3fuk5tzZ systemd[1]: Removed slice User Slice of openpai.
-- Subject: Unit user-1000.slice has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit user-1000.slice has finished shutting down.
Dec 12 19:55:01 iZ8vb7cnonj1n8x3fuk5tzZ CRON[30599]: pam_unix(cron:session): session opened for user root by (uid=0)
Dec 12 19:55:01 iZ8vb7cnonj1n8x3fuk5tzZ CRON[30600]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Dec 12 19:55:01 iZ8vb7cnonj1n8x3fuk5tzZ CRON[30599]: pam_unix(cron:session): session closed for user root
```

**Comment by fanyangCS** [comment]
We assume you run the deployment process in a dev-box, which cannot be the master or worker.

**Comment by Hirosora** [comment]
I konw this and I am running the deployment process on another machine.
I mean I run "systemctl status docker.service" and "journalctl -xe" on the master node following the suggestion, because the error occurs on the master node.

**Comment by fanyangCS** [comment]
Dec 12 19:49:27 iZ8vb7cnonj1n8x3fuk5tzZ dockerd[30548]: unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives don't match any configuration option: data-root.

It seems some of the config option is not supported by this version of Docker. Can you check your docker version and make sure it matches the docker version OpenPAI requires?

**Comment by Hirosora** [comment]
@fanyangCS 
My docker api version is 1.27

```
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.6.2
 Git commit:   f5ec1e2
 Built:        Thu Jul  5 23:07:48 2018
 OS/Arch:      linux/amd64
```

The instruction says 

> Recommend no Docker installed or a Docker with api version >= 1.26.

I think it matches the docker version OpenPAI requires.

**Comment by ydye** [comment]
@Hirosora  Can you share us the daemon.json with us?

**Comment by Hirosora** [comment]
@ydye 
I change my docker from docker.io to docker-ce, and the previous problem was fixed.

But now I encounter a new problem.
![image](https://user-images.githubusercontent.com/21101168/49884309-891cef80-fe6f-11e8-8ae5-269fa0af377d.png)
When I am starting the services, the node-exporter failed to pull image "docker.io/openpai/node-exporter:v0.8.2".
It seems node-exporter has no version 0.8.2.
![image](https://user-images.githubusercontent.com/21101168/49884404-c1243280-fe6f-11e8-8e1e-052773a9d951.png)

How can I fix this ?

**Comment by Hirosora** [comment]
@xudifsd 
Thanks a lot ! The previous problem was solved.

But now I encouter a memory limit problem.

The "pylon-ds" service report "Node didn't have enough resource: memory, requested: 1073741824, used: 28160557056, capacity: 28829487694"

In previous installations, this service didn't request so much memory, does the 0.8.2 version request more memory ?

![image](https://user-images.githubusercontent.com/21101168/49926113-c9bf4c00-fef5-11e8-8cb5-7c846a08c043.png)

![image](https://user-images.githubusercontent.com/21101168/49926330-494d1b00-fef6-11e8-9d5d-d4c1eefeeaab.png)

Our nodes each has 32GB memory.

**Comment by xudifsd** [comment]
@hao1939 maybe you didn't cherry-pick the expansion of resource limit into 0.8 branch?
