### ISSUE TITLE
Job metrics: taskrolelevelmetrics, tasklevelmetrics are missing

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#1883]
Now, taskrolelevelmetrics, tasklevelmetrics are missing.
http://10.151.40.179/view.html?username=hayua&jobName=Vortex-mpi-ADLS-singlebox-20181213

![image](https://user-images.githubusercontent.com/1547343/49913346-476c6300-fec8-11e8-99fd-00ed0dff6387.png)
![image](https://user-images.githubusercontent.com/1547343/49913347-4b988080-fec8-11e8-87e3-74300d8a51db.png)
![image](https://user-images.githubusercontent.com/1547343/49913350-4f2c0780-fec8-11e8-92e0-63a547137183.png)

**Comment by xudifsd** [comment]
You can click on that red corner and it will show error: `414 Request-URI Too Large`. This has been fixed in #1717 .

**Comment by xudifsd** [comment]
These three pages will show value from the same metrics but using different aggregation method:
The first page avg all metrics from one job.
The second page avg over task role level from one job.
The second page avg over task level from one job.

**Comment by hao1939** [comment]
Clarify user's purpose:
1. taskrolelevelmetrics: want to see metrics aggregating by taskRoles. If there are two role `master` and `slave`, it could display different pages for each.
2. tasklevelmetrics: metrics by tasks, could see each container's metrics.

**Comment by xudifsd** [comment]
This is exactly what these pages will display if no bug.

**Comment by hao1939** [comment]
@Anbang-Hu, as @xudifsd mentioned, it's bug. We fixed but haven't released yet.
