### ISSUE TITLE
Job finished but won't quit

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#1884]
Here's an example: http://10.150.144.225/view.html?username=admin&jobName=cntk-test-7898-10110
The job container already received the `EXIT signal` but won't quit.

Tail of the logs:

> Finished Epoch[ 1 of 1]: [Training] ce = 3.07214521 * 40079; errs = 82.143% * 40079; totalSamplesSeen = 40079; learningRatePerSample = 0.0070000002; epochTime=313.508s
> Final Results: Minibatch[1-767]: ce = 2.70157036 * 40079; errs = 76.728% * 40079
> Finished Epoch[ 1 of 1]: [Validate] ce = 2.70157036 * 40079; errs = 76.728% * 40079
> SGD: Saving checkpoint model '/mnt/hdfs/Test/cntk/cntk-test-7898-10110/g2p-01-0/G2P.dnn'
> 
> Action "train" complete.
> 
> COMPLETED.
> 
> [INFO] USER COMMAND END
> 
> [DEBUG] Docker container exit handler: EXIT signal received in docker container, exiting ...
> 2018/12/08 19:38:42 Signal received: terminated
> 2018/12/08 19:38:42 Unmounting...

**Comment by fanyangCS** [comment]
this is a known issue. hdfs-mount won't quit gracefully. that is why we do not recommend using hdfs-mount
