### ISSUE TITLE
jobs get into waiting

### ISSUE THREAD

**Issue by Tuskio** [Microsoft/pai#1892]
We have installed openpai, according to #1881. 

Then, cntk-test failed due to our mechine have no GPU. Besides, launcher-test Succeeded.
![image](https://user-images.githubusercontent.com/30797159/49990843-11a7a700-ffba-11e8-87f0-d542d6ae47e8.png)

After that, we submitted a test-job (keras_tensorflow_backend_mnist) yesterday afternoon.
![image](https://user-images.githubusercontent.com/30797159/49990802-de651800-ffb9-11e8-86cd-c6361eb3c30c.png)
Up to now, the job still is waiting.
How can we fix it?

**Comment by fanyangCS** [comment]
can you share us the job config file, am log. and if the job container log is available, please also share it.

**Comment by Tuskio** [comment]
@fanyangCS  
The job config:
```
{
  "jobName": "keras_tensorflow_backend_mnist",
  "image": "openpai/pai.example.keras.tensorflow",
  "authFile": "",
  "dataDir": "",
  "outputDir": "",
  "codeDir": "",
  "virtualCluster": "default",
  "gpuType": "",
  "retryCount": 0,
  "taskRoles": [
    {
      "name": "mnist",
      "taskNumber": 1,
      "cpuNumber": 2,
      "memoryMB": 4096,
      "gpuNumber": 0,
      "command": "python mnist_cnn.py"
    }
  ]
}
```

Application Tracking Page：

![image](https://user-images.githubusercontent.com/30797159/50040321-39f7da00-007c-11e9-82d8-db3793d8d50e.png)

**Comment by fanyangCS** [comment]
I suspect Node Manager didn't get started successfully. since Node Manager, Data Node all require gigabyte of memory. And your job actually need at least 8G memory (AM need 4G, your job container need 4G). 
@hao1939 , can you take a look.

**Comment by Tuskio** [comment]
@fanyangCS It works. Thank you very much！
