### ISSUE TITLE
P00 - part of 4022 - Prerequisites/node check

### ISSUE THREAD

**Issue by hao1939** [microsoft/pai#1893]
Before installation, check:
1. Hardware requirements (cpu/memory/gpu, etc)
2. System configuration (os, docker, ntp, user, etc)

After installation, collect those info for debug purpose.

**Comment by hao1939** [comment]
#2520 would check os version.

**Comment by fanyangCS** [comment]
done in https://github.com/microsoft/pai/blob/master/contrib/kubespray/doc/requirement.md
