### ISSUE TITLE
Job cannot be scheduled after 90% GPU was used. 

### ISSUE THREAD

**Issue by qinchen123** [Microsoft/pai#190]
The PAI cluster config two queue: default, dev
default queue capacity is 0.9 while dev queue capacity is 0.1.
we need config the "maximum-capacity" to allow default queue to use dev queue resource when dev queue is free. 

Also, we need enable the preemption feature to allow dev queue abort default queue's  extra job.

**Comment by qinchen123** [comment]
use different use in the default queue to submit job can drive the default queue utilization up to 100%.

**Comment by fanyangCS** [comment]
close this issue as it is the by-design behavior.
