### ISSUE TITLE
How to remove current pai cluster compeletly? It seems old configuration impacts new deployment of cluster.

### ISSUE THREAD

**Issue by winrgn** [Microsoft/pai#1900]

**Comment by ydye** [comment]
#### Service level
The following command will:

1. delete hdfs data
2. delete zookeeper data
3. delete yarn data
4. Other service's persistent data.
```
./paictl.py service delete -p /path/to/configuration
```

#### k8s level
The following command will:

1. stop k8s
2. remove etcd data. (Include the user account data in your cluster)

```
./paictl.py cluster k8s-clean -p /path/to/config -f
```
