### ISSUE TITLE
How to get the resource left on each worker?

### ISSUE THREAD

**Issue by shawntian90** [Microsoft/pai#1903]
hi,

The worker's hardware resource usually allocated to many different job instances. The count of left GPU on worker node is easy to know but CPU and RAM may be difficult.

And I want to know left resource on each worker and get the maximum utilization of the limited resource.

Thanks!

**Comment by mzmssg** [comment]
I think we can use **allocated resource** and **utilized resource** instead. The former means the resource has been assigned to some job, but mayn't yet be used. the latter means the resource is in real using. So what's your definition of *left resource*?

**Comment by shawntian90** [comment]
Thanks @mzmssg,

And in my situation the **left resource** means the CPU, MEM and GPU can be assigned to a new job.

**Comment by mzmssg** [comment]
@shawntian90 
You could get every node usage either by http request `http://master_ip:8088/ws/v1/cluster/nodes` or by command line `yarn node -list -showDetails`

**Comment by shawntian90** [comment]
@mzmssg,

So much for the help! This is what I want.

Thanks again!
