### ISSUE TITLE
cgroup: no space left on device

### ISSUE THREAD

**Issue by shawntian90** [Microsoft/pai#1904]
Hi,

I met the problem when I found that cluster can create a new job on one specific worker node, which always failed.

Also failed when just run `hello-world`:
```bash
$ docker run hello-world
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:279: applying cgroup configuration for process caused \"mkdir /sys/fs/cgroup/memory/docker/55d7db61bab0b12b483a1e4dd2164ed7c4787375fd7aaed6a4501656941c0ece: no space left on device\"": unknown.
ERRO[0001] error waiting for container: context canceled
```

I found [this post in CN](http://www.linuxfly.org/kubernetes-19-conflict-with-centos7/), [another post in EN](https://github.com/moby/moby/issues/29638) and the situation is almost the same except for the OS.

```
$ cat /proc/cgroups 
#subsys_name	hierarchy	num_cgroups	enabled
cpuset	10	26	1
cpu	5	127	1
cpuacct	5	127	1
blkio	7	127	1
memory	6	65535	1
devices	8	127	1
freezer	3	26	1
net_cls	2	26	1
perf_event	11	26	1
net_prio	2	26	1
hugetlb	9	26	1
pids	4	128	1
```

The `memory` has reached the maximum usage of `cgroups`.

Thanks!

**Comment by fanyangCS** [comment]
I am not clear about your question. It seems that the Docker has some problem in your host OS? I suggest you to ask this question in Docker community.

Or if you don't want the trouble, a clean install might help address the issue.

**Comment by scarlett2018** [comment]
@shawntian90 - are you suggesting PAI should not always allocate jobs on a node that is out of capability? that is a good perspective. @fanyangCS and @hao1939 to add more comments and thoughts.

BTW, had you able to work around this issue as @fanyangCS suggested, just clean up the nodes first.

Looking forward for your feedback on the issue's current status, thanks.

PAI PM,
Scarlett

**Comment by hao1939** [comment]
Hi @shawntian90 ,

I have read through the reference link you provides.
Seems like it's a cgroup memory leaking problem, we can fix it via updating os kernal?
Are I right? Have you got it fixed yet?

**Comment by shawntian90** [comment]
@hao1939,

Thanks for the reply and I fixed this problem via rebooting the host machine.

Yes, all search results reveal this is a docker/kernel problem and updating the kernel is too much heavy for me. So just reboot and it does not recurrent again.


Thanks!

**Comment by fanyangCS** [comment]
I hereby close this issue. For Docker issue, please refer to Docker community.
