### ISSUE TITLE
How to submit a customized job? job failed when requesting more than one node's resource 

### ISSUE THREAD

**Issue by hughian** [Microsoft/pai#1906]
Hi, now we have successfully deployed openpai on  the VMs and it works fine when we submit some of the example jobs。
![image](https://user-images.githubusercontent.com/24643809/50147628-9e6f9f00-02f1-11e9-87dc-01cce760a39b.png)
However, we have encountered some problems when we modified the job config file and submitted it again.It failed when we tried to use resource from more than one worker node(we have two GPUs  each worker node and this job ask for 4 GPUs).
![image](https://user-images.githubusercontent.com/24643809/50147691-be9f5e00-02f1-11e9-9f62-ad247fc3071c.png)
and how can submit a customized job, do we have to build a docker image every time when we modified our code?

**Comment by shawntian90** [comment]
One job's GPU/CPU/MEM can not larger than single worker's resource limitation.

**Comment by Hirosora** [comment]
@shawntian90 
According to what you said, it seems what OpenPAI does is allocating one job to one worker node. 
If we have a job which needs more than one node's resources to run, can OpenPAI make it ?

**Comment by shawntian90** [comment]
At present, it seems not.

But it is possible to run multiple jobs, building a distributed training system, which is supported by Tensorflow or Pytorch.

**Comment by fanyangCS** [comment]
@hughian , you don't have to build a docker image everytime you change the code. 
Taking TensorFlow as an example, the standard practice is you build a docker image for a certain TF version (e.g., 1.10), and inside the job container, you can git clone your latest code from your repo and run the code afterward.

For details about how to run customized jobs, please refer to: https://github.com/Microsoft/pai/blob/master/docs/job_tutorial.md

And here are some examples https://github.com/Microsoft/pai/tree/master/examples
