### ISSUE TITLE
ERROR: "CancelRequest not implemented". k8s cluster can not bootup.

### ISSUE THREAD

**Issue by winrgn** [Microsoft/pai#1915]
Hi, pls help to resolve this problem.
When I ran "python paictl.py cluster k8s-bootup -p $CONFIG_PATH", always got the following error:

2018-12-20 17:13:29,332 [WARNING] - deployment.k8sPaiLibrary.maintainlib.common : There will be a delay after installing, please wait.
2018-12-20 17:13:29,333 [INFO] - deployment.k8sPaiLibrary.maintainlib.kubectl_install : Wait 5s, and retry it later.
E1220 17:14:06.440453   30485 round_trippers.go:169] CancelRequest not implemented
E1220 17:14:38.440717   30485 round_trippers.go:169] CancelRequest not implemented
E1220 17:15:10.441012   30485 round_trippers.go:169] CancelRequest not implemented
E1220 17:15:42.441323   30485 round_trippers.go:169] CancelRequest not implemented
E1220 17:16:14.441546   30485 round_trippers.go:169] CancelRequest not implemented
Unable to connect to the server: context deadline exceeded (Client.Timeout exceeded while awaiting headers)

My cluster configuration:
machine-sku:
  GENERIC:
    mem: 1
    gpu:
      type: generic
      count: 1
    cpu:
      vcore: 1
    os: ubuntu16.04

machine-list:
  - hostname: ubuntu_201
    hostip: 10.158.230.201
    machine-type: GENERIC
    k8s-role: master
    etcdid: etcdid1
    zkid: "1"
    dashboard: "true"
    pai-master: "true"
  - hostname: ubuntu_202
    hostip: 10.158.230.202
    machine-type: GENERIC
    k8s-role: worker
    pai-worker: "true"

Release version is V0.8.3

Thanks.

**Comment by ydye** [comment]
1: kubernetes-configuration.yaml
2: pls ssh to your master node and execute the command following.
```
sudo docker ps -a
sudo docker logs kubelet 
```

**Comment by winrgn** [comment]
Problem fixed. It seems because of NTP abnormal. I adjusted the time of machines manually, and re-deploy cluster successfully.
