### ISSUE TITLE
Single Box System Deployment Problem: drivers-one-shot is not ready yet. Please wait for a moment!

### ISSUE THREAD

**Issue by liuqy1994** [Microsoft/pai#1916]
**Organization Name**: The fun of openPAI

**Short summary about the issue/question**:Single Box System Deployment ERROR: "drivers-one-shot is not ready yet. Please wait for a moment!"

**Brief what process you are following**: 
When i follow Step 6. Start all PAI services and typing "python paictl.py service start" in the dev-docker, the message "drivers-one-shot is not ready yet. Please wait for a moment!" raised.

**How to reproduce it**: Single Box System Deployment on two PC

**OpenPAI Environment**:
- OpenPAI version:V0.8.3
- Cloud provider or hardware configuration: HP-PC
- OS (e.g. from /etc/os-release):ubuntu 16.04
- Kernel (e.g. `uname -a`):4.15.0-42-generic
- Others:  GeForce GTX 745   Driver Version:  410.48

**Anything else we need to know**:
I think the issue is about nvidia driver, but i don't want to uninstall the Driver,
https://github.com/Microsoft/pai/issues/666#issuecomment-395285939
![image](https://user-images.githubusercontent.com/23204047/50263197-9a599380-044f-11e9-8440-17455a48571f.png)
 But the links in steps1 and steps2 are 404 "Not found"

Any help will be appreciative！

THX

**Comment by ydye** [comment]
@xudifsd

**Comment by ydye** [comment]
@liuqy1994  I have update the two link in the issue you pasted, please check it.

**Comment by liuqy1994** [comment]
> @liuqy1994 I have update the two link in the issue you pasted, please check it.
Thank you very much for your quick reply.I will try it now.

**Comment by liuqy1994** [comment]
> @liuqy1994 I have update the two link in the issue you pasted, please check it.

@ydye Hi, I have moved the folder "/pai/src/drivers/deploy" and changed the line in the file named"hadoop-node-manager.yaml.templata" wiht following your updated links.
"      - name: driver-path
        hostPath:
          path: /usr/lib/nvidia-410
"
And restart "python paictl.py service start" in dev-box, get "hadoop-name-node is not ready yet. Please wait for a moment!"

Then check docker logs of kubelet by "sudo docker logs kubelet" 

"220 09:29:13.338895    9245 kuberuntime_manager.go:514] Container {Name:nvidia-drivers Image:docker.io/openpai/drivers-384.111:latest Command:[bash -x ./install-all-drivers] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[{Name:DRIVER_PATH Value:/var/drivers/nvidia ValueFrom:nil} {Name:PRE_INSTALLED_NV_DRIVER_PATH Value:/usr/local/nvidia ValueFrom:nil}] Resources:{Limits:map[memory:{i:{value:2147483648 scale:0} d:{Dec:<nil>} s:2Gi Format:BinarySI}] Requests:map[memory:{i:{value:268435456 scale:0} d:{Dec:<nil>} s: Format:BinarySI}]} VolumeMounts:[{Name:driver-path ReadOnly:false MountPath:/var/drivers SubPath: MountPropagation:<nil>} {Name:device-path ReadOnly:false MountPath:/dev SubPath: MountPropagation:<nil>} {Name:modules-path ReadOnly:false MountPath:/lib/modules SubPath: MountPropagation:<nil>} {Name:drivers-log ReadOnly:false MountPath:/var/log SubPath: MountPropagation:<nil>} {Name:kernel-head ReadOnly:false MountPath:/usr/src SubPath: MountPropagation:<nil>} {Name:etc-path-ld ReadOnly:false MountPath:/etc/ld.so.conf.d SubPath: MountPropagation:<nil>} {Name:etc-path-docker ReadOnly:false MountPath:/etc/docker SubPath: MountPropagation:<nil>} {Name:pre-install-nv-driver-path ReadOnly:false MountPath:/usr/local/nvidia SubPath: MountPropagation:<nil>}] VolumeDevices:[] LivenessProbe:nil ReadinessProbe:&Probe{Handler:Handler{Exec:&ExecAction{Command:[cat /jobstatus/jobok],},HTTPGet:nil,TCPSocket:nil,},InitialDelaySeconds:5,TimeoutSeconds:1,PeriodSeconds:3,SuccessThreshold:1,FailureThreshold:3,} Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:Always SecurityContext:&SecurityContext{Capabilities:&Capabilities{Add:[ALL],Drop:[],},Privileged:*true,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:nil,} Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
"
How to fix this? 
THX！

**Comment by ydye** [comment]
Please paste more logs.

**Comment by liuqy1994** [comment]
@ydye 
This is docker logs of  kubelet :
![image](https://user-images.githubusercontent.com/23204047/50321401-b6bb0600-050b-11e9-9ebd-ed8b33211380.png)
`W1221 02:30:53.842503    4489 status_manager.go:474] Failed to update status for pod "hadoop-name-node-ds-lq2wv_default(7007063c-04c8-11e9-9281-8cec4b463f09)": Operation cannot be fulfilled on pods "hadoop-name-node-ds-lq2wv": StorageError: invalid object, Code: 4, Key: /registry/pods/default/hadoop-name-node-ds-lq2wv, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 7007063c-04c8-11e9-9281-8cec4b463f09, UID in object meta: 
I1221 02:30:54.290119    4489 kubelet.go:1873] SyncLoop (DELETE, "api"): "hadoop-name-node-ds-lxm6w_default(705ad41f-04c8-11e9-9281-8cec4b463f09)"
I1221 02:30:54.410262    4489 kubelet.go:1867] SyncLoop (REMOVE, "api"): "hadoop-name-node-ds-lxm6w_default(705ad41f-04c8-11e9-9281-8cec4b463f09)"
I1221 02:30:54.410353    4489 kubelet.go:2061] Failed to delete pod "hadoop-name-node-ds-lxm6w_default(705ad41f-04c8-11e9-9281-8cec4b463f09)", err: pod not found
I1221 02:30:54.427688    4489 kubelet.go:1857] SyncLoop (ADD, "api"): "hadoop-name-node-ds-4c5xw_default(70cf38d4-04c8-11e9-9281-8cec4b463f09)"
I1221 02:30:54.428045    4489 predicate.go:124] Predicate failed on Pod: hadoop-name-node-ds-4c5xw_default(70cf38d4-04c8-11e9-9281-8cec4b463f09), for reason: Node didn't have enough resource: memory, requested: 8589934592, used: 6685720576, capacity: 12665458471
I1221 02:30:54.863179    4489 kubelet.go:1873] SyncLoop (DELETE, "api"): "hadoop-name-node-ds-4c5xw_default(70cf38d4-04c8-11e9-9281-8cec4b463f09)"
I1221 02:30:54.943467    4489 kubelet.go:1867] SyncLoop (REMOVE, "api"): "hadoop-name-node-ds-4c5xw_default(70cf38d4-04c8-11e9-9281-8cec4b463f09)"
I1221 02:30:54.943551    4489 kubelet.go:2061] Failed to delete pod "hadoop-name-node-ds-4c5xw_default(70cf38d4-04c8-11e9-9281-8cec4b463f09)", err: pod not found
I1221 02:30:54.961088    4489 kubelet.go:1857] SyncLoop (ADD, "api"): "hadoop-name-node-ds-hgjs6_default(7120914b-04c8-11e9-9281-8cec4b463f09)"
I1221 02:30:54.961460    4489 predicate.go:124] Predicate failed on Pod: hadoop-name-node-ds-hgjs6_default(7120914b-04c8-11e9-9281-8cec4b463f09), for reason: Node didn't have enough resource: memory, requested: 8589934592, used: 6685720576, capacity: 12665458471
I1221 02:30:55.482626    4489 kubelet.go:1873] SyncLoop (DELETE, "api"): "hadoop-name-node-ds-hgjs6_default(7120914b-04c8-11e9-9281-8cec4b463f09)"
I1221 02:30:55.512297    4489 kubelet.go:1867] SyncLoop (REMOVE, "api"): "hadoop-name-node-ds-hgjs6_default(7120914b-04c8-11e9-9281-8cec4b463f09)"
I1221 02:30:55.523583    4489 kubelet.go:2061] Failed to delete pod "hadoop-name-node-ds-hgjs6_default(7120914b-04c8-11e9-9281-8cec4b463f09)", err: pod not found
I1221 02:30:55.567245    4489 kubelet.go:1857] SyncLoop (ADD, "api"): "hadoop-name-node-ds-h2q5q_default(71776d34-04c8-11e9-9281-8cec4b463f09)"
I1221 02:30:55.567583    4489 predicate.go:124] Predicate failed on Pod: hadoop-name-node-ds-h2q5q_default(71776d34-04c8-11e9-9281-8cec4b463f09), for reason: Node didn't have enough resource: memory, requested: 8589934592, used: 6685720576, capacity: 12665458471
I1221 02:30:56.063225    4489 kubelet.go:1873] SyncLoop (DELETE, "api"): "hadoop-name-node-ds-h2q5q_default(71776d34-04c8-11e9-9281-8cec4b463f09)"
I1221 02:30:56.099289    4489 kubelet.go:1867] SyncLoop (REMOVE, "api"): "hadoop-name-node-ds-h2q5q_default(71776d34-04c8-11e9-9281-8cec4b463f09)"
I1221 02:30:56.099364    4489 kubelet.go:2061] Failed to delete pod "hadoop-name-node-ds-h2q5q_default(71776d34-04c8-11e9-9281-8cec4b463f09)", err: pod not found
I1221 02:30:56.206314    4489 kubelet.go:1857] SyncLoop (ADD, "api"): "hadoop-name-node-ds-ssb5w_default(71d0ff52-04c8-11e9-9281-8cec4b463f09)"
I1221 02:30:56.206674    4489 predicate.go:124] Predicate failed on Pod: hadoop-name-node-ds-ssb5w_default(71d0ff52-04c8-11e9-9281-8cec4b463f09), for reason: Node didn't have enough resource: memory, requested: 8589934592, used: 6685720576, capacity: 12665458471
I1221 02:30:56.719882    4489 kubelet.go:1873] SyncLoop (DELETE, "api"): "hadoop-name-node-ds-ssb5w_default(71d0ff52-04c8-11e9-9281-8cec4b463f09)"
I1221 02:30:56.766792    4489 kubelet.go:1867] SyncLoop (REMOVE, "api"): "hadoop-name-node-ds-ssb5w_default(71d0ff52-04c8-11e9-9281-8cec4b463f09)"
I1221 02:30:56.766871    4489 kubelet.go:2061] Failed to delete pod "hadoop-name-node-ds-ssb5w_default(71d0ff52-04c8-11e9-9281-8cec4b463f09)", err: pod not found
I1221 02:30:56.786748    4489 kubelet.go:1857] SyncLoop (ADD, "api"): "hadoop-name-node-ds-tgngl_default(7236d1b2-04c8-11e9-9281-8cec4b463f09)"
I1221 02:30:56.787127    4489 predicate.go:124] Predicate failed on Pod: hadoop-name-node-ds-tgngl_default(7236d1b2-04c8-11e9-9281-8cec4b463f09), for reason: Node didn't have enough resource: memory, requested: 8589934592, used: 6685720576, capacity: 12665458471
I1221 02:30:57.922609    4489 kubelet.go:1873] SyncLoop (DELETE, "api"): "hadoop-name-node-ds-tgngl_default(7236d1b2-04c8-11e9-9281-8cec4b463f09)"
I1221 02:30:58.104075    4489 kubelet.go:1867] SyncLoop (REMOVE, "api"): "hadoop-name-node-ds-tgngl_default(7236d1b2-04c8-11e9-9281-8cec4b463f09)"
I1221 02:30:58.116560    4489 kubelet.go:2061] Failed to delete pod "hadoop-name-node-ds-tgngl_default(7236d1b2-04c8-11e9-9281-8cec4b463f09)", err: pod not found
I1221 02:30:58.191363    4489 kubelet.go:1857] SyncLoop (ADD, "api"): "hadoop-name-node-ds-jdkdx_default(7302ddbf-04c8-11e9-9281-8cec4b463f09)"
I1221 02:30:58.191769    4489 predicate.go:124] Predicate failed on Pod: hadoop-name-node-ds-jdkdx_default(7302ddbf-04c8-11e9-9281-8cec4b463f09), for reason: Node didn't have enough resource: memory, requested: 8589934592, used: 6685720576, capacity: 12665458471
W1221 02:30:58.349546    4489 status_manager.go:474] Failed to update status for pod "hadoop-name-node-ds-tgngl_default(7236d1b2-04c8-11e9-9281-8cec4b463f09)": Operation cannot be fulfilled on pods "hadoop-name-node-ds-tgngl": StorageError: invalid object, Code: 4, Key: /registry/pods/default/hadoop-name-node-ds-tgngl, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 7236d1b2-04c8-11e9-9281-8cec4b463f09, UID in object meta: 
I1221 02:30:58.646677    4489 kubelet.go:1873] SyncLoop (DELETE, "api"): "hadoop-name-node-ds-jdkdx_default(7302ddbf-04c8-11e9-9281-8cec4b463f09)"
I1221 02:30:58.680613    4489 kubelet.go:1867] SyncLoop (REMOVE, "api"): "hadoop-name-node-ds-jdkdx_default(7302ddbf-04c8-11e9-9281-8cec4b463f09)"
I1221 02:30:58.680699    4489 kubelet.go:2061] Failed to delete pod "hadoop-name-node-ds-jdkdx_default(7302ddbf-04c8-11e9-9281-8cec4b463f09)", err: pod not found
I1221 02:30:58.778114    4489 kubelet.go:1857] SyncLoop (ADD, "api"): "hadoop-name-node-ds-wvb7v_default(735ae005-04c8-11e9-9281-8cec4b463f09)"
I1221 02:30:58.778462    4489 predicate.go:124] Predicate failed on Pod: hadoop-name-node-ds-wvb7v_default(735ae005-04c8-11e9-9281-8cec4b463f09), for reason: Node didn't have enough resource: memory, requested: 8589934592, used: 6685720576, capacity: 12665458471
I1221 02:30:59.281666    4489 kubelet.go:1873] SyncLoop (DELETE, "api"): "hadoop-name-node-ds-wvb7v_default(735ae005-04c8-11e9-9281-8cec4b463f09)"
I1221 02:30:59.297208    4489 kubelet.go:1867] SyncLoop (REMOVE, "api"): "hadoop-name-node-ds-wvb7v_default(735ae005-04c8-11e9-9281-8cec4b463f09)"
I1221 02:30:59.297342    4489 kubelet.go:2061] Failed to delete pod "hadoop-name-node-ds-wvb7v_default(735ae005-04c8-11e9-9281-8cec4b463f09)", err: pod not found
I1221 02:30:59.404347    4489 kubelet.go:1857] SyncLoop (ADD, "api"): "hadoop-name-node-ds-m5d4q_default(73b8ef98-04c8-11e9-9281-8cec4b463f09)"
I1221 02:30:59.404682    4489 predicate.go:124] Predicate failed on Pod: hadoop-name-node-ds-m5d4q_default(73b8ef98-04c8-11e9-9281-8cec4b463f09), for reason: Node didn't have enough resource: memory, requested: 8589934592, used: 6685720576, capacity: 12665458471
I1221 02:30:59.873641    4489 kubelet.go:1873] SyncLoop (DELETE, "api"): "hadoop-name-node-ds-m5d4q_default(73b8ef98-04c8-11e9-9281-8cec4b463f09)"
I1221 02:30:59.929413    4489 kubelet.go:1867] SyncLoop (REMOVE, "api"): "hadoop-name-node-ds-m5d4q_default(73b8ef98-04c8-11e9-9281-8cec4b463f09)"
I1221 02:30:59.929498    4489 kubelet.go:2061] Failed to delete pod "hadoop-name-node-ds-m5d4q_default(73b8ef98-04c8-11e9-9281-8cec4b463f09)", err: pod not found
I1221 02:31:00.021678    4489 kubelet.go:1857] SyncLoop (ADD, "api"): "hadoop-name-node-ds-swpmk_default(74196ec9-04c8-11e9-9281-8cec4b463f09)"
I1221 02:31:00.021976    4489 predicate.go:124] Predicate failed on Pod: hadoop-name-node-ds-swpmk_default(74196ec9-04c8-11e9-9281-8cec4b463f09), for reason: Node didn't have enough resource: memory, requested: 8589934592, used: 6685720576, capacity: 12665458471
I1221 02:31:00.545036    4489 kubelet.go:1873] SyncLoop (DELETE, "api"): "hadoop-name-node-ds-swpmk_default(74196ec9-04c8-11e9-9281-8cec4b463f09)"
I1221 02:31:00.624129    4489 kubelet.go:1867] SyncLoop (REMOVE, "api"): "hadoop-name-node-ds-swpmk_default(74196ec9-04c8-11e9-9281-8cec4b463f09)"
I1221 02:31:00.635897    4489 kubelet.go:2061] Failed to delete pod "hadoop-name-node-ds-swpmk_default(74196ec9-04c8-11e9-9281-8cec4b463f09)", err: pod not found
I1221 02:31:00.637513    4489 kubelet.go:1857] SyncLoop (ADD, "api"): "hadoop-name-node-ds-mx247_default(74836e14-04c8-11e9-9281-8cec4b463f09)"
I1221 02:31:00.637808    4489 predicate.go:124] Predicate failed on Pod: hadoop-name-node-ds-mx247_default(74836e14-04c8-11e9-9281-8cec4b463f09), for reason: Node didn't have enough resource: memory, requested: 8589934592, used: 6685720576, capacity: 12665458471
I1221 02:31:01.128966    4489 kubelet.go:1873] SyncLoop (DELETE, "api"): "hadoop-name-node-ds-mx247_default(74836e14-04c8-11e9-9281-8cec4b463f09)"
I1221 02:31:01.147335    4489 kubelet.go:1867] SyncLoop (REMOVE, "api"): "hadoop-name-node-ds-mx247_default(74836e14-04c8-11e9-9281-8cec4b463f09)"
I1221 02:31:01.147405    4489 kubelet.go:2061] Failed to delete pod "hadoop-name-node-ds-mx247_default(74836e14-04c8-11e9-9281-8cec4b463f09)", err: pod not found
I1221 02:31:01.153909    4489 kubelet.go:1857] SyncLoop (ADD, "api"): "hadoop-name-node-ds-csqzn_default(74d345db-04c8-11e9-9281-8cec4b463f09)"
I1221 02:31:01.154231    4489 predicate.go:124] Predicate failed on Pod: hadoop-name-node-ds-csqzn_default(74d345db-04c8-11e9-9281-8cec4b463f09), for reason: Node didn't have enough resource: memory, requested: 8589934592, used: 6685720576, capacity: 12665458471
I1221 02:31:01.712305    4489 kubelet.go:1873] SyncLoop (DELETE, "api"): "hadoop-name-node-ds-csqzn_default(74d345db-04c8-11e9-9281-8cec4b463f09)"
I1221 02:31:01.774829    4489 kubelet.go:1867] SyncLoop (REMOVE, "api"): "hadoop-name-node-ds-csqzn_default(74d345db-04c8-11e9-9281-8cec4b463f09)"
I1221 02:31:01.774903    4489 kubelet.go:2061] Failed to delete pod "hadoop-name-node-ds-csqzn_default(74d345db-04c8-11e9-9281-8cec4b463f09)", err: pod not found
I1221 02:31:01.796622    4489 kubelet.go:1857] SyncLoop (ADD, "api"): "hadoop-name-node-ds-m4vgg_default(75330472-04c8-11e9-9281-8cec4b463f09)"
I1221 02:31:01.797021    4489 predicate.go:124] Predicate failed on Pod: hadoop-name-node-ds-m4vgg_default(75330472-04c8-11e9-9281-8cec4b463f09), for reason: Node didn't have enough resource: memory, requested: 8589934592, used: 6685720576, capacity: 12665458471
I1221 02:31:02.320117    4489 kubelet.go:1873] SyncLoop (DELETE, "api"): "hadoop-name-node-ds-m4vgg_default(75330472-04c8-11e9-9281-8cec4b463f09)"
I1221 02:31:02.367272    4489 kubelet.go:1867] SyncLoop (REMOVE, "api"): "hadoop-name-node-ds-m4vgg_default(75330472-04c8-11e9-9281-8cec4b463f09)"
I1221 02:31:02.367353    4489 kubelet.go:2061] Failed to delete pod "hadoop-name-node-ds-m4vgg_default(75330472-04c8-11e9-9281-8cec4b463f09)", err: pod not found
I1221 02:31:02.388140    4489 kubelet.go:1857] SyncLoop (ADD, "api"): "hadoop-name-node-ds-9v845_default(758d65d2-04c8-11e9-9281-8cec4b463f09)"
I1221 02:31:02.388492    4489 predicate.go:124] Predicate failed on Pod: hadoop-name-node-ds-9v845_default(758d65d2-04c8-11e9-9281-8cec4b463f09), for reason: Node didn't have enough resource: memory, requested: 8589934592, used: 6685720576, capacity: 12665458471
I1221 02:31:02.860708    4489 kubelet.go:1873] SyncLoop (DELETE, "api"): "hadoop-name-node-ds-9v845_default(758d65d2-04c8-11e9-9281-8cec4b463f09)"
I1221 02:31:02.893228    4489 kubelet.go:1867] SyncLoop (REMOVE, "api"): "hadoop-name-node-ds-9v845_default(758d65d2-04c8-11e9-9281-8cec4b463f09)"
I1221 02:31:02.893343    4489 kubelet.go:2061] Failed to delete pod "hadoop-name-node-ds-9v845_default(758d65d2-04c8-11e9-9281-8cec4b463f09)", err: pod not found
I1221 02:31:02.913368    4489 kubelet.go:1857] SyncLoop (ADD, "api"): "hadoop-name-node-ds-8vvmw_default(75dda938-04c8-11e9-9281-8cec4b463f09)"
I1221 02:31:02.913710    4489 predicate.go:124] Predicate failed on Pod: hadoop-name-node-ds-8vvmw_default(75dda938-04c8-11e9-9281-8cec4b463f09), for reason: Node didn't have enough resource: memory, requested: 8589934592, used: 6685720576, capacity: 12665458471
I1221 02:31:03.235330    4489 kuberuntime_manager.go:514] Container {Name:nvidia-drivers Image:docker.io/openpai/drivers-384.111:latest Command:[bash -x ./install-all-drivers] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[{Name:DRIVER_PATH Value:/var/drivers/nvidia ValueFrom:nil} {Name:PRE_INSTALLED_NV_DRIVER_PATH Value:/usr/local/nvidia ValueFrom:nil}] Resources:{Limits:map[memory:{i:{value:2147483648 scale:0} d:{Dec:<nil>} s:2Gi Format:BinarySI}] Requests:map[memory:{i:{value:268435456 scale:0} d:{Dec:<nil>} s: Format:BinarySI}]} VolumeMounts:[{Name:driver-path ReadOnly:false MountPath:/var/drivers SubPath: MountPropagation:<nil>} {Name:device-path ReadOnly:false MountPath:/dev SubPath: MountPropagation:<nil>} {Name:modules-path ReadOnly:false MountPath:/lib/modules SubPath: MountPropagation:<nil>} {Name:drivers-log ReadOnly:false MountPath:/var/log SubPath: MountPropagation:<nil>} {Name:kernel-head ReadOnly:false MountPath:/usr/src SubPath: MountPropagation:<nil>} {Name:etc-path-ld ReadOnly:false MountPath:/etc/ld.so.conf.d SubPath: MountPropagation:<nil>} {Name:etc-path-docker ReadOnly:false MountPath:/etc/docker SubPath: MountPropagation:<nil>} {Name:pre-install-nv-driver-path ReadOnly:false MountPath:/usr/local/nvidia SubPath: MountPropagation:<nil>}] VolumeDevices:[] LivenessProbe:nil ReadinessProbe:&Probe{Handler:Handler{Exec:&ExecAction{Command:[cat /jobstatus/jobok],},HTTPGet:nil,TCPSocket:nil,},InitialDelaySeconds:5,TimeoutSeconds:1,PeriodSeconds:3,SuccessThreshold:1,FailureThreshold:3,} Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:Always SecurityContext:&SecurityContext{Capabilities:&Capabilities{Add:[ALL],Drop:[],},Privileged:*true,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:nil,} Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
E1221 02:31:03.236718    4489 pod_workers.go:186] Error syncing pod c4603b46-0409-11e9-8e53-8cec4b463f09 ("drivers-one-shot-j56bm_default(c4603b46-0409-11e9-8e53-8cec4b463f09)"), skipping: failed to "StartContainer" for "nvidia-drivers" with ImagePullBackOff: "Back-off pulling image \"docker.io/openpai/drivers-384.111:latest\""
I1221 02:31:03.677639    4489 kubelet.go:1873] SyncLoop (DELETE, "api"): "hadoop-name-node-ds-8vvmw_default(75dda938-04c8-11e9-9281-8cec4b463f09)"
I1221 02:31:03.811833    4489 kubelet.go:1867] SyncLoop (REMOVE, "api"): "hadoop-name-node-ds-8vvmw_default(75dda938-04c8-11e9-9281-8cec4b463f09)"
I1221 02:31:03.812458    4489 kubelet.go:2061] Failed to delete pod "hadoop-name-node-ds-8vvmw_default(75dda938-04c8-11e9-9281-8cec4b463f09)", err: pod not found
I1221 02:31:03.830535    4489 kubelet.go:1857] SyncLoop (ADD, "api"): "hadoop-name-node-ds-qns9v_default(766a1079-04c8-11e9-9281-8cec4b463f09)"
I1221 02:31:03.830909    4489 predicate.go:124] Predicate failed on Pod: hadoop-name-node-ds-qns9v_default(766a1079-04c8-11e9-9281-8cec4b463f09), for reason: Node didn't have enough resource: memory, requested: 8589934592, used: 6685720576, capacity: 12665458471
I1221 02:31:04.294492    4489 kubelet.go:1873] SyncLoop (DELETE, "api"): "hadoop-name-node-ds-qns9v_default(766a1079-04c8-11e9-9281-8cec4b463f09)"
I1221 02:31:04.344752    4489 kubelet.go:1867] SyncLoop (REMOVE, "api"): "hadoop-name-node-ds-qns9v_default(766a1079-04c8-11e9-9281-8cec4b463f09)"
I1221 02:31:04.344828    4489 kubelet.go:2061] Failed to delete pod "hadoop-name-node-ds-qns9v_default(766a1079-04c8-11e9-9281-8cec4b463f09)", err: pod not found
I1221 02:31:04.363667    4489 kubelet.go:1857] SyncLoop (ADD, "api"): "hadoop-name-node-ds-6nh8w_default(76bb287f-04c8-11e9-9281-8cec4b463f09)"
I1221 02:31:04.363997    4489 predicate.go:124] Predicate failed on Pod: hadoop-name-node-ds-6nh8w_default(76bb287f-04c8-11e9-9281-8cec4b463f09), for reason: Node didn't have enough resource: memory, requested: 8589934592, used: 6685720576, capacity: 12665458471
I1221 02:31:04.878951    4489 kubelet.go:1873] SyncLoop (DELETE, "api"): "hadoop-name-node-ds-6nh8w_default(76bb287f-04c8-11e9-9281-8cec4b463f09)"
I1221 02:31:04.920295    4489 kubelet.go:1867] SyncLoop (REMOVE, "api"): "hadoop-name-node-ds-6nh8w_default(76bb287f-04c8-11e9-9281-8cec4b463f09)"
I1221 02:31:04.933467    4489 kubelet.go:2061] Failed to delete pod "hadoop-name-node-ds-6nh8w_default(76bb287f-04c8-11e9-9281-8cec4b463f09)", err: pod not found
I1221 02:31:05.011683    4489 kubelet.go:1857] SyncLoop (ADD, "api"): "hadoop-name-node-ds-zd68q_default(7712f182-04c8-11e9-9281-8cec4b463f09)"
I1221 02:31:05.012042    4489 predicate.go:124] Predicate failed on Pod: hadoop-name-node-ds-zd68q_default(7712f182-04c8-11e9-9281-8cec4b463f09), for reason: Node didn't have enough resource: memory, requested: 8589934592, used: 6685720576, capacity: 12665458471`
And how can i get the logs of nn?

**Comment by ydye** [comment]
@hao1939 QoS problem. Resource not enough, watch the log of kubelet

**Comment by liuqy1994** [comment]
@ydye 
![image](https://user-images.githubusercontent.com/23204047/50322042-79a44300-050e-11e9-97ec-97954a1fb0fd.png)

I think the memory of  my PC (16G) is not enough.
So, i have to extending the memory ?

**Comment by fanyangCS** [comment]
64G mem is the minimum requirement.

**Comment by liuqy1994** [comment]
> 64G mem is the minimum requirement.

OK! 
I try the Single Box System Deployment in a workstation which the memory is 64G.

Thanks!
