### ISSUE TITLE
无法在HDFS的portal页面上传数据

### ISSUE THREAD

**Issue by hellocandy** [Microsoft/pai#1930]
**Organization Name**: advantech

**Short summary about the issue/question**:在Azure上部署的openPAI，无法上传文件到HDFS。

**Brief what process you are following**: 在Azure上部署了一个openPAI的集群（master1个，worker2个）。用80端口访问，在页面中因为没有HDFS的链接，然后改用IP:5070打开HDFS的页面，创建目录可以成功，但是上传文件到HDFS的时候出错。用F12查看，发现上传文件这个操作会跳转到内网的IP，因而会上传失败。

**How to reproduce it**: 在Azure上部署的openPAI，用IP:5070打开HDFS的页面，创建一个目录，然后点上传数据的按钮上传文件，此时上传会失败。

**OpenPAI Environment**:
- OpenPAI version: 0.8.2
- Cloud provider or hardware configuration: OpenPAI Cluster（master1个，worker2个）
- OS (e.g. from /etc/os-release): ubuntu16.04
- Kernel (e.g. `uname -a`):
- Others:

**Anything else we need to know**:

**Comment by NothingLZ** [comment]
@hellocandy
HDFS上传问题解决没？

**Comment by fanyangCS** [comment]
I assume the issue has been resolved according to https://github.com/Microsoft/pai/issues/1971.

**Comment by hellocandy** [comment]
用http://external-ip/webhdfs这种登陆方式，在上传文件的时候，也是会跳转到内网IP：

http://10.0.0.7:5075/webhdfs/v1/Container/xianfeng/pai_job.json?op=CREATE&namenoderpcaddress=10.0.0.5:9000&createflag=&createparent=true&overwrite=false
