### ISSUE TITLE
在job中设置code，data，output到HDFS的目录，而container启动后只能在里面看到code映射进来了

### ISSUE THREAD

**Issue by hellocandy** [Microsoft/pai#1931]
**Organization Name**: advantech

**Short summary about the issue/question**:在job中设置code，data，output到HDFS的目录，而container启动后只能在里面看到code映射进来了。

**Brief what process you are following**: openPAI是什么时间将job中设置的HDFS路径映射到container里面的？同时指定code，data，output，只有code映射成功的原因？

**How to reproduce it**: 

**OpenPAI Environment**: singlebox openPAI
- OpenPAI version: 0.8.2
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):Ubuntu16.04
- Kernel (e.g. `uname -a`):
- Others:

**Anything else we need to know**:

**Comment by YanjieGao** [comment]
Pls see doc explain PR: https://github.com/Microsoft/pai/pull/1935

**Comment by YanjieGao** [comment]
finished
