### ISSUE TITLE
end-to-end-test这个openAPI的服务可否删除

### ISSUE THREAD

**Issue by hellocandy** [Microsoft/pai#1932]
**Organization Name**: advantech

**Short summary about the issue/question**:在Azure上部署了一个openPAI集群，没有GPU。在启动后，openPAI会定期执行end-to-end-test。这个定期的job默认会请求使用GPU，而我们的平台没有GPU，这个job会失败。可以在K8S里面删除这个end-to-end-test服务吗？

**Brief what process you are following**: 

**How to reproduce it**: 

**OpenPAI Environment**: cluster
- OpenPAI version:0.8.2
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Anything else we need to know**:

**Comment by ydye** [comment]
直接删除这个目录即可。 https://github.com/Microsoft/pai/tree/master/src/end-to-end-test/deploy
