### ISSUE TITLE
Azure上Cluster部署的openPAI，同时Submit300个Job，没有在预期的时间内执行完

### ISSUE THREAD

**Issue by hellocandy** [Microsoft/pai#1937]
**Organization Name**: advantech

**Short summary about the issue/question**:Azure上Cluster部署的openPAI，同时Submit300个Job，没有在预期的时间内执行完

**Brief what process you are following**: 
同样的参数，在实体机的SibgleBox上执行，跟在Azure云上搭建的Cluster的openPAI，在执行结果上的表现差别比较大。第一个场景，同时派发10个job，两种环境下，都很快执行完了。第二个场景，同时派发300个job，实体机上的过了1小时后，也执行完毕了。而Azure上的300个Job，从昨天晚上9点开始，到现在，过了12个小时还没有执行完成。

**How to reproduce it**: 

**OpenPAI Environment**: Cluster on Azure
- OpenPAI version:0.8.2
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Anything else we need to know**:

**Comment by mzmssg** [comment]
@hellocandy 
有实体机和azure的hardware configuration吗，还有相关的job description

**Comment by mzmssg** [comment]
I suspect most resource are taken by YARN AM, then no enough resource for real job. please refer #1819

**Comment by fanyangCS** [comment]
How many GPU VMs are you running in the cluster?

**Comment by scarlett2018** [comment]
@hellocandy - are you still seeing the issue? if so, would you mind to provide update for @fanyangCS 's recent question? thanks.
