### ISSUE TITLE
[doc] add Resource-Requirement recommend hardware spec [Future extend best practices doc]

### ISSUE THREAD

**Issue by YanjieGao** [Microsoft/pai#1938]
**What would you like to be added**:
add Resource-Requirement recommend hardware spec []
**Why is this needed**:
change wiki page
**Without this feature, how does the current module work**：
work well, but user confused about how to config it
**Components that may involve changes**:
wiki page of https://github.com/Microsoft/pai/wiki/Resource-Requirement

**Comment by squirrelsc** [comment]
@YanjieGao I'm not very clear what's expected in this issue? There is resource-requirement page already, is anything needed more?

**Comment by hao1939** [comment]
Close it, we already have a resource-requirement page.
