### ISSUE TITLE
Need unallocated resource view to help customize job resource requirements

### ISSUE THREAD

**Issue by mzmssg** [Microsoft/pai#1943]
**What would you like to be added**: Unallocated resource view

**Why is this needed**: Users doesn't know how many resource they could apply. Hence,  users might submit exceeding job, then get failed.

**Without this feature, how does the current module work**： from YARN page maste_ip:8088/cluster/nodes

**Components that may involve changes**: rest-server, webportal

**Comment by fanyangCS** [comment]
does the yarn portal provide such information?

**Comment by fanyangCS** [comment]
close and track in #2208 .
