### ISSUE TITLE
How to delete a submitted job?

### ISSUE THREAD

**Issue by liuqy1994** [Microsoft/pai#1952]
**Organization Name**: Fans

**Short summary about the issue/question**: How to delete a submitted job? Just like the way to submit jobs，a button on a web page of PAI, or an API.

**Brief what process you are following**: 

**How to reproduce it**: 

**OpenPAI Environment**:
- OpenPAI version:V0.8.3
- Cloud provider or hardware configuration:None
- OS (e.g. from /etc/os-release):Ubuntu16.04
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by liuqy1994** [comment]
Any help will be appreciated！:)

**Comment by yqwang-ms** [comment]
frameworklauncher supports to delete job.
See https://github.com/Microsoft/pai/blob/master/subprojects/frameworklauncher/yarn/doc/USERMANUAL.md#delete-framework

But seems restserver does not support (expose) it. 
Maybe it is by design.
@Gerhut to confirm.

**Comment by liuqy1994** [comment]
@yqwang-ms 
Like this ?
` curl -X DELETE http://{LauncherAddress}/v1/Frameworks/ExampleFramework -d @ExampleFramework.json --header "Content-Type: application/json"`

![image](https://user-images.githubusercontent.com/23204047/50513749-9d4e2700-0ad4-11e9-8f14-f23fb87c8f44.png)
![image](https://user-images.githubusercontent.com/23204047/50513755-a808bc00-0ad4-11e9-843c-c7eae8050c32.png)

**Comment by yqwang-ms** [comment]
No need to specify body.

**Comment by liuqy1994** [comment]
Ok, I will try it later.
THX！

**Comment by fanyangCS** [comment]
What is the purpose of job deletion? We currently do not to support job deletion in our external Rest API. Because most platform admins prefer so.

**Comment by 111Moderato** [comment]
I tried to delete one of the jobs and run the command：
`curl -XDELETE 'http://master-ip:9086/v1/Frameworks/admin~caffe-mnist'`
But I got a lot of logs,  I think the important ones is：
`{"exception":"AuthorizationException","message":"com.microsoft.frameworklauncher.common.exceptions.AuthorizationException: User [default] does not have the Writable Access to the Namespace [admin].\n\tat 
`
How can I get permission? @fanyangCS @yqwang-ms
