### ISSUE TITLE
webportal login failed after click button with default username and password

### ISSUE THREAD

**Issue by dongluyang** [Microsoft/pai#1958]
when i input admin and admin-password in input field, and click login button, the request is pending,after about 2 mins, the request failed because of timeout. the snapshot is show as below

![1](https://user-images.githubusercontent.com/22255561/50507299-d88e2d00-0ab7-11e9-9b99-f16540304371.png)
and then i see the log for rest-server, its error log is shown as below, can anybody figure out what is wrong, is it etcd's problem ? thank you very much

![2](https://user-images.githubusercontent.com/22255561/50507335-04111780-0ab8-11e9-927f-1fd279ed14db.png)

OpenPAI Environment:

OpenPAI version: v0.8.2
OS (16.04.1 LTS (Xenial Xerus)):
Kernel (Linux pai-2 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux):
Hardware (e.g. core:32, memory:30 GB, storage size: 203G ,):

**Comment by Gerhut** [comment]
Hi @dongluyang 

Could you please ensure that the etcd server is accessible in your cluster?

You can find the etcd url in environment variables of rest server.

**Comment by dongluyang** [comment]
ok,thank you very much. i see, this ticket can be closed.

**Comment by dongluyang** [comment]
@Gerhut  thank you very much
