### ISSUE TITLE
Need an E2E Jupyter Running example for EDU scenario

### ISSUE THREAD

**Issue by scarlett2018** [Microsoft/pai#1962]
**What would you like to be added**:
This is a requirement from Microsoft EDU sales team, they are promoting OpenPAI to EDU scenarios where students use Jupyter to submit jobs to OpenPAI@Azure.

**Why is this needed**:
They are using this as a reference case for EDU promotion.

**Without this feature, how does the current module work**：
It is not functional working right now.

**Components that may involve changes**: N/A

--------------------------
Minjun will add more information later.

**Comment by minjunxu** [comment]
Thanks Scarlett.
We working with an university customer and help them install OpenPAI at 21V.  The PAI had deployed, but customer didn't know how to use json in JupyterHub to connect PAI to submit job.  They hope can find easy way or simple code to help them submit jobs.  PS:They are not specialist of computer.  The machine learning training sample is 385MB and bigger than 10MB limited. I will use Onedrive to share the file to you and please forward to internal colleague. Thanks.

**Comment by fanyangCS** [comment]
https://github.com/Microsoft/pai/blob/master/examples/job-editor/README.md

https://github.com/Microsoft/pai/blob/master/examples/jupyter/README.md

Here are two examples about Jupyter. Is that useful?

**Comment by scarlett2018** [comment]
@fanyangCS  - just had a quick call with minjun, he is having trouble to find the "Jupyter token". He will share the env info to me to follow up accordingly.

**Comment by scarlett2018** [comment]
Minjun's env does not have token but using user/psw directly. the problem was resolved by @hao1939 , closing the ticket.
