### ISSUE TITLE
Log retention period should start from when job finished

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#1969]
User had a long run job, for about 1 week, and found the log removed just after the job finished.

**What would you like to be added**:
Log retention period should start from when job finished.

**Why is this needed**:
User may have long run job, the log may pass retention period before job finished.

**Without this feature, how does the current module work**：
We could simply increase the log retention period.

**Components that may involve changes**:

**Comment by fanyangCS** [comment]
can we count the log retention period from the complete of a job?

**Comment by hao1939** [comment]
For now, we can't.
A possible solution would be archiving the logs in history server.
