### ISSUE TITLE
How to gather the job startTime info in PAI?

### ISSUE THREAD

**Issue by JianfeiHu** [Microsoft/pai#1978]
Organization Name: MSRAIT
Short summary about the issue/question:我试图统计用户对系统的使用情况，计算用户对资源的使用时间,从REST服务器获取作业列表，发现只有createdTime和completedTime。createdTime是用户提交作业的时间，而不是job实际运行的时间。PAI是否记录作业实际运行的时间？

OpenPAI Environment:
- OpenPAI version:0.8.2
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Comment by yqwang-ms** [comment]
FrameworkLauncher记录了YARN app实际运行时间，
  private Long applicationLaunchedTimestamp;
  private Long applicationCompletedTimestamp;

如：
![image](https://user-images.githubusercontent.com/32826762/50762154-2587b580-12a7-11e9-95a4-e60e1295201f.png)

但是restserver好像没暴露出来
@Gerhut

**Comment by JianfeiHu** [comment]
@yqwang-ms我在使用这种方法获得appLaunchedTime，但是对一部分job查询时会出现这种情况。
http://10.150.144.225:9086/v1/Frameworks/nni_exp_NftmjP6l_trial_jOcTK

**Comment by yqwang-ms** [comment]
这个job应该被人删掉了，你看看nni那边是不是有删除逻辑

**Comment by scarlett2018** [comment]
I'm closing the issue as the original question had been resolved. @JianfeiHu - please follow up with @yds05 for the nni job log issue.

**Comment by yqwang-ms** [comment]
@JianfeiHu We have just refined the "作业实际开始运行的时间" in frameworkcontroller (so will be supported in Pure K8S PAI soon).

For more details, please check:
microsoft/frameworkcontroller#35

For a job attempt:
WaitingTime = RunTime - StartTime
RunningTime = CompletionTime - RunTime

For the whole job which may have multiple attempts:
WaitingTime = Sum_all_attempts (RunTime - StartTime)
RunningTime = Sum_all_attempts (CompletionTime - RunTime)
