### ISSUE TITLE
任务对应容器的历史信息

### ISSUE THREAD

**Issue by hirolsj** [Microsoft/pai#1979]
**NEL-BITA USTC**: 

**Short summary about the issue/question**:
需要任务对应的容器的历史信息

**Brief what process you are following**: 
集群中一个节点产生故障重启了，如何查找到重启前任务相关的信息，通过ip和重启的时间查找到故障前正在执行的任务。
目前这个接口rest-serverUrl/api/v1/jobs/jobname仅仅能查到当前的container信息（包括ip），如果任务retry，则任务对应的container信息就会被更新，无法查到历史信息。

容器的相关历史信息不仅是用于集群故障的分析，同时也是记录用户消费机时的依据。所以希望大佬们能重视这个需求，感谢！

**Comment by yqwang-ms** [comment]
Before we support history server, you need to check AM logs for history retried containers, such as:
![image](https://user-images.githubusercontent.com/32826762/50807346-f28c0300-1334-11e9-944c-21a5d12e93f2.png)
![image](https://user-images.githubusercontent.com/32826762/50807356-fae43e00-1334-11e9-9630-1d3c858715c7.png)
![image](https://user-images.githubusercontent.com/32826762/50807369-08012d00-1335-11e9-9915-0e23490f3b6f.png)

**Comment by hirolsj** [comment]
Thanks for your prompt reply.We need to know more about history information of container，such as container starttime、endtime、status。

**Comment by yqwang-ms** [comment]
The log should contains enough info to **infer** history container starttime、endtime、status。
Pls check

**Comment by damon008** [comment]
目前yarn在任务结束之前暴露容器的信息，但是任务一旦结束，容器的信息就看不到了，如下图：
![image](https://user-images.githubusercontent.com/25023599/50817379-94741580-135e-11e9-9e02-52065d860523.png)

![image](https://user-images.githubusercontent.com/25023599/50817353-80301880-135e-11e9-929d-a6757956f4d2.png)

so，想问下是否可以提供任务中的容器的信息，即使是历史容器。

**Comment by hirolsj** [comment]
容器的相关历史信息不仅是用于集群故障的分析，同时也是记录用户消费机时的依据。所以希望大佬们能重视这个需求，感谢！

**Comment by yqwang-ms** [comment]
感谢提出的意见，不过现在只能通过AM的log来看container的retry历史信息。未来打算支持HistoryServer来把这些结构化的信息暴露到网页上。

**Comment by damon008** [comment]
请问AM的log指的是这个：http://10.11.2.38:8042/node/containerlogs/container_e182_1545644799805_0617_01_000002/_e0cafb2d8d4c42639e9ff49105f36429？

**Comment by yqwang-ms** [comment]
对提供API的。
访问不了你的链接，看样子是。（你参考我的第一个回复）

**Comment by damon008** [comment]
嗯，看到了就是这个地址，但是请问具体这个地址调用YARN服务的哪个API呢？

**Comment by damon008** [comment]
嗯，看到返回的信息是个html，而且没有容器的启动成功开始时间等信息。

**Comment by damon008** [comment]
只看到这些，没看到你的那个
![1546941352 1](https://user-images.githubusercontent.com/25023599/50823358-bd040b80-136e-11e9-8289-9cd68bc727b6.png)

**Comment by yqwang-ms** [comment]
你再看看我第一个回复吧

**Comment by yqwang-ms** [comment]
你把你能看到的这些log 也发出来吧，也可能启动AM之前，就报错退出了

**Comment by damon008** [comment]
但任务还是在运行中状态

**Comment by damon008** [comment]
嗯，这边可以看到你说的日志了，要经过redirect才能看到

**Comment by hirolsj** [comment]
感谢耐心的解答。
