### ISSUE TITLE
FAQ for Ops - What's the default *log store duration*? How to extend the duration? 

### ISSUE THREAD

**Issue by JianfeiHu** [Microsoft/pai#1982]
Organization Name: 
Short summary about the issue/question:We want to keep the logs for a long time. Where do we keep the logs for the system and job? How long is the storage period?

OpenPAI Environment:
OpenPAI version:0.8.2
Cloud provider or hardware configuration:
OS (e.g. from /etc/os-release):
Kernel (e.g. uname -a):
Hardware (e.g. core number, memory size, storage size, GPU type etc.):
Others:

**Comment by mzmssg** [comment]
Job's logs are stored on hdfs, by default it will be stored under `/sys/logs` for 7 days.
https://github.com/Microsoft/pai/blob/9bfdbb96edc2d56b54af73c7358b6a9350fd0b3d/src/hadoop-node-manager/deploy/hadoop-node-manager-configuration/yarn-site.xml#L79

**Comment by JianfeiHu** [comment]
@mzmssg 这个值有上限吗？还有系统的日志保存在什么地方？

**Comment by mzmssg** [comment]
@JianfeiHu 
Seems no limitation. 
We don't retain system log, you could persist them by yourself.

**Comment by ydye** [comment]
For service's log, the max log size will be 100m * 10.
```
 "log-opts": {
    "max-size": "100m",
    "max-file": "10"
  },
```

**Comment by mzmssg** [comment]
@JianfeiHu 
Refer to #2244
