### ISSUE TITLE
Add jsonc support for job submission page (V1)

### ISSUE THREAD

**Issue by zhouhaoyu** [Microsoft/pai#1986]
**What would you like to be added**: JSONC (JSON with comments) support on the job submission page (V1) of PAI web portal.

**Why is this needed**: We are currently working on vscode extension for OpenPAI, and would like to improve readability for editing job config file by adding relevant comments in json. To streamline the job submission experience, it could be better if user can upload the commented json straightly to PAI web portal.

**Without this feature, how does the current module work**：User need to strip out the comments from json in order to submit job in PAI web portal.

**Components that may involve changes**: PAI Web portal

**Comment by fanyangCS** [comment]
@scarlett2018 , yes. Yaml has built-in support for comments.

**Comment by fanyangCS** [comment]
closed.
