### ISSUE TITLE
Reduce reserved CPU/memory of worker node

### ISSUE THREAD

**Issue by squirrelsc** [microsoft/pai#1988]
**What would you like to be added**:
1. reduce default reserved CPU/memory for worker node itself, so that some resource can be released for scheduled job.
2. document current behavior of reserved resources, and how to adjust it, if it's possible.

**Why is this needed**:
If user has a computer with 32G mem, there is only 16G for job scheduling. System reserved half of memory in this case, and similar with CPU core also.

**Without this feature, how does the current module work**：
There is no workaround so far.

**Components that may involve changes**:
Deployment

**Comment by fanyangCS** [comment]
https://github.com/Microsoft/pai/wiki/Resource-Requirement.
The number is calculated and measured in the heavy load case. Reduce the number may lead to unstable system behavior.

You can customized the resources requirements through manual config. But you will have to control the load of the system. It is not recommended to do so. 

We are working on a light-weight version to mitigate this issue.

**Comment by scarlett2018** [comment]
Before start this work, we need to have metrics and goals to measure reserved CPU/Memory usage.

**Comment by fanyangCS** [comment]
will address it in pure k8s version.
