### ISSUE TITLE
Let user know current available capacity

### ISSUE THREAD

**Issue by squirrelsc** [microsoft/pai#1989]
**What would you like to be added**:
Add a table in dashboard, tell user below kinds of capacity is available. So that user have a chance to schedule a runnable job, instead of wait until enough resource.

type|CPU|memory|GPU
---|---|---|---
maximized CPU|8|8G|1
maximized Memory|4|64G|0
maximized GPU|4|16G|4

**Why is this needed**:
As fragment resource, user has no idea how difficult to apply resource for his job. And his job may wait long time even no chance to execute.

**Without this feature, how does the current module work**：
No workaround, user may wait long time.

**Components that may involve changes**:

**Comment by fanyangCS** [comment]
done after v0.17. the home page can show the available resource.
