### ISSUE TITLE
Tracking job hdfs issues

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#1992]
User job encounter hdfs errors while saving/reading checkpoints.
It will prevent user job from saving/reading checkpoint.
User job is separately into multiple stages, now it's blocking.

Will collect user jobs here for further investigate.

http://*.239/yarn/10.0.0.16:8042/node/containerlogs/container_1542939248333_4134_01_000002/test/stdout/?start=0 

http://*.239/view.html?username=test&jobName=jhua_BERT_QnA_30M_1ap_5e5_unshared_qpc_circle_fix_continue_nohrs_2

**Comment by YanjieGao** [comment]
https://github.com/Microsoft/pai/pull/1858

**Comment by hao1939** [comment]
Should mitigate by #1857 .

**Comment by mzmssg** [comment]
Closed it firstly, please reopen it with any update
