### ISSUE TITLE
[HDFS-feature-enhancement] quota management for HDFS

### ISSUE THREAD

**Issue by YanjieGao** [Microsoft/pai#1995]
###  What would you like to be added:
quota management for HDFS. Manage quota for job and service.
### Why is this needed:

quota management for HDFS. Quota management for job folder & service folder

###  Without this feature, how does the current module work：
HDFS occupy disk when pai runs lony time will trigger alert for local host disk usage to operator.
Components that may involve changes:

### How to:

1 from PAI design & refactor view:
Replanning the disk usage on HDFS;
1.1 space for service & its folder
1.2 space for job & its folder [important]
should limit the user flexibility
![image](https://user-images.githubusercontent.com/5576848/51009081-9e2d9100-1589-11e9-9456-eca317c2b59a.png)

2 Give doc or auto config HDFS directory quota [Based on 1 then could better do & manage 2]
https://hadoop.apache.org/docs/r2.7.2/hadoop-project-dist/hadoop-hdfs/HdfsQuotaAdminGuide.html

3 For config hdfs multipath feature has merged. 
Give admin flexibility for disk space of HDFS.

**Comment by scarlett2018** [comment]
Closing as dup of #2242
