### ISSUE TITLE
`nvidia-smi` can not detect the PID of processes using GPU

### ISSUE THREAD

**Issue by shawntian90** [Microsoft/pai#2001]
Hi,

`nvidia-smi` can not detect the PID info of processes using the GPU.

Recurrent steps:

1. Login to the job instance via SSH
2. Run `nvidia-smi` and it shows:

```
root@xxx:~# nvidia-smi
Mon Jan 14 07:10:25 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.111                Driver Version: 384.111                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 00000000:83:00.0 Off |                  N/A |
| 22%   59C    P2    74W / 250W |  11637MiB / 12207MiB |     14%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

But acutally, there is an python process runing the [Minst training by Tensorflow](https://www.tensorflow.org/tutorials/)

Please help!

Thanks.
-
Shawn

**Comment by fanyangCS** [comment]
please make sure the nvidia-smi is run under the same process tree space with the python process.

**Comment by shawntian90** [comment]
@fanyangCS

Both `nvidia-smi` and `python process` are running in the same job instance. Login via ssh and run the command. All are running in the same docker container.

I do not get the specific idea of `the same process tree space`. In my case, do you mean:

1. Same docker container
2. Same ssh login-session (`nvidia-smi` and `python process` are launched through SSH)

Which is correct?

**Comment by shawntian90** [comment]
@mzmssg Thanks a lot!

I also find the issue [How to show processes in container with cmd nvidia-smi?](https://github.com/NVIDIA/nvidia-docker/issues/179) , which indicate that this is a defect of NVIDIA driver.

Thanks again!

**Comment by siaimes** [comment]
I solved this issue by using [mpu](https://github.com/matpool/mpu). Just run the following command on the host machine.
```bash
git clone https://github.com/matpool/mpu.git
cd mpu
make
sudo make install
```
