### ISSUE TITLE
Question about Best Practices: what is the easiest way to save model after training with PAI?

### ISSUE THREAD

**Issue by scarlett2018** [Microsoft/pai#2003]
I'm currently using PAI to train CIFAR-10 on Pytorch. The codes are in Python, I know how to save checkpoints in local. But when training with PAI, I don't know where does my model goes. 

The question is: 
- Should I put it in some place in docker? how to and how can I get it later?
- Should I put it in HDFS? is there any sample codes and any recommend place to save the file?

_**My codes for saving in local:**_
        if not os.path.isdir('checkpoint'):
            os.mkdir('checkpoint')
        torch.save(state, './checkpoint/ckpt.t7')

**Comment by sterowang** [comment]
In current default implementation on PAI, you need to write your model on HDFS with path specified in environment variable $PAI_OUTPUT_DIR.

**Comment by scarlett2018** [comment]
> In current default implementation on PAI, you need to write your model on HDFS with path specified in environment variable $PAI_OUTPUT_DIR.

Is there any sample codes for Python?
