### ISSUE TITLE
support to run multiple jobs on same GPU.

### ISSUE THREAD

**Issue by squirrelsc** [Microsoft/pai#2014]

**Comment by mzmssg** [comment]
I doesn't get the point. 
1.  A more finer granularity scheduling, i.e. 0.5 or 0.25 GPU. 
2.  Packing a single user's mutiple jobs on the same GPU.
Which one is your need?

**Comment by squirrelsc** [comment]
for example, 1 powerful GPU with 11GB mem. if ther are 4 jobs with 2GB GPU mem requirement, they can run on the same card. So that more job can be run at same time. It doesn't matter how to implement it, the goal is to enhance usage of GPU resource (computing and memory).

**Comment by fanyangCS** [comment]
currently GPU does not provide a mechanism to isolate two processes on the same GPU. unless you are absolutely sure one process will not interfere with other processes, this could result in process crash in the worse case.

Right now the platform has no way to ensure that.

**Comment by fanyangCS** [comment]
actually, if a user would like to run two jobs on a GPU, there is a way to do that. He/she can just launch a job, ssh to the container and manually launcher two processes sharing one GPU.

We do not have a plan to support the feature from the platform side in the near future, unless new generation GPU has more advanced MPS support.

So reference about MPS:
https://docs.nvidia.com/deploy/pdf/CUDA_Multi_Process_Service_Overview.pdf
https://stackoverflow.com/questions/34709749/how-do-i-use-nvidia-multi-process-service-mps-to-run-multiple-non-mpi-cuda-app
https://devtalk.nvidia.com/default/topic/1024657/cuda-programming-and-performance/question-about-gpu-sharing-of-multi-process-service/
