### ISSUE TITLE
user list ranking is not a-z, z-a.

### ISSUE THREAD

**Issue by scarlett2018** [Microsoft/pai#2016]
I'm using the IT deployment (PAI 0.8.2). When click ranking by user, user Jianxun is ranked before user admin. I can share the server access IP if it can not be reproduced in other deployment.

**requirement**: case insensitive ranking.

**Comment by abuccts** [comment]
"J" does rank before "a" in ascii order, "A-Z" ranks before "a-z".

**Comment by Gerhut** [comment]
Due to new job-list page uses `localeCompare` for ordering, this issue has been resolved.

![image](https://user-images.githubusercontent.com/2500247/55206913-23345800-5213-11e9-9953-de51ec8d4b17.png)
