### ISSUE TITLE
[build] directly build e2e meet hadoop-run dep build failure issue

### ISSUE THREAD

**Issue by YanjieGao** [Microsoft/pai#2021]
run 
```
python pai_build.py build -c ~/pai-config/ -s end-to-end-test
```

![image](https://user-images.githubusercontent.com/5576848/51292001-2b6a5d00-1a44-11e9-86db-34e750e5a117.png)

**Comment by mzmssg** [comment]
seems it's a build issue, could you check this path?

**Comment by YanjieGao** [comment]
Ok. 
If i  run below cmd, do i need to also have other operate to prepare folder? Goal is to build 1 service
./pai_build.py build -c /path/to/configuration-dir/  -s end-to-end-test

https://github.com/Microsoft/pai/blob/master/docs/pai-build/pai-build.md

**Comment by mzmssg** [comment]
@YanjieGao 
I can't reproduce it, need more log before the failure. Have the e2e-test build triggered hadoop-ai build?

**Comment by YanjieGao** [comment]
seems trigger hadoop-ai build

**Comment by mzmssg** [comment]
I have tested it in a fresh environment and it succeeded.

For your case, I think you should remove stale data under /hadoop-binary/.
