### ISSUE TITLE
[hdfs] hdfs api read local block path issue

### ISSUE THREAD

**Issue by YanjieGao** [Microsoft/pai#2023]
After sync with ziming. 

When occurs:
This error maybe occur when touch this condition.
- job need read hdfs block from local
- framework built-in or other hdfs client or user has default config to first read from local disk
http://archive.cloudera.com/cdh4/cdh/4/hadoop/hadoop-project-dist/hadoop-hdfs/ShortCircuitLocalReads.html

Why:
as job not mount local host hdfs data path. Which will lead error log. but then client will select read from datanode which will not break the job whole cycle. 

How to do:
After sync with ziming, currently we maybe could treat it as a known issue

Logs:
For exampel tf job read data from hdfs trainsient occur this:
![image](https://user-images.githubusercontent.com/5576848/51294066-3d4ffe00-1a4c-11e9-8d19-ca822dd45215.png)

**Comment by mzmssg** [comment]
A possible reason, in shortcircuit feature, client need to connect hdfs socket directly, but we doesn't mount the socket in job container.

We could disable this feature. It only take effect when read large hdfs data from local node.

**Comment by YanjieGao** [comment]
agree, suggest disable as doc said:

![image](https://user-images.githubusercontent.com/5576848/51299221-932fa080-1a62-11e9-9523-57f988f7757b.png)

As in my understand in pai deployment will not mount hdfs folder to job container

**Comment by YanjieGao** [comment]
ref: https://github.com/Microsoft/pai/search?q=dfs.client.read.shortcircuit&unscoped_q=dfs.client.read.shortcircuit
