### ISSUE TITLE
logger can print filePath

### ISSUE THREAD

**Issue by swenzi** [microsoft/pai#2030]
Hi ，
Rest-server can log and print file name information as follows:
2019-01-17 17:15:02,683 [INFO] server.js Config: 123 

The configuration is as follows：
[file.zip](https://github.com/Microsoft/pai/files/2768065/file.zip)

**Comment by swenzi** [comment]
Hi, At present, there is no print log file path. It is recommended to print log file path. So I gave my own configuration. I wonder if I can add support for this function.

**Comment by fanyangCS** [comment]
@swenzi, sorry for the late response. Please describe your requirement in more details so we do not misunderstand it.  

Also, we welcome contribution. You can go ahead to submit your PR, we will see if this is a good fit for us.
