### ISSUE TITLE
Service "Tracking Page" log as configurable setting to IT Admin/ops

### ISSUE THREAD

**Issue by scarlett2018** [Microsoft/pai#2037]
**Problem**:
有用户反映十天之前的job的“Go to Tracking Page ”查询不到了，之前是存在的。
系统默认的日志保存时间是多久？

**Current solution been told**
Default retention time is 7 days(604800 secs)
Refer https://github.com/Microsoft/pai/search?q=retain-seconds&unscoped_q=retain-seconds
You could modify these files then restart Hadoop-resource-manager and Hadoop-node-manager.

**Suggested solution**
Exposing the log retain-seconds to service config. We should have a unified solution for PAI k8s launcher as well.

**Comment by fanyangCS** [comment]
https://github.com/Microsoft/pai/pull/2034

**Comment by YanjieGao** [comment]
@mzmssg for below pls review right or not, this is tell a general customize hadoop related component steps for jianfei

How to customize YARN or hadoop related config:

1 stop yarn [Note: add param -n hadoop-resource-manager / -n hadoop-node-manager ]
https://github.com/Microsoft/pai/blob/master/docs/paictl/paictl-manual.md#stop-services-
2 go to dir customize your config
https://github.com/Microsoft/pai/tree/pai-0.8.y/src/hadoop-resource-manager/deploy/hadoop-resource-manager-configuration
https://github.com/Microsoft/pai/tree/pai-0.8.y/src/hadoop-node-manager/deploy/hadoop-node-manager-configuration
3 start service (nm and rm)
https://github.com/Microsoft/pai/blob/master/docs/paictl/paictl-manual.md#start-services-

**Comment by YanjieGao** [comment]
for quick understand PAI's yarn pls refer: https://github.com/Microsoft/pai/blob/master/docs/hadoop/yarn_service.md

**Comment by scarlett2018** [comment]
Problem fixed in #2034.
