### ISSUE TITLE
关于任务量增加后，HDFS占用磁盘空间的问题

### ISSUE THREAD

**Issue by damon008** [Microsoft/pai#2039]
请问：现在有这样一种现象，新建很简单的任务，当任务量到达2.7w左右时，发现HDFS占用磁盘空间相当大了，导致node-manager部分节点开始宕掉。请问这种情况有好的解决方案吗？

**Comment by mzmssg** [comment]
In the next release, we will support configure an isolated path for HDFS data.

**Comment by damon008** [comment]
好的！
