### ISSUE TITLE
How to mount Azure storage as Job container folder

### ISSUE THREAD

**Issue by YanjieGao** [Microsoft/pai#2046]
### Requirement:
How to mount Azure Blob as Job container folder

### Potential Solution (try as minimal change to current pai as possible):
user could leverage [Azure storage fuse](https://azure.microsoft.com/en-us/blog/linux-fuse-adapter-for-blob-storage/) to solve this.

The new FUSE adapter for Blob Storage. This enables you to mount a blob container on Linux platforms. There is no need to rewrite your application! 

[azure storage fuse git](https://github.com/Azure/azure-storage-fuse)

- advatange to below surveys:
no need to change the pai code & redeployment for existing cluster, the administrator and the user can mount the data in the container of the job close to the space without space limit.

### How to do for PAI user
- 0. install blobfuse
[doc](https://github.com/Azure/azure-storage-fuse/wiki/1.-Installation)
- 1. mount azure blob inner job container
[mounting](https://github.com/Azure/azure-storage-fuse#mounting)
- 2. how to upload data to azure blob & create user's blob container from anywhere
[azure blob: see Develop with blobs part](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction)
[python example](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-python). Note: For this should take care if meet errors: 1. remove use public acl config 2. change blockblobservice to pageblobservice
### How to do for PAI admin
- 1. config azure storage account
[create storage account doc](https://docs.microsoft.com/en-us/azure/storage/common/storage-quickstart-create-account?tabs=azure-portal)
- 2. share account & key to pai users
### Note:
- (1) Azure storage account (for blob usage) quota survey for admin
Didn't see the obvious config to limit the size of each blob
![image](https://user-images.githubusercontent.com/5576848/51521044-5ac40400-1e60-11e9-88a2-f8fa85e1f09c.png)

[azure storage limits](https://github.com/MicrosoftDocs/azure-docs/blob/master/includes/azure-storage-limits.md)

- (2) Azure Blob fuse mount limitations for OpenPAI user
[See limitation parts](https://azure.microsoft.com/en-us/blog/linux-fuse-adapter-for-blob-storage/)
![image](https://user-images.githubusercontent.com/5576848/51520939-0456c580-1e60-11e9-87f4-9c7048b752f1.png)

### Another solutions survey and why not recommend:
- directly mount disk to Azure VM then mount to container disk
expose dockerfile a param, then let user could have the flexibility to mount local host other disks.

 - Azure file share smb between VM
Note: this is used for VM on doc, try in docker meet issues.
doc: https://docs.microsoft.com/en-us/azure/storage/files/storage-how-to-use-files-linux

could have a try
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/mount-azure-file-storage-on-linux-using-smb
 drawback: need docker run --privilege=true 
Or will meet error when mount https://stackoverflow.com/questions/27989751/mount-smb-cifs-share-within-a-docker-container
Other error (i try in dev-box container with previlige): 
mount error(115): Operation now in progress
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
[i try offical doc method change to ver=2.0 & not restrict acl. But not work]
https://docs.microsoft.com/en-us/azure/storage/files/storage-troubleshoot-linux-file-connection-problems#mount-error115-operation-now-in-progress-when-you-mount-azure-files-by-using-smb-30

- [Persistent Docker volumes with Azure File Storage](https://azure.microsoft.com/en-us/blog/persistent-docker-volumes-with-azure-file-storage/)
Need pai to update rest-server code, redeploy, and introduce new configuration items, only suitable for Azure is not a suitable for all platform solutions
Also not clean, need support on host env:
https://github.com/Azure/azurefile-dockervolumedriver#start-volume-driver-daemon

DEPRECATION NOTICE [so not investigate]
Please note this driver is no longer supported and will not be maintained moving forwards. We recommend users use CloudStor for Docker native solutions..
https://github.com/Azure/azurefile-dockervolumedriver
- [HDFS Azure blob driver](https://hadoop.apache.org/docs/current/hadoop-azure/index.html)
Need to redeploy and add dependencies to hdfs, and users still have an HDFS read experience that they don't like.
- Directly read Azure storage from restful or python api:
Most deep learning frameworks are not flexible on the storage interface, most of the assumptions are read from disk.

- Docker for Azure persistent data volumes Cloudstor
https://docs.docker.com/docker-for-azure/persistent-data-volumes/
drawback: it is used for swarm service
- Azure file share for azure container
Note: this is used for azure container not for common container which is pai's job
https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/container-instances/container-instances-volume-azure-files.md

- for aks mount disk
Note: can't directly used, aks make customized config support for k8s
https://docs.microsoft.com/en-us/azure/aks/azure-files-volume

- container-instances-volume-azure-files
not useful as use cmd az container create to create containers
https://docs.microsoft.com/en-us/azure/container-instances/container-instances-volume-azure-files

**Comment by YanjieGao** [comment]
Azure Blob fuse has drawbacks of update file. (It is a little like hdfs mount style disk)
Currently is focus on investigating Azure File smb mount solution

**Comment by scarlett2018** [comment]
How this ticket is related to PAI? @YanjieGao

**Comment by fanyangCS** [comment]
close and track this in #2227.
