### ISSUE TITLE
The job status is confusing, especially when not all the containers are ready.

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#2051]
As below, only the slave:2 was ready.
![image](https://user-images.githubusercontent.com/1547343/51577580-43832600-1ef5-11e9-94e5-b15499c9f250.png)

Now the job is not ready, and user may confused with the status `running`.
If we define the `running` different from user's common sense, user will confuse.

**Comment by scarlett2018** [comment]
As discussed in the team meeting, one quick resolution to this problem is to add a "task status" column, so that user knows the job had started to allocate resources for tasks, and some of the tasks are still waiting for resources.

**Comment by yqwang-ms** [comment]
Solved by #2135
