### ISSUE TITLE
generate OpenPAI configuration failed in dev-box

### ISSUE THREAD

**Issue by squirrelsc** [Microsoft/pai#2061]
when I run below command in latest dev-box.

python paictl.py config generate -i /pai/deployment/quick-start/quick-start/quick-start.yaml -o ~/pai-config -f

get below error:

root@:/pai# python paictl.py config generate -i /pai/deployment/quick-start/quick-start/quick-start.yaml -o ~/pai-config -f
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Traceback (most recent call last):
  File "paictl.py", line 30, in <module>
    from deployment.confStorage.synchronization import synchronization
  File "/pai/deployment/confStorage/synchronization.py", line 22, in <module>
    from external_version_control.storage_factory import get_external_storage
  File "/pai/deployment/confStorage/external_version_control/storage_factory.py", line 26, in <module>
    from .git_storage import git_storage
  File "/pai/deployment/confStorage/external_version_control/git_storage.py", line 19, in <module>
    import git
ImportError: No module named git

**Comment by YanjieGao** [comment]
pls try to pip install git? or apt-get install git?

**Comment by YanjieGao** [comment]
maybe related your currently used dev-box image version which maybe not install this dependency

**Comment by YanjieGao** [comment]
see this https://github.com/Microsoft/pai/blob/997983dad12ede6a624b8b15fc043a5b1f59e3b0/src/dev-box/build/dev-box.dockerfile#L46

**Comment by YanjieGao** [comment]
please attach your pai and dev-box version

**Comment by squirrelsc** [comment]
have a try, it should be below one:
python -m pip install gitpython

**Comment by hao1939** [comment]
Hi @squirrelsc,

The `latest` dev-box was out of date, we are not maintaining.
Please use the latest release version, it should be fine.

**Comment by squirrelsc** [comment]
If so, the document should be fixed, there is no tag specified.

https://github.com/Microsoft/pai/blob/pai-0.8.y/docs/pai-management/doc/cluster-bootup.md#customizeddeploy


# Pull the dev-box image from Docker Hub
sudo docker pull docker.io/openpai/dev-box

**Comment by hao1939** [comment]
We have put more document about the dev-box, close it now.
