### ISSUE TITLE
As a user, I need to know the available GPU's type (sku) so that I can decide whether the available GPU are fit for my training.

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#2062]
Had got this request from sys group folk when using DLTS cluster this morning, before submitting his jobs, he want to know what's the current available GPU types. i.e. V100, P40, or others. Depending on the GPU type, he knows what's the GPU memory and disk, etc. There are chances that only V100 can support his job.

**Comment by fanyangCS** [comment]
https://github.com/Microsoft/pai/issues/445
