### ISSUE TITLE
自动检测然后分配足够的内存

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#2067]
华南理工在使用过程中提出的建议：
**现状：**提交作业时需要指定内存大小
**难点：**不同的代码跑起来不能完全确定内存的需求，希望OpenPAI可以有个自适应的管理方式，由OpenPAI自动检测然后分配足够的内存。

**Comment by ICEORY** [comment]
在实际的使用过程中，用openpai分配内存会导致因为内存不足而申请不了GPU。但实际上，我们并不会用到所申请的全部内存；我觉得目前快速的一个解决方案是：去掉 `/src/rest-server/src/templates/yarnContainerScript.mustache` 中对内存的限制，然后所有docker共享主机的内存；这样子实测不会影响任务，并能够解决内存不足的问题，但不清楚会不会对整个平台有不良的影响～

**Comment by fanyangCS** [comment]
figure out the right amount of resource for each job and optimize the resource allocation among jobs is a multi-dimension bin packing problem (NP hard). We do not recommend to go along this direction.  Right now, the cluster divides all the resources into a fix amount of "slice", a job can choose the right amount of slices to fit its need. This is what most of the cluster scheduler does.
