### ISSUE TITLE
To enable SSH info, docker image need include ssh service

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#2071]
**What happened**
The user followed the document https://github.com/Microsoft/pai/blob/master/docs/job_tutorial.md , I try to debug my program via SSH.
Firstly I submit a dummy job and keep it running. But the API returns 404 not found error. 

**Fan's suggestion**
> Please make sure you have included the ssh service in your docker. Otherwise it will be disabled.
> https://github.com/Microsoft/pai/blob/pai-0.8.y/src/rest-server/src/templates/dockerContainerScript.mustache#L142
> 

**Ask**
May we update the job_tutorial or docker image guide?

**Comment by squirrelsc** [comment]
It looks docker image needs openssh-server and curl, and it's better to update document.

**Comment by fanyangCS** [comment]
will overhaul ssh support in pure k8s version.
