### ISSUE TITLE
webportal: need to show the node name or IP address of each job

### ISSUE THREAD

**Issue by ICEORY** [Microsoft/pai#2074]
When we need to remove some nodes from the cluster, we need to find all the jobs that use these nodes and inform the users to stop their jobs (or backup the experiments). I think the best way is to filter the jobs by node name or IP address, instead of clicking each job and checking the IP address. So, it is recommended to add the node name or IP address to the job list. Thanks~

**Comment by scarlett2018** [comment]
@ICEORY - this is a great scenario and very useful for users, would you like to implement it and contribute to PAI? thanks.

PAI PM,
Scarlett

**Comment by scarlett2018** [comment]
@ICEORY - we had a quick implementation for this requirement in the coming release 0.11.0, will provide more information in the release node. stay tuned.
