### ISSUE TITLE
doc link broken

### ISSUE THREAD

**Issue by scarlett2018** [Microsoft/pai#2079]
https://github.com/Microsoft/pai/blob/master/docs/job_tutorial.md#quickstart has broken link
https://github.com/Microsoft/pai/blob/master/pai-management/doc/hdfs.md#WebHDFS

**Comment by YanjieGao** [comment]
master branch use relative link, not contains this issue
![image](https://user-images.githubusercontent.com/5576848/51733451-4da35100-20bc-11e9-948b-952924416251.png)
