### ISSUE TITLE
paictl.py service: can't start service after stop, need to try 'stop then start' for several times

### ISSUE THREAD

**Issue by hao1939** [microsoft/pai#2081]
How to reproduce:

1. Stop a PAI service using: paictl.py service stop -n service_name
2. Start the PAI service using: paictl.py service start -n service_name

It won't work the first time. Take pylon/resource-manager for example, the daemon-set would up, but the pod won't be created.

**Comment by ydye** [comment]
This should be a problem of kubectl or k8s, please provide more message.

**Comment by fanyangCS** [comment]
closed as no further complaints.
