### ISSUE TITLE
binding user account with email

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#2085]
Currently, user account can not contain "-" and "@", user does not have email address info.

To maintain users email, I have to maintain a table to keep the alias. And some users who start with "v-" cannot have the same user account as their alias.

**Comment by fanyangCS** [comment]
@yqwang-ms , can we allow "-" and "@" in the user name?

**Comment by yqwang-ms** [comment]
@ is not allowed, because it is reserved in URI, see https://tools.ietf.org/html/rfc3986#section-2.3
- is already allowed in YARN Launcher. 
(For K8S Launcher it is not allowed, because it is already used to sperator in PodName, etc)

**Comment by yqwang-ms** [comment]
For what we allowed, please check:
https://github.com/Microsoft/pai/blob/master/subprojects/frameworklauncher/yarn/doc/USERMANUAL.md#assumption

**Comment by fanyangCS** [comment]
can we rewrite "@" in the user name to "#"when using it in a uri way?

**Comment by yqwang-ms** [comment]
# is also not allowed in URI, URI only allows below, may be we need another one.
ALPHA / DIGIT / "-" / "." / "_" / "~"

For k8s launcher, I keep align with Statefulset who uses -, it is more complex thing we can disscus later give k8s has more strong naming convention on object name, label name, env name.

**Comment by Gerhut** [comment]
If it just an URI issue, we could encode them.

**Comment by yqwang-ms** [comment]
Agree :+1:

**Comment by fanyangCS** [comment]
@Gerhut and @yqwang-ms , with the support of AAD, we should be able to support "-" in user name. This is a must-have now.

**Comment by yqwang-ms** [comment]
"-" or "." is already allowed in YARN Launcher. 
https://github.com/Microsoft/pai/blob/master/subprojects/frameworklauncher/yarn/doc/USERMANUAL.md#assumption

**Comment by scarlett2018** [comment]
> "-" or "." is already allowed in YARN Launcher.
> https://github.com/Microsoft/pai/blob/master/subprojects/frameworklauncher/yarn/doc/USERMANUAL.md#assumption

@yqwang-ms - what else is needed besides YARN Launcher supports?

**Comment by yqwang-ms** [comment]
I am not sure, @Gerhut may know the details.

**Comment by fanyangCS** [comment]
rest server has some constraint. @Gerhut and @wangcan0329 have more information.

**Comment by scarlett2018** [comment]
cc @xiaowuhu for reference.

**Comment by sterowang** [comment]
It seemed the full email address as user name should be supported when we enable Open ID login. From here https://en.wikipedia.org/wiki/Email_address#Local-part we can see a more versatile email address format, so I think our rules might need to be updated.

**Comment by scarlett2018** [comment]
> It seemed the full email address as user name should be supported when we enable Open ID login. From here https://en.wikipedia.org/wiki/Email_address#Local-part we can see a more versatile email address format, so I think our rules might need to be updated.

Thanks @sterowang , seems need to mark this one as higher priority to unblock Open ID login.
