### ISSUE TITLE
DNS解析错误

### ISSUE THREAD

**Issue by JianfeiHu** [Microsoft/pai#2092]
直接使用ip:80访问系统，每个任务的" Go to Application Tracking Page "点击后都报500错误，
使用ip:9286访问系统，查看" Go to Application Tracking Page "正常。

**Comment by ydye** [comment]
Known issue. Will Fix in 0.9 https://github.com/Microsoft/pai/commit/744f40905336b2978fb9a847e2a4c3137e0dcdb2#diff-c93412ef415e2735572fbcff13733320
