### ISSUE TITLE
Expose Tensorboard URL in Job detailed Page

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#2095]
Currently, we only have a plain text for the tensorboard port, it is not convenience to use directly.

**Open issue**: 
- though port is assigned, PAI does not know whether user is using http or https.
- how to make sure the tensorboard is able to start and launch correctly.
- which root folder the tensorboard is reading.

**Impact Component**
- might need to add a protocol in launcher together with port.

![image](https://user-images.githubusercontent.com/39592018/54983632-32838d80-4fe8-11e9-9b03-ea6fbf74ad10.png)

**Comment by fanyangCS** [comment]
close and track in #3156 .
