### ISSUE TITLE
Job is "running" while GangAllocation cannot satisfied in time for several times.

### ISSUE THREAD

**Issue by scarlett2018** [Microsoft/pai#2099]
![image](https://user-images.githubusercontent.com/39592018/51904364-70ee3900-23f9-11e9-8d53-bedf41f1624c.png)

![image](https://user-images.githubusercontent.com/39592018/51904377-78addd80-23f9-11e9-8df3-e0da4c473540.png)

**Comment by yqwang-ms** [comment]
Solved by #2135
