### ISSUE TITLE
使用自签名证书的Private Registry的问题

### ISSUE THREAD

**Issue by hellocandy** [Microsoft/pai#2101]
使用Private Registry的情景，我们有两套系统，其中有一套使用的是购买的SSL证书，另一套是使用的自签的SSL证书。在使用购买的SSL的系统中，使用PrivateRegistry可以派发job成功。而使用自签证书的系统会失败，出错信息：Error response from daemon: Get https://124.9.14.15/v2/: x509: cannot validate certificate for 124.9.14.15 because it doesn't contain any IP SANs。

**Comment by scarlett2018** [comment]
@hellocandy - I'm closing this issue as it is not actually a OpenPAI issue, but a Docker Repository setting up question. You are encourage to inquiry this question in Docker's Community, or discuss with PAI users in PAI Gitter Chat Room: https://gitter.im/Microsoft/pai.

**Comment by hellocandy** [comment]
目前我们在docker里设置了证书。
然后最新的进展是Pylon组件无法启动。
