### ISSUE TITLE
怎样升级openPAI

### ISSUE THREAD

**Issue by hellocandy** [Microsoft/pai#2109]
我们之前有安装0.8.0版本的openPAI，现在最新的release版本是0.8.3。
我们想升级为0.8.3的版本，如果不采用重新安装的方式，怎样可以实现升级。

**Comment by fanyangCS** [comment]
There is a section “Upgrading from Earlier Release” in our release note. Please let us know if you have further questions.

**Comment by scarlett2018** [comment]
@hellocandy - 
Try this out --> https://github.com/Microsoft/pai/blob/5185b033ccaf9233005d702ef8a4dbf9c8138378/release-notes.md#upgrading-from-earlier-release 

I'm closing the ticket as help had been provided, please feel free to reopen or submit new issue if you meet any problem with that instruction.
