### ISSUE TITLE
[feature request] on-premise k8s component refresh config 

### ISSUE THREAD

**Issue by YanjieGao** [microsoft/pai#2110]
current PAI service support stop / start service to support config refresh.

Need  k8s component refresh feature.

Scenarios:
if k8s LB ip changed. no auto or scripts to batch update config of k8s components

**Comment by fanyangCS** [comment]
I suggest to leverage k8s itself to do that. We need to decouple k8s from OpenPAI .

**Comment by scarlett2018** [comment]
@YanjieGao - who raised this request?

**Comment by YanjieGao** [comment]
once work for app-gate way find lack this feature to batch refresh k8s. bin and fan suggest to log this at issue.

**Comment by fanyangCS** [comment]
not supported.
