### ISSUE TITLE
Broken link in doc home page

### ISSUE THREAD

**Issue by scarlett2018** [Microsoft/pai#2113]
Submit job from VS code page is 404, and need to be updated with the new extension.

![image](https://user-images.githubusercontent.com/39592018/52046993-0bc64f00-2583-11e9-80f8-1ca3267cf2b8.png)

when click on this link, it got a 404. 
https://github.com/Microsoft/vscode-tools-for-ai/blob/master/docs/quickstart-05-pai.md

![image](https://user-images.githubusercontent.com/39592018/52047024-1ed91f00-2583-11e9-8deb-6c810d9a5f67.png)

**Comment by abuccts** [comment]
Already fixed in #2114.
