### ISSUE TITLE
Need to know all the jobs in a Node

### ISSUE THREAD

**Issue by scarlett2018** [Microsoft/pai#2128]
One useful scenario is: Before Node upgrade/migration/deletion, admin need to know all the jobs in the corresponding node. there are more other scenarios.

**Comment by fanyangCS** [comment]
close and track in #349

**Comment by scarlett2018** [comment]
@fanyangCS - I'm reopening the issue as it is a display and query ask for Node<>job list, not just for decommission. I rephrased the job accordingly.

**Comment by xudifsd** [comment]
related PR #2197

**Comment by xudifsd** [comment]
#2197 merged. But seems user want something like, jobs with low resource util are marked with red:

![image](https://user-images.githubusercontent.com/665253/53540717-a0f03f80-3b51-11e9-8682-5cc1d54dbe7e.png)

We can add extra column to following page:

![image](https://user-images.githubusercontent.com/665253/53540762-c41aef00-3b51-11e9-9881-82b22d0204ea.png)

Also user want ordinary user could see the page instead of admin.

Should we discuss this? @scarlett2018 and @fanyangCS @Gerhut @Anbang-Hu

**Comment by scarlett2018** [comment]
@xudifsd - Agree the services page seems the most fit place for this request for now.

**Comment by xudifsd** [comment]
Webportal can query prometheus using query `task_gpu_percent` to get node, job mapping and display correctly in the page, the result of query should be like `task_gpu_percent{container_env_PAI_TASK_INDEX="0",container_label_PAI_CURRENT_TASK_ROLE_NAME="worker",container_label_PAI_HOSTNAME="paigcr-a-gpu-1104",container_label_PAI_JOB_NAME="admin~dixu-gpu-test",container_label_PAI_USER_NAME="admin",instance="10.151.40.4:9102",job="pai_serivce_exporter",minor_number="0",pai_service_name="job-exporter",scraped_from="job-exporter-wxhc4"}`, `instance` is where this job exist, and other labels can be extracted to make up job name.

For low resource usage, Webportal can query using `task_gpu_percent < 50` and `task_gpu_mem_percent < 50` to get low resource util of job, assume we only care gpu, and threshold for low is 50%.

**Comment by scarlett2018** [comment]
> #2197 merged. But seems user want something like, jobs with low resource util are marked with red:
> 
> ![image](https://user-images.githubusercontent.com/665253/53540717-a0f03f80-3b51-11e9-8682-5cc1d54dbe7e.png)
> 
> We can add extra column to following page:
> 
> ![image](https://user-images.githubusercontent.com/665253/53540762-c41aef00-3b51-11e9-9881-82b22d0204ea.png)
> 
> Also user want ordinary user could see the page instead of admin.
> 
> Should we discuss this? @scarlett2018 and @fanyangCS @Gerhut @Anbang-Hu

Created an issue for this ask in #2250

**Comment by xudifsd** [comment]
close this and discuss in #2250
