### ISSUE TITLE
Review and Refine documentation

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#2130]
During the operation on the MS deployments, we found some of the documentation are still hard to be consumed by first time users. This issue is to review and refine current doc for admin/user/ops jump start.

Merge #2000 here.

**Comment by sotetsuk** [comment]
Link to "Submit a job in Visual Studio Code" in README.md is expired: 

![image](https://user-images.githubusercontent.com/5868442/52616246-d4389a80-2ed2-11e9-90d9-5b5268cc38c2.png)

https://github.com/Microsoft/vscode-tools-for-ai/blob/master/docs/quickstart-05-pai.md

![image](https://user-images.githubusercontent.com/5868442/52616279-f92d0d80-2ed2-11e9-9a3d-28e725464d20.png)

**Comment by squirrelsc** [comment]
> Link to "Submit a job in Visual Studio Code" in README.md is expired:
> 
> https://github.com/Microsoft/vscode-tools-for-ai/blob/master/docs/quickstart-05-pai.md

Thanks for reporting, we will fix it in next releases. For VS code extension, please refer to below page.
https://github.com/Microsoft/pai/tree/master/contrib/pai_vscode

**Comment by fanyangCS** [comment]
related issues. 
https://github.com/Microsoft/pai/issues/1938
https://github.com/Microsoft/pai/issues/1794

**Comment by scarlett2018** [comment]
@squirrelsc - I had changed this issue into an Epic, you can splits it into sub items that can fit your pace.

**Comment by fanyangCS** [comment]
closed and tracked in #4023.
