### ISSUE TITLE
Restart docker daemon without stopping containers

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#2140]
We will need to restart docker daemon while upgrade, want to keep job running.

**Comment by fanyangCS** [comment]
https://docs.docker.com/config/containers/live-restore/

**Comment by ydye** [comment]
@fanyangCS https://zhuanlan.zhihu.com/p/35894853
Please aware the scenario which the option is designed for.

**Comment by fanyangCS** [comment]
this seems to be risky. Let's put it on hold.
