### ISSUE TITLE
Virtual Cluster with empty space can be created but can not be used

### ISSUE THREAD

**Issue by scarlett2018** [Microsoft/pai#2169]
**Organization Name**: PAI PROD-1

**How to reproduce it**: 
- Created a VC named "A B" in web UI, the VC has been created successfully
- Add a user to this VC in User "Edit Info" page, it failed.
![image](https://user-images.githubusercontent.com/39592018/53071674-d2e41f00-351d-11e9-9635-cff0043d19fa.png)

**OpenPAI Environment**:
- OpenPAI version: 0.9.0

**Comment by mzmssg** [comment]
Fixed in #2180
