### ISSUE TITLE
Unable to locate package nvidia-container-runtime when running python paictl.py cluster k8s-bootup

### ISSUE THREAD

**Issue by squirrelsc** [Microsoft/pai#2181]
**Organization Name**: int

**Short summary about the issue/question**:

**Brief what process you are following**: 

**How to reproduce it**: 

**OpenPAI Environment**:
- OpenPAI version: 0.9.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Ubuntu 1804
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

2019-02-20 21:56:40,089 [INFO] - deployment.k8sPaiLibrary.maintainlib.common : Executing the command on host [IP is removed]: sudo ./master-deployment/docker-ce-install.sh master-deployment
Omid-B99/4863
python has been installed. And skip python install.
docker has been installed. And skip docker install.
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package nvidia-container-runtime

**Comment by xudifsd** [comment]
related to #1437 , should add the repo as [nvidia said](https://nvidia.github.io/nvidia-container-runtime/)

**Comment by 111Moderato** [comment]
![image](https://user-images.githubusercontent.com/28188655/53225622-a2ce8480-36b3-11e9-941d-60076564e3f4.png)
I've already done this setup. Why is this still a problem?
![image](https://user-images.githubusercontent.com/28188655/53225670-c2fe4380-36b3-11e9-824d-3c930bbd965f.png)

**Comment by 111Moderato** [comment]
> related to #1437 , should add the repo as [nvidia said](https://nvidia.github.io/nvidia-container-runtime/)

请问nvidia-container-runtime是否不支持Ubuntu16.04？
