### ISSUE TITLE
Need alarms for unhealthy GPU cases

### ISSUE THREAD

**Issue by mzmssg** [Microsoft/pai#2192]
**Organization Name**:  Microsoft

**Short summary about the issue/question**:

There are some GPU exceptions PAI can't perfectly handle. For these case, as the first phase, we will alert and introunce manual operations.
1. job-exporter collect gpu status
2. alert admin
3. admin manually decommission nodes.

Currently, we summarized some unhealthy cases, including:
* Nvidia-smi hangs
   1.	In kernal mode
        Detection: Filter processes list of command 'nvidia-smi' and status 'D', to reduce false positive alarms, we could add a timeout: 
* Nvidia-smi works
   1. GPU memory leak
   Detection: Call nvidia-smi to get memory-utilized GPUs and processes running GPUs,
Subtraction results is the memory leak GPU.
  2. GPU used by external processes
  Detection: Call nvidia-smi, get running processes, then get their cgroup in /proc/$pid/cgroup, check whether it’s under job container
  3. GPU used by zombie container
  Detection: Based on 2, further check whether corresponding yarn container survives.
  4. GPU ECC error
  Detection: Call nvidia-smi to get ecc error code.

**OpenPAI Environment**:
- OpenPAI version: master

**Anything else we need to know**:

Alarms and manual operations are the first step. 
As the next step, PAI itself should tolerate such cases.

**Comment by mzmssg** [comment]
If I omit some cases, please help to add

**Comment by xudifsd** [comment]
@mzmssg how to get their cgroup in `/proc/$pid/cgroup`? The content of it looks like:
```
12:rdma:/
11:hugetlb:/docker/74ce4b73b4a46b937129ca40ab4bb131105a1e14a12b8839cf05a04cc4e90b3c
10:pids:/docker/74ce4b73b4a46b937129ca40ab4bb131105a1e14a12b8839cf05a04cc4e90b3c
9:memory:/docker/74ce4b73b4a46b937129ca40ab4bb131105a1e14a12b8839cf05a04cc4e90b3c
8:cpuset:/docker/74ce4b73b4a46b937129ca40ab4bb131105a1e14a12b8839cf05a04cc4e90b3c
7:devices:/docker/74ce4b73b4a46b937129ca40ab4bb131105a1e14a12b8839cf05a04cc4e90b3c
6:perf_event:/docker/74ce4b73b4a46b937129ca40ab4bb131105a1e14a12b8839cf05a04cc4e90b3c
5:blkio:/docker/74ce4b73b4a46b937129ca40ab4bb131105a1e14a12b8839cf05a04cc4e90b3c
4:net_cls,net_prio:/docker/74ce4b73b4a46b937129ca40ab4bb131105a1e14a12b8839cf05a04cc4e90b3c
3:freezer:/docker/74ce4b73b4a46b937129ca40ab4bb131105a1e14a12b8839cf05a04cc4e90b3c
2:cpu,cpuacct:/docker/74ce4b73b4a46b937129ca40ab4bb131105a1e14a12b8839cf05a04cc4e90b3c
1:name=systemd:/docker/74ce4b73b4a46b937129ca40ab4bb131105a1e14a12b8839cf05a04cc4e90b3c
```

How to get ecc error code?

What to do with these situation? Fire an alert?

**Comment by xudifsd** [comment]
job-exporter call `nvidia-smi` with timeout 3 second, I have checked 95th latency for calling nvidia-smi is from 0.5~1,2 second, so we could enlarge the timeout to be 5 second, and trigger alert on 3 second.

**Comment by mzmssg** [comment]
@xudifsd 
Yes, in this case, this process belong to a docker container of ID `74ce4b73b4a46b937129ca40ab4bb131105a1e14a12b8839cf05a04cc4e90b3c`.

For ecc error, a response of nvidia-smi as follows, ECC error code is the right-top number in every GPU, it could be a number, `N/A` or `Off`. A number greater than 0 means abnormal.
```
   +-----------------------------------------------------------------------------+
   | NVIDIA-SMI 384.111                Driver Version: 384.111                   |
   |-------------------------------+----------------------+----------------------+
   | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
   | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
   |===============================+======================+======================|
   |   0  Tesla K80           Off  | 00006B24:00:00.0 Off |                    0 |
   | N/A   26C    P8    34W / 149W |   3322MiB / 11439MiB |      0%      Default |
   +-------------------------------+----------------------+----------------------+
```

**Comment by xudifsd** [comment]
@mzaman1 job-exporter reads output of `nvidia-smi -q -x`, which has following output related to ECC:

```
                <ecc_mode>
                        <current_ecc>Enabled</current_ecc>
                        <pending_ecc>Enabled</pending_ecc>
                </ecc_mode>
                <ecc_errors>
                        <volatile>
                                <single_bit>
                                        <device_memory>0</device_memory>
                                        <register_file>0</register_file>
                                        <l1_cache>0</l1_cache>
                                        <l2_cache>0</l2_cache>
                                        <texture_memory>0</texture_memory>
                                        <texture_shm>N/A</texture_shm>
                                        <cbu>N/A</cbu>
                                        <total>0</total>
                                </single_bit>
                                <double_bit>
                                        <device_memory>0</device_memory>
                                        <register_file>0</register_file>
                                        <l1_cache>0</l1_cache>
                                        <l2_cache>0</l2_cache>
                                        <texture_memory>0</texture_memory>
                                        <texture_shm>N/A</texture_shm>
                                        <cbu>N/A</cbu>
                                        <total>0</total>
                                </double_bit>
                        </volatile>
                        <aggregate>
                                <single_bit>
                                        <device_memory>0</device_memory>
                                        <register_file>0</register_file>
                                        <l1_cache>0</l1_cache>
                                        <l2_cache>0</l2_cache>
                                        <texture_memory>0</texture_memory>
                                        <texture_shm>N/A</texture_shm>
                                        <cbu>N/A</cbu>
                                        <total>0</total>
                                </single_bit>
                                <double_bit>
                                        <device_memory>9</device_memory>
                                        <register_file>0</register_file>
                                        <l1_cache>0</l1_cache>
                                        <l2_cache>0</l2_cache>
                                        <texture_memory>0</texture_memory>
                                        <texture_shm>N/A</texture_shm>
                                        <cbu>N/A</cbu>
                                        <total>9</total>
                                </double_bit>
                        </aggregate>
                </ecc_errors>
```

Maybe I should use `ecc_errors.volatile.single_bit.total` and `ecc_errors.volatile.double_bit.total`?

**Comment by mzmssg** [comment]
@xudifsd 
Seems yes.

**Comment by fanyangCS** [comment]
> job-exporter call nvidia-smi with timeout 3 second, I have checked 95th latency for calling nvidia-smi is from 0.5~1,2 second, so we could enlarge the timeout to be 5 second, and trigger alert on 3 second.

@xudifsd , how long have you test the calling latency to get 0.5~2s 95th latency? can you log the timeout? I suggest to set the timeout to be 10s. Based on our experience, sometimes it could be as much as 60s.

**Comment by xudifsd** [comment]
@fanyangCS for about two weeks, you can see latency from [prod bed](http://10.151.40.179:9091/prometheus/graph?g0.range_input=30m&g0.expr=histogram_quantile(0.95%2C%20sum(rate(cmd_nvidia_smi_latency_seconds_bucket%5B300s%5D))%20by%20(le%2C%20instance))&g0.tab=0). The timeout set in prod bed is 3 second now, so the latency line should all below 3 second. From the graph, it seems no nvidia call has been interrupted by timeout.

I'm fine with setting timeout to be 10s, and maybe set alert on 5s? We may need more cases of nvidia hangs, so better setting lower alert threshold?

**Comment by xudifsd** [comment]
@mzmssg do we need to alert on ecc error? From the [manual](https://developer.download.nvidia.com/compute/DCGM/docs/nvidia-smi-367.38.pdf)

> Single bit ECC errors are automatically corrected by the HW and do not result in data corruption. Double bit errors are detected but not corrected.

Maybe just alert for double error?

**Comment by xudifsd** [comment]
Memory leak should larger than 20M to be troublesome.

**Comment by fanyangCS** [comment]
related issue: https://github.com/Microsoft/pai/issues/2146

**Comment by mzmssg** [comment]
test case checkbox:

- [x] GPU used by zombie container
- [x] GPU used by external process
- [ ] GPU ECC error
- [ ] GPU memory leak
- [ ] nvidia-smi hanging

3~5 is hard to simulate

**Comment by xudifsd** [comment]
maybe should close this issue since the PR has been merged

**Comment by mzmssg** [comment]
Closed
