### ISSUE TITLE
关于NVIDIA驱动问题

### ISSUE THREAD

**Issue by 111Moderato** [Microsoft/pai#2198]
我手动安装了NVIDIA驱动，也就是sudo ./NVIDIA_....390.25.run --no-opengl-files，我是不是必须得卸载它以后才能正常运行drivers-one-shot？

假如我卸载了手动安装的驱动，并且按照PAI中的脚本进行了驱动安装，以后该如何干净的卸载它呢？

本来想修改driver-path的路径试试看，但是我找不到我手动安装的驱动地址。

**Comment by ydye** [comment]
@xudifsd

**Comment by xudifsd** [comment]
@111Moderato nvidia 应该有 drivers 的卸载脚本。使用那个脚本卸载应该即可。你不一定需要卸载才能正常运行。你可以修改你的 services-configuration.yaml 在 drivers 条目下加 一个 `pre-installed-nvidia-path` ，value 为你事先安装好的绝对路径即可，一般这个路径是 `/usr/local/nvidia`。

你也可以在机器上执行 `which nvidia-smi` 来检查路径是什么，需要注意的是，这个路径是不包括 bin 这个目录的，也就是说，如果你的 `which nvidia-smi` 返回的是 /usr/local/nvidia/bin/nvidia-smi，那么你应该填写的是 /usr/local/nvidia。

**Comment by 111Moderato** [comment]
但是我运行which nvidia-smi之后得到的是：
![image](https://user-images.githubusercontent.com/28188655/53309895-510d4080-38e5-11e9-899d-9dabc4ef1c8f.png)
/usr里面没有一个单独的nvidia文件夹 @xudifsd

**Comment by 111Moderato** [comment]
然后，假如我跳过driver这个部分部署其他的，这个hadoop-node-manager会报资源不足的错误：
![image](https://user-images.githubusercontent.com/28188655/53310013-fb856380-38e5-11e9-989c-2011311baf74.png)
![image](https://user-images.githubusercontent.com/28188655/53310003-f0323800-38e5-11e9-8bd2-b94122004507.png)

在文档中我看到要求的是4g就够了？

![image](https://user-images.githubusercontent.com/28188655/53310068-325b7980-38e6-11e9-9209-f57de0111fd9.png)

**Comment by xudifsd** [comment]
@111Moderato 那你执行 `find / -type f | grep libnvidia` 看看

**Comment by xudifsd** [comment]
关于资源限制，你可以配置 `services-configuration.yaml` 的 cluster.common 下的 qos-switch: false 来禁用，这样你应该就能启动。不过 4G 是在是有点小，跑这么多的服务再加 job 可能会撑不住。

**Comment by 111Moderato** [comment]
1. find / -type f | grep libnvidia输出很多内容诶：
[find.txt](https://github.com/Microsoft/pai/files/2898766/find.txt)
2. 我是在kubernetes-configuration.yaml中设置了qos-switch: false，在`services-configuration.yaml` 的 cluster.common 下是需要自己添加这一行吗？对于这个内存上限只能单独给定吗？是否可以设置一个总额，让内部自行分配？

**Comment by xudifsd** [comment]
@111Moderato 你试试 https://askubuntu.com/a/220734 这个？
2. 不是在 kubernetes-configuration.yaml，是在 services-configuration.yaml，是需要自己添加。他是通过每个服务请求一定资源量实现的，比如 https://github.com/Microsoft/pai/blob/pai-0.9.y/src/hadoop-resource-manager/deploy/hadoop-resource-manager.yaml.template#L79

**Comment by 111Moderato** [comment]
@xudifsd emm..我纠结的是运行PAI部署的脚本后自动安装的驱动我该怎么卸载？

**Comment by 111Moderato** [comment]
增加了qos-switch: false设置之后，资源还是不足，我的电脑memory只有31.4G，我是否可以配置一台没有GPU的机子来调用另一台主机的GPU资源，也就是Distributed deploy中的Option A. Start Dev-box contianer as the environemnt.？

**Comment by xudifsd** [comment]
@111Moderato 可以，你可以设置 cpu 机器为 pai-master，gpu 机器为 pai-worker 即可

**Comment by 111Moderato** [comment]
@xudifsd 我还是继续尝试单机部署，然后把主机本身的显卡驱动卸载了，运行PAI的部署代码，但是一直没成功：
![image](https://user-images.githubusercontent.com/28188655/53388096-dddafb80-39c4-11e9-9d74-8ddb41fe07a9.png)

运行sudo docker logs kubelet得到的日志信息在附件中：
[ku.txt](https://github.com/Microsoft/pai/files/2903732/ku.txt)

**Comment by scarlett2018** [comment]
@111Moderato - thanks for reporting the issue, in the new 2019 year, we will start a set of community communication program for PAI users. Would you mind to share which organization (EDU or Company) you are presenting)? and what's the best way to reach your team, thanks.

**Comment by xudifsd** [comment]
@111Moderato 能给下 drivers-one-shot 的 log 么？

**Comment by 111Moderato** [comment]
@xudifsd 在K8S的dashboard里打开drivers-one-shot日志，显示该容器没有日志，我现在在将390.25改为默认的384.111，所以显示的是：
`Error from server (BadRequest): container "nvidia-drivers" in pod "drivers-one-shot-8h5ds" is waiting to start: ContainerCreating`
我昨天其实进行部署后，在日志里是看到了nvidia-smi的信息的，但是后来我想用sudo docker exec -it ××× /bin/bash进入这个容器却连不上，stop服务后重新部署就出错了
另外，把主机的NVIDIA驱动卸载后分辨率就不正常了，如果PAI这一步部署成功了，还能额外在主机安装驱动吗？

**Comment by xudifsd** [comment]
你在机器上看下 /var/drivers/nvidia/ 下面的内容，并运行下 /var/drivers/nvidia/current/bin/nvidia-smi 看看怎么样，如果能运行说明驱动安装成功了。

估计不能再装驱动了，没法装两个 gpu 驱动的

**Comment by 111Moderato** [comment]
还是不行，用默认的384.111也无法部署，查看drivers-one-shot的日志，直接就是空的，因为根本就没创建成功吧？在想是不是镜像拉取不完全？镜像储存在哪里呢？从size来看又好像下好了？
![image](https://user-images.githubusercontent.com/28188655/53409536-1ba74680-39fc-11e9-83ae-83b5b3c1836a.png)

**Comment by scarlett2018** [comment]
@111Moderato - 感谢您报告此问题，在新的2019年，我们将为PAI用户启动一套社区沟通计划。 您是否愿意分享您所介绍的组织（EDU或公司）？ 什么是联系你的团队的最佳方式，谢谢。

**Comment by xudifsd** [comment]
@111Moderato 看上去是下好了，镜像存在 docker.io 上。你可以通过 kubectl describe pod -l app=drivers-one-shot 看具体是为什么

**Comment by 111Moderato** [comment]
@xudifsd 暂时还是没有解决，请问是否可以应用nvidia-docker来解决驱动问题？

**Comment by 111Moderato** [comment]
@scarlett2018 非常感谢你们的项目，很抱歉不能分享更多公司信息

**Comment by fanyangCS** [comment]
Which OS are you using? We support on Ubuntu 16.04.

**Comment by scarlett2018** [comment]
@111Moderato - 公司信息在未经同意下不会对外公布，如果方便请发私信给我scarli@Microsoft.com做为我们产品经理的用户信息参考，再次感谢。

**Comment by 111Moderato** [comment]
@fanyangCS @xudifsd 之前使用的也是16.04，昨天再次用新的系统环境部署后，运行
`/var/drivers/nvidia/current/bin/nvidia-smi`是可以输出驱动信息的
![image](https://user-images.githubusercontent.com/28188655/53610210-0e10dd00-3c05-11e9-904d-2f44ba61a534.png)
但是，按照你们提供的验证步骤，却无法正确输出nvidia-smi的信息：
![image](https://user-images.githubusercontent.com/28188655/53610223-208b1680-3c05-11e9-8bed-dbe01bcaba72.png)
![image](https://user-images.githubusercontent.com/28188655/53610237-2aad1500-3c05-11e9-9dce-b35ade4264d1.png)
这种情况算是成功了吗？PAI的web界面也没有显示GPU的存在：
![image](https://user-images.githubusercontent.com/28188655/53610271-431d2f80-3c05-11e9-8469-16a0182777b5.png)
日志：
[logs-from-nvidia-drivers-in-drivers-one-shot-cs5x2.txt](https://github.com/Microsoft/pai/files/2917575/logs-from-nvidia-drivers-in-drivers-one-shot-cs5x2.txt)

**Comment by xudifsd** [comment]
@111Moderato 你用绝对路径能成功么？这个为 0 是因为 yarn 没探测到 gpu，你看看 hadoop-resource-manger 和 hadoop-node-manager 的日志

**Comment by 111Moderato** [comment]
是进入容器后用绝对路径？

**Comment by xudifsd** [comment]
不是，在机器上

**Comment by 111Moderato** [comment]
@xudifsd 之前是可以的，但是我刚刚试图调用里面的nvidia-xconfig改变图形界面的分辨率，导致循环登录后，就将服务停掉，在机器上重新装了驱动再卸载，然后重新启动服务，现在用绝对路径调用就出现

> NVIDIA-SMI couldn't find libnvidia-ml.so library in your system. Please make sure that the NVIDIA Display Driver is properly installed and present in your system.
> Please also try adding directory that contains libnvidia-ml.so to your system PATH.

在drivers-one-shot日志里倒是能看到nvidia-smi的信息

**Comment by 111Moderato** [comment]
@ydye @xudifsd 
很感谢你们的耐心解答，以下是我当前的部署进展：
1.最后还是进行了双节点部署，相比资源紧张的单节点顺利很多。但是我得在drivers的容器内设置环境变量才能正常显示nvidia-smi的信息，不知是否正常。
2.还有一个疑问：如果有多台服务器，每台服务中假设是4块GPU，对于某个task是否可以跨服务器使用GPU？也就是假如0号服务器剩1块，1号服务器剩1块，我是否可以在单个任务中同时调用这两块GPU？因为看了这个issue：https://github.com/Microsoft/pai/issues/1832，疑惑是否只能在单个任务（或者说容器）中使用同一台服务器的多个GPU。
3.同样地，对于memory，是不是也只能在同一台服务器内共享资源？如果分别有部分剩余，是否能够联合使用？

**Comment by xudifsd** [comment]
@111Moderato 
1. 你需要设置什么环境变量？这个正常
2. 不能跨服务器使用，只能用分布式作业使用不同机器的 GPU
3. 同理不能

**Comment by 111Moderato** [comment]
@xudifsd 

1.在.bashrc中进行了这些设置之后，nvidia-smi才正常显示出来，不然会提示找不到某个.so文件：

![image](https://user-images.githubusercontent.com/28188655/53787236-206a7e00-3f59-11e9-9fde-f2b0a3a1cb74.png)

2.对分布式作业不是特别理解，是指将任务划分成多个子任务，分别放入多个机器来运行吗？PAI是否能实现呢，有没有现有的demo示例存在呢？

**Comment by xudifsd** [comment]
@111Moderato 
1. 这个很正常，container 内部是 cuda 标准的环境，大部分 docker 都设置好了，比如 [tensorflow](https://github.com/tensorflow/tensorflow/blob/62f1d7fd04786aef3312dbecd50a6950c48c97a2/tensorflow/tools/docker/Dockerfile.devel-gpu#L100)
2. 是，见[此](https://github.com/Microsoft/pai/blob/pai-0.9.y/examples/tensorflow/README.md#distributed-tensorflow-cifar-10-image-classification)

**Comment by 111Moderato** [comment]
Thanks!
