### ISSUE TITLE
SSHClient hang during k8s-bootup, using password authentication

### ISSUE THREAD

**Issue by matthewygf** [Microsoft/pai#2200]
**Short summary about the issue/question**:
During the first k8s-bootup , SSHClient hang at sftp_paramiko.

**Brief what process you are following**:

**How to reproduce it**:

    1. Deploy dev-box

    2. configure cluster-config with username and password

    3. k8sdeploy

**OpenPAI Environment**: dev-box

    * OpenPAI version: v0.9.0

    * Cloud provider or hardware configuration:

    * OS (e.g. from /etc/os-release): ubuntu 16.04

    * Kernel (e.g. `uname -a`):

    * Hardware (e.g. core number, memory size, storage size, GPU type etc.):

    * Others:

**Anything else we need to know**:
Seems like its the ternary operator at these line
https://github.com/Microsoft/pai/blob/e79598a2c3d03ccd362830617c8f2a348d242e3d/deployment/k8sPaiLibrary/maintainlib/common.py#L206

https://github.com/Microsoft/pai/blob/e79598a2c3d03ccd362830617c8f2a348d242e3d/deployment/k8sPaiLibrary/maintainlib/common.py#L319

`password = password if password is not None else '' `
`stdin.write( password  + '\n')`

This seems to work

**Comment by ydye** [comment]
Thanks for your reporting.
1) #2201 fix for 0.9 branch
2) #2202 fix for 0.10 branch.
3) #2203 fix for master branch. 
@Gerhut  help me to review it. Thanks.

**Comment by scarlett2018** [comment]
@matthewygf - thanks for reporting the issue, in the new 2019 year, we will start a set of community communication program for PAI users. I had shared the 2019 OpenPAI Roadmap (backlog) in wiki, https://github.com/Microsoft/pai/wiki/Roadmap. We are encourage external contributors to join the design discussion and even PR submission.

Would you mind to share which organization (EDU or Company) you are presenting)? and what's the best way to reach your team, thanks.

**Comment by matthewygf** [comment]
@scarlett2018 - thank you for your message. will take a look at the roadmap.
i am a PhD student at Lancaster university in the UK, researching into platform for AI. My email is g.yeung1@lancaster.ac.uk .

**Comment by scarlett2018** [comment]
Thanks @matthewygf !
