### ISSUE TITLE
Team wise storage for NFS data storage

### ISSUE THREAD

**Issue by scarlett2018** [Microsoft/pai#2204]
**What would you like to be added**:
- PAI supports to set up multiple storage;
- PAI admin can set up users default and accessible storage;
- Storage between different teams can be isolated through settings;

**Why is this needed**:
- security considerations: data isolation;

**Without this feature, how does the current module work**：
all the teams are share one single storage set up

**Components that may involve changes**:
storage_plugin

**Comment by wangdian** [comment]
PR created:
https://github.com/Microsoft/pai/pull/2346

**Comment by wangdian** [comment]
Test Case:

Prerequisites:
1. Set up nfs server, e.g: 10.0.0.1:/share/teamA with settings: (rw, sync, no_root_squash)
2. Install PAI plugin submit-nfs-job [https://github.com/Microsoft/pai/tree/master/contrib/submit-nfs-job] #2358 
3. Start PAI dev-box

Steps:
1. In dev-box, go to pai/contrib/storage_plugin
2. Create server config:
    python storagectl.py storage set teamA 10.0.0.1 /share/teamA --sharedfolders data --privatefolders users
3. Create user config:
    python storagectl.py user setdefault user1 teamA
4. Go to nfs server, check if /share/teamA/data and /share/teamA/users/user1 folder was created
5. Login with user1 in PAI, go to submit-nfs-job page, check if nfs mount section filled with right information
6. Submit a job and check if the job files was created on nfs

**Comment by ydye** [comment]
@wangdian how to install webplugin?

**Comment by ydye** [comment]
@wangdian  When in steps2, come across this error.
```
root@stcal-121:/pai/contrib/storage_plugin# python storagectl.py storage set default x.x.x.x /share/default --sharedfolders data --privatefolders user
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
usage: storagectl.py [-h] {init,server,user,push} ...
storagectl.py: error: invalid choice: 'storage' (choose from 'init', 'server', 'user', 'push')

```
