### ISSUE TITLE
rest server continues restart

### ISSUE THREAD

**Issue by hellocandy** [Microsoft/pai#2205]
**Organization Name**: advantech

 

**Short summary about the issue/question**: We found that the openpai rest server will auto restart. Now we found it restart for 84 times. And it continues to restart. What is the matter of the restart？

**Brief what process you are following**: 

**How to reproduce it**: 

**OpenPAI Environment**: cluster
- OpenPAI version: 0.8.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by fanyangCS** [comment]
please provide logs of rest server.

**Comment by mzmssg** [comment]
Closed for inactiveness, feel free to reopen it with more details like logs.
