### ISSUE TITLE
[Close as Dup] display resource utility per vc/queue metrics

### ISSUE THREAD

**Issue by xudifsd** [Microsoft/pai#2208]
**What would you like to be added**:

A graph/list to show resource util per vc/queue

**Why is this needed**:

User sometime found their job is always in waiting state, this may be due to resource not enough in VC or resource fragment in node, need a graph to help them debug the issue

**Without this feature, how does the current module work**：

User check yarn's page manually.

**Components that may involve changes**:

* yarn-exporter
* grafana

**Comment by Anbang-Hu** [comment]
Is it possible to have metrics showing current resource fragmentation status (per VC)? We should manage users' expectation properly.

**Comment by xudifsd** [comment]
I'm not sure how to show resource fragmentation status, showing node count with certain free card number? How about memory? Like what hadoop showing disk?

![image](https://user-images.githubusercontent.com/665253/53539945-8e283b80-3b4e-11e9-90ef-98f84f934d3e.png)

But this is the whole picture, I think no vc view about this. Am I right? @mzmssg

**Comment by fanyangCS** [comment]
related. https://github.com/Microsoft/pai/issues/2013

**Comment by fanyangCS** [comment]
@xudifsd , a high priority issue is to show how many jobs are in waiting state in a VC.

**Comment by scarlett2018** [comment]
This is fit for the "Virtual Cluster" Page refactoring. Currently, when click on the VC instance name it goes to the single VC page. The current single VC page only has the generic VC info. We can add this info above the current table.

**VC Table**
![image](https://user-images.githubusercontent.com/39592018/53548340-37c9f580-3b6c-11e9-9afe-ec494cc21170.png)

**Single VC Page**
![image](https://user-images.githubusercontent.com/39592018/53548377-4f08e300-3b6c-11e9-89d0-aac2dcae0fe7.png)

**Comment by xudifsd** [comment]
@fanyangCS yes, yarn-exporter should get that metric. We will need to display that and node count with certain free gpu card, memory, cpu graph in some page, so user can get a sense why their job is waiting.

**Comment by mzmssg** [comment]
@fanyangCS 
> a high priority issue is to show how many jobs are in waiting state in a VC.
What's the definition of waiting status? AM launcher but no job container is regarded as  RUNNING or WAITING?

**Comment by yqwang-ms** [comment]
Job Waiting: Job Not Complete and Not Exist Container is Running

**Comment by xudifsd** [comment]
![image](https://user-images.githubusercontent.com/665253/54173221-04685e80-44bc-11e9-9789-f0d1fb213a0a.png)

As discussed in meeting, I think above picture may captured what user may find useful. It has three tables and one histogram. Meaning of each table:

* jobs pending: pending job count of each VC
* containers pending: pending container count of each VC
* free resources: resource available in each VC, this table has already shown in virtual cluster page right now
* free gpu histogram: show node count with certain free GPU, so user could know if certain task can fit in cluster, take the picture as example, tasks require 8 GPU will never be scheduled, since there are no nodes with 8 free GPU.

All required metrics has been exported by #2289 

@scarlett2018 Maybe experience team can take over this job?

**Comment by fanyangCS** [comment]
https://github.com/Microsoft/pai/issues/1943

**Comment by fanyangCS** [comment]
https://github.com/Microsoft/pai/issues/1989

**Comment by scarlett2018** [comment]
@xudifsd - sure, but I don't think experience team has capacity to do this in 0.11.0. 
cc @weixingzhang - do your team want to take this? or are there any comments around this design?

**Comment by scarlett2018** [comment]
Will address this in #2539
