### ISSUE TITLE
Refine Job Details Page Phase I

### ISSUE THREAD

**Issue by scarlett2018** [Microsoft/pai#2211]
**What would you like to be added**:
Refine current Job Details Page to provide a simpler and easier to understand experience for Job Owners.

**Why is this needed**:

- Currently, the tasks' status are not clear and exposing in job detailed view. Users are not clear how things going if some of the tasks are not yet started.
- User logs are inside Tracking Pages, and hard to find.
- Diagnostic info are in several pages and not clear enough which is the one user should follow. 

-----------
**Mock Up**
Task status is displayed and categorized.
![image](https://user-images.githubusercontent.com/39592018/53409665-78a2fc80-39fc-11e9-8b5a-83ec409e0fc4.png)

Task info
![image](https://user-images.githubusercontent.com/39592018/53409678-83f62800-39fc-11e9-8e4b-a142b90d1fee.png)

User log is to the task level and extract to the highest level.
![image](https://user-images.githubusercontent.com/39592018/53409688-8ce6f980-39fc-11e9-91b1-4fa672315744.png)

User log view
![image](https://user-images.githubusercontent.com/39592018/53409704-93757100-39fc-11e9-8a51-b42b022ce530.png)

Go to tracking page is moving to 2nd level "..."
![image](https://user-images.githubusercontent.com/39592018/53409712-983a2500-39fc-11e9-9a7f-135e60184950.png)

**Comment by fanyangCS** [comment]
For “Retries”,please separate system retries from user retries.

**Comment by fanyangCS** [comment]
https://github.com/Microsoft/pai/issues/1990

**Comment by scarlett2018** [comment]
Task State has been differed to Mid April release, the rest design were committed in 0.11.0.

**Comment by sunqinzheng** [comment]
## Test Cases
- Header
  - "Back To Jobs" button
- Job Summary
  - "Refresh" button
  - Auto refresh dropdown
    - could be tested by checking http requests in browser's developer tools
  - Job config
    - will be opened in monaco editor panel
    - will be disabled if job config doesn't exist (launcher test job)
  - Application summary
    - will be opened in monaco editor panel
  - Go to application tracking page
    - will open yarn app tracking page
  - Go to job metrics page
    - will open grafana job metrics page
- Task Info
  - Task role config (question mark icon button)
    - will be opened in monaco editor callout
  - Task Info could be collapsed/expanded
  - Container List
    - View SSH Info
      - bash commands with comments will be showed in monaco editor panel
      - will be disabled if job is not running
    - Stdout / Stderr
      - last 4096 bytes will be showed in monaco editor panel  
      - will be auto refreshed every 10 seconds
        - could be tested by checking http requests in browser's developer tools
      - "View full log" button
        - will open yarn full stderr/stdout log page
    - More icon button -> Go to yarn tracking page
      - will open yarn container tracking page
