### ISSUE TITLE
PAI would officially support upgrade from previously installation after v0.10 (inclusive)

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#2212]
PAI would officially support upgrade, since the release v0.10.

We would provide detailed documents and support plan with each release.

**Comment by scarlett2018** [comment]
deploy 3/18, dogfood 2 days, target release on 3/21. @hao1939

**Comment by fanyangCS** [comment]
@hao1939 , can we close this issue?

**Comment by hao1939** [comment]
Close it, we have announced.
