### ISSUE TITLE
no-driver label mismatch 

### ISSUE THREAD

**Issue by matthewygf** [Microsoft/pai#2219]
**Organization Name**: 

**Short summary about the issue/question**:

**Brief what process you are following**: 

**How to reproduce it**: 

**OpenPAI Environment**: dev-box
- OpenPAI version: v0.9.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:
https://github.com/Microsoft/pai/blob/5f870b348f66b8cff75f65825493e0948c55e0d2/src/drivers/deploy/service.yaml#L35

https://github.com/Microsoft/pai/blob/5f870b348f66b8cff75f65825493e0948c55e0d2/deployment/paiLibrary/paiService/service_management_refresh.py#L72

**Comment by ydye** [comment]
Label the node with ```no-drivers``` through kubelet, the ```drivers``` won't be deployed to the node.

**Comment by ydye** [comment]
https://github.com/Microsoft/pai/pull/2221/files Fix it in master branch.
In the previous release, you could label the machine with the label ```no-drivers``` through kubectl.

**Comment by fanyangCS** [comment]
feel free to reopen it if running into further issues.
