### ISSUE TITLE
batch-job cannot work

### ISSUE THREAD

**Issue by hellocandy** [Microsoft/pai#2220]
**Organization Name**: Advantech

**Short summary about the issue/question**:
batch-job cannot work in KVM

**Brief what process you are following**: 
We create 2 VMs and try to deploy OpenPAI into it. But batch-job cannot work.

**How to reproduce it**: 
I use the following command to create VM:
virt-install  --name=master0 --ram 65536 --vcpus=16 --disk path=/var/afs/master-vm/xenial-server-cloudimg-amd64-disk1.img,size=120,format=raw,bus=virtio --network bridge=br0,model=virtio --vnc --accelerate --force  --autostart --boot hd --boot init=/var/afs/first-boot.sh --boot useserial=on --noautoconsole -v

The batch-job log shows: Call From127.0.0.1 to 172.21.81.186:9000 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused

**OpenPAI Environment**:
- OpenPAI version: v0.8.3
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release): Ubuntu 16.04 LTS Server
- Kernel (e.g. `uname -a`):4.4.0-131-generic
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):CPU XEON 4116 24 core * 2, 148GB RAM, 1TB storage.
- Others:

**Anything else we need to know**:

**Comment by mzmssg** [comment]
Could you provide more VM network details and confirm firewall? 
Is the 172.21.81.186 your master node ip?

**Comment by hellocandy** [comment]
Hi mzmssg,

Master IP: 172.21.81.186
Worker IP: 172.21.81.182

Both of them connect to router directly. And there is no firewall enabled.

**Comment by mzmssg** [comment]
@hellocandy 

Could you help execute some command on Worker?

```
# First zoom in hadoop-data-node
`sudo docker ps | grep k8s_hadoop-data-node` | awk '{print $1}'
sudo docker exec -it ${contianer_id}  /bin/bash

# Confirm connection to hdfs
hdfs dfs -ls /
```

**Comment by hellocandy** [comment]
Hi mzmssg, Here is the command output info:

root@ubuntu:/# hdfs dfs -ls /
ls: Call From localhost/127.0.0.1 to 172.21.81.186:9000 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
root@ubuntu:/#

**Comment by mzmssg** [comment]
@hellocandy 
Confirm hdfs status at 172.21.81.186:5070
if not, please paste name-node log, which is on 172.21.81.186 as well.

**Comment by mzmssg** [comment]
Closed inactivity, feel free to reopen it
