### ISSUE TITLE
Allow IP + Port machine definition in quickstart yaml

### ISSUE THREAD

**Issue by cauldnz** [Microsoft/pai#2224]
**What would you like to be added**:
I would like to be able to speficy the machine list in yaml including both the IP address and a port. So, for example

```
  - 52.168.5.20:50000
  - 52.168.5.20:50001
  - 52.168.5.20:50002
```

**Why is this needed**:
I am trying to deploy OpenPAI using an Azure Virtual Machine Scale Set. This will allow us to easily deploy a cluster using Low Priority Virtual Machines for the compute. By default, a VMSS will expose each machine on a common IPv4 address but with a unique SSH Port. This uses a Load Balaner. This approach allows us to use a local dev-box to manage the cluster and use the single public IP address plus port.

**Without this feature, how does the current module work**：

The current code validates a correct IPv4 address and fails

> 2019-02-27 17:33:33,023 [ERROR] - deployment.k8sPaiLibrary.maintainlib.common : 52.168.5.16:50000 is not a correct ipv4 address!

**Components that may involve changes**:

- Likely to just be a case of modifying `cluster_util.py` to support a unique IPv4+Port combo. At present `ssh-port` can be defined but this applies to all the IPv4 addresses
- cluster-configuration.yaml already supports `hostip` and `sshport` on a per machine basis so assume that given a valid config file everything else should just work.

Hopefully I'll get time to take a look at this issue to send a PR myself. I would appreciate the core team advising if this is appropriate and if there is a preferred approach please?

**Comment by hao1939** [comment]
Hi @cauldnz,

quick-start is only used as a template for generating the config.
So you can generate the config, then manually update the port.

**Comment by scarlett2018** [comment]
@cauldnz - Hi Chris, does @hao1939 's suggestion helps? are you able to walk around the issue?

**Comment by hao1939** [comment]
Hi @cauldnz , I will close it now. Feel free to reopen it if you have more question.
