### ISSUE TITLE
Support samba shares in container

### ISSUE THREAD

**Issue by abuccts** [Microsoft/pai#2227]
PAI runs job container w/o privileged mode enabled. To support samba/smbfs/cifs mount in job container, we need to adjust some capabilities for Docker so that we do not need to start privileged Docker container.

Currently, PAI supports hdfs-mount with `--cap-add=SYS_ADMIN --device=/dev/fuse --security-opt apparmor:unconfined` flags.

To add samba/smbfs/cifs support, `--cap-add=SYS_ADMIN --cap-add=DAC_READ_SEARCH --security-opt apparmor:unconfined` flags are needed in a non-privileged container.

**Comment by fanyangCS** [comment]
so we need to add --cap-add DAC_READ_SEARCH when running a job docker container

**Comment by fanyangCS** [comment]
https://github.com/Microsoft/pai/issues/2046
