### ISSUE TITLE
Add TotalGpuCount and TotalTaskCount into job list

### ISSUE THREAD

**Issue by yqwang-ms** [Microsoft/pai#2228]
**What would you like to be added**:
Add more info into job list, such as TotalGpuCount, TotalTaskCount, etc.

**Why is this needed**:
User can find jobs easiliy with these more info in list.

**Without this feature, how does the current module work**：
Check into job detail info one by one.

**Components that may involve changes**:
web portal, launcher, rest server.

--------------
I'm deferring the "TotalTaskRoleCount" ask from this item, as it seems not that critical to be known in a glance. let's hold this ask to later.

**Comment by yqwang-ms** [comment]
Please help to propose these additional info that you want to add.
Current plan is to add:
TotalGpuCount in Request, TotalTaskCount in Request.

**Comment by fanyangCS** [comment]
maybe to show a meta data field.

**Comment by yqwang-ms** [comment]
@fanyangCS 
What meta data field do you mean? 
Is frameworkDescription below (it can be any string) enough?
![image](https://user-images.githubusercontent.com/32826762/53543433-a5225a00-3b5d-11e9-9ccd-4095f5b61af1.png)

**Comment by fanyangCS** [comment]
Yes. what is the max length? 512?

**Comment by yqwang-ms** [comment]
Yes, 512, it should be enough at least for job list.

**Comment by yqwang-ms** [comment]
@fanyangCS do you need more? Or could you please help to involve PAIExp team?

**Comment by yqwang-ms** [comment]
@fanyangCS I increased the description len to 1024

**Comment by scarlett2018** [comment]
Rest is ready for UX.
