### ISSUE TITLE
The job log link returned by rest api was broken, after job finished

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#2230]
Example: the REST API returns me a container http address below:
http://.../**containerlogs**/container_e12_1549463094480_0900_01_000002/jerasley/

1. When job was running, user could access the container stdout log via the link below:
http://.../**containerlogs**/container_e12_1549463094480_0900_01_000002/jerasley/stdout/?start=0

2. After the job finished, the link broke. It would redirect to the url likes:
http://...**applicationhistory**/logs/10.1.0.8:8041/container_e12_1549463094480_0900_01_000002/container_e12_1549463094480_0900_01_000002/jerasley/stdout?start=0?**start=0**

There's an additional `start=0` appended at the end of the url, which broke the link.

**Comment by hao1939** [comment]
Hi @scarlett2018 ,
Could we add it into the March release? It seems like a small fix and user want it.

**Comment by fanyangCS** [comment]
@hao1939, It would be great if you have free cycles to fix it.

**Comment by scarlett2018** [comment]
@hao1939, sure thing, thanks!

**Comment by hao1939** [comment]
Ok, put it into my backlog.

**Comment by mzmssg** [comment]
Confrim yarn code, redirection works, I guess it's pylon issue.

For raw yarn uri, such as
```
http://{work_node_ip}:8042/.../stdout/?start=0
redirect to
http://{master_node_ip}:8188/.../stdout/?start=0
```
But with pylon
```
http://{pylon_uri}/{work_node_ip}:8042/.../stdout/?start=0
redirect to
http://{pylon_uri}/{master_node_ip}:8188/.../stdout/?start=0?start=0
```

@Gerhut to help investigate more.

**Comment by Gerhut** [comment]
Confirmed that it's a pylon bug, fixing
