### ISSUE TITLE
Support to hide secret information in job file

### ISSUE THREAD

**Issue by squirrelsc** [microsoft/pai#2240]
**What would you like to be added**:
User can use some customized variables in job definition file, so that some secret like password can be hidden. For example, let user can define some secret env variables, and the variables can shown in owner's job definition, but show stars in others' view. Azure Devops has similar design.

**Why is this needed**:
There are some password, or connection information, and they shouldn't be shown to others. but currently, everyone can view all job definition. And some user may need to learn from others' job definitions. It's good to share job definition, but other users should have same secret information before accessing resource.

**Without this feature, how does the current module work**：
No workaround yet. user's secret will leak to everyone.

**Components that may involve changes**:

**Comment by fanyangCS** [comment]
We can define a rule: any variables starting with the prefix PAI_SECRET will be hidden from the log, as well as the job config file.

**Comment by squirrelsc** [comment]
@scarlett2018  can it be supported earlier, so that user can use storage safer.

**Comment by scarlett2018** [comment]
Adding @qfyin , @sunqinzheng  and @abuccts for technical evaluation on this feature.

**Comment by mydmdm** [comment]
We support `secrects` in [new job protocol](https://github.com/Microsoft/pai/blob/master/docs/pai-job-protocol.yaml)
