### ISSUE TITLE
Support HDFS percentage quota control

### ISSUE THREAD

**Issue by mzmssg** [microsoft/pai#2242]
**What would you like to be added**:
1. expose hdfs reserved disk to cluster-configuration
2. support percentage configuration.

**Why is this needed**:
For now, we reserve a fixed value(10 G) on every machine, but alert is triggered by percentage. Align them with each other would be better.

**Without this feature, how does the current module work**：
calculate quota value then change code to apply

**Components that may involve changes**:
hadoop data node

**Merging #1995 's comments in:**
How to:
1 from PAI design & refactor view:
Replanning the disk usage on HDFS;
1.1 space for service & its folder
1.2 space for job & its folder [important]
should limit the user flexibility
image

2 Give doc or auto config HDFS directory quota [Based on 1 then could better do & manage 2]
https://hadoop.apache.org/docs/r2.7.2/hadoop-project-dist/hadoop-hdfs/HdfsQuotaAdminGuide.html

3 For config hdfs multipath feature has merged.
Give admin flexibility for disk space of HDFS.

**Comment by fanyangCS** [comment]
https://github.com/Microsoft/pai/issues/1995

**Comment by fanyangCS** [comment]
we decide to delegate quota control to individual storage provider.
