### ISSUE TITLE
cluster clean does not work

### ISSUE THREAD

**Issue by shawntian90** [Microsoft/pai#2243]
Hi,

I setuped up an test environment of OpenPAI v0.9.1 with one master and one worker with GPU, which master is 4 CPUs and 8G RAM.

At first, I was failed, because the CPU of master is not meet the requirement of Master server. So I clean up the entire environtment via command:

```bash
./paictl.py cluster k8s-clean -p /cluster-configuration/
```

And delete the dev-box docker container and then re-run `bootup` command. But something wired happed.

![image](https://user-images.githubusercontent.com/1191121/53619681-25fb5780-3c2b-11e9-80e6-216790ec7a74.png)

It seems that the old data of k8s was remained.

**OpenPAI Environment**:
- OpenPAI version: v0.9.1
- Cloud provider or hardware configuration: Aliyun
- OS (e.g. from /etc/os-release): Ubuntu 16.04.4 LTS
- Kernel (e.g. `uname -a`):4.4.0-117-generic
- Hardware (e.g. core number, memory size, storage size, GPU type etc.): 
  master: 4cores, 8G
  worker: 8cores, 32G, Nvidia

Please help!

**Comment by fanyangCS** [comment]
@shawntian90 , as the UI showed, your hardware does not have enough resource. Please find more powerful machines to try.

**Comment by mzmssg** [comment]
For a test purpose, you could disable qos by a flag:
https://github.com/Microsoft/pai/blob/d26f762301f0de2efd263b84548f958b453d979b/examples/cluster-configuration/services-configuration.yaml#L28

**Comment by shawntian90** [comment]
Hi, @fanyangCS,

Thanks for the reply.

This is an **TEST** environment, which is used for testing the new release of OpenPAI and doing some dangerous operation. Limited resource for this environment.

So I edit the yaml file:

```
	modified:   deployment/k8sPaiLibrary/template/apiserver.yaml.template
	modified:   deployment/k8sPaiLibrary/template/controller-manager.yaml.template
	modified:   deployment/k8sPaiLibrary/template/dashboard-deployment.yaml.template
	modified:   deployment/k8sPaiLibrary/template/etcd.yaml.template
	modified:   deployment/k8sPaiLibrary/template/scheduler.yaml.template
```

Decrease the resource requrest of CPU option to the following:

```
:/pai# git diff deployment/k8sPaiLibrary/template/apiserver.yaml.template
diff --git a/deployment/k8sPaiLibrary/template/apiserver.yaml.template b/deployment/k8sPaiLibrary/template/apiserver.yaml.template
index 8c49b1a..4ada54f 100644
--- a/deployment/k8sPaiLibrary/template/apiserver.yaml.template
+++ b/deployment/k8sPaiLibrary/template/apiserver.yaml.template
@@ -51,5 +51,5 @@ spec:
     resources:
       requests:
         memory: "1Gi"
-        cpu: "1000m"
-    {%- endif %}
\ No newline at end of file
+        cpu: "500m"
+    {%- endif %}
```

**Comment by shawntian90** [comment]
@fanyangCS , the `does not have enough resource` is not the key point, what I want to ask is that:

Why some old data still exists when I rebuild the entire openpai?

**Comment by mzmssg** [comment]
@shawntian90 
Add `-f` to clean all k8s data, by default we only stop k8s.
```
./paictl.py cluster k8s-clean -p /cluster-configuration/ -f
```

**Comment by shawntian90** [comment]
Hi, @mzmssg ,

SOOOOO much for the help! `-f` really works!
