### ISSUE TITLE
Jub Submission Needs - Extending needs from Simple Job Submission Item.

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#2247]
1. For directory paths in docker, it should be able configurable. So that user don't need to update their code to align with OpenPAI. 
2. The paths may need credential to access. It's a difficult part to support different type of resource, but need to be considered in design also.
3. We should tell user or let their choose the files are copied or mounted. So that they know the disk space impact, and if they can get data out with those folders.

_Originally posted by @squirrelsc in https://github.com/Microsoft/pai/issues/2238#issuecomment-468509257_

**Comment by fanyangCS** [comment]
new job submission experience should support all this.
