### ISSUE TITLE
Highlight low resource utilization jobs on webportal

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#2249]
Should design a metrics label for job owner, and define an alert rule, also for query to check if job is in low resource for rest-server to highlight.

Note from: Di Xu
low resource jobs can be queried from http://$IP:9091/prometheus/api/v1/query_range?query=avg%20by%20(job_name)%20(task_gpu_mem_percent)%20%3C%2010%20and%20avg%20by%20(job_name)%20(task_gpu_percent)%20%3C%2010&start=2019-03-13T04:00:00.000Z&end=2019-03-13T06:00:00.000Z&step=300s

should change start/end/step, and if result jobs has value less than 10% for 4 hours, we can mark them as red in webportal

**Comment by xudifsd** [comment]
We can send email to job owner, by using GroupLabels as demonstrated in [this](https://github.com/Microsoft/pai/tree/dixu/alert-on-low-resource) branch

**Comment by sterowang** [comment]
Added a new related issue #2629

**Comment by fanyangCS** [comment]
done
