### ISSUE TITLE
Mark utilization for each job in the Node

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#2250]
#2197 merged. But seems user want something like, jobs with low resource util are marked with red:

![image](https://user-images.githubusercontent.com/665253/53540717-a0f03f80-3b51-11e9-8682-5cc1d54dbe7e.png)

We can add extra column to following page:

![image](https://user-images.githubusercontent.com/665253/53540762-c41aef00-3b51-11e9-9881-82b22d0204ea.png)

Also user want ordinary user could see the page instead of admin.

Should we discuss this? @scarlett2018 and @fanyangCS @Gerhut @Anbang-Hu

_Originally posted by @xudifsd in https://github.com/Microsoft/pai/issues/2128#issuecomment-468130720_

**Comment by fanyangCS** [comment]
https://github.com/Microsoft/pai/issues/1943

**Comment by scarlett2018** [comment]
related to #2404

**Comment by fanyangCS** [comment]
done in v0.15

**Comment by fanyangCS** [comment]
done in v0.14
