### ISSUE TITLE
Need the feature to copy dataDir content from hdfs to local container automatically

### ISSUE THREAD

**Issue by gemfield** [Microsoft/pai#2268]
Currently(version 0.9.1), only codeDir will be copied automatically.

**Comment by gemfield** [comment]
Also, what is the most efficient way to copy dataDir for current version (0.9.1, wrt to the largest dataset size)?  currently I use following command, is this reasonable? 
```bash
hdfs dfs -get $PAI_DATA_DIR ./data
```
Thanks.

**Comment by fanyangCS** [comment]
@gemfield , OpenPAI will not support this feature. for smaller dataset, your approach makes sense. For larger dataset, this approach will lead to out of disk exception.

If you decide to store large data in hdfs, the recommended way is to use the native hdfs reader to read the data in-the-fly. TensorFlow supports hdfs natively. As for PyTorch, we suggest to leverage Python hdfs library to do so (e.g., https://hdfscli.readthedocs.io/en/latest/).
