### ISSUE TITLE
in clusterview, show allocated GPU count instead of used GPU count

### ISSUE THREAD

**Issue by fanyangCS** [Microsoft/pai#227]

**Comment by scarlett2018** [comment]
cleaning old issues,  @fanyangCS   please help to evaluate whether this is still an issue, thanks.

**Comment by fanyangCS** [comment]
making the reserved GPU count consistent

**Comment by YitongFeng** [comment]
Is on the way, should we add this feature in v0.7 release? @fanyangCS

**Comment by fanyangCS** [comment]
please link the PR to this issue. If the change involves multiple components, I would suggest to test it thoroughly and go with the next release.

**Comment by YitongFeng** [comment]
#1035
