### ISSUE TITLE
How can we remove these services ?

### ISSUE THREAD

**Issue by Tuskio** [Microsoft/pai#2276]
When we move openpai to another sub-network the problem happened. Some services belong to the first sub-network are waiting start. Actually, they couldn't be started. And now, we can't install anymore, unless reinstall OS. How can we remove these services ?

![image](https://user-images.githubusercontent.com/30797159/53858506-74d33380-4015-11e9-89e8-690590504b12.png)

**Comment by mzmssg** [comment]
If your cluster-configuration is right, I think you could delete the stale inaccessable nodes by `kubectl delete node`.
