### ISSUE TITLE
pylon is not ready yet. Please wait for a moment! [Occasional]

### ISSUE THREAD

**Issue by mydmdm** [Microsoft/pai#2282]
**Organization Name**: 

**Short summary about the issue/question**:

**Brief what process you are following**: 

**How to reproduce it**: 

**OpenPAI Environment**: 
- OpenPAI version: v0.9.0 
- Cloud provider or hardware configuration: Azure 
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.): 64GB mem，16vcpu
- Others:

**Anything else we need to know**:
![image](https://user-images.githubusercontent.com/7117512/53939689-cc919d80-40ee-11e9-9444-0c05f863d743.png)

**Comment by fanyangCS** [comment]
pulling docker images takes time, especially when your server connection to docker registry has low bandwidth. 
I assume it will go away after a while?

**Comment by sterowang** [comment]
Can you show post the kubelet and pod for pylon-ds-xxxx logs on 192.168.200.3?

**Comment by ddebby** [comment]
Issue fixed by the following steps:

1.  Check pylon-ds logs:
```
~$ kubectl logs pylon-ds-jrsg8

Error from server (BadRequest): container "pylon" in pod "pylon-ds-jrsg8" is waiting to start: ContainerCreating
```
2. Check docker logs:
```
sudo journalctl -u docker

...
Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use"
```
It seems the 80 port is already used by other process.

3. Check the port using applications info:
```
~$ sudo netstat nlp |grep 80
```
The apache2 is using 80 port and so docker-proxy service is hung.

After stop the apache service and issue fixed.

**Comment by fanyangCS** [comment]
As it is resolved, I hereby close this issue. feel free to reopen it if you run into further issues.
