### ISSUE TITLE
have to re-install OpenPAI after VM powered off and on

### ISSUE THREAD

**Issue by mydmdm** [microsoft/pai#2283]
**Organization Name**: 

**Short summary about the issue/question**:
After installing, everything seems ok and jobs can be submitted successfully. But after the VM restarted, OpenPAI fails to work. 

**Brief what process you are following**: 

**How to reproduce it**: 

**OpenPAI Environment**:
- OpenPAI version: v0.9.0 
- Cloud provider or hardware configuration: Azure VM
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.): 64GB mem，16vcpu
- Others:

**Anything else we need to know**:

**Comment by fanyangCS** [comment]
this is the all-on-one setup?

**Comment by scarlett2018** [comment]
@mydmdm please provide more logs as @fanyangCS asked, thanks.

**Comment by fanyangCS** [comment]
close as no response in a long time.
