### ISSUE TITLE
docker's data-root will lost on Azure Node restart

### ISSUE THREAD

**Issue by ydye** [microsoft/pai#2286]
**Organization Name**: ```OpenPAI```

**Impact**
Currently, PAI is using temp path, but if Azure restarts, temp data will lost. PAI can use other path as the temp path instead, while on the other side OS disk is too small to be used.

**Short summary about the issue/question**:

``` 
If you configure docker ```data-root``` to a tmp path and data on the tmp path is lost, OpenPAI will crushed.
What's more, kubelet won't restart due to the loss of docker's ```data-root```. 
```

https://forums.docker.com/t/unable-to-restart-the-container-when-the-data-of-data-root-is-lost/70581

**Brief what process you are following**: 

**How to reproduce it**: 

```
sudo systemctl stop docker
sudo rm -rf /path/to/docker/data/root
sudo systemctl start docker
```

**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by fanyangCS** [comment]
@ydye, do you have time to fix this?

**Comment by ydye** [comment]
@fanyangCS If you accept the solution to start kubelet by systemd, instead of docker.

**Comment by fanyangCS** [comment]
@ydye, I agree with your solution. Please make sure user can upgrade smooth from old to new solution.

**Comment by ydye** [comment]
@fanyangCS Obviously, it will be a broken upgrade. User will have to stop all service and restart all k8s node.

**Comment by fanyangCS** [comment]
That’s ok.

**Comment by scarlett2018** [comment]
@ydye - may you provide an estimation for this task? we are considering putting it in Aug release.

**Comment by ydye** [comment]
https://github.com/microsoft/pai/pull/3307

**Comment by ydye** [comment]
Code Merged.

**Comment by fanyangCS** [comment]
could you deploy it to the INT bed?
