### ISSUE TITLE
paibuild hadoop-run.dockerfile can not find dependency/hadoop-binary

### ISSUE THREAD

**Issue by matthewygf** [Microsoft/pai#2293]
**Organization Name**: 

**Short summary about the issue/question**:
During paibuild for hadoop-run images, the hadoop binary path was not copied to dependency after hadoop-ai was built similar to #780. 

**Brief what process you are following**: 
During initial Paibuild

**How to reproduce it**: 
python paibuild.py build -c [path/to/configDir]

**OpenPAI Environment**:
- OpenPAI version: 0.9.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:
One thing i tried to make it work was to manually copied the hadoop binary path from hadoop-ai,
by putting the following lines at the start in hadoop-run/build/build-pre.sh, 
then it will follow the rest of the script, copying the /hadoop-binary into dependency.

`docker create -ti --name=hadoop-dummy --volume=/hadoop-binary:/hadoop-binary hadoop-build /bin/bash`
`docker cp hadoop-dummy:/hadoop-binary /hadoop-binary`
`docker rm -fv hadoop-dummy`

**Comment by mzmssg** [comment]
@matthewygf 
What's your build environment, on your host or in the dev-box?
