### ISSUE TITLE
Why the containers always show all of the GPUs?

### ISSUE THREAD

**Issue by ICEORY** [Microsoft/pai#2294]
- OpenPAI 0.9.1

After upgrading the OpenPAI from 0.8.2 to 0.9.1, I find that the containers always allocate all of GPUs of the host machine. 

e.g. ,
![image](https://user-images.githubusercontent.com/11911903/54080878-b117d400-4334-11e9-9d8a-4b83764e8d56.png)

when I run "nvidia-smi", I got

![image](https://user-images.githubusercontent.com/11911903/54080837-fb4c8580-4333-11e9-8391-6c5009b03f3c.png)

- More information: 

![image](https://user-images.githubusercontent.com/11911903/54080849-2931ca00-4334-11e9-8aff-29b447320aa2.png)

- docker version: 
![image](https://user-images.githubusercontent.com/11911903/54080884-1370d480-4335-11e9-88b8-852278783174.png)

- nvidia-container-runtime --version
runc version 1.0.0-rc6+dev
commit: 12f6a991201fdb8f82579582d5e00e28fba06d0a-dirty
spec: 1.0.1-dev

**Comment by ICEORY** [comment]
@abuccts thanks, adding `-e NVIDIA_VISIBLE_DEVICES=$gpu_id` to the file `yarnContainerScript.mustache` solve the issue

**Comment by xudifsd** [comment]
@ICEORY what's your config? Did you enabled the [`set-nvidia-runtime`](https://github.com/Microsoft/pai/blob/pai-0.9.y/deployment/quick-start/services-configuration.yaml.template#L82)?

**Comment by ICEORY** [comment]
Yes, I have enabled the `set-nvidia-runtime`. Should I disable it?

**Comment by xudifsd** [comment]
@ICEORY Yes, how did you know that config?

**Comment by ICEORY** [comment]
well, when upgrading the OpenPAI, I got the issues "fork/exec /usr/bin/nvidia-container-runtime: no such file or directory: unknown" and "cannot locate software nvidia-container-runtime". Then, I added the source of `nvidia-container-runtime` and enabled the `set-nvidia-runtime`(this option is provided in `service-configuration.yaml` ). I guessed the issues above are caused by `nvidia-container-runtime` :-)

By the way,  I also need to delete the old replica set of `prometheus`, `watchdog`, `grafana` by hand, in order to deploy the new replica set.

**Comment by xudifsd** [comment]
Yes, drivers will config nvidia-container-runtime in `/etc/docker/daemon.json` in version 0.9, so the upgrade process should tear down k8s and redeploy k8s again.

But PAI users should not use `set-nvidia-runtime`, this option is used for kube-launcher project, and was added in #1437 . But since you added `-e NVIDIA_VISIBLE_DEVICES`, I think there should be no other problems, you can keep that option.

What you mean by hand? During upgrade, you should use paictl to do `service stop` and `service start`, the stop command will delete 3 services you mentioned.

**Comment by ICEORY** [comment]
I have tried `service stop` and `service start` several times, but I found that the new replica set would keep pending if the old ones are running. Besides, it seems that the old version of replica set would run first and the new ones are pending when I restart the services. So I delete the services on kubernetes by myself.

**Comment by xudifsd** [comment]
After you've done `service stop`, all old replica set will stop. Why you still have old one?

**Comment by ICEORY** [comment]
@xudifsd Thanks for your help! 

Since I have deployed OpenPAI successfully, I cannot reproduce the issue and cannot provide more details.

**Comment by xudifsd** [comment]
Ok, I will close the issue, feel free to reopen it if you have more concerns.

**Comment by xudifsd** [comment]
@ICEORY Hi, we just found by setting `-e NVIDIA_VISIBLE_DEVICES=$gpu_id` may have unexpected consequences, you can reference what we found [here](https://github.com/Microsoft/pai/issues/1667#issuecomment-474195824). Basically, you should set NVIDIA_VISIBLE_DEVICES to empty string not `$gpu_id`.
