### ISSUE TITLE
Azure Load Balance issue may cause cluster status unstable

### ISSUE THREAD

**Issue by ydye** [Microsoft/pai#2298]
**Organization Name**: 
```
Microsoft
```

**Short summary about the issue/question**:
```
If the master nodes is in the backend pool of azure lb, the request from kubelet on k8s-master to api-server will fail, due to the known issue of azure lb in the following link. And then, the k8s status on the master node will be unstable.
```
https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-overview#limitations

**Brief what process you are following**: 

**How to reproduce it**: 

**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by fanyangCS** [comment]
It seems Azure application gateway does not have this limitation. https://azure.microsoft.com/en-us/services/application-gateway/

**Comment by fanyangCS** [comment]
I hereby close this issue, as this is not a PAI bug.
