### ISSUE TITLE
March 2019 Endgame

### ISSUE THREAD

**Issue by scarlett2018** [Microsoft/pai#2307]
This is the endgame schedule for [March 2019 Iteration](https://github.com/Microsoft/pai/issues/2207).
_last updated on 3/21/2019_

**Schedule** 
-----------------
- End game master: @mzmssg 
- **March**  ~15~ **20, 2019** Code freeze for the endgame
- ~March 29~ **April 3, 2019** Endgame done
- ~March 29~ **April 3, 2019**  Expected release date (this may change)

~Friday 03/15~ Wednesday  3/20 @mzmssg
- [x] Code freeze at 6pm UTC+8 
- [x] Release branch pai-0.11.y

~Monday 03/18~ Thursday 3/21
- [x] Image build @mzmssg
- [x] Int bed deploy @mzmssg
- [x] Feature **test case** ready 
  - [x] Detect and alert for unhealthy GPU  @mzmssg
  - [x] Provide the ability to query all the jobs in a Node in PAI Web Portal @xudifsd 
  - [x] Team wise storage management support @wangdian 
  - [x] Simplest Job Submission Page for Job (types) that will only run on 1 node @debuggy 
  - [x] Provide filters for jobs list page @Gerhut 
  - [x] Refine Job detail page @sunqinzheng 
  - [x] Basic supports for reserving container's life time for debug after job completion @ydye 
- [x] Test @mzmssg

~Tuesday - Wednesday  03/19 - 03/20~ Friday - Monday 3/22 - 3/25
- [x] Release checklist validate @mzmssg
- [x] New feature test (_test owner to be decided_)
- [x] Bug bash 
- [x] Cherry-pick hotfix
- [x] Remind teams to verify issue status

~Thursday 03/21~ Tuesday 3/26
- [x] Release note ready, confirm with team members. @scarlett2018 @mzmssg
   - [x] Each release should update the quick-start template to using the latest release image tag.
   - [x] Each release may need to update the upgrade tutorial, for example, change version numbers in some place or so on.
- [x] Rebuild images @mzmssg
- [x] Push images to public repo @mzmssg
- [x] Prod bed upgrade headsup announcement @scarlett2018

~Friday 03/22~ Wednesday 3/27
- [x] Prod bed data backup @mzmssg
- [x] Prod bed upgrade @mzmssg
- [x] Polish release notes @scarlett2018 

~Monday-Wednesday 03/25-03/27~ Thursday - Monday 3/28 - 4/1
- [x] Dogfood user test @scarlett2018 
- [x] Collect feedback @scarlett2018  
- [x] Fix blocking issue
- [x] Polish release notes @scarlett2018 

~Thursday-Friday 03/28-03/29~ Tuesday - Wednesday 4/2 - 4/3
- [x] Add git tag @mzmssg
- [x] Release announcement @scarlett2018

**Comment by hao1939** [comment]
Add two items:
1. Each release should update the `quick-start` template to using the `latest release` image tag.
2. Each release may need to update the `upgrade` tutorial, for example, change some version numbers and so on.

**Comment by mzmssg** [comment]
Should also change the version to the latest
https://github.com/Microsoft/pai/blob/86f0fd50fa2c0f47d359824d8e80bb9a93ef0665/deployment/tools/configMigration.py#L66
