### ISSUE TITLE
How to get permission to delete Job

### ISSUE THREAD

**Issue by 111Moderato** [Microsoft/pai#2308]
I tried to delete one of the jobs（framework） and run the command：
`curl -XDELETE 'http://master-ip:9086/v1/Frameworks/admin~caffe-mnist'`
But I got a lot of logs,  I think the important ones is：
`{"exception":"AuthorizationException","message":"com.microsoft.frameworklauncher.common.exceptions.AuthorizationException: User [default] does not have the Writable Access to the Namespace [admin].\n\tat 
`
How can I get permission? Thanks!

**Comment by yqwang-ms** [comment]
Specify your username to be admin.

Please check our doc:
https://github.com/Microsoft/pai/blob/master/subprojects/frameworklauncher/yarn/doc/USERMANUAL.md#common-request-headers
https://github.com/Microsoft/pai/blob/master/subprojects/frameworklauncher/yarn/doc/USERMANUAL.md#delete-framework

**Comment by 111Moderato** [comment]
Excuse me, do you have any examples?
I tried to use `curl -X delete 'http://master-ip:9086/v1/Frameworks/admin~caffe-mnist' {UserName}~admin `, but it seems that I misunderstood it.  @yqwang-ms

**Comment by yqwang-ms** [comment]
Please check:
https://github.com/Microsoft/pai/blob/master/subprojects/frameworklauncher/yarn/doc/USERMANUAL.md#common-request-headers
https://stackoverflow.com/questions/356705/how-to-send-a-header-using-a-http-request-through-a-curl-call

**Comment by yqwang-ms** [comment]
`curl -H "UserName: admin" -X DELETE http://master-ip:9086/v1/Frameworks/admin~caffe-mnist`

**Comment by 111Moderato** [comment]
@yqwang-ms Thank u !
