### ISSUE TITLE
Add PAI job url in restserver getjob response

### ISSUE THREAD

**Issue by yds05** [Microsoft/pai#2315]
**Organization Name**:  Microsoft NNI team.

**Short summary about the issue/question**:
Currently, PAI rest server only returns Yarn job url in "appTrackingUrl" field. However, in NNI's scenario, Yarn job url is not meaningful for user. We would like to show PAI job url to user, like http://{REST_SERVER}//view.html?username={USER_NAME}&jobName={JOB_NAME}

**Comment by scarlett2018** [comment]
As restful verbs defined, rest-server should better return the created object for a 'create/update' operation.

Now the submit job api POST /api/v1/user/:username/jobs returns:

{
  "message": "update job $jobName successfully"
}
====
from #1629

**Comment by Gerhut** [comment]
This is definitely different with #1629 

In RESTful #1629 requests that when the job controller received a `POST` or `PUT` request, the response should contains the resource it just created, following a `Location` header which point to it, which is follow the RESTful standard.

This issue requests adding a new field to the job resource, which is the web portal page URL of the job. This will cause the rest server depends on the web portal, at least it's config.

**Comment by scarlett2018** [comment]
@yds05 - can NNI follow #1629's request instead of the proposal in this issue? cc @Gerhut

**Comment by yds05** [comment]
@scarlett2018, I dont think #1629 is the same requirement with this one #2315. Returning job object is not enough for this requirement, that means client side (like NNI) need to construct their own PAI job URL based on a hard-coded format.

**Comment by Gerhut** [comment]
Hi @yds05 ,

Just synced with @sterowang. Currently we decide not to provide the web portal integration support with third-party services, nor make URL schema of web portal as stable protocols. If third-party services need to integrate with the web portal, they could generate the web portal URL by themselves, and use it at own risk.

**Comment by scarlett2018** [comment]
closed as won't fix as the team decision for current stage.
