### ISSUE TITLE
dev-box is not carrying the corresponding code, as the image tag indicated

### ISSUE THREAD

**Issue by hao1939** [microsoft/pai#2325]
dev-box:v0.10.1 was supposed to carry the code of release v0.10.1.

The currently implementation is not right:
1. dev-box has a defalut 'CMD'
`CMD ["/usr/local/start-script.sh"]`

2. The script would checkout the `latest release`, now is `v0.9.1`, which is not expected.
`TAG=$(curl --silent "https://api.github.com/repos/microsoft/pai/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/') && git checkout $TAG`

3. For the dev-box:v0.8.3, it would checkout `v0.9.1`, it's not right too.

I manually updated the dev-box:v0.8.3 and devbox:v0.9.1, pushed to dockerhub.

**Comment by mzmssg** [comment]
Should it be added to release process?

**Comment by hao1939** [comment]
I think so, before we fix the issue.

**Comment by fanyangCS** [comment]
included in release process.
