### ISSUE TITLE
Job support tags, job list support filter by tag.

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#2331]
tags provide more user flexitiblity for user and teams.

**merging** #1796 How could I mark a job? For example tag a job with a label '1 gpu', '100g', 'distributed'. 
@hao1939 's ask: When do experiments, user will change some setting and submit a new job.
For example, increase GPUs count, increase memory, edit scripts.

But there is no way to track the difference.
Could tag works?

**Comment by fanyangCS** [comment]
closed and tracked in #2226.
