### ISSUE TITLE
A complete story about VC bonus, (Per) job preemption choice

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#2340]
we had a very initial support for bonus and preemption since v0.9.0 release in #2147. 

- Rest support is not convience, we need have either commandline, or config file, or web ui support for the setting up.
- The feature need to be well documented as an end to end user story, which covers how admin use this, and how user can benift from it, and what's the need-to-knows.
- The feature did not have a good control on which jobs gonna be killed, we need to have a clear rule to kill jobs instead of killing job randomly. 
- If Job preemption is disabled, users should get alert on VC capacity over thredshold. 

**Test Case**
![image](https://user-images.githubusercontent.com/39592018/54965124-1fea6380-4faa-11e9-8d62-6448cb776314.png)

**Comment by scarlett2018** [comment]
![image](https://user-images.githubusercontent.com/39592018/54965124-1fea6380-4faa-11e9-8d62-6448cb776314.png)

**Comment by fanyangCS** [comment]
We use HiveD to support this.
