### ISSUE TITLE
Increase the maximum number of completed applications RM keeps.

### ISSUE THREAD

**Issue by mzmssg** [microsoft/pai#2348]
**What would you like to be added**:

Increase the maximum number of completed applications RM keeps.

**Why is this needed**:

Currently RM only keeps 1000 application, which is inconvenient for job retrieval

**Without this feature, how does the current module work**：

Find log address from launcher

**Components that may involve changes**:

resource manager `yarn.resourcemanager.max-completed-applications`.
2.9 default value is 10000, but the newest version lower it to 1000 in https://issues.apache.org/jira/browse/YARN-4464, which said 10000 might take RM 20mins to recover.

**Comment by fanyangCS** [comment]
maybe to retrieve the log from launcher directly?

**Comment by yqwang-ms** [comment]
But that need to parse launcher log.
For long term we can resolve this by Launcher history service.

**Comment by fanyangCS** [comment]
@yqwang-ms , how difficult is it to parse the log?
If it is just simple regex, we can do that. 
History service is to keep the long term job data. 
This issue is about the retrieve newer job information that is available in launcher.

**Comment by yqwang-ms** [comment]
It should be just simple regex. But please parse the log directly through local disk, instead of calling Launcher log API to get logs.

**Comment by yqwang-ms** [comment]
Or a more simple apporach is leverage current HDFS folder structure to get the app id, such as

![image](https://user-images.githubusercontent.com/32826762/54588831-f340c400-4a5e-11e9-9964-e883a04e05a7.png)

**Comment by fanyangCS** [comment]
closed. We remove hadoop after v0.15.
