### ISSUE TITLE
Is there a recommended server configuration?

### ISSUE THREAD

**Issue by 111Moderato** [microsoft/pai#2359]
Hi，
        Recently, I deployed OpenPAI on two hosts, which seems to be the lowest configuration requirement according to the instructions in **hardware resource requirements**, so submitting job is a bit tied (resource constrained). 
 1. Now I want to deploy the server cluster. Do you have the recommended configuration? For example, memory, GPU, CPU, etc. I didn't find any relevant information in the community.

In the process of submitting tasks, it is found that each task occupies two or more CPU cores, one of which is said to be used to schedule resources.Once the task is increased, the CPU is obviously not enough. In the process of submitting tasks, it is found that each task occupies two or more CPU cores, one of which is said to be used to schedule resources.Once the task is increased, the CPU is obviously not enough.

2. When I query docker documents, I see that fewer CPU resources can be allocated to containers, such as 0.5 CPUs. Can PAI do the same?

3. I can see various resource loads of different nodes on a page (represented by solid circles of different colors), but how can I know the exact amount of resources I can still use when submitting a task?

By the way, my main need is in the inference phase.

**Comment by fanyangCS** [comment]
for resource requirement, please refer to https://github.com/Microsoft/pai/wiki/Resource-Requirement.

OpenPAI does not support 0.5 CPU.  

For resource usage, you can go the master_ip/yarn page to find out more details.
