### ISSUE TITLE
The retry of job

### ISSUE THREAD

**Issue by hellocandy** [Microsoft/pai#2360]
**Organization Name**: advantech

**Short summary about the issue/question**: We submit several job to the openpai, and the job config is of the same, however, some of the job will retry. Some job retried for one time, and some retied for 4 times. The retryCount of job config is 0. 
At the Tracking Page, i found the follwing log:
[WARNING] Failed to request info from webhdfs, sleep 20 s ...
Using default tag: latest
latest: Pulling from loretoparisi/darknet
Digest: sha256:b5f4e0860fb21216e7dfea7d0e9d7aefba341a2d54f040b152be6ceabddb8c26
Status: Image is up to date for loretoparisi/darknet:latest
/pai/bootstrap/docker_bootstrap.sh: line 49: hadoop: command not found

**Brief what process you are following**: Why is the retry occur? What is the max retry count? Where can i find the retry log at Tracking Page？ 

**How to reproduce it**:

**OpenPAI Environment**: 
- OpenPAI version: 0.8.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by yqwang-ms** [comment]
https://github.com/Microsoft/pai/blob/master/subprojects/frameworklauncher/yarn/doc/USERMANUAL.md#retrypolicy

PAI enables FancyRetryPolicy, so it will always retry for tranisent failure.

We can refine above into https://github.com/Microsoft/pai/blob/master/docs/job_tutorial.md
