### ISSUE TITLE
add machine to kubernetes

### ISSUE THREAD

**Issue by qzwlinux** [Microsoft/pai#2366]
**Organization Name**:

**Short summary about the issue/question**:

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by scarlett2018** [comment]
@qzwlinux - I'm closing this issue seems you had created another duplicate one: #2369
