### ISSUE TITLE
How many jobs can be run simultaneously

### ISSUE THREAD

**Issue by hellocandy** [Microsoft/pai#2376]
**Organization Name**: Advantech

**Short summary about the issue/question**: We submit job to openpai simultaneously, in theory 22 job can be running at the same time, however only 10 jobs running at the same time.
The job consumes 4G Mem and 1CPU. We have 2 woker nodes, each node have 46G mem and 32 CPU. How to calculate the count of jobs that can be running at the same time? And in what condition will the job change from waiting to runing?

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**: Cluster, one master and two worker node.
- OpenPAI version: 0.8.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.): 46Mem/32Cpu for each worker node.
- Others:

**Anything else we need to know**:

**Comment by hellocandy** [comment]
I found that when submit one job, two container will be created, and then the job consume double of the resources. For example, the job use 1 CPU and 4G Mem, while the actual resource used is 2CPU and 8G Mem.

**Comment by mzmssg** [comment]
@hellocandy 
Not double, just additional 1 cpu and 4G memory. That's because our scheduler is based on YARN, which need an extra container to manager jobs. So a job with `m` CPU, `n`G Mem actually consumes `m+1` CPU ,`n+4`G memory. 
BTW, we reduce the overhead to 1 CPU and 1G memory in #2072

**Comment by hellocandy** [comment]
Is it possible to reduce the memory used by YARN for each job？ The job apply for 1 CPU and 1G memory， while the YRAN consumes mush more than the job.

**Comment by mzmssg** [comment]
`1G` is the minimum scheduling granularity. So 1 CPU and 1G memory are the minumum overhead in current architecture.

**Comment by hellocandy** [comment]
How to config the YARN to consume 1 CPU and 1G memory?

**Comment by hellocandy** [comment]
I find a strange phenomenon，I submit job that consume 1 CPU and 8G memory, and 12 job can be run at the same time , while this is above our total resource (92G). How to explain this phenomenon?

**Comment by mzmssg** [comment]
@hellocandy 
It's PAI configuraion, please upgrade to 0.10.
For the `running` status, please refer to #2022, we also refined them in 0.10, in which there should be some jobs showing `waiting`.

**Comment by hellocandy** [comment]
I submit job that consume 1 CPU and 8G memory again, and 13 job can be run at the same time , while this is above our total resource (92G). How to explain this phenomenon?

**Comment by fanyangCS** [comment]
Some of running jobs are actually waiting in queue. We fix the job state issue in 0.11.y

**Comment by hellocandy** [comment]
The YARN for each job consumes 1G Memory at 0.10, but it seems still too high. Why the limit is 1G ? We want to reduce the memory of YARN to 512M, and we can modify the source code of openPAI to 512M. Is there any possible problem if we modify the resource of YARN as 512M？

**Comment by mzmssg** [comment]
@hellocandy 
Of course it's possible, but we think the stability is the highest priority. We have tested 1G and it works fine for most distributed workloads. But 512M may not.
