### ISSUE TITLE
多个节点的hostname一致时，将只能命中一台主机

### ISSUE THREAD

**Issue by 784134748** [Microsoft/pai#2377]
result_stdout, result_stderr = pai_common.ssh_shell_paramiko_with_result(
            host_config,
            "hostname")
        m["hostname"] = result_stdout.strip()
获取的hostname如果一致时
machine-list:
  - hostname: ubuntu
    hostip: 10.20.37.175
    machine-type: GENERIC
    k8s-role: master
    etcdid: etcdid1
    zkid: "1"
    dashboard: "true"
    pai-master: "true"
  - hostname: ubuntu
    hostip: 10.20.94.51
    machine-type: GENERIC
    k8s-role: worker
    pai-worker: "true"
  - hostname: ubuntu
    hostip: 10.20.41.233
    machine-type: GENERIC
    k8s-role: worker
    pai-worker: "true"

        for role in ["proxy", "master", "worker"]:
            if "{0}-list".format(role) not in com["kubernetes"]:
                continue

            for hostname in com["kubernetes"]["{0}-list".format(role)]:
                node_config = com["machine"]["machine-list"][hostname]
                self.logger.info("Begin to deploy k8s on host {0}, the node role is [ {1} ]".format(node_config["hostip"], role))
                self.prepare_package(node_config, "{0}-deployment".format(role))
                self.job_executer(node_config, "{0}-deployment".format(role))

                if self.clean_flag == True:
                    self.logger.info(" package cleaner is working on the folder of {0}!".format(node_config["hostip"]))
                    self.delete_packege(node_config)
                    self.logger.info(" package cleaner's work finished! ")

                    self.logger.info(" remote host cleaner is working on the host of {0}!".format(node_config["hostip"]))
                    self.remote_host_cleaner(node_config, "{0}-deployment".format("proxy"))
                    self.logger.info(" remote host cleaning job finished! ")
以上这段代码将只能选中其中一台主机的ip

**Comment by scarlett2018** [comment]
@784134748 您能按着Create Issue的Template把信息再丰富一下吗？谢谢。

**Issue Template**
Organization Name: 

Short summary about the issue/question: 
Brief what process you are following:

How to reproduce it:

OpenPAI Environment: Cluster, one master and two worker node.

OpenPAI version: 
Cloud provider or hardware configuration:
OS (e.g. from /etc/os-release):
Kernel (e.g. uname -a):
Hardware (e.g. core number, memory size, storage size, GPU type etc.): 
Others:
Anything else we need to know:

**Comment by scarlett2018** [comment]
@fanyangCS - is this behavior by design or a bug?

**Comment by abuccts** [comment]
`hostname` should be unique to identify the host in a network. It's by design.

**Comment by scarlett2018** [comment]
@abuccts - do we have any validate and warning logic for duplicate hostname cases? if not, would it help to provide that so that users understand this by design behavior.
