### ISSUE TITLE
Failed task is no longer highlighted

### ISSUE THREAD

**Issue by mzmssg** [Microsoft/pai#2378]
**Organization Name**:

Microsoft

**Short summary about the issue/question**:
In new job detail page, failed task is no longer highlighted, then user can't glance over task status.
![image](https://user-images.githubusercontent.com/11887940/54801456-f11a7780-4ca1-11e9-9c47-85ddf73e9ff7.png)

This is old page:
![image](https://user-images.githubusercontent.com/11887940/54801710-2a071c00-4ca3-11e9-8599-9a78a5ef8527.png)

**Brief what process you are following**:

**OpenPAI Environment**:
- OpenPAI version: v0.11

**Comment by fanyangCS** [comment]
there should have been a container state field to replace the "exit code", indicating whether it fails or succeeds.

**Comment by sunqinzheng** [comment]
#2382

**Comment by scarlett2018** [comment]
Closing as dup, will track in #2382
