### ISSUE TITLE
hadoop-resource-manager-ds Liveness probe failed

### ISSUE THREAD

**Issue by qzwlinux** [Microsoft/pai#2383]
**Organization Name**:

**Short summary about the issue/question**:

集群部署完成后hadoop-resource-manager-ds出现问题
**Brief what process you are following**:
集群已经搭建完成   可以新建job但无法打开job详细页面
Liveness probe failed: HTTP probe failed with statuscode: 404
Back-off restarting failed container
![image](https://user-images.githubusercontent.com/46511491/54862459-41fba000-4d76-11e9-9217-fc9484b90b36.png)

<!--deployment related issues
Please fill this for deployment related issues:
- Operating type: Initial deployment 

**OpenPAI Environment**:
- OpenPAI version:v0.11.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):ubuntu 16.04
- Kernel (e.g. `uname -a`): 4.4.0-131-generic
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
    master:62G mem    2 cpu
    node1: 48G mem    2cpu    4 TitanX GPU
   node2:48G  mem    2cpu     4 Tesla K80
- Others:

**Comment by mzmssg** [comment]
> 可以新建job但无法打开job详细页面

job详细页面是指哪个，另外请提供集群的版本

**Comment by qzwlinux** [comment]
> > 可以新建job但无法打开job详细页面
> 
> job详细页面是指哪个，另外请提供集群的版本


![image](https://user-images.githubusercontent.com/46511491/54890232-60cb7500-4ee3-11e9-8953-16d81cc56578.png)
就是MarketPlace中创建的job不能点开job项目，但是自己创建的任务可以打开
版本是v0.11.0




目前由于问题没有解决，使用了v0.9.1

v0.9.1版本中Hardware无法显示，其他功能正常
![image](https://user-images.githubusercontent.com/46511491/54890314-b99b0d80-4ee3-11e9-9818-ba9d2d701cf2.png)

**Comment by mzmssg** [comment]
@qzwlinux 
Does liveness probe failure exist in v0.9.1? If not, we could rename this issue.

**Comment by qzwlinux** [comment]
不好意思  跨版本提问了  可以删除这篇文章

**Comment by qzwlinux** [comment]
> @qzwlinux
> Does liveness probe failure exist in v0.9.1? If not, we could rename this issue more appropriate.

不好意思 跨版本提问了 可以删除这篇文章

**Comment by mzmssg** [comment]
Feel free to reopen it
