### ISSUE TITLE
 the node information on dashboad.html  auto disappear during 24 hours after reboot.

### ISSUE THREAD

**Issue by lvyufeng** [Microsoft/pai#2384]
**Organization Name**: Chongqing University

**Short summary about the issue/question**: the node information on dashboad.html  auto disappear during 24 hours after reboot.
![Screenshot from 2019-03-23 23-39-23](https://user-images.githubusercontent.com/12846585/54868196-04723380-4dc5-11e9-88cb-1ac4827420f8.png)
![Screenshot from 2019-03-23 23-39-10](https://user-images.githubusercontent.com/12846585/54868197-04723380-4dc5-11e9-83e3-a63480708775.png)
![Screenshot from 2019-03-23 23-38-57](https://user-images.githubusercontent.com/12846585/54868198-050aca00-4dc5-11e9-8989-73ab0d49608f.png)

**Brief what process you are following**: acturall i didn't do anything.

**How to reproduce it**: for this situation, i already tried the new version 0.10.y, and when webportal service started, the page did not show any information even for the first visit.
i'll show the screen shots.

**OpenPAI Environment**:
- OpenPAI version:0.9.y
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): ubuntu16.04(kylin actually, because the Gigabyte X299 motherboad only support this version)
- Kernel (e.g. `uname -a`): 4.14.0-041400-generic (update manual)
- Hardware (e.g. core number, memory size, storage size, GPU type etc.): 16cores, 64g mem, 4T + 512SSD, 2 geforce1080ti
- Others:

**Anything else we need to know**:
maybe the service interface have some bugs? the hadoop page shows the right info, and i can still start new jobs. Futhermore, i use the single-node configuration, and reduce the hadoop file
'nodemanager-start-service.sh' mem from 40 to 20. i dont know whether it cause this problem.

`then
    echo "Node role is 'Worker'. Reserve 16G for os and k8s."
    let mem_reserved=16*1024
else
    echo "Node role is 'Master & Worker'. Reserve 40G for os and k8s."
    let mem_reserved=20*1024
fi
`

**Comment by zhuqian187** [comment]
I observe U have used gtx 1080ti, which pai version do you use, v0.9.0? while i use v0.9.0, on gtx 1080ti I found all the drivers docker can not work during installation. which version of drivers have U used! Thank you, wait for U reply.

**Comment by lvyufeng** [comment]
> I observe U have used gtx 1080ti, which pai version do you use, v0.9.0? while i use v0.9.0, on gtx 1080ti I found all the drivers docker can not work during installation. which version of drivers have U used! Thank you, wait for U reply.

I use the 0.9.y branch, you can check this issue [https://github.com/Microsoft/pai/issues/666](issue 666)
and also use this command first to get the logs.
`kubectl logs drivers-name`
And you can get drivers' pod name in this way.
`kubectl get pod | grep "drivers"`

it seems that the kernel version of linux and whether you block the `nouveau` are the main reason cause those failure.

**Comment by zhuqian187** [comment]
> > I observe U have used gtx 1080ti, which pai version do you use, v0.9.0? while i use v0.9.0, on gtx 1080ti I found all the drivers docker can not work during installation. which version of drivers have U used! Thank you, wait for U reply.
> 
> I use the 0.9.y branch, you can check this issue [issues/666](https://github.com/Microsoft/pai/issues/666)
> and also use this command first to get the logs.
> `kubectl logs drivers-name`
> And you can get drivers' pod name in this way.
> `kubectl get pod | grep "drivers"`
> 
> it seems that the kernel version of linux and whether you block the `nouveau` are the main reason cause those failure.

how many rack do you have? only one plays master and worker ? if is, i guess you can invoke one master, a vm can play also(PS: master mem master more than 40G).

**Comment by xudifsd** [comment]
@lvyufeng can you list all pai services? `kubectl get pod`

**Comment by lvyufeng** [comment]
> @lvyufeng can you list all pai services? `kubectl get pod`
It seems that the “batch-job-Hadoop” auto finish after 25 hours.
I’ve already change the configuration from 20g to 40g, but don’t have any effect.
![DD75D587-81DD-4AA4-BC27-ED5E395C8380](https://user-images.githubusercontent.com/12846585/54984950-e423be00-4fea-11e9-955c-0c84f87331a3.png)

**Comment by xudifsd** [comment]
Seems services are running normally.

I'm not sure I understand what you meant by auto disappear, since you have rebooted. You meant you have reboot the master node and node info disappeared, or it still exist after the reboot but disappeared later?

Could you check the log of job-exporter and node-exporter? `kubectl logs -l app=job-exporter` and `kubectl logs -l app=node-exporter`?

**Comment by lvyufeng** [comment]
> Seems services are running normally.
> 
> I'm not sure I understand what you meant by auto disappear, since you have rebooted. You meant you have reboot the master node and node info disappeared, or it still exist after the reboot but disappeared later?
> 
> Could you check the log of job-exporter and node-exporter? `kubectl logs -l app=job-exporter` and `kubectl logs -l app=node-exporter`?

once I reboot the machine, it will start all services and work normally, and 24h later, the information disappeared.

**Comment by lvyufeng** [comment]
> Seems services are running normally.
> 
> I'm not sure I understand what you meant by auto disappear, since you have rebooted. You meant you have reboot the master node and node info disappeared, or it still exist after the reboot but disappeared later?
> 
> Could you check the log of job-exporter and node-exporter? `kubectl logs -l app=job-exporter` and `kubectl logs -l app=node-exporter`?

`kubectl logs -l app=job-exporter` shows:
![QQ20190326-185956](https://user-images.githubusercontent.com/12846585/54992134-7cc13a80-4ff9-11e9-91d7-2e561140dd48.png)
`kubectl logs -l app=node-exporter` shows:
![QQ20190326-185957](https://user-images.githubusercontent.com/12846585/54992149-8b0f5680-4ff9-11e9-8bbe-443ff099f3e2.png)

**Comment by xudifsd** [comment]
@lvyufeng seems normal.

You can visit your master node's 9091 port, it's the default port listen by prometheus, you can try some of the query like `configured_gpu_count` and `node_load1` to see if prometheus scrapped data from job-exporter and node-exporter, more metrics you can tried listed [here](https://github.com/Microsoft/pai/blob/master/docs/alerting/exporter-metrics.md).

If no data displayed you can check the status->service discovery and click "show more" besides "pai_serivce_exporter" to check if these service was discovered by prometheus. Prometheus uses [this](https://github.com/Microsoft/pai/blob/master/src/prometheus/deploy/prometheus-configmap.yaml.template#L45) mechanism to discover services in k8s, you can have some check.

**Comment by lvyufeng** [comment]
@xudifsd i cannot understand those logs, please check it.
by the way, i find the ip of container address use 172.xx.xx.xxx, and our university also use this net segment. did this cause the problem? 
[Prometheus Time Series Collection and Processing Server.pdf](https://github.com/Microsoft/pai/files/3016965/Prometheus.Time.Series.Collection.and.Processing.Server.pdf)

**Comment by xudifsd** [comment]
Seems prometheus can discover them. Can you check if you can connect to node-exporter and job-exporter in prometheus container?

**Comment by lvyufeng** [comment]
@xudifsd Maybe prometheus container break, i uese `sudo docker exec -it 4e6c0f7d0705 /bin/bash` to enter the container, and get some errors as below:
`OCI runtime exec failed: exec failed: container_linux.go:344: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown
`

**Comment by xudifsd** [comment]
prometheus container do not have bash, you need to use sh

**Comment by lvyufeng** [comment]
> prometheus container do not have bash, you need to use sh

@xudifsd  use `sudo docker exec -it 4b79abd02ca8 /bin/sh` also get this error
 `OCI runtime exec failed: exec failed: container_linux.go:344: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory": unknown
`

**Comment by xudifsd** [comment]
`sudo docker exec -it $container_id sh`

**Comment by lvyufeng** [comment]
@xudifsd I'm sorry that i have no idea of connecting to node-exporter and job-exporter. use the `ping` command or other operate? it seems these container share the same ip address.

**Comment by xudifsd** [comment]
then, can you restart the prometheus/job-exporter/node-exporter?

```
./paictl.py service stop -n prometheus
./paictl.py service start -n prometheus
./paictl.py service stop -n job-exporter
./paictl.py service start -n job-exporter
./paictl.py service stop -n node-exporter
./paictl.py service start -n node-exporter
```

These operation will not affect the job current running or job submission.

**Comment by lvyufeng** [comment]
@xudifsd I try these command，but nothing changed. that look like a magic.......other function did not have any problem, even dashboard always show 0 node.

**Comment by xudifsd** [comment]
I also have no idea why you met this problem, please read prometheus doc about how it works and debug yourself. It's too slow to replay like this.

Next possible steps:

* check prometheus log `kubectl logs -l app=prometheus`
* check if you can visit node-exporter url directly like `$IP:9100/metrics`, from node where prometheus deployed and from prometheus container

**Comment by lvyufeng** [comment]
@xudifsd fortunately, I found the reason, the server time not be synchronized, Prometheus shows the warning `Warning! Detected 6417.97 seconds time difference between your browser and the server. Prometheus relies on accurate time and time drift might cause unexpected query results.
`
