### ISSUE TITLE
The code_dir storage error log is not consistent with size

### ISSUE THREAD

**Issue by debuggy** [Microsoft/pai#2387]
**Organization Name**:
microsoft

**Short summary about the issue/question**:

When User code_dir_size is 0. There will be an error log says that dir is larger than 200MB.
```
[INFO] User code_dir_size is 0
hdfs://10.0.0.4:9000/qinsu/qinsu-test2_04320b0b is larger than 200MB, exit.
```
The related bug location:
https://github.com/Microsoft/pai/blob/0f80208482eade027af88c61b4d58b78bf39b57a/src/rest-server/src/templates/yarnContainerScript.mustache#L262

**Comment by fanyangCS** [comment]
https://github.com/Microsoft/pai/pull/2388
