### ISSUE TITLE
Confusing status jump: A running Job is converting to "waiting" before converting to "succeeded"

### ISSUE THREAD

**Issue by mzmssg** [microsoft/pai#2389]
**Organization Name**:
Microsoft

**Short summary about the issue/question**:
Current job state convertion might be `waiting` -> `running` -> `waiting` -> `succeeded`, but idealy it should be `waiting` -> `running` -> `succeeded`.

**OpenPAI Environment**:
- OpenPAI version: master

**Comment by scarlett2018** [comment]
Cannot differenciate "waiting for resource allocation" vs. "waiting for launcher processing".

**Comment by yqwang-ms** [comment]
This is resolved in microsoft/frameworkcontroller#35 (so will also be in Pure K8S PAI soon).
