### ISSUE TITLE
potential security vulnerability

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#2396]
![image](https://user-images.githubusercontent.com/39592018/54965651-7193ed80-4fac-11e9-9c88-5fd176641914.png)

**Comment by Gerhut** [comment]
Currently we have no [src/rest-server/package-lock.json](https://github.com/Microsoft/pai/blob/master/src/rest-server/package-lock.json) and we are using [morgan 1.9.1](https://github.com/Microsoft/pai/blob/master/src/rest-server/yarn.lock#L1970) now

**Comment by fanyangCS** [comment]
deployed a bot to fix vulnerability automatically.
