### ISSUE TITLE
Refine Home Page for Admin Experience

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#2404]
1. scenario (node -> job list)
we had a quick implementation for this requirement in the coming release 0.11.0, will provide more information in the release node. stay tuned.

_Originally posted by @scarlett2018 in https://github.com/Microsoft/pai/issues/2074#issuecomment-476537417_

2. to be added

**Comment by Binyang2014** [comment]
![sample](https://user-images.githubusercontent.com/9415966/62021408-ae415100-b1f9-11e9-8145-f4b490be5b43.png)
Attach the node status page
