### ISSUE TITLE
About Resource Requirement

### ISSUE THREAD

**Issue by 111Moderato** [Microsoft/pai#2411]
In the Page:https://github.com/Microsoft/pai/wiki/Resource-Requirement

default | Daemon Sets | drivers | 0.25 | 2 | N/A | N/A | Burstable | Worker & Worker
-- | -- | -- | -- | -- | -- | -- | -- | --

What is the Worker & Worker?

**Comment by mzmssg** [comment]
Fixed, thanks for report.
