### ISSUE TITLE
Confusion about Resource-Requirement

### ISSUE THREAD

**Issue by 111Moderato** [microsoft/pai#2414]
In the Page:https://github.com/Microsoft/pai/wiki/Resource-Requirement

It said: 　

For cluster installation, each **PAI-Worker** reserve 16G memory for OS and K8S, memory for user jobs is total_mem - 16g.

According to the Master/Worker column in the table, the worker's memory requirement is about 5.5G?

Most of the items in the table are memory requirements of the master. How much memory does the master actually save for OS and k8s?

Is this 16G just a requirement for K8S and os? Does it exclude the need for openpai services?

**Comment by squirrelsc** [comment]
@hao1939 Hao, would you help on updating this wiki page? Thanks.

**Comment by hao1939** [comment]
Here's case:

Total = Reserved + User
Reserved = os + k8s + pai + safe gap.

**Comment by 111Moderato** [comment]
@hao1939 Is Master and worker Reserved the same size? Thanks！

**Comment by hao1939** [comment]
No, master node is fully reserved for os + k8s + PAI.
