### ISSUE TITLE
integrate dev-box into k8s

### ISSUE THREAD

**Issue by squirrelsc** [microsoft/pai#2415]
**Organization Name**:

**Short summary about the issue/question**: 

After initiating setup, OpenPAI can create a pod for this deployment, and use for futher maintanence.

Pros,
1. The deployment can be shared among admins
1. it can be reset to init state to get clean enviornment.
1. user can connect to the maintenance box in web UI of k8s.

**Comment by scarlett2018** [comment]
Adding @hao1939 .

@squirrelsc - May you explain what's the drawbacks of not having this (today)? thanks.

**Comment by squirrelsc** [comment]
See pros in bug, and I found there are documents to ask user to setup the dev-box manually. And as my experience, some documents are incomplete, and hard to setup correctly.

https://github.com/Microsoft/pai/blob/master/docs/paictl/paictl-manual.md#manage-cluster-configuration-

**Comment by hao1939** [comment]
Per my understanding, our goal is to make the dev-box stateless and one-off.
Seems the proposal is against the design, not sure we are going to support.

**Comment by squirrelsc** [comment]
> Per my understanding, our goal is to make the dev-box stateless and one-off.
> Seems the proposal is against the design, not sure we are going to support.

It's still stateless, the pod can be deleted any time.

**Comment by hao1939** [comment]
What's point of keeping a stateless pod? If it's stateless indeed.

**Comment by squirrelsc** [comment]
I'm just saying it can be stateless. Check above points about pros of this pod.

**Comment by hao1939** [comment]
I see, that's against the design.

> The deployment can be shared among admins
The dev-box is design to be one-off.

> it can be reset to init state to get clean enviornment.
one-off, so no need to reset.

> user can connect to the maintenance box in web UI of k8s.
Dev-box may be used to maintain K8S, the k8s UI may be not available.

**Comment by fanyangCS** [comment]
I do not suggest to deploy dev-box in the k8s cluster, messing up with user workload. admin should provide a machine to host the dev-box.

**Comment by squirrelsc** [comment]
> I do not suggest to deploy dev-box in the k8s cluster, messing up with user workload. admin should provide a machine to host the dev-box.

It can be stick to master node, so it wouldn't impact user workload. It's very useful for admin, and reducing documentation about how to create such a box.
