### ISSUE TITLE
How to deploy PAI behind a proxy

### ISSUE THREAD

**Issue by Breath123** [Microsoft/pai#2422]
**Organization Name**: Individual

**Short summary about the issue/question**: Seems there is no configuration that support to deploy PAI behind a proxy.

**Brief what process you are following**: I followed the guide of "Deploy OpenPAI"[https://github.com/Microsoft/pai#deploy-openpai] to deploy PAI.

 The guide of "Deploy OpenPAI"[https://github.com/Microsoft/pai#deploy-openpai]

**How to reproduce it**:

**OpenPAI Environment**: 3 Ubuntu host servers behind company's proxy. 
- OpenPAI version: latest with pai-v0.10.y branch
- Cloud provider or hardware configuration: NA
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.): 40 cpu core and 1 Tesla V100 GPU of each host
- Others:

**Anything else we need to know**:

**Comment by fanyangCS** [comment]
OpenPAI should be able to work if you expose pylon to external networks.

**Comment by Breath123** [comment]
Hello fanyangCS,
@fanyangCS Thanks for your reply and I jump to the document of [pylon](https://github.com/Microsoft/pai/blob/3adbcddada8fa95844e065843f4ed3009edac967/docs/pylon/README.md) followed by your suggestion. According to the document, the solution is "to deploy Pylon instances on these jump machines as a reverse proxy". Unfortunately, we can't access to that jump machines, and usually, we set the proxy-related env as "export http_proxy=proxy_ip:proxy_port; export https_proxy=proxy_ip:proxy_port;" to connect to the outside world.
So, do you have any suggestions about how to deploy behind a proxy when we can't deploy Pylon on jump machines?
Many thanks.

**Comment by fanyangCS** [comment]
I am not sure I understand your requirements. 

You want to deploy OpenPAI to an internal environment, and you would like to access it from outside?

Or you want the job on the OpenPAI platform to access external network?

**Comment by Breath123** [comment]
@fanyangCS , I want to deploy OpenPAI to an internal environment and access it from internal. But deploy OpenPAI need to access the internet like install some software, pull docker images, and so on. The only way to access the internet in our internal environment is through the specified proxy. 
Thus, the requirement is to deploy OpenPAI behind a proxy which allows internal hosts access to the internet.
As I know, this kind of proxy affects the configuration of k8s, and some k8s deployment tools like kubespray need to fill this kind of proxy in configuration files.

**Comment by fanyangCS** [comment]
In this case, you can deploy OpenPAI from a local docker registry, where you need to move the public docker images to the docker registry. here is a related issue. you don't have to build the images by your own though. https://github.com/Microsoft/pai/issues/1225

**Comment by Breath123** [comment]
Thank you, I'll try it.
