### ISSUE TITLE
Regression: Duration of a running job is missing 

### ISSUE THREAD

**Issue by scarlett2018** [Microsoft/pai#2423]
In v0.11.0 pai-prod-1 bed, verifying to be released 0.11, found this regression.

In Previous versions, running job will set the current running times as duration before job complete:
![image](https://user-images.githubusercontent.com/39592018/55064776-84461980-50b5-11e9-89e6-75396722d2d3.png)

In the build, duration is set to **N/A**
![image](https://user-images.githubusercontent.com/39592018/55064816-9a53da00-50b5-11e9-8452-1b0127eb78e1.png)

**Comment by sunqinzheng** [comment]
fixed in #2436 #2437
