### ISSUE TITLE
when bootup k8s-cluster, it says kubelet has been installed, but 8080 was refused, crash

### ISSUE THREAD

**Issue by nirvanacc** [Microsoft/pai#2432]
**Short summary about the issue/question**:
I am bootup k8s-cluster, master and worker has been deployed
In the dev-box container, i think it execute 'kubectl get node' to check cluster, then it says 8080 was refused.
I make sure the apiserver at master is not created, so i execute 'docker ps -a' at master, there is only a 'hyperkube' container.
And the images for apiserver,manager-controller,etc. are not pulled.
This occurs when I use docker registrt by docker.io and private registry at local.

**Comment by nirvanacc** [comment]
root@master:~# docker ps -a
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS                   PORTS               NAMES
d22a22fe910b        openpai/pause-amd64:3.0    "/pause"                 5 minutes ago       Up 5 minutes                                 k8s_POD_etcd-server-172.21.81.100_default_b4c084f83e34030c1a842add54009c1a_0
165fb978f258        openpai/pause-amd64:3.0    "/pause"                 5 minutes ago       Up 5 minutes                                 k8s_POD_kube-scheduler-172.21.81.100_kube-system_10ed8ec571f64ad7e4c4af69711b0c1e_0
3abd6021075a        openpai/pause-amd64:3.0    "/pause"                 5 minutes ago       Up 5 minutes                                 k8s_POD_kube-controller-manager-172.21.81.100_kube-system_364814e9f35e71c02fdb634189713e60_0
48df905fe6fd        openpai/pause-amd64:3.0    "/pause"                 5 minutes ago       Up 5 minutes                                 k8s_POD_kube-apiserver-172.21.81.100_kube-system_384a1d35d8499ceb28490c5028bae083_0
ac717ac3f263        openpai/hyperkube:v1.9.9   "/hyperkube kubelet …"   5 minutes ago       Up 5 minutes                                 kubelet
248c8f14fe48        registry                   "/entrypoint.sh /etc…"   3 hours ago         Up 22 minutes                                registry

**Comment by fanyangCS** [comment]
please do not run dev-box in the master node. you have to run it outside the OpenPAI bed.

**Comment by ydye** [comment]
What's the api server version? Can you try to manually pull this image?

**Comment by ydye** [comment]
No response for a long time, I will close this issue.
I believe the issue is caused by resource requirement, and setting the flag to close the resource requirement will solve it.
