### ISSUE TITLE
upgrade regression of v0.10.1

### ISSUE THREAD

**Issue by squirrelsc** [Microsoft/pai#2433]
Below commit is hit twice in upgrading, it should be fixed in v0.10
https://github.com/Microsoft/pai/commit/c275ca684bbefa84ed2ee718a9996ebddc10ad7f

**Comment by mzmssg** [comment]
Add #2434

**Comment by scarlett2018** [comment]
This item is marked as a known issue on v0.10.1, a hotfix will be provided by @mzmssg , @scarlett2018  will update the v0.10.1 release note with the hotfix accordingly. And the formal fix has been merged to v0.11.

**Comment by mzmssg** [comment]
I will submit a hotfix #2441 to `pai-0.10.y`, then user could apply these patches with `git fetch; git checkout pai-0.11.y`
