### ISSUE TITLE
Use framework name as job name in REST server / web portal.

### ISSUE THREAD

**Issue by Gerhut** [microsoft/pai#2439]
Since enabling ACL in framework launcher, the _framework name_ in framework launcher are prepended the user name to avoid the naming confliction, looks like `user~job`. For backward compatibility, user-faced services like REST server & web portal chose to hide these details to user, still returns & shows _job name_, w/o user name prepended. As more services, plugins & third-party tools integrate to rest server/web portal, the difference between _job name_ (without the username, `job`) and _framework name_ (with the username, `user~job`) causes confusing and extra workload. To clarify, the meaning of _job name_ terminology will be changed to the same as _framework name_, which is prepended username, looks like `user~job`, and still provided the backward compatibility of the _job name_ without the username.

**Comment by Gerhut** [comment]
Ping @xudifsd @yqwang-ms to see if any concerns

**Comment by xudifsd** [comment]
LGTM

**Comment by yqwang-ms** [comment]
LGTM
