### ISSUE TITLE
HDFS error message is not accurate.

### ISSUE THREAD

**Issue by squirrelsc** [Microsoft/pai#2440]
**Short summary about the issue/question**:

As below code, if there is HDFS error, it will print error message, "Can not get code from HDFS. HDFS may be down". But the error may be caused by malformat file name. The error message misleads user in this case. It's better to print original error message.

https://github.com/Microsoft/pai/blob/master/src/rest-server/src/templates/yarnContainerScript.mustache#L264

**Comment by abuccts** [comment]
The original error message is in `stderr` instead of `stdout`.

**Comment by scarlett2018** [comment]
@yqwang-ms - shall we cover this type of issue in the status Epic?

**Comment by yqwang-ms** [comment]
Yep, we plan to cover this by Phase 3.
![image](https://user-images.githubusercontent.com/32826762/55313396-3e64c900-549a-11e9-9fc0-9c9e606dc936.png)

**Comment by squirrelsc** [comment]
It's a code error, can be fixed quickly. And the #2326 is a high level design. Suggest to deal with them separately.

**Comment by yqwang-ms** [comment]
If so, @mzmssg to fix it.

**Comment by mzmssg** [comment]
The error message should be in stderr, we shouldn't reprint the same errors in both stdout and stderr.

**Comment by yqwang-ms** [comment]
@mzmssg 

The point seems that "Can not get code from HDFS. **HDFS may be down**" may mislead user.

Please breakdown the error to be more detailed, such as HDFS file not found, etc.
If you feel hard in current stage, please just remove "HDFS may be down", and expose the orignal HDFS client exception message.

**Comment by scarlett2018** [comment]
@mzmssg how about we make the following 2 changes:
* Change the message to a more generic message: "Failed to copy data from HDFS."
* Full error logs should be print out in both stdout and stderr.

**Comment by mzmssg** [comment]
@scarlett2018 
Change 1 is acceptable, but Change 2 will make `stderr` meaningless.

**Comment by scarlett2018** [comment]
@mzmssg - so your proposal is only print to stderr? I'm fine with this as well. Do you think this 2 changes can be make in End April Release?

**Comment by mzmssg** [comment]
#2464, of course it would be better if we seperate service log from the stdout and stderr in the furtue
