### ISSUE TITLE
Mismatch between driver and kernel version

### ISSUE THREAD

**Issue by mzmssg** [microsoft/pai#2446]
**Organization Name**:
Microsoft

**Short summary about the issue/question**:
Both 0.11 and 0.10 have this error.

Error log:
![image](https://user-images.githubusercontent.com/11887940/55207489-4c55e800-5215-11e9-8f55-dad708e19133.png)

**OpenPAI Environment**:
- OpenPAI version: v0.11, v0.10

Reference: https://devtalk.nvidia.com/default/topic/1046451/linux/linux-4-4-168-and-nvidia-linux-x86_64-410-93-and-get_user_pages-/

**Comment by mzmssg** [comment]
It might be a linux kernel and driver mismatch, `4.4.0-143-generic` version have it. 
Error log:
```
   In file included from /root/drivers/NVIDIA-Linux-x86_64-384.111/kernel/common/inc/nv-linux.h:21:0,
                    from /root/drivers/NVIDIA-Linux-x86_64-384.111/kernel/nvidia/os-mlock.c:15:
   /root/drivers/NVIDIA-Linux-x86_64-384.111/kernel/common/inc/nv-mm.h:44:9: error: too many arguments to function 'get_user_pages'
            get_user_pages(current, current->mm, start, nr_pages, write, force, pages, vmas)

```

**Comment by mzmssg** [comment]
We provide a dogfood image for this issue, please hardcode the image `docker.io/openpai/drivers-418.30:v0.11.0` here:
https://github.com/Microsoft/pai/blob/c0703488e06eadffae47b2386b2806fc59a79f49/src/drivers/deploy/drivers.yaml.template#L35 with

**Comment by Chenyangzh** [comment]
hello, I also meet this error right now!

Follows are my coditions:
one master with no gpus and one worker with teslav100
pai-version: v0.12.0
nvidia-driver-version: 410.73
worker-node-kernel: 4.18.0-17-generic
worker-node-os: Ubuntu-18.04-lst

I also tried to change the kernel version to 4.18.0-15-generic and to use the driver with version of 418.30, but both of them are not work.
By the way, I once successfully deployed pai by using these conditions without any linux-kernel errors. Right now, I am trying to clear old settings and repeat to deploy it but meet this type of error.

Any one can help? THX

**Comment by fanyangCS** [comment]
@ydye , have you met @Chenyangzh 's problem?

**Comment by Chenyangzh** [comment]
Hi @fanyangCS, thanks for your reply. I solved the problem by forbidding the dkms installation of nvidia driver~

**Comment by edenbuaa** [comment]
@Chenyangzh Could you told us how to disable dkms installation?

**Comment by Chenyangzh** [comment]
> @Chenyangzh Could you tell us how to disable dkms installation?

Hi @edenbuaa, I followed these steps:
1. Open the nvidia-driver docker image which is downloaded from docker-hub.
2. You may defaultly get into the path of '~/drivers' and can find a file named 'install-nvidia-drivers'
3. Edit that script by adding an tag '--dkms' following the nvidia-driver install line (begin with line 74)
4. Store and commit the changed docker image to replace the origin nvidia-docker image. 
5. Restart the pai services and fix this issue!
Hope itcan help and good luck!

**Comment by edenbuaa** [comment]
@Chenyangzh thanks. The install script of 470.73 has this '--dkms' tag defaultly, and I think this option allows to install by dkms, how to disable it?
