### ISSUE TITLE
CPU usage is unexpected high

### ISSUE THREAD

**Issue by ddebby** [microsoft/pai#2450]
**Organization Name**:

**Short summary about the issue/question**:
I have depolyed an all-in-one OpenPAI (version 0.9.1) in a big size VM with 16 vcpu and 64GB memory. After everything is ready, the CPU load is unexpected high, all the vcpu with a 100% usage:
![123](https://user-images.githubusercontent.com/7961354/55211827-9dbba280-5228-11e9-977c-a1a154e91c74.png)

**Brief what process you are following**:
I have tried to scale up the VM from 16 vcups to 64 vcups. There seems no improvement:
![31](https://user-images.githubusercontent.com/7961354/55211919-ec693c80-5228-11e9-99f9-a2f15acc2c55.png)

 

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version: 0.9.1
- Cloud provider or hardware configuration: VM 
- OS (e.g. from /etc/os-release): Ubuntu 16.04

- Kernel (e.g. `uname -a`): Linux all-in-one-k8s 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Hardware (e.g. core number, memory size, storage size, GPU type etc.): 64vcpu/64GB 
- Others:

**Anything else we need to know**:

**Comment by hao1939** [comment]
Hi @ddebby ,

Could you 'top' the process taking up the CPU?

**Comment by ddebby** [comment]
> Hi @ddebby ,
> 
> Could you 'top' the process taking up the CPU?
```bash
ps aux | sort -nrk 3,3 | head -n 5
root     20677  688  0.1 2453424 72616 ?       Ssl  13:01 579:42 /tmp/docker -c /tmp/k.conf
root     25435  675  0.1 2453424 69876 ?       Ssl  13:01 565:04 /tmp/docker -c /tmp/k.conf
root     46676  658  0.1 2453424 65988 ?       Ssl  13:04 533:46 /tmp/docker -c /tmp/k.conf
root     44000  654  0.1 2453424 69468 ?       Ssl  13:03 532:36 /tmp/docker -c /tmp/k.conf
root      2766  420  0.1 2453424 67280 ?       Ssl  14:01 100:16 /tmp/docker -c /tmp/k.conf
```

**Comment by hao1939** [comment]
Hi @ddebby ,

Seems you are running other processes on the node.

**Comment by ddebby** [comment]
> Hi @ddebby ,
> 
> Seems you are running other processes on the node.

The only processes here on this VM is openpai. When I delete the cluster by `sudo python paictl.py cluster k8s-clean -p ~/pai-config/`, all the cpu load will down to nearly zero.

**Comment by fanyangCS** [comment]
have you resolved the issue?

**Comment by fanyangCS** [comment]
closed as no further response.
