### ISSUE TITLE
Runtime enviroment check

### ISSUE THREAD

**Issue by mzmssg** [microsoft/pai#2454]
**What would you like to be added**:

Runtime check host environment, such as kernel version or docker status.

**Why is this needed**:

One case is linux kernel upgrade, then drivers might be incompatible, PAI need to raise it at runtime.

**Without this feature, how does the current module work**:
service might down and no enough error information.

**Components that may involve changes**:
Not sure

**Comment by fanyangCS** [comment]
it is done in the precheck during deployment
