### ISSUE TITLE
P1 - Will need a unified framework to do integration test in jenkins

### ISSUE THREAD

**Issue by xudifsd** [microsoft/pai#2455]
There are more and more integration test fail found during the release process, we will need to define more test cases to be ran during jenkins integration test, for example #2447 case can be written in script, and can be found before merge.

Before adding test cases, I think we may need to define a framework to make it easy to define and run integration test cases. i.e. set an standard environment, how to do tear down, etc.

**Comment by fanyangCS** [comment]
deferred to pure k8s version.

**Comment by abuccts** [comment]
In #4035, Jenkins test scripts have been moved from host to `tests/jenkins/` path in repo.
More CI test cases could be added in [stage_test.sh](https://github.com/microsoft/pai/blob/master/tests/jenkins/stage_test.sh) file easily in the future.

**Comment by fanyangCS** [comment]
https://github.com/microsoft/pai/issues/4119
