### ISSUE TITLE
enable hdfs automatic rebalance

### ISSUE THREAD

**Issue by squirrelsc** [microsoft/pai#2462]
**What would you like to be added**:
Trigger hdfs rebalance periodically, so that no false alert is triggered.

**Why is this needed**:
It looks hdfs rebalance is not enabled by default on OpenPAI. So admin needs to rebalance disk usage to resolve alerts and prevent potential service issue.

**Without this feature, how does the current module work**:
Admin have to trigger rebalance manually.

**Components that may involve changes**:

**Comment by fanyangCS** [comment]
@squirrelsc , if it can be done automatically, why hdfs didn't do that?

**Comment by squirrelsc** [comment]
> @squirrelsc , if it can be done automatically, why hdfs didn't do that? things might be a bit more trickier than expected.

hdfs as a platform, it cannot predict usage of system, so rebalancer should be decided by admin of hdfs. But for OpenPAI ops, if they receive alerts since unbalanced node, and need to balance it manually each time. Why not make it automatically?

**Comment by fanyangCS** [comment]
if you clearly defines the conditions to trigger unbalance, yes can we can do that.

**Comment by squirrelsc** [comment]
To avoid unnecessary alerts, it can be set to lower than bar of alerts by default, for example, 80% trigger rebalance, and 90% triggers alert. And it should be configurable, so that user can change both rebalance and alerts bar.

**Comment by fanyangCS** [comment]
the alert may not be triggered by unbalance.

**Comment by squirrelsc** [comment]
The goal is to avoid alerts, when rebalance can reduce disk space usage. The alert will be triggered when rebalance doesn't fix disk space pressure, it's expected alert. Admin has to fix it manually.

**Comment by fanyangCS** [comment]
Not supported.
