### ISSUE TITLE
Regression: "Retry link" to yarn application attempts is missing

### ISSUE THREAD

**Issue by scarlett2018** [Microsoft/pai#2466]
**Retry Link** in Previous versions:
![image](https://user-images.githubusercontent.com/39592018/55371566-3dcb4180-5531-11e9-9790-d51567e52997.png)
the link will link to a yarn cluster with all the previous attempts log: http://host/yarn/10.1.0.4:8088/cluster

![image](https://user-images.githubusercontent.com/39592018/55371625-7539ee00-5531-11e9-8297-c598ab5ff016.png)

in v0.11.0 detail page, the link is missing:
![image](https://user-images.githubusercontent.com/39592018/55371661-926ebc80-5531-11e9-9a74-574c478ed612.png)

**Comment by scarlett2018** [comment]
@mzmssg - please list this as known issue of v0.11.0, this is currently planned to Mid April Release.

**Comment by mzmssg** [comment]
added
