### ISSUE TITLE
Some shell command consumes much time, then job is regarded as no response.

### ISSUE THREAD

**Issue by mzmssg** [microsoft/pai#2469]
**Organization Name**:
Microsoft

**Short summary about the issue/question**:
Some runtime command consumes 10+ secs, then container is timeout.
![image](https://user-images.githubusercontent.com/11887940/55374745-2c3b6700-553c-11e9-88d8-970f64bfb1ed.png)

**How to reproduce it**:
Not sure

**OpenPAI Environment**:
- OpenPAI version: 0.10, 0.11

**Comment by mzmssg** [comment]
#2468 is a mitigation, still investigating.

**Comment by fanyangCS** [comment]
Please see if the disk is under heavy load.

**Comment by mzmssg** [comment]
@fanyangCS 
Yeah, it's the most possibility, another possibility is docker cpu limit. Will do some test.

**Comment by mzmssg** [comment]
The most possibility:
It's the user process that used up IO, processes may hang for secs or even mins. Then runtime monitor mechanism failed and container suicide.

**Comment by fanyangCS** [comment]
close as it has been addressed by new PAI runtime.
