### ISSUE TITLE
Alerts: CPU usage alerts shouldn't be triggered when user load is high

### ISSUE THREAD

**Issue by squirrelsc** [microsoft/pai#2471]
**What would you like to be added**:
CPU usage alert only triggers when OpenPAI service is in high workload.

**Why is this needed**:
There are a lot of CPU alerts triggered by user usage. It's expected on a computing platform, and shouldn't trigger alerts.

**Without this feature, how does the current module work**:
If CPU is in high usage, there are alerts triggered. Admin have to investigate with extra effort or ignore them but ignore real alerts also.

**Comment by fanyangCS** [comment]
close and track in #2472
