### ISSUE TITLE
PS can't exit automatically，when distributed.（当任务完成时，ps job不能退出，一直在运行）

### ISSUE THREAD

**Issue by fusimeng** [microsoft/pai#2496]
我用你们提供的分布式（TensorFlow）示例，但是worker节点运行完毕，但是ps 节点不能正常退出，模型也已保存。
![image](https://user-images.githubusercontent.com/33896958/55446282-8cd8ab80-55f1-11e9-9899-4fbc4ffe7873.png)
进入ps容器后，查看进程，如下：
![image](https://user-images.githubusercontent.com/33896958/55446316-b09bf180-55f1-11e9-9638-a0388cb26a98.png)

**Comment by scarlett2018** [comment]
@fusimeng thanks for raising the questions. Could you please follow the issue template and provide more information for us as reference? thank.s

------------Issue Template------------
Organization Name:

Short summary about the issue/question:

Brief what process you are following:

How to reproduce it:

OpenPAI Environment:

OpenPAI version:
Cloud provider or hardware configuration:
OS (e.g. from /etc/os-release):
Kernel (e.g. uname -a):
Hardware (e.g. core number, memory size, storage size, GPU type etc.):
Others:
Anything else we need to know:

**Comment by abuccts** [comment]
@fusimeng What's your job configuration?

**Comment by fusimeng** [comment]
@scarlett2018  
 ------------Issue ------------  
1、Organization Name:北京思腾合力（sitonholy）

2、Short summary about the issue/question:
PS can't exit automatically，when distributed.（当任务完成时，ps job不能退出，一直在运行）

3、Brief what process you are following:
Distributed TensorFlow CIFAR-10 image classification，URL：https://github.com/Microsoft/pai/tree/master/examples/tensorflow#distributed-tensorflow-cifar-10-image-classification

4、How to reproduce it:  
重新运行，第3步的例子，

5、OpenPAI Environment:

6、 OpenPAI version:
v0.10.1

7、OS (e.g. from /etc/os-release):
> Kernel (e.g. uname -a):
    Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-131-generic x86_64)
> Hardware (e.g. core number, memory size, storage size, GPU type etc.):
master：32core，mem（31GB），storage（445GB-SSD），
node1:48core，mem（62GB）,storage(4T-HDD),GPU(k80 * 4)
node2:48core，mem（62GB）,storage(4T-HDD),GPU(p40 * 4)
node3:48core，mem（62GB）,storage(4T-HDD),GPU(1080ti * 4)
> Anything else we need to know:
上面已经
![image](https://user-images.githubusercontent.com/33896958/55469290-ca602780-5637-11e9-854a-4cec5164dd8b.png)
![image](https://user-images.githubusercontent.com/33896958/55469321-d8ae4380-5637-11e9-8168-5ea4070ab7b2.png)
![image](https://user-images.githubusercontent.com/33896958/55469355-f24f8b00-5637-11e9-8677-a9399a61b9a6.png)
![image](https://user-images.githubusercontent.com/33896958/55469382-fe3b4d00-5637-11e9-97f2-466eb58da2b8.png)

**Comment by fanyangCS** [comment]
Please share us you job json file.

**Comment by abuccts** [comment]
Closed due to lack of response, please feel free to reopen if you have any questions.

**Comment by scarlett2018** [comment]
@fanyangCS @abuccts - @fusimeng mentioned in his comment, he is using our example. 

> Brief what process you are following:
> Distributed TensorFlow CIFAR-10 image classification，URL：https://github.com/Microsoft/pai/tree/master/examples/tensorflow#distributed-tensorflow-cifar-10-image-classification
> 
> 4、How to reproduce it:
> 重新运行，第3步的例子，

**Comment by abuccts** [comment]
According to the snapshot which shows 1 ps server and 2 works, the config is different from example.

**Comment by abuccts** [comment]
Closed, please feel free to reopen if you have additional questions.
