### ISSUE TITLE
How to upload the cluster configuration

### ISSUE THREAD

**Issue by edenbuaa** [Microsoft/pai#2502]
**How to reproduce it**:
- run dev-box docker 
- Prepare Configuration by default
- deploy Kubernetes with paictl
- update cluster configuration into Kubernetes 

when I try to execute 'python paictl.py config push -c ~/.kube/config' ,the logs show as follows:
[INFO] - deployment.paiLibrary.common.kubernetes_handler : Couldn't find configmap named pai-external-storage-conf
 [ERROR] - deployment.confStorage.external_version_control.external_config : Unable to get the external storage configuration from k8s cluster.
 [ERROR] - deployment.confStorage.external_version_control.external_config : Please check the configmap named [pai-external-storage] in the namespace [default]

**OpenPAI Environment**:
- OpenPAI version: v0.11.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): ubuntu16.04
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

what should i do? thanks

**Comment by edenbuaa** [comment]
found the solution, close it.

**Comment by wunaner** [comment]
Hi，I meet the same question, can you tell me how to fix the problem?
