### ISSUE TITLE
[AuthN] Login With AAD, and keep basic login solution.

### ISSUE THREAD

**Issue by ydye** [microsoft/pai#2504]
### ```Feature Target```

When deploying OpenPAI, admin could chose Azure Active Directory (AAD) OIDC as the authentication solution for the cluster. And once the Azure Active Directory is chosen, the basic login (Account name && Password) solution will be disabled.

###  ```Relative Module```
rest-server
webportal

### ```Process Overview```

![image](https://user-images.githubusercontent.com/8675883/55547784-9c94e480-5704-11e9-8ef9-bfae12510d38.png)

### ```Reference```
Azure Active Directory: https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-whatis

**Comment by fanyangCS** [comment]
done.
