### ISSUE TITLE
基于hadoop-run集成hive时遇到的小坑

### ISSUE THREAD

**Issue by 784134748** [Microsoft/pai#2506]
hadoop-run镜像中

ENV HADOOP_VERSION=hadoop-2.9.0

将导致基于该镜像集成hive组件出现以下异常
Unable to determine Hadoop version information.

见hive启动脚本中，要求HADOOP_VERSION格式必须为“2.9.0”
  hadoop_version_re="^([[:digit:]]+)\.([[:digit:]]+)(\.([[:digit:]]+))?.*$"
  
  if [[ "$HADOOP_VERSION" =~ $hadoop_version_re ]]; then
      hadoop_major_ver=${BASH_REMATCH[1]}
      hadoop_minor_ver=${BASH_REMATCH[2]}
      hadoop_patch_ver=${BASH_REMATCH[4]}
  else
      echo "Unable to determine Hadoop version information."
      echo "'hadoop version' returned:"
      echo `$HADOOP version`
      exit 5
  fi
提醒后来者，此处有坑！

**Comment by fanyangCS** [comment]
thanks for reporting this. closing the issue.
