### ISSUE TITLE
Add nfs plugin with dev-box error

### ISSUE THREAD

**Issue by qzwlinux** [microsoft/pai#2509]
**Organization Name**:
SitonHoly Technology

**Short summary about the issue/question**:
Add nfs plugin with dev-box error
**Brief what process you are following**:
1. i use the course [Simplified-Job-Submission-for-OpenPAI-with-NFS-deployment](https://github.com/Microsoft/pai/wiki/Simplified-Job-Submission-for-OpenPAI-with-NFS-deployment)
2.i  installed k8s-bootup finish
![image](https://user-images.githubusercontent.com/46511491/55695582-cc393a80-59eb-11e9-8f2b-21657c71dcb0.png)

2. when i run this command，it was error
![image](https://user-images.githubusercontent.com/46511491/55695091-98f5ac00-59e9-11e9-9766-686ac7784e7c.png)
3. then i add a argument ,but it still error
![image](https://user-images.githubusercontent.com/46511491/55695525-841a1800-59eb-11e9-843f-03d020755a88.png)

**How to reproduce it**:
1. In dev-box
2. finish k8s-bootup
3.root@openpai:/pai/contrib/storage_plugin# python storagectl.py server set teamA nfs 192.168.31.107 /raid/nfs --sharedfolders data --privatefolders users

**OpenPAI Environment**:
OpenPAI version: v0.11.0
Cloud provider or hardware configuration:DGX-Station
OS :ubuntu:18.04
Kernel : 4.4.0-31-generic
Hardware :
     core number:40
     memory size:251G
     storage size, Tesla V100*4

**Comment by scarlett2018** [comment]
@wangdian - could you please help? thanks.

**Comment by wangdian** [comment]
Hi @qzwlinux:
This error may because the storage-user has no content.
The storage data should be created, but since no user, the folder on target machine was not created. You can just ignore the error and continue to create storage user data.
```
python storagectl.py user setdefault <your user name> teamA
```
We will fix this in our next version.

**Comment by qzwlinux** [comment]
@wangdian thanks ,i will try it

**Comment by scarlett2018** [comment]
@wangdian - would you like to add this to Mid-April release (code freeze at 4/12)?

**Comment by wangdian** [comment]
> @wangdian - would you like to add this to Mid-April release (code freeze at 4/12)?
Yes, I will add the test case to PR.
