### ISSUE TITLE
PAI upload local data investigation

### ISSUE THREAD

**Issue by debuggy** [microsoft/pai#2519]
Investigation of how to enable user upload local data to native HDFS.

- 2 OS: windows, linux
- 4 solutions
  - [winutils](https://github.com/steveloughran/winutils)
  - webhdfs
  - libhdfs
  - libhdfs3

solution |  os                     | features 
--------- | ---                     |   ----
winutil    | windows           |  .exe file
libhdfs    | windows, linux  | needs install hadoop in local machine
webhdfs | windows, linux  | rest api has size limit
libhdfs3  | linux                  | only support linux

**Comment by sotetsuk** [comment]
Just FYI. As a linux user, I'm currently using one of
- webhdfs or
- `scp` to a running container and then `cp` to mounted HDFS
