### ISSUE TITLE
Job List Status filter should list all the status

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#2535]
Version: 0.11.0
Env: PAI INT Bed
Context: Currently, Status filter only list the active status, but not all the status. 
![image](https://user-images.githubusercontent.com/39592018/55925948-ef5d2780-5c41-11e9-95f9-ae9df4d7becd.png)

Problem and how to reproduce:
1. when there are no "waiting" jobs;
2. submit a new job, the job will be in waiting status;
3. select waiting in the status, and go into the waiting job's detail page; 
4. Back to Jobs list once the job turns to Running.
Will hit a type error:
![image](https://user-images.githubusercontent.com/39592018/55926076-7e6a3f80-5c42-11e9-8859-0e5da3d02e60.png)
And then the list view is empty, with no status selection:
![image](https://user-images.githubusercontent.com/39592018/55926107-a063c200-5c42-11e9-8e03-de6830ed1c9a.png)

**Comment by Gerhut** [comment]
Hi @scarlett2018 , @sterowang , @fanyangCS

I plan to retrieve the filter choices (users / VCs) from rest-server directly (`/api/v1/user`) (`/api/v1/virtual-clusters`) instead of aggregating from job lise currently, to resolve these filtering issues (no content without any filter choice selected). However, currently the user listing API is limited to admin only, can we remove this limitation to implement this refinement?

**Comment by scarlett2018** [comment]
> Hi @scarlett2018 , @sterowang , @fanyangCS
> 
> I plan to retrieve the filter choices (users / VCs) from rest-server directly (`/api/v1/user`) (`/api/v1/virtual-clusters`) instead of collecting from job list, to resolve these filtering issues (no content without any filter choice selected). However, currently the user listing API is limited to admin only, can we remove this limitation to implement this refinement?

@Gerhut
The current webportal supports non-admin user to get the user list, the RESTful API is not, this is an inconsist behaviour. Which I think worth to make them consist. 

From a longer term perspective, I would expect **reading user list** is a right that can be managed by user permission auth component. But for the short term perspective, I think it's fine to open the Restful API to make it behave the same as WebPortal today.
