### ISSUE TITLE
Refine Home UI Part II - User (not Admin user) home page

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#2539]
Homepage for user 
- Job status
- My virtual clusters
- Available GPU nodes
- My recent jobs: Create / Tutorial (first time login)

![PAI-Home-1](https://user-images.githubusercontent.com/44491713/55927539-fd15ab80-5c47-11e9-9010-bb1df3bd9824.png)
![PAI-Home-2](https://user-images.githubusercontent.com/44491713/55927543-01da5f80-5c48-11e9-9f76-9b9630c62e49.png)

**Comment by abuccts** [comment]
Merged in #2614,
