### ISSUE TITLE
VC permission management

### ISSUE THREAD

**Issue by hao1939** [microsoft/pai#2545]
Goal:
Limit who can access or manager specific VCs.

My thought:
It's a typical authorization problem: Does `somebody` has permission to `act` on `target`?
Three inputs and one output.

Design:
A most popular pattern is `role based authorization`.
Briefly with two mapping:

1. User/Group -> Role: mapping user/group to role.
2. Role -> Permission: mapping what the role is capable of.

APIs needed:
Notice: the item 1 and 2 are mandatory, 3 is optional.

1. authorization api: yes/no = (user/group + act + target)?.
2. CRUD for `User/Group -> Role`.
3. CRUD for `Role -> Permission`.

**Comment by debuggy** [comment]
not in this release

**Comment by fanyangCS** [comment]
it is done in v0.16
