### ISSUE TITLE
distributed TensorFlow job always failed

### ISSUE THREAD

**Issue by edenbuaa** [Microsoft/pai#2547]
**Short summary about the issue/question**:
run a distributed job by following the instructions at https://github.com/Microsoft/pai/blob/master/docs/job_tutorial.md#a-deep-learning-job-example-  ,but I always get failed.

**How to reproduce it**:
### the job json is:
{
  "jobName": "tensorflow-distributed-cifar10",
  "image": "openpai/pai.run.tensorflow",
  "authFile": "",
  "dataDir": "$PAI_DEFAULT_FS_URI/data",
  "outputDir": "$PAI_DEFAULT_FS_URI/output",
  "codeDir": "$PAI_DEFAULT_FS_URI/code/tf_cnn_benchmarks",
  "virtualCluster": "default",
  "retryCount": 0,
  "taskRoles": [
    {
      "name": "ps_server",
      "taskNumber": 2,
      "cpuNumber": 2,
      "memoryMB": 8192,
      "gpuNumber": 0,
      "command": "pip --quiet install scipy && python /code/tf_cnn_benchmarks/tf_cnn_benchmarks.py --local_parameter_device=cpu --batch_size=$batch_size --model=$job_model --variable_update=parameter_server --data_dir=$PAI_DATA_DIR --data_name=cifar10 --train_dir=$PAI_OUTPUT_DIR --ps_hosts=$PAI_TASK_ROLE_ps_server_HOST_LIST --worker_hosts=$PAI_TASK_ROLE_worker_HOST_LIST --job_name=ps --task_index=$PAI_CURRENT_TASK_ROLE_CURRENT_TASK_INDEX",
      "portList": [
        {
          "label": "http",
          "beginAt": 0,
          "portNumber": 1
        },
        {
          "label": "ssh",
          "beginAt": 0,
          "portNumber": 1
        }
      ]
    },
    {
      "name": "worker",
      "taskNumber": 2,
      "cpuNumber": 2,
      "memoryMB": 16384,
      "gpuNumber": 2,
      "minSucceededTaskCount": 2,
      "command": "pip --quiet install scipy && python /code/tf_cnn_benchmarks/tf_cnn_benchmarks.py --local_parameter_device=cpu --batch_size=$batch_size --model=$job_model --variable_update=parameter_server --data_dir=$PAI_DATA_DIR --data_name=cifar10 --train_dir=$PAI_OUTPUT_DIR --ps_hosts=$PAI_TASK_ROLE_ps_server_HOST_LIST --worker_hosts=$PAI_TASK_ROLE_worker_HOST_LIST --job_name=worker --task_index=$PAI_CURRENT_TASK_ROLE_CURRENT_TASK_INDEX",
      "portList": [
        {
          "label": "http",
          "beginAt": 0,
          "portNumber": 1
        },
        {
          "label": "ssh",
          "beginAt": 0,
          "portNumber": 1
        }
      ]
    }
  ],
  "jobEnvs": {
    "batch_size": 32,
    "job_model": "resnet20"
  },
  "extras": {}
}

### The application summary as follows:

[ExitStatus]: LAUNCHER_EXIT_STATUS_UNDEFINED
[ExitCode]: 177
[ExitDiagnostics]:
ExitStatus undefined in Launcher, maybe UserApplication itself failed.
[ExitType]: UNKNOWN
________________________________________________________________________________________________________________________________________________________________________________________________________
[ExitCustomizedDiagnostics]:
<Raw>[ExitCode]: 2
<Raw>[ExitDiagnostics]:
[2019-04-12 06:22:55.343]Exception from container-launch: 
ExitCodeException exitCode=2: YarnContainerScripts/1.sh: line 58: [: -gt: unary operator expected

	at org.apache.hadoop.util.Shell.runCommand(Shell.java:998)
	at org.apache.hadoop.util.Shell.run(Shell.java:884)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:1216)
	at org.apache.hadoop.yarn.server.nodemanager.DockerContainerExecutor.launchContainer(DockerContainerExecutor.java:312)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.launchContainer(ContainerLaunch.java:443)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:294)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:92)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[DEBUG] Performing clean up action...
[DEBUG] Write exit code 2 to file /var/lib/hadoopdata/nm-local-dir/nmPrivate/application_1554866214738_0057/container_1554866214738_0057_01_000002/container_1554866214738_0057_01_000002.pid.exitcode.
[2019-04-12 06:22:55.343]
[2019-04-12 06:22:55.346]Container exited with a non-zero exit code 2. Last 4096 bytes of stderr :
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100  6160  100  6160    0     0  1236k      0 --:--:-- --:--:-- --:--:-- 1236k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 13122  100 13122    0     0  1853k      0 --:--:-- --:--:-- --:--:-- 1853k
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.

[2019-04-12 06:22:55.347]
[2019-04-12 06:22:55.347]Container exited with a non-zero exit code 2. Last 4096 bytes of stderr :
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100  6160  100  6160    0     0  1236k      0 --:--:-- --:--:-- --:--:-- 1236k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 13122  100 13122    0     0  1853k      0 --:--:-- --:--:-- --:--:-- 1853k
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.

[2019-04-12 06:22:55.347]

________________________________________________________________________________________________________________________________________________________________________________________________________
<Raw>[ExitCustomizedDiagnostics]:

[worker]: [LastCompletedTask]: [TaskStatus]:
{
  "taskIndex" : 0,
  "taskRoleName" : "worker",
  "taskState" : "TASK_COMPLETED",
  "taskRetryPolicyState" : {
    "retriedCount" : 0,
    "succeededRetriedCount" : 0,
    "transientNormalRetriedCount" : 0,
    "transientConflictRetriedCount" : 0,
    "nonTransientRetriedCount" : 0,
    "unKnownRetriedCount" : 0
  },
  "taskCreatedTimestamp" : 1555049840231,
  "taskCompletedTimestamp" : 1555050175678,
  "taskServiceStatus" : {
    "serviceVersion" : 0
  },
  "containerId" : "container_1554866214738_0057_01_000002",
  "containerHost" : "10.10.47.4",
  "containerIp" : "10.10.47.4",
  "containerPorts" : "http:29435;ssh:29436;",
  "containerGpus" : 3,
  "containerLogHttpAddress" : "http://10.10.47.4:8042/node/containerlogs/container_1554866214738_0057_01_000002/admin/",
  "containerConnectionLostCount" : 0,
  "containerIsDecommissioning" : null,
  "containerLaunchedTimestamp" : 1555049841998,
  "containerCompletedTimestamp" : 1555050175674,
  "containerExitCode" : 2,
  "containerExitDiagnostics" : "[2019-04-12 06:22:55.343]Exception from container-launch: \nExitCodeException exitCode=2: YarnContainerScripts/1.sh: line 58: [: -gt: unary operator expected\n\n\tat org.apache.hadoop.util.Shell.runCommand(Shell.java:998)\n\tat org.apache.hadoop.util.Shell.run(Shell.java:884)\n\tat org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:1216)\n\tat org.apache.hadoop.yarn.server.nodemanager.DockerContainerExecutor.launchContainer(DockerContainerExecutor.java:312)\n\tat org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.launchContainer(ContainerLaunch.java:443)\n\tat org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:294)\n\tat org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:92)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n\n[DEBUG] Performing clean up action...\n[DEBUG] Write exit code 2 to file /var/lib/hadoopdata/nm-local-dir/nmPrivate/application_1554866214738_0057/container_1554866214738_0057_01_000002/container_1554866214738_0057_01_000002.pid.exitcode.\n[2019-04-12 06:22:55.343]\n[2019-04-12 06:22:55.346]Container exited with a non-zero exit code 2. Last 4096 bytes of stderr :\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\n\r100  6160  100  6160    0     0  1236k      0 --:--:-- --:--:-- --:--:-- 1236k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\n\r100 13122  100 13122    0     0  1853k      0 --:--:-- --:--:-- --:--:-- 1853k\nWARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.\n\n[2019-04-12 06:22:55.347]\n[2019-04-12 06:22:55.347]Container exited with a non-zero exit code 2. Last 4096 bytes of stderr :\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\n\r100  6160  100  6160    0     0  1236k      0 --:--:-- --:--:-- --:--:-- 1236k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\n\r100 13122  100 13122    0     0  1853k      0 --:--:-- --:--:-- --:--:-- 1853k\nWARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.\n\n[2019-04-12 06:22:55.347]\n",
  "containerExitType" : "UNKNOWN"
}
[worker]: [LastCompletedTask]: [ContainerLocations]:
ContainerLogHttpAddress: http://10.10.47.4:8042/node/containerlogs/container_1554866214738_0057_01_000002/admin/
ContainerLogNetworkPath: 10.10.47.4:/var/lib/yarn/userlogs/application_1554866214738_0057/container_1554866214738_0057_01_000002
ContainerCacheNetworkPath: 10.10.47.4:/var/lib/hadoopdata/nm-local-dir/usercache/admin/appcache/application_1554866214738_0057/container_1554866214738_0057_01_000002
________________________________________________________________________________________________________________________________________________________________________________________________________
[ApplicationCompletionReason]: [worker]: FailedTaskCount 1 has reached MinFailedTaskCount 1.

**OpenPAI Environment**: 
- OpenPAI version: v.0.11.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): ubuntu16.04
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Comment by edenbuaa** [comment]
any suggestion？

**Comment by abuccts** [comment]
It's failed by the job itself.
Could you please paste the `stdout` log from ContainerLogHttpAddress (http://10.10.47.4:8042/node/containerlogs/container_1554866214738_0057_01_000002/admin/ according to your exit diagnostics)?

**Comment by edenbuaa** [comment]
@abuccts the container log hangs at: 
[info] User Command Start

**Comment by edenbuaa** [comment]
@abuccts  the log in container like: 
.....
PAI_ps_server_0_http_PORT=16469
PAI_ps_server_0_ssh_PORT=16470
PAI_worker_0_http_PORT=28325
PAI_worker_0_ssh_PORT=28326
PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/hadoop/bin:/usr/local/hadoop/sbin
PWD=/root
SHLVL=1
TENSORFLOW_VERSION=1.4.0
TERM=xterm
_=/usr/bin/printenv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100   380  100   380    0     0  72643      0 --:--:-- --:--:-- --:--:-- 72643
[INFO] Webhdfs downloads file succeed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100  1678  100  1678    0     0   410k      0 --:--:-- --:--:-- --:--:--  410k
[INFO] Webhdfs downloads file succeed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
mv: cannot remove '/pai/ssh_config/config': Read-only file system
[INFO] start ssh service
 * Restarting OpenBSD Secure Shell server sshd       [80G 
[74G[ OK ]
[INFO] USER COMMAND START

**Comment by abuccts** [comment]
Seems the command hasn't been started.
@mzmssg please help to have a look.

**Comment by edenbuaa** [comment]
the issue point to the example docker image. I will submit a PR later.
close it.
