### ISSUE TITLE
New containers will run when restart the cluster

### ISSUE THREAD

**Issue by dwang55** [Microsoft/pai#2548]
**Organization Name**:

**Short summary about the issue/question**:
New containers will start when we restart the cluster. Is there any way to restart the old containers when restart the cluster?
**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version: 0.9.y
- Cloud provider or hardware configuration: hardware
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by mzmssg** [comment]
@dwang55 
Idealy, container will be restored after cluster reboot. In some case, container will be aborted.
1. Your command depended on some service, such as hdfs downloading, if you didn't handle the exception when service down, your container will fail.
2. The downtime of some service, more specifically node-manager, is over toleration, which leads containers are unmanaged, so a new container will be launched.
3. Docker daemon was restarted, it might happen when you restart kubernetes by `./paictl.py cluster k8s-clean/bootup`, that's becasue we reconfigurate some docker items, which will destory all running contaienrs.

So please give more details about your "restart", such as command and duration.

**Comment by dwang55** [comment]
Thanks for responding. Our cluster was powered off unfortunately. We found the all containers(not just node-manager) exited and new containers was running after restarting machines of the cluster. 
Is there any way to restore the containers in such case?

**Comment by mzmssg** [comment]
Nope, hardware failure won't be restored, you need to do checkpoint on remote storage, such as NFS or HDFS.

**Comment by dwang55** [comment]
Thanks for timely response, there is no need to remain this issue open anymore.
