### ISSUE TITLE
pai-v0.11.0 hardware page shows N/A for GPU and GPU mem

### ISSUE THREAD

**Issue by ICEORY** [Microsoft/pai#2553]
- Openpai v0.11.0 (upgraded from v0.9.1)
- GPU: 1080ti
- Nvidia Driver: 410.73

![image](https://user-images.githubusercontent.com/11911903/56082481-e2ac1f80-5e4b-11e9-8bab-6e608c025470.png)

maybe this issue is related to [https://github.com/Microsoft/pai/pull/2534#issue-269185384](https://github.com/Microsoft/pai/pull/2534#issue-269185384) ?

Besides, i found that the job-exporter always failed on some nodes
![image](https://user-images.githubusercontent.com/11911903/56082527-68c86600-5e4c-11e9-928d-bed16f074a3c.png)

- logs of job-exporter
```
2019-04-13 16:29:28,764 - INFO - MainThread - network.py:244 - didn't find correct network interface in this node, configured eth0,eno2, found {'lo': '127.0.0.1', 'enp129s0f0': 'xxx.xxx.xxx.xxx', 'ens4f0': 'xxx.xxx.xxx.xxx', 'docker0': '172.17.0.1'}
WARNING: No swap limit support
WARNING: No swap limit support
```

**Comment by GeoffreyChen777** [comment]
@ICEORY can you provide the output log of your job-explorer?

**Comment by xudifsd** [comment]
@ICEORY please check your job-exporter's log like @GeoffreyChen777 said, if it's the same as #2534 , let's track the issue there.

Please also note that log
```
2019-04-13 16:29:28,764 - INFO - MainThread - network.py:244 - didn't find correct network interface in this node, configured eth0,eno2, found {'lo': '127.0.0.1', 'enp129s0f0': 'xxx.xxx.xxx.xxx', 'ens4f0': 'xxx.xxx.xxx.xxx', 'docker0': '172.17.0.1'}
```

This means job-exporter can not find the the interface to listen for network traffic, which may leads to incorrect network traffic.

Current job-exporter will select one interface that can access "hub.docker.com" if configured interface not found. You can correct this by providing maybe `interface: enp129s0f0` to job-exporter config.

**Comment by ICEORY** [comment]
@xudifsd Thanks, this issue is caused by the incorrect network interface, I modify the job-exporter config and it works fine now.

**Comment by wjlzk1** [comment]
> @xudifsd谢谢，这个问题是由不正确的网络接口引起的，我修改了job-exporter配置，现在工作正常。

我想知道你怎么修改的job-exporter配置 ,是进入容器吗,修改什么文件呢,,谢谢
