### ISSUE TITLE
openpai v0.11.0 cannot view ssh info on chrome/opera

### ISSUE THREAD

**Issue by ICEORY** [Microsoft/pai#2554]
- openpai v0.11.0

- when open "view ssh info/stdour/stderr" on chrome/opera: 

![image](https://user-images.githubusercontent.com/11911903/56082651-d9bc4d80-5e4d-11e9-81f4-6a2e4cc1c0c1.png)
![image](https://user-images.githubusercontent.com/11911903/56082725-b04ff180-5e4e-11e9-9c29-616948138d2e.png)

- it works fine on firefox 
![image](https://user-images.githubusercontent.com/11911903/56082730-be9e0d80-5e4e-11e9-8327-eaae3c1eeb16.png)

**Comment by Gerhut** [comment]
Closed by #2559
