### ISSUE TITLE
PAICTL machine add doesn't add machines into service

### ISSUE THREAD

**Issue by squirrelsc** [microsoft/pai#2556]
I used below command to add machines into a cluster, but I found added machines are not in nodes view of YARN.

python paictl.py machine add -p config -l added-machines.yaml

**Comment by GeoffreyChen777** [comment]
same here.

**Comment by squirrelsc** [comment]
> same here.

@GeoffreyChen777 you need to make sure it's not in maintenance list, and then run below commands to label new machine as a worker.

python paictl.py config push -p config
python paictl.py service start -n cluster-configuration

**Comment by fanyangCS** [comment]
close as if resolved.
