### ISSUE TITLE
Regression - VC View Jobs

### ISSUE THREAD

**Issue by scarlett2018** [Microsoft/pai#2565]
v0.11.0 PAI-PROD

**How to reproduce**
1. Go to Virtual Cluster page, find a VC with utilization >0 (vc name: **be*e**), click on the View Jobs link.
2. go back to VC page;
3. select another vc whose utilization is 0 (vc name: **xi*e**, click on the view jobs link

Expectation
View jobs in the job list page

Actual
The jobs shows the previous vc's (**be*e**) job list.

![image](https://user-images.githubusercontent.com/39592018/56131274-92eb6680-5fb9-11e9-8f1c-f61bbe83dda3.png)

**Comment by Gerhut** [comment]
Will fix with #2535
