### ISSUE TITLE
Add confirm dialog for stop actions to avoid mis-operation.

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#2577]
Currently, user/admin might click on the "Stop" button by mistake when scrolling the job list or job detail page. As stop is not able to resume from the stop point, we'd better provide a confirm dialog to avoid mis-operation.

In the confirm dialog, we can also gather the reason why the user is stopping the job:
i.e. 
For users, (1) Early stop; (2) Need to change the command or config; (3) etc.
For admin, (1) stop abnormal jobs; (2) release resource for higher priority jobs; (3) system maintance; etc.

**Note**: this change should not break downstream (NNI, VS Code Client) integration logic.

**Comment by fanyangCS** [comment]
done.
