### ISSUE TITLE
Merge the SSH Infor into one command.

### ISSUE THREAD

**Issue by GeoffreyChen777** [Microsoft/pai#2580]
**What would you like to be added**: Merge the SSH Infor into one command like this:

```
# Step 1. Open a Bash shell terminal.
# Step 2: Download and use the private key to connect to the container: 
wget http://192.168.193.1/a/192.168.193.1:5070/webhdfs/v1/Container/xxx/xxx~xxx/ssh/keyFiles/geo~xxx?op=OPEN -O xxx && \
chmod 600 xxx && \
ssh -i xxx -p 25842 root@192.168.193.9
```

**Why is this needed**: Reduce the repeated copy and paste.

**Without this feature, how does the current module work**: 

```
# Step 1. Open a Bash shell terminal.
# Step 2: Download the private key:
wget http://192.168.193.1/a/192.168.193.1:5070/webhdfs/v1/Container/geo/geo~kenet-dev_61076495/ssh/keyFiles/geo~kenet-dev_61076495?op=OPEN -O geo~kenet-dev_61076495
# Step 3: Set correct permission for the key file:
chmod 600 geo~kenet-dev_61076495
# Step 4: Connect to the container:
ssh -i geo~kenet-dev_61076495 -p 25842 root@192.168.193.9
```
We need to copy three commands individually.

**Components that may involve changes**: webportal

If this is reasonable, I can raise a pull request.

**Comment by Gerhut** [comment]
Hi @GeoffreyChen777 

Thanks for your suggestion! Actually I have a similar idea too, which is *generating a shell script includes these 3 commands and ask user to download and run directly*. However I have been not sure how to make a shell script (and/or command) that give a SSH environment at the end of the execution. Moreover, compatibility with bash / zsh / fish / even PowerShell is also an important point.

If you are interested in this feature, feel free to do advise and contribute.

**Comment by sunqinzheng** [comment]
The comments startswith '#' will be ignored by shell.
You can copy the whole script into your shell directly and the three commands will be executed sequentially.

**Comment by GeoffreyChen777** [comment]
@sunqinzheng There is still a bug:

zsh can not run `wget http://192.168.193.1/a/192.168.193.1:5070/webhdfs/v1/Container/geo/geo~kenet-dev_61076495/ssh/keyFiles/geo~kenet-dev_61076495?op=OPEN -O geo~kenet-dev_61076495`
directly:

```
> wget http://192.168.193.1/a/192.168.193.1:5070/webhdfs/v1/Container/geo/geo~kenet-dev_61076495/ssh/keyFiles/geo~kenet-dev_61076495?op=OPEN -O geo~kenet-dev_61076495
> zsh: no matches found: http://192.168.193.1/a/192.168.193.1:5070/webhdfs/v1/Container/geo/geo~kenet-dev_61076495/ssh/keyFiles/geo~kenet-dev_61076495?op=OPEN
```

We need to enclose the url in quote marks like this:

```
wget "http://192.168.193.1/a/192.168.193.1:5070/webhdfs/v1/Container/geo/geo~kenet-dev_61076495/ssh/keyFiles/geo~kenet-dev_61076495?op=OPEN" -O geo~kenet-dev_61076495
```

**Comment by sunqinzheng** [comment]
I have created a new issue for the url bug. #2633 Pull request: #2634 
Thank you for reporting this bug.

P.S. You edited a wrong file. The old ejs job detail page is deprecated...

**Comment by GeoffreyChen777** [comment]
@sunqinzheng OK, I will close the wrong PR.
