### ISSUE TITLE
PAI Launcher to support Protocol V2

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#2590]
Currently, all the protocol analyze and validation logic are in RESTful Service. From a clean architecture design perspective, we should define clean contracts between RESTFul API with PAI clients, as well as contracts between Launcher with RESTFul API.

Per team discussion meeting, Launcher should be the one to understand and handle jobs. This refactor is to make current Launcher wrap with the logic to support Protocol V2.

**Comment by fanyangCS** [comment]
done. @abuccts.
