### ISSUE TITLE
Need report for  (average) GPU Efficiency

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#2597]
Need the following 2 reports:
GPU Allocation Rate = Average(`Allocated GPU/Total GPU` in a certain time slot);
GPU Utilization = Average(`GPU real usage/Total GPU capacity` in a certain time slot);

**Comment by xudifsd** [comment]
After some investigation, I found we can get average value from prometheus using query like:

```
(avg_over_time( yarn_queue_gpu_total[31d]) - avg_over_time( yarn_queue_gpu_available[31d])) / avg_over_time( yarn_queue_gpu_total[31d])
```

will give average (allocated_gpus/total_gpus) during 31 days.

And

```
avg(avg_over_time(nvidiasmi_utilization_gpu[31d]))
```

will give average real gpu utilization during 31 days.

We can put this directly in Grafana, instead of putting it in report.

**Comment by xudifsd** [comment]
@scarlett2018 I have verified that the first query should be changed to
```
sum(sum_over_time(yarn_queue_gpu_total[31d]) - sum_over_time(yarn_queue_gpu_available[31d])) / sum(sum_over_time( yarn_queue_gpu_total[31d]))
```

And second query unchanged.

**Comment by fanyangCS** [comment]
I believe this has been done. @scarlett2018 feel free to reopen it if we still have some pending issue.
