### ISSUE TITLE
关于rest-server中发送http请求获取报文被分块处理问题

### ISSUE THREAD

**Issue by damon008** [Microsoft/pai#2605]
const postData = querystring.stringify({
  'msg': '你好世界'
});

const options = {
  hostname: 'nodejs.cn',
  port: 80,
  path: '/upload',
  method: 'POST',
  headers: {
    'Content-Type': 'application/x-www-form-urlencoded',
    'Content-Length': Buffer.byteLength(postData)
  }
};

const req = http.request(options, (res) => {
  console.log(`状态码: ${res.statusCode}`);
  console.log(`响应头: ${JSON.stringify(res.headers)}`);
  res.setEncoding('utf8');
  res.on('data', (chunk) => {
    console.log(`响应主体: ${chunk}`);
  });
  res.on('end', () => {
    console.log('响应中已无数据');
  });
});

req.on('error', (e) => {
  console.error(`请求遇到问题: ${e.message}`);
});

// 将数据写入请求主体。
req.write(postData);
req.end();

我在用上面这段代码发送http请求同一个接口时，发现data事件中的chunk有时候完整的，有时候被分块了，类似json对象被分割成两部分，而且被分块时是作为两次接收到，因为每次获取后都执行了end事件。所以想问下这种分块传输的理念为什么是有时候出现分块，有时候没有分块而是完整的在data事件中一次性传输接收，而且这种出现的情况时间是未知的，比如在一次批量执行时，第一次调用就出现分块了，有时候在几十次、几百次才出现。不能理解这样的现象出现。实际上请求的接口的报文每次都是一样的。

**Comment by Gerhut** [comment]
Please raise your Node.js dev question in [StackOverflow](https://stackoverflow.com/questions/ask?tags=node.js). Thanks

**Comment by damon008** [comment]
//发送 http Post 请求
    const postData=querystring.stringify({
        email:email,
        password:password
    });
    const options={
        hostname: loginUrl,
        port:loginPort,
        path:'/manage/login',
        method:'POST',
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            'Content-Length': Buffer.byteLength(postData)
        }
    };
    logger.debug('Login url: %s, loginPort: %s', loginUrl, loginPort);
    const reqq = http.request(options, (ress) => {
        logger.info(`Login response status: ${ress.statusCode}`);
        logger.debug(`Login response headers: ${JSON.stringify(ress.headers)}`);
        ress.setEncoding('utf-8');
        if(ress.statusCode !== 200){
            return res.status(200).json({
                code: 500,
                error: 'Login Failed',
                message: 'Login Failed'
            });
        }
        ress.on('data', (body) => {
            logger.debug(`Login response body: ${body}`);
            try{
                var respBody = JSON.parse(body);
                if (respBody.code == 0){
                    let nowTime = Date.now();
                    var user = respBody.result.user;
                    var bitaToken = respBody.result.token;
                    admin = false;
                    if (adminUserEmail.indexOf(email) > -1) {
                        admin = true;
                    }
                    jwt.sign({
                        username: user.id,
                        admin: admin,
                    }, tokenConfig.secret, {expiresIn: expiration}, (signError, token) => {
                        if (signError) {
                            logger.warn('Sign token error', signError);
                            return res.status(500).json({
                                error: 'SignTokenFailed',
                                message: 'sign token failed',
                            });
                        }
                        return res.status(200).json({
                            code: 0
                        });
                    });
                }
                else{
                    logger.warn('User %s authentication failed', email);
                    return res.status(200).json({
                        code: respBody.code,
                        error: 'AuthenticationFailed',
                        message: respBody.msg
                    });
                }
            }
            catch (e) {
                logger.error(`parse json body error: ${body}`);
                logger.error(e);
            }
        });
        ress.on('end', () => {
            logger.debug('No more data in response.');
        });
    });
    reqq.on('error', (e) => {
        logger.error(`login auth problem with request: ${e.message}`);
    });
    reqq.write(postData);
    reqq.end();

完整代码如上，但是在data事件  返回的body时，有时候是完整的传输接收，有时候被分块了，需要两次才接收到完整的，但是两次中end事件都执行了。

**Comment by scarlett2018** [comment]
> Please raise your Node.js dev question in [StackOverflow](https://stackoverflow.com/questions/ask?tags=node.js). Thanks

Closing the issue per the above comments, thanks @Gerhut .
