### ISSUE TITLE
pylon is not ready yet. Please wait for a moment!

### ISSUE THREAD

**Issue by kakaluote** [Microsoft/pai#2609]
启动pai服务时，卡在这里，images已下载好了
管理界面的日志只有一句话  
container "pylon" in pod "pylon-ds-hhkqx" is waiting to start: ContainerCreating
请问在哪里看卡住的详细原因

**Comment by speciallan** [comment]
我也卡在这，但是问题是Failed create pod sandbox.

**Comment by kakaluote** [comment]
之前找到过一些原因，是因为docker镜像下载慢，还有一个是端口被用了，换了个端口就好了，但是偶尔还是会卡住，找不到哪里能详细原因

**Comment by abuccts** [comment]
Hi, you can check the methods in [this issue](https://github.com/Microsoft/pai/issues/2282#issuecomment-472701749).
The common reason for `pylon` not ready is port conflict or firewall.

You can also check `kubelet` log in your dev box by `docker logs kubelet`.

**Comment by speciallan** [comment]
thx, i solve this problem by uncommenting pylon port:88 in services-configuaration.yaml , it confilict with my nginx.
