### ISSUE TITLE
Command conflict between yarn(pkg) and hadoop yarn

### ISSUE THREAD

**Issue by QuanluZhang** [Microsoft/pai#261]
In the base docker image provided by PAI, hadoop is installed and it has _yarn_ command. However, there is another _yarn_, a dependency/package management tool similar to _npm_. Users are more likely to use latter yarn rather than the former one, but there is a name conflict between these two yarn commands.

**Comment by abuccts** [comment]
`yarnpkg` is only used in infra service which users do not need in their job.

**Comment by fanyangCS** [comment]
hadoop yarn is actually not used. we should remove it from base dockerfile. For now, you can rm the hadoop yarn binary in your startup script

**Comment by scarlett2018** [comment]
cleaning old issues,  @fanyangCS  @QuanluZhang  please help to evaluate whether this is still an issue, thanks.
