### ISSUE TITLE
pai里面怎么配置使hdfs能发现的新增的硬盘

### ISSUE THREAD

**Issue by kakaluote** [Microsoft/pai#2610]
部署成功后，查看hdfs的节点，只有2T的硬盘，请问如何是hdfs能使用挂载的其它硬盘

**Comment by kakaluote** [comment]
找到了一个配置，services-configuration.yaml里面 data-path 配置  "path1,path2"
但是，这样的配置，要求所有机器上的硬盘挂载都一样吗
如果 机器a有2个硬盘，机器b有1个硬盘，该怎么配置

**Comment by mzmssg** [comment]
@kakaluote 
No need. Assuming you have two path /path/to/disk1, /path/to/disk2. Then in machine a, they could point to different disk, in machine b, they could be the same disk, that's fine.

**Comment by kakaluote** [comment]
thank you
