### ISSUE TITLE
可以指定job使用的GPU吗

### ISSUE THREAD

**Issue by kakaluote** [Microsoft/pai#2611]
可以制定job使用的gpu吗，如 使用 机器a的gpu2，gpu3
或者分布式训练时，使用 机器a的gpu0，gpu1     机器b的gpu2，gpu3

**Comment by scarlett2018** [comment]
@kakaluote 多谢提交需求，此功能在现有版本中尚未支持。

请帮忙根据模板提供更多的背景信息，帮助我们更好的排序这个需求，谢谢。

Organization Name:

What would you like to be added:

Why is this needed:

Without this feature, how does the current module work:

Components that may involve changes:

**Comment by kakaluote** [comment]
Organization Name: DeepThink.ai

What would you like to be added:   Let the job can specify the GPUs to use
example: my job needs 4 gpus, so i can specify   machine A -> gpu2 and gpu3, machine A -> gpu0 and gpu1

Why is this needed: My cluster has different types of GPUs，i want to use same type gpus  to run the job

Without this feature, how does the current module work: my 2080ti machine not in cluster (others are 1080ti)

Components that may involve changes: i don't what it means ...


one more question,Pai is how to allocate resources to jobs，one job can only use one machine's resources? If a job requires 4 gpus, but this machine‘s 2 gpus are used by other jobs, will this job fail when allocating resources?
