### ISSUE TITLE
Need to auto recover due to Azure temp disk cleaned

### ISSUE THREAD

**Issue by squirrelsc** [microsoft/pai#2615]
Currently, some OpenPAI instance is using Azure temp disk for Docker cache. But init logic of kubernetes is on this disk also. So that, if Azure cleans up this disk, it needs to recover service manually.

It should store kubernetes configuration on system drive, and keep cache on temp drive.

**Comment by fanyangCS** [comment]
close and track in https://github.com/microsoft/pai/issues/2286
