### ISSUE TITLE
Consolidate Job Submission Experience

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#2621]
Currently, we have 2 Job Submission Plugin and one legacy Job Submission Page. 

We need to consolidate them into one single simple experience.

**Comment by Binyang2014** [comment]
We will split this issue to three tasks:
1. submit job v2 page design --binyang
2. v2 fully support (exclude submit page)   --qinzheng
3. v1 to v2 converter --yifan

**Comment by Binyang2014** [comment]
Sub issues: #2815
