### ISSUE TITLE
关于rest-server获取framework的任务列表信息耗时

### ISSUE THREAD

**Issue by damon008** [microsoft/pai#2626]
getJobList(query, next) {
        let reqPath = launcherConfig.frameworksPath();
        if (query.username) {
            reqPath = `${reqPath}?UserName=${query.username}`;
        }
        unirest.get(reqPath)
            .headers(launcherConfig.webserviceRequestHeaders)
            .end((res) => {
                    const resJson = typeof res.body === 'object' ?
                        res.body : JSON.parse(res.body);
            });
    }

目前发现通过以上代码获取全部任务信息时，当任务数达到6万以上时，从framework拿到的数据接收后耗时比较严重,需要三秒，耗时是指从framework返回数据到rest-server拿到数据的时间:
![1555902739(1)](https://user-images.githubusercontent.com/25023599/56481138-17754200-64f0-11e9-8af0-ebc10f25749d.png)
请问有啥其他好的办法减少这段耗时吗？

**Comment by damon008** [comment]
不包含const resJson = typeof res.body === 'object' ?
res.body : JSON.parse(res.body);处理的时间，这个任务数66000情况下，耗时300ms左右。

**Comment by yqwang-ms** [comment]
You have too many tasks stored, before we support paging, please reduce below to mitigate:
https://github.com/Microsoft/pai/blob/09c1bf1088b1c189f9b23c36272fec69aed54edc/src/yarn-frameworklauncher/deploy/yarn-frameworklauncher-configuration/frameworklauncher.yml#L40

**Comment by damon008** [comment]
@yqwang-ms  Yeah，nodejs层有好的解决方案吗？

**Comment by yqwang-ms** [comment]
@Gerhut

**Comment by scarlett2018** [comment]
Hi @damon008 - 能帮忙提供更多您想了解这个实现的背景原因么？我是项目的PM,从您发表的问题，我不能确定您想解决的到底是什么问题。

我们有问题背景提示模板，请配合填写，以帮助我们更了解问题，从而解决问题，谢谢。

Organization Name:

Short summary about the issue/question:

Brief what process you are following:

How to reproduce it:

OpenPAI Environment:

OpenPAI version:
Cloud provider or hardware configuration:
OS (e.g. from /etc/os-release):
Kernel (e.g. uname -a):
Hardware (e.g. core number, memory size, storage size, GPU type etc.):
Others:
Anything else we need to know:

**Comment by fanyangCS** [comment]
close as no response in a long time.
