### ISSUE TITLE
The url in ssh info needs to be quoted

### ISSUE THREAD

**Issue by sunqinzheng** [Microsoft/pai#2633]
zsh can not run `wget http://192.168.193.1/a/192.168.193.1:5070/webhdfs/v1/Container/geo/geo~kenet-dev_61076495/ssh/keyFiles/geo~kenet-dev_61076495?op=OPEN -O geo~kenet-dev_61076495`
directly:

```
> wget http://192.168.193.1/a/192.168.193.1:5070/webhdfs/v1/Container/geo/geo~kenet-dev_61076495/ssh/keyFiles/geo~kenet-dev_61076495?op=OPEN -O geo~kenet-dev_61076495
> zsh: no matches found: http://192.168.193.1/a/192.168.193.1:5070/webhdfs/v1/Container/geo/geo~kenet-dev_61076495/ssh/keyFiles/geo~kenet-dev_61076495?op=OPEN
```

We need to enclose the url in quote marks like this:

```
wget "http://192.168.193.1/a/192.168.193.1:5070/webhdfs/v1/Container/geo/geo~kenet-dev_61076495/ssh/keyFiles/geo~kenet-dev_61076495?op=OPEN" -O geo~kenet-dev_61076495
```

_Originally posted by @GeoffreyChen777 in https://github.com/Microsoft/pai/issues/2580#issuecomment-485394547_

**Comment by abuccts** [comment]
Already merged.
