### ISSUE TITLE
failed to deploy hadoop data node after config hadoop-data-node 

### ISSUE THREAD

**Issue by edenbuaa** [Microsoft/pai#2637]
**Issue Description**
The hadoop data node can't be in running after change the storage-path of hadoop-data-node in service-configuration.yaml.

**Steps to Reproduce** 
1. delete pai service
2. clean k8s
3. edit storage-path to another disk folder
4. boot up k8s
5. start pai service
and then, the data-node report error: 

19/04/23 02:51:05 INFO datanode.DataNode: registered UNIX signal handlers for [TERM, HUP, INT]
19/04/23 02:51:05 INFO checker.ThrottledAsyncChecker: Scheduling a check for [DISK]file:/var/lib/hdfs/data-1/
19/04/23 02:51:05 INFO impl.MetricsConfig: loaded properties from hadoop-metrics2.properties
19/04/23 02:51:05 INFO impl.MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
19/04/23 02:51:05 INFO impl.MetricsSystemImpl: DataNode metrics system started
19/04/23 02:51:05 INFO common.Util: dfs.datanode.fileio.profiling.sampling.percentage set to 0. Disabling file IO profiling
19/04/23 02:51:05 INFO datanode.BlockScanner: Initialized block scanner with targetBytesPerSec 1048576
19/04/23 02:51:05 INFO datanode.DataNode: Configured hostname is <ip>
19/04/23 02:51:05 INFO common.Util: dfs.datanode.fileio.profiling.sampling.percentage set to 0. Disabling file IO profiling
19/04/23 02:51:05 WARN conf.Configuration: No unit for dfs.datanode.outliers.report.interval(1800000) assuming MILLISECONDS
19/04/23 02:51:05 INFO datanode.DataNode: Starting DataNode with maxLockedMemory = 0
19/04/23 02:51:05 INFO datanode.DataNode: Opened streaming server at /0.0.0.0:5010
19/04/23 02:51:05 INFO datanode.DataNode: Balancing bandwidth is 536870912 bytes/s
19/04/23 02:51:05 INFO datanode.DataNode: Number threads for balancing is 100
19/04/23 02:51:05 INFO mortbay.log: Logging to org.slf4j.impl.Log4jLoggerAdapter(org.mortbay.log) via org.mortbay.log.Slf4jLog
19/04/23 02:51:05 INFO server.AuthenticationFilter: Unable to initialize FileSignerSecretProvider, falling back to use random secrets.
19/04/23 02:51:05 INFO http.HttpRequestLog: Http request log for http.requests.datanode is not defined
19/04/23 02:51:05 INFO http.HttpServer2: Added global filter 'safety' (class=org.apache.hadoop.http.HttpServer2$QuotingInputFilter)
19/04/23 02:51:05 INFO http.HttpServer2: Added filter static_user_filter (class=org.apache.hadoop.http.lib.StaticUserWebFilter$StaticUserFilter) to context datanode
19/04/23 02:51:05 INFO http.HttpServer2: Added filter static_user_filter (class=org.apache.hadoop.http.lib.StaticUserWebFilter$StaticUserFilter) to context logs
19/04/23 02:51:05 INFO http.HttpServer2: Added filter static_user_filter (class=org.apache.hadoop.http.lib.StaticUserWebFilter$StaticUserFilter) to context static
19/04/23 02:51:05 INFO http.HttpServer2: Jetty bound to port 31601
19/04/23 02:51:05 INFO mortbay.log: jetty-6.1.26
19/04/23 02:51:06 INFO mortbay.log: Started HttpServer2$SelectChannelConnectorWithSafeStartup@localhost:31601
19/04/23 02:51:06 INFO web.DatanodeHttpServer: Listening HTTP traffic on /0.0.0.0:5075
19/04/23 02:51:06 INFO util.JvmPauseMonitor: Starting JVM pause monitor
19/04/23 02:51:06 INFO datanode.DataNode: dnUserName = root
19/04/23 02:51:06 INFO datanode.DataNode: supergroup = supergroup
19/04/23 02:51:06 INFO ipc.CallQueueManager: Using callQueue: class java.util.concurrent.LinkedBlockingQueue queueCapacity: 5000 scheduler: class org.apache.hadoop.ipc.DefaultRpcScheduler
19/04/23 02:51:06 INFO ipc.Server: Starting Socket Reader #1 for port 5020
19/04/23 02:51:06 INFO datanode.DataNode: Opened IPC server at /0.0.0.0:5020
19/04/23 02:51:06 INFO datanode.DataNode: Refresh request received for nameservices: null

19/04/23 02:51:06 INFO datanode.DataNode: dnUserName = root
19/04/23 02:51:06 INFO datanode.DataNode: supergroup = supergroup
19/04/23 02:51:06 INFO ipc.CallQueueManager: Using callQueue: class java.util.concurrent.LinkedBlockingQueue queueCapacity: 5000 scheduler: class org.apache.hadoop.ipc.DefaultRpcScheduler
19/04/23 02:51:06 INFO ipc.Server: Starting Socket Reader #1 for port 5020
19/04/23 02:51:06 INFO datanode.DataNode: Opened IPC server at /0.0.0.0:5020
19/04/23 02:51:06 INFO datanode.DataNode: Refresh request received for nameservices: null
19/04/23 02:51:06 INFO datanode.DataNode: Starting BPOfferServices for nameservices: &lt;default&gt;
19/04/23 02:51:06 INFO datanode.DataNode: Block pool &lt;registering&gt; (Datanode Uuid unassigned) service to /10.10.47.8:9000 starting to offer service
19/04/23 02:51:06 INFO ipc.Server: IPC Server Responder: starting
19/04/23 02:51:06 INFO ipc.Server: IPC Server listener on 5020: starting
19/04/23 02:51:06 INFO datanode.DataNode: Acknowledging ACTIVE Namenode during handshakeBlock pool &lt;registering&gt; (Datanode Uuid unassigned) service to /10.10.47.8:9000
19/04/23 02:51:06 INFO common.Storage: Using 1 threads to upgrade data directories (dfs.datanode.parallel.volumes.load.threads.num=1, dataDirs=1)
19/04/23 02:51:06 INFO common.Storage: Lock on /var/lib/hdfs/data-1/in_use.lock acquired by nodename 22@localhost
19/04/23 02:51:06 WARN common.Storage: Failed to add storage directory [DISK]file:/var/lib/hdfs/data-1/
java.io.IOException: Incompatible clusterIDs in /var/lib/hdfs/data-1: namenode clusterID = CID-55b2584e-23a4-4412-8132-82ae11a2bcea; datanode clusterID = CID-5b022c80-2c06-49dc-9195-b70c77552f56
	at org.apache.hadoop.hdfs.server.datanode.DataStorage.doTransition(DataStorage.java:762)
	at org.apache.hadoop.hdfs.server.datanode.DataStorage.loadStorageDirectory(DataStorage.java:293)
	at org.apache.hadoop.hdfs.server.datanode.DataStorage.loadDataStorage(DataStorage.java:409)
	at org.apache.hadoop.hdfs.server.datanode.DataStorage.addStorageLocations(DataStorage.java:388)
	at org.apache.hadoop.hdfs.server.datanode.DataStorage.recoverTransitionRead(DataStorage.java:556)
	at org.apache.hadoop.hdfs.server.datanode.DataNode.initStorage(DataNode.java:1649)
	at org.apache.hadoop.hdfs.server.datanode.DataNode.initBlockPool(DataNode.java:1610)
	at org.apache.hadoop.hdfs.server.datanode.BPOfferService.verifyAndSetNamespaceInfo(BPOfferService.java:374)
	at org.apache.hadoop.hdfs.server.datanode.BPServiceActor.connectToNNAndHandshake(BPServiceActor.java:280)
	at org.apache.hadoop.hdfs.server.datanode.BPServiceActor.run(BPServiceActor.java:816)
	at java.lang.Thread.run(Thread.java:748)
19/04/23 02:51:06 ERROR datanode.DataNode: Initialization failed for Block pool &lt;registering&gt; (Datanode Uuid 5594b612-553b-4c75-8ad0-24defe515f1c) service to /10.10.47.8:9000. Exiting. 
java.io.IOException: All specified directories have failed to load.
	at org.apache.hadoop.hdfs.server.datanode.DataStorage.recoverTransitionRead(DataStorage.java:557)
	at org.apache.hadoop.hdfs.server.datanode.DataNode.initStorage(DataNode.java:1649)
	at org.apache.hadoop.hdfs.server.datanode.DataNode.initBlockPool(DataNode.java:1610)
	at org.apache.hadoop.hdfs.server.datanode.BPOfferService.verifyAndSetNamespaceInfo(BPOfferService.java:374)
	at org.apache.hadoop.hdfs.server.datanode.BPServiceActor.connectToNNAndHandshake(BPServiceActor.java:280)
	at org.apache.hadoop.hdfs.server.datanode.BPServiceActor.run(BPServiceActor.java:816)
	at java.lang.Thread.run(Thread.java:748)
19/04/23 02:51:06 WARN datanode.DataNode: Ending block pool service for: Block pool &lt;registering&gt; (Datanode Uuid 5594b612-553b-4c75-8ad0-24defe515f1c) service to /10.10.47.8:9000
19/04/23 02:51:06 INFO datanode.DataNode: Removed Block pool &lt;registering&gt; (Datanode Uuid 5594b612-553b-4c75-8ad0-24defe515f1c)
19/04/23 02:51:08 WARN datanode.DataNode: Exiting Datanode
19/04/23 02:51:08 INFO datanode.DataNode: SHUTDOWN_MSG: 
/************************************************************
SHUTDOWN_MSG: Shutting down DataNode at localhost/127.0.0.1
************************************************************/

**Comment by mzmssg** [comment]
> 19/04/23 02:51:06 WARN common.Storage: Failed to add storage directory [DISK]file:/var/lib/hdfs/data-1/
java.io.IOException: Incompatible clusterIDs in /var/lib/hdfs/data-1: namenode clusterID = CID-55b2584e-23a4-4412-8132-82ae11a2bcea; datanode clusterID = CID-5b022c80-2c06-49dc-9195-b70c77552f56

How did you delete pai service? `./paictl.py service stop` or `./paictl.py service delete`?

**Comment by edenbuaa** [comment]
@mzmssg  ./paictl.py service delete

**Comment by mzmssg** [comment]
@edenbuaa 
Could you show me your services-configuration.yaml before and after?

**Comment by mzmssg** [comment]
@edenbuaa 
It's a bug, to workaround it, please manually delete your hadoop-data-node storage directory.

**Comment by edenbuaa** [comment]
@mzmssg  thanks. I try to delete the storage directory, but I it still be not in ready. the log shows:
container "hadoop-data-node" in pod "hadoop-data-node-ds-4874x" is waiting to start: ContainerCreating

**Comment by mzmssg** [comment]
@edenbuaa 
1. Stop hadoop data node
2. Delete storage dirs
3. Start hadoop data node

**Comment by edenbuaa** [comment]
@mzmssg It maybe a issue docker related. thanks and closed
