### ISSUE TITLE
rest-server API didn't work

### ISSUE THREAD

**Issue by xinmingHou** [Microsoft/pai#2642]
I want to Submit a job through the API provided by https://github.com/Microsoft/pai/blob/master/docs/rest-server/API.md

when i use:
`http://restserver/api/v1/token`
return
`{"code":"NoApiError","message":"API /api/v1/token is not found."}`

when i use:
`curl -H "Content-Type: application/x-www-form-urlencoded" \
     -X POST http://restserver/api/v1/token \
     -d "username=YOUR_USERNAME" -d "password=YOUR_PASSWORD"`
return
`curl: (52) Empty reply from server`

**OpenPAI Environment**:
- OpenPAI version:0.9.0
- OS (e.g. from /etc/os-release): ubuntu16.04

**Comment by xinmingHou** [comment]
![屏幕快照 2019-04-23 下午3 24 29](https://user-images.githubusercontent.com/26767685/56562460-f9850b80-65db-11e9-9445-603260b6c0df.png)
rest-server is running.

**Comment by abuccts** [comment]
Hi @xinmingHou,

* When you visit `http://restserver/api/v1/token` in browser, it uses a `GET` http request so the response should be `{"code":"NoApiError","message":"API /api/v1/token is not found."}`.
* The `curl` behavior is abnormal.

Could you please paste the related log from `rest-server-ds-p476g` pod? You can replace sensitive information with masks.

**Comment by abuccts** [comment]
Please also paste the log of `curl -v`:
```sh
curl -v -H "Content-Type: application/x-www-form-urlencoded" -X POST http://restserver/api/v1/token -d "username=YOUR_USERNAME" -d "password=YOUR_PASSWORD"
```
You can replace your ip with `192.168.0.1` in the log.

**Comment by dwang55** [comment]
It can work when replace restserver with the URI of rest server.
But we can not submit job config file  through it. The error code is: {"code":"NoVirtualClusterError","message":"Virtual cluster your_virtual_cluster is not found."}
However we we found that all users have right to access to 'default' cluster according to the pai/src/rest-server/src/models/user.js

**Comment by xinmingHou** [comment]
> Hi @xinmingHou,
> 
> * When you visit `http://restserver/api/v1/token` in browser, it uses a `GET` http request so the response should be `{"code":"NoApiError","message":"API /api/v1/token is not found."}`.
> * The `curl` behavior is abnormal.
> 
> Could you please paste the related log from `rest-server-ds-p476g` pod? You can replace sensitive information with masks.

thank u for answer。
it's work.
may be something wrong with my "curl" or web config.

**Comment by abuccts** [comment]
@xinmingHou Glad to hear, `curl: Empty reply from server` is likely caused by network issues.
