### ISSUE TITLE
job failed before  USER COMMAND START

### ISSUE THREAD

**Issue by kakaluote** [Microsoft/pai#2654]
**mv: cannot remove '/pai/ssh_config/config': Read-only file system**
[INFO] start ssh service
 * Restarting OpenBSD Secure Shell server sshd       [80G 
[74G[ OK ]
[INFO] USER COMMAND START

**/pai/bootstrap/docker_bootstrap.sh: line 169: cd: tools: No such file or directory**
job has finished with exit code 1
[DEBUG] Docker container exit handler: EXIT signal received in docker container, exiting ...

where is /pai/ssh_config/config,  and where is /pai/bootstrap/docker_bootstrap.sh

**Comment by abuccts** [comment]
`mv` is a warning, the error is caused by `cd: tools: No such file or directory`, there's no `tools` directory in your working directory. Please check your path.

**Comment by kakaluote** [comment]
got it, thank you
