### ISSUE TITLE
如何使job容器使用映射目录

### ISSUE THREAD

**Issue by kakaluote** [Microsoft/pai#2655]
job容器执行时，与物理主机之间有目录映射
类似   docker run -v a:b  image_tag
请问有这样的配置吗，在哪里配置

**Comment by abuccts** [comment]
Hi @kakaluote,

We do not support customized volume mounting currently, you can add new host volumes in [docker run](https://github.com/Microsoft/pai/blob/master/src/rest-server/src/templates/yarnContainerScript.mustache#L330-L337) and re-build rest server image as a workaround.
You can also open a new feature request using [this template](https://github.com/Microsoft/pai/issues/new?template=enhancement.md).
