### ISSUE TITLE
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).

### ISSUE THREAD

**Issue by kakaluote** [Microsoft/pai#2656]
如题，job 执行失败
可以docker run  --shm-size 8G，or  --ipc=host  可以解决这个问题
请问 openpai 中 如何给job执行这样的参数？

**Comment by abuccts** [comment]
Please use `shmMB` in your [job config](https://github.com/Microsoft/pai/blob/master/docs/job_tutorial.md#specification), e.g. `shmMB: 8192`.

**Comment by kakaluote** [comment]
great,thank you

**Comment by zeyu-hello** [comment]
Hi, @abuccts 
I tried to edit the job yaml in submit jog page, but get this error:
```
ValidationError: child "taskRoles" fails because [child "Task_role_1" fails because [child "resourcePerInstance" fails because ["shmMB" is not allowed]]]
```

PAI v0.14.0

**Comment by zeyu-hello** [comment]
Hi, @abuccts 
I tried to add 
```
extraContainerOptions:
      shmMB: 8192
```
into the yaml, but after I closed the yaml editting page, this config disapeared.
