### ISSUE TITLE
Job list view loads over 10 seconds with 30k jobs

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#2662]
it takes around 10 seconds to load the entire job list for a cluster with more than 30k jobs. we might need to consider pagination to improve the job query performance.

**Comment by fanyangCS** [comment]
This is not the case previously. I suggest to optimize the first.

**Comment by fanyangCS** [comment]
Let’s do a profiling first to see where is the bottleneck.

**Comment by scarlett2018** [comment]
updated the title

**Comment by fanyangCS** [comment]
resolved. https://github.com/microsoft/pai/pull/3244
