### ISSUE TITLE
pytorch distributed train

### ISSUE THREAD

**Issue by kakaluote** [Microsoft/pai#2669]
I want to do pytorch distributed training. multi machine，not single machine multi gpu.
i know use horovod can do this,but how can i make it in PAI.
is there some example already exist?

**Comment by abuccts** [comment]
Maybe you can refer to [this example](https://github.com/Microsoft/pai/tree/master/examples/horovod#horovod-with-mpi-on-openpai).

**Comment by kakaluote** [comment]
thank you
