### ISSUE TITLE
训练监控

### ISSUE THREAD

**Issue by kakaluote** [microsoft/pai#2670]
如何执行训练监控的进程，如tensorboard或其它。
example.tensorflow中有关于tensorboard的示例，它是通过提交一个新的job，在新的container中运行tensorboard的。这里需要train job container 和 tensorboard job container有数据互通，示例中是通过hdfs，保存训练的log。
我的训练是pytorch，训练结束之后，才会上传所有生成的log和checkpoint到hdfs。
有办法在同一个container内运行tensorboard吗

**Comment by GeoffreyChen777** [comment]
训练开始通过ssh 进去的container，从里面开的tensorboard 就行了。访问可以直接用container所在的机子的ip加端口（默认6006）

**Comment by mikixu** [comment]
我的训练也是pytorch，设置了hdfs的outputdir，但是训练结束之后，却没有任何东西上传上去，是需要做什么特殊处理吗？

**Comment by GeoffreyChen777** [comment]
@mikixu `outputdir`just set the enviorment var `PAI_OUTPUT_DIR`to `hdfs://ip:port/path`.

If you want to save your output, you need to manually run a command: `hdfs dfs -put xxx $PAI_OUTPUT_DIR`.

**Comment by mikixu** [comment]
我这边尝试使用了以下方法：
1.将PAI_OUTPUT_DIR设定到hdfs://ip:port/path
2.hdfs-mount到$PAI_DEFAULT_FS_URI
看样子的话，好像是保存成功了，但是，任务一直在retry，
当我ls -lh这个目录时，显示了如下信息
total 0
-rw-r--r-- 1 2147483647 root 113 Apr 26 04:20 events.out.tfevents.1556251769.test-worker1
-rw-r--r-- 1 2147483647 root 113 Apr 26 04:32 events.out.tfevents.1556252492.test-worker1
-rw-r--r-- 1 2147483647 root  68 Apr 26 04:45 events.out.tfevents.1556253213.test-worker1
-rw-r--r-- 1 2147483647 root 113 Apr 26 04:57 events.out.tfevents.1556253954.test-worker1
-rw-r--r-- 1 2147483647 root   0 Apr 26 04:58 events.out.tfevents.1556254696.test-worker1
看起来成功了，但又没有。

**Comment by abuccts** [comment]
@kakaluote You can run tensorboard in backgroud, e.g.
```sh
tensorboard --logdir=$LOG_DIR &
python train.py
```

---

@GeoffreyChen777 Thanks for your reply. Native Hadoop `hdfs` lib is recommended to use hdfs. If you use TensorFlow, it also supports [reading hdfs](https://github.com/tensorflow/examples/blob/master/community/en/docs/deploy/hadoop.md) which requires Hadoop.

---

@mikixu If you use PyTorch, you can try [`hdfs`](https://hdfscli.readthedocs.io/en/latest/) package to download/upload data in Python.
The retrying is related to your job logic according to your limit description.

**Comment by kakaluote** [comment]
@mikixu 我这边上传checkpoint是使用python的hdfs库操作hdfs的
类似这样    python train.py  && python hdfs_op.py --local_path=path_to_ckpt --hdfs_path=path_on_hdfs

**Comment by kakaluote** [comment]
@abuccts 我觉得PAI的job container需要有个数据持久化的方案
现在我的训练，需要先上传训练数据到hdfs，然后每次训练都需要下载数据到容器内，因为容器销毁，下载的数据都没了。如果数据量很大，每次都下载就合理了
如果能将下载的训练数据，保存在容器所在的物理机上，后面的训练，就可以直接用了。
或者其它方案缓存下载？

pytorch能直接操作hdfs上的数据吗？如果可以的话，直接操作大量图片这种小数据的话，效率会很低下吧

tensorflow似乎能直接读取hdfs上的tfrecord，它是直接读取，还是先下载到容器内再操作？

**Comment by kakaluote** [comment]
> @kakaluote You can run tensorboard in backgroud, e.g.
> 
> ```shell
> tensorboard --logdir=$LOG_DIR &
> python train.py
> ```


i try this, not work...,failed by this
job has finished with exit code 1

**Comment by GeoffreyChen777** [comment]
@kakaluote NFS can solve your problem. You can use a Linux machine as a storage machine to store all your training data, and use NFS to share the data in this machine.

Before you train your model, you can mount the NFS machine to your container and you can read and write the data in the storage machine directly.

**Comment by mikixu** [comment]
> @kakaluote You can run tensorboard in backgroud, e.g.
> 
> ```shell
> tensorboard --logdir=$LOG_DIR &
> python train.py
> ```
> 
> @GeoffreyChen777 Thanks for your reply. Native Hadoop `hdfs` lib is recommended to use hdfs. If you use TensorFlow, it also supports [reading hdfs](https://github.com/tensorflow/examples/blob/master/community/en/docs/deploy/hadoop.md) which requires Hadoop.
> 
> @mikixu If you use PyTorch, you can try [`hdfs`](https://hdfscli.readthedocs.io/en/latest/) package to download/upload data in Python.
> The retrying is related to your job logic according to your limited description.

@abuccts 不能理解$PAI_OUTPUT_DIR设定到HDFS路径的意义，感觉OPENPAI对这一点并没有进行特别的处理，如果OPenpai不支持文件自动上传到hdfs，那设定$PAI_OUTPUT_DIR到HDFS路径的意义又是什么呢

**Comment by kakaluote** [comment]
$PAI_OUTPUT_DIR  这种变量是启动job container的时候，传递给执行命令的，除了下载code到容器内，PAI帮忙做了，其它的都得自己做
tensorflow支持操作hdfs，但pytorch不支持，官方有个issue说的是，让我们自己用python的第三方库实现

**Comment by leepengcheng** [comment]
> $PAI_OUTPUT_DIR 这种变量是启动job container的时候，传递给执行命令的，除了下载code到容器内，PAI帮忙做了，其它的都得自己做
> tensorflow支持操作hdfs，但pytorch不支持，官方有个issue说的是，让我们自己用python的第三方库实现



> $PAI_OUTPUT_DIR 这种变量是启动job container的时候，传递给执行命令的，除了下载code到容器内，PAI帮忙做了，其它的都得自己做

貌似下载code到容器也需要镜像支持,我用自己做的镜像就不行。
