### ISSUE TITLE
[feature]How to manage the webhdfs 

### ISSUE THREAD

**Issue by edenbuaa** [microsoft/pai#2671]
Does the webhdfs support user and files group management? It seem that all the user can access it.

**Comment by mzmssg** [comment]
We assume hdfs a public storage, if you want group management, please take other storage, such as our [nfs](https://github.com/Microsoft/pai/wiki/Simplified-Job-Submission-for-OpenPAI-with-NFS-deployment) solution

**Comment by mzmssg** [comment]
It's a false error log, we have fixed it in the new version. Please ignore and go ahead.

**Comment by edenbuaa** [comment]
sounds good. thanks
