### ISSUE TITLE
Job was killed but the status is Success

### ISSUE THREAD

**Issue by hellocandy** [Microsoft/pai#2672]
**Organization Name**:Advantech

**Short summary about the issue/question**: The job was killed, but the status is success. 
If the container was not active for about 30 seconds, the container will be killed. Is there exist any better mechanism to indicate whether the container is alive?
And if the container is killed, the status should be Fail.

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**: Cluster
- OpenPAI version: 0.10.1
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by mzmssg** [comment]
In https://github.com/Microsoft/pai/pull/2468
