### ISSUE TITLE
Group storage admin tool

### ISSUE THREAD

**Issue by wangdian** [microsoft/pai#2674]
Admin tool to manage group storage.  Commands includes:

./storagectl.py server set NAME nfs ADDRESS ROOTPATH
./storagectl.py server set NAME samba ADDRESS ROOTPATH USERNAME PASSWORD DOMAIN
./storagectl.py server set NAME azurefile DATASTORE FILESHARE ACCOUNTNAME KEY [-p PROXY_ADDRESS PROXY_PASSWORD]
./storagectl.py server set NAME azureblob DATASTORE FILESHARE ACCOUNTNAME KEY [-p PROXY_ADDRESS PROXY_PASSWORD]
./storagectl.py server list [-n SERVER_NAME_1, SERVER_NAME_2 ...]
./storagectl.py user delete SERVER_NAME

./storagectl.py group set GROUP_NAME SERVER_NAME_1 [SERVER_NAME_2 ...] [-m MOUNT_POINT SERVER PATH]...
./storagectl.py group list [-n GROUP_NAME_1, GROUP_NAME_2 ...]
./storagectl.py group delete GROUP_NAME

./storagectl.py user set USER_NAME SERVER_NAME_1 [SERVER_NAME_2 ...]
./storagectl.py user list [-n USER_NAME_1, USER_NAME_2 ...]
./storagectl.py user delete USER_NAME

**Comment by fanyangCS** [comment]
done.
