### ISSUE TITLE
[Feedback v0.12.0] "View full log" for stdout does not work

### ISSUE THREAD

**Issue by sotetsuk** [Microsoft/pai#2678]
Click "View full log" for stdout in each task does not work. 

![image](https://user-images.githubusercontent.com/5868442/56803769-27758480-6856-11e9-8f65-d60322679bf6.png)

![image](https://user-images.githubusercontent.com/5868442/56803759-1af12c00-6856-11e9-9bb6-58207b5d5efa.png)

For stderr, it's working

**Comment by mzmssg** [comment]
Seems it's a webportal bug, to workaround it, you could leverage pylon to redirect, please visit master_ip:80 instead of master_ip:9286

**Comment by abuccts** [comment]
Already fixed in https://github.com/Microsoft/pai/commit/a01d6b2606d58b6b745aaf05fb1ca7856b52b60a.
