### ISSUE TITLE
WebPortal Delete Job Question

### ISSUE THREAD

**Issue by qzwlinux** [microsoft/pai#2684]
**Organization Name**: SitonHoly

**Short summary about the issue/question**:
i submit some jobs in webportal,but some jobs error
Too much wrong task make me feel angry
i want to delete these jobs，what should i do?
![image](https://user-images.githubusercontent.com/46511491/56858572-b5fd1980-69ae-11e9-968f-3362035ca2bb.png)

**Brief what process you are following**:
submit some tasks

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version: 0.11.0
- Cloud provider or hardware configuration: SitonHoly Server machine
- OS (e.g. from /etc/os-release):ubuntu 16.04
- Kernel (e.g. `uname -a`):4.4.0-116-generic
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
   master:30core,125G,60T,gpu=none
   workerA:30core,376G,20T,gpu=v100
   workerB:30core,376G,20T,gpu=1080ti
   master*1,workerA*2,workerB*7
- Others:

**Anything else we need to know**:

**Comment by fanyangCS** [comment]
we do not expose API to delete a job. you can only stop jobs.

**Comment by leepengcheng** [comment]
> we do not expose API to delete a job. you can only stop jobs.

i try deploy  nni on openpai and  found very trial will generate a job,so when  trial number=1000,there will be 1000 jobs!
