### ISSUE TITLE
dev-box should stick to right version instead of latest version

### ISSUE THREAD

**Issue by squirrelsc** [microsoft/pai#2685]
below script is used as init script of dev-box, and it check out latest tag always. So, if user wants to use dev-box of 0.11.0, but it still use latest dev-box like 0.12.0. it's confusing. For dev-box, it should checkout current released tag, and not to latest version.

https://github.com/Microsoft/pai/blob/7ffc1df7ecd495ec6b476e50fac9f543da2a5c31/src/dev-box/build/start-script.sh#L24

**Comment by ydye** [comment]
https://github.com/microsoft/pai/blob/master/src/dev-box/build/start-script.sh#L22
