### ISSUE TITLE
How to pull images from a local docker repository?

### ISSUE THREAD

**Issue by tanzeyy** [Microsoft/pai#2688]
**Question:**
How can I pull images from my local repository?

**My operation process:**
Due to the Internet issues, I had to build my local repository (without authorization) and push my own images. Later when I try to submit a job with following config:

```json
{
  "jobName": "TestPython_1",
  "image": "REPO-URL/miniconda3",
  "authFile": "",
  "dataDir": "hdfs://HDFS-URL/data/",
  "outputDir": "",
  "codeDir": "hdfs://HDFS-URL/code/",
  "virtualCluster": "default",
  "gpuType": "",
  "retryCount": 0,
  "taskRoles": [
    {
      "name": "write_file",
      "taskNumber": 1,
      "cpuNumber": 1,
      "memoryMB": 100,
      "shmMB": 64,
      "gpuNumber": 0,
      "minFailedTaskCount": 1,
      "minSucceededTaskCount": null,
      "command": "python -m pip install hdfs && cp /code/helloworld.py ./helloworld.py && python helloworld.py",
      "portList": []
    }
  ],
  "jobEnvs": {},
  "extras": {}
}
```

and I receive following error:

```bash
Can not pull Docker image
```

then I add authorization to my repo and use config:

```json
{
  "jobName": "TestPython_2",
  "image": "REPO-URL/miniconda3",
  "authFile": "hdfs://HDFS-URL/authFiles/docker-auth.json",
  "dataDir": "hdfs://HDFS-URL/data/",
  "outputDir": "",
  "codeDir": "hdfs://HDFS-URL/code/",
  "virtualCluster": "default",
  "gpuType": "",
  "retryCount": 0,
  "taskRoles": [
    {
      "name": "write_file",
      "taskNumber": 1,
      "cpuNumber": 1,
      "memoryMB": 100,
      "shmMB": 64,
      "gpuNumber": 0,
      "minFailedTaskCount": 1,
      "minSucceededTaskCount": null,
      "command": "python -m pip install hdfs && cp /code/helloworld.py ./helloworld.py && python helloworld.py",
      "portList": []
    }
  ],
  "jobEnvs": {},
  "extras": {}
}
```

and submit the job again, I got:

```bash
Authorized failed
```

The format of the auth-file is like:
```json
{
	"auths": {
		"REPO-URL": {
			"auth": "some_string"
		}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/18.09.2 (linux)"
	}
}
```
I'm wondering how can I pull images from my local repository, thanks for your help!!!

**Comment by tanzeyy** [comment]
I configure my auth-file to the format mentioned in https://github.com/Microsoft/pai/blob/master/docs/faq.md#q-how-to-use-private-docker-registry-job-image-when-submitting-an-openpai-job and try again, however it appears that it can not pull from an insecure registry:

```bash
Error response from daemon: Get https://repo-url/v2/: http: server gave HTTP response to HTTPS client
```

**Comment by abuccts** [comment]
It's an issue for your Docker configuration, you can try:
1. Modify Docker daemon config file (the default path is `/etc/docker/daemon.json`) on your work nodes, add a new field `"insecure-registries": ["your_registry_url:port"]` in the json, here's the [reference](https://docs.docker.com/registry/insecure/).

2. Restart Docker daemon on all worker nodes by `sudo service docker restart`. Note this will restart all PAI service pods on those nodes.

**Comment by tanzeyy** [comment]
> It's an issue for your Docker configuration, you can try:
> 
> 1. Modify Docker daemon config file (the default path is `/etc/docker/daemon.json`) on your work nodes, add a new field `"insecure-registries": ["your_registry_url:port"]` in the json, here's the [reference](https://docs.docker.com/registry/insecure/).
> 2. Restart Docker daemon on all worker nodes by `sudo service docker restart`. Note this will restart all PAI service pods on those nodes.

So I have to modify the docker config file on all nodes? It there any other way?

**Comment by abuccts** [comment]
You are using the default config of Docker daemon, which uses "https". So if you want to pull images from a registry, either change the client Docker daemon to accept "http" or enable "https" in your registry. It's by design by Docker.

**Comment by tanzeyy** [comment]
> You are using the default config of Docker daemon, which uses "https". So if you want to pull images from a registry, either change the client Docker daemon to accept "http" or enable "https" in your registry. It's by design by Docker.
> 
> If you just think there're too many nodes to modify, you can use [some tools](https://unix.stackexchange.com/questions/19008/automatically-run-commands-over-ssh-on-many-servers) to execute in parallel.

It seems that this is the solution for me, I will modify the docker config on my work nodes. Thanks for your help!
