### ISSUE TITLE
Can kubernetes be upgraded？

### ISSUE THREAD

**Issue by 111Moderato** [microsoft/pai#2689]
**Short summary about the issue/question**:  
The version of kubernetes is 1.9.9. Can it be upgraded? What changes need to be made?

**OpenPAI Environment**: 
- OpenPAI version: 0.9.0
- Cloud provider or hardware configuration: hardware configuration
- OS (e.g. from /etc/os-release): Ubuntu16.04
- Kernel (e.g. `uname -a`): Linux master 4.15.0-47-generic
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Comment by fanyangCS** [comment]
yes you can upgrade it. please refer to k8s community for details.
