### ISSUE TITLE
Add a environment variable to tell user docker "I'm PAI".

### ISSUE THREAD

**Issue by sterowang** [Microsoft/pai#269]

**Comment by abuccts** [comment]
user can check all env vars prefixed with `PAI_`

**Comment by fanyangCS** [comment]
Why do we need this?

**Comment by scarlett2018** [comment]
cleaning old issues,  @sterowang  please help to evaluate whether this is still an issue, thanks.

**Comment by scarlett2018** [comment]
We already have variables starting with PAI_ nowadays, let's make sure they are well documented before closing the issue.

**Comment by fanyangCS** [comment]
It is all documented here: https://github.com/Microsoft/pai/blob/master/docs/job_tutorial.md#job-runtime-environmental-variable-.
