### ISSUE TITLE
How to Encrypt rest-server

### ISSUE THREAD

**Issue by SeSaHasaki** [microsoft/pai#2692]
I tried Google Closure Compiler,YUI Compressor,UglifyJS,JScrambler,JXcore,Obfuscator，but none of them worked.Running for a period of time while encrypting index.js will also result in an decodeExp is not defined error.

**Comment by fanyangCS** [comment]
what is the purpose of your approach? can you elaborate more in details?

**Comment by SeSaHasaki** [comment]
I want to encrypt some of the core JS files in rest-server and package them in a docker image for others to use.

**Comment by fanyangCS** [comment]
why do you do this?

**Comment by SeSaHasaki** [comment]
Because I've added some JS code and sensitive configuration files, I don't want people to get information from the container.

**Comment by fanyangCS** [comment]
encryption of code is not a good practice to protect sensitive information. we currently do not provide any way to achieve this. but in the future we will address this issue in a more systematic way.

**Comment by SeSaHasaki** [comment]
Okay, then I'll think of another way. Thank you for your support.

**Comment by abuccts** [comment]
Closed, please feel free to reopen if you have additional questions.
