### ISSUE TITLE
Is there any way to create Virtual Clusters with specified worker nodes?

### ISSUE THREAD

**Issue by GeoffreyChen777** [Microsoft/pai#2693]
Suppose that I have 20 worker nodes, 10 with 1080ti and 10 with 2080ti.
I want to split them into two groups equally for two teams.
Group A and B both have 5 1080ti and 5 2080ti.
Does OpenPAI support that?

**Comment by mzmssg** [comment]
PAI hasn't support it, you could implement such logic in launcher by yourself, or achieve it by yarn [node-label](https://hadoop.apache.org/docs/r2.9.0/hadoop-yarn/hadoop-yarn-site/NodeLabel.html)

**Comment by GeoffreyChen777** [comment]
Thank you @mzmssg
