### ISSUE TITLE
Get structural gpu info in hadoop-ai

### ISSUE THREAD

**Issue by mzmssg** [microsoft/pai#2695]
**What would you like to be added**:
Currently, hadoop-ai patch get gpu info by regex, but we could access structural info intead by `nvidia-smi -x`. 

**Why is this needed**:
Rewrite this part could reduce bugs.

**Without this feature, how does the current module work**:
It works with potential bugs.

**Components that may involve changes**:
hadoop

**Comment by fanyangCS** [comment]
on hold.
