### ISSUE TITLE
配置问题

### ISSUE THREAD

**Issue by JuiYang** [microsoft/pai#2697]
2019-04-29 10:00:27,465 [INFO] - deployment.k8sPaiLibrary.maintainlib.kubectl_install : Successfully install kubectl on the dev-box.
2019-04-29 10:00:27,466 [INFO] - deployment.k8sPaiLibrary.maintainlib.kubectl_install : Generate the configuation file of kubectl.
2019-04-29 10:00:27,466 [INFO] - deployment.k8sPaiLibrary.maintainlib.kubectl_install : Cluster configuration is detected.
2019-04-29 10:00:27,466 [INFO] - deployment.k8sPaiLibrary.maintainlib.kubectl_install : Generate the KUBECONIFG based on the cluster configuration.
2019-04-29 10:00:27,470 [INFO] - deployment.k8sPaiLibrary.maintainlib.kubectl_install : Successfully configure kubeconfig in the dev-box.
NAME            STATUS     ROLES    AGE     VERSION
10.120.139.31   NotReady   <none>   3s      v1.9.9
10.120.139.72   Ready      <none>   9m45s   v1.9.9
2019-04-29 10:00:30,067 [INFO] - deployment.k8sPaiLibrary.maintainlib.kubectl_install : Successfully install kubectl and configure it!
NAME                              SHORTNAMES   APIGROUP                       NAMESPACED   KIND
bindings                                                                      true         Binding
componentstatuses                 cs                                          false        ComponentStatus
configmaps                        cm                                          true         ConfigMap
endpoints                         ep                                          true         Endpoints
events                            ev                                          true         Event
limitranges                       limits                                      true         LimitRange
namespaces                        ns                                          false        Namespace
nodes                             no                                          false        Node
persistentvolumeclaims            pvc                                         true         PersistentVolumeClaim
persistentvolumes                 pv                                          false        PersistentVolume
pods                              po                                          true         Pod
podtemplates                                                                  true         PodTemplate
replicationcontrollers            rc                                          true         ReplicationController
resourcequotas                    quota                                       true         ResourceQuota
secrets                                                                       true         Secret
serviceaccounts                   sa                                          true         ServiceAccount
services                          svc                                         true         Service
mutatingwebhookconfigurations                  admissionregistration.k8s.io   false        MutatingWebhookConfiguration
validatingwebhookconfigurations                admissionregistration.k8s.io   false        ValidatingWebhookConfiguration
customresourcedefinitions         crd          apiextensions.k8s.io           false        CustomResourceDefinition
apiservices                                    apiregistration.k8s.io         false        APIService
controllerrevisions                            apps                           true         ControllerRevision
daemonsets                        ds           apps                           true         DaemonSet
deployments                       deploy       apps                           true         Deployment
replicasets                       rs           apps                           true         ReplicaSet
statefulsets                      sts          apps                           true         StatefulSet
tokenreviews                                   authentication.k8s.io          false        TokenReview
localsubjectaccessreviews                      authorization.k8s.io           true         LocalSubjectAccessReview
selfsubjectaccessreviews                       authorization.k8s.io           false        SelfSubjectAccessReview
selfsubjectrulesreviews                        authorization.k8s.io           false        SelfSubjectRulesReview
subjectaccessreviews                           authorization.k8s.io           false        SubjectAccessReview
horizontalpodautoscalers          hpa          autoscaling                    true         HorizontalPodAutoscaler
cronjobs                                       batch                          true         CronJob
jobs                                           batch                          true         Job
certificatesigningrequests        csr          certificates.k8s.io            false        CertificateSigningRequest
events                            ev           events.k8s.io                  true         Event
daemonsets                        ds           extensions                     true         DaemonSet
deployments                       deploy       extensions                     true         Deployment
ingresses                         ing          extensions                     true         Ingress
networkpolicies                   netpol       extensions                     true         NetworkPolicy
podsecuritypolicies               psp          extensions                     false        PodSecurityPolicy
replicasets                       rs           extensions                     true         ReplicaSet
networkpolicies                   netpol       networking.k8s.io              true         NetworkPolicy
poddisruptionbudgets              pdb          policy                         true         PodDisruptionBudget
clusterrolebindings                            rbac.authorization.k8s.io      false        ClusterRoleBinding
clusterroles                                   rbac.authorization.k8s.io      false        ClusterRole
rolebindings                                   rbac.authorization.k8s.io      true         RoleBinding
roles                                          rbac.authorization.k8s.io      true         Role
storageclasses                    sc           storage.k8s.io                 false        StorageClass
2019-04-29 10:00:32,902 [INFO] - deployment.k8sPaiLibrary.maintainlib.deploy : Create kube-proxy daemon for kuberentes cluster.
daemonset.apps/kube-proxy created
2019-04-29 10:00:33,312 [INFO] - deployment.k8sPaiLibrary.maintainlib.deploy : Create kubernetes dashboard deployment for kuberentes cluster.
2019-04-29 10:00:33,313 [INFO] - deployment.k8sPaiLibrary.maintainlib.deploy : Create dashboard service.
service/kubernetes-dashboard created
2019-04-29 10:00:33,633 [INFO] - deployment.k8sPaiLibrary.maintainlib.deploy : Create dashboard deployment.
deployment.apps/kubernetes-dashboard created
2019-04-29 10:00:33,980 [INFO] - deployment.k8sPaiLibrary.maintainlib.deploy : Update node configuration into configmap in the namespace [ kube-system ] as the name [ pai-node-config ] 
2019-04-29 10:00:33,993 [INFO] - deployment.paiLibrary.common.kubernetes_handler : Couldn't find configmap named pai-node-config. Create a new configmap
2019-04-29 10:00:34,029 [INFO] - deployment.paiLibrary.common.kubernetes_handler : Configmap named pai-node-config is created
2019-04-29 10:00:34,029 [INFO] - deployment.k8sPaiLibrary.maintainlib.deploy : The kubernetes deployment is finished!
2019-04-29 10:00:34,029 [INFO] - deployment.clusterCmd : Finish initializing PAI k8s cluster.

但是 打开网页启动不起来

python paictl.py service start 后
一直循环
drivers-one-shot is not ready yet. Please wait for a moment!
drivers-one-shot is not ready yet. Please wait for a moment!
drivers-one-shot is not ready yet. Please wait for a moment!
drivers-one-shot is not ready yet. Please wait for a moment!

**Comment by abuccts** [comment]
Could you provide the log of `drivers-one-shot-ds` pod from kubernetes dashboard? You can visit the dashboard at `9090` port of your master ip.

**Comment by zjuter0126** [comment]
请问您找到方法解决这个问题了吗
