### ISSUE TITLE
[mantaince] backup jobs 

### ISSUE THREAD

**Issue by edenbuaa** [Microsoft/pai#2699]
openpai version: v0.11.0
issue description: for now, Job is clean after reinstall openpai. Could we find a way to backup the job data before service delete and recovery later?

**Comment by abuccts** [comment]
You can `stop` and `start` services instead of `delete` them, [reference](https://github.com/Microsoft/pai/blob/master/docs/paictl/paictl-manual.md#maintain-infrastructure-services-).
