### ISSUE TITLE
Add “PAI_DEFAULT_HDFS_URI” environment  variable in docker.

### ISSUE THREAD

**Issue by sterowang** [Microsoft/pai#270]

**Comment by fanyangCS** [comment]
maybe we can change the name of the environment variable to PAI_DEFAULT_FILE_SYSTEM_URI. 
Currently PAI only provides HDFS as the storage solution, in the future we could support more file system.

**Comment by abuccts** [comment]
But where can we get this "default hdfs uri"?

**Comment by fanyangCS** [comment]
cluster config
