### ISSUE TITLE
Could Openpai use nvidia driver higher than 410?

### ISSUE THREAD

**Issue by edenbuaa** [Microsoft/pai#2701]
In the current version, openpai only provide driver 410 version, how can i use driver version higher than that? thanks.

**Comment by abuccts** [comment]
We haven't tested many driver versions but it may work likely.
You can modify the [driver version](https://github.com/Microsoft/pai/blob/master/docs/pai-management/doc/how-to-congiure-service-config.md#customized-configuration---for-advanced-user-) in service configuration, then [rebuild](https://github.com/Microsoft/pai/blob/master/docs/pai-build/pai-build.md#build) images by your own.
