### ISSUE TITLE
Why is the available memory smaller than my configuration?

### ISSUE THREAD

**Issue by kakaluote** [Microsoft/pai#2702]
at machine type,i config mem: 60G,when i call this  http://master_ip:8088/ws/v1/cluster/nodes to get the available resources of my workers, i got this <availMemoryMB>46080</availMemoryMB>

another worker has 30G mem, but <availMemoryMB>15360</availMemoryMB>

where is my memory

**Comment by mzmssg** [comment]
Some memory is reserved for PAI service

**Comment by kakaluote** [comment]
PAI  eat 15G ?

**Comment by mzmssg** [comment]
It's for prod configuration, anyway, it's a opensource project, you could change it as wanted 
https://github.com/Microsoft/pai/blob/a01d6b2606d58b6b745aaf05fb1ca7856b52b60a/src/hadoop-node-manager/deploy/hadoop-node-manager-configuration/nodemanager-generate-script.sh#L66

**Comment by kakaluote** [comment]
thank you for response
