### ISSUE TITLE
与kubeflow的关系

### ISSUE THREAD

**Issue by zhaojizhuang4** [Microsoft/pai#2705]
openPAI现在已经很满足我们业务部门需求了，除了NFS还需要略微加强下，但是不同的声音还是有的，有的人认为kubeflow更强，黑猫白猫，抓住耗子就是好猫，我力挺openPAI因为我看到了里面智慧的结晶和汗水，但是我还是想问问大牛们未来的规划

**Comment by fanyangCS** [comment]
https://github.com/Microsoft/pai/wiki/Roadmap

**Comment by zhaojizhuang4** [comment]
thank u very much!  i believe openpai will be the winner against kubeflow
