### ISSUE TITLE
VS Code Client UI minor issues.

### ISSUE THREAD

**Issue by squirrelsc** [microsoft/pai#2706]
There are some UI related minor issues,

1. Command Palette -> PAI: Open Dashboard. In current version, it can open not only dashboard, and also open other pages. The text should be updated.
2. PAI Cluster Explorer -> Open Web Portal.... In current version, OpenPAI uses job list page as default page. So this entry should be removed.
3. Settings -> pai.job.upload.enabled. When selecting explorer, it opens the hdfs in vs code explorer also, it's part of side bar. So the name should be changed like in Explorer/OpenPAI side bar, or it's confusing.

**Comment by yiyione** [comment]
Hi  @squirrelsc ,
2. In current version, OpenPAI use a home page as default page, I think we can keep "Open Web Portal....".
3. In current version, the HDFS isn't in "vs code explorer" anymore. So I think the name doesn't need to be changed now.
