### ISSUE TITLE
Deploy kubernetes cluster with OpenPAI

### ISSUE THREAD

**Issue by kangapp** [Microsoft/pai#2710]
![image](https://user-images.githubusercontent.com/33341430/57204347-c71adb80-6fe9-11e9-927f-a484130ea636.png)

It lasted for a long time, what is the problem

**Comment by fanyangCS** [comment]
how much time did you wait? 
Depending on your network bandwidth, it could take a hour or two, or as long as a few days.

**Comment by kangapp** [comment]
@fanyangCS 
 I waited for about three hours ,and finally output this.

> 2019-05-06 04:56:30,741 [WARNING] - deployment.k8sPaiLibrary.maintainlib.common : There will be a delay after installing, please wait.
> 2019-05-06 04:56:30,742 [INFO] - deployment.k8sPaiLibrary.maintainlib.kubectl_install : Wait 5s, and retry it later.
> Unable to connect to the server: dial tcp 117.50.43.131:8080: i/o timeout
> 2019-05-06 04:59:05,826 [WARNING] - deployment.k8sPaiLibrary.maintainlib.common : There will be a delay after installing, please wait.
> 2019-05-06 04:59:05,827 [ERROR] - deployment.k8sPaiLibrary.maintainlib.kubectl_install : kubectl ready test failed. Exit paictl.

how to solve this problem?

**Comment by fanyangCS** [comment]
Is 117.50.43.131 your master node? please check whether the port 8080 has been occupied by other process.

**Comment by kangapp** [comment]
117.50.43.131 is my master node ,No other process occupies the port 8080

**Comment by kangapp** [comment]
docker logs kubelet

> I0506 06:00:37.672324    9741 docker_service.go:250] Setting cgroupDriver to cgroupfs
> I0506 06:00:37.672479    9741 kubelet.go:657] Starting the GRPC server for the docker CRI shim.
> I0506 06:00:37.672535    9741 docker_server.go:51] Start dockershim grpc server
> I0506 06:00:37.688446    9741 remote_runtime.go:43] Connecting to runtime service unix:///var/run/dockershim.sock
> I0506 06:00:37.690152    9741 kuberuntime_manager.go:186] Container runtime docker initialized, version: 18.09.2, apiVersion: 1.39.0
> I0506 06:00:37.690557    9741 plugins.go:453] Loaded volume plugin "kubernetes.io/aws-ebs"
> I0506 06:00:37.690609    9741 plugins.go:453] Loaded volume plugin "kubernetes.io/empty-dir"
> I0506 06:00:37.690625    9741 plugins.go:453] Loaded volume plugin "kubernetes.io/gce-pd"
> I0506 06:00:37.690645    9741 plugins.go:453] Loaded volume plugin "kubernetes.io/git-repo"
> I0506 06:00:37.690679    9741 plugins.go:453] Loaded volume plugin "kubernetes.io/host-path"
> I0506 06:00:37.690708    9741 plugins.go:453] Loaded volume plugin "kubernetes.io/nfs"
> I0506 06:00:37.690724    9741 plugins.go:453] Loaded volume plugin "kubernetes.io/secret"
> I0506 06:00:37.690743    9741 plugins.go:453] Loaded volume plugin "kubernetes.io/iscsi"
> I0506 06:00:37.690762    9741 plugins.go:453] Loaded volume plugin "kubernetes.io/glusterfs"
> I0506 06:00:37.690787    9741 plugins.go:453] Loaded volume plugin "kubernetes.io/rbd"
> I0506 06:00:37.690812    9741 plugins.go:453] Loaded volume plugin "kubernetes.io/cinder"
> I0506 06:00:37.690831    9741 plugins.go:453] Loaded volume plugin "kubernetes.io/quobyte"
> I0506 06:00:37.690844    9741 plugins.go:453] Loaded volume plugin "kubernetes.io/cephfs"
> I0506 06:00:37.690866    9741 plugins.go:453] Loaded volume plugin "kubernetes.io/downward-api"
> I0506 06:00:37.690879    9741 plugins.go:453] Loaded volume plugin "kubernetes.io/fc"
> I0506 06:00:37.690889    9741 plugins.go:453] Loaded volume plugin "kubernetes.io/flocker"
> I0506 06:00:37.690901    9741 plugins.go:453] Loaded volume plugin "kubernetes.io/azure-file"
> I0506 06:00:37.690936    9741 plugins.go:453] Loaded volume plugin "kubernetes.io/configmap"
> I0506 06:00:37.690953    9741 plugins.go:453] Loaded volume plugin "kubernetes.io/vsphere-volume"
> I0506 06:00:37.690970    9741 plugins.go:453] Loaded volume plugin "kubernetes.io/azure-disk"
> I0506 06:00:37.690983    9741 plugins.go:453] Loaded volume plugin "kubernetes.io/photon-pd"
> I0506 06:00:37.690997    9741 plugins.go:453] Loaded volume plugin "kubernetes.io/projected"
> I0506 06:00:37.691024    9741 plugins.go:453] Loaded volume plugin "kubernetes.io/portworx-volume"
> I0506 06:00:37.691049    9741 plugins.go:453] Loaded volume plugin "kubernetes.io/scaleio"
> I0506 06:00:37.691120    9741 plugins.go:453] Loaded volume plugin "kubernetes.io/local-volume"
> I0506 06:00:37.691142    9741 plugins.go:453] Loaded volume plugin "kubernetes.io/storageos"
> I0506 06:00:37.692220    9741 server.go:129] Starting to listen on 117.50.43.131:10250
> E0506 06:00:37.692253    9741 kubelet.go:1287] Image garbage collection failed once. Stats initialization may not have completed yet: failed to get imageFs info: unable to find data for container /
> I0506 06:00:37.692380    9741 server.go:149] Starting to listen read-only on 117.50.43.131:10255
> I0506 06:00:37.693689    9741 server.go:299] Adding debug handlers to kubelet server.
> F0506 06:00:37.693954    9741 server.go:157] listen tcp 117.50.43.131:10255: bind: cannot assign requested address
> Flag --require-kubeconfig has been deprecated, You no longer need to use --require-kubeconfig. This will be removed in a future version. Providing --kubeconfig enables API server mode, omitting --kubeconfig enables standalone mode unless --require-kubeconfig=true is also set. In the latter case, the legacy default kubeconfig path will be used until --require-kubeconfig is removed.
> I0506 06:01:38.288315    9929 server.go:182] Version: v1.9.9
> I0506 06:01:38.288501    9929 feature_gate.go:226] feature gates: &{{} map[DevicePlugins:true TaintBasedEvictions:true]}
> W0506 06:01:38.288739    9929 server.go:280] --require-kubeconfig is deprecated. Set --kubeconfig without using --require-kubeconfig.
> I0506 06:01:38.289150    9929 mount_linux.go:195] Detected OS without systemd
> W0506 06:01:38.289313    9929 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
> I0506 06:01:38.295725    9929 plugins.go:101] No cloud provider specified.
> I0506 06:01:38.295756    9929 server.go:303] No cloud provider specified: "" from the config file: ""
> I0506 06:01:38.298966    9929 manager.go:151] cAdvisor running in container: "/sys/fs/cgroup/cpu,cpuacct"
> I0506 06:01:38.362663    9929 fs.go:139] Filesystem UUIDs: map[03aa638c-d3c2-414c-8291-e2325ade2043:/dev/vdb 7cef075a-e1dc-43f2-82cf-7b135e22a302:/dev/vda1]
> I0506 06:01:38.362704    9929 fs.go:140] Filesystem partitions: map[shm:{mountpoint:/rootfs/var/lib/docker/containers/435bcc780fa555b9f06d4ddf48766cd523c74b1f64ad24530b4b5f49131b5433/mounts/shm major:0 minor:42 fsType:tmpfs blockSize:0} tmpfs:{mountpoint:/sys/fs/cgroup major:0 minor:44 fsType:tmpfs blockSize:0} /dev/vda1:{mountpoint:/var/lib/docker major:253 minor:1 fsType:ext4 blockSize:0} /dev/vdb:{mountpoint:/rootfs/data major:253 minor:16 fsType:ext4 blockSize:0}]
> I0506 06:01:38.373177    9929 manager.go:225] Machine: {NumCores:16 CpuFrequency:2194916 MemoryCapacity:67556999168 HugePages:[{PageSize:1048576 NumPages:0} {PageSize:2048 NumPages:0}] MachineID:6ab8e438b2d597dc4b575134008892a8 SystemUUID:BE8BF497-41F2-46B7-A078-FFA9E284F809 BootID:d7ea16b2-bec1-4674-8642-d8580a0042a5 Filesystems:[{Device:tmpfs DeviceMajor:0 DeviceMinor:44 Capacity:33778499584 Type:vfs Inodes:8246704 HasInodes:true} {Device:/dev/vda1 DeviceMajor:253 DeviceMinor:1 Capacity:21001531392 Type:vfs Inodes:1310720 HasInodes:true} {Device:/dev/vdb DeviceMajor:253 DeviceMinor:16 Capacity:2113653604352 Type:vfs Inodes:131072000 HasInodes:true} {Device:shm DeviceMajor:0 DeviceMinor:42 Capacity:67108864 Type:vfs Inodes:8246704 HasInodes:true} {Device:overlay DeviceMajor:0 DeviceMinor:41 Capacity:21001531392 Type:vfs Inodes:1310720 HasInodes:true}] DiskMap:map[253:0:{Name:vda Major:253 Minor:0 Size:21474836480 Scheduler:none} 253:16:{Name:vdb Major:253 Minor:16 Size:2147483648000 Scheduler:none}] NetworkDevices:[{Name:eth0 MacAddress:52:54:00:ad:4c:15 Speed:-1 Mtu:1454}] Topology:[{Id:0 Memory:67556999168 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]}] Caches:[]} {Id:1 Memory:0 Cores:[{Id:0 Threads:[1] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]}] Caches:[]} {Id:2 Memory:0 Cores:[{Id:0 Threads:[2] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]}] Caches:[]} {Id:3 Memory:0 Cores:[{Id:0 Threads:[3] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]}] Caches:[]} {Id:4 Memory:0 Cores:[{Id:0 Threads:[4] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]}] Caches:[]} {Id:5 Memory:0 Cores:[{Id:0 Threads:[5] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]}] Caches:[]} {Id:6 Memory:0 Cores:[{Id:0 Threads:[6] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]}] Caches:[]} {Id:7 Memory:0 Cores:[{Id:0 Threads:[7] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]}] Caches:[]} {Id:8 Memory:0 Cores:[{Id:0 Threads:[8] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]}] Caches:[]} {Id:9 Memory:0 Cores:[{Id:0 Threads:[9] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]}] Caches:[]} {Id:10 Memory:0 Cores:[{Id:0 Threads:[10] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]}] Caches:[]} {Id:11 Memory:0 Cores:[{Id:0 Threads:[11] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]}] Caches:[]} {Id:12 Memory:0 Cores:[{Id:0 Threads:[12] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]}] Caches:[]} {Id:13 Memory:0 Cores:[{Id:0 Threads:[13] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]}] Caches:[]} {Id:14 Memory:0 Cores:[{Id:0 Threads:[14] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]}] Caches:[]} {Id:15 Memory:0 Cores:[{Id:0 Threads:[15] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]}] Caches:[]}] CloudProvider:Unknown InstanceType:Unknown InstanceID:None}
> I0506 06:01:38.374965    9929 manager.go:231] Version: {KernelVersion:4.4.0-142-generic ContainerOsVersion:Debian GNU/Linux 9 (stretch) DockerVersion:18.09.2 DockerAPIVersion:1.39 CadvisorVersion: CadvisorRevision:}
> I0506 06:01:38.377821    9929 cadvisor_linux.go:175] Failed to register cAdvisor on port 4194, retrying. Error: listen tcp 117.50.43.131:4194: bind: cannot assign requested address
> I0506 06:01:38.379015    9929 server.go:431] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
> I0506 06:01:38.382098    9929 container_manager_linux.go:242] container manager verified user specified cgroup-root exists: /
> I0506 06:01:38.383897    9929 container_manager_linux.go:247] Creating Container Manager object based on Node Config: {RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRuntime:docker CgroupsPerQOS:true CgroupRoot:/ CgroupDriver:cgroupfs KubeletRootDir:/var/lib/kubelet ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: EnforceNodeAllocatable:map[pods:{}] KubeReserved:map[] SystemReserved:map[memory:{i:{value:3221225472 scale:0} d:{Dec:<nil>} s:3Gi Format:BinarySI}] HardEvictionThresholds:[]} ExperimentalQOSReserved:map[] ExperimentalCPUManagerPolicy:none ExperimentalCPUManagerReconcilePeriod:10s}
> I0506 06:01:38.384109    9929 container_manager_linux.go:266] Creating device plugin manager: true
> I0506 06:01:38.384210    9929 manager.go:96] Creating Device Plugin manager at /var/lib/kubelet/device-plugins/kubelet.sock
> I0506 06:01:38.384391    9929 server.go:696] Using root directory: /var/lib/kubelet
> I0506 06:01:38.384673    9929 kubelet.go:293] Adding manifest path: /etc/kubernetes/manifests
> I0506 06:01:38.384801    9929 file.go:52] Watching path "/etc/kubernetes/manifests"
> I0506 06:01:38.384901    9929 kubelet.go:318] Watching apiserver
> W0506 06:01:38.401791    9929 kubelet_network.go:139] Hairpin mode set to "promiscuous-bridge" but kubenet is not enabled, falling back to "hairpin-veth"
> I0506 06:01:38.401977    9929 kubelet.go:580] Hairpin mode set to "hairpin-veth"
> I0506 06:01:38.407144    9929 client.go:80] Connecting to docker on unix:///var/run/docker.sock
> I0506 06:01:38.407187    9929 client.go:109] Start docker client with request timeout=2m0s
> W0506 06:01:38.409448    9929 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
> I0506 06:01:38.414608    9929 docker_service.go:232] Docker cri networking managed by kubernetes.io/no-op
> I0506 06:01:38.443695    9929 docker_service.go:237] Docker Info: &{ID:4CHA:SEKH:B7K4:DSI4:N57M:VRRV:VDYH:P5XA:ZFVG:ICEU:VZYJ:IUBR Containers:1 ContainersRunning:1 ContainersPaused:0 ContainersStopped:0 Images:1 Driver:overlay2 DriverStatus:[[Backing Filesystem extfs] [Supports d_type true] [Native Overlay Diff true]] SystemStatus:[] Plugins:{Volume:[local] Network:[bridge host macvlan null overlay] Authorization:[] Log:[awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog]} MemoryLimit:true SwapLimit:false KernelMemory:true CPUCfsPeriod:true CPUCfsQuota:true CPUShares:true CPUSet:true IPv4Forwarding:true BridgeNfIptables:true BridgeNfIP6tables:true Debug:false NFd:29 OomKillDisable:true NGoroutines:49 SystemTime:2019-05-06T14:01:38.416036686+08:00 LoggingDriver:json-file CgroupDriver:cgroupfs NEventsListener:0 KernelVersion:4.4.0-142-generic OperatingSystem:Ubuntu 16.04.6 LTS OSType:linux Architecture:x86_64 IndexServerAddress:https://index.docker.io/v1/ RegistryConfig:0xc4205abd50 NCPU:16 MemTotal:67556999168 GenericResources:[] DockerRootDir:/var/lib/docker HTTPProxy: HTTPSProxy: NoProxy: Name:10-46-179-174 Labels:[] ExperimentalBuild:false ServerVersion:18.09.2 ClusterStore: ClusterAdvertise: Runtimes:map[nvidia:{Path:/usr/bin/nvidia-container-runtime Args:[]} runc:{Path:docker-runc Args:[]}] DefaultRuntime:runc Swarm:{NodeID: NodeAddr: LocalNodeState:inactive ControlAvailable:false Error: RemoteManagers:[] Nodes:0 Managers:0 Cluster:<nil>} LiveRestoreEnabled:false Isolation: InitBinary:docker-init ContainerdCommit:{ID:9754871865f7fe2f4e74d43e2fc7ccd237edcbce Expected:9754871865f7fe2f4e74d43e2fc7ccd237edcbce} RuncCommit:{ID:09c8266bf2fcf9519a651b04ae54c967b9ab86ec Expected:09c8266bf2fcf9519a651b04ae54c967b9ab86ec} InitCommit:{ID:v0.18.0 Expected:fec3683b971d9c3ef73f284f176672c44b448662} SecurityOptions:[name=apparmor name=seccomp,profile=default]}
> I0506 06:01:38.443837    9929 docker_service.go:250] Setting cgroupDriver to cgroupfs
> I0506 06:01:38.443973    9929 kubelet.go:657] Starting the GRPC server for the docker CRI shim.
> I0506 06:01:38.444010    9929 docker_server.go:51] Start dockershim grpc server
> I0506 06:01:38.469777    9929 remote_runtime.go:43] Connecting to runtime service unix:///var/run/dockershim.sock
> I0506 06:01:38.478032    9929 kuberuntime_manager.go:186] Container runtime docker initialized, version: 18.09.2, apiVersion: 1.39.0
> I0506 06:01:38.482848    9929 plugins.go:453] Loaded volume plugin "kubernetes.io/aws-ebs"
> I0506 06:01:38.482888    9929 plugins.go:453] Loaded volume plugin "kubernetes.io/empty-dir"
> I0506 06:01:38.482901    9929 plugins.go:453] Loaded volume plugin "kubernetes.io/gce-pd"
> I0506 06:01:38.482912    9929 plugins.go:453] Loaded volume plugin "kubernetes.io/git-repo"
> I0506 06:01:38.482930    9929 plugins.go:453] Loaded volume plugin "kubernetes.io/host-path"
> I0506 06:01:38.482941    9929 plugins.go:453] Loaded volume plugin "kubernetes.io/nfs"
> I0506 06:01:38.482952    9929 plugins.go:453] Loaded volume plugin "kubernetes.io/secret"
> I0506 06:01:38.482967    9929 plugins.go:453] Loaded volume plugin "kubernetes.io/iscsi"
> I0506 06:01:38.482984    9929 plugins.go:453] Loaded volume plugin "kubernetes.io/glusterfs"
> I0506 06:01:38.482995    9929 plugins.go:453] Loaded volume plugin "kubernetes.io/rbd"
> I0506 06:01:38.483034    9929 plugins.go:453] Loaded volume plugin "kubernetes.io/cinder"
> I0506 06:01:38.483057    9929 plugins.go:453] Loaded volume plugin "kubernetes.io/quobyte"
> I0506 06:01:38.483069    9929 plugins.go:453] Loaded volume plugin "kubernetes.io/cephfs"
> I0506 06:01:38.483090    9929 plugins.go:453] Loaded volume plugin "kubernetes.io/downward-api"
> I0506 06:01:38.483102    9929 plugins.go:453] Loaded volume plugin "kubernetes.io/fc"
> I0506 06:01:38.483113    9929 plugins.go:453] Loaded volume plugin "kubernetes.io/flocker"
> I0506 06:01:38.483124    9929 plugins.go:453] Loaded volume plugin "kubernetes.io/azure-file"
> I0506 06:01:38.483139    9929 plugins.go:453] Loaded volume plugin "kubernetes.io/configmap"
> I0506 06:01:38.483151    9929 plugins.go:453] Loaded volume plugin "kubernetes.io/vsphere-volume"
> I0506 06:01:38.483167    9929 plugins.go:453] Loaded volume plugin "kubernetes.io/azure-disk"
> I0506 06:01:38.483178    9929 plugins.go:453] Loaded volume plugin "kubernetes.io/photon-pd"
> I0506 06:01:38.483190    9929 plugins.go:453] Loaded volume plugin "kubernetes.io/projected"
> I0506 06:01:38.483202    9929 plugins.go:453] Loaded volume plugin "kubernetes.io/portworx-volume"
> I0506 06:01:38.483219    9929 plugins.go:453] Loaded volume plugin "kubernetes.io/scaleio"
> I0506 06:01:38.484026    9929 plugins.go:453] Loaded volume plugin "kubernetes.io/local-volume"
> I0506 06:01:38.484044    9929 plugins.go:453] Loaded volume plugin "kubernetes.io/storageos"
> I0506 06:01:38.486083    9929 server.go:758] Started kubelet
> E0506 06:01:38.487034    9929 kubelet.go:1287] Image garbage collection failed once. Stats initialization may not have completed yet: failed to get imageFs info: unable to find data for container /
> I0506 06:01:38.490012    9929 server.go:149] Starting to listen read-only on 117.50.43.131:10255
> F0506 06:01:38.491139    9929 server.go:157] listen tcp 117.50.43.131:10255: bind: cannot assign requested address

**Comment by fanyangCS** [comment]
"F0506 06:01:38.491139 9929 server.go:157] listen tcp 117.50.43.131:10255: bind: cannot assign requested address". For some reason, binding to the IP address 117.50.43.131 failed.
@ydye, have you met this issue before?

**Comment by fanyangCS** [comment]
@kangapp, looks like you solve the issue. care to explain how you fixed it?

**Comment by kangapp** [comment]
Public IP can not be access, so I change to Private IP and it work
