### ISSUE TITLE
create guidance for plugins

### ISSUE THREAD

**Issue by squirrelsc** [microsoft/pai#2711]
Currently, there are some plugins in OpenPAI project, it's great to have them, but it looks they are not in standard deployment progress. So can we create a guidance for each plugin, so that others  can use it easily?

For example,
1. It (the plugin) is included in standard deployment tools. So, if it's enabled, it can be installed, updated, uninstalled with OpenPAI.
1. It should provide test scenarios, so it can prevent regression during OpenPAI releases.
1. It should provide deployment guidance for admin, so that admin can follow it to setup.
1. It may need a dependent server, e.g. file server, it should be one time setup, and provide clear guidance to setup it. If there is breaking change, it should be documented in release notes.
1. It should provide document for end-users, so that users can learn themselves.

**Comment by fanyangCS** [comment]
the principle looks good. it is engineering 101 that applies to any development process. let's track it in separate issue.
