### ISSUE TITLE
hadoop-name-node is not ready yet. Please wait for a moment

### ISSUE THREAD

**Issue by kangapp** [microsoft/pai#2718]
![image](https://user-images.githubusercontent.com/33341430/57270729-1aab2900-70bf-11e9-82dc-58a47273d8f4.png)
![image](https://user-images.githubusercontent.com/33341430/57270748-2c8ccc00-70bf-11e9-832d-e366e1ab3d11.png)
![image](https://user-images.githubusercontent.com/33341430/57270760-3b737e80-70bf-11e9-8997-5c51a81ca52b.png)

how to solve this problem

**Comment by diao1104** [comment]
I'd like to ask you how you solved this problem. I have the same problem

**Comment by diao1104** [comment]
I'd like to ask you how you solved this problem. I have the same problem
