### ISSUE TITLE
Is it possible to define two type of GPU on one machine in layout.yaml ?

### ISSUE THREAD

**Issue by x1y2z3456** [microsoft/pai#2720]
**Short summary about the issue/question**:

for the distributed deployment , we may use layout.yaml to set up machine-sku, however, i was wondering if we change the configuration to make one machine can use more than one type of GPU

**Brief what process you are following**:

editing file layout.yaml to make one machine with more than one type of GPU

For example,
like this

node1:
    mem: 32G
    gpu:
        type: gtx1080ti
        count: 2
        type: k80
        count: 2
    cpu:
        vcore: 32
    os: ubuntu16.04

or

node1:
    mem: 32G
    gpu:
        type: gtx1080ti
        count: 2
    gpu:
        type: k80
        count: 2
    cpu:
        vcore: 32
    os: ubuntu16.04

Any suggestions ?

**OpenPAI Environment**:
- OpenPAI version: latest, v0.12.0
- OS (e.g. from /etc/os-release): Ubuntu16.04

**Comment by fanyangCS** [comment]
no. we do not support this feature.
