### ISSUE TITLE
docker version 18.09.6 works while version 18.09.2 does not work

### ISSUE THREAD

**Issue by zmsunnyday** [microsoft/pai#2721]
When I built a image using docker version 18.09.2 and deployed it on openPAI platform, it said that cannot find nvidia-smi. However, when the image was built using docker version  18.09.6, nvidia-smi ran normally. What's more, both images ran well on my own PC. Is there a lowest version requirement for docker of OpenPAI?

**Comment by abuccts** [comment]
There's no difference running Docker on host or through PAI. You should check `PATH` and `LD_LIBRARY_PATH` environment variables in your Docker images first if you cannot run `nvidia-smi`.

**Comment by scarlett2018** [comment]
@zmsunnyday - does @abuccts ' suggestion work for you? are you still facing the problem? please update the issue with your latest findings.

**Comment by zmsunnyday** [comment]
> @zmsunnyday - does @abuccts ' suggestion work for you? are you still facing the problem? please update the issue with your latest findings.

The suggestion did not work for me. I solved this problem by update the docker from version 18.09.2 to 18.09.6. But I still have no idea why this happened...

**Comment by scarlett2018** [comment]
@zmsunnyday - thanks for the update, this is very valuable info. I'm changing the title in case it is helpful to people who meet the same issue.
