### ISSUE TITLE
bootup turn error 'Skip this precess'

### ISSUE THREAD

**Issue by JuiYang** [microsoft/pai#2732]
when i run `python paictl.py cluster k8s-bootup -p ~/pai-config/
` command, the log shows that skip this process of  Executing the script to install kubectl on your host .
[this is log](http://140.143.224.98:8080/openpai/bootup.html),

kubectl is foreign  software and needs to visit foreign websites. It failed to install in China.

Is this the reason why 9090 port cannot be accessed?

what should i do ?

**Comment by abuccts** [comment]
Seems k8s boot-up succeed after a short delay. Can't you visit 9090 in a browser? It might be blocked by firewall on your node. Can you paste the log of `sudo docker logs kubelet` on your master node?

**Comment by fanyangCS** [comment]
close as no further response.
