### ISSUE TITLE
[Job Exporter] Cannot get GPU status

### ISSUE THREAD

**Issue by abuccts** [microsoft/pai#2737]
Currently, job exporter uses a hard code path,

https://github.com/microsoft/pai/blob/0eb286f029d78865c24feb6aabcc990c44336c11/src/job-exporter/src/nvidia.py#L165-L166

which will get failed when starting pods by nvidia-docker without mounting driver path from host.

**Comment by fanyangCS** [comment]
@binyang2014, do we still have this issue?

**Comment by Binyang2014** [comment]
This issue already solved, close this issue.
