### ISSUE TITLE
the question of submitting the job

### ISSUE THREAD

**Issue by JuiYang** [microsoft/pai#2743]
When we submit tasks using official documents, we can't find out how to configure the download data path.
We can't find the downloaded data.

**Comment by abuccts** [comment]
The data won't be downloaded into container. You can use `hdfs` lib or [Python hdfs](https://pypi.org/project/hdfs/) to download data if you want, but it's better to reading it directly without downloading into container.

**Comment by scarlett2018** [comment]
Thanks @JuiYang for submitting the question. We had been aware of this confusion and been working on a set of UX and document improvements. Please refer to the following (draft) document, hope it helps:
https://github.com/squirrelsc/pai/blob/l10n_master_release/docs/zh_CN/user/storage.md

Any suggestions or questions are welcomed
