### ISSUE TITLE
Problem in reconnection to cluster

### ISSUE THREAD

**Issue by zouzhenhong98** [microsoft/pai#2746]
Fail when trying to reconnect to cluster after close the VScode 1.33.1 
on Windows_NT x64 10.0.17763, the OpenPAI version is 0.2.0:

I started another cluster service with the same account to deal with the problem:
<img width="243" alt="reconnection" src="https://user-images.githubusercontent.com/26429253/57584990-6ec96980-7514-11e9-9e4b-0fc95b4f7db7.png">

**Comment by yiyione** [comment]
I can't reproduce this bug. But looks like re-add the cluster can deal with it.
