### ISSUE TITLE
Samba server with AAD for team wise storage

### ISSUE THREAD

**Issue by wangdian** [microsoft/pai#2751]
Provide documents and Docker Image to deploy Samba server with AAD integration. 
Includes:
1. Samba server with AAD integratoin
2. Team wise directory management
3. Api to get user's groups

**Comment by wangdian** [comment]
We provide a docker image for Microsoft AAD Samba server. 
Since the settings is configured for Microsoft AAD, the PR was not merged to main branch.
Please refer to PR #2755

**Comment by fanyangCS** [comment]
PR #2755 can serve as an example. please highlight those configuration parameters that should be changed to support the integration with AAD service.

**Comment by wangdian** [comment]
Create a new PR that uses fake KDC as an example. 
Please refer to PR #3292
