### ISSUE TITLE
Recieved SHUTDOWN signal from Resourcemanager, Registration of NodeManager failed, Message from ResourceManager: NodeManager from   IP   doesn't satisfy minimum allocations

### ISSUE THREAD

**Issue by chentao111** [microsoft/pai#2753]
![image](https://user-images.githubusercontent.com/29122848/57665430-6bc29c00-762e-11e9-83e0-91d98ab731b5.png)
![image](https://user-images.githubusercontent.com/29122848/57665445-7715c780-762e-11e9-8014-cb8d61838927.png)
![image](https://user-images.githubusercontent.com/29122848/57665462-8b59c480-762e-11e9-8d06-647a8cc02b3c.png)

**Comment by wangzhao123456** [comment]
hello, I run into the same problem, would you please tell me how to fix this problem? I don't know where to set up the minimum allocation. Thanks
