### ISSUE TITLE
The commited job (Open MPI TensorFlow CIFAR-10) can not access to hdfs

### ISSUE THREAD

**Issue by Chenyangzh** [microsoft/pai#2773]
**Short summary about the issue/question**:
I am following the guidance of "Open MPI TensorFlow CIFAR-10 example" https://github.com/microsoft/pai/tree/master/examples/horovod

First, I download the dataset and upload them with 
`hdfs dfs -put cifar10_dataset/. hdfs://myip:9000/my_pai_username/examples/tensorflow/distributed-cifar-10/data`
Then, I prepare the v1.10 tensorflow benchmark code, and upload it with
`hdfs dfs -put cifar10_dataset hdfs://myip:9000/my_pai_username/examples/horovod/code`
After that, I download the horovod official docker image and upload it to my own docker repository.
Finally, I committed the job, but getting errors saying that the tensorflow.gfile api cannot access to hdfs.
the error code is here:
`tensorflow.python.framework.errors_impl.NotFoundError: libhdfs.so: cannot open shared object file: No such file or directory`

**Following are my java scripts:**
{
  "jobName": "horovod-mpi-cifar10",
  "image": "my-own-docker-repository/horovod:0.14.1-tf1.10.0-torch0.4.0-py2.7",
  "dataDir": "$PAI_DEFAULT_FS_URI/$PAI_USERNAME/examples/tensorflow/distributed-cifar-10/data",
  "outputDir": "$PAI_DEFAULT_FS_URI/$PAI_USERNAME/examples/horovod/output",
  "codeDir": "$PAI_DEFAULT_FS_URI/$PAI_USERNAME/examples/horovod/code",
  "taskRoles": [
    {
      "name": "main",
      "taskNumber": 1,
      "cpuNumber": 4,
      "memoryMB": 16384,
      "gpuNumber": 2,
      "minSucceededTaskCount": 1,
      "command": "/bin/bash code/start.sh"
    },
    {
      "name": "worker",
      "taskNumber": 1,
      "cpuNumber": 4,
      "memoryMB": 16384,
      "gpuNumber": 2,
      "command": "sleep infinity"
    }
  ]
}

**Following are the error log:**

)
  File "/examples/code/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1701, in _build_graph
    shift_ratio=shift_ratio)
  File "/examples/code/benchmarks/scripts/tf_cnn_benchmarks/preprocessing.py", line 640, in minibatch
    all_images, all_labels = dataset.read_data_files(subset)
  File "/examples/code/benchmarks/scripts/tf_cnn_benchmarks/datasets.py", line 168, in read_data_files
    inputs.append(cPickle.load(f, **encoding))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 125, in read
    (input_producer_op, enqueue_ops, fetches) = self._build_model()
  File "/examples/code/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2228, in _build_model
    all_images, all_labels = dataset.read_data_files(subset)
  File "/examples/code/benchmarks/scripts/tf_cnn_benchmarks/datasets.py", line 168, in read_data_files
    self._preread_check()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    inputs.append(cPickle.load(f, **encoding))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 125, in read
    input_processing_info = self._build_input_processing(shift_ratio=0)
  File "/examples/code/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2157, in _build_input_processing
    self._preread_check()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: libhdfs.so: cannot open shared object file: No such file or directory
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: libhdfs.so: cannot open shared object file: No such file or directory
    shift_ratio=shift_ratio)
  File "/examples/code/benchmarks/scripts/tf_cnn_benchmarks/preprocessing.py", line 640, in minibatch
    all_images, all_labels = dataset.read_data_files(subset)
  File "/examples/code/benchmarks/scripts/tf_cnn_benchmarks/datasets.py", line 168, in read_data_files
    inputs.append(cPickle.load(f, **encoding))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 125, in read
    self._preread_check()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: libhdfs.so: cannot open shared object file: No such file or directory

Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.

mpirun.real detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[41865,1],2]
  Exit code:    1

**Comment by Chenyangzh** [comment]
I also tried using python hdfs interface and it is succeed!
But It should be able to use tensorflow.gfile api for hdfs, isn't it?
Anyone can help?

**Comment by mzmssg** [comment]
> tensorflow.python.framework.errors_impl.NotFoundError: libhdfs.so: cannot open **shared object file**: No such file or directory

The error is due to libhdfs.so not found, not hdfs files not found.  FYI: https://stackoverflow.com/questions/42307908/running-tensorflow-with-file-on-hdfs-cannot-find-libhdfs-so

**Comment by Chenyangzh** [comment]
Thank you for your reply! 
Before I just downloaded the horovod image from official site and commit it into my local repository without setting hdfs environment. If it’s the key of this problem? 
The other thing I am confused is how the horovod job docker can access to the hdfs system? is it set as the secondary name node of Hadoop?
Look forward to your reply

**Comment by mzmssg** [comment]
> Before I just downloaded the horovod image from official site and commit it into my local repository without setting hdfs environment. If it’s the key of this problem?

Maybe, but it should be easy to resolve.

> how the horovod job docker can access to the hdfs system

Not sure your point. PAI hdfs is insecure and disable authorization, so anyone could access it with the url(hdfs://master_ip:9000) in a reachable machine.

**Comment by Chenyangzh** [comment]
Thanks a lot! I solved this by writing a dockerfile and add hdfs envs~

**Comment by JuiYang** [comment]
> **Short summary about the issue/question**:
> I am following the guidance of "Open MPI TensorFlow CIFAR-10 example" https://github.com/microsoft/pai/tree/master/examples/horovod
> 
> First, I download the dataset and upload them with
> `hdfs dfs -put cifar10_dataset/. hdfs://myip:9000/my_pai_username/examples/tensorflow/distributed-cifar-10/data`
> Then, I prepare the v1.10 tensorflow benchmark code, and upload it with
> `hdfs dfs -put cifar10_dataset hdfs://myip:9000/my_pai_username/examples/horovod/code`
> After that, I download the horovod official docker image and upload it to my own docker repository.
> Finally, I committed the job, but getting errors saying that the tensorflow.gfile api cannot access to hdfs.
> the error code is here:
> `tensorflow.python.framework.errors_impl.NotFoundError: libhdfs.so: cannot open shared object file: No such file or directory`
> 
> **Following are my java scripts:**
> {
> "jobName": "horovod-mpi-cifar10",
> "image": "my-own-docker-repository/horovod:0.14.1-tf1.10.0-torch0.4.0-py2.7",
> "dataDir": "$PAI_DEFAULT_FS_URI/$PAI_USERNAME/examples/tensorflow/distributed-cifar-10/data",
> "outputDir": "$PAI_DEFAULT_FS_URI/$PAI_USERNAME/examples/horovod/output",
> "codeDir": "$PAI_DEFAULT_FS_URI/$PAI_USERNAME/examples/horovod/code",
> "taskRoles": [
> {
> "name": "main",
> "taskNumber": 1,
> "cpuNumber": 4,
> "memoryMB": 16384,
> "gpuNumber": 2,
> "minSucceededTaskCount": 1,
> "command": "/bin/bash code/start.sh"
> },
> {
> "name": "worker",
> "taskNumber": 1,
> "cpuNumber": 4,
> "memoryMB": 16384,
> "gpuNumber": 2,
> "command": "sleep infinity"
> }
> ]
> }
> 
> **Following are the error log:**
> 
> )
> File "/examples/code/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1701, in _build_graph
> shift_ratio=shift_ratio)
> File "/examples/code/benchmarks/scripts/tf_cnn_benchmarks/preprocessing.py", line 640, in minibatch
> all_images, all_labels = dataset.read_data_files(subset)
> File "/examples/code/benchmarks/scripts/tf_cnn_benchmarks/datasets.py", line 168, in read_data_files
> inputs.append(cPickle.load(f, **encoding))
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 125, in read
> (input_producer_op, enqueue_ops, fetches) = self._build_model()
> File "/examples/code/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2228, in _build_model
> all_images, all_labels = dataset.read_data_files(subset)
> File "/examples/code/benchmarks/scripts/tf_cnn_benchmarks/datasets.py", line 168, in read_data_files
> self._preread_check()
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 85, in _preread_check
> compat.as_bytes(self.__name), 1024 * 512, status)
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 519, in **exit**
> inputs.append(cPickle.load(f, **encoding))
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 125, in read
> input_processing_info = self._build_input_processing(shift_ratio=0)
> File "/examples/code/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2157, in _build_input_processing
> self._preread_check()
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 85, in _preread_check
> compat.as_bytes(self.__name), 1024 * 512, status)
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 519, in **exit**
> c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.NotFoundError: libhdfs.so: cannot open shared object file: No such file or directory
> c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.NotFoundError: libhdfs.so: cannot open shared object file: No such file or directory
> shift_ratio=shift_ratio)
> File "/examples/code/benchmarks/scripts/tf_cnn_benchmarks/preprocessing.py", line 640, in minibatch
> all_images, all_labels = dataset.read_data_files(subset)
> File "/examples/code/benchmarks/scripts/tf_cnn_benchmarks/datasets.py", line 168, in read_data_files
> inputs.append(cPickle.load(f, **encoding))
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 125, in read
> self._preread_check()
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 85, in _preread_check
> compat.as_bytes(self.__name), 1024 * 512, status)
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 519, in **exit**
> c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.NotFoundError: libhdfs.so: cannot open shared object file: No such file or directory
> 
> Primary job terminated normally, but 1 process returned
> a non-zero exit code. Per user-direction, the job has been aborted.
> 
> mpirun.real detected that one or more processes exited with non-zero status, thus causing
> the job to be terminated. The first process to do so was:
> 
> Process name: [[41865,1],2]
> Exit code: 1

你好，执行该命令hdfs dfs -put cifar10_dataset/. hdfs://myip:9000/my_pai_username/examples/tensorflow/distributed-cifar-10/data 是在master节点执行吗，master节点没有hdfs命令，需要在master节点配置hadoop吗

**Comment by mzmssg** [comment]
@JuiYang 
PAI的部署是在docker中，不会在host环境上安装hadoop。
因此必须在要上传数据的机器上下载hadoop binary。如果你不想单独配置hadoop，可以使用我们的[docker image](https://cloud.docker.com/u/openpai/repository/docker/openpai/hadoop-run)，将数据目录mount至container，在container内执行hdfs命令

**Comment by JuiYang** [comment]
> @JuiYang
> PAI的部署是在docker中，不会在host环境上安装hadoop。
> 因此必须在要上传数据的机器（不必是master，任意网络可达机器均可）上下载hadoop binary。如果你不想单独配置hadoop，可以使用我们的[docker image](https://hub.docker.com/r/openpai/hadoop-run)，将数据目录mount至container，在container内执行hdfs命令

这个镜像是伪分布式吗，这边报错了：safemode: FileSystem file:/// is not an HDFS file system

**Comment by apri30th** [comment]
@JuiYang  你好我也遇到了这个问题。safemode: FileSystem file:/// is not an HDFS file system  请问你解决了吗? 如果是的话，麻烦说下好吗？谢谢
