### ISSUE TITLE
Gateway Timeout

### ISSUE THREAD

**Issue by kakaluote** [microsoft/pai#2777]
i use "python paictl.py service start -n webportal" to start webportal.
but i got this error

> webportal is not ready yet. Please wait for a moment!
> Exception when calling CoreV1Api->list_pod_for_all_namespaces: (504)
> Reason: Gateway Timeout
> HTTP response headers: HTTPHeaderDict({'Date': 'Thu, 16 May 2019 11:49:16 GMT', 'Content-Length': '136', 'Content-Type': 'text/plain; charset=utf-8'})
> HTTP response body: {"metadata":{},"status":"Failure","message":"Timeout: request did not complete within 1m0s","reason":"Timeout","details":{},"code":504}

when this happend, the ssh connect looks like broken, no response with my command, and i ssh to master node, command hang. only i can do is restart machine.

**Comment by scarlett2018** [comment]
@kakaluote - sorry for the late responds, may you provide more information about your OpenPAI instance info for us as reference? You can follow the bug submission template to fill in the info:
https://github.com/microsoft/pai/issues/new?template=bug-report.md, thanks.

**Comment by fanyangCS** [comment]
close as no further response.
