### ISSUE TITLE
[INT Bed] Error on login 

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#2779]
When login as core on INT bed, hit this error:

![image](https://user-images.githubusercontent.com/39592018/57900644-3e772780-7894-11e9-9f48-9dbda1b83522.png)

**Comment by abuccts** [comment]
Already fixed in #2774.

**Comment by abuccts** [comment]
@sunqinzheng This issue hasn't been fixed completely. Here's a way to reproduce:
1. open webportal in a laptop and login
2. sleep the laptop for several hours
3. open the laptop again and use webportal

**Comment by fanyangCS** [comment]
@sunqinzheng, this happens when I submit a job selected from the marketplace.

**Comment by abuccts** [comment]
It's a cookie expiration bug, fixed in #2843.
