### ISSUE TITLE
Metrics graph for finished job should be narrow to the job's lifecycle

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#2781]
When viewing metrics graph for finished jobs, we should scroll to time job just finished. Currently we scroll to time by now. If jobs is not just finished, users need to shrink graph more and more until it covers job lift time to find it, and then zoom in again and again for proper scale.

**Comment by xudifsd** [comment]
The grafana dashboard accept arguments of `from` and `to`. To implement this feature, we can change the link to dashboard by adding these two arguments, just pass create timestamp and finished timestamp as the value should be ok.

BTW, We can also pass `from` if the job is running to avoid user zoom out to see metrics from the start.

**Comment by abuccts** [comment]
Already merged in #2797.
