### ISSUE TITLE
Clone job on INT bed did not update the JobName

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#2791]
_On INT Bed_

How to reproduce
1. in Home Page, my recent job, find one job; 
2. open the job, and click clone.

Expectation
the job will be cloned and able to submit

What I got
![image](https://user-images.githubusercontent.com/39592018/58007575-29f99000-7b1d-11e9-8e9e-544ae9120cb9.png)

**Note: the clone works well when I clone others' job.**

**Comment by abuccts** [comment]
Already merged in #2802.
