### ISSUE TITLE
the layout of the new home screen looks not right in a lower resolution screen(e.g., surface pro)

### ISSUE THREAD

**Issue by fanyangCS** [microsoft/pai#2798]
**Organization Name**:

**Short summary about the issue/question**:
![image](https://user-images.githubusercontent.com/5820832/58023453-6986a300-7b42-11e9-9564-0b0eb86ef8bb.png)

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by abuccts** [comment]
Already fixed in #2805.
