### ISSUE TITLE
How to do？

### ISSUE THREAD

**Issue by NothingLZ** [microsoft/pai#2800]
![image](https://user-images.githubusercontent.com/12367891/58073926-82d92f00-7bd6-11e9-9d68-af21eeed1f66.png)

**Comment by ydye** [comment]
pls check your cluster id through the url following. It's set by you when the first time to deploy openpai.
http://${master_ip}:9090/#!/configmap/default/pai-cluster-id?namespace=default

**Comment by NothingLZ** [comment]
![image](https://user-images.githubusercontent.com/12367891/58078976-8e325780-7be2-11e9-9684-1518599b824f.png)

**Comment by ydye** [comment]
You should open another issue and paste more detailed logs, thanks.
Cause the issue of cluster-id is solved, i will close it. Thanks.

**Comment by NothingLZ** [comment]
咱们有没有交流群呢，比如微信，QQ之类的

**Comment by scarlett2018** [comment]
@NothingLZ - 我们有Gitter Chatroom ==> https://gitter.im/Microsoft/pai?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by scarlett2018** [comment]
> You should open another issue and put more detailed logs.
> Cause the issue of cluster-id is solved, i will close it. Thanks.

closing this item as it has been fixed. Please find the team and OpenPAI community users for IM chatting in Gitter Chatroom.

**Comment by NothingLZ** [comment]
> @NothingLZ - 我们有Gitter Chatroom ==> https://gitter.im/Microsoft/pai?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

I think WeChat will be better.

**Comment by scarlett2018** [comment]
> I think it will be better for domestic developers WeChat.

It's okey to chat in the Gitter in Chinese. WeChat has too many personal info there, we did not open WeChat for discussion so far, thanks.
