### ISSUE TITLE
[Issue] Hardware view does not have any data, while K8s dashboard is able to list deployments.

### ISSUE THREAD

**Issue by NothingLZ** [microsoft/pai#2806]
![image](https://user-images.githubusercontent.com/12367891/58098654-a4550d80-7c0c-11e9-8bf8-1c81b34073af.png)

![image](https://user-images.githubusercontent.com/12367891/58098825-eb430300-7c0c-11e9-9774-b52edcb3fa0f.png)

**Comment by scarlett2018** [comment]
@NothingLZ - thanks for raising the issue, may you share more information about how you are deploying your cluster today follow the template https://github.com/microsoft/pai/issues/new?template=bug-report.md . we will need more information to get clue about what's happening there.

**Comment by fanyangCS** [comment]
close as no further response.
