### ISSUE TITLE
Why is the user not admin?

### ISSUE THREAD

**Issue by NothingLZ** [microsoft/pai#2807]
![image](https://user-images.githubusercontent.com/12367891/58142857-46134380-7c7b-11e9-8e76-41bf6a8f62b5.png)

![image](https://user-images.githubusercontent.com/12367891/58142811-1c5a1c80-7c7b-11e9-99de-38bd7c422c14.png)

**Comment by mzmssg** [comment]
PAI's authorization & authentication are out of hadoop. Thus the hadoop user is meaningless.
