### ISSUE TITLE
virtual cluster with chinese name ,how to delete it

### ISSUE THREAD

**Issue by zhaojizhuang4** [microsoft/pai#2812]
unfortunately i create a virtual cluster with chinese name  in privious version of openpai and the virtual cluster exist after seveal upgrade of openpai, i have tried many method to delete it ,but the virtual cluster in yarn maybe  is in a xml file ,so i cann't delete it like traditional database method  and we have many training job running in openpai ,i can't completely clean openpai.So i need your help,i have no idea ,thanks a lot ,emergency

**Comment by mzmssg** [comment]
What's your version?

**Comment by zhaojizhuang4** [comment]
0.11.0 thanks mzmssg

**Comment by mzmssg** [comment]
@zhaojizhuang4 
The name checker is added in 0.10, as a workaround, could you try to roll back some service to 0.9 to solve it.
Here is the process:
1. Change your [configuration](https://github.com/microsoft/pai/blob/6d6d93f158d9f2dabdff2bd72e915d901d6c7bd3/examples/cluster-configuration/services-configuration.yaml#L51) to v0.9.y
2. Push it to configmap
3. ./paictl.py service stop -n rest-server
4. ./paictl.py service start -n rest-server
5. delete vc

Then recover to current version similarly. We will consider add a compartibility.

**Comment by zhaojizhuang4** [comment]
thanks mzmssg ,if i use zookeeper tools to delete /confstore/CONF_STORE and restart hadoop resource manager ,could this method possible?

**Comment by mzmssg** [comment]
@zhaojizhuang4 
What's the error message?
If you want access hadoop directly, resource manager api is better
https://hadoop.apache.org/docs/r2.9.0/hadoop-yarn/hadoop-yarn-site/ResourceManagerRest.html#Scheduler_Configuration_Mutation_API

**Comment by zhaojizhuang4** [comment]
i will try your suggestion to use RM API,  i forget the error i don't  know where  the vc name encoding problem webportal  or rest api server or RM api  ,neverthereless this problem have been solved from v0.11.0 ,i will try your suggestion

**Comment by zhaojizhuang4** [comment]
friend mzmssg, just now ,follow your last surgestion   i have successfully deleted 智慧畜牧,
 i first use tcpdump to catch the vc create/update/delete op on webportal caused http flow  on 8088 port of hadoop rm , and use rested plugin of firefox  to simlate the http flow   and finally ,i get 3 gpu back , and my leader deep wang will be happy 
thanks a lot
