### ISSUE TITLE
What is the effect of cpu-vcore and mem settings in layout.yaml

### ISSUE THREAD

**Issue by Chenyangzh** [microsoft/pai#2821]
Hi, I am confused about machine-sku settings in layout.yaml file.machine-sku
The question is what the effects of mem and cpu-vcore? I changed the value of these two tags but there is no change in cluster. 
After I enlarged the mem from 128G to 256G and the vcore from 80 to 896, the Mem Avail and VCores Avail in hadoop webpage are same as before.

Following is the machine-sku settings in tutorial, and not too many explanation for this part.
machine-sku:
  k80-node:
    mem: 40G
    gpu:
      type: Tesla K80
      count: 4
    cpu:
      vcore: 24
    os: ubuntu16.04
  p100-node:
    mem: 20G
    gpu:
      type: Tesla P100
      count: 2
    cpu:
      vcore: 24
    os: ubuntu16.04

Anyone can help? Thanks!

**Comment by mzmssg** [comment]
We kept this part as a reference, we encourage to configure it, because something like metrics might get sku info here. 

For hadoop, it will automatically detect available resource in deployment, that's why changing here doesn't work.

**Comment by leonfg** [comment]
> 
> 
> We kept this part as a reference, we encourage to configure it, because something like metrics might get sku info here.
> 
> For hadoop, it will automatically detect available resource in deployment, that's why changing here doesn't work.

And how about GPU? What is the naming convention for GPUs? Can I use 'generic' for all the GPUs

**Comment by mzmssg** [comment]
It's allowed

**Comment by fanyangCS** [comment]
closed as no further response.
