### ISSUE TITLE
why not using port mapping

### ISSUE THREAD

**Issue by zhaojizhuang4** [microsoft/pai#2826]
hi, i wonder why the openpai not using docker port mapping cmd to prevent port collition ,or deppend on k8s to do multi user isolation, i am not understand how to write port range or what that exactly mean in webportal

**Comment by zhaojizhuang4** [comment]
thanks scarlett2018 and fanyangCS,  i mean if not using port mapping then why should user input port range because node manager can  auto detect which ports be used by user's docker on host network

**Comment by fanyangCS** [comment]
port mapping or k8s virtual network might slow down the network performance. Distributed jobs require the access to host network to achieve high performance training, thus openpai enables the use of host network by default, which may lead to port conflicts (e.g., ssh). 

If you have multiple NICs, it is possible to enable k8s virtual network or docker port mapping for network traffic that does not require high performance.

**Comment by zhaojizhuang4** [comment]
thanks fanyangCS,  I finally have a very reasonable answer from you to tell our users that port conflicts is very small uneasy  compared with high performance, In fact in our china telecom the most difficult to choose docker cloud platform production is the low performance of virtual switch network plugin , and  every node be gateway surely process more network flow  than one  network gatway . 
But i still do not understand how to write port range in webportal, i know maybe this is a hadoop problem and i should read your code in framworklaucher, but  i will be very glad if u give our your advise.
and we will deploy openpai on 30 nvidia p40 from our experience of using openpai stable for 3 months.
thanks! openpai is bravio

**Comment by abuccts** [comment]
Here's the [config spec](https://github.com/microsoft/pai/blob/master/docs/job_tutorial.md#specification), e.g.,
If you want to use port `3000` and `3001`, you can write
```
{
    "label": "port_alias",
    "beginAt": 3000,
    "portNumber": 2
}
```
then the system will allocate those two ports to you if they are not in use, otherwise the job will fail.

If you do not care about the port number, just want `2` ports, you can change the `beginAt` field to `"beginAt": 0`, the allocated ports can be get in environment variable `PAI_PORT_LIST_$taskRole_$taskIndex_$portLabel`.

**Comment by zhaojizhuang4** [comment]
thank u abuccts  very much, indeed the best way is user's code in docker to  use  PAI_PORT_LIST_$taskRole_$taskIndex_$portLabel  this environment variable to indicate what port number 
can listen to to  avoid port conflict in that node, 
and if not using such way, users want to directly indicate their specific ports ,this could cause job fail after they submit job, and ,i think it could be a better solution to tell user th!eir port have been used when they input port range in webportal, ou,i am wrong,the system can schedule port on free port node.
i think i have understand your system design. and frankly speeking, why user need to listen specific port if they just want to train their models and not for modal serving . 
thanks abuccts thanks !

**Comment by abuccts** [comment]
For distributed training, each container needs ports to communicate through Ethernet or InfiniBand. 
Here is an [example](https://github.com/tensorflow/examples/blob/master/community/en/docs/deploy/distributed.md#create-a-tftrainclusterspec-to-describe-the-cluster).

**Comment by zhaojizhuang4** [comment]
thanks abuccts very very much, your link is the best senario of understanding port  variables to coordinate distributed traing ,thank u very very much !
