### ISSUE TITLE
upgrade grafana to  latest version

### ISSUE THREAD

**Issue by satoshinakamora1995** [microsoft/pai#2828]
**Organization Name**:

**Short summary about the issue/question**:

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by scarlett2018** [comment]
@satoshinakamora1995 - the issue does not have any detail info about the problem or ask or background, I'm closing it for now. May you add more info and reopen it? thanks.
