### ISSUE TITLE
Enhance GPU assignment.

### ISSUE THREAD

**Issue by GeoffreyChen777** [microsoft/pai#2839]
**What would you like to be added**:
Prioritize those machines that already have tasks but have free GPUs.
**Why is this needed**:
Suppose that I have 2 workers, 4 GPUs on each one.
JobA uses 2 GPUs and runs on worker1. When JobB is submitted to OPENPAI, PAI might assign a GPU on worker2 to JobB.
Now the GPU usage is 2/4 and 1/4. I can't submit a 4 GPUs job.
I think OPENPAI should prioritize those machines that already have tasks but have free GPUs. For example, assign a GPU on worker1 to JobB.

**Components that may involve changes**:
YARN?

**Comment by mzmssg** [comment]
Yeah, we have it. 
https://github.com/microsoft/pai/blob/b2324866d0280a2d22958717ea6025740f71b9f0/subprojects/frameworklauncher/yarn/src/main/java/com/microsoft/frameworklauncher/common/model/LauncherConfiguration.java#L110

Default value of 2 means we choose 2 heaviest nodes, then randomly pick 1. You could set it 1 to avoid randomness. Then Every job will be assign to the heaviest node.
