### ISSUE TITLE
To be compatible with centos. Or what's more, is it possible to run pai on different os?

### ISSUE THREAD

**Issue by ydye** [Microsoft/pai#284]

**Comment by fanyangCS** [comment]
currently we have no plan to support OS other than Ubuntu 16.04LTS, we weclome contribution.

**Comment by fanyangCS** [comment]
This is out of the scope of OpenPAI. We should rely on community efforts for this kind of effort. 
e.g., https://github.com/wise2c-devops/breeze/blob/master/README.md
