### ISSUE TITLE
Single box install nvidia gforce 1080ti driver error

### ISSUE THREAD

**Issue by kenqxcheng** [microsoft/pai#2864]
![image](https://user-images.githubusercontent.com/4695796/58623314-4ad19a80-8300-11e9-80df-c22e9c8010f4.png)

**Comment by mzmssg** [comment]
Could you help the fix? https://github.com/microsoft/pai/issues/2446

**Comment by scarlett2018** [comment]
@kenqxcheng - does #2446 's fix work for you? could you please let us know the result? thanks.

**Comment by scarlett2018** [comment]
haven't got any feedback since May, closing it for now. feel free to reopen @kenqxcheng, if it is still an issue.
