### ISSUE TITLE
Allocated gpus number on webportal  is not the same actually used

### ISSUE THREAD

**Issue by zhaojizhuang4** [microsoft/pai#2872]
**Organization Name**:chinatelecom beijing research institute 

**Short summary about the issue/question**: allocated gpus is 10 and actually allocated is 9

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:  ubuntu16.04
- OpenPAI version: v0.11.0
- Cloud provider or hardware configuration: private deploy test bed
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):Nvidia P4000
- Others:

**Anything else we need to know**:
in pai_clusterview we see allocated gpus 10 but indeed only 9 we used, in the virtual cluster view on webportal the only vc default GPUs is 9

**Comment by xudifsd** [comment]
How many node do you have? And how many gpu cards in each node? Does this problem persist? What's the status of hadoop-resource-manager and yarn-exporter container?

**Comment by zhaojizhuang4** [comment]
hello xudifsd,  I found one former job which had been stopped   but in webportal monitor panel ,in joblevel matrix we can still see this job

**Comment by zhaojizhuang4** [comment]
I pssh  and grep all gpu node by job name keyword and find this running docker in one node which should 
have been stopped through manual op on web portal on job manage,and i find this docker's output showning "SIGTERM received, job may be killed by YARN",  but why it life power is so hard?

**Comment by zhaojizhuang4** [comment]
and after i exec  docker stop  ,in webportal monitor ui ,i  immediatly see this  lost gpu return to free pool,        but why yarn can not kill that docker  programly

**Comment by xudifsd** [comment]
@mzmssg Seems like a dockerScript bug?

**Comment by xudifsd** [comment]
@zhaojizhuang4 Can you provide more log of job container?

**Comment by mzmssg** [comment]
@zhaojizhuang4 
Could you provide the false stopped job logs, find it here
![image](https://user-images.githubusercontent.com/11887940/59003667-8103a280-8849-11e9-9dd1-cc2b71306faa.png)

**Comment by mzmssg** [comment]
@zhaojizhuang4 
And have you tried to zoom into this container and execute some commands? 
From our experience, there might be a zombie container: docker inspect/logs works, but further command such as docker exec doesn't. Then YARN might get messy.

**Comment by zhaojizhuang4** [comment]
@mzmssg hello , the last log in yarn tracking page is "[DEBUG] SIGTERM received, job may be killed by YARN" the former log  looks like  have no business with our issue,  unfortunately i have stopped that container and it looks like the container has no defference with others when running docker ps command. thanks ALL!
