### ISSUE TITLE
[Request]Is there a example of distributed training for tensorflow keras.backend model

### ISSUE THREAD

**Issue by edenbuaa** [microsoft/pai#2883]
if not, what instructions should i follow? 
thanks for any suggestion.

**Comment by abuccts** [comment]
* If you look for training on multiple GPU, you can find examples [here](https://github.com/keras-team/keras/tree/master/examples#keras-examples-directory) and refer to https://github.com/microsoft/pai/tree/master/examples/keras#mnist_tensorflow_backend.
* If you look for training on multiple nodes, you may refer to distributed TensorFlow ps-worker example https://github.com/microsoft/pai/tree/master/examples/tensorflow#distributed-tensorflow-cifar-10-image-classification.

**Comment by scarlett2018** [comment]
Thanks @edenbuaa for raising the question, hope document listed by @abuccts helps. It is highly appreciated if you can also commit examples once you get your codes work.
