### ISSUE TITLE
[AAD] End-to-End test AAD 

### ISSUE THREAD

**Issue by ydye** [microsoft/pai#2898]

**Comment by debuggy** [comment]
not in End June Release

**Comment by fanyangCS** [comment]
1. add/remove user (normal and admin)
2. grant/remove user access to some VC

**Comment by ydye** [comment]
@fanyangCS All have been done. And it has been added into UT.

**Comment by fanyangCS** [comment]
@ydye, please list all the test cases here, which are prepared for final release test.

**Comment by ydye** [comment]
- user api https://github.com/microsoft/pai/blob/master/src/rest-server/test/userManagement.js
- user crud https://github.com/microsoft/pai/blob/master/src/rest-server/test/userModelK8sCRUD.js
- user vc update ut https://github.com/microsoft/pai/blob/master/src/rest-server/test/userManagement.js#L779
- vc permission check api https://github.com/microsoft/pai/blob/master/src/rest-server/test/vc.js

**Comment by fanyangCS** [comment]
@ydye, can you design *end-to-end* test cases to cover those UTs?

**Comment by fanyangCS** [comment]
done.
