### ISSUE TITLE
[PureK8S] System storage solution for Pure K8S based PAI

### ISSUE THREAD

**Issue by wangdian** [microsoft/pai#2906]
Define system storage solution for Pure K8S based PAI.
In PAI, HDFS was used as the system storage to save the following things. Since Yarn is not included in Pure K8S based PAI, these data should be handled elsewhere.

Name | PAI | PAI-lite
-- | -- | --
YarnContainerScripts | Stored in HDFS | Not used
DockerContainerScripts | Stored in HDFS | Use kube-runtime   instead, generate in init container and share with job container.
FrameworkDescription | Stored in HDFS |  Ignore 
JobConfig | Stored in HDFS | Stored in ETCD using annotations
Ssh Key Files | Stored in HDFS | Managed by user
Job Output | Stored in HDFS | Stored in system NAS  / other NAS like team wise storage
User Logs | Handled by yarn | EFK / ELK / Other solution

Use k8s Persistent volume to decouple PAI-lite and real technique used for NAS.

Work items:
- [x] Refine kube-runtime for ENVs
- [x] Generate provision file for multi jobs
- [x] Read/write JobConfig. Using annotations to save in etcd (Work with #2933)
- [x] Migrate job-exporter to compatible with Pure K8S based PAI
- [x] Migrate webportal
- [x] Job Output Config. Create Persistent volume for Job Output
- [x] Refine deploy code 

optional
- [x] User Log solution

**Comment by fanyangCS** [comment]
done.
