### ISSUE TITLE
Replace the "Document" side bar with the "help" icon.

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#2908]
**Current** 
![image](https://user-images.githubusercontent.com/39592018/59174637-add6f300-8b84-11e9-85f4-f927d7a8f2bd.png)

**To be**
either 
![image](https://user-images.githubusercontent.com/39592018/59174658-c5ae7700-8b84-11e9-81d0-0719be72581c.png)
or something like
![image](https://user-images.githubusercontent.com/39592018/59174703-03ab9b00-8b85-11e9-901c-bc33cdf2bc9c.png)

**Comment by debuggy** [comment]
assign @sunqinzheng to check it out
