### ISSUE TITLE
webportal can't show legacy job log 

### ISSUE THREAD

**Issue by mzmssg** [microsoft/pai#2917]
**Organization Name**:
Microsoft

**Short summary about the issue/question**:
v0.13 rename job logs:
```
stdout -> user.pai.stdout
stderr -> user.pai.stderr
```
A job submitted before v0.13 has an old-style logname like `stdout`, but new webportal try to retrive new-style name, like `user.pai.stdout`:
![image](https://user-images.githubusercontent.com/11887940/59263779-4ef0a700-8c74-11e9-9407-72928a84658f.png)

**OpenPAI Environment**:
- OpenPAI version: v0.13

**Comment by debuggy** [comment]
status unknown

**Comment by fanyangCS** [comment]
fixed.
