### ISSUE TITLE
How to integrate pai with vs tools for ai/vscode tools for ai?

### ISSUE THREAD

**Issue by ueqt** [Microsoft/pai#292]
Hi, as I know we can submit jobs to pai from vs tools for ai, but I don't know how to implement it, could you write some document about it?, how to add pai to Azure Batch AI/Clusters, and use pai job to run it?

**Comment by fanyangCS** [comment]
We are working on it.

**Comment by ueqt** [comment]
Do you have roadmap or timeline about it? Or any other docs about it to share?

**Comment by fanyangCS** [comment]
in a few months

**Comment by fanyangCS** [comment]
vs-tools-for-ai has announced the support to OpenPAI.
https://marketplace.visualstudio.com/items?itemName=ms-toolsai.vstoolsai-vs2017
