### ISSUE TITLE
Merge user stdout & stderr

### ISSUE THREAD

**Issue by mzmssg** [microsoft/pai#2934]
**What would you like to be added**:

A merged log

**Why is this needed**:

v0.13 seperates user stdout and stderr, it brings two bad experience:
1. Python logging module write log to stderr, user might be confused why stdout is empty.
2. Without a merged log, it's hard to get a clear command timeline

**Without this feature, how does the current module work**:
Users add timestamp in their output module

**Components that may involve changes**:
runtime

**Comment by Binyang2014** [comment]
Close this issue, further progress please refer to #3246
