### ISSUE TITLE
关于checkToken时获取用户信息的逻辑的实现原理

### ISSUE THREAD

**Issue by damon008** [microsoft/pai#2937]
如下图：在解析token的时候，请问为何可以通过req.user.username，req.user.admin获取用户信息。如果是获取其他服务sign生成的token，该如何处理，从而获取其生成的token的用户信息。
![image](https://user-images.githubusercontent.com/25023599/59421138-b0de1780-8e00-11e9-91a9-5efa4c23ff44.png)

**Comment by abuccts** [comment]
`req.user` is set by [jwt express middleware](https://github.com/auth0/express-jwt#usage).

It depends if you use other services to generate tokens, you may cannot get username from that token. But you can always write your own middlewares.

**Comment by damon008** [comment]
@abuccts 现在是第三方生成的token，那rest-server如何确保可以获取用户信息呢？

**Comment by damon008** [comment]
现在想通过第三方生成的token来验证，生成的token的密钥都知道，然后rest-server又可以跟现在一样全局可以获取用户信息。请问怎样可处理呢？

**Comment by ydye** [comment]
Do you mean OIDC?

**Comment by damon008** [comment]
我的想法是认证中心在别人那，但是认证的思路以及密钥这边都知道，这边作为客户端想通过认证中心生成的token在rest-server全局拿到用户信息。

**Comment by ydye** [comment]
一般第三方返回的Token内会有user的一些信息，你可以通过这些信息，做一些后台逻辑。
以AAD为例子，我们会利用Azure AD 做user的认证，拿到authcode，然后rest-server会利用这个code去向AzureAD请求user的Token，从Token里面parse出必要的信息，如果user还不存在于OpenPAI内，则会重新create一个user，如果user已经存在，则还是利用之前的OpenPAI自己的Token middleware 签发一个JWT

**Comment by damon008** [comment]
@ydye 我理解你的意思是：通过对方的token鉴权，成功后在这边继续生成rest-server的token，然后通过其来获取用户信息。但是这样就需要前端还是每次获取任务时都得传rest-server的token来获取用户的信息。我的目标是只要传第三方生成的token就可以获取任务信息。不需要再传rest-server的token来获取任务信息。

**Comment by abuccts** [comment]
You can implement your own `jwt.verify` [here](https://github.com/microsoft/pai/blob/master/src/rest-server/src/middlewares/token.js#L28-L29).

**Comment by damon008** [comment]
@abuccts 请问你说的这个是对第三方生成的token进行verify吗？那secret对应的是对方的secret? 这样可以获取的result会拿到信息吗？

**Comment by abuccts** [comment]
You haven't provided any information about the 3rd party token or secret you are talking about. I cannot know what's the secret or how to verify your token.

**Comment by damon008** [comment]
@GerHut 您好，了解到您有参与更新了鉴权后获取用户信息的逻辑。想请问下，如何在通过第三方鉴权后获取其生成的token，然后在rest-server通过token获取用户信息。我看新逻辑中有req.param,req.query等，这些是怎样的原理呢？

**Comment by damon008** [comment]
@abuccts 不提供，怎么通过token、secret怎么获取token的用户信息呢？我认为jwt.verify方法需要token与其secret才能解析获取result。

**Comment by damon008** [comment]
@abuccts 不提供，怎么通过token、secret怎么获取token的用户信息呢？我认为jwt.verify方法需要token与其secret才能解析获取result。

**Comment by abuccts** [comment]
What's your token? What's your secret? How do you generate token for user?
Nobody knows how to get user from the token you generated without any information.

**Comment by scarlett2018** [comment]
Hi @damon008 - 能帮忙提供更多您想了解这个实现的背景原因么？我是项目的PM,从您发表的问题，我不能确定您想解决的到底是什么问题。

我们有问题背景提示模板，请配合填写，以帮助我们更了解问题，从而解决问题，谢谢。

Organization Name:

Short summary about the issue/question:

Brief what process you are following:

How to reproduce it:

OpenPAI Environment:

OpenPAI version:
Cloud provider or hardware configuration:
OS (e.g. from /etc/os-release):
Kernel (e.g. uname -a):
Hardware (e.g. core number, memory size, storage size, GPU type etc.):
Others:
Anything else we need to know:

**Comment by damon008** [comment]
@scarlett2018 您好，我这边想的需求是rest-server其实也只是一个client，通过一个认证中心鉴权后获取其token，UI每次请求中在头部提供这个token给rest-server即可，rest-server拿到其检验下并获取里面的用户信息。因为我们不想通过rest-server来生成token，只想有一个认证中心鉴权即可，并且这个token是这个认证中心生成的。

**Comment by scarlett2018** [comment]
@damon008 我们有问题背景提示模板，请配合填写，以帮助我们更了解问题，从而解决问题，谢谢。

Organization Name:

Short summary about the issue/question:

Brief what process you are following:

How to reproduce it:

OpenPAI Environment:

OpenPAI version:
Cloud provider or hardware configuration:
OS (e.g. from /etc/os-release):
Kernel (e.g. uname -a):
Hardware (e.g. core number, memory size, storage size, GPU type etc.):
Others:
Anything else we need to know:

**Comment by damon008** [comment]
@scarlett2018 你好，我可能找到解决的思路了。
