### ISSUE TITLE
An issue occure when starting up hadoop-data-node

### ISSUE THREAD

**Issue by fengzifrank** [microsoft/pai#2948]
hadoop-data-node is not ready yet. Please wait for a moment!
hadoop-data-node is not ready yet. Please wait for a moment!
hadoop-data-node is not ready yet. Please wait for a moment!
hadoop-data-node is not ready yet. Please wait for a moment!
hadoop-data-node is not ready yet. Please wait for a moment!
hadoop-data-node is not ready yet. Please wait for a moment!
hadoop-data-node is not ready yet. Please wait for a moment!
hadoop-data-node is not ready yet. Please wait for a moment!
hadoop-data-node is not ready yet. Please wait for a moment!
hadoop-data-node is not ready yet. Please wait for a moment!
hadoop-data-node is not ready yet. Please wait for a moment!
hadoop-data-node is not ready yet. Please wait for a moment!

[ERROR] - deployment.paiLibrary.common.linux_shell : Failed to execute the start script of service hadoop-data-node
2019-06-16 09:33:27,431 [ERROR] - deployment.paiLibrary.paiService.service_management_start : Failed to start service hadoop-data-node
2019-06-16 09:33:27,432 [INFO] - deployment.paiLibrary.paiService.service_management_start : -----------------------------------------------------------
2019-06-16 09:33:27,432 [ERROR] - deployment.paiLibrary.paiService.service_management_start : Have retried 5 times, but service hadoop-data-node doesn't start. Please check it.

Is this a configuration file or a network problem? Thank you.

**Comment by abuccts** [comment]
You need to go to k8s dashboard (http://your_master_ip:9090) and paste hadoop data node's log, here is [an instruction](https://github.com/microsoft/pai/blob/master/docs/pai-management/doc/validate-deployment.md#11-check-drivers-services-log-).

You can also share your configuration files if you are not sure about them, please remove sensitive information like ip and password first.

**Comment by fengzifrank** [comment]
Thanks a lot for this is my profile  services-configuration.yaml    
cluster:
  common:
    cluster-id: pai-example
  #
  #  # HDFS, zookeeper data path on your cluster machine.
    data-path: "/datastorage"

  # the docker registry to store docker images that contain system services like frameworklauncher, hadoop, etc.
  docker-registry:

    # The namespace in your registry. If the registry is docker.io, the namespace will be your user account.
    namespace: openpai

    # E.g., gcr.io.
    # if the registry is hub.docker, please fill this value with docker.io
    domain: docker.io
    # If the docker registry doesn't require authentication, please comment username and password
    #username: <username>
    #password: <password>

    tag: v0.13.0


    # The name of the secret in kubernetes will be created in your cluster
    # Must be lower case, e.g., regsecret.
    secret-name: pai-secret


#Uncomment following lines if you want to customize yarn
#hadoop-resource-manager:
#  # job log retain time
#  yarn_log_retain_seconds: 2592000
#  # port for yarn exporter
#  yarn_exporter_port: 9459


#Uncomment following lines if you want to customize hdfs
#hadoop-data-node:
#  # storage path for hdfs, support comma-delimited list of directories, eg. /path/to/folder1,/path/to/folder2 ...
#  # if left empty, will use cluster.common.data-path/hdfs/data
#  storage_path:


# uncomment following if you want to change customeize yarn-frameworklauncher
#yarn-frameworklauncher:
#  frameworklauncher-port: 9086


rest-server:
  # database admin username
  default-pai-admin-username: admin
  # database admin password
  default-pai-admin-password: admin-password


# uncomment following section if you want to customize the port of web portal
# webportal:
#   server-port: 9286

# uncomment following if you want to change customeize grafana
# grafana:
#   port: 3000

# uncomment following if you want to change customeize drivers
#drivers:
#  set-nvidia-runtime: false
#  # You can set drivers version here. If this value is miss, default value will be 384.111
#  # Current supported version list
#  # 384.111
#  # 390.25
#  # 410.73
#  version: "384.111"

# uncomment following if you want node-exporter listen to different port
# node-exporter:
#   port: 9100

# uncomment following if you want to customeize job-exporter
# job-exporter:
#   port: 9102
#   logging-level: INFO
#   interface: eth0,eno2

# if you want to enable alert manager to send alert email, uncomment following lines and fill
# the right values.
# alert-manager:
#   receiver: your_addr@example.com
#   smtp_url: smtp.office365.com:587
#   smtp_from: alert_sender@example.com
#   smtp_auth_username: alert_sender@example.com
#   smtp_auth_password: password_for_alert_sender
#   port: 9093 # this is optional, you should not write this if you do not want to change the port alert-manager is listening on

# uncomment following if you want to change customeize prometheus
# prometheus:
#   port: 9091
#   # How frequently to scrape targets
#   scrape_interval: 30
#
#   # if you want to use key file to login nodes
#   

# uncomment following section if you want to customize the port of pylon
# pylon:
#  port: 80

# uncomment following section if you want to customize the threshold of cleaner
# cleaner:
#  threshold: 94
#  interval: 60

**Comment by fengzifrank** [comment]
cluster:
  common:
    cluster-id: pai-example
  #
  #  # HDFS, zookeeper data path on your cluster machine.
    data-path: "/datastorage"

  # the docker registry to store docker images that contain system services like frameworklauncher, hadoop, etc.
  docker-registry:

    # The namespace in your registry. If the registry is docker.io, the namespace will be your user account.
    namespace: openpai

    # E.g., gcr.io.
    # if the registry is hub.docker, please fill this value with docker.io
    domain: docker.io
    # If the docker registry doesn't require authentication, please comment username and password
    #username: <username>
    #password: <password>

    tag: v0.13.0


    # The name of the secret in kubernetes will be created in your cluster
    # Must be lower case, e.g., regsecret.
    secret-name: pai-secret


#Uncomment following lines if you want to customize yarn
#hadoop-resource-manager:
#  # job log retain time
#  yarn_log_retain_seconds: 2592000
#  # port for yarn exporter
#  yarn_exporter_port: 9459


#Uncomment following lines if you want to customize hdfs
#hadoop-data-node:
#  # storage path for hdfs, support comma-delimited list of directories, eg. /path/to/folder1,/path/to/folder2 ...
#  # if left empty, will use cluster.common.data-path/hdfs/data
#  storage_path:


# uncomment following if you want to change customeize yarn-frameworklauncher
#yarn-frameworklauncher:
#  frameworklauncher-port: 9086


rest-server:
  # database admin username
  default-pai-admin-username: admin
  # database admin password
  default-pai-admin-password: admin-password


# uncomment following section if you want to customize the port of web portal
# webportal:
#   server-port: 9286

# uncomment following if you want to change customeize grafana
# grafana:
#   port: 3000

# uncomment following if you want to change customeize drivers
#drivers:
#  set-nvidia-runtime: false
#  # You can set drivers version here. If this value is miss, default value will be 384.111
#  # Current supported version list
#  # 384.111
#  # 390.25
#  # 410.73
#  version: "384.111"

# uncomment following if you want node-exporter listen to different port
# node-exporter:
#   port: 9100

# uncomment following if you want to customeize job-exporter
# job-exporter:
#   port: 9102
#   logging-level: INFO
#   interface: eth0,eno2

# if you want to enable alert manager to send alert email, uncomment following lines and fill
# the right values.
# alert-manager:
#   receiver: your_addr@example.com
#   smtp_url: smtp.office365.com:587
#   smtp_from: alert_sender@example.com
#   smtp_auth_username: alert_sender@example.com
#   smtp_auth_password: password_for_alert_sender
#   port: 9093 # this is optional, you should not write this if you do not want to change the port alert-manager is listening on

# uncomment following if you want to change customeize prometheus
# prometheus:
#   port: 9091
#   # How frequently to scrape targets
#   scrape_interval: 30
#
#   # if you want to use key file to login nodes
#   

# uncomment following section if you want to customize the port of pylon
# pylon:
#  port: 80

# uncomment following section if you want to customize the threshold of cleaner
# cleaner:
#  threshold: 94
#  interval: 60

**Comment by fengzifrank** [comment]
quick-start.yaml 
machines:
  - 192.168.2.15
  - 192.168.2.15

# (Required) Log-in info of all machines. System administrator should guarantee
# that the username/password pair is valid and has sudo privileg
ssh-username: qaz123
ssh-password:  qaz123

# (Optional, default=22) Port number of ssh service on each machine.
#ssh-port: 22

# (Optional, default=DNS of the first machine) Cluster DNS.
#dns: <ip-of-dns>

# (Optional, default=10.254.0.0/16) IP range used by Kubernetes. Note that
# this IP range should NOT conflict with the current network.
#service-cluster-ip-range: <ip-range-for-k8s>
layout.yaml
kubernetes:
  api-servers-url: http://192.168.2.15:8080
  dashboard-url: http://192.168.2.15:9090

# TODO please modify it according to your own hardware
machine-sku:
  GENERIC:
    mem: 40
    gpu:
      type: generic
      count: 1
    cpu:
      vcore: 10
    os: ubuntu16.04

machine-list:
  - dashboard: "true"
    docker-data: "/var/lib/docker"
    etcdid: "etcdid1"
    hostip: "192.168.2.15"
    hostname: "ububuntu"
    k8s-role: "master"
    machine-type: "GENERIC"
    nodename: "192.168.2.15"
    pai-master: "true"
    password: "qaz123"
    ssh-port: "22"
    username: "qaz123"
    zkid: "1"
