### ISSUE TITLE
hardware: network requirement for PAI

### ISSUE THREAD

**Issue by Jong-Won** [microsoft/pai#2949]
We would like to build a GPU cluster of 10 servers. Maybe we will train distrubuted models (multi machine). I don't whether network will be bottleneck.
Is there any request for network?  standard gigabit network or 10G Network or IB network(InfiniBand)？

**Comment by abuccts** [comment]
Ethernet is OK and InfiniBand will be much faster, it depends on your workload. PAI just runs jobs in Docker container and uses host network.

**Comment by scarlett2018** [comment]
@Jong-Won thanks for raising the question. Would you mind fill in more information for us to reference? thanks.

Organization Name:
OpenPAI version:
Cloud provider or hardware configuration:
OS (e.g. from /etc/os-release):
Kernel (e.g. uname -a):
Hardware (e.g. core number, memory size, storage size, GPU type etc.):
Others:
Anything else we need to know:

**Comment by IdiosyncraticDragon** [comment]
@abuccts I was trying to make two taskroles (insie the same job) to communicate with each other by network. Is there any document about the how to congigure the networking of containers in PAI? As you said, PAI uses host network, can the user specifiy the port for each taskrole?

**Comment by fanyangCS** [comment]
here is an example. https://github.com/microsoft/pai/blob/master/marketplace-v2/tensorflow-cifar10.yaml. 
For details, please refer to https://github.com/microsoft/pai/blob/master/docs/job_tutorial.md.
