### ISSUE TITLE
关于任务状态显示

### ISSUE THREAD

**Issue by damon008** [microsoft/pai#2958]
Hello ，关于任务状态：在FL中，executionType= START，frameworkState=APPLICATION_WAITING，此时这个任务已经分配到容器，处于运行状态，但是在展示这块还是显示waiting状态。这块逻辑判断jobState = waiting，返回给webportal。是否存在问题呢?
![image](https://user-images.githubusercontent.com/25023599/59666069-b1065a80-91e6-11e9-8484-bb4ee1390b1f.png)

**Comment by damon008** [comment]
@abuccts  Is there a problem with the state of this job? Please answer it.

**Comment by yqwang-ms** [comment]
1. App running need all tasks running, instead of any task running.
2. Even if all task running, there is latency between all task running and FL detects it. I.e. it is eventually consistent.

**Comment by damon008** [comment]
@yqwang-ms just only one taskRole and only one container

**Comment by yqwang-ms** [comment]
Even if all task running, there is latency between all task running and FL detects it. I.e. it is eventually consistent.

**Comment by yqwang-ms** [comment]
If the latency is very long, such as > 10min, please check FL and YARN logs

**Comment by damon008** [comment]
@yqwang-ms 你说的时间很长，而且保持很久这种状态，所以诧异，日志也并未看到啥结果。所以这块的判断是否存在问题呢?不管是framework 、app、还是container。

**Comment by yqwang-ms** [comment]
We need logs to further investigate, otherwise we also do not know why

**Comment by scarlett2018** [comment]
@damon008 - thanks for raising questions, please feel free to submit PR if you think any logic in codes are not as expected.
