### ISSUE TITLE
ERROR: The Nouveau kernel driver is currently in use by your system

### ISSUE THREAD

**Issue by leepengcheng** [microsoft/pai#2962]
i installed pai in singlebox,the nvidia-driver was uninstalled. 
is there a simpe way to install openpai without uninstall nvidia-driver?

### Environment
OpenPAI version:V0.13.0
OS :ubuntu 16.04
GPU: 1080ti x 4
MEM:128G

the error logs of openpai/drivers-384.111  container is:
--------------------------------------------------------------------------------------------------------------------
+ export MLNX_PREFIX=/var/drivers/mellanox/MLNX_OFED_LINUX-4.2-1.2.0.0-ubuntu16.04-x86_64/usermode
+ MLNX_PREFIX=/var/drivers/mellanox/MLNX_OFED_LINUX-4.2-1.2.0.0-ubuntu16.04-x86_64/usermode
+ export NV_DRIVER=/var/drivers/nvidia/384.111
+ NV_DRIVER=/var/drivers/nvidia/384.111
+ export LIBRARY_PATH=/usr/local/cuda/lib64/stubs:/var/drivers/mellanox/MLNX_OFED_LINUX-4.2-1.2.0.0-ubuntu16.04-x86_64/usermode/lib
+ LIBRARY_PATH=/usr/local/cuda/lib64/stubs:/var/drivers/mellanox/MLNX_OFED_LINUX-4.2-1.2.0.0-ubuntu16.04-x86_64/usermode/lib
+ export LD_LIBRARY_PATH=/var/drivers/mellanox/MLNX_OFED_LINUX-4.2-1.2.0.0-ubuntu16.04-x86_64/usermode/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/var/drivers/nvidia/384.111/lib:/var/drivers/nvidia/384.111/lib64:/usr/local/cuda/lib64
+ LD_LIBRARY_PATH=/var/drivers/mellanox/MLNX_OFED_LINUX-4.2-1.2.0.0-ubuntu16.04-x86_64/usermode/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/var/drivers/nvidia/384.111/lib:/var/drivers/nvidia/384.111/lib64:/usr/local/cuda/lib64
+ export PATH=/var/drivers/mellanox/MLNX_OFED_LINUX-4.2-1.2.0.0-ubuntu16.04-x86_64/usermode/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/drivers/nvidia/384.111/bin
+ PATH=/var/drivers/mellanox/MLNX_OFED_LINUX-4.2-1.2.0.0-ubuntu16.04-x86_64/usermode/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/drivers/nvidia/384.111/bin
+ export C_INCLUDE_PATH=/var/drivers/mellanox/MLNX_OFED_LINUX-4.2-1.2.0.0-ubuntu16.04-x86_64/usermode/include:/var/drivers/mellanox/MLNX_OFED_LINUX-4.2-1.2.0.0-ubuntu16.04-x86_64/usermode/include/infiniband
+ C_INCLUDE_PATH=/var/drivers/mellanox/MLNX_OFED_LINUX-4.2-1.2.0.0-ubuntu16.04-x86_64/usermode/include:/var/drivers/mellanox/MLNX_OFED_LINUX-4.2-1.2.0.0-ubuntu16.04-x86_64/usermode/include/infiniband
+ export CPLUS_INCLUDE_PATH=/var/drivers/mellanox/MLNX_OFED_LINUX-4.2-1.2.0.0-ubuntu16.04-x86_64/usermode/include:/var/drivers/mellanox/MLNX_OFED_LINUX-4.2-1.2.0.0-ubuntu16.04-x86_64/usermode/include/infiniband
+ CPLUS_INCLUDE_PATH=/var/drivers/mellanox/MLNX_OFED_LINUX-4.2-1.2.0.0-ubuntu16.04-x86_64/usermode/include:/var/drivers/mellanox/MLNX_OFED_LINUX-4.2-1.2.0.0-ubuntu16.04-x86_64/usermode/include/infiniband
+ lspci
+ grep -qE '[0-9a-fA-F][0-9a-fA-F]:[0-9a-fA-F][0-9a-fA-F].[0-9] (3D|VGA compatible) controller: NVIDIA Corporation.*'
+ '[' -f /usr/local/nvidia/bin/nvidia-smi ']'
+ /bin/bash -x install-nvidia-drivers
++ uname -r
+ KERNEL_FULL_VERSION=4.15.0-51-generic
+ CURRENT_DRIVER=/var/drivers/nvidia/current
+ echo ======== If NVIDIA present exit early =========
+ nvidiaPresent
+ [[ -f /proc/driver/nvidia/version ]]
======== If NVIDIA present exit early =========
+ return 1
+ '[' 1 == 0 ']'
+ echo ======== If NVIDIA driver already running uninstall it =========
======== If NVIDIA driver already running uninstall it =========
+ lsmod
+ grep -qE '^nvidia'
+ echo === Building and installing NVIDIA modules
+ echo /var/drivers/nvidia/384.111/lib
=== Building and installing NVIDIA modules
+ echo /var/drivers/nvidia/384.111/lib64
+ mkdir -p /var/drivers/nvidia/384.111/lib /var/drivers/nvidia/384.111/lib64 /var/drivers/nvidia/384.111/bin
+ ./NVIDIA-Linux-x86_64-384.111/nvidia-installer --utility-prefix=/var/drivers/nvidia/384.111 --opengl-prefix=/var/drivers/nvidia/384.111 --x-prefix=/var/drivers/nvidia/384.111 --compat32-prefix=/var/drivers/nvidia/384.111 --opengl-libdir=lib64 --utility-libdir=lib64 --x-library-path=lib64 --compat32-libdir=lib --dkms -a -s -N

WARNING: The '--no-network' option is deprecated:  nvidia-installer will
         ignore this option.

ERROR: The Nouveau kernel driver is currently in use by your system.  This
       driver is incompatible with the NVIDIA driver, and must be disabled
       before proceeding.  Please consult the NVIDIA driver README and your
       Linux distribution's documentation for details on how to correctly
       disable the Nouveau kernel driver.

ERROR: Installation has failed.  Please see the file
       '/var/log/nvidia-installer.log' for details.  You may find
       suggestions on fixing installation problems in the README available
       on the Linux driver download page at www.nvidia.com.

+ echo === Loading NVIDIA UVM module
+ modprobe nvidia-uvm
=== Loading NVIDIA UVM module
modprobe: FATAL: Module nvidia-uvm not found in directory /lib/modules/4.15.0-51-generic

**Comment by ydye** [comment]
Have you try to manually disable Nouveau before installing nvidia drivers?

**Comment by leepengcheng** [comment]
> Have you try to manually disable Nouveau before installing nvidia drivers?
yes,i try disabled Nouveau and then can not access the system...
this problem make me crazy

**Comment by ydye** [comment]
@leepengcheng Can you paste the command or process that you disable nouveau?

**Comment by leepengcheng** [comment]
> @leepengcheng Can you paste the command or process that you disable nouveau?

## uninstall nvidia
sudo apt remove --purge nvidia-*

## disable nouveau
sudo gedit /etc/modprobe.d/blacklist.conf
blacklist nouveau
options nouveau modeset=0
sudo update-initramfs -u
sudo reboot

after reinstall openpai,the drivers-one-shot container show error:
---------------------------------------------------------------------------------------
Error: failed to start container "nvidia-drivers": Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:407: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=9.1 --pid=15859 /var/lib/docker/overlay2/6532806090db4c3592779b2732bd77cd4e9e994ef274de8500dc144db175a014/merged]\\\\nnvidia-container-cli: requirement error: unsatisfied condition: cuda >= 9.1\\\\n\\\"\"": unknown
Back-off restarting failed container



i use default drivers config

**Comment by leepengcheng** [comment]
It's so strange that i slove this problem by delete /datastorage and reinstall pai.
