### ISSUE TITLE
关于手动stop的任务无法获取其容器结束的时间containerCompletedTimestamp

### ISSUE THREAD

**Issue by damon008** [microsoft/pai#2963]
大家好，对于FL接口***:9086/v1/Frameworks/:jobName，获取任务明细时，当前任务如果是手动stop，发现该接口提供的containerCompletedTimestamp为null。

**Comment by damon008** [comment]
请问这个是否可以修复呢?

**Comment by abuccts** [comment]
The job hasn't completed yet, you can still start it again.

**Comment by damon008** [comment]
@abuccts start it 我的理解是run一个新容器了，不是继续运行上个容器吧？如果是，那么请问调用哪个接口可以继续运行那个容器呢？还有在stop后，该容器处于什么状态呢？仍然存在，不在running？

**Comment by damon008** [comment]
@abuccts 你好，我不懂你说的start还是submit and run还是其他的。

**Comment by abuccts** [comment]
You are asking framework launcher's api, so if you want to START a framework after STOP it, you can use [`PUT ExecutionType` api](https://github.com/microsoft/pai/blob/master/subprojects/frameworklauncher/yarn/doc/USERMANUAL.md#put-executiontype).

If you just want to know when you stopped it or when it stopped, you can use `lastRequestTimestamp` and `frameworkCompletedTimestamp`.

**Comment by damon008** [comment]
@abuccts  These properties what you said can not be a reflection of reality about containers.

**Comment by yqwang-ms** [comment]
This is already resolved in https://github.com/microsoft/pai/pull/2635.
Please upgrade your PAI.

**Comment by damon008** [comment]
@yqwang-ms  only update file:frameworklauncher/yarn/src/main/java/com/microsoft/frameworklauncher/webserver/StatusManager.java?

**Comment by yqwang-ms** [comment]
Please update all in PR.

**Comment by scarlett2018** [comment]
@damon008 - everything good after update your PAI to latest?

**Comment by fanyangCS** [comment]
closed as no further response.

**Comment by yqwang-ms** [comment]
@damon008 
The completion time is refined to be more accurate in https://github.com/microsoft/frameworkcontroller/pull/27.
And will be leveaged in pure k8s version PAI soon.
