### ISSUE TITLE
delete job

### ISSUE THREAD

**Issue by leepengcheng** [microsoft/pai#2969]
i try deploy nni on openpai and found very trial will generate a job,so when trial number=1000,there will be 1000 jobs. there are also  many test and unuseful jobs, i want delete them instead of stop.

so many temporary jobs are difficult to manage.

for OpenPAI VS Code Client,it is absolutely impossible to find the job.

**Comment by scarlett2018** [comment]
Thanks @leepengcheng for the feedback. When you say delete jobs, do you want to permanently delete the jobs, or just want to delete them from the Web UI (REST API)? is there a need to get the trials back?

**Comment by leepengcheng** [comment]
> Thanks @leepengcheng for the feedback. When you say delete jobs, do you want to permanently delete the jobs, or just want to delete them from the Web UI (REST API)? is there a need to get the trials back?
> 
> BTW, would you mind provide more info about how you are using PAI+NNI today:
> Organization Name:
> 
> Short summary about the issue/question:
> 
> Brief what process you are following:
> 
> How to reproduce it:
> 
> OpenPAI Environment:
> 
> OpenPAI version:
> Cloud provider or hardware configuration:
> OS (e.g. from /etc/os-release):
> Kernel (e.g. uname -a):
> Hardware (e.g. core number, memory size, storage size, GPU type etc.):
> Others:
> Anything else we need to know:
------------------------------------------------------------------------
OpenPAI version:v0.13.0
i use the nni's  mnist-tensorflow pai deploy example
i need  permanently delete the jobs,most of them are test job / wrong-config job or temp job.

**Comment by scarlett2018** [comment]
Adding @SparkSnail @yds05 @qfyin @mydmdm @squirrelsc for comments on the feature, I'm considering  add this to July release.
