### ISSUE TITLE
Filter User: It's very hard to find a user when the user list is very long

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#2970]
May need to provide **Search** for the filter..
![image](https://user-images.githubusercontent.com/39592018/59894240-6ec16100-9412-11e9-8545-3d1e1a439186.png)

**Comment by yangou1988** [comment]
Add a search bar
Check box 
Limit max height: 240px

![Filter](https://user-images.githubusercontent.com/44491713/59896433-20649000-941b-11e9-95db-6d55ea1822c2.png)

**Comment by debuggy** [comment]
have not done yet
