### ISSUE TITLE
Support RTX2080

### ISSUE THREAD

**Issue by hellocandy** [microsoft/pai#3002]
**Organization Name**: advantech

**Short summary about the issue/question**: When will the openpai support RTX2080. 

**Brief what process you are following**: We planed to use RTX2080, however the driver imported in openpai do not support this device.

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by GeoffreyChen777** [comment]
@hellocandy 
Can you provide the version of your OpenPAI?
Since Ver.0.9, OpenPAI supports 384.111, 390.25 and 410.73, I think RTX2080 can work with 410.73.
You can change the driver version in the services configuration: https://github.com/microsoft/pai/blob/a75e56a4f60a7df30dfc082a36c91eeb4aea3325/examples/cluster-configuration/services-configuration.yaml#L108

**Comment by zhiltsov-max** [comment]
RTX2080 should work well with 410.73, but there is a problem with `job-exproter` service. For a reason, `nvidia-smi`  has a different output for RTX devices in ECC (`ecc_errors`) part:

GTX
```
<ecc_errors>
    <volatile>
        <single_bit>
            <device_memory>N/A</device_memory>
            <register_file>N/A</register_file>
            <l1_cache>N/A</l1_cache>
            <l2_cache>N/A</l2_cache>
            <texture_memory>N/A</texture_memory>
            <texture_shm>N/A</texture_shm>
            <cbu>N/A</cbu>
            <total>N/A</total>
        </single_bit>
        <double_bit>
            <device_memory>N/A</device_memory>
            <register_file>N/A</register_file>
            <l1_cache>N/A</l1_cache>
            <l2_cache>N/A</l2_cache>
            <texture_memory>N/A</texture_memory>
            <texture_shm>N/A</texture_shm>
            <cbu>N/A</cbu>
            <total>N/A</total>
        </double_bit>
    </volatile>
    <aggregate>
        <single_bit>
            <device_memory>N/A</device_memory>
            <register_file>N/A</register_file>
            <l1_cache>N/A</l1_cache>
            <l2_cache>N/A</l2_cache>
            <texture_memory>N/A</texture_memory>
            <texture_shm>N/A</texture_shm>
            <cbu>N/A</cbu>
            <total>N/A</total>
        </single_bit>
        <double_bit>
            <device_memory>N/A</device_memory>
            <register_file>N/A</register_file>
            <l1_cache>N/A</l1_cache>
            <l2_cache>N/A</l2_cache>
            <texture_memory>N/A</texture_memory>
            <texture_shm>N/A</texture_shm>
            <cbu>N/A</cbu>
            <total>N/A</total>
        </double_bit>
    </aggregate>
</ecc_errors>
```

RTX
```
<ecc_errors>
    <volatile>
        <sram_correctable>N/A</sram_correctable>
        <sram_uncorrectable>N/A</sram_uncorrectable>
        <dram_correctable>N/A</dram_correctable>
        <dram_uncorrectable>N/A</dram_uncorrectable>
    </volatile>
    <aggregate>
        <sram_correctable>N/A</sram_correctable>
        <sram_uncorrectable>N/A</sram_uncorrectable>
        <dram_correctable>N/A</dram_correctable>
        <dram_uncorrectable>N/A</dram_uncorrectable>
    </aggregate>
</ecc_errors>
```

This breaks `job-exporter`'s code, so monitoring does not work. This can be fixed by small changes to the `src/job-exporter/src/nvidia.py:134-141`

**Comment by GeoffreyChen777** [comment]
@zhiltsov-max  I have fixed this bug in #2534.

**Comment by hellocandy** [comment]
I use the driver 410.73, and the drivers-one-shot works now, but the available GPU count at the node is still 0.

**Comment by abuccts** [comment]
@hellocandy Could you share the log of hadoop node manager in k8s dashboard? It's probably caused by parsing errors in hadoop ai #2736.

/cc @mzmssg

**Comment by hellocandy** [comment]
19/06/26 11:36:35 INFO recovery.NMLeveldbStateStoreService: Starting full compaction cycle
19/06/26 11:36:35 INFO recovery.NMLeveldbStateStoreService$LeveldbLogger: Level-0 table #1398: started
19/06/26 11:36:35 INFO recovery.NMLeveldbStateStoreService$LeveldbLogger: Level-0 table #1398: 0 bytes OK
19/06/26 11:36:35 INFO recovery.NMLeveldbStateStoreService$LeveldbLogger: Delete type=0 #1394
 19/06/26 11:36:35 INFO recovery.NMLeveldbStateStoreService$LeveldbLogger: Manual compaction at level-0 from (begin) .. (end); will stop at (end)
 19/06/26 11:36:35 INFO recovery.NMLeveldbStateStoreService$LeveldbLogger: Manual compaction at level-1 from (begin) .. (end); will stop at (end)
 19/06/26 11:36:35 INFO recovery.NMLeveldbStateStoreService: Full compaction cycle completed in 30 msec
19/06/26 11:36:36 INFO localizer.ResourceLocalizationService: Cache Size Before Clean: 0, Total Deleted: 0, Public Deleted: 0, Private Deleted: 0
19/06/26 11:46:36 INFO localizer.ResourceLocalizationService: Cache Size Before Clean: 0, Total Deleted: 0, Public Deleted: 0, Private Deleted: 0
19/06/26 11:56:36 INFO localizer.ResourceLocalizationService: Cache Size Before Clean: 0, Total Deleted: 0, Public Deleted: 0, Private Deleted: 0
19/06/26 12:06:36 INFO localizer.ResourceLocalizationService: Cache Size Before Clean: 0, Total Deleted: 0, Public Deleted: 0, Private Deleted: 0
19/06/26 12:16:36 INFO localizer.ResourceLocalizationService: Cache Size Before Clean: 0, Total Deleted: 0, Public Deleted: 0, Private Deleted: 0
19/06/26 12:26:36 INFO localizer.ResourceLocalizationService: Cache Size Before Clean: 0, Total Deleted: 0, Public Deleted: 0, Private Deleted: 0
19/06/26 12:36:35 INFO recovery.NMLeveldbStateStoreService: Starting full compaction cycle
19/06/26 12:36:35 INFO recovery.NMLeveldbStateStoreService$LeveldbLogger: Level-0 table #1400: started
19/06/26 12:36:35 INFO recovery.NMLeveldbStateStoreService$LeveldbLogger: Level-0 table #1400: 0 bytes OK
19/06/26 12:36:35 INFO recovery.NMLeveldbStateStoreService$LeveldbLogger: Delete type=0 #1397
 19/06/26 12:36:35 INFO recovery.NMLeveldbStateStoreService$LeveldbLogger: Manual compaction at level-0 from (begin) .. (end); will stop at (end)
 19/06/26 12:36:35 INFO recovery.NMLeveldbStateStoreService$LeveldbLogger: Manual compaction at level-1 from (begin) .. (end); will stop at (end)
 19/06/26 12:36:35 INFO recovery.NMLeveldbStateStoreService: Full compaction cycle completed in 41 msec
19/06/26 12:36:36 INFO localizer.ResourceLocalizationService: Cache Size Before Clean: 0, Total Deleted: 0, Public Deleted: 0, Private Deleted: 0
19/06/26 12:46:36 INFO localizer.ResourceLocalizationService: Cache Size Before Clean: 0, Total Deleted: 0, Public Deleted: 0, Private Deleted: 0
19/06/26 12:56:36 INFO localizer.ResourceLocalizationService: Cache Size Before Clean: 0, Total Deleted: 0, Public Deleted: 0, Private Deleted: 0
19/06/26 13:06:36 INFO localizer.ResourceLocalizationService: Cache Size Before Clean: 0, Total Deleted: 0, Public Deleted: 0, Private Deleted: 0

**Comment by mzmssg** [comment]
@hellocandy 
Could you share the output of `nvidia-smi`

**Comment by hellocandy** [comment]
=== Recall nvidia-smi
Thu Jun 27 02:27:13 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.73       Driver Version: 410.73       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  On   | 00000000:3B:00.0 Off |                  N/A |
| 41%   41C    P0    68W / 260W |      0MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  On   | 00000000:5E:00.0 Off |                  N/A |
| 39%   53C    P0    64W / 260W |      0MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 208...  On   | 00000000:86:00.0 Off |                  N/A |
| 49%   50C    P0    73W / 260W |      0MiB / 10989MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 208...  On   | 00000000:D8:00.0 Off |                  N/A |
| 25%   56C    P0    74W / 260W |      0MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by mzmssg** [comment]
> I use the driver 410.73, and the drivers-one-shot works now, but the available GPU count at the node is still 0.

Have you reployed cluster after new driver? Where do you get availabel GPU count, from YARN or metrics?

It will be very help if you could dump some debug log:
1. change https://github.com/microsoft/pai/blob/6dc5bd91178063fb26665d2a4ece851d530e70f4/src/hadoop-node-manager/deploy/hadoop-node-manager.yaml.template#L114 to `value: DEBUG,console,RFA`
2. restart node-manager
3. download node manager log from k8s dashboard

**Comment by hellocandy** [comment]
19/06/27 06:43:57 WARN util.SysInfoLinux: error get GPU status info:java.io.IOException: Cannot run program "nvidia-smi": error=2, No such file or directory
19/06/27 06:44:35 INFO localizer.ResourceLocalizationService: Cache Size Before Clean: 0, Total Deleted: 0, Public Deleted: 0, Private Deleted: 0
19/06/27 06:44:57 WARN util.SysInfoLinux: error get GPU status info:java.io.IOException: Cannot run program "nvidia-smi": error=2, No such file or directory
19/06/27 06:45:57 WARN util.SysInfoLinux: error get GPU status info:java.io.IOException: Cannot run program "nvidia-smi": error=2, No such file or directory
19/06/27 06:46:57 WARN util.SysInfoLinux: error get GPU status info:java.io.IOException: Cannot run program "nvidia-smi": error=2, No such file or directory
19/06/27 06:47:58 WARN util.SysInfoLinux: error get GPU status info:java.io.IOException: Cannot run program "nvidia-smi": error=2, No such file or directory
19/06/27 06:48:58 WARN util.SysInfoLinux: error get GPU status info:java.io.IOException: Cannot run program "nvidia-smi": error=2, No such file or directory
19/06/27 06:49:58 WARN util.SysInfoLinux: error get GPU status info:java.io.IOException: Cannot run program "nvidia-smi": error=2, No such file or directory
19/06/27 06:50:58 WARN util.SysInfoLinux: error get GPU status info:java.io.IOException: Cannot run program "nvidia-smi": error=2, No such file or directory
19/06/27 06:51:58 WARN util.SysInfoLinux: error get GPU status info:java.io.IOException: Cannot run program "nvidia-smi": error=2, No such file or directory
19/06/27 06:52:58 WARN util.SysInfoLinux: error get GPU status info:java.io.IOException: Cannot run program "nvidia-smi": error=2, No such file or directory
19/06/27 06:53:58 WARN util.SysInfoLinux: error get GPU status info:java.io.IOException: Cannot run program "nvidia-smi": error=2, No such file or directory
19/06/27 06:54:35 INFO localizer.ResourceLocalizationService: Cache Size Before Clean: 0, Total Deleted: 0, Public Deleted: 0, Private Deleted: 0
19/06/27 06:54:59 WARN util.SysInfoLinux: error get GPU status info:java.io.IOException: Cannot run program "nvidia-smi": error=2, No such file or directory
19/06/27 06:55:59 WARN util.SysInfoLinux: error get GPU status info:java.io.IOException: Cannot run program "nvidia-smi": error=2, No such file or directory
19/06/27 06:56:59 WARN util.SysInfoLinux: error get GPU status info:java.io.IOException: Cannot run program "nvidia-smi": error=2, No such file or directory
19/06/27 06:57:59 WARN util.SysInfoLinux: error get GPU status info:java.io.IOException: Cannot run program "nvidia-smi": error=2, No such file or directory
19/06/27 06:58:59 WARN util.SysInfoLinux: error get GPU status info:java.io.IOException: Cannot run program "nvidia-smi": error=2, No such file or directory
19/06/27 06:59:59 WARN util.SysInfoLinux: error get GPU status info:java.io.IOException: Cannot run program "nvidia-smi": error=2, No such file or directory

**Comment by mzmssg** [comment]
It seems that driver isn't correctly installed, do you have customization?

**Comment by hellocandy** [comment]
No, I pull the driver at docker hub.
The openpai version is v0.10.1.

**Comment by mzmssg** [comment]
Could you try the lastest version to apply recent fixes?

**Comment by hellocandy** [comment]
After redeploy the openpai, the RTX 2080 works now.
Thanks for your help.
