### ISSUE TITLE
Can I add a machine to PAI cluster without adding it as a HDFS data node?

### ISSUE THREAD

**Issue by atlascollege** [microsoft/pai#3005]
I have added a new machine in the PAI cluster without setting its "PAI roles" so that the kubernetes can see the machine while PAI cannot (the new machine cannot be seen in the PAI dashboard). Now I need let the PAI to see the machine, but I do not want it be a data node of hdfs. What should I do?

**Comment by mzmssg** [comment]
It is not supported. Could you make it a feature request as our issue template.

**Comment by fanyangCS** [comment]
@mzmsg, I thought it can be achieved by adding some labels to a node? while our deployment does not support this, but advanced users can do further customization on their own.

**Comment by mzmssg** [comment]
@fanyangCS 
It's easy to achieve by changing few lines. However, without a full story, it's easy to abuse and lead permanent data lost.

**Comment by fanyangCS** [comment]
@mzmssg , you can advise user how to change the code to achieve that.
