### ISSUE TITLE
Provide filter for jobs list table

### ISSUE THREAD

**Issue by fanyangCS** [Microsoft/pai#302]

**Comment by scarlett2018** [comment]
cleaning old issues,  @fanyangCS please help to evaluate whether this is still an issue, thanks.

**Comment by squirrelsc** [comment]
As there may be a lot of jobs in job list, a filter is helpful to find interested one. Currently, there is a search box, and can search in any column. But it's not so intuitive, and friendly. It's better to provide some filters, like My jobs, Running, Failed as so on. So that user can get them with one click.

**Comment by fanyangCS** [comment]
https://github.com/Microsoft/pai/pull/2111

**Comment by Gerhut** [comment]
Artboards

![web 1920 1](https://user-images.githubusercontent.com/2500247/53733732-e186ea80-3ebc-11e9-8cdd-f47a5cb70171.png)
![web 1920 2](https://user-images.githubusercontent.com/2500247/53733733-e186ea80-3ebc-11e9-8e1e-a6bdd0c06b0d.png)
![web 1920 3](https://user-images.githubusercontent.com/2500247/53733734-e21f8100-3ebc-11e9-891b-54cf9a7ee0d4.png)
![web 1920 4](https://user-images.githubusercontent.com/2500247/53733735-e21f8100-3ebc-11e9-97b9-5f6940238b28.png)
![web 1920 5](https://user-images.githubusercontent.com/2500247/53733736-e21f8100-3ebc-11e9-8e2b-cd0f145fa9a4.png)
![web 1920 6](https://user-images.githubusercontent.com/2500247/53733737-e21f8100-3ebc-11e9-9352-cd9e3e77f636.png)
![web 1920 7](https://user-images.githubusercontent.com/2500247/53733738-e2b81780-3ebc-11e9-8d75-0b4df8911f0e.png)
![web 1920 8](https://user-images.githubusercontent.com/2500247/53733739-e2b81780-3ebc-11e9-92b6-b275ff0de943.png)
![web 1920 9](https://user-images.githubusercontent.com/2500247/53733740-e350ae00-3ebc-11e9-84fb-5f01ed9837c2.png)

**Comment by Gerhut** [comment]
Test case:

1. Job lists rendered fine, could go into details page
2. Paginator works fine
3. Filters
  a. All filters works fine
  b. Filtered label displayed in the label, with (+n) when multiple
  c. Change the filters will reset the pagination
  d. Clear filter (cross icon at the right of the filter bar)
4. Ordered by Name / Date Modified / User / Duration / Vrtual Cluster / Status
5. "Stop" button
  a. For simple job, right of the row.
  b. For multiple jobs at the top bar.
6. "New" button, linked to submit job page.
7. The filter state will persist after browser close and open.
8. The initial filter:to recover the initial filter: run `window.localStorage.removeItem("pai-job-filter")` in console.
  a. If user is admin, default no filtered.
  b. If not, default filtered user's jobs.
