### ISSUE TITLE
Some files are changed when building rest-server or webportal.

### ISSUE THREAD

**Issue by ydye** [microsoft/pai#3035]
Every time I build webportal or rest-server, the script does some change on the following files. And I have to do some git operation, or I can't checkout to another branch directly. Bad development experience.
```
git checkout xxxxxxx
error: Your local changes to the following files would be overwritten by checkout:
        src/rest-server/package.json
        src/webportal/package.json
Please, commit your changes or stash them before you can switch branches.
Aborting

```

**Comment by abuccts** [comment]
What did you run?

**Comment by ydye** [comment]
> What did you run?

clean branch, master , then build rest-server or webportal. You could have a try. Because a version is input into the package.json. Some the code base is changed.

**Comment by abuccts** [comment]
You only need the following commands for dev purpose:
```
yarn
yarn dev
```

**Comment by ydye** [comment]
Anyway, I will create a PR to handle this issue. I don't think testing webportal or rest-server locally is a good experience.

**Comment by ydye** [comment]
https://github.com/microsoft/pai/pull/3038/files

**Comment by abuccts** [comment]
You only need `yarn dev` or `yarn build` to build instead of running `build-pre.sh`, the script is only used in deployment.

**Comment by ydye** [comment]
@abuccts If you don't change the build logic, the problem still exits. Anyway, I have create the PR.  And I prefer to test in docker container. So if you still think yarn dev or yarn build is better. Could you make some change on the building logic?

**Comment by abuccts** [comment]
I thought your problem is `version` in `package.json` will change in git repo.

The problem won't exist if you move `npm version` line into Dockerfile, it will change `package.json` file in Docker images, instead of your git repo.
