### ISSUE TITLE
Improve Available GPU board

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#3045]
Add explanation or some other ways to make the board more clear to the user.

![image](https://user-images.githubusercontent.com/39592018/60497482-84bf0380-9ce7-11e9-8e34-5e90537e48bd.png)

**Comment by debuggy** [comment]
not done yet

**Comment by yangou1988** [comment]
![image](https://user-images.githubusercontent.com/44491713/61034904-bb3c0300-a3f8-11e9-88b2-d6301459a1f3.png)
•	Show the number of nodes directly upon the bar
•	Change the title name of #GPU to make it easy to understand  ( suggested by user )
•	Update the content of tooltip of each bar

**Comment by fanyangCS** [comment]
done.
