### ISSUE TITLE
The connection to the server xx.xx.xx.xx:8080 was refused

### ISSUE THREAD

**Issue by chunweixu** [microsoft/pai#3061]
**Short summary about the issue/question**:There are some problems after running the command "python paictl.py cluster k8s-bootup -p ~/pai-config", and I tried to slove the problem following the previous post here, but it does not work.
List my terminal logs and kubectl logs on the master:
![Screen Shot 2019-07-04 at 12 01 46 PM](https://user-images.githubusercontent.com/12983441/60639510-860e3e80-9e55-11e9-8748-cd5e169f713b.png)
![Screen Shot 2019-07-04 at 12 03 08 PM](https://user-images.githubusercontent.com/12983441/60639515-87d80200-9e55-11e9-88f2-256767e3cca3.png)

**OpenPAI Environment**:
- OpenPAI version:v0.13.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):Ubuntu 18.04
- Kernel (e.g. `uname -a`):Linux iZ8vbapazaiiwppozbplz3Z 4.15.0-52-generic
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):4core  mem:32G 
 500G
- Others:

**Comment by chunweixu** [comment]
@ydye

**Comment by ydye** [comment]
Maybe you should provide more completed log of kubelet

**Comment by chunweixu** [comment]
Thanks, i fixed this problem...

**Comment by ClarrkLau** [comment]
> Thanks, i fixed this problem...

How did you fix it anyway? I'm still confuse about it.
