### ISSUE TITLE
drivers-one-shot installation failed because of mismatch between driver and kernel

### ISSUE THREAD

**Issue by Chenyangzh** [microsoft/pai#3079]
hello, my issue can refer to #2865 

Follows are my coditions:
one master with no gpus and one worker with teslav100
pai-version: v0.12.0
nvidia-driver-version: 410.73
worker-node-kernel: 4.18.0-17-generic
worker-node-os: Ubuntu-18.04-lst

I also tried to change the kernel version to 4.18.0-15-generic and to use the driver with version of 418.30, but both of them are not work.
By the way, I once successfully deployed pai by using these conditions without any linux-kernel errors. Right now, I am trying to clear old settings and repeat to deploy it but meet this type of error.

Any one can help? THX

**Comment by Chenyangzh** [comment]
How can I install the driver without dkms?

**Comment by Chenyangzh** [comment]
Hello, How can I check the dkms build.log in the drivers container, which always changes itself! I want to check if the error is caused by wrong kernel version.

**Comment by Chenyangzh** [comment]
Finally, I solved the issue by disable test gcc version while installing nvidia driver

**Comment by wjlzk1** [comment]
> 最后，我在安装nvidia驱动程序时禁用了测试gcc版本，从而解决了该问题

请问怎么禁用测试gcc版本..
