### ISSUE TITLE
write tutorial of job submission

### ISSUE THREAD

**Issue by debuggy** [microsoft/pai#3083]

**Comment by debuggy** [comment]
https://github.com/microsoft/pai/blob/zhiyuhe/v0.14.0_docs/docs/user/job_submission.md

**Comment by debuggy** [comment]
- Team Storage: @wangdian
- Advanced
  - Retry:
  - Ports:
  - Completion Policy:

**Comment by wangdian** [comment]
The Team-wise Storage Doc is done. Please refer to PR #3164

**Comment by hzy46** [comment]
Use a new branch because of conficts

https://github.com/microsoft/pai/pull/3183
