### ISSUE TITLE
Improve PAI upgrade documentation

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#3102]
1.	Create maintenance box for new version
2.	Run below lines to connect cluster
cd /pai
./paictl.py cluster k8s-set-env
 
3.	Pull latest configuration, and upgrade to new version
./paictl.py config pull -o /cluster-configuration
 
4.	Check configuration
./paictl.py check -p /cluster-configuration
5.	Update version in old config, search old version and replace with new version
vi /cluster-configuration/services-configuration.yaml
6.	Push new configuration
./paictl.py config push -p /cluster-configuration
 
7.	Stop services
./paictl.py service stop
 
8.	clean up current cluster
./paictl.py cluster k8s-clean -p /cluster-configuration
 
9.	Install new services
./paictl.py cluster k8s-bootup -p /cluster-configuration
 
10.	Start service
./paictl.py service start

**Comment by debuggy** [comment]
there will be a build and push image step among them

**Comment by scarlett2018** [comment]
@debuggy - @hzy46  had offered help on this issue, please check with him whether this is in the June release or July release. thanks.

**Comment by debuggy** [comment]
@scarlett2018 the update doc of this release is in #3195
However, I think the overall deployment doc also needs be improved.
