### ISSUE TITLE
Early stop jobs that are over configured

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#3106]
There are times when users who are not familiar with the cluster's max capability, and they submit jobs that over requiring the resources. i.e. A cluster with only 4 GPU nodes, a user submitted a job need 8 GPU per node. this happens to memory and cpu core as well.

These jobs are failure by its nature, but PAI is still trying to fulfill the resource needs today, which causes other normal jobs waiting and on hold till these jobs are failed (by time out).

We should figure out approaches to do this more gracefully. i.e. avoid users from submitting these jobs, or let the system has the capability to early stop these jobs.

**Comment by fanyangCS** [comment]
should be fixed in pure k8s version.

**Comment by yqwang-ms** [comment]
Fixed by https://github.com/microsoft/pai/pull/3812
