### ISSUE TITLE
SDK / CLI bug triage

### ISSUE THREAD

**Issue by mydmdm** [microsoft/pai#3118]
- [x] opai job submit 弹出未知 protocolVersion 错误，opai job sub 正常
[cause] `protocolVersion` in `prerequisite` is optional, not required
[solution] remove mandatory check of `protocolVersion`

- [x] 提交v2 job时cli无视了我jobconfig里面写的name （用 `opai job sub` 提交的）
[cause] sub 需要你指定一个--job-name（因为是新生成config），submit 会用config中的name（or jobName），除非你用--update 改掉
[solution] update `help` message for `sub`, to let use know `sub  = generate + submit`

- [x] sdk默认安装到了~/src下面
[cause] 在安装的时候用了 -e 选项，这样的话source code是editable，这个对于调试比较方便，但是对于用户而言就不需要了
[solution] update documents to remove the `-e` option when installing

- [x] 我不太清楚现在edit的时候会检查哪些editor，建议检查vscode, notepad 和 vim
[solution] let user specified an editor command (default is `code`) before we find a general way / package to work on both Win/Mac/*nix

- [?] 我已经select了cluster，job那边正常是用我select的cluster，storage弹出了warning
[cause] 怀疑是因为切换了工作目录。（目前set / select都是per folder的，只在当前文件夹有效）
[solution] global set

- [x] 希望没输命令的时候默认-h
[solution] only works for `opai`. since subparser are used for every sub command, will report error for sub commands like `opai job`

- [x] 对于一些boolean的argument比如storage delete的recursive不应该需要写成 --recursive true应该只有--recursive就行了

- [x] [feature] support global set / select

- [x] [feature] get `stderr` or `stdout` from SDK

- [x] [feature] support `-j job_name_$uuid$` to avoid job name conflict

- [ ] [feature] report status of clusters (resources per VC)

**Comment by debuggy** [comment]
could this issue closed now and I will delete 0.14.0 label soon.
