### ISSUE TITLE
[TensorBoard] Integrate TensorBoard on job submission page(v0.14.0)

### ISSUE THREAD

**Issue by TongboZhang** [microsoft/pai#3122]
TensorBoard will support remote storages:
  1. Built-in HDFS(only when it exists);
  2. Team wise storage(only when it exists);
  3. NFS;

There is a detailed design here (#3156).

**Comment by mydmdm** [comment]
Hope that we could unified the way to let user specify `tensorboard` directory, like adding `parameters.tensorboard_logdir` in the protocol. Thus we could provide more advanced functions such as compare diagrams in multiple jobs

**Comment by TongboZhang** [comment]
> Hope that we could unified the way to let user specify `tensorboard` directory, like adding `parameters.tensorboard_logdir` in the protocol. Thus we could provide more advanced functions such as compare diagrams in multiple jobs



> Hope that we could unified the way to let user specify `tensorboard` directory, like adding `parameters.tensorboard_logdir` in the protocol. Thus we could provide more advanced functions such as compare diagrams in multiple jobs

The logdir of TensorBoard will be defined on the extra field of job config YAML, which likes #3156. There will be no interface on the job-submission page because we think job submitter don't need to care about this. There is a detailed [design](https://microsoft.sharepoint.com/teams/OpenAIInfra/_layouts/OneNote.aspx?id=%2Fteams%2FOpenAIInfra%2FSiteAssets%2FOpenAIInfra%20Notebook&wd=target%28PAI%20Features%2FFeatures.one%7C7E270380-17DE-4AF6-8969-18E3A0315776%2FDesigns%20of%20TensorBoard%20Integration%7C9B9E0509-F755-419C-9783-84E98CB5D17C%2F%29
onenote:https://microsoft.sharepoint.com/teams/OpenAIInfra/SiteAssets/OpenAIInfra%20Notebook/PAI%20Features/Features.one#Designs%20of%20TensorBoard%20Integration&section-id={7E270380-17DE-4AF6-8969-18E3A0315776}&page-id={9B9E0509-F755-419C-9783-84E98CB5D17C}&end) here. Please share your thoughts.

**Comment by fanyangCS** [comment]
closed and tracked in #3156 .
