### ISSUE TITLE
Generate a random initial password for new user

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#3133]
same for batch user creation.

**Comment by scarlett2018** [comment]
@mslichao - do you want to take this item?

**Comment by mslichao** [comment]
@scarlett2018 

Yes, I can take this but I need more detail about this issue.

Generate random initial password both for Create user and Batch Create User page?

For create user page, currently we only show the **** when user type their password, so I need a design if we change to generate random password.

**Comment by scarlett2018** [comment]
@mslichao - I think an addition general random password button is good enough, which does not change current behaviors. + @yangou1988 for more comments.

**Comment by yangou1988** [comment]
Random password 
![Random password-add+edit user](https://user-images.githubusercontent.com/44491713/60945868-53fe5000-a31f-11e9-9665-e054c43020f4.png)

**Comment by mslichao** [comment]
Working in branch lchao/randomPassword
