### ISSUE TITLE
job will fail if user use '\' to split command

### ISSUE THREAD

**Issue by debuggy** [microsoft/pai#3137]
![image](https://user-images.githubusercontent.com/8444268/60877929-5609d580-a271-11e9-8152-54dd3c9a2803.png)
![image](https://user-images.githubusercontent.com/8444268/60878975-586d2f00-a273-11e9-9543-6acdf2dadea7.png)

error job name in int bed: test_command_1234

**Comment by hzy46** [comment]
Other failure cases :

1. name in int bed: test_command_echo
![image](https://user-images.githubusercontent.com/7499023/60880597-899b2e80-a276-11e9-8edb-07529ea2304d.png)

**Comment by debuggy** [comment]
solution: tell user not to use '\', and list as known issue
