### ISSUE TITLE
[TensorBoard] Redesign TensorBoard Integration

### ISSUE THREAD

**Issue by TongboZhang** [microsoft/pai#3156]
![design-1](https://user-images.githubusercontent.com/12277407/61034973-e292d000-a3f8-11e9-9aa9-2e7d02e29fc0.jpg)
![design-2](https://user-images.githubusercontent.com/12277407/61034976-e4f52a00-a3f8-11e9-8994-b824867004a3.jpg)
![design-3](https://user-images.githubusercontent.com/12277407/61034980-e6265700-a3f8-11e9-996a-9d156ba6bac1.jpg)
![design-4](https://user-images.githubusercontent.com/12277407/61034982-e7578400-a3f8-11e9-9366-6d393cdef7fa.jpg)
![design-5](https://user-images.githubusercontent.com/12277407/61034989-e9b9de00-a3f8-11e9-90bd-b69a78087d9f.jpg)

The following tasks will be done with new design:
- submit-job-v2 plugin
- job-detail page
- job-submission page

**Comment by fanyangCS** [comment]
https://github.com/microsoft/pai/issues/2095

**Comment by fanyangCS** [comment]
https://github.com/microsoft/pai/issues/3122

**Comment by mydmdm** [comment]
user has to write the `path/to/lgodir` at least twice (one for `tensorboard` command, the other for checkpoint writing). Why not use something like `parameters`?
Another benefit is user could easily get logdir of a completed job. The `tensorboard` would be closed when training is done, but it is quite common to see the logs after. It would be helpful if we can start a `tensorboard` command given only a job name (in web portal or cli)
