### ISSUE TITLE
Add debuggability for PAI paltform 

### ISSUE THREAD

**Issue by Binyang2014** [microsoft/pai#3163]
Customers may want to debug their code which running on the pai cluster.
We need to provide a way to help customer remote debug their code.

Such as: provide cli such as: next, step, break, print
IDE plugin to virtual debug the code

To enable remove debug, we need both change in client side (IDE or CLI) and server side(the container running python code)

This issue may should be split into several sub issues;
1. Provide a simple demo for cli remote debug (pdb debug)
2. Provide a design about which feature we want to support for debugging. (Single/Distribute job, Jobs with GPU or other device)
3. Provide a design for implementation detail
...

**Comment by fanyangCS** [comment]
https://github.com/microsoft/pai/issues/2210

**Comment by fanyangCS** [comment]
closed and tracked in #2210 .
