### ISSUE TITLE
failed to start container "nvidia-drivers"

### ISSUE THREAD

**Issue by 784134748** [microsoft/pai#3186]
v0.12.0升级0.13.0出现以下错误

Error: failed to start container "nvidia-drivers": Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:407: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=8.0 --pid=9412 /var/lib/docker/overlay2/d04c6926d8b8fd8f759e543bcad1ad8ae6b50355888f3d0f6971f128e4c92428/merged]\\\\nnvidia-container-cli: initialization error: cuda error: forward compatibility was attempted on non supported hw\\\\n\\\"\"": unknown

**Comment by abuccts** [comment]
Seems you have installed `nvidia-container-runtime` previously.

You need to change `default-runtime: nvidia` to `default-runtime: runc` in `/etc/docker/daemon.json`, then restart Docker daemon.

**Comment by fanyangCS** [comment]
close as no further response.
