### ISSUE TITLE
显卡驱动升级

### ISSUE THREAD

**Issue by wjlzk1** [microsoft/pai#3189]
**Organization Name**:

**Short summary about the issue/question**:

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**
节点主机的显卡驱动版本无法手动升级，我需要做什么操作，让显卡驱动可以升级？

**Comment by scarlett2018** [comment]
Hardware related question, please search it in other communities.
