### ISSUE TITLE
[Error] Argument list too long

### ISSUE THREAD

**Issue by edenbuaa** [microsoft/pai#3192]
**OpenPAI Environment**:
- OpenPAI version: v0.11.0
- Cloud provider or hardware configuration: private cloud
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

The following error was reported and command was killed in tensorflow(1.13.1) saving checkpoint:
```
/pai/bootstrap/docker_bootstrap.sh:   line 177:  /bin/date: Argument list too long
job has finished with exit code 137

```
The tensorflow logs as follow:
`I0715  11.03.15.893666 140091793905408  basic_sessio_run_hooks.py: 594] Saving checkpoints for 1000 into model/model.ckpt`

I have no idea about this error, thanks for any suggestions!

**Comment by mzmssg** [comment]
Could it be stably reproduced? And could you try to the latest version? Recently we fixed many script bugs.

**Comment by abuccts** [comment]
@edenbuaa Could you share the runtime logs?

<details>
<summary>You can find the entrypoint on webportal, and view runtime logs on YARN page.</summary>

![image](https://user-images.githubusercontent.com/13360214/61271297-c87d3700-a7d6-11e9-951d-57efc5a0e376.png)

</details>

**Comment by edenbuaa** [comment]
@abuccts the runtime log is simple:

[INFO] USER COMMAND START

nohup: redirecting stderr to stdout
/pai/bootstrap/docker_bootstrap.sh:   line 177:  /bin/date: Argument list too long
job has finished with exit code 137
===================================================
======  The job container failed, so it will be reserved for 1 week          ======
======         After  debugging, please stop the job manually.                ======
===================================================

**Comment by abuccts** [comment]
I mean `YarnContainerDebug.log` and `DockerContainerDebug.log`, not `stdout` or `stderr`.

**Comment by edenbuaa** [comment]
thanks. it maybe caused by the time out of sync.
