### ISSUE TITLE
web log redirect

### ISSUE THREAD

**Issue by chunweixu** [microsoft/pai#3205]
Click this url in the browser: http://master:9286/virtual-clusters.html , but it will redirect to the web of http://master:9286/index.html automatically. and i can not login in this page, it is likely to be a template. 
Here is the page:

![Screen Shot 2019-07-17 at 2 54 25 PM](https://user-images.githubusercontent.com/12983441/61353739-1b242500-a8a3-11e9-9af4-ef5fb53f5ee9.png)

**Comment by abuccts** [comment]
Please use the admin username/password in your [configuration file](https://github.com/microsoft/pai/blob/master/examples/cluster-configuration/services-configuration.yaml#L82-L84) to login.

**Comment by chunweixu** [comment]
It does not work
![Screen Shot 2019-07-17 at 4 25 25 PM](https://user-images.githubusercontent.com/12983441/61360093-4b25f500-a8b0-11e9-9753-9f4b4d0daff9.png)

I think the right page is like this, and why my page be redirected to http://master:9286/index.html automatically, can some one explain?
![Screen Shot 2019-07-17 at 4 34 35 PM](https://user-images.githubusercontent.com/12983441/61360321-cd161e00-a8b0-11e9-91cc-58a63b904fe9.png)

**Comment by abuccts** [comment]
Did you start other services? Can you visit `http://masterip:9186/api/v1/`?

The first one is new version page and the second one is old version, addresses do not matter.

**Comment by chunweixu** [comment]
The result of the page like that:
![Screen Shot 2019-07-17 at 5 06 43 PM](https://user-images.githubusercontent.com/12983441/61362797-60515280-a8b5-11e9-8b80-d871f400948d.png)

**Comment by chunweixu** [comment]
this is my rest-server log:
[logs-from-rest-server-in-rest-server-ds-rlgfk.txt](https://github.com/microsoft/pai/files/3401026/logs-from-rest-server-in-rest-server-ds-rlgfk.txt)

**Comment by abuccts** [comment]
It's strange, the rest server looks fine. Could you please try to login again on webportal and when you are in [this page](https://user-images.githubusercontent.com/12983441/61360093-4b25f500-a8b0-11e9-9753-9f4b4d0daff9.png), press <kbd>F12</kbd> and paste error logs in browser console?

BTW, which version of PAI do you use?

**Comment by chunweixu** [comment]
Failed to load resource: net::ERR_CONNECTION_TIMED_OUT     172.26.102.174:9186/api/v1/token:1 
环境：阿里云ESC上面部署      PAI version:v0.13.0
![Screen Shot 2019-07-18 at 2 04 24 PM](https://user-images.githubusercontent.com/12983441/61433267-63a41700-a965-11e9-850a-fea1cf4a4536.png)

**Comment by abuccts** [comment]
Seems a network issue, could you try to `POST` a token using `curl`?
```sh
curl -v \
     -H "Content-Type: application/x-www-form-urlencoded" \
     -X POST 172.26.102.174:9186/api/v1/token \
     -d "username=YOUR_USERNAME" -d "password=YOUR_PASSWORD"
```

/cc @sunqinzheng could you help to have a look?

**Comment by chunweixu** [comment]
"172.26.102.174" is private ip in my aliyun ESC, and there also has a public ip for this machine.
It does not work:
`curl -v \
     -H "Content-Type: application/x-www-form-urlencoded" \
     -X POST 172.26.102.174:9186/api/v1/token \
     -d "username=YOUR_USERNAME" -d "password=YOUR_PASSWORD"`  
but it works when i change to the public ip:
`curl -v \
     -H "Content-Type: application/x-www-form-urlencoded" \
     -X POST public_ip:9186/api/v1/token \
     -d "username=YOUR_USERNAME" -d "password=YOUR_PASSWORD"`

**Comment by abuccts** [comment]
That's the problem, you cannot visit rest api with the private ip in your browser.

Solutions:
* If you have deployed pylon service, you can visit `http://master` directly (remove port) and try again. (preferred, but please make sure your firewall allows 80 port)
* If not, you can [create a SOCKS5 with ssh](https://superuser.com/a/1308648) and use the proxy in your browser.

**Comment by chunweixu** [comment]
It works, thanks @abuccts

**Comment by abuccts** [comment]
Glad to hear, close this issue.
