### ISSUE TITLE
[WebPortal] New mount entry on the data section of job-submission page(v0.14)

### ISSUE THREAD

**Issue by TongboZhang** [microsoft/pai#3217]
![image](https://user-images.githubusercontent.com/12277407/62102170-8ec62900-b2ca-11e9-8563-f496f442c1e4.png)

**Comment by debuggy** [comment]
I think the `add hdfs` of add data source has the same function `Customized mount`, maybe they could be merged together

**Comment by TongboZhang** [comment]
> I think the `add hdfs` of add data source has the same function `Customized mount`, maybe they could be merged together

I think `add hdfs` can not only add PAI HDFS but also customized HDFS, so I separate them for now. But maybe we can merge them into one component.
