### ISSUE TITLE
Different training efficiency between openpai job and nv-docker run on machine.

### ISSUE THREAD

**Issue by rtrobin** [microsoft/pai#3267]
**Short summary about the issue/question**:

Different training efficiency between openpai job and nv-docker run on machine. Bottleneck is about pinned memory usage.

**Brief what process you are following**:

We deploy openpai on our new cluster. Each node is a physical machine with 8 V100 cards. I test pytorch framework on openpai, which is much slower than I expect. After the investigation, I find out the bottleneck is about the pinned memory usage during training process.

As you may know, the [DataLoader](https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader) class in pytorch has a parameter _pin_memory_ which defines whether using pin memory to accelerate tensor transfer between host memory and device memory. Setting _pin_memory_ to _True_, the training speed is dramatically 10x slower than _False_. I also try the same docker image with same code on the same machine, by ssh logging in. I use nv-docker run the image and test the code. The training speed with _False_ option is equivalent to the same _False_ option launching by openpai. The speed with _True_ option is a bit faster than _False_ option as expected.

The only difference between the test, is the docker launching parameters. I checked the log of openpai job. The openpai seems not using nv docker. It launched the docker with `docker run --runtime=runc --device=/dev/nvidiactl --device=/dev/nvidia-uvm --device=/dev/nvidia0 --device=/dev/fuse ...`. While I ran the docker on machine with `docker run --runtime=nvidia ...`. I wonder if the docker run parameter difference results in the bad behavior of pinned memory.

I also ran some test on tensorflow and keras. Both training speed is much slower than running docker on local machine. But I don't find how to disable pin memory use in these two frameworks. So I can't give a comparison test with tensorflow and keras.

**However**, we also have some virtual OS machine with V100 on cloud deployed openpai. They behave the same with nv docker run on local and openpai launching, as it should be. Which makes me very very confused about our new physical machine cluster...

**OpenPAI Environment**: 
- OpenPAI version: 0.11.0
- Cloud provider or hardware configuration: V100
- OS (e.g. from /etc/os-release): Ubuntu 16.04.4 LTS
- Kernel (e.g. `uname -a`): I'm not sure...
- Hardware (e.g. core number, memory size, storage size, GPU type etc.): V100
- Others: 

**Anything else we need to know**:

Any advice would be appreciated. Thanks.

**Comment by fanyangCS** [comment]
could you share your job submission config file?

**Comment by rtrobin** [comment]
@fanyangCS 

Thanks for the reply. I have assigned very large memory and shm-size for the job to run. As I mentioned in the post, the same job could run correctly on other virtual OS cluster.

Currently I can't reach the cluster. I will post my job config file later.

**Comment by rtrobin** [comment]
My test code is based on horovod benchmark code on horovod base image. We have built a private harbor to store docker images. I could push my image and test code to public, if needed.

``` json
{
  "jobName": "test_pin_memory",
  "image": "10.10.47.9/tyj/horovod:0.16.4",
  "virtualCluster": "default",
  "taskRoles": [
    {
      "name": "main",
      "taskNumber": 1,
      "cpuNumber": 6,
      "memoryMB": 10240,
      "gpuNumber": 1,
      "command": "nvidia-smi && mkdir /nfs  && mount -t nfs4 10.10.47.9:/nfs /nfs  && cd /nfs/tyj/benchmark && python pytorch_synthetic_benchmark.py",
      "shmMB": 10240
    }
  ],
  "jobEnvs": {
    "isDebug": true
  }
}
```

**Comment by rtrobin** [comment]
I pushed my test code to my [repo](https://github.com/rtrobin/codeMixed/tree/master/python/pytorch/benchmark). Hope it could help.

Thanks.

**Comment by rtrobin** [comment]
@fanyangCS 

Is there any public doc about how to enable nvidia docker runtime? I could share it to our administrator, and make further test. Thanks.

**Comment by xudifsd** [comment]
@rtrobin If you used pai to deploy k8s, you'r nodes sure already have nvidia docker runtime installed. If not, execute these [commands](https://github.com/microsoft/pai/blob/3adbcddada8fa95844e065843f4ed3009edac967/deployment/k8sPaiLibrary/maintaintool/docker-ce-install.sh#L72-L78) to install.

This will **not** configure nvidia-container-runtime as default runtime, and I believe you do not need it to be. With above setup you can run some docker using nvidia runtime just execute `docker run --runtime=nvidia xxx`. Pai will not start container in nvidia runtime runtime but with almost same environment, you can see task start command [here](https://github.com/microsoft/pai/blob/master/src/rest-server/src/templates/yarnContainerScript.mustache#L539).

Below is just for your information, I do not think you need default container runtime to be nvidia:

To set nvidia runtime as default docker runtime, you can execute `./paictl.py service stop drivers` and change the config of [`set-nvidia-runtime`](https://github.com/microsoft/pai/blob/3adbcddada8fa95844e065843f4ed3009edac967/deployment/quick-start/services-configuration.yaml.template#L84) to True and then execute `./paictl.py service start drivers` to enable nvidia container runtime as default runtime. This command will execute these [commands](https://github.com/microsoft/pai/blob/master/src/drivers/build/config-docker-runtime.sh#L29-L34) in each of your worker node.

**Comment by rtrobin** [comment]
Sorry for the late reply. We are still trying to make it work. I will post update later.

**Comment by edenbuaa** [comment]
@xudifsd I also have this problem in pai-v0.13.0.
The nodes have installed nvidia docker runtime, and the following error reports when set the set-nvidia-runtime to true and start service:

`Error: failed to start container "job-exporter": Error response from daemon: OCI runtime create failed: container_linux.go:345:starting container process caused"process_linux.go:424:container init caused \"process_linux.go:407:running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --device=all --utility -pid=15315 /var/lib/docker/aufs/mnt/90adf647b99ea637b76d0bfa2e49a7f631dbb22c9510a8bf00591e759c5de05]\\\\nnvidia-container-cli: initalization error: cuda error: system has unsupported display driver combination\\\\n\\\"\"": unknown Back-off restarting failed container`

@rtrobin did you fix this problem? @xudifsd What should I do to solve this problem? thanks.

**Comment by xudifsd** [comment]
@edenbuaa seems your node do not have driver installed correctly. Does this node previous installed some drivers?

**Comment by rtrobin** [comment]
@edenbuaa @fanyangCS No, I haven't.

We have done some upgrading work this week. We upgraded our installed docker, openpai, and other stuffs. Now we could use nvidia runtime in openpai. However, the training speed is still the same. 

We are doing further investigation now. I will keep the post updated later.

**Comment by rtrobin** [comment]
I have found the tricks about my training speed problem. The use of runc or nvidia doesn't affect it. 

Our gpu node has two NUMA nodes. The docker parameter `--cpus=6` doesn’t allocate 6 cpu cores to the job, but load every cores balanced under cpu rate 6/**cpu_core_nums**. To run the training job correctly, the docker parameter `--cpuset-cpus` should be used.

**Comment by fanyangCS** [comment]
thanks for reporting back. we really appreciate it.
