### ISSUE TITLE
Clock out of sync

### ISSUE THREAD

**Issue by ultmaster** [microsoft/pai#3277]
**Organization Name**: NNI Team

**Short summary about the issue/question**: Two problems regrading clocks in PAI

1. The clocks on computing nodes seems out of sync with the clock on manager nodes. The time printed by the program with `datetime.now()` in Python is earlier even than the starting time.

![image](https://user-images.githubusercontent.com/8463288/62033410-7698d000-b21e-11e9-94da-9c894861ee26.png)

![image](https://user-images.githubusercontent.com/8463288/62033426-7d274780-b21e-11e9-810c-899838bc266a.png)

2. The clocks are not in the same timezone: 09:50 + 8 hours = 17:50.

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**: 10.151.40.179. Job ID is `nni_exp_c4Z6mVSw_trial_z4Ao4`.

**Comment by ydye** [comment]
1: Created time from launcher on the master node (NTP installed). And the log time in your job based on the worker node (without NTP).  For example, now the master date is ```Tue Jul 30 06:36:29 UTC 2019 ```, and the worker date is ```Tue Jul 30 06:27:58 UTC 2019```
2: It's by design, and depends on the setting of the vm.

**Comment by ydye** [comment]
Can we tag this issue as known issue? @scarlett2018

**Comment by fanyangCS** [comment]
If this is 179 bed, it is Azure based. The Azure VM's clock is in sync by default. https://docs.microsoft.com/en-us/azure/virtual-machines/linux/time-sync#use-the-default. 

@ydye, can you confirm the two VMs have clock drift?

**Comment by ydye** [comment]
> If this is 179 bed, it is Azure based. The Azure VM's clock is in sync by default. https://docs.microsoft.com/en-us/azure/virtual-machines/linux/time-sync#use-the-default.
> 
> @ydye, can you confirm the two VMs have clock drift?

Have confirmed

**Comment by scarlett2018** [comment]
> Can we tag this issue as known issue? @scarlett2018

@ydye - tagged, but let's try to fix it or find a workaround ... as it is impacting NNI.

**Comment by fanyangCS** [comment]
According to @ydye , in newer Linux distributions, the VMICTimeSync service uses the precision time protocol (PTP), but earlier distributions may not support PTP and will fall-back to NTP for getting time from the host. OpenPAI now runs on earlier distribution. This could be the reason.

**Comment by scarlett2018** [comment]
> According to @ydye , in newer Linux distributions, the VMICTimeSync service uses the precision time protocol (PTP), but earlier distributions may not support PTP and will fall-back to NTP for getting time from the host. OpenPAI now runs on earlier distribution. This could be the reason.

@fanyangCS @ydye - help me understand better... will this problem be automatically fixed after PAI VM image upgrade (or PAI's underlying Linux distribution upgrade)?

**Comment by fanyangCS** [comment]
in the future, we will not support the configuration in host environment. We assume this will be handled by k8s itself, which is in-turn deployed by third-party tool like AKS or Kubespray.
