### ISSUE TITLE
[WebPortal]: Design to display Job History Attempts

### ISSUE THREAD

**Issue by yqwang-ms** [microsoft/pai#3299]
**What would you like to be added**:
Current RestServer can only provide **the current attempt of a job**.
However, it will soon support to also provide **all history attempts of a job**.
The history job is in the same schema of current job.

So, we wish WebPortal can also support to display **all history attempts of a job** instead of just **the current attempt of a job**. 

A simple WebPortal enhancement design may be like:
1. By default, we will only display **current attempt of a job** as current we do in the job detail page, but in addition, we will also display a selection box on the same page, and each item in the selection box is **the job attempt id**.
2. And when **user selected one job attempt id**, he will be redirected to the job detail page of the selected **job attempt id.**

**Why is this needed**:
To help user understand job history retries.

**Without this feature, how does the current module work**:
Check backend logs which user useally does not have permission and hard to understand.

**Components that may involve changes**:
WebPortal

**Comment by fanyangCS** [comment]
close and track here: https://github.com/microsoft/pai/pull/3623
