### ISSUE TITLE
Submit Job slowly

### ISSUE THREAD

**Issue by IamSunGuangzhi** [microsoft/pai#3311]
**Short summary about the issue/question**:
- When i submit a job by OpenPAI, the app needs one minutes to submit. I want to know that how long does it take to submit a task, when you test. Thanks!

**OpenPAI Environment**:
- OpenPAI version: v0.14.0
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Kernel (e.g. `uname -a`): 4.15.0-55-generic #60~16.04.2-Ubuntu SMP x86_64
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):Titan xp
- Others:

**Comment by fanyangCS** [comment]
How do you measure the submission time? The default time interval for state change is 30s (in Yarn launcher). But this is just the display time. Things can go faster and the display state may have some lag.

**Comment by IamSunGuangzhi** [comment]
Hi fanyangCS, thanks for your reply. I start by submitting tasks on the webportal, and it takes about a minute until the webportal displays app information. We want to reduce this time. What should we do. We think it is the problem of our own configuration, so we would like to know whether it is the same for you?

**Comment by fanyangCS** [comment]
I suspect it is due to the slow network connection between client and webportal or restserver? Otherwise it should be instantly shown in the webportal.

**Comment by IamSunGuangzhi** [comment]
Hi fanyangCS, thanks for your reply.  When you click `submit`, the webportal instantly show `running`?How much time is there?

**Comment by fanyangCS** [comment]
at most tens of seconds. it usually takes a few seconds. But this depends on the network speed between your client and restserver/webportal

**Comment by IamSunGuangzhi** [comment]
Hi, fanyangCS. I find that you use this code to sleep 30s. why? What are you doing at this time?
https://github.com/microsoft/pai/blob/2472b37792092e448b4050c776b35acb3e6ffafb/subprojects/frameworklauncher/yarn/src/main/java/com/microsoft/frameworklauncher/applicationmaster/RequestManager.java#L110

**Comment by IamSunGuangzhi** [comment]
@fanyangCS

**Comment by yqwang-ms** [comment]
@IamSunGuangzhi We do polling to get the request by design. You can Reduce the AmRequestPullIntervalSec by launcher config, but this will also increase ZK workload.

**Comment by IamSunGuangzhi** [comment]
Hi yqwang-ms, thanks for your reply. We find a bug. When we print lots logs, click `View Full log`. Pai show `{"message":"Page not found","error":{}}`, we find the url is error.

**Comment by yqwang-ms** [comment]
Please file another issue for this
