### ISSUE TITLE
Add machine not work

### ISSUE THREAD

**Issue by edenbuaa** [microsoft/pai#3313]
PAI Version: v0.11.0 & v0.13.0
I executed the following command to add new node to cluster:
`python paictl.py machine add -p /path/to/cluster-configuration/dir -l machine-list.yaml`
then, the new node can be listed in kubernete dashboard but not in pai webportal's. I have tried to add the node to layout.yaml and restart service, but it didn't work.  
How to fix this problem? thanks.

**Comment by ydye** [comment]
After adding machine, you should first restart the service named ```cluster-configuration```

**Comment by edenbuaa** [comment]
@ydye I tried your solution, it still didn't work.

**Comment by ydye** [comment]
Have you push the latest config to clst?

**Comment by edenbuaa** [comment]
yes.

**Comment by ydye** [comment]
- cluster-configuration will update the node label, if you update your cfg to cluster. ``` paictl config push ....```
- After restarting cluster-configuration, you need to refresh hadoop-data-node and hadoop-node-manager and drivers

- If the first steps didn't work, you should manually add the node label by kubectl. 
```
kubectl label --overwrite=true nodes {{ cluster_cfg['layout']['machine-list'][host]['nodename'] }} pai-worker=true
```
