### ISSUE TITLE
if we can support .ini config file?

### ISSUE THREAD

**Issue by jiweng** [microsoft/pai#3318]
As we try to use rest-server and webportal in autopilot environment, but autopilot not support yaml flattened, if we can support .ini config file? current we rely on group.yaml and oidc.yaml

**Comment by yqwang-ms** [comment]
We currently does not support ini.
Can you use existing tools to convert ini to yaml?

**Comment by yqwang-ms** [comment]
Like: https://github.com/kigster/dupervisor
