### ISSUE TITLE
automatically attach code commit number to the webportal

### ISSUE THREAD

**Issue by debuggy** [microsoft/pai#3320]
Current the webportal only shows version number, however we could not know whether this deployment is in the newest code commit or not. So when found a bug, we always struggled to find out if it has been fixed in new version.

![image](https://user-images.githubusercontent.com/8444268/62517471-0a3f5180-b85a-11e9-9c93-28342f1dfc22.png)

Therefore I suggest to attach a commit number in the webportal or somewhere automatically when deployment for debug.

**Comment by hzy46** [comment]
https://github.com/microsoft/pai/pull/3374
