### ISSUE TITLE
[AAD] Provide a way to show the token to the user in webportal

### ISSUE THREAD

**Issue by ydye** [microsoft/pai#3324]
1.  An API to provide token
2. Set the Token expire time to 4 weeks.
3. An page in webportal to show the token for user.

After this change, 3rd sdk or service can use the token copied from webportal to login the rest-server.

@scarlett2018 the no.3 item need to cooperate (UI).

**Comment by fanyangCS** [comment]
in future release, we need to discuss the experience of token renewal

**Comment by scarlett2018** [comment]
how does we renew today? instead of manual review and get info from Webportal, should we provide a programmatic way to get the token?

something like:

> 4. Enter the following url into the textbox and select POST
> https://login.microsoftonline.com/{{tenantId}}/oauth2/token

in https://blog.jongallant.com/2017/03/azure-active-directory-access-tokens-postman/

cc @yds05 @mydmdm @qfyin for suggestions about how 3rd sdk use the token.

**Comment by ydye** [comment]
Seems confused about the solution.
1: Grant the permission to an app, so will we grant the permission to 3rd sdk? It's dangerous. And I found the token not granted to a specific user. It seems it can get all resource from the aad.
2: If it's granted to OpenPAI, so openpai can get user's info through AAD. But the question is how we can known the user who use the 3rd sdk is a validated user? If we can validate the user's id, so why not directly make the user access to the api?

**Comment by scarlett2018** [comment]
@ydye - this is blocking the 3rd party integration with AAD, right? may we have a quick sync up with tech leads in this thread?
