### ISSUE TITLE
enable ssh deployment that supports ed25519

### ISSUE THREAD

**Issue by fanyangCS** [microsoft/pai#3325]
**What would you like to be added**:
enable ssh deployment that supports ed25519

**Why is this needed**:
some host only allows ed25519, instead of rsa

**Without this feature, how does the current module work**:

**Components that may involve changes**:

**Comment by ydye** [comment]
Install paramiko through pip？

**Comment by fanyangCS** [comment]
@ydye, yes if that works.

**Comment by abuccts** [comment]
It's better to upgrade to Python 3, Python 2 and many related packages are deprecated.
