### ISSUE TITLE
[Security] Kubernete Api server unauthorized access vulnerability

### ISSUE THREAD

**Issue by edenbuaa** [microsoft/pai#3337]
PAI Version: v0.13.0

The default Kubernete api port 8080 is unauthorized access, it's reported as a security vulnerability. It failed to login in pai webportal after config the security strategy in firewall for 8080 (don't allow access by 8080 except from the cluster nodes).
Is there another way to solve this problem? thanks.

**Comment by fanyangCS** [comment]
this is known issue. we will fix in future release.

**Comment by edenbuaa** [comment]
@fanyangCS yes, I have used the pylon and configurated the security strategy for kubernete API server. Did i missing something?

**Comment by ydye** [comment]
#3618 Will evaluate kubespray. And try to replace the k8s deployment part by kubespray which should solve this issue.
