### ISSUE TITLE
Automatically Setup for HA storage solution

### ISSUE THREAD

**Issue by TongboZhang** [microsoft/pai#3339]
- [x] DRBD
  - [x] DRBD Config
  - [x] DRBD Maintaince Script
- [x] Sharing Service
  - [x] NFS
  - [x] SMB
- [x] Monitor Service
  - [x] Service Config
  - [x] Service Timer
  - [x] Checking Script
  - [x] SMTP Script
- [x] Automatically Script
  - [ ] ~~Setup Script~~
  - [x] Maintaince Script (control host role MASTER/BACKUP, control services)

**Comment by fanyangCS** [comment]
@tongbozhang, can you link each item to the corresponding PRs?

**Comment by TongboZhang** [comment]
> @TongboZhang, can you link each item to the corresponding PRs?

@fanyangCS Should these files be involved in PAI repo? If so, which folder should I put in? contrib?

**Comment by fanyangCS** [comment]
contrib looks good.
