### ISSUE TITLE
[pure-k8s] Disk usage monitor module

### ISSUE THREAD

**Issue by wangdian** [microsoft/pai#3340]
In Pure-k8s based PAI, we will switch to k8s's eviction mechanism when disk is full,  because all the job are pods managed by k8s. So the diskcleaner will not be deployed in pure-k8s version.
But we still need a monitor for disk usage. A new disk monitor is needed.

**Comment by fanyangCS** [comment]
https://github.com/microsoft/pai/issues/3765

**Comment by fanyangCS** [comment]
closed and tracked in #4694
