### ISSUE TITLE
请升级0.14.0的dev-box

### ISSUE THREAD

**Issue by qzwlinux** [microsoft/pai#3341]
今天测试了14版本的dev-box，但发现/pai的分支是v0.13.0
修改~/pai-config/services-configuration.yaml中版本为0.14.0但是pylon无法运行
于是下载0.14.0版本的代码到这个dev-box容器后，使用新的代码可以部署成功
这是一个小反馈

**Comment by fanyangCS** [comment]
@debuggy, can you take a look?

**Comment by debuggy** [comment]
@qzwlinux 你好，我测试了一下，目前dockerhub上的[devbox:v0.14.0](https://hub.docker.com/r/openpai/dev-box/tags)应该是最新的image.

根据dev-box的[build script](https://github.com/microsoft/pai/blob/v0.14.0/src/dev-box/build/start-script.sh)，pai会checkout最新的release 版本，所以不知道为什么在你的场景中pai分支会是v0.13.0，希望你能再确认一下，或者给出reproduce process，谢谢！

**Comment by qzwlinux** [comment]
@debuggy 不好意思   检查了一下，不知道原因是什么，下载的14版本和13版本的docker images ID相同，非常感谢   重新pull了一份，和您描述的内容相同
