### ISSUE TITLE
Fail to update cpu configuration of node

### ISSUE THREAD

**Issue by edenbuaa** [microsoft/pai#3349]
PAI Version: v0.13.0

steps to reproduce:
1. Edit the layout.yaml to update the `vcore` item of node from 16 to 32. then push to the cluster, restart pai service.
2. submit a job that request 20 cpus in a task. job failed with this reason:
`Invalid resource request, requested virtual cores < 0, or requested virtual cores > max configured, requestedVirtualCores=20, maxVirtualCores=16`

the maxVirtualCores is still 16, It seems the update for vcore does not work? What should I do to make it work? thanks.

**Comment by mzmssg** [comment]
The cpu is auto-detected by hadoop, not loaded from layout.yaml. Every vcore means a physical core.

**Comment by mzmssg** [comment]
Please change code if you realy want to customize: https://github.com/microsoft/pai/blob/49c11438354c99d8a3e403d4a2a188927fcb00ba/src/hadoop-node-manager/deploy/hadoop-node-manager-configuration/nodemanager-generate-script.sh#L74

But job might not get promised cpu time, because your node has only 16 physical core.

**Comment by edenbuaa** [comment]
Thanks @mzmssg 
As your mentioned, I make a test on work nodes which all have 64 vcores.  And indeed, the value of `yarn.nodemanager.resource.cpu-vcores` in yarn-site.xml is 64. but it still report '`Invalid resource request, requested virtual cores < 0, or requested virtual cores > max configured, requestedVirtualCores=64, maxVirtualCores=32`' when I try to sumbit a job requesting 64 cpunumber. I am confused about this,  Could you please explain that?

**Comment by mzmssg** [comment]
We have a global maximum resource limit:
https://github.com/microsoft/pai/blob/bcc7978900056f55ef8361ab59c873b67b80d79c/src/hadoop-resource-manager/deploy/hadoop-resource-manager-configuration/yarn-site.xml.template#L349

I guess that you deployed an old version, previouesly it's 32

**Comment by edenbuaa** [comment]
Oh, My!  thanks a lot.
