### ISSUE TITLE
Build docker images with SSH enabled

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#3355]
The recommended docker images do not have openssh-server and curl packages, thus the SSH feature doesn't work for them.

![image](https://user-images.githubusercontent.com/7499023/62847105-0eaab500-bd07-11e9-8eda-fa7243bce82e.png)

Need to build ssh-enabled docker images.

**Comment by hzy46** [comment]
PR: https://github.com/microsoft/pai/pull/3381

**Comment by debuggy** [comment]
Maybe we could take this chance to renew the images of openpai in github and furthermore create a subproject to maintain and opensource it, as a replace of deepo.
