### ISSUE TITLE
Add an example for pytorch

### ISSUE THREAD

**Issue by rabbit008** [microsoft/pai#3357]
**What would you like to be added**:
Add an example for pytorch

**Comment by hzy46** [comment]
The example should contain "shmMB" as its setting.

**Comment by fanyangCS** [comment]
https://github.com/microsoft/pai/blob/master/marketplace-v2/horovod-pytorch-synthetic-benchmark.yaml

**Comment by fanyangCS** [comment]
here is an example yaml file with shmMB:

protocolVersion: 2
name: test
type: job
jobRetryCount: 0
prerequisites:
  - type: dockerimage
    uri: 'xxx'
    name: docker_image_0
taskRoles:
  taskrole:
    instances: 1
    completion:
      minFailedInstances: 1
      minSucceededInstances: 1
    taskRetryCount: 0
    dockerImage: docker_image_0
    extraContainerOptions:
      shmMB: 400000
    resourcePerInstance:
      gpu: 8
      cpu: 24
      memoryMB: 400000
    commands:
      - 
defaults:
  virtualCluster: default
extras:
  com.microsoft.pai.runtimeplugin:
    - plugin: ssh
      parameters:
        jobssh: true
