### ISSUE TITLE
Can't ssh in docker container based on ubuntu 18.04

### ISSUE THREAD

**Issue by rtrobin** [microsoft/pai#3359]
**Short summary about the issue/question**:

Can't ssh in docker container based on ubuntu 18.04

**Brief what process you are following**:

Our nodes in cluster are installed ubuntu 16.04.4. When running ubuntu 18.04 based image in openpai, it failed to ssh the running container. To be more specific, the ssh info could successfully show in job page. But by using the command list in ssh info, it gives such error: `ssh: connect to host ip port port_number: Connection refused`.

I have looked up this online, and found the version of openssh-client & openssh-server in 16.04 and 18.04 is different. I re-installed the same version of openssh* as worker node and rebuilt the image. But it still can't work.

**How to reproduce it**:

The [horovod](https://hub.docker.com/r/horovod/horovod) official image `horovod/horovod:0.16.4-tf1.14.0-torch1.1.0-mxnet1.4.1-py3.6` can be used for reproduce.

**OpenPAI Environment**:
- OpenPAI version: 0.13.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): 16.04.4
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

SSH for attaching running container is a minor problem. The fatal problem is, without ssh successfully, most distributed training job cannot be launched.

**Comment by abuccts** [comment]
Hi @rtrobin, it's a known bug because of changes in ubuntu 18.04 `sshd_config` and has been fixed in #3251 already. Thanks for reporting.

For a temporal solution, you can add `sed -i 's/[# ]*Port.*/Port '$PAI_CONTAINER_SSH_PORT'/' /etc/ssh/sshd_config && service ssh restart &&` in the beginning of your command. Or re-built rest server image with changes in #3251.

**Comment by rtrobin** [comment]
Hi @abuccts , thanks for the reply. I would try your suggestion later. Btw, is there any release plan for the fix of this defect?

**Comment by abuccts** [comment]
The fix has been merged into master already and will be in next release by the end of this month #3250.

**Comment by rtrobin** [comment]
Thanks.
