### ISSUE TITLE
Could openPAI submit job automatically?

### ISSUE THREAD

**Issue by pzYui** [microsoft/pai#3360]
I execute a script to submit job once a week , does openPAI have some feature can help me to submit job automatically?   

**OpenPAI Environment**:
- OpenPAI version:v0.14.0

**Comment by abuccts** [comment]
You can run a [cron job](https://stackoverflow.com/questions/16717930/how-to-run-crontab-job-every-week-on-sunday) for submitting job through api:
```sh
curl -H "Content-Type: application/json" -H "Authorization: Bearer YOUR_TOKEN" \
-X POST YOUR_REST_API/api/v1/jobs -d @YOUR_JOB_CONFIG_FILE
```

**Comment by fanyangCS** [comment]
@pzyui, you can leverage the cron job and leverage the Python SDK we provide https://github.com/microsoft/pai/tree/master/contrib/python-sdk

**Comment by pzYui** [comment]
Thanks
