### ISSUE TITLE
Suspicious GPU usage upon launching

### ISSUE THREAD

**Issue by ultmaster** [microsoft/pai#3372]
**Organization Name**: NNI Dev

**Short summary about the issue/question**: I'm currently running experiments on PAI, and some of my experiments failed with all similar settings. Trying to figure out why, I added an `nvidia-smi` before my code. And it shows this:

![image](https://user-images.githubusercontent.com/8463288/62933686-5a3b8c80-bdf5-11e9-95ab-23b613c70f9d.png)

Why is there already GPU memory consumption before I do anything? Is this by design or a bug?

**How to reproduce it**:

Link to job: http://10.151.40.179/job-detail.html?username=v_yugzh&jobName=nni_exp_nmBU5BUf_trial_wngTb

`train_imagenet.sh` can be found [here](https://github.com/ultmaster/EfficientNet-PyTorch/blob/b05ae6a1431969084d39faf0c703f7197e01bffc/train_imagenet.sh).

**OpenPAI Environment**: I'm using 179.

**Anything else we need to know**:

**Comment by abuccts** [comment]
It should be a GPU process in `D` state, the node is unhealthy.

/cc @wangdian pls help to reboot.

**Comment by wangdian** [comment]
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.56       Driver Version: 418.56       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 00004A30:00:00.0 Off |                    0 |
| N/A   56C    P0    58W / 149W |   7127MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           On   | 0000A061:00:00.0 Off |                    0 |
| N/A   54C    P0    57W / 149W |   5806MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           On   | 0000E323:00:00.0 Off |                    0 |
| N/A   43C    P0    71W / 149W |   5825MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           On   | 0000FD27:00:00.0 Off |                    0 |
| N/A   44C    P0    72W / 149W |   5806MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      4135      C   python                                      7112MiB |
|    1      4135      C   python                                      5791MiB |
|    2      4135      C   python                                      5810MiB |
|    3      4135      C   python                                      5791MiB |
+-----------------------------------------------------------------------------+

This process belongs to a stopped job. But the container and process still remains.
Will reboot the machine.

**Comment by wangdian** [comment]
Node rebooted. Close this issue. Will add a work item to set alert for this.
