### ISSUE TITLE
[alert-manager] Add alert for process in D state that holds GPU memory

### ISSUE THREAD

**Issue by wangdian** [microsoft/pai#3375]
According to issue #3372, we have process in D state holds GPU memory and not release after job stopped. 
Currently we only reports D state of nvidia-smi to detect the GPU status of the node, but not detect the situation that a process in D state that holds GPU.
Should add an alert for this.

**Comment by mzmssg** [comment]
We should have a zombie container alert for it

**Comment by Binyang2014** [comment]
You are correct, but seems no alert triggered at this time. Need to check why this happens.
