### ISSUE TITLE
How to set up HA for openpai master?

### ISSUE THREAD

**Issue by x1y2z3456** [microsoft/pai#3386]
**Organization Name**: Chaintech

**Short summary about the issue/question**:
I want to set up HA for master, but I'm not sure about what to do.

**Brief what process you are following**:
https://github.com/microsoft/pai/blob/master/docs/pai-management/doc/kubernetes-ha.md

**OpenPAI Environment**:
- OpenPAI version: 0.12.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`): Linux master 4.15.0-45-generic #48~16.04.1-Ubuntu SMP Tue Jan 29 18:03:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
core number: 12 , memory size: 49G, storage size: 256G, no GPU on master node
- Others:

**Comment by abuccts** [comment]
For k8s high availability, you can refer to [this doc](https://github.com/microsoft/pai/blob/master/docs/pai-management/doc/kubernetes-ha.md),

/cc @ydye to help

**Comment by x1y2z3456** [comment]
OK, I got it, thank you very much.
