### ISSUE TITLE
[Deploy] Use cluster-type in to control default service parameters

### ISSUE THREAD

**Issue by wangdian** [microsoft/pai#3436]
Currently PAI has two types: yarn and k8s. The services use different parameters in these types.
The purpose is the admin can setup cluster with minimal change of config.

**Comment by wangdian** [comment]
use cluster.common.cluster-type in services-configuration.yaml to control type.
If service config for a cluster type has specific parameter, define it in [service name]_[cluster type].yaml. The default parameters for all types are stored in [service name].yaml like before.

**Comment by fanyangCS** [comment]
done.
