### ISSUE TITLE
[Feature]Assign a job to specific node

### ISSUE THREAD

**Issue by edenbuaa** [microsoft/pai#3438]
Is it possible that submit and run a job into a specific node? if yes, how to do this?

**Comment by abuccts** [comment]
You can use [dedicated virtual cluster](https://github.com/microsoft/pai/blob/pai-0.14.y/docs/tools/dedicated_vc.md).

/cc @mzmssg

**Comment by edenbuaa** [comment]
@abuccts thanks. I use v0.11.0 of pai, it reports `invalid choice: 'user' (choose from 'badgpus','blacklist')` when I execute the command
`python node_maintain.py user set -u {admin_username} -p {admin_password} -m {master_ip}`

**Comment by abuccts** [comment]
Seems you need to upgrade your pai becasue dedicated virtual cluster is supported in later version.
+@mzmssg to take a look.

**Comment by mzmssg** [comment]
Dedicated vc is supported in v0.14, you need an upgrade.
To achieve the binding, you need:
1. Create a dedicated vc with binding nodes
2. Add user to this vc
3. Submit job to that vc
4. Delete the dedicated vc

**Comment by edenbuaa** [comment]
@mzmssg I have created a dedicated vc following your steps, but I cannot find how to add user to this vc, that document (https://github.com/microsoft/pai/blob/pai-0.14.y/docs/tools/dedicated_vc.md) didn't seems include this operation. Could you explain that? thanks.

**Comment by mzmssg** [comment]
@edenbuaa 
It's the same as common vc, operated in the webport user manaement. 
No need to specify in this doc.

**Comment by edenbuaa** [comment]
ok, got it. thanks.
