### ISSUE TITLE
Hidden part in IP and ports

### ISSUE THREAD

**Issue by ultmaster** [microsoft/pai#3447]
Currently, on job page, the IP and ports looks like this:

![image](https://user-images.githubusercontent.com/8463288/63692828-22950180-c845-11e9-85f1-e346a73da103.png)

This provides nothing useful, even if when my mouse hovers on it, there is still no "title" or "labels" popping out. So in order to know the full address, I have no choice but to press F12 and copies content from that.

**What would you like to be added**: Add a "title" attribute to the web element.

**Why is this needed**: To see the full IP and ports.

**Without this feature, how does the current module work**: Press F12, find them in the webpage elements.

**Components that may involve changes**: Frontend.

**Comment by ultmaster** [comment]
It would be also nice if we can have a button to copy "HOST:PORT" to clipboard, or just host, or just port.

**Comment by abuccts** [comment]
You can toggle the table border to view the full record.
![image](https://user-images.githubusercontent.com/13360214/63737078-cc14db00-c8b7-11e9-99ac-e483987fb07c.png)

/cc @sunqinzheng can we add a tooltip here?

**Comment by sunqinzheng** [comment]
Tooltips and copy buttons will be added in #3499

**Comment by sunqinzheng** [comment]
#3499 merged
