### ISSUE TITLE
User can see others' secrets

### ISSUE THREAD

**Issue by mydmdm** [microsoft/pai#3448]
In current REST API spec, [GET user/:username/jobs/:jobName/config](https://github.com/Microsoft/pai/blob/master/docs/rest-server/API.md#get-userusernamejobsjobnameconfig) will not check the authentication and will feedback the raw job config including plain `secrets` to all users. Thus users can get others' `secrets` via web portal or REST API.

Possible solutions - update API  `user/:username/jobs/:jobName/config`

- For users except for job owner: keep current API format but hide `secrets` in the response
- For job owner, rest server checks authentication token in the header, and feedback complete job config with `secrets`

**Comment by abuccts** [comment]
1. Backend does not store any secrets in config if you used yaml to [submit v2 jobs](https://github.com/microsoft/pai/blob/master/docs/rest-server/API.md#post-jobs).
2. If you add authorization in getting config, clone job feature won't work anymore.

**Comment by mydmdm** [comment]
> 2\. If you add authorization in getting config, clone job feature won't work anymore.

It will not break cloning because 
1. without authentication token, the job config will still be get, only with an empty `secrets` fields; 
2. users are supposed to replace with their own `secrets` in the cloned jobs

**Comment by mydmdm** [comment]
> * Backend does not store any secrets in config if you used yaml to [submit v2 jobs](https://github.com/microsoft/pai/blob/master/docs/rest-server/API.md#post-jobs).

The job config (yaml content) itself (including plain `secrets`) is stored somewhere and user could get via REST API.
