### ISSUE TITLE
[BUG] VC nni show in virtual clusters list but failed when update VC for user.

### ISSUE THREAD

**Issue by mslichao** [microsoft/pai#3451]
VC nni show in virtual clusters list but failed when update VC for user.

![image](https://user-images.githubusercontent.com/40487035/63738975-37fa4200-c8be-11e9-8d58-35244d587289.png)

![image](https://user-images.githubusercontent.com/40487035/63738995-46485e00-c8be-11e9-82e2-3966b2270040.png)

**Comment by mzmssg** [comment]
It's possibly due to test enviroment
