### ISSUE TITLE
How to limit the access of HDFS under the container

### ISSUE THREAD

**Issue by hellocandy** [microsoft/pai#3467]
**Organization Name**: advantech

**Short summary about the issue/question**: After submit job, under the container of job, the HDFS can be accessed without any authority. While we will use the same openpai cluster to provide service for many customers. And we want to know how to limit the access of HDFS under the container. 

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**: cluster
- OpenPAI version: 0.10.1
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by mzmssg** [comment]
You could consider [NFS solution](https://github.com/Microsoft/pai/wiki/Simplified-Job-Submission-for-OpenPAI-with-NFS-deployment)

Currently, HDFS is not a good option to provide authority in OpenPAI.

**Comment by hellocandy** [comment]
We planed to provide the blob storage for customer. However, the job container have the right to access the HDFS, we do not want the user to use the HDFS.

**Comment by fanyangCS** [comment]
we will remove HDFS in pure k8s version. https://github.com/microsoft/pai/issues/3382. This way users won't access the public storage. please watch for our announcement.
