### ISSUE TITLE
Decommission data and job before machine removal.

### ISSUE THREAD

**Issue by sterowang** [Microsoft/pai#349]

**Comment by fanyangCS** [comment]
https://github.com/Microsoft/pai/pull/923 this PR is the first step toward graceful decommission of a node.

**Comment by fanyangCS** [comment]
https://github.com/Microsoft/pai/issues/1852

**Comment by fanyangCS** [comment]
one PR to decommision yarn node manager. https://github.com/Microsoft/pai/pull/2139

**Comment by fanyangCS** [comment]
related https://github.com/Microsoft/pai/issues/2128

**Comment by scarlett2018** [comment]
The work item had been here for 1 year and have several PRs committed, I'm closing it. If there are any new needs, let's create new ones with more clear business needs and technical needs descriptions.
