### ISSUE TITLE
Use ceph instead of hdfs for the dataset storage.

### ISSUE THREAD

**Issue by gemfield** [microsoft/pai#3509]
Is there a feature plan to add Ceph as the second storage backend?
Users can choose either hdfs or Ceph to store the dataset.

**Comment by fanyangCS** [comment]
you can already deploy your own storage solution (including ceph) and mount to it from within job containers.

**Comment by forths** [comment]
https://github.com/microsoft/pai/tree/master/contrib/storage_plugin#Usages_server

**Comment by gemfield** [comment]
@fanyangCS I didn't see any Ceph doc there, so how to use Ceph as the NAS storage?

**Comment by fanyangCS** [comment]
At this stage we do not have a plan to support Ceph officially. If you know how to set up a Ceph server, a job can simply mount to the Ceph server from within the Docker container. If you do not know how to do this, please ask Ceph community for help.

**Comment by gemfield** [comment]
I have setup a Ceph cluster, could you show a simple example that how to mount a CephFS/RBD to the Docker container (with OpenPAI style)?
