### ISSUE TITLE
How to deploy hive on openpai please?

### ISSUE THREAD

**Issue by zhaojizhuang4** [microsoft/pai#3518]
we have several TB data of hive raw format file from production env  ,and we want to analyze it on gpu env , one method is first step deploy hive on openpai using hdfs   ,and then place raw format file on it ,do this method available ? thanks for help

**Comment by scarlett2018** [comment]
@fanyangCS any suggestions?

**Comment by fanyangCS** [comment]
You can deploy Hive on your own and OpenPAI job can leverage it. OpenPAI does not support the deployment of Hive though.
