### ISSUE TITLE
Tasks waiting even if some tasks have already been assigned resources

### ISSUE THREAD

**Issue by ultmaster** [microsoft/pai#3519]
This is more like a feature request/clarification rather than an issue.

Currently, I've been experiencing the situations like this:

![image](https://user-images.githubusercontent.com/8463288/64071225-057a8b80-cca8-11e9-8659-c464e86793d4.png)

Due to the nature of my experiment, I want to run an experiment for, let's say, 20 times, for the assessment of stability. But if I set it to be 20, I have to wait for a long time before I see any of my tasks start running. That's terrible if there is a problem in the experiment (need to wait for a long time to see it failed).

What I want to see, is that some instances have already started running, or have succeeded, even though other instances have been waiting. I know this could be a problem, because in some situations there could be need for synchronization (but in case of that, the user should be aware to hang the job). Another solution is to add a `minTasksReady`, to let the user decide.

**Comment by abuccts** [comment]
Framework launcher in PAI uses [gang scheduling](https://github.com/microsoft/pai/blob/master/subprojects/frameworklauncher/yarn/README.md#features), so only when all tasks are ready will they start to run.
Maybe you can consider to submit 20 jobs instead of 20 tasks.

/cc @yqwang-ms

**Comment by yqwang-ms** [comment]
Launcher supports to enable/disable gang scheduling per job, so could PAI restserver can also let user make his choice? @abuccts

**Comment by yqwang-ms** [comment]
https://github.com/microsoft/pai/blob/b94e63894bc831a2a9ddb421c2263e3f8f0f51b7/subprojects/frameworklauncher/yarn/src/main/java/com/microsoft/frameworklauncher/common/model/PlatformSpecificParametersDescriptor.java#L83

**Comment by scarlett2018** [comment]
@ultmaster - does parallel submit 20 jobs serve your problem?

**Comment by ultmaster** [comment]
Yes. My workaround is to write a script to submit multiple jobs in batch. Working like a charm :)

**Comment by scarlett2018** [comment]
> Yes. My workaround is to write a script to submit multiple jobs in batch. Working like a charm :)

why not use NNI?
