### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe5 in position 159: invalid continuation byte

### ISSUE THREAD

**Issue by lizhaodong** [microsoft/pai#3542]
**Organization Name**:

**Short summary about the issue/question**:

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**: ubuntu18.04
- OpenPAI version: 0.14.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:
exec cmd : python paictl.py  cluster  k8s-bootup -p ~/pai-config, 
![image](https://user-images.githubusercontent.com/1129767/64108842-8ae96300-cdb0-11e9-997f-033f0207d075.png)

**Comment by lizhaodong** [comment]
The local environment problem has been solved.

**Comment by lyjslay** [comment]
could you please tell me how you solved this  problem

**Comment by lizhaodong** [comment]
> could you please tell me how you solved this problem
mend source code: vim  /usr/local/lib/python2.7/dist-packages/paramiko/py3compat.py +64
![image](https://user-images.githubusercontent.com/1129767/64683850-a0e4db00-d4b6-11e9-8a7e-4e9cb4c01c27.png)

**Comment by lizhaodong** [comment]
mend source code: vim /usr/local/lib/python2.7/dist-packages/paramiko/py3compat.py  + 64 







At 2019-09-08 15:51:24, "lyjslay" <notifications@github.com> wrote:


could you please tell me how you solved this problem
