### ISSUE TITLE
Nvidia Driver version problem

### ISSUE THREAD

**Issue by fengzifrank** [microsoft/pai#3561]
Hello, because the company recently installed a number of graphics card drivers are 430.87 not in the list of support. I saw that there was such a similar problem but there is still a little doubt that your solution is to replace the version in the configuration file with the list support. 418.39 But this is not the same as the installed driver version. Does this affect the normal startup operation? Or let dev-box reinstall according to the configuration file. Thank you.

**Organization Name**:

**Short summary about the issue/question**:

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by abuccts** [comment]
Did you install nvidia drivers on your host already? If yes, you should not run drivers service anymore.
You can choose to (uninstall host nvidia drivers or skip drivers service.

**Comment by mzmssg** [comment]
@abuccts 
Driver service should support exsiting drivers detection and skip installation, please correct me.

https://github.com/microsoft/pai/blob/6e3e3ff27fe2a1bca60a74639050fbf82d9e105b/src/drivers/deploy/drivers.yaml.template#L67

**Comment by abuccts** [comment]
> Driver service should support exsiting drivers detection and skip installation, please correct me.
> 
It does not work if there's no such **one** path.

**Comment by wjlzk1** [comment]
现在我的openpai集群运行的默认模板安装,默认安装显卡驱动是383版本.我怎么在不重现部署集群的情况下,将各个节点的驱动版本升级呢??(自己手动到节点尝试过 手动升级,并不奏效)

**Comment by scarlett2018** [comment]
> 现在我的openpai集群运行的默认模板安装,默认安装显卡驱动是383版本.我怎么在不重现部署集群的情况下,将各个节点的驱动版本升级呢??(自己手动到节点尝试过 手动升级,并不奏效)

@fanyangCS @abuccts any suggestions?

**Comment by nan0755** [comment]
Hi, @abuccts 
How to skip driver service?

**Comment by ydye** [comment]
@zeyu-hello Current we haven't implement a solution to skip a service when deploying OpenPAI. But you could delete ```pai/src/drivers/deploy``` as a work around to skip drivers deployment.

**Comment by fanyangCS** [comment]
In v1.x, customers are required to install driver by their own (e.g., through apt-get)
