### ISSUE TITLE
[Pure K8S] REST API verification

### ISSUE THREAD

**Issue by yiyione** [microsoft/pai#3578]
# OpenPAI Pure K8S REST API verification

## Cluster info

- [x] GET /api/v1

## Authn

- [x] GET /api/v1/authn/info
- [x] GET /api/v1/authn/oidc/login
- [x] GET /api/v1/authn/oidc/logout
- [ ] `POST /api/v1/authn/basic/login`
        `NoApiError`

## Group

- [x] GET /api/v2/group/:groupname
- [x] GET /api/v2/group
- [x] PUT /api/v2/group/:groupname/extension
- [x] PUT /api/v2/group/:groupname/extension/:attribute
- [x] PUT /api/v2/group/:groupname/description
- [x] DELETE /api/v2/group/:groupname
- [x] POST /api/v2/group
- [x] PUT /api/v2/group/:groupname/externalname
- [x] GET /api/v2/group/:groupname/userlist

## Job v1

- [x] GET /api/v1/jobs
- [ ] `POST /api/v1/user/:userName/jobs`

```js
{
    "code": "NoApiError",
    "message": "API /api/v1/user/yiyi/jobs is not found."
}
```

Change POST to `POST /api/v1/jobs` got another ERROR:

```js
{
    "code": "InvalidProtocolError",
    "message": "[{\"keyword\":\"type\",\"dataPath\":\"\",\"schemaPath\":\"#/type\",\"params\":{\"type\":\"object\"},\"message\":\"should be object\"}]"
}
```

- Page not found error:

    ```js
    {
        "message": "Page not found",
        "error": {}
    }
    ```

  - [ ] `GET /api/v1/user/:userName/jobs/:jobName`
  - [ ] `PUT /api/v1/user/:userName/jobs/:jobName`
  - [ ] `DELETE /api/v1/user/:userName/jobs/:jobName`
  - [ ] `PUT /api/v1/user/:userName/jobs/:jobName/executionType`
  - [ ] `GET /api/v1/user/:userName/jobs/:jobName/config`
  - [ ] `GET /api/v1/user/:userName/jobs/:jobName/ssh`

Page not found.

## Jobs v2

- [x] GET /api/v2/jobs (Not work in yarn version)
- [x] POST /api/v2/jobs
- [x] GET /api/v2/jobs/:frameworkName
- [x] PUT /api/v2/jobs/:frameworkName/executionType (Not work in yarn version)
- [x] GET /api/v2/jobs/:frameworkName/config
- [ ] `GET /api/v2/jobs/:frameworkName/ssh`

```js
{
    "code": "NoJobSshInfoError",
    "message": "SSH info of job <user name>~<job name> is not found."
}
```

## Token

- [ ] `POST /api/v1/token`

```js
{
    "code": "NoApiError",
    "message": "API /api/v1/token is not found."
}
```

## User

- [x] GET /api/v1/user/:username
- [x] GET /api/v2/user/:username
- [x] GET /api/v2/user
- [x] PUT /api/v2/user/:username/extension

- No api error:

    ```js
    {
        "code": "NoApiError",
        "message": "API /api/v2/user is not found."
    }
    ```

  - [ ] `POST /api/v2/user`
  - [ ] `DELETE /api/v2/user/:username`
  - [ ] `PUT /api/v2/user/:username/virtualcluster`
  - [ ] `PUT /api/v2/user/:username/password`
  - [ ] `PUT /api/v2/user/:username/email`
  - [ ] `PUT /api/v2/user/:username/admin`
  - [ ] `PUT /api/v2/user/:username/grouplist`
  - [ ] `PUT /api/v2/user/:username/group`
  - [ ] `DELETE /api/v2/user/:username/group`

## Virtual-Cluster

- Unknow Error:

    ```js
    {
        "code": "UnknownError",
        "message": "Unexpected token u in JSON at position 0"
    }
    ```

  - [ ] `GET /api/v1/virtual-clusters`
  - [ ] `PUT /api/v1/virtual-clusters/:vcName`
  - [ ] `PUT /api/v1/virtual-clusters/:vcName/status`
  - [ ] `DELETE /api/v1/virtual-clusters/:vcName`

- [ ] `GET /api/v1/virtual-clusters/:vcName`

```js
Status: 200

{}
```

Always return empty (default, vc1, vc2).

- [x] GET /api/v2/virtual-clusters
- [x] GET /api/v2/virtual-clusters/nodeResource
- [x] GET /api/v2/virtual-clusters/:virtualClusterName
- [x] GET /api/v2/virtual-clusters/:virtualClusterName/resourceUnits (Not work in yarn version)

- Not Implemented Error:

    ```js
    {
        "code": "NotImplementedError",
        "message": "updateVc not implemented in k8s",
        "message": "updateVc not implemented in k8s",
        "message": "removeVc not implemented in k8s",
        "message": "stopVc not implemented in k8s"
    }
    ```

  - [ ] `PUT /api/v2/virtual-clusters/:virtualClusterName`
  - [ ] `DELETE /api/v2/virtual-clusters/:virtualClusterName`
  - [ ] `PUT /api/v2/virtual-clusters/:virtualClusterName/status`

**Comment by fanyangCS** [comment]
Done in API compatibility test.
