### ISSUE TITLE
[cluster-object-model] Add cluster-type into each service's config

### ISSUE THREAD

**Issue by ydye** [microsoft/pai#3581]
In k8s mode only generate k8s-relative configuration.
In yarn mode only generate yarn-relative configuration.

**Comment by scarlett2018** [comment]
@ydye - what's this configure for? what if we do not have them?

**Comment by ydye** [comment]
> @ydye - what's this configure for? what if we do not have them?

Tell cluster-object-model this service is needed in k8s-type or yarn-type or both of them. Then in some specific situation we can skip some module's configuration generation..
