### ISSUE TITLE
How to do compatible with centos7. I change some config file but it doesn't work with error is: the server doesn't have a resource type "node"

### ISSUE THREAD

**Issue by archer-z** [microsoft/pai#3590]
**Organization Name**:

**Short summary about the issue/question**:

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**: 
- OpenPAI version: v0.14
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):centos7.6
- Kernel (e.g. `uname -a`):Linux node1 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by fanyangCS** [comment]
sorry. we do not support centos for now. in the future, we plan to allow user to use third-party tool to deploy k8s (e.g., AKS, kubespray).

**Comment by archer-z** [comment]
if i really want to deploy it for centos, how can i do, could you gei me some advise? Thank you so much!




------------------ 原始邮件 ------------------
发件人: "fan yang"<notifications@github.com>; 
发送时间: 2019年9月9日(星期一) 下午4:19
收件人: "microsoft/pai"<pai@noreply.github.com>; 
抄送: "好人"<1158667545@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [microsoft/pai] How to do compatible with centos7. I change someconfig file but it doesn't work with error is: the server doesn't have aresource type "node" (#3590)




sorry. we do not support centos for now. in the future, we plan to allow user to use third-party tool to deploy k8s (e.g., AKS, kubespray).

**Comment by fanyangCS** [comment]
@ydye, can you provide some information?

**Comment by fanyangCS** [comment]
With the new pure k8s version, you can use kubespray to deploy k8s in centos and then deploy OpenPAI services afterward

**Comment by archer-z** [comment]
sorry I just saw you message, my host is centos and images with installed modules is ubuntu&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"fan yang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月12日(星期二) 晚上9:41
收件人:&nbsp;"microsoft/pai"<pai@noreply.github.com&gt;;
抄送:&nbsp;"好人"<1158667545@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/pai] How to do compatible with centos7. I change some config file but it doesn't work with error is: the server doesn't have a resource type "node" (#3590)




Closed #3590.

**Comment by zlwzlwzlw** [comment]
it can already deployment, and work recently, thanks

**Comment by archer-z** [comment]
It can already deployment, and work recently, thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"fan yang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月12日(星期二) 晚上9:41
收件人:&nbsp;"microsoft/pai"<pai@noreply.github.com&gt;;
抄送:&nbsp;"好人"<1158667545@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/pai] How to do compatible with centos7. I change some config file but it doesn't work with error is: the server doesn't have a resource type "node" (#3590)




Closed #3590.

**Comment by jwgu** [comment]
@archer-z : Can you please explain how you solve this problem? Thanks in advance.
