### ISSUE TITLE
[Launcher] Do not list child jobs by default.

### ISSUE THREAD

**Issue by sterowang** [Microsoft/pai#360]
Child jobs created by top level jobs should not listed unless a "all" parameter is specified.

**Comment by sterowang** [comment]
Some jobs want's to create child jobs such as NNI. Users sometimes only want to list out top level jobs such as several NNI sessions first, then if select a specific NNI session job, it can list out the all child jobs created in this session.

**Comment by fanyangCS** [comment]
this is not something PAI will support, as it involves job session (a set of jobs belong to one automl session) level information, which PAI should not be aware of.
Maybe we can expose a metadata filed for each job, and higher level service like automl can leverage this field to achieve this goal. Here is a related issue: https://github.com/Microsoft/pai/issues/2228

**Comment by fanyangCS** [comment]
I will close this issue. Feel free to reopen it if the solution is insufficient.

**Comment by scarlett2018** [comment]
We should support "Tags" for job, that's more flexibile for different grouping and query purpose.
