### ISSUE TITLE
How to auto monitor the status of tasks.

### ISSUE THREAD

**Issue by IamSunGuangzhi** [microsoft/pai#3602]
**Short summary about the issue/question**:
I wan to auto monitor the status of tasks. When the tasks happen error, I can get the error right away. And don`t need add the alert manually, when i submit a job. For example, pai can support the alert of dingding。

**OpenPAI Environment**:
- OpenPAI version: v0.14.0
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Hardware (e.g. core number, memory size, storage size, GPU type etc.): titan Xp

**Anything else we need to know**:
NULL

**Comment by IamSunGuangzhi** [comment]
how to support the task error alerts!
grafana? alertmanager?

**Comment by scarlett2018** [comment]
@IamSunGuangzhi - thanks for raising the feature request. is this request for an PAI end user's daily training job or for a PAI admin?

**Comment by IamSunGuangzhi** [comment]
Thanks for your reply, @scarlett2018 .  This request is for an PAI end user's daily training job. Because PAI is training platform. PAI can auto monitor the status of tasks, which facilitates task debugging.

**Comment by scarlett2018** [comment]
OpenPAI does not have plan to support dingding alike IM integration. But we could think of providing status change subscription for email address, or status feed, etc. Adding to the backlog for feature design and discussion first.

**Comment by yqwang-ms** [comment]
Reasonable feature request, but it is not in our planning yet.
We may leverage https://www.elastic.co/what-is/elasticsearch-alerting, alertmanager, or something like https://github.com/bitnami-labs/kubewatch.

For now, you can achieve this by yourself, such as, polling the RestServer and send alert on some conditions.

**Comment by IamSunGuangzhi** [comment]
OK, thanks @scarlett2018  @yqwang-ms . I will try.

**Comment by scarlett2018** [comment]
Thanks, closing the issue as answer had been taken. Please few free to reopen if you meet any issue while applying the suggestions.
