### ISSUE TITLE
[Bug] Full log is unavailable in v14 version

### ISSUE THREAD

**Issue by edenbuaa** [microsoft/pai#3615]
PAI Version: v0.14.0
WebPortal:  http://master-ip/

It seems that the full log href link is wrong on the job detail page, it links to 
`http://master-ip/node/containerlogs/container_e04_1568009317169_1075_01_000002/user/user.pai.stdout/?start=0`
but this page shows:
`{"message": "Page not found", "error":{}}`
how to fix it? thanks.

**Comment by IamSunGuangzhi** [comment]
Yes, we have the same problem.

**Comment by scarlett2018** [comment]
@IamSunGuangzhi - thanks for reporting the issue, this is a known issue in 0.14.0, we had fixed it in later branch. 

**To walk around the issue** you can use the "..." after "Stderr", click "Go to Tracking Page" and then click the full log link there.

**Comment by scarlett2018** [comment]
let me know if the walk around works for you, I will close the issue accordingly, thanks @IamSunGuangzhi =).

**Comment by edenbuaa** [comment]
@scarlett2018 Do you mean this bug would been fixed if I pull the latest codes of v14 branch and rebuild the webportal image?

**Comment by scarlett2018** [comment]
The fix might still in dev's personal branch, we did not plan to merge for another release yet. 

+ @sunqinzheng to confirm @edenbuaa 's question.

**Comment by IamSunGuangzhi** [comment]
@scarlett2018 Thanks. This way works for me. You can close the issue.
