### ISSUE TITLE
[Feature] Permission for user's job

### ISSUE THREAD

**Issue by edenbuaa** [microsoft/pai#3632]
PAI version: v0.14.0
Is there a feature to set the permission (private or public) for user's job, and it works on the visibility of job to others?

**Comment by scarlett2018** [comment]
@edenbuaa - thanks for asking this question. it is not yet supported today. we are considering adding it in later versions. We'd like to hear more about how you'd like to set the permissions, per job or per person or per group, etc.

**Comment by edenbuaa** [comment]
Thanks. I wish this feature could follow these rules:
1. user's jobs are isolated by group level
2. one user could belong to multiple groups
3. a config to set the user job's visibility to others' within a group

**Comment by scarlett2018** [comment]
> @scarlett2018 - thanks. I wish this feature could follow these rules:
> 
> 1. user's jobs are isolated by group level
> 2. one user could belong to multiple groups
> 3. a config to set the user job's visibility to others' within a group. If true, user's job is public in group, or only visible to himself.

@edenbuaa - thanks for the valuable feedback, we will consider this during design. Would you mind share how you are using OpenPAI in your organization today for our reference? like:



**Organization Name**:



**Short summary about the issue/question**:

**Brief what process you are following**:





**How to reproduce it**:



**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by edenbuaa** [comment]
Sure @scarlett2018 ,thanks.

Organization Name: ODDC

Short summary about the issue/question: Need a feature works on the permission for user's job

Brief what process you are following:    

1. user's jobs are isolated by group level
2. one user could belong to multiple groups
3. a config to set the user job's visibility to others' within a group. If true, user's job is public in group, or only visible to himself.

OpenPAI Environment:

    OpenPAI version: v0.14.0
    Cloud provider or hardware configuration:
    OS (e.g. from /etc/os-release): ubuntu16.04
    Kernel (e.g. uname -a):
    Hardware (e.g. core number, memory size, storage size, GPU type etc.):
    Others:

**Comment by scarlett2018** [comment]
Thanks @edenbuaa! BTW, the full name of ODDC is?

**Comment by edenbuaa** [comment]
open data center committee
