### ISSUE TITLE
drivers-one-shot is not ready yet. Please wait for a moment! 

### ISSUE THREAD

**Issue by wjlzk1** [microsoft/pai#3634]
Readiness probe failed: cat: /jobstatus/jobok: No such file or directory
Back-off restarting failed container

**Comment by wjlzk1** [comment]
what shoud  i  do ...... now

**Comment by scarlett2018** [comment]
@wjlzk1 - please provide more information like: which OpenPAI version are you using? when this problem happened.

**Comment by fanyangCS** [comment]
close as no further response.
