### ISSUE TITLE
Long run jobs policies and actions

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#3640]
There are users in the cluster who resolve resources for long time, most of the time these jobs are not actively working, the resources were locked for ease of remote debug.

As an admin, we'd like to avoid this type of misbehave. One simple help can provide by the platform is like:
- automated generate a long run (i.e. > 7d) jobs summary to Admin
- allow admin to set an automated stop long run rule
- send notification to users who have long run jobs and ask them to take actions
- enable auto stop long run jobs for admin

**Comment by fanyangCS** [comment]
closed and tracked in #5337
