### ISSUE TITLE
K8s bootup about python failing

### ISSUE THREAD

**Issue by wjx0818** [microsoft/pai#3646]
When I run python paictl.py cluster k8s-bootup \
  -p ~/pai-config.  Errors will be reported below.
failed install python
![A3A5FB1A-40A1-47E2-8163-8BBD688B0F92](https://user-images.githubusercontent.com/55446020/65046134-9765e200-d992-11e9-8995-c4ffc8b99178.jpeg)

**Comment by abuccts** [comment]
What's the output of `python -V` and `whereis python`?

**Comment by scarlett2018** [comment]
@wjx0818 - in addition to @abuccts 's question, which version are you using?

**Comment by wjx0818** [comment]
> @ wjx0818-除了@abuccts的问题之外，您还在使用哪个版本？

python2、7/python3‘5/anaconda3-7

**Comment by scarlett2018** [comment]
@wjx0818 I mean the version of OpenPAI.

**Comment by fanyangCS** [comment]
close as no further response.
