### ISSUE TITLE
pai webportal logout with AAD could not redirect to login page

### ISSUE THREAD

**Issue by debuggy** [microsoft/pai#3651]
When user enter pai webportal without login, the url should redirect to login page. However currently the redirect does not work.

Reproduce step:
1. go to vnext webportal url: <vnext_url>/home.html
2. if you in a sign in status, click sign out
3. the page could not redirect to index page
4. if you did not sign in before, the page is supposed to redirect to index page to let you sign in. However it did not work.

As a result the browser stuck in this page:
![image](https://user-images.githubusercontent.com/8444268/65134609-1f9dc300-da37-11e9-80da-150f30a98af9.png)

**Comment by debuggy** [comment]
#3625 did not solve this issue throughly

**Comment by fanyangCS** [comment]
fixed in https://github.com/microsoft/pai/pull/3937
