### ISSUE TITLE
[Deploy] Unable to compare pai_version and cluster_version correctly

### ISSUE THREAD

**Issue by TongboZhang** [microsoft/pai#3656]
![image](https://user-images.githubusercontent.com/12277407/65210686-91751b80-dace-11e9-941b-9433c57cac0f.png)

How to fix:
Should remove '\n' in `cluster_version`.

Will fix in #3637.

**Comment by fanyangCS** [comment]
done in https://github.com/microsoft/pai/pull/3826.
