### ISSUE TITLE
[Storage Manager] Add a service storage-manager to maintain NFS and SMB

### ISSUE THREAD

**Issue by TongboZhang** [microsoft/pai#3657]
This new service will have the following characteristics:
1.	Create an NFS server
2.	Create an SMB server with or without AAD enabled
3.	Report liveness to k8s

This service will only be deployed on the node tagged as pai-storage in layout.yaml.
The configuration of SMB AAD (krb5.conf) will be stored in the configmap of k8s.

- [x] SMB server
  - [x] Start SMB server in docker
  - [x] Read krb5.conf from configmap
  - [x] SMB with/without AAD enabled
  - [x] Report liveness to k8s
- [x] NFS server
  - [x] Start NFS server in docker
  - [x] Enable kernel modules in docker if needed
  - [x] Report liveness to k8s
- [x] Deployment
  - [x] Change paictl to pull and push krb5.conf in configmap
  - [x] Add a role named `pai-storage`
- [ ] Doc

Bug fix:
#3656

**Comment by scarlett2018** [comment]
@TongboZhang - which branch will this new feature commit to? master or K8S alpha?

**Comment by TongboZhang** [comment]
> @TongboZhang - which branch will this new feature commit to? master or K8S alpha?

@scarlett2018 This will commit to master.
