### ISSUE TITLE
Error from server (AlreadyExists): secrets "job-ssh-secret" already exists

### ISSUE THREAD

**Issue by ydye** [microsoft/pai#3662]
#### 1
https://github.com/microsoft/pai/blob/9b78d0cb6fa73122bdd1a78dd09feb6fd6435b0a/src/cluster-configuration/deploy/secret-create.sh#L21

Please refer to secret in the following approach.

https://github.com/microsoft/pai/blob/master/src/cluster-configuration/deploy/configmap-create.sh

**Comment by fanyangCS** [comment]
this should be removed later.

**Comment by wangdian** [comment]
Merged, related PR: #3838 
Close this issue
