### ISSUE TITLE
[Deploy]Custom the cleanup interval of job history

### ISSUE THREAD

**Issue by edenbuaa** [microsoft/pai#3675]
PAI Version: v0.14.0

For now, the finished jobs would be cleanup  in about 30 days, How to custom this config and Is it possible to archive these jobs before cleanup? 

thanks for any suggestion.

**Comment by abuccts** [comment]
Hi, you can increase `frameworkCompletedRetainSec` [here](https://github.com/microsoft/pai/blob/master/src/yarn-frameworklauncher/deploy/yarn-frameworklauncher-configuration/frameworklauncher.yml#L40), pls refer to #1039.

There's no api to archive jobs currently, maybe you can dump job list json, or backup zookeeper data.

**Comment by edenbuaa** [comment]
got it. thanks.
