### ISSUE TITLE
GPU ：scheduling of resource

### ISSUE THREAD

**Issue by lirq-q** [microsoft/pai#3692]
**What would you like to be added**:
There are multiple GPU CARDS in an openpai cluste，eg:1080TI、2080TI、2080，all GPU resources are allocated，
Two days later，To take back the resources of the specified GPU card and use them for other projects,such as 2080TI。
**Why is this needed**:
We want to use multiple GPU CARDS in a cluster, but the resources that have been recaptured so far are randomly allocated。We applied for resources of 2080TI, but maybe we got 1080TI in the end, so we did not allocate resources as expected.I don't know if this is an expectation or a bug
**Without this feature, how does the current module work**:
Currently, a cluster is set up for each type of card
**Components that may involve changes**:

**Comment by lirq-q** [comment]
> **What would you like to be added**:
> There are multiple GPU CARDS in an openpai cluste，eg:1080TI、2080TI、2080，all GPU resources are allocated，
> Two days later，To take back the resources of the specified GPU card and use them for other projects,such as 2080TI。
> **Why is this needed**:
> We want to use multiple GPU CARDS in a cluster, but the resources that have been recaptured so far are randomly allocated。We applied for resources of 2080TI, but maybe we got 1080TI in the end, so we did not allocate resources as expected.I don't know if this is an expectation or a bug
> **Without this feature, how does the current module work**:
> Currently, a cluster is set up for each type of card
> **Components that may involve changes**:

**Comment by fanyangCS** [comment]
we will support this in next release (after 0.15)
