### ISSUE TITLE
how to uninstall openpai

### ISSUE THREAD

**Issue by dq116** [microsoft/pai#3697]
Several days ago, I successfully installed the openpai  in three computers .But later I think the distribution is not well.I want to remove the master node  out of the cluster.Actually,I want to change  the pervious master into the host for deployment and change the previous host for deployment into the master 。I think uninstalling the pai is a method.  So I want to ask how can I totally uninstall the pai? Or are there other better solutions？

**Comment by abuccts** [comment]
please try
```sh
python paictl.py service delete
python paictl.py cluster k8s-clean -p /path/to/cluster-configuration/dir
```

**Comment by fanyangCS** [comment]
close as no further response.
