### ISSUE TITLE
P1 - Job Near FIFO scheduling

### ISSUE THREAD

**Issue by yqwang-ms** [microsoft/pai#3704]
**What would you like to be added**:

**Why is this needed**:

**Without this feature, how does the current module work**:

**Components that may involve changes**:

**Potential Solutions**:
1. [**LongTerm**][Strict FIFO]: Support workflow/jobdependeny by user or PAI (such as Aether https://github.com/microsoft/pai/issues/3702) - **Pending**
2. [**Picked**][Near FIFO]: RestServer leverage [Pod priority](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/) to nearly ensure Job FIFO scheduling in default scheduler - **Works: near FIFO, need to disable Priority Admission Controller and set per job priority decreasingly, [disable k8s preemption](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#how-to-disable-preemption), a little hack and [small chances to starve later jobs](https://github.com/kubernetes/kubernetes/issues/71486#issuecomment-445567835)**
Such as PodPriority=-(MaxJobPriority-JobPriority, JobCreationTime)
     ```
     Given JobPriority range: [-1, 126]
     PodPriority int32bits =
     FixToNegative: uint1bits = (Fix to 1) | 
     JobPriority: uint8bits = (126 - JobPriority) | 
     JobCreationTime: uint23bits = (UnixEpoch % (2^23))
     ```
   This makes sure job Pod priority is by default lower than system services Pod priority, and k8s reserved priorities.
3. [**LongTerm**][Near FIFO]: Changes for default scheduler to do FIFO queuing according to the Pod creation time instead of the Pod last queued time by scheduler. - **Long term to be on AKS and [small chances to starve later jobs](https://github.com/kubernetes/kubernetes/issues/71486#issuecomment-445567835) and cannot tolerate job interleave such as task retry**
Tracked in https://github.com/kubernetes/kubernetes/issues/83834 and fixed by https://github.com/kubernetes/kubernetes/pull/83835.
4. [Infeasible][Weak FIFO]: Leverage existing default scheduler FIFO queue - **Not work: Very weak FIFO**
5. [Infeasible][Weak FIFO]: Leverage existing default scheduler Priority queue - **Not work: Very weak FIFO**

**Tests**:
Setup scheduler with No HA and No Restart.
- [x] Priority queue + Decreasing Pod Priority: **Works: near FIFO** (<5% cut in line)
- [x] Priority queue + Same Pod Priority: **Not work** (>40% cut in line)
- [x] Priority queue + Same Pod Priority + Using Pod creation time to sort: **Works: near FIFO** (<5% cut in line)
- [x] FIFO queue: **Not work** (>40% cut in line)
![image](https://user-images.githubusercontent.com/32826762/66626461-ea962200-ec2a-11e9-95ed-380e35cfc248.png)
![image](https://user-images.githubusercontent.com/32826762/66626479-f97cd480-ec2a-11e9-9112-567a9328e3d6.png)
![image](https://user-images.githubusercontent.com/32826762/66626488-000b4c00-ec2b-11e9-9068-a819e847e825.png)
![image](https://user-images.githubusercontent.com/32826762/66626501-08fc1d80-ec2b-11e9-8447-9ee0b534f391.png)

**Comment by yqwang-ms** [comment]
Seems we cannot support FIFO without changing k8s code.
So prefer Solutions.1:
[Most Strong FIFO]: Support workflow/jobdependeny by user or PAI (such as Aether #3702)

**Comment by fanyangCS** [comment]
@yqwang-ms , maybe we can sort the pods by its submission time before scheduling in HiveD?

**Comment by yqwang-ms** [comment]
@fanyangCs
The next scheduling pod is sent from default scheduler to HiveD. HiveD cannot control the sending order, but it can skip to schedule the out of order pods, which looks too hack.

Anyway, I do not think **strict** job FIFO should be supported by FC or Hived, it should be supported by a workflow/dependency controller, like https://github.com/argoproj/argo.
And for **weak** job FIFO, like current situation is acceptable for non-workflow/dependency jobs.

**Comment by yqwang-ms** [comment]
From current investigation:
Default scheduler FIFO queue cannot ensure FIFO mainly due to:
1. New Pod is added to queue according to scheduler **seen time** instead of Pod creation time
2. Pod which failed to schedule will be added back to the tail of FIFO queue, which may **behind the Pod newer than it**.
3. Scheduler view is updated between 2 Pods scheduling, so **later Pod may scheduled** to newly freed resource that previous Pod failed to schedule to.

Later Pod is scheduled but previous not:
```
I1011 07:01:50.803619       1 scheduling_queue.go:908] About to try and schedule pod default/f5rqerbecxz4cja69wuk0c1d64-train-64
I1011 07:01:50.803635       1 scheduler.go:453] Attempting to schedule pod: default/f5rqerbecxz4cja69wuk0c1d64-train-64
I1011 07:01:50.803786       1 factory.go:647] Unable to schedule default/f5rqerbecxz4cja69wuk0c1d64-train-64: no fit: 0/7 nodes are available: 1 node(s) didn't match node selector, 6 Insufficient nvidia.com/gpu.; waiting
I1011 07:01:50.803828       1 factory.go:742] Updating pod condition for default/f5rqerbecxz4cja69wuk0c1d64-train-64 to (PodScheduled==False, Reason=Unschedulable)
I1011 07:01:50.803838       1 scheduler.go:465] Pod priority feature is not enabled or preemption is disabled by scheduler configuration. No preemption is performed.

I1011 07:01:50.842156       1 scheduling_queue.go:908] About to try and schedule pod default/f5rqerbecxz4cja69wuk0c1d68-train-0
I1011 07:01:50.842176       1 scheduler.go:453] Attempting to schedule pod: default/f5rqerbecxz4cja69wuk0c1d68-train-0
I1011 07:01:50.842455       1 factory.go:647] Unable to schedule default/f5rqerbecxz4cja69wuk0c1d68-train-0: no fit: 0/7 nodes are available: 1 node(s) didn't match node selector, 6 Insufficient nvidia.com/gpu.; waiting
I1011 07:01:50.842507       1 factory.go:742] Updating pod condition for default/f5rqerbecxz4cja69wuk0c1d68-train-0 to (PodScheduled==False, Reason=Unschedulable)
I1011 07:01:56.157324       1 scheduler.go:465] Pod priority feature is not enabled or preemption is disabled by scheduler configuration. No preemption is performed.

I1011 07:01:56.157503       1 scheduling_queue.go:908] About to try and schedule pod default/f5rqerbecxz4cja69wuk0c1d68-train-1
I1011 07:01:56.157522       1 scheduler.go:453] Attempting to schedule pod: default/f5rqerbecxz4cja69wuk0c1d68-train-1
I1011 07:01:56.157930       1 scheduler_binder.go:269] AssumePodVolumes for pod "default/f5rqerbecxz4cja69wuk0c1d68-train-1", node "10.151.41.19"
I1011 07:01:56.157950       1 scheduler_binder.go:279] AssumePodVolumes for pod "default/f5rqerbecxz4cja69wuk0c1d68-train-1", node "10.151.41.19": all PVCs bound and nothing to do
I1011 07:01:56.157992       1 factory.go:733] Attempting to bind f5rqerbecxz4cja69wuk0c1d68-train-1 to 10.151.41.19
```

**Comment by yqwang-ms** [comment]
We now have 2 choices:
1. [Strong FIFO]: Support workflow/jobdependeny by user or PAI (such as Aether #3702) - Prefered
2. [Near FIFO]: RestServer leverage Pod priority to nearly ensure Job FIFO scheduling in default scheduler - Works: near FIFO, need to disable Priority Admission Controller and set per job priority decreasingly, a little hack

@fanyangCS @sterowang what is your suggestion?
