### ISSUE TITLE
P2 - Support job max parallelism: max running task count

### ISSUE THREAD

**Issue by yqwang-ms** [microsoft/pai#3705]
**What would you like to be added**:
I.e. Per job total capacity throttling (100k datapartition -> 100k tasks in one job)

However, static datapartition to task mapping k-1, or dynamic mapping based on queue maybe better.

**Why is this needed**:

**Without this feature, how does the current module work**:

**Components that may involve changes**:

**Comment by fanyangCS** [comment]
I think we can live with that for now. feel free to reopen this issue if requirement changes.
