### ISSUE TITLE
What will happen if the jobs reaches the limit (60k jobs)

### ISSUE THREAD

**Issue by hellocandy** [microsoft/pai#3711]
**Organization Name**: Advantech

**Short summary about the issue/question**: According to the default configuration, PAI supports 60k jobs, including waiting/running/finished jobs. What will happen if the jobs reaches the limit (60k jobs)?

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by fanyangCS** [comment]
we support more than 60k jobs.
