### ISSUE TITLE
[BUG]virutual cluster is not cloned

### ISSUE THREAD

**Issue by edenbuaa** [microsoft/pai#3718]
PAI Version: v0.14.0

1. The `virutal cluster` field is not cloned when clone a job, is there a easy way to fix this temporarily?
2. The `shm `option is not allowed in the YAML job protocol, is there a plan to support this again?
thanks for any suggestions.

**Comment by abuccts** [comment]
For 1, it's fixed in #3473, you change to v0.15 webportal.
For 2, it's allowed in `extraContainerOptions.shm` https://github.com/microsoft/pai/blob/7953d59a4abd892e9fc878aa0e92a6a940988e83/docs/pai-job-protocol.yaml#L60-L61 the value is fixed to `512` in v0.14, and uses config value in v0.15.

**Comment by edenbuaa** [comment]
@abuccts Thanks.
