### ISSUE TITLE
GPU:Can openpai manage multiple gpus?

### ISSUE THREAD

**Issue by lirq-q** [microsoft/pai#3724]
**Organization Name**:

**Short summary about the issue/question**:
1.Whether openpai cluster can manage multiple gpus？
2.If the cluster can manage a variety of gpus, can the specified gpus run JOB in the process of use？
**Brief what process you are following**:
Cluster creates 2 queues.One 0%, one 100%，Is it possible to allocate multiple GPU resources when 100% queue resources are allocated?
If we want to use a 0% queue, if we want to grab 100% of the queue's resources,In this process, it is currently clear that the resource allocation of the preempted queue is random. Can it be realized to allocate resources according to the type of GPU when the preempted queue is allocated?

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:V0.14.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):Ubuntu 16.04
- Kernel (e.g. `uname -a`):3.19.0-25
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
cpu:i7-9800x  8core 16threads
memory size:128G
storage size: system disk 1G
GPU type:NVIDIA 2080TI、NVIDIA 1080TI
-Others:

**Anything else we need to know**:

**Comment by fanyangCS** [comment]
I'm not sure if I understand your question. as of 0.14 our scheduler is YARN based, so the behavior should be the same as YARN scheduler. And we do not officially support multiple type of GPU yet.

**Comment by lirq-q** [comment]
Have we tried using multiple types of gpus in a cluster?When it comes to cluster building, only one type of GPU is used?

**Comment by fanyangCS** [comment]
yes. we will announce the support to multiple type of GPU later.

**Comment by fanyangCS** [comment]
Please keep an eye on this release plan, which includes the support to different GPU types. https://github.com/microsoft/pai/issues/3382
