### ISSUE TITLE
problem of “kubectl get nodes”

### ISSUE THREAD

**Issue by gxfun** [Microsoft/pai#373]
./bootstrap.py -p /path/to/your/clusterconfig.yaml -a deploy

when executeing the command "kubectl get nodes", this is a problem "The connection to the server 192.168.6.23：8080 was refused - did you specify the right host or port?" can you help me solve this problem? Thanks

**Comment by ydye** [comment]
Hi,
Do you deploy k8s as a ha cluster or a single master cluster? 192.168.6.23 is a load balance ip or the master ip.

**Comment by gxfun** [comment]
@ydye 
Hi, I note deploy k8s as ha cluster.  in bootstrap.py, related code is commented 
component_list:
  haproxy:
  - src: haproxy.yaml
    dst: src/etc/kubernetes/manifests
  - src: haproxy.cfg
    dst: src/haproxy
    
remote_deployment:
  proxy:
    listname: proxymachinelist
    component:
    - name: kubelet
    - name: haproxy
    
proxymachinelist:

  proxy-01:
    nodename: IP
    hostip: IP
    username: username
    password: password

192.168.6.23 is a master ip. firewall is also disabled.

now, in 192.168.6.23, there are two containers running，including kubelet（hyperkube:v1.7.3）and kubernetes-deployment. In work node(192.168.6.22),only hyperkube:v1.7.3 is running

**Comment by ydye** [comment]
1） Can you show me your whole cluster-configuration of k8s ? (Hide the sensitive information such as IP)
2） Can you check the Path （/etc/kubernetes/manifests）in your master host ？

**Comment by gxfun** [comment]
@ydye
Thanks！

 [The details of cluster-configuration and the *.yaml in /etc/kubernetes/manifests ](https://github.com/gxfun/Dockerfile/blob/master/configuration/details)

In addition, our host is an internal network that can't get software directly from the Internet

**Comment by ydye** [comment]
1) Possible probelm
check the dns server configured in your host.
``` 
cat /etc/resolv.conf
```

Now the dns configured in the cluster-configuration is : 168.63.129.16 
I found this is the example dns address we left on the example cluster-configuration.

```
 --cluster-dns stringSlice                                                                                   Comma-separated list of DNS server IP address.  This value is used for containers DNS server in case of Pods with "dnsPolicy=ClusterFirst". Note: all DNS servers appearing in the list MUST serve the same set of records otherwise name resolution within the cluster may not work correctly. There is no guarantee as to which DNS server may be contacted for name resolution.
```
https://kubernetes.io/docs/reference/generated/kubelet/

2) Maybe Another problem in your cluster-configuration
The node : ```infra-01``` and ```worker-01``` should be same with your hostname which you could get by the command  ```echo `hostname````

**Comment by gxfun** [comment]
@ydye
Thanks !

After changing `cluster-dns, infra-01, worker-01`, this still output the problem.  But after about 30 seconds, everything is normal and kubernetes initializes successful.

I guess this is caused by this code `while  True` in bootstrap.py(line 266)

``` python
   while True:
        res = execute_shell_return( "kubectl get node", "Error in kubectl installing" )

        if res == True:
            break
```

Thanks again！

**Comment by ydye** [comment]
Hi
```
 while True:
        res = execute_shell_return( "kubectl get node", "Error in kubectl installing" )

        if res == True:
            break
```

This code is put here, because sometime api-server can not be ready when the kubectl is installed. So we set the while loop here to wait the api-server be a ready status, so that api-server could solve the request from kubectl. Or the script will be terminated.

**Comment by ydye** [comment]
No continuous update. close this Issue.
