### ISSUE TITLE
[OpenPAI@AKS] nvidia-runtime hasn't mounted nvidia-smi automaticly

### ISSUE THREAD

**Issue by ydye** [microsoft/pai#3733]
https://github.com/Azure/AKS/issues/1271

@abuccts Which service depending on nvidia-runtime is affacted? Can you comment below ?

For OpenPAI Service， service owner should mount the nvidia-smi manually in the yaml file and set nvidia environment at the same time.

**Comment by abuccts** [comment]
* job exporter
* user jobs

**Comment by fanyangCS** [comment]
job exporter has privilege mode, it can detect whether nvidia-smi is missing. user jobs need init-container's help.
