### ISSUE TITLE
vnext rest api could not filter jobs by user

### ISSUE THREAD

**Issue by debuggy** [microsoft/pai#3738]
Reproduce Step:

1. Get  <vnext_rest_server>/api/v1/jobs?username=xxx

2. The API will return all jobs instead of only returning jobs of xxx

**Comment by wangdian** [comment]
As discussed in scrum, in k8s version, the user filter should be implemented by filter pod labels.

**Comment by debuggy** [comment]
> 
> 
> As discussed in scrum, in k8s version, the user filter should be implemented by filter pod labels.

So the code of rest server should be changed?
