### ISSUE TITLE
[pure-k8s] Bug fix: http://restserver/api/v1/user/:username/jobs will get all jobs

### ISSUE THREAD

**Issue by wangdian** [microsoft/pai#3740]
Rest API http://restserver/api/v1/user/:username/jobs will get all jobs instead of get user's jobs.

**Comment by fanyangCS** [comment]
I think this has been fixed. @abuccts ?

**Comment by abuccts** [comment]
we didn't support `/user/:username/jobs/:jobname` format name in k8s version, use `username~jobname` instead
