### ISSUE TITLE
Does the prerequisite of env deployment must be Ubuntu?

### ISSUE THREAD

**Issue by HistoryGift** [microsoft/pai#3743]
I read the readme.md, the prerequisites need Ubuntu ,but my env is redhat7.5 
so i would like to know whether OpenPAI can be deployed on redhat7.5 ?

**Comment by fanyangCS** [comment]
We have not tried Redhat. In the future, we will allow you to use third party tool to deploy k8s, and paictl  can deploy OpenPAI services on such k8s deployment. In that case, you can figure out whether the third party tool (e.g., AKS, Kubespray) can support Redhat.
