### ISSUE TITLE
Error:[WebHDFS] when submit a job

### ISSUE THREAD

**Issue by visaki** [microsoft/pai#3745]
Last week the cluster was replaced with a new master node and redeployed to the same version v0.14.0 as before.  The worker node was not changed

But now submitting the task will pop up a window with a long paragraph about the WebHDFS Container permission rejection, causing the task to fail to be submitted.

Some keywords:    Error:[WebHDFS] 403;   org.apache.hadoop.security.AccessControlException; Permission denied: user=admin, access=WRITE;    container supergroup:drwxr-xr-x.

What's the problem? How to solve it?

**Comment by fanyangCS** [comment]
since the master contains critical Hadoop component (like HDFS name node), removing master node without backing up data will result in loss of HDFS metadata. Hadoop community should have enough discussion for the details.

**Comment by visaki** [comment]
@fanyangCS Thank you very much. Very useful. So one possible solution is to reset all compute nodes?

**Comment by fanyangCS** [comment]
If you don't mind losing all the data, resetting should work.
