### ISSUE TITLE
question about Nvidia driver

### ISSUE THREAD

**Issue by Wnaner** [microsoft/pai#3752]
It seems that I have successfully deployed the OpenPAI, the kubernetes show that the nvidia driver is deploy in the master and worker, and I can see the information by /var/drivers/nvidia/384.111/bin/nvidia-smi, when I run nvidia-smi, it shows commond not found, I must use the absolute path /var/drivers/nvidia/384.111/bin/nvidia-smi. Is it normal ?

And when I try to submit hello world job to examine the openpai,I cannot see the GPU utils and GPU Memory in the dashboard of openpai，but the job is actully running, and there also aren't  ssh info 、stdout and stderr.

**Organization Name**:

**Short summary about the issue/question**:

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by wunaner** [comment]
![图片](https://user-images.githubusercontent.com/44542468/67072016-95bc5380-f1b6-11e9-8515-7850463d5a33.png)

**Comment by wunaner** [comment]
I find there is a change, does this mean we need to install nvidia driver on all the node(master and worker) by ourself?
Remove drivers service in k8s cluster deployment
https://github.com/microsoft/pai/pull/3648

**Comment by fanyangCS** [comment]
in the future, we will allow you to use third party tool like AKS or Kubespray to install driver.

**Comment by wunaner** [comment]
> 
> 
> in the future, we will allow you to use third party tool like AKS or Kubespray to install driver.

I still need to deploy openpai in Ubuntu without nvidia driver installed berfore ,and openpai will install nvidia-driver in docker , right? Thank you .
