### ISSUE TITLE
lazy load of monaco editor

### ISSUE THREAD

**Issue by debuggy** [microsoft/pai#3755]
repro steps:
  1. In job list select an arbitrary job.
  2. Click on it and the job detail page opens slowly.
  3. Click job config, a monaco editor opens quickly because the monaco editor preloads when opening this page.

Solution:
  1. Lazy load monaco editor because it has a size of serveral MBs

**Comment by abuccts** [comment]
ref:
https://github.com/microsoft/pai/blob/834109832de98fe2fe33c5cf25d62d42fd44ca36/contrib/submit-job-v2/src/App/ProtocolForm.tsx#L33
https://github.com/microsoft/pai/blob/834109832de98fe2fe33c5cf25d62d42fd44ca36/contrib/submit-job-v2/src/App/ProtocolForm.tsx#L279-L289
