### ISSUE TITLE
kubelet启动调用的docker镜像问题

### ISSUE THREAD

**Issue by HistoryGift** [microsoft/pai#3759]
当启动keuelet时，openpai-kubelet调用的镜像，我这边无法正常pull下来，docker search搜索出来的多数是个人的镜像，不确定是否安全，能否提供一下国内官方推荐的镜像地址？

**Comment by ydye** [comment]
hyperkube: https://hub.docker.com/r/openpai/hyperkube/tags
kube-controller-manager: https://hub.docker.com/r/openpai/kube-controller-manager/tags
kube-scheduler：https://hub.docker.com/r/openpai/kube-scheduler/tags
kube-apiserver : https://hub.docker.com/r/openpai/kube-apiserver/tags
dashboard: https://hub.docker.com/r/openpai/kubernetes-dashboard-amd64/tags
etcd: https://hub.docker.com/r/openpai/etcd/tags
pause-amd64: https://hub.docker.com/r/openpai/pause-amd64/tags

**Comment by ydye** [comment]
@HistoryGift It's our project's repo on dockerhub, and the image is from google. You could pull image from it.
