### ISSUE TITLE
openPAI 0.14 version Job debug log is not as sufficient as 0.11

### ISSUE THREAD

**Issue by zhaojizhuang4** [microsoft/pai#3769]
**Organization Name**:

**Short summary about the issue/question**: In openPAI v0.11 when user 's script execute error ,the log is very sufficient including PAI env and std output ,but in openPAI v0.14, PAI env is not printed in log output and can not find the root err info
 
**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**: 0.14.
- OpenPAI version:
- Cloud provider or hardware configuration:5118
- OS (e.g. from /etc/os-release):ubuntu16.04
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):TESLA P100 * 16
- Others:

**Anything else we need to know**:
thanks a lot best regards!

**Comment by Binyang2014** [comment]
Hi @zhaojizhuang4 
In version 0.14. We separate the PAI runtime log with the user log.
PAI env will print in PAI runtime log. 
![image](https://user-images.githubusercontent.com/9415966/67487726-0674db80-f6a1-11e9-8941-814d6d05772c.png)
You can click go to yarn tracking page. And check the these logs.

**Comment by zhaojizhuang4** [comment]
hi @Binyang2014   thanks a lot !
