### ISSUE TITLE
Normal user should see memory/CPU consumption of the VC

### ISSUE THREAD

**Issue by Binyang2014** [microsoft/pai#3772]
**What would you like to be added**:
Show mem/CPU consumption of the VC which he/she can use for normal user.
**Why is this needed**:
User should know the whole resource usage about the VC. Not just GPU usage
**Components that may involve changes**:
Webportal

**Possible UX design**
Just like admin page, but user can only see the VCs he/she can use.
![image](https://user-images.githubusercontent.com/9415966/67545402-85165b00-f72b-11e9-8891-4a50bcf5b522.png)

**Comment by Binyang2014** [comment]
@scarlett2018 Any comments about this feature or UX design?

**Comment by yangou1988** [comment]
@Binyang2014 Let's add the utilization and detail (Memory, CPU, GPU)  to the normal user's VC. and hide the button: view all and column: action.

**Comment by Binyang2014** [comment]
@scarlett2018 @fanyangCS @yangou1988 PR: #3784 will add this feature. But previous home page will show if VC is dedicated for normal user, and display different colors: https://github.com/microsoft/pai/blob/2f060ca59da85672238ccb897f6b35943713b135/src/webportal/src/app/home/home/virtual-cluster-list.jsx#L60 After this change, such info will missing. Do we need to keep this info?

**Comment by scarlett2018** [comment]
@Binyang2014 - any visual example? compare the 2 effects..

**Comment by Binyang2014** [comment]
![image](https://user-images.githubusercontent.com/9415966/67847753-58ed4680-fb3e-11e9-9bcd-2ff06cd8cb55.png)
Just like this
