### ISSUE TITLE
my pods disappered

### ISSUE THREAD

**Issue by dq116** [microsoft/pai#3775]
To redeploy the openpai,I tried the this 

`python paictl.py service delete`

then I got this

![2019-10-13 21-27-42屏幕截图](https://user-images.githubusercontent.com/48147194/67634603-34545d00-f8f9-11e9-95fa-aaeb8e66ff24.png)

but I didn't put in the right cluster id 
![delete](https://user-images.githubusercontent.com/48147194/67634663-ec820580-f8f9-11e9-9b88-f75b12e64e9f.png)

Because I put in the wrong id ,I thought the 'delete' wouldn’t  begin.
But when I logged in  my k8s dashboard , I found my pods disappeared (the 'watchdog' in the photo was newly downloaded)(and the photo was shot fortnight ago)

![2019-10-13 21-49-05屏幕截图](https://user-images.githubusercontent.com/48147194/67634930-792dc300-f8fc-11e9-8672-301a1a3acd8d.png)

Does the disappered pods are deleted by myself？

**Comment by scarlett2018** [comment]
@dq116 - would you mind provide more information for us to understand the context? thanks.


Organization Name:

Short summary about the issue/question:

Brief what process you are following:

How to reproduce it:

OpenPAI Environment:

OpenPAI version:
Cloud provider or hardware configuration:
OS (e.g. from /etc/os-release):
Kernel (e.g. uname -a):
Hardware (e.g. core number, memory size, storage size, GPU type etc.):
Others:
Anything else we need to know:

**Comment by fanyangCS** [comment]
closed as no further response.
