### ISSUE TITLE
Taskrole close button has bug

### ISSUE THREAD

**Issue by debuggy** [microsoft/pai#3778]
![image](https://user-images.githubusercontent.com/8444268/67738129-8fe13080-fa48-11e9-9a49-d4d663fec21b.png)

Repro Steps:
1. In distributed submit job page, add 2 new task roles.
2. close the task role on the left, the tab could not be deleted correctly.

**Comment by sunqinzheng** [comment]
I can not reproduce this bug. Maybe it has been fixed
