### ISSUE TITLE
taskRetryCount is not passed to backend successfully

### ISSUE THREAD

**Issue by debuggy** [microsoft/pai#3781]
When submitting job with ```taskRetryCount: 3```, the task role could not successfully retried 3 times because the backend received config with ```taskRetryCount: 0```.

**Comment by abuccts** [comment]
The single task retry is meaningless in gang scheduling jobs, not sure how to set it in gang allocation yet.

For elastic jobs, the retry count could be used after enabling `fancyRetryPolicy`.

**Comment by yqwang-ms** [comment]
@abuccts For elastic jobs, can we make maxretrycount does not depend on fancyRetryPolicy? So, elastic jobs can disable task fancyRetryPolicy but set non-zero retry count.

**Comment by abuccts** [comment]
Currently, `fancyRetryPolicy` is set by us and is not exposed to user.
For gang allocation, task level `fancyRetryPolicy=false`, otherwise, `fancyRetryPolicy=true`.
