### ISSUE TITLE
job retry history design

### ISSUE THREAD

**Issue by debuggy** [microsoft/pai#3788]
## Webportal

- Make job retry number as a link in job detail page.

![image](https://user-images.githubusercontent.com/8444268/67835224-63024b80-fb24-11e9-87b3-c2a8d3072dd1.png)

- When click the link, redirect to a new page with a job retry grid.

- Link each item to a detail page of attempts.

### `Job retry history health check`

Get the health status of job retry history endpoint

*Request*

```json
GET /api/v2/jobs/:frameworkName/jobRetries/healthz
```

*Response if succeeded*

```json
Status: 200
ok
```

*Response job history endpoint does not work*

```json
Status: 404
Not found
```
### `List job retries by job UUID`

List all job retry histories by job ID

*Request*

```json
GET /api/v2/jobs/:frameworkName/jobRetries
```

*Response if succeeded*

```json
Status: 200
{
  [<jobRetry schema>]
}
```

*Response if the job id is not found*

```json
Status: 404
The job ID is not found
```

Response if a server error occurred

Status: 500

{
  "code": "UnknownError",
  "message": "*Upstream error messages*"
}

### `Get specified job retry by retry index`

Get specified job retry by retry index

*Request*

```json
GET /api/v2/jobs/:frameworkName/jobRetries/:jobRetryIndex
```

*Response if succeeded*

```json
Status: 200
{
  <jobRetry schema>
}
```

*Response if the job retry is not found*

```json
Status: 404
The job retry is not found
```

Response if a server error occurred

Status: 500

{
  "code": "UnknownError",
  "message": "*Upstream error messages*"
}

**Comment by yqwang-ms** [comment]
Thanks @debuggy for the design.
Some questions:

0. Can you explain more on "a new page with a job retry grid" and " a detail page of attempts"? 
A snapshot will be great.
For the job retry grid, we would better show some summarized failure msg on each retry, so user does not need to click into detail page.
It would be better that, we can count each failure types on the grid page, such as user failure: 7, unknown failure 2, OOM failures: 5, etc.

1. Do we really need the API "Job retry history health check"?
Can we just check this by using PAI feature gate: job-history=true?

2. For API "List job retries by job UID", pls also adjust the url to be:
`GET /api/v2/jobs/:frameworkUID/jobRetries`
`GET /api/v2/jobs/:frameworkName/jobRetries/:jobRetryIndex
`
`GET /api/v2/jobs/:frameworkName/jobRetries/healthz
`

**Comment by yqwang-ms** [comment]
And Retry number is tooo small and user does not aware click it can go to retry history. Why not also add a link like "view job config"
![image](https://user-images.githubusercontent.com/32826762/67935925-c57f4880-fc05-11e9-8710-5e2c6b8e4b10.png)
