### ISSUE TITLE
consult the setting of IP in service-deployment

### ISSUE THREAD

**Issue by gxfun** [Microsoft/pai#379]
Thanks

I am a beginner on kubernetes. There has some confusion about the ip settings in service-deployment.
``` python
rest_server_uri: http://10.0.3.9:9186
    # root url of the k8s apiserver
    k8s_api_server_uri: http://10.0.3.9:8080
    # root url of the webhdfs api server
    webhdfs_uri: http://10.0.3.9:50070
    # root url of the prometheus server
    prometheus_uri: http://10.0.1.9:9090
    # root url of the k8s dashboard
    k8s_dashboard_uri: http://10.0.3.9:9090
    # root url of grafana
    grafana_uri: http://10.0.1.9:3000
    # root url of the web portal
    webportal_uri: http://10.0.3.9:9286
```

I know 10.0.3.9 is the ip of master. but 10.0.1.9 ？
Another question , how many machines are needed in our pai at least?  Dose the master node not run specific work with gpu?

**Comment by ydye** [comment]
For the question about the number of machines: You should have at least 1 infra node to run the master service (Include kubernetes master component) and at least 1 worker node to run worker service. (Not you should correctly configure hdfs's replica according to your cluster size). 

For the address 10.0.1.9  is a issue. @YanjieGao  could you solve it? And please pay attention to the port of prometheus, it conflicts with k8s-dashboard.

**Comment by YanjieGao** [comment]
I will refine prometheus's host and ip and submit a PR for this

**Comment by YanjieGao** [comment]
Please see #380

**Comment by gxfun** [comment]
@YanjieGao 
Thanks!
