### ISSUE TITLE
刚部署好服务器，使用vscode上传代码遇到permission denied问题。

### ISSUE THREAD

**Issue by siaimes** [microsoft/pai#3816]
**Organization Name**:

**Short summary about the issue/question**:
刚部署好服务器，使用vscode上传代码遇到permission denied问题。

**Brief what process you are following**:
1. 按doc配置好服务器；
2. 安装vscode插件；
3. 打开HDFS EXPLORER；
4. 上传文件到pai_data；
5. 失败：permission denied。

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by scarlett2018** [comment]
@siaimes - what's the OpenPAI version are you using? what's the VSCode client version you are using?

**Comment by siaimes** [comment]
@scarlett2018 Thank you for your reply. My OpenPAI version is v0.14.0 and the version of VScode client is 0.2.1.

**Comment by yiyione** [comment]
I think user don't have permission to access `pai_data` folder by default, can you create a new folder **outside** the `pai_data` folder and try to upload the file ?

**Comment by siaimes** [comment]
@yiyione Your right. Thank you. Bug, when I am doing this, I found that the server can be accessed by someone who does not log in from link like this `182.168.1.2:50070/explorer.html`. From this link, one can upload, download, and delete all the files of the server. Maybe this is a leak?

**Comment by yiyione** [comment]
@siaimes I think it's a known issue in OpenPAI.
我不是很确定这个问题会不会被修，因为之后的版本中，PAI可能不再自带一个HDFS，大概去掉HDFS也算是解决了这个问题？

**Comment by fanyangCS** [comment]
@siaimes , if you need a secure storage solution, you will have to deploy it on your own.  OpenPAI can leverage external storage solution: a job can mount to an external storage service from within a job's docker container

**Comment by siaimes** [comment]
@yiyione @fanyangCS Thank you for your replay.

**Comment by siaimes** [comment]
> @siaimes I think it's a known issue in OpenPAI.
> 我不是很确定这个问题会不会被修，因为之后的版本中，PAI可能不再自带一个HDFS，大概去掉HDFS也算是解决了这个问题？

所以现在的版本我需要如何解决这个问题呢？
