### ISSUE TITLE
Stop Job will first make Task become running then stopped

### ISSUE THREAD

**Issue by yqwang-ms** [microsoft/pai#3818]
**Organization Name**:

**Short summary about the issue/question**:
Stop Job will first make Task become running then stopped.

The running maybe caused by Task does not have Stopping state, so backend completing state is translated to running.
We would better add a Stopping state for Task, and completing state should not change orignal stopping state.

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by sunqinzheng** [comment]
I think the current display is more straightforward. The job is stopping but some task is not stopped yet. And the user could find out which task is still stucked.

I think a better solution is that launcher could provide a per-task stopping state instead of a fake state guessed by web portal

**Comment by yqwang-ms** [comment]
It is not fake, because if launcher is down, it does not have chance to update the state to be stopping, but the execution type can be modified to be stopped by restserver. So only restserver know it is stopping by check the execution type from APIServer.

**Comment by yqwang-ms** [comment]
Note both launcher and restserver are clients of APIServer. restserver is not directly a client of launcher.

**Comment by yqwang-ms** [comment]
![image](https://user-images.githubusercontent.com/32826762/69039808-9f401200-0a27-11ea-9e04-8b9e14acd1b4.png)
So, let's treat the task as **Stopping** if and only if state==AttemptDeleting and exitCode === -220
