### ISSUE TITLE
P1 - Job config is modified after it is imported/uploaded/cloned

### ISSUE THREAD

**Issue by yqwang-ms** [microsoft/pai#3823]
**Organization Name**:

**Short summary about the issue/question**:

Import from Submit Job page:
Left original, right after import
![image](https://user-images.githubusercontent.com/32826762/68640353-6e04a500-0542-11ea-9450-298de5a20fbd.png)

Import from Submit Job by plugin page:
Left original, right after import
![image](https://user-images.githubusercontent.com/32826762/68640346-6b09b480-0542-11ea-88cd-ae39c50d9cf6.png)

User will confuse why **just import/upload/clone** will change his job config, and concerns if it can also **reproduce** this job anymore.
Suggest:
1. The **defaulting** should only be done after **submission phase.** 
2. And we **should not change** user already specified values **in any phase.**

We should always pay attention to our **reproducibility**.

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by yqwang-ms** [comment]
temp workaround: using sdk or cli to submit raw job config yaml

**Comment by Binyang2014** [comment]
After #4016 is merged, we will keep the Yaml contents are equivalent. But may change the order of config sentences.
As discussed, it's acceptable.  Close this issue.

**Comment by yqwang-ms** [comment]
Acceptable in current does not mean we totally solved this. Defaulting should not be done at this phase.

**Comment by fanyangCS** [comment]
we need a better yaml editor

**Comment by scarlett2018** [comment]
- [ ] The defaulting should only be done after submission phase.
the current validation updated the fields that is empty with default values, should not change users original form.
- [X] And we should not change user already specified values in any phase.
