### ISSUE TITLE
vCPU数量的申请限制[Feedback v0.15.0]

### ISSUE THREAD

**Issue by fmxFranky** [microsoft/pai#3825]
PAI里面的job中申请cpu数量的单位是逻辑核心，但是在我的机器上目前没有办法申请到所有逻辑核心，存在最大数量的限制

我这边集群的机器均为96物理核心，但是我提交任务的时候最多只能申请96个逻辑核心，不知道如何取消这个限制

ps运维人员的调试结果：

> hadoop里有192 vcpu，但是最多一次分配96.        
layout.yaml里虽然设置的是96而不是192，但是据说没关系       
hadoop-resource-manager-configuration/yarn-site.xml.template里把vcore最大值从96设置为192，并重新部署hadoop-resource-manager，但是并没什么用

**Comment by abuccts** [comment]
Could you explain your cluster's configuration more clearly, do you mean the cluster has 2 worker nodes, each node has 96 vcores?

The maximum vcores you could request in one task is `min(yarn.scheduler.maximum-allocation-vcores, #vcores in one node)`.
So in the above case, you could only request 96 vcores in one task. If you want192 vcores, you need to request 2 tasks, each task will get 96 vcores.

**Comment by visaki** [comment]
@abuccts I can explain. 

Each work node has 96 physical cpus and 192 logical cpus. Therefore, although I set vcpu at 96 in layout.yaml, it was automatically adjusted to 192 in hadoop.

However, when the user tried to apply for 192 vcpus, it was prompted that 96 vcpus could be applied at most. 

After changing  the value 96(yarn.scheduler.maximum-allocation-vcores) to 192 , redepoly hadoop-resource-manager, still prompt can only apply 96.

How to solve it?Notice that the vcpu in layout.yaml is still 96.

**Comment by abuccts** [comment]
Here're the steps:
1. change `yarn.scheduler.maximum-allocation-vcores` in `yarn-site.xml.template` file https://github.com/microsoft/pai/blob/72c034868aa06798440b37e83a1a887476006df8/src/hadoop-resource-manager/deploy/hadoop-resource-manager-configuration/yarn-site.xml.template#L349
2. `python paictl service stop -n hadoop-resource-manager`
3. `python paictl service start -n hadoop-resource-manager`

If you followed the above steps but it didn't work, please check whether the value changed in k8s configmap at `http://k8s-dashboard-address/#!/configmap/default/hadoop-resource-manager-configuration?namespace=default`.

**Comment by mzmssg** [comment]
@visaki 
Could you confirm the lastest setting at `{master_ip}:8088/conf`?

**Comment by visaki** [comment]
@mzmssg @abuccts 
I've done these three steps before asking this question, but I've just done them again

But still request more than 96vcpu will report an error

The {master_ip}:8088/conf:
<name>yarn.scheduler.maximum-allocation-vcores</name>
<value>192</value>
<final>false</final>
<source>yarn-site.xml</source>

I remember my hadoop-run:v0.15.0 mirror was copied directly from v0.14.0
Could it have something to do with that?

**Comment by abuccts** [comment]
could you paste or capture the detailed error message?

**Comment by visaki** [comment]
Exit Code:              -7200
Exit Type:               USER_FAILURE
Exit Reason:           Launcher AM failed to heartbeat with YARN RM due to YarnException, maybe App is non-compliant 
                              Invalid resource request, requested virtual cores < 0, or requested virtual cores > max configured, requestedVirtualCores=100, maxVirtualCores=96
Exit Solutions:        Check diagnostics and revise your job config

@abuccts 
The task will fail if it has just been submitted and has not been assigned to the work node

**Comment by abuccts** [comment]
The re-configuration in `yarn-site.xml.template` should work.

1. Could you check the output of `cat /proc/cpuinfo | grep "processor" | wc -l` on your worker nodes? It should be `192` for your case.

2. If the output number is right, try to stop then start **all** pai services:
    ```sh
    python paictl.py service stop
    python paictl.py service start
    ```

**Comment by mzmssg** [comment]
I get it.
@visaki
The reason is hadoop has persisted these configuration into zookeeper, so updating the file doesn't help. The quickest fix is redeploy zookeeper.
```
python paictl.py service delete -n zookeeper
python paictl.py service start -n zookeeper
```
**Noticed it would permanently delete previous jobs and vc configuration!**

**Comment by visaki** [comment]
@mzmssg @abuccts 
Problem solved

Step 1：use the method of mzmssg, which cannot be allocated normally after completion

Step 2：use the method of abuccts

These two steps must be executed one after the other
