### ISSUE TITLE
Confusing exception if FC has not create the status field

### ISSUE THREAD

**Issue by yqwang-ms** [microsoft/pai#3828]
**Organization Name**:

**Short summary about the issue/question**:
Confusing exception in job detail page (after submission) if FC has not create the status field.
![image](https://user-images.githubusercontent.com/32826762/68656291-7eca1080-056c-11ea-9050-52d85e1a1f8d.png)
This may happen if FC is very busy, or down or during upgrade.
So, RestServer should not assume the framework.status field is always not nil.
Instead, like YARN, it should mock a waiting status of the framework.

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by abuccts** [comment]
Fixed in #3876.
