### ISSUE TITLE
consult some question when bootstraping service 

### ISSUE THREAD

**Issue by gxfun** [Microsoft/pai#385]

**Comment by gxfun** [comment]
Hi

Firstly, when executing the script `./deploy.py -d -p /cluster-configuration/clusterconfig-service.yaml `, there exists two errors: 
     `1  Error from server (BadRequest): error when creating "rest-server.yaml": DaemonSet in version "v1beta1" cannot be handled as a DaemonSet: [pos 587]: json: expect char '"' but got char '1' `
     `2 error: 'prometheus' already has a value (true), and --overwrite is false`
  [the details of log in this](https://github.com/gxfun/Dockerfile/blob/master/configuration/details_of_deploy_service.yaml) 
   But sometimes there is no second error.

Second, I noticed that the tag of  image `( prom/node-exporter)` is not marked in [line 34](https://github.com/Microsoft/pai/blob/master/service-deployment/bootstrap/prometheus/node-exporter-ds.yaml.template), so the status of pods `( node-exporter-nsk5g)` is `ErrImagePull` , although there exists the image of each version on my machine.
    [the details of executing this command `kubectl describe pods node-exporter-nsk5g`](https://github.com/gxfun/Dockerfile/blob/master/configuration/details_of_node-exporter.yaml)
  I also tried to add tag for the image in `service-deployment/bootstrap/prometheus/node-exporter-ds.yaml`, but it didn't work.

Besides , there may be a bug: when I use `ctrl+c ` to interrupt this script `./deploy.py -d -p /cluster-configuration/clusterconfig-service.yaml `, the terminal still outputs `***** is not ready yet. Pleas wait for a moment!`

Thanks!

**Comment by xwzheng1020** [comment]
maybe you can try to add "imagePullPolicy: IfNotPresent" to service-deployment/bootstrap/prometheus/node-exporter-ds.yaml

**Comment by ydye** [comment]
@YanjieGao

**Comment by gxfun** [comment]
@xwzheng1020 @ydye 
Thanks!

I solve the second problem by assigning the specific tag (v0.15.2 other than latest ) in [line 34](https://github.com/Microsoft/pai/blob/master/service-deployment/bootstrap/prometheus/node-exporter-ds.yaml.template).
Then, the status of pods `(pylon-ds-c30xt)` is `ContainerCreating`.
[the details of executing this command `kubectl describe pods pylon-ds-c30xt`](https://github.com/gxfun/Dockerfile/blob/master/configuration/details_of_pylon.yaml)
Is this situation normal? Or how to solve thisproblem?

**Comment by YanjieGao** [comment]
fix error: 'prometheus' already has a value (true), and --overwrite is false
#386

**Comment by ydye** [comment]
@gxfun Can you check the Log of kubelet on the machine which be scheduled with pylon?

With the command ```docker log```

**Comment by gxfun** [comment]
@ydye
Thanks!

[the details of executing `docker logs kubelet`](https://github.com/gxfun/Dockerfile/blob/master/configuration/details_of_kubelet.yaml)

**Comment by ydye** [comment]
@gxfun Have you tried to restart this service? By the script clean.sh and start.sh in ```bootstrap/pylon```

**Comment by YanjieGao** [comment]
let's use fixed node-exporter version tag #389

**Comment by gxfun** [comment]
@ydye 
Hi，

I solve the problem of  `pylon` by modifying the port in [line 139](https://github.com/Microsoft/pai/blob/master/service-deployment/clusterconfig-example.yaml), beasuse the port of 80 are often occupied by `apache`.

Thanks!

**Comment by ydye** [comment]
Issue has been solved. Closed this issue.

**Comment by gxfun** [comment]
@ydye 
Hi， there also has another issue `Error from server (BadRequest): error when creating "rest-server.yaml": DaemonSet in version "v1beta1" cannot be handled as a DaemonSet: [pos 587]: json: expect char '"' but got char '1' `. Now, it doesn't exist pod of  `rest_server` with command `kubectl get pods `. I this is a important problem, but I can't solve it.

**Comment by ydye** [comment]
@gxfun Can you paste tje rest-server.yaml after generated?

**Comment by gxfun** [comment]
@ydye 
[the details of rest-server.yaml](https://github.com/gxfun/Dockerfile/blob/master/configuration/details_of%20_rest.yaml)

Thanks!

**Comment by ydye** [comment]
@gxfun

```
 - name: LOWDB_PASSWD
    value: 123456
```


to

```
 - name: LOWDB_PASSWD
    value: "123456"
```

The value shouldn't be a number. If the string only contain digits, please add quotation.

**Comment by ydye** [comment]
#393

**Comment by gxfun** [comment]
@ydye
Thanks, Everything is working fine now。
Beside，is NTP service necessary?

**Comment by ydye** [comment]
@gxfun 
Suggest to setup NTP service on your infra node. Because too serious time drift will cause etcd cluster unstable.

**Comment by fanyangCS** [comment]
NTP is required, as stated in https://github.com/Microsoft/pai#prerequisite
