### ISSUE TITLE
How to expose the webportal in the public network？

### ISSUE THREAD

**Issue by zhanlinfeng** [microsoft/pai#3855]
**Short summary about the issue/question**:I try to access Webportal through public address，I got the login page，but I can't sign in because login request points to intranet address。

**Brief what process you are following**:I edit configuriton，The following configuration has been added：
```
cluster:
  common:
    getway-uri: "http://public-address"
```
and restart pai，but it doesn't work。What should I do?
By the way, dev-box version is 0.13.0

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:v0.14.0
- Cloud provider or hardware configuration:a master without GPU and a worker with GPU k80
- OS (e.g. from /etc/os-release):ubuntu 16.04
- Kernel (e.g. `uname -a`):4.4.0-1096-aws
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by abuccts** [comment]
We didn't support such a config.
Please visit webportal through [pylon](https://github.com/Microsoft/pai/blob/master/docs/pylon/README.md).

**Comment by zhanlinfeng** [comment]
> We didn't support such a config.
> Please visit webportal through [pylon](https://github.com/Microsoft/pai/blob/master/docs/pylon/README.md).
Sorry about that，I'm a green hand.

**Comment by zhanlinfeng** [comment]
Sorry about that，I'm a green hand.

**Comment by scarlett2018** [comment]
> Sorry about that，I'm a green hand.

no worries, please try what pylon.
