### ISSUE TITLE
efficiency low

### ISSUE THREAD

**Issue by xxxt** [microsoft/pai#3860]
**Organization Name**:westlake

**Short summary about the issue/question**: efficiency low

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**: v0.14.0
- OpenPAI version:v0.14.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):ubuntu 16.04.6
- Kernel (e.g. `uname -a`):4.14.145
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):mem:512GB,CPU:Gold 6144,1T NVME SSD,V100 SXM2 *8
- Others:

**Anything else we need to know**:
openpai is 6% slower than Anaconda
nvidia-docker is 1.5% slower than Anaconda

**Comment by scarlett2018** [comment]
@xxxt - can you share the performance test scripts? how you calculated the 6% and 1.5%.

**Comment by fanyangCS** [comment]
https://github.com/microsoft/pai/issues/3267 Related

**Comment by fanyangCS** [comment]
The single digit performance variation is often due to subtle differences in OS configuration like numa node, different kernel version etc. 

Please firstly make sure the software version (host and docker images) is the same for a fair comparison.

**Comment by xxxt** [comment]
It's the same as #3267 
Thanks！
