### ISSUE TITLE
WebUI Font Format Adjustment

### ISSUE THREAD

**Issue by yangou1988** [microsoft/pai#3877]
**What would you like to be added**:

Update the standard of font format & size.

![image](https://user-images.githubusercontent.com/44491713/70290891-67511100-1814-11ea-80de-d625a3dfca7a.png)

#1: 16px Segoe Regular
#2: 16px Segoe Bold
#3: 12px Segoe Regular
#4: 14px Segoe Semibold
#5: 16px Segoe Regular

**Comment by Binyang2014** [comment]
@debuggy @sunqinzheng please take a look when you have time
