### ISSUE TITLE
Is JOB randomly generated in a WORKER?

### ISSUE THREAD

**Issue by kkwang-001** [microsoft/pai#3894]
I have 2 WORKER with 8 GPU.I want to create 3 jobs.Job 1 and job 2 need 4 GPU,job 3 need 6 GPU.If job 1 is in WORKER 1 and job 2 is in WORKER 2,job 3 can not be created.But it is ok if job 1 and job2 is also in WORKER 1.
  So, what can i do to control which WORKER is the job specifically located.

  Thanks

**Comment by fanyangCS** [comment]
the scheduler will do such packing by default. If not, please wait for our 0.16.y release, which includes the HiveD scheduler that support node reservation. https://github.com/microsoft/pai/tree/master/subprojects/GOPATH/src/github.com/microsoft/hivedscheduler
