### ISSUE TITLE
[Feedback v0.14.0] python paictl.py service start fails on  to start prometheus service and rest-server  service 

### ISSUE THREAD

**Issue by apri30th** [microsoft/pai#3895]
when run  python paictl.py service start  ,it fails  on promethus service and rest-server service
![image](https://user-images.githubusercontent.com/4046214/69536332-c31bce80-0fb8-11ea-9954-3d578a35066c.png)

check the log   rest-server outputs Error: ENOENT: no such file or directory, open '/group-configuration/group.yaml'
 promthus  pod   output  container "prometheus" in pod "prometheus-deployment-6576b757c8-f95bk" is waiting to start: PodInitializing
when i  repeat  python paictl.py service stop  python paictl.py cluster k8s-clean -p ~/pai-config    
and reboot openpai via python paictl.py cluster k8s-bootup -p ~/pai-config . it still the same.

how could i to solve them ?

**OpenPAI Environment**: 
- OpenPAI version: v0.14.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): unbuntu16.04
- Kernel (e.g. `uname -a`): 4.4.0-131-generic
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
gpu type : titian v
nvidia driver : 384.111 

----- but i use  openpai v0.11.0  ,  i success to deploy it 。 how could i to solve them when i want to use new latest releasion?

**Comment by Binyang2014** [comment]
Can you try to run `python paictl.py service stop -n prometheus`,  `python paictl.py service start -n prometheus`. And check if it will solve the problem?
For rest-server, please check rest-server log

**Comment by apri30th** [comment]
> ase check rest-server log

when i already install it  when retry  thank you  for your reply
