### ISSUE TITLE
there is no v0.16.0 images on docker hub?

### ISSUE THREAD

**Issue by flybird08765** [microsoft/pai#3960]
**Organization Name**: Advantech

**Short summary about the issue/question**:

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:
I wanna deploy v0.16.0 on my local server, but there is no v0.16.0 docker image on docker hub. Is v0.16.0 the official release, Or a internal release? Thanks.

**Comment by hzy46** [comment]
It is an internal release. If you are interested you could build the images by yourselves. e.g.: 
```
./build/pai_build.py build -c <path-to-pai-config>
./build/pai_build.py push -c <path-to-pai-config>
```
