### ISSUE TITLE
hadoop-name-node-ds Back-off restarting failed container

### ISSUE THREAD

**Issue by diao1104** [microsoft/pai#3970]
[logs-from-hadoop-name-node-in-hadoop-name-node-ds-knj7h.txt](https://github.com/microsoft/pai/files/3925965/logs-from-hadoop-name-node-in-hadoop-name-node-ds-knj7h.txt)
![1](https://user-images.githubusercontent.com/44333273/70221741-dc283a80-1783-11ea-98b6-ee7c32c31ebf.PNG)

how to solve this problem

**Comment by ydye** [comment]
Can you paste the layout.yaml? And please remove the sensitive data such as password and public ip address.

**Comment by diao1104** [comment]
> 您可以粘贴layout.yaml吗？并且请删除敏感数据，例如密码和公共IP地址。

![捕获](https://user-images.githubusercontent.com/44333273/70227184-1fd37200-178d-11ea-9f8e-218f988683f0.PNG)

**Comment by ydye** [comment]
> > 您可以粘贴layout.yaml吗？并且请删除敏感数据，例如密码和公共IP地址。
> 
> ![捕获](https://user-images.githubusercontent.com/44333273/70227184-1fd37200-178d-11ea-9f8e-218f988683f0.PNG)

Please check that the hostname in the machinelist should be same with the output of the commond ``` echo `hostname` ```. Please check both worker and master.

**Comment by diao1104** [comment]
> > > 您可以粘贴layout.yaml吗？并且请删除敏感数据，例如密码和公共IP地址。
> > 
> > 
> > ![捕获](https://user-images.githubusercontent.com/44333273/70227184-1fd37200-178d-11ea-9f8e-218f988683f0.PNG)
> 
> 请检查计算机列表中的主机名是否应与commond的输出相同`` echo `hostname` ``。请同时检查工人和主人。

![捕获1](https://user-images.githubusercontent.com/44333273/70231395-367dc700-1795-11ea-8201-de39037975ee.PNG)

**Comment by diao1104** [comment]
> > > 您可以粘贴layout.yaml吗？并且请删除敏感数据，例如密码和公共IP地址。
> > 
> > 
> > ![捕获](https://user-images.githubusercontent.com/44333273/70227184-1fd37200-178d-11ea-9f8e-218f988683f0.PNG)
> 
> 请检查计算机列表中的主机名是否应与commond的输出相同`` echo `hostname` ``。请同时检查工人和主人。

![捕获1](https://user-images.githubusercontent.com/44333273/70231506-6927bf80-1795-11ea-9b8f-a7083a536e10.PNG)

**Comment by ydye** [comment]
@diao1104 Please login the hosts (master and node001). And paste the command output of the following commmand.
```
sudo cat /etc/hosts
```

**Comment by diao1104** [comment]
![捕获2](https://user-images.githubusercontent.com/44333273/70297639-e3098880-1829-11ea-91eb-a43d5e26856a.PNG)

**Comment by diao1104** [comment]
If I change the name of the master, it will appear zookeeper is not ready yet. Please wait for a moment!
![捕获3](https://user-images.githubusercontent.com/44333273/70298870-1fd77e80-182e-11ea-960d-9ef04506a55d.PNG)
