### ISSUE TITLE
Miss Worker Node in Cluster

### ISSUE THREAD

**Issue by xulzee** [microsoft/pai#3984]
**Organization Name**: Private Test

**Short summary about the issue/question**: I deployed a cluster with three nodes, including a master node and two GPU nodes, but only one node can be found in the dashboard after my deployment.

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:0.14.0
- OS (e.g. from /etc/os-release): ubuntu16.04
- Kernel (e.g. `uname -a`): Linux ubuntu 4.4.0-170-generic #199-Ubuntu SMP Thu Nov 14 01:45:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):this is my layout.yaml
machine-sku:                               
  master-node:                             
    mem: 64G                               
    gpu:                                   
      type: none                           
      count: 0                             
    cpu:                                   
      vcore: 28                            
    os: ubuntu16.04                        
  p100-node:                               
    mem: 64G                               
    gpu:                                   
      type: Tesla P100                     
      count: 2                             
    cpu:                                   
      vcore: 16                            
    os: ubuntu16.04                        
  gtx1080ti-2-node:                        
    mem: 64G                               
    gpu:                                   
      type: GTX1080Ti                      
      count: 2                             
    cpu:                                   
      vcore: 32                            
    os: ubuntu16.04                        
                                           
machine-list:                              
  - dashboard: "true"                      
    docker-data: "/var/lib/docker"         
    etcdid: "etcdid1"                      
    hostip: "192.168.1.106"                
    hostname: "ubuntu"                     
    k8s-role: "master"                     
    machine-type: "master-node"            
    nodename: "192.168.1.106"              
    pai-master: "true"                     
    password: "311311311"                  
    ssh-port: "22"                         
    username: "pai"                        
    zkid: "1"                              
                                           
  - docker-data: "/var/lib/docker"         
    hostip: "192.168.1.83"                 
    hostname: "test-PowerEdge-R730"        
    k8s-role: "worker"                     
    machine-type: "p100-node"              
    nodename: "192.168.1.83"               
    pai-worker: "true"                     
    password: "311311311"                  
    ssh-port: "22"                         
    username: "pai"                        
                                           
  - docker-data: "/var/lib/docker"         
    hostip: "192.168.1.94"                 
    hostname: "GTX1080-2"                  
    k8s-role: "worker"                     
    machine-type: "gtx1080ti-2-node"       
    nodename: "192.168.1.94"
    pai-worker: "true"
    password: "311311311"
    ssh-port: "22"
    username: "pai"
- Others:

**Anything else we need to know**:Is this because the hardware of my P100 node can not meet the requirements?
Thank you very much for any help.

**Comment by xulzee** [comment]
Dashboard:
![image](https://user-images.githubusercontent.com/29273676/70376374-6d91db00-1943-11ea-91dd-b6446f9745bd.png)

Hardware:
![image](https://user-images.githubusercontent.com/29273676/70376382-7e425100-1943-11ea-842b-f530c1be26c0.png)

**Comment by xulzee** [comment]
The missing node(p100-node):
![image](https://user-images.githubusercontent.com/29273676/70376572-08d78000-1945-11ea-98d7-bdc2feff48d9.png)


gtx1080ti-2-node:
![image](https://user-images.githubusercontent.com/29273676/70376576-0f65f780-1945-11ea-804b-37743eb46f21.png)

**Comment by Binyang2014** [comment]
Please check yarn API:` http://master_ip:8088/ws/v1/cluster/nodes`. If your node not in RUNNING or DECOMMISSIONING states, we will treat it as not ready.

**Comment by xulzee** [comment]
I have reinstalled the system of P100 node. Now there is no such problem. Thank you very much
