### ISSUE TITLE
How to get all the containers by k8s

### ISSUE THREAD

**Issue by edenbuaa** [microsoft/pai#3994]
**OpenPAI Environment**:
- OpenPAI version: v0.14.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): ubuntu16.04
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

Is there a way to get all the running containers of jobs by k8s command or other interface? thanks.

**Comment by abuccts** [comment]
```sh
$ kubectl get pods --selector='type=kube-launcher-task'
```

or you can `GET apiserver/api/v1/pods?labelSelector=type=kube-launcher-task`

**Comment by edenbuaa** [comment]
@abuccts  thanks.  these instructions seems not work:
![image](https://user-images.githubusercontent.com/16248697/70487615-e013de00-1b30-11ea-8657-0cc6c736f9fd.png)

**Comment by abuccts** [comment]
Sorry, if you're using YARN version, all job containers are run through local Docker daemon instead of kubelet, there's no such an interface in k8s to list. The above only works for pure k8s version.

**Comment by edenbuaa** [comment]
Got it. Did the k8s version release?

**Comment by abuccts** [comment]
It's [v0.16.0](https://github.com/microsoft/pai/tree/v0.16.0), images haven't been released, but you can build images by yourself.

You will need to change the following line to `cluster-type: k8s` to use pure k8s version.
https://github.com/microsoft/pai/blob/141301d4ad637cbe0fff41e40e60bf7bf2797900/examples/cluster-configuration/services-configuration.yaml#L23

**Comment by edenbuaa** [comment]
all right. thanks.
