### ISSUE TITLE
how to make capacity-scheduler.xml take affect

### ISSUE THREAD

**Issue by feng257** [microsoft/pai#3995]
**Short summary about the issue/question**:
I changed the capacity-scheduler.xml as follow, but no matter I refresh or start after deleted , it does not take affect:
![image](https://user-images.githubusercontent.com/16338017/70436784-0ef46a80-1ac5-11ea-8e67-64de18c86462.png)

so, am I missing something to configure?  Thx for any reply.

**OpenPAI Environment**:
- OpenPAI version:  **0.14**
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): **ubuntu 16.04 server**
- Kernel (e.g. `uname -a`): **Linux  4.4.0-116-generic**
- Hardware (e.g. core number, memory size, storage size, GPU type etc.): 
- Others:

**Comment by mzmssg** [comment]
Firstly, capacity-scheduler.xml is generated from template, so any change on it is meaningless.

Then, PAI doesn't expose and fully test these configurations. If you really want to customize them, please try [YARN API](https://hadoop.apache.org/docs/r2.9.0/hadoop-yarn/hadoop-yarn-site/ResourceManagerRest.html#Scheduler_Configuration_Mutation_API), which should be at `http://master_ip:8088/ws/v1/cluster/scheduler-conf`.

**Comment by feng257** [comment]
thanks, I sloved it by calling YARN API.
