### ISSUE TITLE
How to set up the drivers-one-shot service without re-install the nvidia driver ?

### ISSUE THREAD

**Issue by DeepDarkOdyssey** [microsoft/pai#3998]
Coming from [issue #2198](https://github.com/Microsoft/pai/issues/2198)
The situation is:
I'm setting up a single-box deployment on a gpu-server, after setting up the k8s stuff, I'm trying to start the PAI service on it. While the machine I'm using has already got the nvidia driver installed in `/usr/lib/nvidia-418`:
![image](https://user-images.githubusercontent.com/37280638/70500226-fb451480-1b55-11ea-8856-6e17abbb99dd.png)
And I customized the `services-configuration.yaml`  following the [guide](https://github.com/microsoft/pai/blob/master/src/drivers/config/drivers.md):
![image](https://user-images.githubusercontent.com/37280638/70501505-2e3cd780-1b59-11ea-8986-7935a342408e.png)
However when I start the pai service,  the drivers-one-shot pod keeps crashing and restarting, because the driver is already installed and still being used, here's the log:
![image](https://user-images.githubusercontent.com/37280638/70501197-6263c880-1b58-11ea-85c7-67c3bf9ef315.png)
![image](https://user-images.githubusercontent.com/37280638/70501061-08630300-1b58-11ea-974e-5f3a6672d451.png)
Have I missed anything?

**Comment by Binyang2014** [comment]
Can you follow these steps and try again? https://github.com/microsoft/pai/issues/666#issuecomment-395285939

**Comment by DeepDarkOdyssey** [comment]
Thanks @Binyang2014 , it works... Then what's the point of setting `drivers.pre-installed-nvidia-path` in `services-configuration.yaml` ?

**Comment by Binyang2014** [comment]
@ydye Do you know this setting `drivers.pre-installed-nvidia-path`?

**Comment by ydye** [comment]
https://github.com/microsoft/pai/blob/09c1bf1088b1c189f9b23c36272fec69aed54edc/src/drivers/build/install-all-drivers#L28

**Comment by ydye** [comment]
If the path ```/usr/local/nvidia``` contains ```nvidia-smi```, we will assume the driver is installed on hosts.

**Comment by scarlett2018** [comment]
closing the issue as the question has been addressed, feel free to reopen the issue if there are still other questions around the answer.
