### ISSUE TITLE
How to safely reboot entire cluster nodes?

### ISSUE THREAD

**Issue by s2100** [microsoft/pai#3999]
How to safely reboot entire cluster nodes?

After reboot, I found some of the pods launched with errors in the k8s dashboard. And it won't be fixed after waiting for a very long time.

**OpenPAI Environment**:
- OpenPAI version: v0.14.0

**Comment by Binyang2014** [comment]
@s2100  Can you give more specific information? What errors do you occur?

**Comment by s2100** [comment]
@Binyang2014 No errors met, but I want to shutdown them due some hardware maintenance.

**Comment by Binyang2014** [comment]
You can shutdown the node without any extra operations. After restart, k8s will help to start all pods.
If you meet some issues such as `/etc/hosts` is modified, or disk is broken, you need to fix it by yourself...

**Comment by s2100** [comment]
Gotcha, and thanks.
