### ISSUE TITLE
[Feedback v0.14.0] WebHDFS Permission Denied problem

### ISSUE THREAD

**Issue by xulzee** [microsoft/pai#4004]
**Organization Name**:

**Short summary about the issue/question**:
After I have deployed Pai, my admin user can submit tasks to run normally. But when I create a new user and log in with a new user name on another machine, I encounter "webhdfs permission denied problem" when submitting the task

![image](https://user-images.githubusercontent.com/29273676/70593258-4541ff00-1c17-11ea-8917-04652a9757cb.png)

When I visit the http://master/webhdfs web page, I find that only the root user has access to the file. Where did I not deploy correctly?

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:0.14.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):ubuntu16.04
- Kernel (e.g. `uname -a`): 4.4

**Comment by hzy46** [comment]
Hi xulzee, the default HDFS permission is rwxr-xr-x for `root`. Please use a `root` user to run `hdfs dfs -chmod 777 hdfs://<your-hdfs-namenode>:9000/` if you need to change the permission.

**Comment by jnitsch** [comment]
Just in case anyone else is still struggling with this issue. As @hzy46 mentioned you can fix the issue with changing file permissions, I just want to add a more detailed how-to for other users which also use the hdfs docker mentioned in [link](https://github.com/microsoft/pai/blob/master/docs/hadoop/hdfs.md#HDFS_Command)

1. `sudo docker run -it paiexample/pai.example.hdfs bash`
2. `hdfs dfs -chmod 777 hdfs://<your-hdfs-name-node>/Container`
3. `exit`

In case you encounter any other permission denied error you can change the permissions of the other folders as well (`hdfs dfs -ls hdfs://<your-hdfs-name-node>`).

**Comment by fanyangCS** [comment]
@jinitsch, thanks a lot for your information.

**Comment by zeyu-hello** [comment]
Hi, @hzy46 
What does `hdfs://<your-hdfs-name-node>` infer ? Is it the node **ip**?

**Comment by hzy46** [comment]
> Hi, @hzy46
> What does `hdfs://<your-hdfs-name-node>` infer ? Is it the node **ip**?

It will be your PAI master IP, if you do not change the configuration.

**Comment by zeyu-hello** [comment]
@hzy46 
I used this command: `hdfs dfs -chmod 777 hdfs://<your-hdfs-namenode>:9000/` in my admin user submitted job docker, then changed to a none-root user account, but still got same error in job submit page.

**Comment by hzy46** [comment]
> @hzy46
> I used this command: `hdfs dfs -chmod 777 hdfs://<your-hdfs-namenode>:9000/` in my admin user job docker, then changed to a none-root user account, but still got same error in job submit page.
> 
> Should I restart PAI service?

Restarting PAI Service may not help. Please double check your folder permission. For example: `hdfs dfs -ls hdfs://<your-hdfs-namenode>:9000/<the-folder-you-want-to-access>`

**Comment by zeyu-hello** [comment]
Problem solverd.

Thanks! @hzy46

**Comment by chuangxinyuan** [comment]
Works.  But should run the following command on devbox:
`hdfs dfs -chmod 777 hdfs://<your-hdfs-name-node>:9000/Container` 
dont forget the **port number**
