### ISSUE TITLE
job retry failed with unknown reason

### ISSUE THREAD

**Issue by debuggy** [microsoft/pai#4008]
![image](https://user-images.githubusercontent.com/8444268/70684321-caddb180-1ce0-11ea-9d06-944a6c9ac857.png)

**Comment by debuggy** [comment]
The detailed reason of this issue is that if there is no history data in elastic search (i.e. if no gc happens in framework launcher), there will no ‘framework’ index in elastic search. This will cause error response when requesting elastic search api. 

When there  is history data in es, the index will be initialized, and the error be gone.

Work around:
1. Hide link and warning icon when retry is 0
2. regard as healthy if  'index not found'

**Comment by fanyangCS** [comment]
@debuggy, do you have a fix for 2 ?
