### ISSUE TITLE
[Feedback v0.14.0] "View full log" for stdout does not work 

### ISSUE THREAD

**Issue by xulzee** [microsoft/pai#4009]
Hi,
Click "View full log" for stdout and stderr in each task does not work.

![image](https://user-images.githubusercontent.com/29273676/70685215-acc58080-1ce3-11ea-9619-2a9757c0bf2c.png)

but sometimes it works and the url is quit different.
![image](https://user-images.githubusercontent.com/29273676/70685276-d8e10180-1ce3-11ea-98a7-c947888a1b5b.png)

Thank you very much for your help!

**Comment by xulzee** [comment]
In addition, if I add "/ yarn / < master IP >: 8188 /, it works.
![image](https://user-images.githubusercontent.com/29273676/70685478-82c08e00-1ce4-11ea-857f-1fdd89c630b2.png)

**Comment by mzmssg** [comment]
It might be pylon or webportal issue. 

Confirmed with @sunqinzheng , it should be fix in #3256 .
