### ISSUE TITLE
[v0.16.0] Failed to fetch nodes and gpu info 

### ISSUE THREAD

**Issue by edenbuaa** [microsoft/pai#4020]
**OpenPAI Environment**:
- OpenPAI version: v0.16.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): ubuntu16.04
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

I deploied the k8s version with v0.16.0, but the total gpu count and node number is 0 in dashboard. Actually, There should be 2 gpus and 1 work node.
![image](https://user-images.githubusercontent.com/16248697/70898759-47012d80-2030-11ea-9547-cdd6e71d1dac.png)

the hardware page:

![image](https://user-images.githubusercontent.com/16248697/70898986-b5de8680-2030-11ea-891b-609778508b0e.png)

![image](https://user-images.githubusercontent.com/16248697/70899052-d73f7280-2030-11ea-9d18-48fe9503003e.png)

Are there any instructions I can follow to check this problem? thanks.

**Comment by fanyangCS** [comment]
dashboard is obsoleted in 0.16. and this is an internal release.

**Comment by edenbuaa** [comment]
Ok. When will the official version be released?

**Comment by scarlett2018** [comment]
@edenbuaa - please stay tune with https://github.com/microsoft/pai/issues/3872, release related info will be posted on top pinned issues like #3872.

BTW, would you mind share more about your org's info (name, deployment scale, how PAI is used, etc.) for our reference? thanks.
