### ISSUE TITLE
P00 - Deployment story for Beta release

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#4022]
Deployment should be limited within few hours to at most 1 day in general

**Comment by fanyangCS** [comment]
related https://github.com/microsoft/pai/issues/1733

**Comment by fanyangCS** [comment]
related https://github.com/microsoft/pai/issues/1893

**Comment by fanyangCS** [comment]
a quick start document to help make the deployment easier (in recommended environment)
