### ISSUE TITLE
Deploy openpai on the existing kubernetes cluster

### ISSUE THREAD

**Issue by zw39125432** [microsoft/pai#4030]
**Organization Name**:

**Short summary about the issue/question**:
How to deploy openpai on the existing kubernetes cluster
**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by fanyangCS** [comment]
This is a PR showing how to deploy OpenPAI on an existing k8s cluster using AKS-engine. https://github.com/microsoft/pai/pull/4735
