### ISSUE TITLE
[webportal] Out of border when too many recent jobs and having two screens

### ISSUE THREAD

**Issue by shiyemin** [microsoft/pai#4031]
![image](https://user-images.githubusercontent.com/1501158/71053813-ad9a5e80-218a-11ea-8071-2a6ca48312f6.png)

When using two screens (with different resolution) and submit too many recent jobs, the recent list will be out of bourder on the screen with lower resolution and works fine on the other.

**How to reproduce it**: Submit 10 jobs. View the home page on the PC with two screens (having different resolution). On the lower resolution screen, the list will be out of border.

**OpenPAI Environment**:
- OpenPAI version: v0.16.0
- Device: Surface
- Screen 1 resolution: 2736x1824, 200% Font Size
- Screen 2 resolution: 1920x1080, 100% Font Size

**Comment by fanyangCS** [comment]
should have been fixed by @debuggy , waiting for confirmation.
