### ISSUE TITLE
All jobs hang on `waiting` status while submit multiple jobs over few seconds

### ISSUE THREAD

**Issue by s2100** [microsoft/pai#4034]
Hi,

After I submitted multiple jobs(almost 10) over a few seconds, I found that all jobs kept `waiting` status for more than 1 hour.

Then I stop all jobs except one `waiting` job and it turns to be `Running` status a few minutes later. 

How could I fix that? How could I submit multiple jobs in a very short time and wait for it finishes one by one?

**OpenPAI Environment**:
- OpenPAI version: 0.14.0

**Comment by yqwang-ms** [comment]
Can you provide more info? Such as Launcher Service log, AM log, RM log, etc.

**Comment by fanyangCS** [comment]
close as no response.
