### ISSUE TITLE
Submit CPU only job

### ISSUE THREAD

**Issue by shiyemin** [microsoft/pai#4054]
I am currently using v0.16.0 with hivedscheduler. I am wondering if there is any way to submit CPU only job? If it's not possible, is there a way to switch scheduler dynamically? In this way, maybe we can use another scheduler to submit CPU job.

**Comment by fanyangCS** [comment]
Do you have CPU only servers? if yes, you can create a VC that accepts CPU only jobs (in the leaf node, you can specify a "dummy" GPU to emulate this). If all nodes are GPU nodes, HiveD does not allow you to submit a CPU only job, because this will damage the "cell" HiveD assign to each VC.

**Comment by shiyemin** [comment]
> Do you have CPU only servers? if yes, you can create a VC that accepts CPU only jobs (in the leaf node, you can specify a "dummy" GPU to emulate this). If all nodes are GPU nodes, HiveD does not allow you to submit a CPU only job, because this will damage the "cell" HiveD assign to each VC.
> 
> And by the way, it is possible to deploy multiple k8s schedulers to the bed, you can deploy one default k8s scheduler to manage CPU only nodes (with the help of labels).

en...That's interesting. I will try the "dummy" GPU method after the CPU only server is ready.

**Comment by redpoppet** [comment]
sorry,  I only have one server without GPU, and I want to deploy openpai with singbox. I don't know how to deal with GPU driver。kubelet can't start because of gpu dirver,so service can't start
