### ISSUE TITLE
Pylon should not let user specify arbitrary addresses

### ISSUE THREAD

**Issue by hwuu** [Microsoft/pai#406]
Related discussion: https://github.com/Microsoft/pai/pull/377#discussion_r175250432. Bin's suggestion:

> I'm thinking of we should limit the user's freedom to compose Yarn urls with arbitrary target_port so that users will not able to use this proxy to probe our backend resources randomly but only able to visit RMs and NMs.
>
> And also we should like WebHDFS not let user to specify RM host name but we pick it up from environment for not exposing deployment specific stuff on API path.

**Comment by scarlett2018** [comment]
I'm closing all the Yarn related low risk items, as we are not making any movement towards that direction.
If there are any new needs, let's create new ones with more clear business needs and technical needs descriptions.
