### ISSUE TITLE
What's the difference between the  pure k8s version and yarn version

### ISSUE THREAD

**Issue by edenbuaa** [microsoft/pai#4062]
I am a little confused about the two kinds of pai version: yarn and pure k8s
1. what's the difference between them and what's the scenarios to use the specific one?
2. Are they same for the gpu schedule strategy?

thanks.

**Comment by fanyangCS** [comment]
2. They are different.
1. Yarn version uses Yarn’s scheduler and k8s version uses a new k8s scheduler developed by us.

**Comment by edenbuaa** [comment]
@fanyangCS Could you give a little more detail explanation about their difference, or what's the advantage of the new k8s scheduler.

**Comment by fanyangCS** [comment]
The new k8s scheduler, HiveD, is a scheduler designed for multi-tenant GPU cluster running DNN workloads. The key advantage of HiveD is it protects each VC from the fragmentation from other VCs. For example, traditional scheduler YARN allows you to reserve 64 GPUs, HiveD allows you to reserve 8 nodes with 8GPUs. In any case, HiveD ensures that your VC will enjoy 8 nodes each with 8GPUs, while Yarn (or other k8s scheduler) can only ensure that your VC can get 64 GPUs, which could be scattered across more than 8 nodes.

**Comment by edenbuaa** [comment]
thanks @fanyangCS
