### ISSUE TITLE
Cannot retrieve job status when job is submitting

### ISSUE THREAD

**Issue by ultmaster** [microsoft/pai#4072]
When I try to access the web portal to retrieve the job list at the same time when I submit new jobs, the webportal errors with this:

![image](https://user-images.githubusercontent.com/8463288/71454411-b5ca4d80-27cb-11ea-979c-2de986799fc4.png)

I don't know if this is by design. The problem is, if I'm submitting jobs in batch (like with NNI), there will be minutes during which I cannot access job list.

**Comment by abuccts** [comment]
It happens when there's a heavy load and framework controller cannot update all frameworks timely.
#3876 already mocks statuses for those jobs, seems your bed needs an upgrade.

**Comment by ultmaster** [comment]
Well informed and thanks.
