### ISSUE TITLE
[Feedback openpai v0.14.0] submit job error  when use Team wise storage  via nfs

### ISSUE THREAD

**Issue by apri30th** [microsoft/pai#4073]
my openpai version is  v0.14.0 
I use nfs  to submit job  
![image](https://user-images.githubusercontent.com/4046214/71454547-5456ae80-27cc-11ea-964e-47284b8647f8.png)
when i click the submit button  , it pops the alert view as follows.
![image](https://user-images.githubusercontent.com/4046214/71454639-a0a1ee80-27cc-11ea-829e-a2c9c5b20e25.png)
it shows like  hdfs safemode problem.
then i  in openpai docker image  and use command   hdfs dfsadmin -safemode leave 
but it show  safemode: FileSystem file:/// is not an HDFS file system

how could i to solve this ? any suggestion  ?  thanks

**Comment by Binyang2014** [comment]
@apri30th Can you show your job config?
@debuggy Do you know this? Any suggestion?

**Comment by apri30th** [comment]
> @apri30th Can you show your job config?
> @debuggy Do you know this? Any suggestion?

@Binyang2014    i input any random words  in command  , when  click the submit button ,it will pop the safeModeException alert 

![image](https://user-images.githubusercontent.com/4046214/71505448-2babe300-28b8-11ea-8df9-1b26ad6ab93b.png)

**Comment by debuggy** [comment]
@apri30th 
Just as the error says, the resources are low in your hdfs, maybe disk space or memory is out of usage. Could you make sure if your hdfs file system has enough resources？

**Comment by apri30th** [comment]
> e resources are low in your hdfs, maybe disk space or memory is out of usage. Could you make sure if your hdfs file system has enough reso

@debuggy 
![image](https://user-images.githubusercontent.com/4046214/71513225-615ec500-28d4-11ea-8ec7-9ab086b1f962.png)
i think it have enough resources .   and i try to solve it in  dev-box docker images . in dev-box docker image i input the command hdfs dfsadmin -safemode leave , but it show safemode: FileSystem file:/// is not an HDFS file system

**Comment by fanyangCS** [comment]
please refer to Hadoop community for the safe mode issue.
