### ISSUE TITLE
Refine Web UI Homepage (normal user and admin) + fix no available node

### ISSUE THREAD

**Issue by yangou1988** [microsoft/pai#4074]
Refine homepage UI
1. home page - normal user
Update the margin and padding
Add My favorite job
![Homepage Normal uesr– 1920x1080px – 1](https://user-images.githubusercontent.com/44491713/71457162-b4068700-27d7-11ea-8ffa-c2be06204949.png)
![Homepage Normal user  – no available node + add my Favorite jobs 1920x1080px – 2](https://user-images.githubusercontent.com/44491713/71457164-b49f1d80-27d7-11ea-927f-49161614a2c8.png)

2. home page - admin user
Update the margin and padding
Add My recent job
![Homepage admin – no available node + add my recent jobs 1920x1080px – 1](https://user-images.githubusercontent.com/44491713/71457170-b8cb3b00-27d7-11ea-92ae-55a874025cc6.png)
![Homepage Admin – 1920x1080px](https://user-images.githubusercontent.com/44491713/71457172-b8cb3b00-27d7-11ea-95ed-7bd2e3d176a6.png)

3. UI of no available GPU nodes
Show a sentence: No available GPU nodes now at the middle of the chart
![image](https://user-images.githubusercontent.com/44491713/71457123-799cea00-27d7-11ea-8a20-62f0f24cddc7.png)

4. Update the color of Utilization 
Usage color: 0.0 - 0.9 Green, above 0.9 Red
![image](https://user-images.githubusercontent.com/44491713/71457131-80c3f800-27d7-11ea-8ac1-369cadf0da05.png)

5. Fix and keep the icons of Job state align with Job list.
![image](https://user-images.githubusercontent.com/44491713/71457138-8a4d6000-27d7-11ea-9f60-ede4c6946f2f.png)

**Comment by fanyangCS** [comment]
we seem to have a new constraint: the name of vc has to be low-cased. @yqwang-ms

**Comment by yqwang-ms** [comment]
yep, VC name now is constrained by https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
