### ISSUE TITLE
Can I use pylon to forward Tensorboard port or SSH port?

### ISSUE THREAD

**Issue by xulzee** [microsoft/pai#4100]
**Organization Name**: Nanjing University

**Short summary about the issue/question**: In my use, due to the school's restrictions on the security of the campus network, we can only arrange the PAI platform in the subnet of the campus network, and then we work in another subnet of the campus network, so we can't directly use tensorboard or SSH in the form of computer IP in the PAI platform. I know that some agents (shadowlocks, VPN, etc.) can be used, but these have some impact on daily work. I refer to the design documents of Pai, which uses pylon to forward various services. Can pylon be used to forward the tensorboard port or SSH port of these jobs?

**OpenPAI Environment**:
- OpenPAI version: 0.16.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): ubuntu
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Comment by abuccts** [comment]
Pylon is a nginx server, you can use it as [http proxy](http://nginx.org/en/docs/http/ngx_http_proxy_module.html) or [ssh proxy](http://nginx.org/en/docs/stream/ngx_stream_proxy_module.html) by modifying nginx [config](https://github.com/microsoft/pai/blob/master/src/pylon/deploy/pylon-config/location.conf.template).

But it will be easier if you simply use ssh tunnel (`ssh -L`) or ssh socks proxy (`ssh -D`).

**Comment by xulzee** [comment]
Thank you very much. It solved my problem.
