### ISSUE TITLE
[pylon][k8s-dashboard][SSL] SSL cfg should be independent from pylon

### ISSUE THREAD

**Issue by ydye** [microsoft/pai#4108]
#### The reason why we introduce the SSL cfg into OpenPAI.

Before the point we support AAD (OIDC) authentication, OpenPAI doesn't need to configure https. All request from outside to cluster internal is http. 
Due to requirement of azure ad, we need receive the response (Auth code & Token) with a https url, which is called redirect url in AAD.
To achieve the requirement of AAD, we make a change for pylon (nginx) to support the feature that receive https from outside and then redirect it to cluster inside as http.

#### How to configure ssl cfg formerly. And why do we design it as that previously.

SSL config is a sub module in pylon. 
Because in our previously design, all https is sent to pylon, and process it as a http request.

#### The issue comes from the old design

Now the reqeust to k8s-dashboard should be https. And not only pylon need to configure ssh key, k8s-dashboard should be configured too.

pylon will create ssl cert secret by judging whether the cluster is enable oidc (aad) or not.
Now, after @Binyang2014 's fix #4109 ,dashboard will perform the same logic. But I think now ssl is a feature of OpenPAI, not a  dependency of OIDC. So we shouldn't judge as what we have done before.

#### What should we do to resolve it. 

So ssl shouldn't be a sub module of pylon. And it should be indenpent from pylon as a separated configuration module.

**Comment by Binyang2014** [comment]
After separate the ssl and aad, pylon config will be clean.
Then we can redirect some `http` requests to `https` request in pylon.
Currently, request `http://k8s-dashboard-url` will not return `301` and redirect to  `https://k8s-dashboard-url`, even though https is supported.

**Comment by Binyang2014** [comment]
Fixed by https://github.com/microsoft/pai/pull/4493
