### ISSUE TITLE
Can not use kube-config generated by kubespray to access k8s-dashboard 

### ISSUE THREAD

**Issue by Binyang2014** [microsoft/pai#4112]
Refer to https://github.com/kubernetes/dashboard/issues/2474
Currently, the kube-config generated by kubespray doesn't have token field and can not be used to access dashboard.
1. Maybe we should investigate why this field is missing, and try to add this field.
2. If can not add this field, create a cluster-admin service account and use its' token to access dashboard is another option.

**Comment by fanyangCS** [comment]
add a document to show how to access k8s dashboard. https://github.com/microsoft/pai/blob/master/docs/k8s-dashboard/access-k8s-dashboard.md.
