### ISSUE TITLE
Documents about Webportal

### ISSUE THREAD

**Issue by xulzee** [microsoft/pai#4115]
**Organization Name**: Nanjing University

**Short summary about the issue/question**: I want to make some changes to the front-end code and add some projects. Do you have any documents about Webportal?

**Comment by Gerhut** [comment]
Check out https://github.com/microsoft/pai/blob/master/docs/webportal/PLUGINS.md

Web portal could be easily customized by developing web portal plugins.

**Comment by abuccts** [comment]
@xulzee To run webportal locally and make some small changes, please refer to [this document](https://github.com/microsoft/pai/blob/master/src/webportal/README.md). Custom plugins are extensions on webportal if you want to add some new plugable features.

**Comment by xulzee** [comment]
Got it. Thanks verymuch! I found the rest-server API.
