### ISSUE TITLE
Can we have multiple master nodes?

### ISSUE THREAD

**Issue by jwgu** [microsoft/pai#4116]
I have deployed a small size cluster. Now, I want to upgrade the master node to a more powerful machine. Is that possible? Can we have multiple master nodes? If so, how can I configure it?

**Comment by fanyangCS** [comment]
which version are you using?

**Comment by edenbuaa** [comment]
@fanyangCS Does the v0.14.0 version support this feature?

**Comment by fanyangCS** [comment]
the short answer is yes. 0.14.0 supports multiple masters. These master nodes form an etcd cluster. We do not have document to show how to do it. Experienced user can refer to etcd community to figure it out.

**Comment by ydye** [comment]
Hi @jwgu, I guess you wanna deploy OpenPAI's master service to serveral node to balance the load. Am i right?

**Comment by edenbuaa** [comment]
@ydye yes.

**Comment by ydye** [comment]
@edenbuaa currently, the master service can only be placed in one node. And mutliple master node is not supported yet.

**Comment by edenbuaa** [comment]
Thanks @ydye. 
by the way,  is there a way to restore the data(users & jobs) after the OpenPAI's services was deleted?

**Comment by ydye** [comment]
OpenPAI's user data is stored in k8s. If k8s is not cleaned, the user data will be kept. Or you can just get all user data with k8s' api. And after deleting the cluster, you can write the data into k8s again.

For hadoop's job, it's stored in zk. If you wanna keep the job data, I think you can find a solution to migrate the data in zk.

**Comment by edenbuaa** [comment]
@ydye It sounds cool!  but I can not find the kubespray module in my v0.14.0 code. Does the v0.14.0 version support this feature?

**Comment by ydye** [comment]
You can use this script in v0.14.0, and you can find the script in master branch. 
And for the k8s secrect's backup, it works in both version.

**Comment by edenbuaa** [comment]
Thanks. @ydye

**Comment by ydye** [comment]
And be careful, there will be some risks if you wanna migrate the hadoop job's data. Because we haven't done it before.

**Comment by scarlett2018** [comment]
Closing the issue as the question has been answered. Thanks @ydye, @edenbuaa and @jwgu
