### ISSUE TITLE
P0.5: Disallow ApiServer HA for Pod safety

### ISSUE THREAD

**Issue by yqwang-ms** [microsoft/pai#4120]
**Organization Name**:

**Short summary about the issue/question**:
ApiServer HA setup may cause controller and scheduler stale read and make wrong operation, see kubernetes/kubernetes#59848
#4117

Anyway we should not introduce an alpha feature for prod:
https://kubernetes.io/docs/tasks/administer-cluster/highly-available-master/#

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by Binyang2014** [comment]
Have disabled API server HA in all bed. Close it.
