### ISSUE TITLE
Default not to create priority class

### ISSUE THREAD

**Issue by yqwang-ms** [microsoft/pai#4124]
**Organization Name**:

**Short summary about the issue/question**:
Ref: https://github.com/microsoft/pai/issues/4117

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by abuccts** [comment]
Fixed in #4131.
