### ISSUE TITLE
How to mount a volum of local disk storage to job docker?

### ISSUE THREAD

**Issue by zeyu-hello** [microsoft/pai#4126]
**Short summary about the issue/question**:
Since OpenPAI doesn't support docker command `docker run -v /path:/path`, I have a data folder on the master node, and the [team-wise](https://github.com/microsoft/pai/tree/pai-0.14.y/contrib/storage_plugin) only support NAS. Then, how do I access this folder in OpenPAI?

**Comment by fanyangCS** [comment]
set up a NFS server on the master node, and mount to the NFS storage from within the job container.

**Comment by zeyu-hello** [comment]
I see.
Thanks! @fanyangCS
