### ISSUE TITLE
[Driver] Failed to build the specified version driver

### ISSUE THREAD

**Issue by edenbuaa** [microsoft/pai#4128]
**OpenPAI Environment**:
- OpenPAI version:  v0.14.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): ubuntu16.04
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

I want to build NVIDIA driver 440.33 to support cuda 10.2 after edited the _NVIDIA_VERSION = 440.33_ in dockerfile. But it reported errors 'not found':
```
https://us.download.nvidia.cn/XFree86/Linux-x86_64/440.33/NVIDIA-Linux-x86_64-440.33.run:
 ERROR 404: Not Found.
```
Did I miss something or Any suggestion? 
thanks a lot.

**Comment by abuccts** [comment]
there's no such driver version, maybe you mean `440.33.01`

you can get the correct link at https://www.nvidia.com/download/driverResults.aspx/154569/en-us after accepted the license, then replace the previous link in Dockerfile

**Comment by edenbuaa** [comment]
@abuccts thanks.

**Comment by VitoRazor** [comment]
> @abuccts thanks.

hi bro:
Sincerely ask you. How do you operate openpai with dockerfile? I hope to receive your reply. Thank you very much

**Comment by VitoRazor** [comment]
> @edenbuaa 

hi bro:
Sincerely ask you. How do you operate openpai with dockerfile? I hope to receive your reply. Thank you very much
