### ISSUE TITLE
Provide a way to setup storage in basic authentication mode

### ISSUE THREAD

**Issue by Binyang2014** [microsoft/pai#4130]
According to issue #4001, for basic authentication, we don't have a way to create group and add user to such group.
Storage config rely on user/group feature. To make sure `storage feature` works in basic auth mode we need to :
- Figure out how to create group in basic auth mode
- Test setup storage config in basic auth mode, provide clear doc about how to use storage in basic auth mode.

Current doc for setup storage config can be found at https://github.com/microsoft/pai/tree/master/contrib/storage_plugin, but it only works for aad auth mode

**Comment by fanyangCS** [comment]
begin after the refactoring of OpenPAI storage support

**Comment by Binyang2014** [comment]
Close this issue since #4161 is merged
