### ISSUE TITLE
[Feedback v0.14.0] How to add dashboard page for common user?

### ISSUE THREAD

**Issue by zeyu-hello** [microsoft/pai#4134]
Only the admin user has dashboard page bar, how to add this page for common user?
The `dashboard` page can be visited through `http://<master-node-ip>/dashboard.html` for comman user, but cannot throught clicking left side gui bar.

![image](https://user-images.githubusercontent.com/29373801/72244555-7f912880-3629-11ea-9810-e5f004624106.png)

Thanks!

**Comment by Binyang2014** [comment]
@zeyu-hello Why you need this feature. This page should only be visited by admin. It's by design.

**Comment by zeyu-hello** [comment]
I noticed previous version has this feature, and found it very convenient and intuitive.
why do you abandon it? I think you can make it as `optional`.

**Comment by Binyang2014** [comment]
The dashboard is a cluster view. For normal user, he/she needn't to care about the whole cluster resource, he/she only need to care about the VC resource he/she can use. Currently, we provide a home page for normal users. Please refer to issue #4057. Normal user could find cpu/memory/gpu usage in home page.

**Comment by zeyu-hello** [comment]
I see.
Thanks! @Binyang2014
