### ISSUE TITLE
Add document on how to access rbac k8s dashboard

### ISSUE THREAD

**Issue by abuccts** [microsoft/pai#4136]
**Short summary about the issue/question**:
Add documents on how to access rbac k8s dashboard, including use kube config and get service token.

**Comment by Binyang2014** [comment]
For PAI which not enable https, we may need to provide a self-sign cert for dashbaord. Otherwise, we need to access dashboard through `kube-proxy`.

Or we can make PAI enable https by default and dashboard can reuse the cert

**Comment by fanyangCS** [comment]
@Binyang2014 , we should enable https by default.

**Comment by fanyangCS** [comment]
https://github.com/microsoft/pai/blob/master/docs/k8s-dashboard/access-k8s-dashboard.md
