### ISSUE TITLE
[Minor Change] improve the AAD integration error message

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#4158]
The current failure message is like:

> I try to login through portal but it failed with error "{"code":"ForbiddenUserError","message":"User ** is not in configured groups."}"

Suggest to change to:
`"{"code":"ForbiddenUserError","message":"User ** is not in configured groups (group A, group B), please contact user group admin to join the groups."}"`

**Comment by ydye** [comment]
#4167
