### ISSUE TITLE
Upgrade nvidia driver manually

### ISSUE THREAD

**Issue by zhanlinfeng** [microsoft/pai#4169]
Can I upgrade NVIDIA driver manually instead of via Pai?
I've tried many versions of the driver,but failed beacuase  Driver/library version mismatch。
Does this have anything to do with pai?
Besides，The driver seems to be reset to version 384 by pai after a while.

**Comment by ydye** [comment]
Have you manually installed the nvidia drivers with apt on your machine?

**Comment by zhanlinfeng** [comment]
> Have you manually installed the nvidia drivers with apt on your machine?

yes

**Comment by ydye** [comment]
i think you haven't remove the driver installed by openpai. And its module is still running in your os. Before install the drivers by yourself, you should unload it at first.
- You could remove openpai's drivers and unload the module from kernal with this script https://github.com/microsoft/pai/blob/master/contrib/kubespray/clean-nvidia-driver-by-openpai.sh
- And then you should reboot your machine.
- Suggest remove the driver installed by yourself too. And install it again after cleaning the driver of openpai

**Comment by scarlett2018** [comment]
> i think you haven't remove the driver installed by openpai. And its module is still running in your os. Before install the drivers by yourself, you should unload it at first.
> 
> * You could remove openpai's drivers and unload the module from kernal with this script https://github.com/microsoft/pai/blob/master/contrib/kubespray/clean-nvidia-driver-by-openpai.sh
> * And then you should reboot your machine.
> * Suggest to remove the driver installed by yourself too. And install it again after cleaning the driver of openpai

Closing the issue as the question has been answered, feel free to reopen if there are any part not yet address. We are also love to hear the feedback on trying the suggestions. @zhanlinfeng
