### ISSUE TITLE
Help, rest-server error

### ISSUE THREAD

**Issue by zhanlinfeng** [microsoft/pai#4173]
**Organization Name**:

**Short summary about the issue/question**:I cannot start rest-server，I get the following prompt:
rest-server is not ready yet. Please wait for a moment!
The logs on k8s are as follows:
2020-02-08T08:15:09.142Z [ERROR] Failed to load group config from configmap file. 
/usr/src/app/src/config/authn.js:59
  throw error;
  ^
Error: ENOENT: no such file or directory, open '/group-configuration/group.yaml'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.&lt;anonymous&gt; (/usr/src/app/src/config/authn.js:56:46)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pai-rest-server@0.14.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pai-rest-server@0.14.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-08T08_15_09_148Z-debug.log

**Brief what process you are following**:I try to reinstall pai, but it doesnot wotk.What should I do？

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:0.14.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):ubuntu16.04
- Kernel (e.g. `uname -a`):4.15.0-76-generic
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by ydye** [comment]
Can you paste the content of service-configuration.yaml please?

**Comment by ydye** [comment]
And please provide the output of the following command in pai's source rep
```
git branch
```

**Comment by victorming** [comment]
I also encounter the same issue, any progress?

**Comment by ydye** [comment]
@victorming 
please
Paste the output of following command and the your service-configuration.yml
```
git rev-parse --abbrev-ref HEAD
```

**Comment by victorming** [comment]
v0.14.0

**Comment by victorming** [comment]
BTW, I redeployed rest-server of v0.13.0. It works.

**Comment by ydye** [comment]
Can you paste the code in the path pai/src/rest-server/deploy/rest-server.yml.template?

**Comment by victorming** [comment]
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rest-server-ds
spec:
  selector:
    matchLabels:
      app: rest-server
  template:
    metadata:
      name: rest-server
      labels:
        app: rest-server
    spec:
      hostNetwork: false
      hostPID: false
      containers:
      - name: rest-server
        image: {{ cluster_cfg['cluster']['docker-registry']['prefix'] }}rest-server:{{ cluster_cfg['cluster']['docker-registry']['tag'] }}
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /pai-cluster-config
          name: pai-configuration-rest-server
        - mountPath: /job-exit-spec-configuration
          name: job-exit-spec-rest-server
        env:
        - name: LAUNCHER_TYPE
          value: yarn
        - name: LAUNCHER_WEBSERVICE_URI
          value: {{ cluster_cfg['yarn-frameworklauncher']['webservice'] }}
        - name: HDFS_URI
          value: hdfs://{{ cluster_cfg['hadoop-name-node']['master-ip'] }}:9000
        - name: WEBHDFS_URI
          value: http://{{ cluster_cfg['hadoop-name-node']['master-ip'] }}:5070
        - name: YARN_URI
          value: http://{{ cluster_cfg['hadoop-resource-manager']['master-ip'] }}:8088
        - name: JWT_SECRET
          value: {{ cluster_cfg['rest-server']['jwt-secret'] }}
        - name: DEFAULT_PAI_ADMIN_USERNAME
          value: {{ cluster_cfg['rest-server']['default-pai-admin-username'] }}
        - name: DEFAULT_PAI_ADMIN_PASSWORD
          value: {{ cluster_cfg['rest-server']['default-pai-admin-password'] }}
        - name: K8S_APISERVER_URI
          value: {{ cluster_cfg['layout']['kubernetes']['api-servers-url'] }}
        - name: AZ_RDMA
          value: "{{ cluster_cfg['cluster']['common']['az-rdma']}}"
        - name: DEBUGGING_RESERVATION_SECONDS
          value: "{{ cluster_cfg['rest-server']['debugging-reservation-seconds']}}"
{% if cluster_cfg['rest-server']['github-owner'] %}
        - name: GITHUB_OWNER
          value: {{ cluster_cfg['rest-server']['github-owner'] }}
{% endif %}
{% if cluster_cfg['rest-server']['github-repository'] %}
        - name: GITHUB_REPOSITORY
          value: {{ cluster_cfg['rest-server']['github-repository'] }}
{% endif %}
{% if cluster_cfg['rest-server']['github-path'] %}
        - name: GITHUB_PATH
          value: {{ cluster_cfg['rest-server']['github-path'] }}
{% endif %}
{% if cluster_cfg['layout']['kubernetes']['api-servers-url'].startswith('https://') %}
        - name: K8S_APISERVER_CA_FILE
          value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - name: K8S_APISERVER_TOKEN_FILE
          value: /var/run/secrets/kubernetes.io/serviceaccount/token
{% endif %}
        ports:
        - name: rest-server
          containerPort: 8080
          hostPort: {{ cluster_cfg['rest-server']['server-port'] }}
        {%- if cluster_cfg['cluster']['common']['qos-switch'] == "true" %}
        resources:
          limits:
            memory: "512Mi"
        {%- endif %}
      imagePullSecrets:
      - name: {{ cluster_cfg["cluster"]["docker-registry"]["secret-name"] }}
      volumes:
      - name: pai-configuration-rest-server
        configMap:
          name: pai-configuration
      - name: job-exit-spec-rest-server
        configMap:
          name: job-exit-spec-configuration

**Comment by victorming** [comment]
rest-server of v0.13.0 can't work compatibly with webportal. When I login on webportal, it reports following error: 
{"code":"NoApiError","message":"API /api/v1/authn/oidc/login?redirect_uri=http%3A%2F%2F192.168.101.241%3A9286%2Findex.html&callback=http%3A%2F%2F192.168.101.241%3A9286%2F is not found."}

**Comment by ydye** [comment]
Seems your code is not in the branch `pai-0.14.y`
https://github.com/microsoft/pai/blob/pai-0.14.y/src/rest-server/deploy/rest-server.yaml.template#L122

**Comment by ydye** [comment]
> rest-server of v0.13.0 can't work compatibly with webportal. When I login on webportal, it reports following error:
> {"code":"NoApiError","message":"API /api/v1/authn/oidc/login?redirect_uri=http%3A%2F%2F192.168.101.241%3A9286%2Findex.html&callback=http%3A%2F%2F192.168.101.241%3A9286%2F is not found."}

Yes, you should deploy rest-server with the same version as webportal

**Comment by victorming** [comment]
I use the dev-box of v0.14.0. Maybe the container has yet to be updated.

**Comment by ydye** [comment]
You could re-clone the code. Then have a try.

**Comment by victorming** [comment]
OK

**Comment by victorming** [comment]
Now the rest-server is OK. But the webportal in dev-box@v0.14.0 needs to be updated either. Otherwise, webportal displays error when login. Seems the directory /pai in dev-box@v0.14.0 doesn't synchronize with the version of v0.14.0.

**Comment by ydye** [comment]
I think you should deploy all service with the code you cloned just before.

**Comment by victorming** [comment]
OK, I will redeploy these services with the code cloned. Thanks anyway!
