### ISSUE TITLE
In openpai, how to download containers in harbor when submitting tasks

### ISSUE THREAD

**Issue by mtzfei** [microsoft/pai#4176]
**Organization Name**:haiyangdaxue

**Short summary about the issue/question**:How to set the harbor private warehouse when submitting tasks in openpai so that tasks can run in custom containers

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by fanyangCS** [comment]
just deploy a private docker registry. https://docs.docker.com/registry/deploying/

**Comment by scarlett2018** [comment]
> just deploy a private docker registry. https://docs.docker.com/registry/deploying/

Closing the issue as the question has been answered, feel free to reopen if you (@mtzfei) have further questions, thanks.
