### ISSUE TITLE
Feb end game plan

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#4177]
planning plan #3872 
release manager @Binyang2014  
test period: 2/10 ~ 2/17

----------------------
Test plan item
----------------------
Feature issue id | Feature Owner | Test Owner(s) | Doc ready for test (Y/N)
1. VS Code | @yiyione | @qfyin | Test case: #4186
2. #4024 new UI | @debuggy | @yangou1988 | Y, use Yang's design doc as test cases;
3. #4020 Grafana | @Binyang2014  | @abuccts | No document needed 
4. #4131 #4125 priority class + pod creation error pattern | @abuccts | @yqwang-ms | No document needed 
5. #3866 auto deletion leak | @Binyang2014 | @yqwang-ms | to do: binyang open up leak for test
6. #4027 remove yarn version | @ydye | @abuccts | No, @abuccts will write test cases
7. #4081 storage manager restart issue | @Binyang2014 | @abuccts | No document needed 
8. 2 P1 security issues (secret/ACS) | @Binyang2014 | @mydmdm |  No document needed 
9. Job history dev log | @debuggy | @debuggy | for debug only  (```Any doc needed?```)
10. #4105, #3823 | @Binyang2014 | @yiyione | submit job with runtime plugin(storage, ssh, tensorboard, ...), review its yaml file, make sure the behavior is as expect. (Need to check `new job`, `clone job`, `import job`)
11. #4014 | @Binyang2014 | @mydmdm | plugin as an optional requests
12. Job retry page issue #4008 |@debuggy | @debuggy | bug fix  (```finish```)
13. NNI integration | @SparkSnail 
14. #4022 | @ydye  |@Binyang2014 | deploy and precheck
15. tag and commit number | @ydye/@debuggy | @Binyang2014 (```#4190```) 
16.  Finalize protocol - Job UUID #3935 | @abuccts | @debuggy  | check annotation and md5 decode
17. K8S Dashboard https enabled #4025 | @Binyang2014 | TBD | Need doc first
18. Service page #3892  | @sunqinzheng | @debuggy

**Comment by fanyangCS** [comment]
done.
