### ISSUE TITLE
Web portal - Jobs ( left navigation ) filtered Status automatically

### ISSUE THREAD

**Issue by yangou1988** [microsoft/pai#4197]
**Short summary about the issue/question**:
Web portal - Jobs ( left navigation ) filtered Status automatically if clicked the home's job status before.

**Brief what process you are following**:
1. Click any 'view all' button of Job status at Home page (example: Succeeded)
url: https://int.openp.ai/job-list.html?status=Succeeded&user= 
![image](https://user-images.githubusercontent.com/44491713/74319791-817e1100-4dba-11ea-9265-5694aa1fb3b7.png)

2. visit other pages
3. Click Jobs in left navigation
![image](https://user-images.githubusercontent.com/44491713/74319829-935fb400-4dba-11ea-862d-9c2c3bf5b5b8.png)

4. Jobs filtered status 'Succeeded' automatically not all jobs
url: https://int.openp.ai/job-list.html
![image](https://user-images.githubusercontent.com/44491713/74319768-71663180-4dba-11ea-84b9-16ce4c178837.png)

**Comment by debuggy** [comment]
After discussing with @yangou1988, with remain this behavior in this release.
