### ISSUE TITLE
Mismatch failurePolicy behavior for different runtime plugins

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#4200]
- With `teamwise storage` plugin and a wrong storage setting, the job will fail even `failurePolicy = ignore`
- With `cmd` plugin and a wrong user command, the job will succeed if `failurePolicy = ignore`.

It may be confusing for user to determine when to use `failurePolicy` to bypass runtime plugin failure.

**Comment by Binyang2014** [comment]
This issue becauses `failurePolicy` only ignore the errors when the command is running in user container.
If error is occurred in init container. The failure will not ignore.

**Comment by fanyangCS** [comment]
@Binyang2014 , this makes the failurePolicy hard to understand. Can you respect the policy even in init Container?

**Comment by Binyang2014** [comment]
Sure, will fix this issue and respect the policy in the init container. Since it's just a debug feature and the fix is not straightforward, I suggest fix this issue in next release. Fix in 0.17 release may bring some risk.

**Comment by Binyang2014** [comment]
> @Binyang2014 , this makes the failurePolicy hard to understand. Can you respect the policy even in init Container? It is fine if the whole job may fail if you ignore the failure. You simply define the failurePolicy of a plugin, the job state is out of the scope of this policy.

Sure, will fix this issue and respect the policy in the init container. Since it's just a debug feature and the fix is not straightforward, I suggest fix this issue in next release. Fix in 0.17 release may bring some risk.

**Comment by fanyangCS** [comment]
@Binyang2014 ok, let's make it a known issue and fix in next release.
