### ISSUE TITLE
[Drivers] No data point in dashboard with driver 440.33

### ISSUE THREAD

**Issue by edenbuaa** [microsoft/pai#4207]
*OpenPAI Environment**:
- OpenPAI version: v0.14.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): ubuntu16.04
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

I build the driver of 440.33 version based on the driver dockerfile in src/driver/build. But there's no data point for GPU memory or GPU Utilization after upgrading. The logs in job-exporter show as follows:
![image](https://user-images.githubusercontent.com/16248697/74519356-7bba3400-4f50-11ea-915a-f6cc2a6cbead.png)

How to fix this? thanks.

**Comment by Binyang2014** [comment]
@edenbuaa, Please make sure the driver installed in `/var/drivers/nvidia/current`  folder. And you can run `nvidia-smi` after set correct `PATH` and `LD_LIBRARY_PATH` env.

**Comment by edenbuaa** [comment]
@Binyang2014 How to check where the driver installed?

**Comment by Binyang2014** [comment]
@edenbuaa If you use `drivers-one-shot` to install driver, the driver will be installed into host. Please go to your worker node and check if `/var/drivers/nvidia/current` exist. And the `nvdia-smi` inside it is valid

**Comment by edenbuaa** [comment]
thanks @Binyang2014 . The  `/var/drivers/nvidia/current` folder exist in work node. when I execute `nvidia-smi` , It report the following message:

```
NVIDIA-SMI couldn't find libnvidia-ml.so library in your system. Please make sure that the NVIDIA Display Driver is properly installed and present in your system.
Please also try adding directory that contains libnvidia-ml.so to your system PATH
```
I found two 'libnvidia-ml.so' in system:
/var/drivers/nvidia/440.33.01/lib/libnvidia-ml.so
/var/drivers/nvidia/440.33.01/lib64/libnvidia-ml.so
and the PATH doesn't contains the two of them. what we should do next?

**Comment by Binyang2014** [comment]
Hi @edenbuaa `libnvidia-ml.so`  should under `/var/drivers/nvidia/current/lib` and `/var/drivers/nvidia/current/lib64`. Can you confirm the file exist under these paths? And please make sure following command is work. Otherwise, it's driver install issue.
```sh
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/var/drivers/nvidia/current/lib64:/var/drivers/nvidia/current/lib
/var/drivers/nvidia/current/bin/nvidia-smi
```

**Comment by edenbuaa** [comment]
@Binyang2014 yes, you are right.
Another error report after export LD_LIBRARY_PATH in job-exporter:
![image](https://user-images.githubusercontent.com/16248697/74623890-53fde280-5181-11ea-8a87-84d4335cf7cb.png)

**Comment by Binyang2014** [comment]
Hi @edenbuaa. After you make sure the `/var/drivers/nvidia/current/` point to the correct driver in your worker node. You can restart the `job-exporter` in the dev-box by running: 
```bash
python paictl.py service stop -n job-exporter
python paictl.py service start -n job-exporter
```

**Comment by edenbuaa** [comment]
It works! thanks @Binyang2014
