### ISSUE TITLE
Provide standard deep learning docker images

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#4227]
We use docker images from `deepo` as the default images in OpenPAI. It is okay for basic needs. However, `deepo` suffers from the following problems:
  -  The version of the deep learning framework, such as `TensorFlow` and `PyTorch`, is not fixed even with the same tag.
  - Lacks some basic functions, such as `SSH` and `Jupyter Notebook`.

To enhance the user experience, we could build the following docker images:

  - Python 3
  - `TensorFlow`/`PyTorch`/`MXNet`/`CNTK`, tagged by version.
  - With/Without GPU support.
  - With `SSH` and `Jupyter Notebook` support.

**Comment by mydmdm** [comment]
refer to the documentation here
https://openpai.readthedocs.io/en/latest/manual/cluster-user/docker-images-and-job-examples.html
