### ISSUE TITLE
Runtime ssh barrier timeout threshold too short 

### ISSUE THREAD

**Issue by Binyang2014** [microsoft/pai#4239]
When running MPI job, we may need all job be prepared for ssh.
But when image size is large, if one node already has the image in cache, one node doesn't.

The node which doesn't have the image need to pull whole image from the registry, and this will cause ssh barrier timeout. Even though there is no error.

We can avoid this by two options:
1. extend ssh barrier timeout threshold 
2. Help customer pull image in init-container, and doesn't start the user container util everything is done.

**Comment by fanyangCS** [comment]
can you set the default ssh barrier timeout of infinite?

**Comment by Binyang2014** [comment]
> can you set the default ssh barrier timeout of infinite?

Set timeout to infinite may take some risk. If worker failed to start ssh, the job will hang forever. I can set the default timeout to `30 min` or longer and provide an option to let customer set the timeout. And provide more information in error spec.
