### ISSUE TITLE
How to use ports to Connect to Visdom?

### ISSUE THREAD

**Issue by andrewjong** [microsoft/pai#4240]
**Organization Name**: AI startup

**Short summary about the issue/question**:
How do we use OpenPAI's ports so we can run Visdom?

**Brief what process you are following**:

I am running a simple example using the [PyTorch CycleGAN repository](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix). This repository uses Facebook's [Visdom](https://github.com/facebookresearch/visdom/) to visualize training.

I want to pass the http port to my Python program with `python train.py --display_port <the_port>`

I found that it is possible to use the `$PAI_PORT_LIST_$taskRole_$taskIndex_$portType` environment variable, but I'm not sure how to use it. I figure `$portType` is the label of the port, right? But what are `$taskRole` and `$taskIndex` are supposed to be? What I tried below does not work.

![image](https://user-images.githubusercontent.com/8121216/75728619-40806a80-5c9d-11ea-99f8-9306b587a43e.png)

I get this error
```
train.py: error: argument --display_port: expected one argument
```

and echoing $PAI_PORT_LIST_Task_role_1_visdom gives nothing.

**How to reproduce it**:

See image above.

**OpenPAI Environment**:
- OpenPAI version: v0.14.0
- Cloud provider or hardware configuration: not sure, waiting to hear back from my administrator
- OS (e.g. from /etc/os-release): Ubuntu 16.04.6 LTS
- Kernel (e.g. `uname -a`): Linux pai04 4.15.0-45-generic #48~16.04.1-Ubuntu SMP Tue Jan 29 18:03:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by andrewjong** [comment]
I figured it out. It should have been `$PAI_PORT_LIST_Task_role_1_0_visdom`

**Comment by fanyangCS** [comment]
yes. 3 instances means you will have three tasks, task index 0, 1, and 2. 

And we allow you to define task role (e.g., MPI_server and MPI_worker),  tasks in different role has a separate index. If you define two task roles, each with 3 instances, you will have 6 instances in total. 3 in each task role, and they have an index from 0, 1, 2 in each task tole.

**Comment by abuccts** [comment]
@andrewjong you could get the value of `$taskRole` and `$taskIndex` from env variables `$PAI_CURRENT_TASK_ROLE_NAME` and `$PAI_CURRENT_TASK_ROLE_CURRENT_TASK_INDEX`, respectively

**Comment by andrewjong** [comment]
Thank you very much, @fanyangCS and @abuccts !
