### ISSUE TITLE
[Job Submission] how to reference port in commands

### ISSUE THREAD

**Issue by mydmdm** [microsoft/pai#4246]
Here is the description in the adding port panel in job submission page. Then my question is how to use the variable when task has multiple counts? As far as I know, bash doesn't support nested literal e.g. `${PAI_PORT_LIST_${taskRole}_${taskIndex}_<port-label>}`

> You can get the assigned port value (comma separated list if count > 1) through the environment variable:
> PAI_PORT_LIST_$taskRole_$taskIndex_$portLabel

**Comment by yiyione** [comment]
1. MY_PORT="PAI_PORT_LIST_${taskRole}_${PAI_CURRENT_TASK_ROLE_CURRENT_TASK_INDEX}_<port-lable>"
2. PORT = ${!MY_PORT}

**Comment by mydmdm** [comment]
Here is a summary, 

- use [Indirection](https://stackoverflow.com/a/16553351/1012014) supported by `bash` as below 
> 1. `MY_PORT="PAI_PORT_LIST_${taskRole}_${PAI_CURRENT_TASK_ROLE_CURRENT_TASK_INDEX}_<port-label>"`
> 2. `PORT = ${!MY_PORT}`

*Note that you need use `$PAI_CURRENT_TASK_ROLE_CURRENT_TASK_INDEX` instead of `$taskIndex`*

- use a **to-be-deprecated** environmental variable to get port (list) in current container `PAI_CONTAINER_HOST_<port-label>_PORT_LIST`

And I think maybe something like `<% ports.<port-label> %>` is more easy to understand

**Comment by chuangxinyuan** [comment]
It works, but you need to remove the blanks in `PORT = ${!MY_PORT}`,  use `PORT=${!MY_PORT}` instead.
