### ISSUE TITLE
PAI become unavailable when users open too many job detail-pages 

### ISSUE THREAD

**Issue by Binyang2014** [microsoft/pai#4263]
Currently, PAI job-detail page will auto-refresh every `10 seconds`. When user submit too many job instances, every refresh will take a long time to retrieve data. And this will block other requests send to `rest-server`

Options to solve this problem:
1. Disable auto-refresh in job detail page
2. Add cache in rest-server
3. Add PAI service alert. When PAI become unavailable, rest-server will consume more than 4GB memory and cpu usage is over 100%. Maybe we can trigger an alert for this. (Collecting rest-server logs will also helpful)

**Comment by fanyangCS** [comment]
In the short term, I suggest to:
* Only call API to get GPU index when mouse hovering
* Disable auto-refresh when number of containers is larger than 64
