### ISSUE TITLE
update nvidia driver from 410.73 to 418.56,GPU Available becomes 0

### ISSUE THREAD

**Issue by shanying2017** [microsoft/pai#4269]
Hi:
  I update nvidia driver from 410.73 to 418.56,and the home page, GPU Available becomes 0
![image](https://user-images.githubusercontent.com/25327419/76218979-0dffe000-6250-11ea-97d2-4a6580a737ed.png)
is there any way to solve this without restart openpai ?
version: 0.14.0
thanks

**Comment by ydye** [comment]
Can you check all drivers service is ready or not？

**Comment by shanying2017** [comment]
all of them are running well
root@localhost:/# kubectl get pod --all-namespaces
NAMESPACE     NAME                                     READY   STATUS      RESTARTS   AGE
default       batch-job-hadoop-pcjjq                   0/1     Completed   0          39h
default       cleaner-ds-9gl47                         1/1     Running     0          39h
default       cleaner-ds-sctx2                         1/1     Running     0          39h
default       drivers-one-shot-2v8kd                   1/1     Running     0          39h
default       drivers-one-shot-jkkgp                   1/1     Running     0          39h
default       drivers-one-shot-mmqnx                   1/1     Running     0          39h
default       etcd-server-192.168.21.230               1/1     Running     0          3d11h
default       grafana-f4bbd4c59-2nmsv                  1/1     Running     0          39h
default       hadoop-data-node-ds-64vrp                1/1     Running     0          39h
default       hadoop-data-node-ds-8mzpm                1/1     Running     0          39h
default       hadoop-jobhistory-service-mpkxb          1/1     Running     0          39h
default       hadoop-name-node-ds-4ld9q                1/1     Running     0          39h
default       hadoop-node-manager-ds-872h2             1/1     Running     0          39h
default       hadoop-node-manager-ds-npnnn             1/1     Running     0          39h
default       hadoop-resource-manager-ds-lf4d9         2/2     Running     0          36h
default       job-exporter-kj66f                       1/1     Running     0          39h
default       job-exporter-nj4bb                       1/1     Running     0          39h
default       job-exporter-vbwwk                       1/1     Running     0          39h
default       node-exporter-66g2l                      1/1     Running     0          39h
default       node-exporter-8ptht                      1/1     Running     0          39h
default       node-exporter-f8gjd                      1/1     Running     0          39h
default       prometheus-deployment-b69bc6598-mfr5s    1/1     Running     0          39h
default       pylon-ds-mnthh                           1/1     Running     0          39h
default       rest-server-ds-hnsh2                     1/1     Running     0          39h
default       watchdog-5569dd7dfb-tr9vb                1/1     Running     0          39h
default       webportal-ds-brlmm                       1/1     Running     0          39h
default       yarn-frameworklauncher-ds-wq84d          1/1     Running     0          39h
default       zookeeper-ds-gmrqs                       1/1     Running     0          39h
kube-system   kube-apiserver-192.168.21.230            1/1     Running     0          3d11h
kube-system   kube-controller-manager-192.168.21.230   1/1     Running     0          3d11h
kube-system   kube-proxy-dkvwh                         1/1     Running     1          3d11h
kube-system   kube-proxy-scqv6                         1/1     Running     0          3d11h
kube-system   kube-proxy-wtx59                         1/1     Running     0          3d11h
kube-system   kube-scheduler-192.168.21.230            1/1     Running     0          3d11h
kube-system   kubernetes-dashboard-74cf4d8965-7hvk9    1/1     Running     0          3d11h

and I check the Prometheus, node 192.168.21.231' value should be 1 but get 0
![image](https://user-images.githubusercontent.com/25327419/76371220-88c21b80-6374-11ea-9d07-fbcbfbc0138d.png)

**Comment by ydye** [comment]
Can you execute the command following？
```
kubectl exec -it  drivers-one-shot-2v8kd nvidia-smi
```

**Comment by shanying2017** [comment]
the drivers is running well, I delete the pod hadoop-node-manager-ds and the available gpu come back
thanks a lot!
