### ISSUE TITLE
Start k8s service in dev box，and connection to the server:8080 was refused

### ISSUE THREAD

**Issue by mtzfei** [microsoft/pai#4276]
**Organization Name**:haiyangdaxue

**Short summary about the issue/question**:Start k8s service in dev box, and the connection to the server 192.168.100.11:8080 was refused - did you specify the right host or port?
  [ERROR] - deployment.k8sPaiLibrary.maintainlib.kubectl_install : kubectl ready test failed. Exit paictl.

**Brief what process you are following**:
python paictl.py cluster k8s-bootup -p ~/pai-config

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:v0.17.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by fanyangCS** [comment]
0.17 is an internal release. We do not provide support to this version. And we do not use paictl to deploy k8s in this version. 

We will release a public version soon.
