### ISSUE TITLE
single Box deployment on a server without GPU

### ISSUE THREAD

**Issue by redpoppet** [microsoft/pai#4281]
Hello,
   I deploy pai  use single box on a server(64G,ubuntu 16.04),  when when run "sudo python paictl.py service start " ,find error:  "zookeeper is not ready yet. Please wait for a moment! "  
Following #666 #1916,   I have moved the folder "~/pai/src/drivers/deploy" . But the server has no GPU,
i don‘t know how to handle it.
and I have modify the request memory of these file:
deployment/k8sPaiLibrary/template/apiserver.yaml.template
deployment/k8sPaiLibrary/template/controller-manager.yaml.template
deployment/k8sPaiLibrary/template/dashboard-deployment.yaml.template
deployment/k8sPaiLibrary/template/etcd.yaml.template
deployment/k8sPaiLibrary/template/scheduler.yaml.template
src/cleaner/deploy/cleaner.yaml.template
src/hadoop-jobhistory/deploy/hadoop-jobhistory.yaml.template
src/hadoop-name-node/deploy/hadoop-name-node.yaml.template
src/hadoop-node-manager/deploy/hadoop-node-manager.yaml.template
src/hadoop-resource-manager/deploy/hadoop-resource-manager.yaml.template
src/pylon/deploy/pylon.yaml.template
src/yarn-frameworklauncher/deploy/yarn-frameworklauncher.yaml.template
src/zookeeper/deploy/zookeeper.yaml.template
but no works 

execute  "kubectl get pods"
NAME                           AGE
drivers-one-shot-kb7jl         19h
hadoop-node-manager-ds-894vl   18h
zookeeper-ds-26k7h             18h
zookeeper-ds-rqrvd             18h

execute  "kubectl logs zookeeper-ds-26k7h"
Error from server: Get https://192.168.200.210:10250/containerLogs/default/zookeeper-ds-26k7h/zookeeper: dial tcp 192.168.200.210:10250: getsockopt: connection refused

how to fix it ? thx

**Comment by mydmdm** [comment]
Maybe https://github.com/microsoft/pai/issues/4054 would help

**Comment by redpoppet** [comment]
sorry, I only have one server without GPU, and I want to deploy openpai with singbox. I don't know how to deal with GPU driver。kubelet can't start because of gpu dirver,so service can't start.
Follow #4054, i should create a vc(?) and specify a "dummy" GPU to emulate this, but i don't know how to deal with it. Do you have any guidance？Thx。

**Comment by mydmdm** [comment]
actually we are preparing a manual to cover this topic related to install in CPU-only nodes, and will let it be public ASAP. Hope it would be helpful

**Comment by abuccts** [comment]
This is not a gpu node issue, but k8s deployment issue using paictl in yarn version.
@ydye to have a look.

**Comment by ydye** [comment]
Seem like a Zookeeper error. But the log is too short, I can't find more detail

**Comment by scarlett2018** [comment]
> execute "kubectl logs zookeeper-ds-26k7h"
> Error from server: Get https://192.168.200.210:10250/containerLogs/default/zookeeper-ds-26k7h/zookeeper: dial tcp 192.168.200.210:10250: getsockopt: connection refused

Hi @redpoppet 
it seems the problem is related to connection refused, are you having a good network connection with the target node? BTW, we had just release v1.0, would you like to try it out on the latest version and feedback to us, thanks.

**Comment by fanyangCS** [comment]
closed and track in https://github.com/microsoft/pai/issues/4578
