### ISSUE TITLE
Consider to use host-network for PAI service

### ISSUE THREAD

**Issue by Binyang2014** [microsoft/pai#4288]
Currently, PAI services **DOESN'T** use `host network`. When deploy PAI with k8s network plugin, customer may face some network issues, such as `rest-server` could not connect to internet.

Consider to use `host-network` for PAI services (rest-server, webportal, log-manager and so on)

**Comment by fanyangCS** [comment]
relate to https://github.com/microsoft/pai/issues/4603. close as fixed by this PR https://github.com/microsoft/pai/pull/4672
