### ISSUE TITLE
Import Error of kubernetes in legacy_user_migrate.py

### ISSUE THREAD

**Issue by shuangjiexu** [microsoft/pai#4298]
**summary of the issue**
Import Error of kubernetes in `src/rest-server/deploy/legacy_user_migrate.py`

**Brief what process you are following**:
Update v0.15.0 to v0.17.0 and runing command `python paictl.py service start`
There is no import error in v0.15.0 before. 

Error log:

> 2020-03-19 13:07:15,692 [INFO] - deployment.paiLibrary.paiService.service_template_generate : The template file of service rest-server is generated.
> 2020-03-19 13:07:15,692 [INFO] - deployment.paiLibrary.paiService.service_management_start : Begin to start service: [ rest-server ]
> 2020-03-19 13:07:15,692 [INFO] - deployment.paiLibrary.paiService.service_management_start : Begin to execute service rest-server's start script.
> configmap/group-configuration configured
> configmap/job-exit-spec-configuration configured
> Traceback (most recent call last):
>   File "legacy_user_migrate.py", line 10, in <module>
>     from kubernetes import client, config
> ImportError: No module named 'kubernetes'
> 2020-03-19 13:07:16,572 [ERROR] - deployment.paiLibrary.common.linux_shell : Failed to execute the start script of service rest-server
> 2020-03-19 13:07:16,573 [ERROR] - deployment.paiLibrary.paiService.service_management_start : Failed to start service rest-server
> 2020-03-19 13:07:16,573 [INFO] - deployment.paiLibrary.paiService.service_management_start : -----------------------------------------------------------
> 2020-03-19 13:07:16,574 [ERROR] - deployment.paiLibrary.paiService.service_management_start : Have retried 5 times, but service rest-server doesn't start. Please check it.

pip install kubernetes not works.

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version: v0.17.0
- OS: Ubuntu 16.04.6 LTS
- Kernel: Linux ubuntu 4.4.0-142-generic
- Hardware: 
`machine-sku:
  GENERIC:
    mem: 250
    gpu:
      type: 2080ti
      count: 8
    cpu:
      vcore: 64
    os: ubuntu16.04`

**Comment by abuccts** [comment]
pls try `pip3 install kubernetes`

**Comment by shuangjiexu** [comment]
Thanks! @abuccts 
`pip3 install kubernetes` and then `python paictl.py service start` solve my problem
