### ISSUE TITLE
v0.17.0 : hdfs name node can not access

### ISSUE THREAD

**Issue by shuangjiexu** [microsoft/pai#4308]
**v0.17.0 : hdfs name node can not access**:

When I use the HDFS data in PAI, it seems that the hdfs server could not be accessed
![image](https://user-images.githubusercontent.com/10096172/77147385-0d750e00-6ac8-11ea-9b2a-52700b53a522.png)

The hadoop-node is online:
![image](https://user-images.githubusercontent.com/10096172/77147465-43b28d80-6ac8-11ea-860f-6e7e64a14919.png)
and I can access http://10.3.1.12:5070/explorer.html

The port of 5070 statues:
```
$ curl -i "http://10.3.1.12:5070/webhdfs/v1/?op=LISTSTATUS"
HTTP/1.1 200 OK
Cache-Control: no-cache
Expires: Fri, 20 Mar 2020 08:24:20 GMT
Date: Fri, 20 Mar 2020 08:24:20 GMT
Pragma: no-cache
Expires: Fri, 20 Mar 2020 08:24:20 GMT
Date: Fri, 20 Mar 2020 08:24:20 GMT
Pragma: no-cache
Content-Type: application/json
X-FRAME-OPTIONS: SAMEORIGIN
Transfer-Encoding: chunked

{"FileStatuses":{"FileStatus":[
{"accessTime":0,"blockSize":0,"childrenNum":2,"fileId":16400,"group":"supergroup","length":0,"modificationTime":1578626572479,"owner":"root","pathSuffix":"Container","permission":"777","replication":0,"storagePolicy":0,"type":"DIRECTORY"},
{"accessTime":0,"blockSize":0,"childrenNum":79,"fileId":16399,"group":"supergroup","length":0,"modificationTime":1584692436570,"owner":"root","pathSuffix":"Launcher","permission":"755","replication":0,"storagePolicy":0,"type":"DIRECTORY"},
{"accessTime":0,"blockSize":0,"childrenNum":4,"fileId":16736,"group":"supergroup","length":0,"modificationTime":1582269363897,"owner":"dr.who","pathSuffix":"datasets","permission":"777","replication":0,"storagePolicy":0,"type":"DIRECTORY"},
{"accessTime":0,"blockSize":0,"childrenNum":4,"fileId":169490,"group":"supergroup","length":0,"modificationTime":1584330081066,"owner":"dr.who","pathSuffix":"out","permission":"755","replication":0,"storagePolicy":0,"type":"DIRECTORY"},
{"accessTime":0,"blockSize":0,"childrenNum":1,"fileId":16419,"group":"supergroup","length":0,"modificationTime":1576920533097,"owner":"root","pathSuffix":"sys","permission":"755","replication":0,"storagePolicy":0,"type":"DIRECTORY"},
{"accessTime":0,"blockSize":0,"childrenNum":1,"fileId":16393,"group":"supergroup","length":0,"modificationTime":1576919312644,"owner":"root","pathSuffix":"tmp","permission":"770","replication":0,"storagePolicy":0,"type":"DIRECTORY"},
{"accessTime":0,"blockSize":0,"childrenNum":2,"fileId":16386,"group":"supergroup","length":0,"modificationTime":1576919291641,"owner":"root","pathSuffix":"yarn","permission":"755","replication":0,"storagePolicy":0,"type":"DIRECTORY"}
]}}

```

but the port 50700 is not accessable:
```
$ curl -i "http://10.3.1.12:50700/webhdfs/v1/?op=LISTSTATUS"
curl: (7) Failed to connect to 10.3.1.12 port 50700: Connection refused
```

**OpenPAI Environment**:
- OpenPAI version: v0.17.0
- OS: Ubuntu 16.04.6 LTS
- Kernel: Linux ubuntu 4.4.0-142-generic
- Hardware: 
`machine-sku:
  GENERIC:
    mem: 250
    gpu:
      type: 2080ti
      count: 8
    cpu:
      vcore: 64
    os: ubuntu16.04`

**Comment by scarlett2018** [comment]
Adding 0.17 release manager to triage the issue.

**Comment by Binyang2014** [comment]
@shuangjiexu Can you show us the `pylon` deamonSet spec?
You can get it from `k8s-dashboard`
![image](https://user-images.githubusercontent.com/9415966/77172792-893b7e80-6af9-11ea-92e0-f8ed328d963e.png)

**Comment by Binyang2014** [comment]
@scarlett2018 This problem is related the `yarn` version PAI. What's our plan about `yarn` version. Seems we bring some regression issue when developing `pure k8s` version. And not fully tested the `yarn` version in the latest release.

**Comment by scarlett2018** [comment]
> @scarlett2018 This problem is related the `yarn` version PAI. What's our plan about `yarn` version. Seems we bring some regression issue when developing `pure k8s` version. And not fully tested the `yarn` version in the latest release.

if we can provide quick fix for yarn version, I'd prefer to have a fix PR to the yarn branch and release a 0.17.1 for a stable yarn version. if the change is big, we might have to suggest user to roll back to previous version. @fanyangCS  @sterowang to comment.

**Comment by fanyangCS** [comment]
There’s no benefit to upgrade to 0.17 for yarn version. I suggest users to stick to 0.14 if they prefer yarn version.

**Comment by scarlett2018** [comment]
> There’s no benefit to upgrade to 0.17 for yarn version. I suggest users to stick to 0.14 if they prefer yarn version.

 @fanyangCS @Binyang2014  - 
In this case, at least 2 things need to take to avoid user confusions:  
- update 0.17.0 release note with the above statement. Clarify the major changes in 0.17.0 is for the upcoming K8S version, ask user to wait for v-next version or stay with Yarn version
- share the v0.17 downgrade to v0.14 guidance to users who had already upgrade
comments?

**Comment by scarlett2018** [comment]
> > There’s no benefit to upgrade to 0.17 for yarn version. I suggest users to stick to 0.14 if they prefer yarn version.
> 
> @fanyangCS @Binyang2014 -
> In this case, at least 2 things need to take to avoid user confusions:
> 
> 1. update 0.17.0 release note with the above statement. Clarify the major changes in 0.17.0 is for the upcoming K8S version, ask user to wait for v-next version or stay with Yarn version
> 2. share the v0.17 downgrade to v0.14 guidance to users who had already upgrade
>   comments?

For #1, I updated the release note as below.
![image](https://user-images.githubusercontent.com/39592018/77510258-50105f00-6ea9-11ea-9464-1b25054a760f.png)

**Comment by scarlett2018** [comment]
> > > There’s no benefit to upgrade to 0.17 for yarn version. I suggest users to stick to 0.14 if they prefer yarn version.
> > 
> > 
> > @fanyangCS @Binyang2014 -
> > In this case, at least 2 things need to take to avoid user confusions:
> > 
> > 1. update 0.17.0 release note with the above statement. Clarify the major changes in 0.17.0 is for the upcoming K8S version, ask user to wait for v-next version or stay with Yarn version
> > 2. share the v0.17 downgrade to v0.14 guidance to users who had already upgrade
> >    comments?
> 
> For #1, I updated the release note as below.
> ![image](https://user-images.githubusercontent.com/39592018/77510258-50105f00-6ea9-11ea-9464-1b25054a760f.png)

@fanyangCS @Binyang2014 - do you think we should do something on #2 issue I mentioned.

**Comment by Binyang2014** [comment]
@scarlett2018 I don't think we need to provide a way for customer about downgrade v0.17 to v0.14. Since v0.17 is a **breaking change**. All job history will lost after upgrade to v0.17. If user want to downgrade to v0.14. The job history will also be lost, so he/she can clean the bed, then reinstall v0.14 to finish downgrade.

**Comment by scarlett2018** [comment]
> @scarlett2018 I don't think we need to provide a way for customer about downgrade v0.17 to v0.14. Since v0.17 is a **breaking change**. All job history will lost after upgrade to v0.17. If user want to downgrade to v0.14. The job history will also be lost, so he/she can clean the bed, then reinstall v0.14 to finish downgrade.

Sorry to hear that, but seems like the only approach. @shuangjiexu - do you have further questions?
