### ISSUE TITLE
User job failed due to ECC error and failed to retry

### ISSUE THREAD

**Issue by Binyang2014** [microsoft/pai#4314]
When nvidia GPU has ECC error. The user job running on it will failed.
Since the exit reason is `Segmentation fault`. 

According to errorSpec: https://github.com/microsoft/pai/blob/e30100559ae1b0cbdd827c21547984d27198d455/src/k8s-job-exit-spec/config/k8s-job-exit-spec.yaml#L1048-L1064

The jobs failed because of `Segmentation fault` will not retry.

Consider fix this problem by:
1. For runtime, when return exit code, combine the user log with running env. Then provide reasonable retry suggestion to FC.
2. Maybe we should monitor the device-health to avoid schedule job to such device.

**Comment by fanyangCS** [comment]
can we not treat segmentation fault as permanent failure?
