### ISSUE TITLE
P0 support CPU-only Nodes

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#4321]
Create a new issue to trace the progress of current support of cpu-only nodes and jobs, related issues are #4054

The main idea is to **create a special VC with cpu-only nodes (with a mocked gpu type)**, which involves work items as below

## P0 items
These items are necessary for `OpenPAI` to support cpu-only nodes and pure cpu jobs

- [ ] Figure out the best practices and document them
    - [x] create a special VC and add cpu-only nodes to it 
    - [ ] support cpu-only nodes in hived config generation
    - [ ] support above operation in quick-start
    - [x] (verify) submit to cpu-only jobs to this VC (with API / cli)
    - [ ] documentation
        - [ ] step by step guidance
        - [ ] quick start
- [ ] UI improvement
    - [ ] front end could identify a VC as cpu-only (via *REST API* or *by VC name* as workaround)
    - [ ] hide GPU options when VC selected to the cpu-only one (auto insert a gpu number according to number of cpu cores and memory)
    - [ ] resource display UI needs to be updated for the cpu-only VC
        - [ ] rest server may need update its resource calculation for cpu-only VC

## Backlog items
Here is some discussions about future items such as how to efficiently utilize the GPUs by cpu-gpu mixed jobs, which could let some workers runs on pure cpu nodes to relax the requirement of GPU. 

It cannot support CPU-GPU-mixed jobs, since one job can only be scheduled to one VC. One solution is submitting two jobs. One is GPU-only and the other is CPU-only. However:
    - The two jobs have no convenient ways to communicate.
    - The separate scheduling of the two jobs is not GANG schedeling, which will cause resource starvation.

----
here is the raw content

>  - It cannot support CPU-GPU-mixed jobs, since one job can only be scheduled to one VC. One solution is submitting two jobs. One is GPU-only and the other is CPU-only. However:
    - The two jobs have no convenient ways to communicate.
    - The separate scheduling of the two jobs is not GANG schedeling, which will cause resource starvation.
 > - Front-end (including rest-server, and webportal) has no ways to figure out which VC is CPU-only. This will cause:
    - Confusing GPU number on webportal.
    - Users cannot submit job with 0 GPU. They must fill in a fake GPU number.
> - (need check) installation for CPU-only nodes

**Comment by fanyangCS** [comment]
For the heterogeneous computing, I would prefer not to making things unnecessarily complicated. 

To set up a VC that is dedicated for a CPU only servers is not a workaround, it is a recommended solution. It is possible that a VC contains different type of nodes, including some CPU nodes. But it would make the use of them a bit complicated. 

Currently, for a gang scheduled job, we do not support it running on different types of nodes. Please elaborate the usage scenario so we can understand why there exists such a need. 

For a job requires no gang-scheduling, it does not has such a constraint and can run on different types of nodes.

**Comment by hzy46** [comment]
> For the heterogeneous computing, I would prefer not to making things unnecessarily complicated.
> 
> To set up a VC that is dedicated for a CPU only servers is not a workaround, it is a recommended solution. It is possible that a VC contains different type of nodes, including some CPU nodes. But it would make the use of them a bit complicated.
> 
> Currently, for a gang scheduled job, we do not support it running on different types of nodes. Please elaborate the usage scenario so we can understand why there exists such a need.
> 
> For a job requires no gang-scheduling, it does not has such a constraint and can run on different types of nodes.

I think demonds for gang-scheduling on different types exist, for example:

1. An imagenet model training job can take 8 GPU for training. A validation job usually runs on 16 CPU vCores periodically to calculate model accuracy.

2. A face recognition model can take a large scale of training images. If preprocessing of these images are done by GPU, the utilization of GPU will be low. Thus, we can put data preprocess on CPU to maximize GPU efficiency.

In my opinion, GPU nodes are expensive resource. In a machine learning job, some in-expensive operations, such as data preprocessing, logging, model validation can take place on CPU nodes. This can help users make best use of both GPU and CPU resources.

**Comment by fanyangCS** [comment]
Why are these two examples a gang-scheduling problem? 

For the first example, isn't reserving two types of node in a gang-scheduled manner a more expensive way to reserve resources? You are wasting CPU nodes when using GPUs, and wasting GPU nodes when using CPUs.
 
For the second example, do not forget the GPU nodes also have CPUs, which is exactly what the current practice: pipelining CPU and GPU workload to maximize system utilization. I don't see the necessity of using CPU node and GPU node in tandem. And again, scheduling the two types of nodes in a gang-scheduled manner is a waste of resource.

**Comment by hzy46** [comment]
> Why are these two examples a gang-scheduling problem?
> 
> For the first example, isn't reserving two types of node in a gang-scheduled manner a more expensive way to reserve resources? You are wasting CPU nodes when using GPUs, and wasting GPU nodes when using CPUs.
> 
> For the second example, do not forget the GPU nodes also have CPUs, which is exactly what the current practice does: pipelining CPU and GPU workload to maximize system utilization. I don't see the necessity of using CPU node and GPU node in tandem. And again, scheduling the two types of nodes in a gang-scheduled manner is a waste of resource.

For the first example, as I mentioned, GPU resource is more expensive. Thus, wasting GPU resource is not acceptable, but wasting some CPU resource is OK. The first example runs a GPU training process and a CPU testing process **parallelly**. The GPU training process never stops. It keeps training and produce some model checkpoints periodically. The CPU testing process check if there is a new model checkpoint: if there does, it will do the testing job. We only waste some CPU resource when there is no new checkpoint available, the GPU resource is not wasted. Training on GPU, and testing on CPU is a common practice when testing on GPU is expensive for the model trainer.

For the second example, the job recognition one. We can put the image processing and traing on GPU node, using the CPU resource altogether. It is convenient in most cases. However, when we optimize the training speed, two kinds of speed are taken into consideration:

 **1. The speed of image IO and preprocessing.  
   2. The speed of model forward and back propagation.** 

Usually, 1 is done on CPU and 2 is done on GPU. The common situation is speed 2 is slower than speed 1. In such situation, doing data processing on GPU node is OK, since the bottleneck of the speed is the GPU training speed.

However, in some cases, speed 2 is faster than speed 1. This would happen when the GPU is powerful or the model is simple. One realistic example is face recognition model traing, where the training images are more than 1,000,000 but the model could be a simple ResNet. We can then put 1 on a CPU node, which has powerful CPUs and optimized disk/network IO for data preprocessing. It helps save resource to separate speed 1 and speed 2.  

Besides the 2 examples, another example could be some sparse model in the recommendation system, such as DeepFM. This kind of model are faster trained on CPU than on GPU. If DeepFM wants to use some image features, the best practice is to use a less powerful GPU for image feature transformation and the whole model training takes place on CPU.

**Comment by fanyangCS** [comment]
I am not saying a ML job that mixes the use CPU and GPU is not possible. I am saying these workloads better use the CPUs in the GPU nodes to optimize their workloads, instead of using dedicated CPU nodes to do this. And it is weird to co-deploy CPU nodes together with GPU node in the same cluster. 

That being said, I want to clarify the following points. 
1) OpenPAI does support the co-deployment of CPU and GPU nodes
2) OpenPAI does support a VC containing multiple types of nodes, including CPU nodes
3) An OpenPAI job does support running on different type of nodes. It does support running few containers in CPU nodes and other containers in  GPU nodes, as long as you specify them in different task roles. And they do have a way to communicate with each other, with the environment variables.

**Comment by hzy46** [comment]
> I am not saying a ML job that mixes the use CPU and GPU is not possible. I am saying these workloads better use the CPUs in the GPU nodes to optimize their workloads, instead of using dedicated CPU nodes to do this. And it is weird to co-deploy CPU nodes together with GPU node in the same cluster.
> 
> That being said, I want to clarify the following points.
> 
> 1. OpenPAI does support the co-deployment of CPU and GPU nodes
> 2. OpenPAI does support a VC containing multiple types of nodes, including CPU nodes
> 3. An OpenPAI job does support running on different type of nodes. It does support running few containers in CPU nodes and other containers in  GPU nodes, as long as you specify them in different task roles. And they do have a way to communicate with each other, with the help of environment variables.

As far as I know, **3** is impossible because:

  1.  All task roles must use the same virtual cluster. Thus, the virtual cluster we use must have both CPU nodes and GPU nodes.
  2. In that cluster, CPU nodes in hivedscheduler act as a "fake GPU node". In other words, they are also valid GPU nodes. If I want task role A using GPU, and task role B using CPU, I cannot express this need in the job config, since it only let me fill in GPU number. There is possibility that task role A is allocated to the "fake GPU node", and task role B is allocated to real GPU node.

**Comment by mydmdm** [comment]
@fanyangCS @hzy46 I edited this issue (the origin is move to bottom) to focus on the high priority items that would be figured out in the following release. 

For the heterogeneous computing or jobs mixed with cpu/gpu taskroles (or actually use multi-types of gpus in one job), it is valuable discussions, but we need more thinking and digging of the scenarios, which really go out of this issue.

**Comment by abuccts** [comment]
To fully support cpu type in hived scheduler, here're the work items in rest server:
- [ ] change `gpuTypes` schema in hived config
- [ ] update gpu validation for cpu type
- [ ] update hived request generation
- [ ] update vc metrics for cpu type

**Comment by scarlett2018** [comment]
P0 work done, left major work: UI for CPU only scenario.
