### ISSUE TITLE
Show Container NodeName on Job detail page

### ISSUE THREAD

**Issue by yqwang-ms** [microsoft/pai#4323]
**What would you like to be added**:
Show Container NodeName on Job detail page.

**Why is this needed**:
Currently, we only show Container IP on the page, however, all backend components are using the NodeName to query and locate the node info uniquly.

And there is no easy way to find an IP's corresponding NodeName, so we are very hard to debug node related issues from the UI.

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/32826762/77396934-9f8a5880-6ddf-11ea-9fe6-b335b7bbe861.png)
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/32826762/77396931-9d27fe80-6ddf-11ea-82a0-44980d683559.png)

**Without this feature, how does the current module work**:

**Components that may involve changes**:
We already exposed the podNodeName

```
            {
              "index": 4,
              "startTime": "2020-03-24T03:45:41Z",
              "completionTime": null,
              "state": "AttemptCompleted",
              "transitionTime": "2020-03-24T05:55:10Z",
              "retryPolicyStatus": {
                "totalRetriedCount": 2308,
                "accountableRetriedCount": 0,
                "retryDelaySec": 0
              },
              "attemptStatus": {
                "id": 2308,
                "startTime": "2020-03-24T05:55:07Z",
                "runTime": null,
                "completionTime": "2020-03-24T05:55:10Z",
                "instanceUID": "2308_f1af033f-d15f-4d3e-a941-65e6d6b50868",
                "podName": "2460771fd492ad76654a6339765644cd-taskrole-4",
                "podUID": "f1af033f-d15f-4d3e-a941-65e6d6b50868",
                "podNodeName": "k80lp55ee00002t",
                "podIP": "10.1.4.8",
                "podHostIP": "10.1.4.8",
```

**Comment by fanyangCS** [comment]
closed and track in #4649
