### ISSUE TITLE
The description for X-axis is not clear and not visual optimized

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#4327]
there are user feedback, that the current X-axis is confusing. 

We could add one link to describe the chart and make the X-axis label simple.
i.e. description: 
The chart is to show the distribution of nodes of available GPU in nodes. 
X axis represents nodes where the number of available GPUs is X
Y axis represents the amount of the nodes

X-axis' label can be simplified to 1, 2, 3

When there are no nodes with available GPU, we should not keep the chart empty, which seems weird, we should add one nodes there saying: "No node has a GPU available.". 

![image](https://user-images.githubusercontent.com/39592018/77528113-5104b900-6ec8-11ea-8bc2-bdd6b568889c.png)

**Comment by yangou1988** [comment]
![image](https://user-images.githubusercontent.com/44491713/79124405-d3e5a900-7dce-11ea-9a5c-589edf43875d.png)
Default status

![image](https://user-images.githubusercontent.com/44491713/79124464-ed86f080-7dce-11ea-8919-f6d436272838.png)
Click info icon - tooltips description

![image](https://user-images.githubusercontent.com/44491713/79124482-f972b280-7dce-11ea-9781-fccd263f0df9.png)
No nodes with available GPU status

**Comment by debuggy** [comment]
see #4386

![image](https://user-images.githubusercontent.com/8444268/79187483-ee5f6700-7e4e-11ea-8946-f0d3396d3834.png)
