### ISSUE TITLE
rest-server reports: fetch job status failed: podCompletionStatus.containers is not iterable

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#4330]
How to reproduce:

1. Setup a hived vc which has more cpu capacity than ground truth. For example, you have a node with 10 CPUs, but configure the hived as it has 20 CPUs.
2. Submit a job to that vc, which takes all CPUs of the vc capacity.

Then try to access the submitted job:

![image](https://user-images.githubusercontent.com/7499023/77626450-56253f00-6f80-11ea-90bd-c2596cd8e924.png)

It cannot be stopped:

![image](https://user-images.githubusercontent.com/7499023/77626508-6fc68680-6f80-11ea-9930-594d4524a01b.png)

**Comment by abuccts** [comment]
Caused in extracting runtime output @Binyang2014 
https://github.com/microsoft/pai/blob/f8365cd1d38b0ea3d9cc68e856599f2e79c5a498/src/rest-server/src/models/v2/job/k8s.js#L1095-L1101
