### ISSUE TITLE
hivedscheduler is prone to misconfig due to daemon Pods, such as weave net and nginx proxy

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#4331]
After PAI is deployed, run `kubectl describe <worker-node>`:

![image](https://user-images.githubusercontent.com/7499023/77627327-b23c9300-6f81-11ea-8bf1-98f2afc4acec.png)

This will cause a mis-configuration in hivedscheduler.

**Comment by yqwang-ms** [comment]
Operator need to pay attention to 

>  1. Using `kubectl describe nodes` to check if these `K80` nodes have nearly the same ([Allocatable Resources](https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources) - [All Daemon Pods Requests, such as Pods for Device Plugin,  Network Plugin, etc](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#resource-requests-and-limits-of-pod-and-container)), especially for gpu, cpu, memory. If not, please fix it. Assume the aligned minimal resources are: 4 gpus, 23 cpus, and 219GB memory.


Which is mentioned in doc:
https://github.com/microsoft/hivedscheduler/blob/master/doc/user-manual.md#config-quickstart

**Comment by hzy46** [comment]
> Operator need to pay attention when config Hived to avoid this misconfig:
> 
> > 1. Using `kubectl describe nodes` to check if these `K80` nodes have nearly the same ([Allocatable Resources](https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources) - [All Daemon Pods Requests, such as Pods for Device Plugin,  Network Plugin, etc](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#resource-requests-and-limits-of-pod-and-container)), especially for gpu, cpu, memory. If not, please fix it. Assume the aligned minimal resources are: 4 gpus, 23 cpus, and 219GB memory.
> 
> Which is mentioned in doc:
> https://github.com/microsoft/hivedscheduler/blob/master/doc/user-manual.md#config-quickstart

Could hivedscheduler do a pre-check to avoid mis-configuration? Configuring up hivedscheduler manually is error-prone.

**Comment by yqwang-ms** [comment]
Yeap. But anyway, it is not just precheck, we need to always check in case this "Allocatable Resources - All Daemon Pods Requests, such as Pods for Device Plugin, Network Plugin, etc" is changed during Hived running. 
Operator ensures this, is current the easiest apporach.
Will consider how to auto it later.

**Comment by hzy46** [comment]
> Yeap. But anyway, it is not just precheck, we need to always check in case this "Allocatable Resources - All Daemon Pods Requests, such as Pods for Device Plugin, Network Plugin, etc" is changed during Hived running.
> Operator ensures this, is current the easiest apporach.
> Will consider how to auto it later.

Yes, exactly.

**Comment by yqwang-ms** [comment]
Resolved by https://github.com/microsoft/pai/pull/4855
