### ISSUE TITLE
Same commands fail on 0.17 succeed on 0.14

### ISSUE THREAD

**Issue by chuangxinyuan** [microsoft/pai#4339]
**Organization Name**: SHAIIC

**Short summary about the issue/question**:
We are evaluting the PAI environment variable PAI_PORT_LIST_$taskRole_$taskIndex_$portType, so we made a simple test, run the following commands:

PORT=$PAI_PORT_LIST_taskrole_0_jupyterniu
echo $PORT
echo "aaaa"

But we get error on PAI 0.17, the error msg is as the following:
However, the same commands on PAI 0.14 succeed. 

--------------------
[Exit Trigger Info]

ExitTriggerMessage: FailedTaskCount 1 has reached MinFailedTaskCount 1 in TaskRole [taskrole]
ExitTriggerTaskRole: taskrole
ExitTriggerTaskIndex: 0
UserExitCode: 127

--------------------------------------------------------------------------------

[Exit Spec]

code: 255
phrase: CONTAINER_RUNTIME_UNKNOWN_FAILURE
issuer: PAI_RUNTIME
causer: UNKNOWN
type: UNKNOWN_FAILURE
stage: COMPLETING
behavior: UNKNOWN
reaction: RETRY_TO_MAX
reason: Container failed but the failure cannot be recognized by PAI Runtime
repro:
  - User program directly exits with exitcode 1
solution:
  - Check container log and find root cause
  - Wait result from next retry

--------------------------------------------------------------------------------

[Exit Diagnostics]

[2020-03-29 13:55:40.988]Exception from container-launch: 
ExitCodeException exitCode=255: 
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:998)
	at org.apache.hadoop.util.Shell.run(Shell.java:884)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:1216)
	at org.apache.hadoop.yarn.server.nodemanager.DockerContainerExecutor.launchContainer(DockerContainerExecutor.java:312)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.launchContainer(ContainerLaunch.java:443)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:294)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:92)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[2020-03-29 13:55:40.988]
[2020-03-29 13:55:40.989]Container exited with a non-zero exit code 255. Last 40960 bytes of runtime.pai.agg.error :
[PAI_RUNTIME_ERROR_START]
exitcode: 255
trigger: originalUserExitCode
reason: |
  User process exited with code: 127
solution: |
  
originalUserExitCode: 127
dockerStatus: 
caughtSignal: 
caughtException:
matchedUserLogString:
errorLogs:
  user: |
    /pai/bootstrap/docker_bootstrap.sh: line 213: aaaa: command not found
  runtime: |
    1585490140 ERROR REASON "User process exited with code: 127"
    WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
    1585490140 INFO USER_EXIT_CODE 127
  diskCleaner: |
[PAI_RUNTIME_ERROR_END]

[2020-03-29 13:55:40.989]
--------------------

**Brief what process you are following**:

**How to reproduce it**:
Job YAML

protocolVersion: 2
name: admin_ae5f6968
type: job
jobRetryCount: 0
prerequisites:
  - type: dockerimage
    uri: tomcat
    name: docker_image_0
taskRoles:
  taskrole:
    instances: 1
    completion:
      minFailedInstances: 1
      minSucceededInstances: -1
    taskRetryCount: 0
    dockerImage: docker_image_0
    resourcePerInstance:
      gpu: 0
      cpu: 2
      memoryMB: 4096
      ports:
        jupyterniu: 1
    commands:
      - PORT=$PAI_PORT_LIST_taskrole_0_jupyterniu
      - echo $PORT
      - echo "aaaa"
defaults:
  virtualCluster: default

**OpenPAI Environment**: 
- OpenPAI version:0.17
- Cloud provider or hardware configuration: Azure 
- OS (e.g. from /etc/os-release):ubuntu16.04
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):NC6S_v3 (6 VCPU, 1GPU, 112GMEM)
- Others:

**Anything else we need to know**:

**Comment by chuangxinyuan** [comment]
Add more:

The output on PAI0.14 is as the following which is exactly what we excpect

[INFO] USER COMMAND START

15872
aaaaa

[INFO] USER COMMAND END

**Comment by mydmdm** [comment]
I have a quick test and the commands work in deployment of latest master

```
taskRoles:
  taskrole:
    instances: 1
    completion:
      minFailedInstances: 1
      minSucceededInstances: -1
    taskRetryCount: 0
    dockerImage: docker_image_0
    resourcePerInstance:
      gpu: 1
      cpu: 4
      memoryMB: 8192
      ports:
        jupyter: 1
    commands:
      - PORT=$PAI_PORT_LIST_taskrole_0_jupyter
      - echo $PORT
      - echo "hello world"
```
here is the output
```
28790
hello world
 ```

**Comment by Binyang2014** [comment]
@chuangxinyuan, please make sure you are using `k8s` version not `yarn` version.
Please refer :https://github.com/microsoft/pai/issues/4308#issuecomment-601740810. If you are using yarn version, we suggest stick to v0.14.0 and not upgrade to v0.17.0.

For your problem, maybe same with: #4306

**Comment by mydmdm** [comment]
Or we'd make a release soon that would be more stable and recommend

**Comment by chuangxinyuan** [comment]
Thanks for the quick reply, we used workround in  #4306, the job staus showed success, but no results shown in the stdout. Anyway, we will stick to 0.14, and wait for the next new-era version :)

**Comment by scarlett2018** [comment]
Closing the issue as the work round fix the problem temporarily. please stay tune with our upcoming release.
