### ISSUE TITLE
How to use storage manager after installation

### ISSUE THREAD

**Issue by mtzfei** [microsoft/pai#4354]
**Organization Name**:

How to use storage manager after installation
![11](https://user-images.githubusercontent.com/60864045/78213857-63917a80-74e6-11ea-9f47-aa5280fd04ab.PNG)

**Short summary about the issue/question**:
I want to use smba storage. After the storage manager is installed, how should I use it
**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:v0.17.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by Binyang2014** [comment]
Storage-manager is for `k8s ` version
Seems you use yarn version. Please refer to this comments: https://github.com/microsoft/pai/issues/4308#issuecomment-601740810. If you use `yarn` version, please stick to `v0.14.0`

If you want to upgrade to k8s version. Please refer to https://github.com/microsoft/pai/blob/master/contrib/kubespray/readme.md.

But it's a pre-release. And will bring **breaking change**

**Comment by scarlett2018** [comment]
Closing the issue as the question had been answered, thanks @mtzfei and @Binyang2014
