### ISSUE TITLE
kubectl get pod display not full

### ISSUE THREAD

**Issue by shanying2017** [microsoft/pai#4357]
release v0.17.0
openpai deploy successfully through dev-box, but when use kubectl ,it display only NAME and AGE
root@dev-box:/pai# kubectl get pod -n default
NAME                                    AGE
batch-job-hadoop-mfcbq                  4m6s
cleaner-ds-g88s4                        2m31s
cleaner-ds-wn6pp                        2m31s
cleaner-ds-xl68s                        2m31s
drivers-one-shot-97pk6                  7m1s
drivers-one-shot-cwh2f                  7m1s
drivers-one-shot-fmsjj                  7m1s
drivers-one-shot-vhsgv                  7m1s
etcd-server-192.168.24.39               76m
grafana-6c4f496f58-9fdmm                7m22s
hadoop-data-node-ds-7qpvz               5m19s
hadoop-data-node-ds-dd4sr               5m19s
hadoop-data-node-ds-z2wpb               5m19s
hadoop-jobhistory-service-8k9rm         4m27s
hadoop-name-node-ds-5s4p5               5m39s
hadoop-node-manager-ds-7t4kw            4m37s
hadoop-node-manager-ds-825j4            4m37s
hadoop-node-manager-ds-bhc8d            4m37s
hadoop-resource-manager-ds-nqcxh        4m58s
job-exporter-2sgpl                      6m10s
job-exporter-4gk5f                      6m10s
job-exporter-k8228                      6m10s
job-exporter-rxzxz                      6m10s
node-exporter-28x4c                     3m12s
node-exporter-kpxb9                     3m12s
node-exporter-tjrcz                     3m12s
node-exporter-vx622                     3m12s
prometheus-deployment-6896c68bd-c6b7x   9m33s
pylon-ds-chxvv                          7m11s
rest-server-ds-m7t2g                    3m53s
watchdog-57df75577d-6rhvv               3m42s
webportal-ds-4ltdl                      2m41s
yarn-frameworklauncher-ds-b5wnh         4m6s
zookeeper-ds-pwlzw                      6m

how can I get it normally

**Comment by fanyangCS** [comment]
please use 0.14 as 0.17 is an internal release. Once ready, we will make 0.18 a public version.

**Comment by shanying2017** [comment]
thanks，I‘m waiting for the 0.18, how long will it be ready
