### ISSUE TITLE
nvidia-smi not found

### ISSUE THREAD

**Issue by dawnos** [microsoft/pai#4359]
**Organization Name**: Zhejiang University

**Short summary about the issue/question**: nvidia-smi not found in docker `openpai/drivers-418.56`

**Brief what process you are following**:

I follow [Single Box Deploy](https://github.com/microsoft/pai/blob/master/docs/pai-management/doc/single-box.md#c-step-1) step by step, and everything seems OK except step 6: Validate deployment. In [Check Drivers version](https://github.com/microsoft/pai/blob/master/docs/pai-management/doc/validate-deployment.md#12-check-drivers-version-), In get the following output:

> ubuntu@server3:~$ sudo docker ps | grep driver
> 50dd3dbe948c  openpai/drivers-418.56 "bash -x ./install-a…"   34 minutes ago      Up 34 minutes  k8s_nvidia-drivers_drivers-one-shot-6jn9z_default_584dadad-74f6-11ea-80bc-ac1f6ba1bfb2_0
> 26e55525e86f        openpai/pause-amd64:3.0              "/pause"                 34 minutes ago      Up 34 minutes                                                                            k8s_POD_drivers-one-shot-6jn9z_default_584dadad-74f6-11ea-80bc-ac1f6ba1bfb2_0
 
When I go into the docker, I get:
> ubuntu@server3:\~$ sudo docker exec -it 50dd3dbe948c /bin/bash
> root@server3:\~/drivers# nvidia-smi
> bash: nvidia-smi: command not found

 It is obvious that nvidia-smi is not found. I CAN find it in `~/drivers/NVIDIA-Linux-x86_64-418.56`, and by running nvidia-smi under this directory, I can get the correct output.

My question is: Does it matter?

**How to reproduce it**: Not clear.

**OpenPAI Environment**:
- OpenPAI version: 0.17.0
- Cloud provider or hardware configuration: See bellow
- OS (e.g. from /etc/os-release): Ubuntu 16.04.6 LTS
- Kernel (e.g. `uname -a`): Linux csc104-server3 4.15.0-94-generic #95~16.04.1-Ubuntu SMP Wed Mar 25 15:25:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Hardware (e.g. core number, memory size, storage size, GPU type etc.): 48 cores, 126G mem, 468G SSD, 4x2080Ti
- Others: No

**Anything else we need to know**: No

**Comment by abuccts** [comment]
sorry for the late response.

the bin path for `nvidia-smi` is not added to `PATH` env in driver service pod, but it should be in `PATH` inside pods of other services which need gpu (like hadoop rm and exporter) and job pods.

so it does not matter.
