### ISSUE TITLE
Cannot fetch TTY window size in container

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#4369]
Some deep-learning programmers like to create a "progress bar" during their training process, which needs a tty environment. It appears in many repos, such as:

  - [pytorch-cifar](https://github.com/kuangliu/pytorch-cifar/blob/bf78d3b8b358c4be7a25f9f9438c842d837801fd/utils.py#L45)
  - [AMC ](https://github.com/mit-han-lab/amc/blob/291c40601eff8949eed7aafcf9338d6f34d7fe4d/lib/utils.py#L172)
  - [wiki2bio](https://github.com/tyliupku/wiki2bio/blob/421a002dead47d37280240a9c6a114eb4d3e437d/util.py#L9)

These codes will fail in PAI because PAI doesn't provide a tty environment:
![image](https://user-images.githubusercontent.com/7499023/78644562-a25d7100-78e8-11ea-81b3-7985c2aa2fbd.png)

**Comment by abuccts** [comment]
1. `stty` cannot get size because standard streams (stdin/stdout) are not connected to a terminal.

    This is the fact in non-interactive Docker which runs on PAI, and it also happens in other cases like test pipeline or some IDE.

2. It's better to handle errors in the above code, and it is also os/platform dependent.

3. A pythonic way is to use built-in `get_terminal_size`:

    ```python
    import shutil
    cols, lines = shutil.get_terminal_size()
    ```

    You will search 9k+ occurrences for [`os.popen('stty size', 'r')`](https://github.com/search?l=Python&q=os.popen%28%27stty+size%27%2C+%27r%27%29&type=Code) on GitHub, but 233k+ occurrences for [`shutil.get_terminal_size`](https://github.com/search?l=Python&q=shutil.get_terminal_size&type=Code).

**Comment by hzy46** [comment]
> 1. `stty` cannot get size because standard streams (stdin/stdout) are not connected to a terminal.
>    This is the fact in non-interactive Docker which runs on PAI, and it also happens in other cases like test pipeline or some IDE.
> 2. It's better to handle errors in the above code, and it is also os/platform dependent.
> 3. A pythonic way is to use built-in `get_terminal_size`:
>    ```python
>    import shutil
>    cols, lines = shutil.get_terminal_size()
>    ```
>    
>    
>    You will search 9k+ occurrences for [`os.popen('stty size', 'r')`](https://github.com/search?l=Python&q=os.popen%28%27stty+size%27%2C+%27r%27%29&type=Code) on GitHub, but 233k+ occurrences for [`shutil.get_terminal_size`](https://github.com/search?l=Python&q=shutil.get_terminal_size&type=Code).

Thanks for the detailed explanation!

**Comment by fanyangCS** [comment]
close this issue as there is a workaround. Feel free to reopen if running into further issues.
