### ISSUE TITLE
ERROR! the playbook: copy-daemon-openpai-default-runtime.yml could not be found

### ISSUE THREAD

**Issue by mtzfei** [microsoft/pai#4372]
**Organization Name**:

**Short summary about the issue/question**:
When I run ”/bin/bash quick-start-kubespray.sh -m example/master.csv -w example/worker.csv -c example/config.yml“，an error occurred
ERROR! the playbook: copy-daemon-openpai-default-runtime.yml could not be found
![111](https://user-images.githubusercontent.com/60864045/78743338-ec9a2d00-7990-11ea-9a3d-72e8fbb4be8d.PNG)

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:v0.17.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by ydye** [comment]
Please paste the content of the file ```example/config.yml```

**Comment by mtzfei** [comment]
> 请粘贴文件内容 `example/config.yml`

![123](https://user-images.githubusercontent.com/60864045/79083701-71ef5a00-7d62-11ea-8be9-b4eadf3e3d80.PNG)

**Comment by ydye** [comment]
```
branch-name: pai-0.17.y
```
