### ISSUE TITLE
how to upload source to HDFS of v2job? [v0.17.0]

### ISSUE THREAD

**Issue by MaPing01** [microsoft/pai#4385]
how to upload source to HDFS of v2job?

**Comment by fanyangCS** [comment]
if you are using YARN version, please stick to v0.14. If you are using k8s version, and deploy a separate HDFS, you need to upload the source and download the source on your own. Because in this case HDFS is not managed by OpenPAI.

**Comment by MaPing01** [comment]
thanks for your answer,i uploaded the source to HDFS on my own,but can i konw hou to use the  HDFS source folder in the job?seems i can't find my source folder when i submit v2 job,thanks a lot.

**Comment by MaPing01** [comment]
> if you are using YARN version, please stick to v0.14. If you are using k8s version, and deploy a separate HDFS, you need to upload the source and download the source on your own. Because in this case HDFS is not managed by OpenPAI.

thanks for your answer,i uploaded the source to HDFS on my own,but can i konw hou to use the HDFS source folder in the job?seems i can't find my source folder when i submit v2 job, as the photo i uploaded ,my source folder is NER,thanks a lot.
![批注 2020-04-16 094824](https://user-images.githubusercontent.com/39873427/79405631-884a1f80-7fc7-11ea-9411-a35886e60cb9.png)

**Comment by MaPing01** [comment]
if there have anyone to help me.....?

**Comment by debuggy** [comment]
Hi @MaPing01 , please see if #4417 solves your problem. If not, you could leave comments there.
