### ISSUE TITLE
Cannot submit jobs with very long job name

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#4391]
How to reproduce:

1. Submit a job with a very long job name.

2. The job will keep in `WAITING` status.

3. `kubectl describe po` returns:

![image](https://user-images.githubusercontent.com/7499023/79417540-f6510f80-7fe4-11ea-93e2-bbd34d085a3b.png)

![image](https://user-images.githubusercontent.com/7499023/79417515-e76a5d00-7fe4-11ea-8d6c-6ce500016f54.png)

**Comment by mydmdm** [comment]
we should clarify the constraint in the document
