### ISSUE TITLE
Weave net cause MPI job hang

### ISSUE THREAD

**Issue by Binyang2014** [microsoft/pai#4394]
When deploy bed with weave net CNI.  Some node failed to connect each other through weave net allocated IP. This will cause MPI job hang due to job select weave-net interface to connect each other (though we use host-network to start pod).

Consider remove weave-net and use Azure CNI or use AKS directly, when deploy bed in Azure.
For on-premise, maybe suggestion other CNI when deploy k8s with kubespray

**Comment by fanyangCS** [comment]
if the job uses the correct NIC name (the name of the host NIC), the MPI job can run successfully, right?

**Comment by Binyang2014** [comment]
> if the job uses the correct NIC name (the name of the host NIC), the MPI job can run successfully, right?

I think job can set `--mca btl_tcp_if_include eth0` to avoid such issue. But I don't test it in the bed. Currently, just removed weave-net in `ne` bed and provide a doc to show the steps to remove weave-net: https://github.com/microsoft/pai/blob/master/contrib/kubespray/doc/faqs-and-troubleshooting.md#faqs

**Comment by fanyangCS** [comment]
This is a problem not limited to weave-net. 

It is a common issue that you need to choose the right NIC to do the MPI when you have multiple NICs. 

In a cluster with InfiniBand (IB), it is typical that a host has more than one NIC. the cluster user need to be informed which NIC has IB capacity.

**Comment by Binyang2014** [comment]
Thanks, got it. But weave-net may still has some issue. It may cause network partition.

During the deploy, the vm get the ip allocated by weave-net. 
For example VM1: 10.206.80.1, VM2: 10.204.13.5, VM3: 10.205.14.5. I found VM2 can ping VM3 through weave-net ip. But VM2 and VM3 can not ping VM1. VM1 is unreachable by other VMs though weave-net ip. (If I use host IP, don't have such issue)

And I notice if VM2 and VM3 are reachable though weave-net IP. The MPI job can run on VM2 and VM3 successfully. Otherwise the MPI job will hang.

So the problem is weave-net may cause network partition.

**Comment by fanyangCS** [comment]
related to https://github.com/microsoft/pai/issues/4622 and https://github.com/microsoft/pai/issues/4603
fixed by https://github.com/microsoft/pai/pull/4672
