### ISSUE TITLE
Job cifar-10 failed: ModuleNotFoundError: No module named 'contextlib2'

### ISSUE THREAD

**Issue by victorming** [microsoft/pai#4408]
**Organization Name**: CloudEdu智学云

**Short summary about the issue/question**:
Job Cifar-10 failed: ModuleNotFoundError: No module named 'contextlib2'
**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**: 
- OpenPAI version: v0.14.0
- Cloud provider or hardware configuration: GTX1080Ti
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`): 
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:
Job Config:protocolVersion: 2
name: admin_cifar-10_202004171415
type: job
jobRetryCount: 0
prerequisites:
  - type: dockerimage
    uri: 'ufoym/deepo:tensorflow-py36-cu90'
    name: docker_image_0
taskRoles:
  Task_role_1:
    instances: 1
    completion:
      minFailedInstances: 1
      minSucceededInstances: 1
    dockerImage: docker_image_0
    resourcePerInstance:
      gpu: 1
      cpu: 4
      memoryMB: 8192
    commands:
      - apt update
      - apt install -y git
      - 'git clone https://github.com/tensorflow/models'
      - cd models/research/slim
      - >-
        python download_and_convert_data.py --dataset_name=cifar10
        --dataset_dir=/tmp/data
      - >-
        python train_image_classifier.py --dataset_name=cifar10
        --dataset_dir=/tmp/data --max_number_of_steps=100
    taskRetryCount: 0
defaults:
  virtualCluster: default

Job Error:
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 1.)
debconf: falling back to frontend: Readline
Cloning into 'models'...
Traceback (most recent call last):
  File "download_and_convert_data.py", line 47, in <module>
    from datasets import download_and_convert_visualwakewords
  File "/models/research/slim/datasets/download_and_convert_visualwakewords.py", line 81, in <module>
    from datasets import download_and_convert_visualwakewords_lib
  File "/models/research/slim/datasets/download_and_convert_visualwakewords_lib.py", line 31, in <module>
    import contextlib2
ModuleNotFoundError: No module named 'contextlib2'

**Comment by hzy46** [comment]
pls use docker `openpai/standard:python_3.6-tensorflow_1.15.0-gpu`

**Comment by scarlett2018** [comment]
> pls use docker `openpai/standard:python_3.6-tensorflow_1.15.0-gpu`

Hi @victorming had you tried this out? thanks.

**Comment by fanyangCS** [comment]
closed as no further response.
