### ISSUE TITLE
Marking a node as unschedulable if it has GPU ECC error

### ISSUE THREAD

**Issue by yqwang-ms** [microsoft/pai#4409]
**What would you like to be added**:
Marking a node as unschedulable if it has GPU ECC error
https://kubernetes.io/docs/concepts/architecture/nodes/#manual-node-administration

**Why is this needed**:

**Without this feature, how does the current module work**:

**Components that may involve changes**:

**Comment by fanyangCS** [comment]
relate to https://github.com/microsoft/pai/issues/4604 and https://github.com/microsoft/pai/issues/4344

**Comment by fanyangCS** [comment]
closed and track in https://github.com/microsoft/pai/issues/4604.
