### ISSUE TITLE
[AAD Integration UX] User XX is not in configurated groups.

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#4415]
Currently (0.18), when user is not able to access OpenPAI, the error message is "User XX is not in configurated groups.". 

For users, they can only contact Admin to add them to a group, but as a user, they don't know which group to be added.

For Admin, they are only able to get the request through email (ad-hoc) request. And they don't know which group this user should below to as well.

Ideally,  the message should suggest the user which group they should request to join, and the team lead of the VC should able to approve the request instead of asking the PAI admin.

For default vc, the admin should able to easily knows which group it is referencing.

**Comment by scarlett2018** [comment]
https://github.com/microsoft/pai/pull/4167

**Comment by hzy46** [comment]
Closed since it is fixed
