### ISSUE TITLE
source upload error when submit v2 job from vscode 

### ISSUE THREAD

**Issue by MaPing01** [microsoft/pai#4417]
**source upload error when submit v2 job from vscode **:

**source upload error when submit v2 job from vscode ,
the error is :Error occurred while uploading code: Cannot read property 'getChildren' of undefined**:

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:1.17
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by yiyione** [comment]
Hi @MaPing01 , can you view the storage from the `STORAGE EXPLORER` ?
![Annotation 2020-04-21 165346](https://user-images.githubusercontent.com/17357108/79846244-ca70c800-83f0-11ea-89e3-7197787edaa3.png)

**Comment by MaPing01** [comment]
> Hi @MaPing01 , can you view the storage from the `STORAGE EXPLORER` ?
> ![Annotation 2020-04-21 165346](https://user-images.githubusercontent.com/17357108/79846244-ca70c800-83f0-11ea-89e3-7197787edaa3.png)

![image](https://user-images.githubusercontent.com/39873427/79847132-e163ea00-83f1-11ea-834d-5e55375d735d.png)
yes i can see

**Comment by yiyione** [comment]
The error message looks like the uploader can't open the target folder from the `STORAGE EXPLORER`,
Can you try to go to the target folder ? And see what's happening.
for example:
![Annotation 2020-04-21 1611](https://user-images.githubusercontent.com/17357108/79848327-86cb8d80-83f3-11ea-8b65-d78d8b260ac7.png)

**Comment by MaPing01** [comment]
> Hi @MaPing01 , The error message looks like the uploader can't open the target folder from the `STORAGE EXPLORER`,
> Can you try to go to the target folder ? And see what's happening.
> for example:
> ![Annotation 2020-04-21 1611](https://user-images.githubusercontent.com/17357108/79848327-86cb8d80-83f3-11ea-8b65-d78d8b260ac7.png)

![image](https://user-images.githubusercontent.com/39873427/79851199-9220b800-83f7-11ea-9670-f495736a0ab3.png)
seems nothing can see in my cluster storage? is this due to something i did not set up or what can i do for this?

**Comment by yiyione** [comment]
I think it's because the cluster admin didn't setup the team-wise storage in OpenPAI.
You can just disable the source code auto uploading in vscode, and upload your code manually:
![Annotation 2020-04-21 2222](https://user-images.githubusercontent.com/17357108/79854297-d1e99e80-83fb-11ea-8ed9-7c0250a6788e.png)
Set the field `"pai.job.v2.upload.<cluster name>.enable"` to false.

If you still want use the auto upload feature, you can right click the `Personal storage` in `STORAGE EXPLORER` to add your storage, or ask the cluster admin to setup a team-wise storage.

**Comment by MaPing01** [comment]
> > Hi @MaPing01 , The error message looks like the uploader can't open the target folder from the `STORAGE EXPLORER`,
> > Can you try to go to the target folder ? And see what's happening.
> > for example:
> > ![Annotation 2020-04-21 1611](https://user-images.githubusercontent.com/17357108/79848327-86cb8d80-83f3-11ea-8b65-d78d8b260ac7.png)
> 
> ![image](https://user-images.githubusercontent.com/39873427/79851199-9220b800-83f7-11ea-9670-f495736a0ab3.png)
> seems nothing can see in my cluster storage? is this due to something i did not set up or what can i do for this?

![image](https://user-images.githubusercontent.com/39873427/79853412-9b5f5400-83fa-11ea-879d-3b7a1aa0ba3a.png)
find on the website have error 

> > Hi @MaPing01 , The error message looks like the uploader can't open the target folder from the `STORAGE EXPLORER`,
> > Can you try to go to the target folder ? And see what's happening.
> > for example:
> > ![Annotation 2020-04-21 1611](https://user-images.githubusercontent.com/17357108/79848327-86cb8d80-83f3-11ea-8b65-d78d8b260ac7.png)
> 
> ![image](https://user-images.githubusercontent.com/39873427/79851199-9220b800-83f7-11ea-9670-f495736a0ab3.png)
> seems nothing can see in my cluster storage? is this due to something i did not set up or what can i do for this?

![image](https://user-images.githubusercontent.com/39873427/79859288-5986db80-8403-11ea-8a85-bc9083e3db79.png)
in cluster web portal i found this error? 50070/webhdfs/v1/?op=liststatus not have any response.and if  the auto upload will upload source to HDFS default?

**Comment by yiyione** [comment]
The auto upload for v1 job will upload source to HDFS by default.
But for v2 job will not, it should ask user to select a storage, because the OpenPAI don't have a default HDFS any more after pure k8s version.

I don't know the version of your OpenPAI cluster, from the website snip, the `Team Share Storages` was empty, 
so the auto upload will fail in vscode ext, and I suggest to disable the source auto upload in vscode ext setting, and do it manually.

**Comment by MaPing01** [comment]
> The auto upload for v1 job will upload source to HDFS by default.
> But for v2 job will not, it should ask user to select a storage, because the OpenPAI don't have a default HDFS any more after pure k8s version.
> 
> I don't know the version of your OpenPAI cluster, from the website snip, the `Team Share Storages` was empty,
> so the auto upload will fail in vscode ext, and I suggest to disable the source auto upload in vscode ext setting, and do it manually.


thanks a lot. i try to upload source to HDFS manually but i don't konw how to use the HDFS folder in job? and  we stiil want to konw
how i can access :50070/webhdfs/v1/?op=liststatus and upload source in web portal?

thanks.......................

**Comment by yiyione** [comment]
If your cluster have a HDFS, there's a document about how to access it [HDFS](https://github.com/microsoft/pai/blob/master/docs/hadoop/hdfs.md).
And I have no idea about what's wrong with the 50070 port, but I think you can try `http://<master-node-address>/webhdfs`.

Maybe @debuggy can provide some help about access HDFS from the web portal.

**Comment by debuggy** [comment]
hi, @MaPing01 If you use OpenPAI version 0.17, the hdfs will not be deployed by default. 

The 50070 is the port of webHDFS. You could try to directly go to your cluster web Hdfs page (http://<clusterip>/webhdfs or http://<clusterip>:50070) to see if there is any webHDFS exists.

**Comment by MaPing01** [comment]
> hi, @MaPing01 If you use OpenPAI version 0.17, the hdfs will not be deployed by default.
> 
> The 50070 is the port of webHDFS. You could try to directly go to your cluster web Hdfs page (http:///webhdfs or http://:50070) to see if there is any webHDFS exists.
![image](https://user-images.githubusercontent.com/39873427/79947104-eda87f80-84a3-11ea-8526-906cd9298652.png)
![image](https://user-images.githubusercontent.com/39873427/79947205-2183a500-84a4-11ea-9394-53d5c899c135.png)

hi @debuggy thanks , my web hdfs page is 5070 and can see some folders,but in the openpai web pag the source upload will acess 50070, what's the difference between 5070 port and 50070 port?

**Comment by debuggy** [comment]
ok, so the problem is the storage manager will connect to 50070 by default and it could not be configured to other port because it is a deprecated feature now. 

So I suggest you to redeploy webhdfs to port 50070 if you want to use this storage feature.

**Comment by scarlett2018** [comment]
> ok, so the problem is the storage manager will connect to 50070 by default and it could not be configured to other port.
> 
> So I suggest you to redeploy webhdfs to port 50070 if you want to use this storage feature and see if it works.

@debuggy - this work round is fine. but seems something we should improve here as well, make the port configurable?

**Comment by debuggy** [comment]
related issue #4385

**Comment by scarlett2018** [comment]
@MaPing01 - had you got a chance try the suggestions? any feedback or updates? thanks.

**Comment by fanyangCS** [comment]
close as no further response.
