### ISSUE TITLE
Some job history API response not match schema in swagger

### ISSUE THREAD

**Issue by yiyione** [microsoft/pai#4425]
During the test, I found some jobs history response not match the schema in [swagger](https://github.com/microsoft/pai/blob/pai-0.18.y/src/rest-server/docs/swagger.yaml)

1. get /api/v2/jobs/{user}~{job}/job-attempts
error message:
```js
{
    keyword: 'type',
    dataPath: '[0].exitDiagnostics.runtime',
    schemaPath: '#/items/properties/exitDiagnostics/properties/runtime/type',
    params: { type: 'object' },
    message: 'should be object'
}
// Got "runtime": null
```

2. get /api/v2/jobs/{user}~{job}/job-attempts/{attemptIndex}
```js
{
    keyword: 'type',
    dataPath: '.exitDiagnostics.runtime',
    schemaPath: '#/properties/exitDiagnostics/properties/runtime/type',
    params: { type: 'object' },
    message: 'should be object'
}
// Got "runtime": null
```

**Comment by fanyangCS** [comment]
@yiyione, pls ping the owner of this API for clarification.

**Comment by yiyione** [comment]
> @yiyione, pls ping the owner of this API for clarification.

OK. I'll ping them.

**Comment by debuggy** [comment]
I will create a pr and edit history schema to include ``null``` cases
