### ISSUE TITLE
OpenPai examples need to be updated

### ISSUE THREAD

**Issue by victorming** [microsoft/pai#4432]
**Organization Name**:
CloudEdu

**Short summary about the issue/question**:
OpenPAI examples need to be updated. The examples use JSON but OpenPAI of v0.14.0 only accept YAML file when submit jobs.
**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**: Ubuntu 16.04
- OpenPAI version: v0.14.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by andrewjong** [comment]
I agree with this. I've been confused when I come across JSON examples.

**Comment by abuccts** [comment]
All outdated examples have been removed, pls refer to https://github.com/microsoft/pai/tree/v1.0.1/marketplace-v2 for examples.
