### ISSUE TITLE
Review user manual and admin manual

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#4439]
- [ ] user manual review: https://github.com/microsoft/pai/blob/user_manual/manual/cluster-user/README.md
  - [x] Quick Start @debuggy 
  - [x] Docker Images and Job Examples @debuggy 
  - [x] How to Manage Data @Binyang2014 
  - [x] How to Debug Jobs @Binyang2014 
  - [x] Advanced Jobs @abuccts 
  - [x] Use Marketplace @debuggy 
  - [x] Use VSCode Extension @yiyione 
  - [x] Use Jupyter Notebook Extension (empty doc)
- [ ] admin manual review: https://github.com/microsoft/pai/blob/user_manual/manual/cluster-admin/README.md
  - [x] Installation Guide @ydye 
  - [x] Installation FAQs and Troubleshooting @ydye 
  - [x] Basic Management Operations 
    - [x] webportal @debuggy 
    - [x] access k8s dashboard @Binyang2014 
    - [x] paictl @ydye 
  - [x] How to Manage Users and Groups @ydye 
  - [x] How to Setup Kubernetes Persistent Volumes as Storage @abuccts 
  - [x] How to Set Up Virtual Clusters @abuccts
  - [x] How to Add and Remove Nodes @ydye 
  - [ ] How to use CPU Nodes @mydmdm 
  - [x] How to Customize Cluster by Plugins @debuggy 
  - [x] Troubleshooting @abuccts 
  - [x] How to Uninstall OpenPAI @ydye 
  - [x] Upgrade Guide  (empty doc)
- [x] Check all links

**Comment by ydye** [comment]
Please change the config from https://github.com/microsoft/pai/blob/user_manual/manual/cluster-admin/installation-guide.md#config-example to https://github.com/microsoft/pai/blob/master/contrib/kubespray/doc/quick-start.md#write-config

**Comment by hzy46** [comment]
> Please change the config from https://github.com/microsoft/pai/blob/user_manual/manual/cluster-admin/installation-guide.md#config-example to https://github.com/microsoft/pai/blob/master/contrib/kubespray/doc/quick-start.md#write-config

Done.

**Comment by Binyang2014** [comment]
For `ssh` and `tensorBoard`. These two plugins only works when the IP address is accessible from customer env (not cluster internal IP). So if PAI deployed in some cloud env such as Azure, these two plugins will not work. Please add this notice in the doc.

**Comment by hzy46** [comment]
> For `ssh` and `tensorBoard`. These two plugins only works when the IP address is accessible from customer env (not cluster internal IP). So if PAI deployed in some cloud env such as Azure, these two plugins will not work. Please add this notice in the doc.

Done.
