### ISSUE TITLE
User specified GPUType job will not trigger yarn preemption.

### ISSUE THREAD

**Issue by qinchen123** [Microsoft/pai#445]
GPU type is PAI supported feature, but not supported in hadoop yarn. 
If user submit job with GPU Type specified, this job will not preempt others job even if his VC quota is occupied by others.

**Comment by qinchen123** [comment]
Update hadoop-ai to hadoop-2.9.0 will resovle it.

**Comment by fanyangCS** [comment]
we will remove GPU type support when submitting a job. We will bind GPU type to a VC, and assuming one VC only has one SKUs.

**Comment by GeoffreyChen777** [comment]
> we will remove GPU type support when submitting a job. We will bind GPU type to a VC, and assuming one VC only has one SKUs.

@fanyangCS Is this feature in plan now?

**Comment by fanyangCS** [comment]
@GeoffreyChen777 , yes. the plan is to introduce a "tag" like feature, when submitting a job, user can specify the tag so that the scheduler knows what to match when finding a qualified node. 

Initial design passed, pending release date
