### ISSUE TITLE
Support delete/archive jobs

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#4453]
This ticket is not for the current release but for a future support.

**Scenario**
As an OpenPAI user, I could permanent delete (clean up) some of my jobs to get rid of not in use jobs. After deletion, no one can restore this jobs. User need to confirm before the deletion.

As an Administrator, I could able to archive some bad job to clean up the view for all the users. After archive, the jobs are disappeared from job list and search views, but accessible from the job url (as archived read only job). Admin and user may or may not able to restore this jobs (to be decides, comments are welcomed here).

**Comment by LiFang-Shaiic** [comment]
We need admin user can delete some testing jobs. On developing some features in our platform  based on OpenPAI, we need get the job list. If admin user cannot delete those useless jobs, the list of jobs that we get by API will be so long. And it seems that too many jobs will impact the performance of OpenPAI.

**Comment by mydmdm** [comment]
@LiFang-Shaiic Here are work arounds for `admin`

- for `k8s` version, admin may use `kubectl` to delete framework objects

- for `yarn` version, try below link  https://github.com/microsoft/pai/blob/master/subprojects/frameworklauncher/yarn/doc/USERMANUAL.md#delete-framework

**Comment by mydmdm** [comment]
The `archive` of jobs is planned to be supported in the following releases

**Comment by hzy46** [comment]
Support job archive (only `Completed` jobs can be archived):

- Add rest-server interface or use existing interface
  - PUT /jobs/{user}~{job}/executionType ?
- Get /jobs : support to include archived jobs or not. Default is not to include archived jobs

**Comment by suiguoxin** [comment]
This feature can be realized by using job-tagging. Users can add a tag `archived` to the jobs. 

Please refer to https://github.com/microsoft/pai/pull/4853
