### ISSUE TITLE
Can't connect local NVIDIA driver and hadoop-node-manager

### ISSUE THREAD

**Issue by andrewsen13** [microsoft/pai#4469]
**OpenPAI Environment**:
- OpenPAI version: 0.14.0
- OS (e.g. from /etc/os-release): Ubuntu 18.04
- Kernel (e.g. `uname -a`): 5.3.0-42-generic
- Hardware (e.g. core number, memory size, storage size, GPU type etc.): 12 core, 64 RAM, 1 Tb SSD, NVIDIA 2080 Ti

**The main problem**:

I'm trying to install PAI without "drivers" service and I added the info about my driver in the hadoop-node-manager service (135 line in hadoop-node-manager.yaml.template). Also, I have added information about my pre-installed-driver in service-configuration.yaml. 
However, It doesn't connect anyway.

docker logs k8s_hadoop-node-manager:
`./start_service.sh: line 47: nvidia-smi: command not found
`
And in the end of this log 
![image](https://user-images.githubusercontent.com/56435717/80542481-b3fcda80-89b5-11ea-871d-a53a0ceeab8a.png)

docker logs k8s_job-exporter shows me these:
![image](https://user-images.githubusercontent.com/56435717/80542597-f58d8580-89b5-11ea-9e00-534687733b3d.png)

In addition, I have installed NVIDIA driver using apt install (`apt install nvidia-driver-430.50`), and I see my driver only in `/usr/src/nvidia-430.50` directory. I don't see anything in `/var/drivers/nvidia/current` and the same in `/usr/local/nvidia`. Also, this worker machine has pre-installed nvidia-container-runtime. May you know how to add driver's components in `/usr/local/nvidia`? Or can you suggest where I am wrong?

**Comment by ydye** [comment]
https://askubuntu.com/questions/32507/how-do-i-get-a-list-of-installed-files-from-a-package

Can you list the file path with this command.

**Comment by andrewsen13** [comment]
`apt-file nvidia-driver-430` shows me this:

nvidia-driver-430: /usr/share/doc/nvidia-driver-430/LICENSE.gz
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/NVIDIA_Changelog.gz
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/README.txt.gz
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/acknowledgements.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/addressingcapabilities.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/addtlresources.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/appendices.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/audiosupport.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/changelog.Debian.gz
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/commonproblems.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/configlaptop.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/configmultxscreens.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/configtwinview.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/copyright
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/depth30.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/displaydevicenames.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/dma_issues.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/dpi.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/editxconfig.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/egpu.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/faq.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/flippingubb.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/framelock.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/glxsupport.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/gpunames.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/i2c.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/index.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/installationandconfiguration.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/installdriver.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/installedcomponents.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/introduction.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/kms.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/knownissues.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/minimumrequirements.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/newusertips.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/nvidia
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/nvidia-debugdump.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/nvidia-hibernate.service
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/nvidia-ml.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/nvidia-persistenced-init.tar.bz2
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/nvidia-persistenced.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/nvidia-resume.service
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/nvidia-sleep.sh
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/nvidia-smi.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/nvidia-suspend.service
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/nvidiasettings.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/openglenvvariables.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/optimus.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/powermanagement.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/procinterface.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/profiles.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/programmingmodes.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/randr14.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/retpoline.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/sdi.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/selectdriver.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/sli.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/supportedchips.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/vdpausupport.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/xcompositeextension.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/xconfigoptions.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/xineramaglx.html
nvidia-driver-430: /usr/share/doc/nvidia-driver-430/xrandrextension.html

**Comment by ydye** [comment]
what the output of this 
```
dpkg-query -L ${pkg}
```

**Comment by andrewsen13** [comment]
I have this output:
```
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/nvidia-driver-430
/usr/share/doc/nvidia-driver-430/LICENSE.gz
/usr/share/doc/nvidia-driver-430/NVIDIA_Changelog.gz
/usr/share/doc/nvidia-driver-430/README.txt.gz
/usr/share/doc/nvidia-driver-430/acknowledgements.html
/usr/share/doc/nvidia-driver-430/addressingcapabilities.html
/usr/share/doc/nvidia-driver-430/addtlresources.html
/usr/share/doc/nvidia-driver-430/appendices.html
/usr/share/doc/nvidia-driver-430/audiosupport.html
/usr/share/doc/nvidia-driver-430/changelog.Debian.gz
/usr/share/doc/nvidia-driver-430/commonproblems.html
/usr/share/doc/nvidia-driver-430/configlaptop.html
/usr/share/doc/nvidia-driver-430/configmultxscreens.html
/usr/share/doc/nvidia-driver-430/configtwinview.html
/usr/share/doc/nvidia-driver-430/copyright
/usr/share/doc/nvidia-driver-430/depth30.html
/usr/share/doc/nvidia-driver-430/displaydevicenames.html
/usr/share/doc/nvidia-driver-430/dma_issues.html
/usr/share/doc/nvidia-driver-430/dpi.html
/usr/share/doc/nvidia-driver-430/editxconfig.html
/usr/share/doc/nvidia-driver-430/egpu.html
/usr/share/doc/nvidia-driver-430/faq.html
/usr/share/doc/nvidia-driver-430/flippingubb.html
/usr/share/doc/nvidia-driver-430/framelock.html
/usr/share/doc/nvidia-driver-430/glxsupport.html
/usr/share/doc/nvidia-driver-430/gpunames.html
/usr/share/doc/nvidia-driver-430/i2c.html
/usr/share/doc/nvidia-driver-430/index.html
/usr/share/doc/nvidia-driver-430/installationandconfiguration.html
/usr/share/doc/nvidia-driver-430/installdriver.html
/usr/share/doc/nvidia-driver-430/installedcomponents.html
/usr/share/doc/nvidia-driver-430/introduction.html
/usr/share/doc/nvidia-driver-430/kms.html
/usr/share/doc/nvidia-driver-430/knownissues.html
/usr/share/doc/nvidia-driver-430/minimumrequirements.html
/usr/share/doc/nvidia-driver-430/newusertips.html
/usr/share/doc/nvidia-driver-430/nvidia
/usr/share/doc/nvidia-driver-430/nvidia-debugdump.html
/usr/share/doc/nvidia-driver-430/nvidia-hibernate.service
/usr/share/doc/nvidia-driver-430/nvidia-ml.html
/usr/share/doc/nvidia-driver-430/nvidia-persistenced-init.tar.bz2
/usr/share/doc/nvidia-driver-430/nvidia-persistenced.html
/usr/share/doc/nvidia-driver-430/nvidia-resume.service
/usr/share/doc/nvidia-driver-430/nvidia-sleep.sh
/usr/share/doc/nvidia-driver-430/nvidia-smi.html
/usr/share/doc/nvidia-driver-430/nvidia-suspend.service
/usr/share/doc/nvidia-driver-430/nvidiasettings.html
/usr/share/doc/nvidia-driver-430/openglenvvariables.html
/usr/share/doc/nvidia-driver-430/optimus.html
/usr/share/doc/nvidia-driver-430/powermanagement.html
/usr/share/doc/nvidia-driver-430/procinterface.html
/usr/share/doc/nvidia-driver-430/profiles.html
/usr/share/doc/nvidia-driver-430/programmingmodes.html
/usr/share/doc/nvidia-driver-430/randr14.html
/usr/share/doc/nvidia-driver-430/retpoline.html
/usr/share/doc/nvidia-driver-430/sdi.html
/usr/share/doc/nvidia-driver-430/selectdriver.html
/usr/share/doc/nvidia-driver-430/sli.html
/usr/share/doc/nvidia-driver-430/supportedchips.html
/usr/share/doc/nvidia-driver-430/vdpausupport.html
/usr/share/doc/nvidia-driver-430/xcompositeextension.html
/usr/share/doc/nvidia-driver-430/xconfigoptions.html
/usr/share/doc/nvidia-driver-430/xineramaglx.html
/usr/share/doc/nvidia-driver-430/xrandrextension.html

```

**Comment by ydye** [comment]
Not sure where the binary is installed. I guess the gpu drivers in 18.04 different from 16.04, I mean the target path to be installed. Can you ensure this?

**Comment by andrewsen13** [comment]
I tried `whereis nvidia` and it showed me `nvidia: /usr/lib/nvidia /usr/local/nvidia /usr/share/nvidia /usr/src/nvidia-430.50/nvidia
`
I've checked anything there and there are no lib directory:
- in `/usr/lib/nvidia` is only pre-install file
- in `/usr/local/nvidia` is nothing (no one file)
- in `/usr/share/nvidia/` are `nvidia-application-profiles-430.50-key-documentation  nvidia-application-profiles-430.50-rc` files
- in `/usr/src/nvidia-430.50/nvidia` i have these files `common  conftest.sh  dkms.conf  Kbuild  Makefile  nvidia  nvidia-drm  nvidia-modeset  nvidia-uvm  patches
`

**Comment by andrewsen13** [comment]
**Dear ydye,** could you tell me what should be inside the directory of the driver (/usr/local/nvidia or /var/drivers/nvidia/current)?

I see that in drivers.md file of **master** branch is following information as an example:
![image](https://user-images.githubusercontent.com/56435717/80624303-245a3900-8a54-11ea-90b7-2e14d0e3b435.png)


But what exactly should be there?

**Comment by ydye** [comment]
@andrewsen13

 Once, in the yarn type openpai, we install nvidia drivers by ourselfs with nvidia's package. The path ```/var/drivers/nvidia/current``` is where the drivers should be installed.

The path ```/usr/local/nvidia``` is installed by apt-get in ubuntu 16.04 LTS. 

See the code in hadoop nm:
https://github.com/microsoft/pai/blob/pai-0.17.y/src/hadoop-node-manager/deploy/hadoop-node-manager-configuration/nodemanager-start-service.sh#L20
https://github.com/microsoft/pai/blob/pai-0.16.y/src/hadoop-node-manager/deploy/hadoop-node-manager.yaml.template#L110

This path should contain the binary nvidia-smi. But in my mind, you'd better mount all path which installed the nvidia-drviers' file.

**Comment by andrewsen13** [comment]
@ydye

I have this directory `/var/drivers/nvidia/current`, but there are nothing too. 

However, I know where nvidia-smi locates, it's `/usr/bin`, I've tried to add it in hadoop-node-manager.yaml.template in the line which you noticed, but it hasn't worked too.

I see that nvidia's libraries locates in `/usr/lib/x86_64-linux-gnu`, but there are no nvidia-smi for sure. I will try to add `/usr/bin` and `/usr/lib/x86_64-linux-gnu` in nodemanager-start-service.sh as a hard-code

**Comment by ydye** [comment]
By the way, it's the first time you install openpai or not?
If yes, I suggest to wait for the pure-k8s version. In this version, we will support local nvidia drivers.

**Comment by andrewsen13** [comment]
@ydye

Yes, it's the first time when I want to try to use it, but it's not my first installation. I'm trying to deploy it to a working version.
Could you tell me when pure-k8s version will be ready?

**Comment by andrewsen13** [comment]
@ydye 

I have solved this problem. 

I created bin and lib directories in `/usr/local/nvidia`, after this copied nvidia-smi from /usr/bin to `/usr/local/nvidia/bin`, and copied nvidia-driver libraries from `/usr/lib/x86_64-linux-gnu` to `/usr/local/nvidia/lib`.

After this, I changed in hadoop-node-manager.yaml.template following lines from `/var/drivers/nvidia/current` to `/usr/local/nvidia`:
- https://github.com/microsoft/pai/blob/pai-0.17.y/src/hadoop-node-manager/deploy/hadoop-node-manager.yaml.template#L55
- https://github.com/microsoft/pai/blob/pai-0.17.y/src/hadoop-node-manager/deploy/hadoop-node-manager.yaml.template#L111
- https://github.com/microsoft/pai/blob/pai-0.17.y/src/hadoop-node-manager/deploy/hadoop-node-manager.yaml.template#L135

The same I did for job-exporter.yaml.template from `/var/drivers/nvidia/current` to `/usr/local/nvidia`:
- https://github.com/microsoft/pai/blob/v0.14.0/src/job-exporter/deploy/job-exporter.yaml.template#L70
- https://github.com/microsoft/pai/blob/v0.14.0/src/job-exporter/deploy/job-exporter.yaml.template#L78
- https://github.com/microsoft/pai/blob/v0.14.0/src/job-exporter/deploy/job-exporter.yaml.template#L98

And now it's working fine without any problems.

@ydye Thank you a lot!

By the way, I want to know anyway when pure-k8s version will be ready? (:

**Comment by ydye** [comment]
> @ydye
> 
> Yes, it's the first time when I want to try to use it, but it's not my first installation. I'm trying to deploy it to a working version.
> Could you tell me when pure-k8s version will be ready?

@hzy46

**Comment by andrewsen13** [comment]
@hzy46 , could you provide some detail of that?
Just want to up the topic.

**Comment by hzy46** [comment]
> @hzy46 , could you provide some detail of that?
> Just want to up the topic.

Sorry for the late reply. It will be ready in this week.
