### ISSUE TITLE
job mutil command error

### ISSUE THREAD

**Issue by MaPing01** [microsoft/pai#4471]
**Organization Name**:

** excute mutil command in job but error **:
![image](https://user-images.githubusercontent.com/39873427/80559230-7c228100-8a0f-11ea-9844-945c2355419e.png)
![image](https://user-images.githubusercontent.com/39873427/80559246-8a709d00-8a0f-11ea-9cad-3db19fb78707.png)

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by Binyang2014** [comment]
Please refer to https://github.com/microsoft/pai/issues/4306#issuecomment-601555216, there is a workaround for this issue.

Add refer to https://github.com/microsoft/pai/issues/4308#issuecomment-601740810.
If you are using `yarn` version, we suggest to use v0.14 version.

**Comment by fanyangCS** [comment]
close as no further response.
