### ISSUE TITLE
if can use smbclient and nfs mount in v2 job

### ISSUE THREAD

**Issue by MaPing01** [microsoft/pai#4474]
**Organization Name**:

**Short summary about the issue/question**:

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:1.17
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by MaPing01** [comment]
https://github.com/microsoft/pai/blob/master/docs/zh_CN/user/storage.md
i refer to this doc,and use smbclient to get my source code,but failed and don't have any error info
![image](https://user-images.githubusercontent.com/39873427/80663000-5bb4fe00-8ac5-11ea-9fa6-194a7f6d9c24.png)
![image](https://user-images.githubusercontent.com/39873427/80663050-8010da80-8ac5-11ea-8806-cfacc3572d42.png)
i already install smbclient in my image

**Comment by abuccts** [comment]
@MaPing01 could you run the same command successfully on the host? according to [smbclient manual](https://www.tldp.org/HOWTO/SMB-HOWTO-8.html), there's an issue with your samba address which doesn't use backslashes or escape the backslashes.

the job didn't prevent you from mounting, it's all about your image and command

**Comment by MaPing01** [comment]
> @MaPing01 could you run the same command successfully on the host? according to [smbclient manual](https://www.tldp.org/HOWTO/SMB-HOWTO-8.html), there's an issue with your samba address which doesn't use backslashes or escape the backslashes.
> 
> the job didn't prevent you from mounting, it's all about your image and command
i can run the same command successfully on the host, refer to storage.md https://github.com/microsoft/pai/blob/master/docs/zh_CN/user/storage.md

**Comment by abuccts** [comment]
could you change `smbclient` debug level, e.g. add `-d=3` in the mount command, and paste the output from job (stdout/stderr) and from host? you can remove the sensitive information.

**Comment by MaPing01** [comment]
> could you change `smbclient` debug level, e.g. add `-d=3` in the mount command, and paste the output from job (stdout/stderr) and from host? you can remove the sensitive information.

![image](https://user-images.githubusercontent.com/39873427/81150708-d93fa900-8fb2-11ea-8d38-8be24b41fa7c.png)
 command successfully on the host

**Comment by MaPing01** [comment]
> > could you change `smbclient` debug level, e.g. add `-d=3` in the mount command, and paste the output from job (stdout/stderr) and from host? you can remove the sensitive information.
> 
> ![image](https://user-images.githubusercontent.com/39873427/81150708-d93fa900-8fb2-11ea-8d38-8be24b41fa7c.png)
> command successfully on the host

![image](https://user-images.githubusercontent.com/39873427/81151435-929e7e80-8fb3-11ea-9612-e3f1da015613.png)
![image](https://user-images.githubusercontent.com/39873427/81151502-a21dc780-8fb3-11ea-941f-a0ea1cc38c32.png)
![image](https://user-images.githubusercontent.com/39873427/81151538-aba72f80-8fb3-11ea-9483-2be1d89d01c5.png)

**Comment by MaPing01** [comment]
> could you change `smbclient` debug level, e.g. add `-d=3` in the mount command, and paste the output from job (stdout/stderr) and from host? you can remove the sensitive information.

![image](https://user-images.githubusercontent.com/39873427/81152883-f6757700-8fb4-11ea-9bf7-101a6fa137ff.png)
but the job log like this

**Comment by abuccts** [comment]
could you paste the stdout and stderr of your job?
![image](https://user-images.githubusercontent.com/13360214/81157106-3a6a7b00-8fb9-11ea-99de-9a202043e696.png)

and seems you run `apt-get`, could you also share the job config?

**Comment by MaPing01** [comment]
> could you paste the stdout and stderr of your job by clicking the following buttons?
> ![image](https://user-images.githubusercontent.com/13360214/81157106-3a6a7b00-8fb9-11ea-99de-9a202043e696.png)
> 
> and seems you run `apt-get`, could you also share the job config?

![image](https://user-images.githubusercontent.com/39873427/81158251-5f132280-8fba-11ea-96cc-a04d9aef4e72.png)
job config is

**Comment by MaPing01** [comment]
> > could you paste the stdout and stderr of your job by clicking the following buttons?
> > ![image](https://user-images.githubusercontent.com/13360214/81157106-3a6a7b00-8fb9-11ea-99de-9a202043e696.png)
> > and seems you run `apt-get`, could you also share the job config?
> 
> ![image](https://user-images.githubusercontent.com/39873427/81158251-5f132280-8fba-11ea-96cc-a04d9aef4e72.png)
> job config is
stdout and stderr fech error

**Comment by abuccts** [comment]
according to the limited exit log in your previous screenshot, the job is failed because of network issue, in line 65 `Network is unreachable`, you may need to check it

![image](https://user-images.githubusercontent.com/39873427/81152883-f6757700-8fb4-11ea-9bf7-101a6fa137ff.png)

and for your test on the host, the prompt is `root@2134279eea66`, it seems that it's inside a container. did you really run on the host environment?

**Comment by scarlett2018** [comment]
Hi @MaPing01 - thanks for following openpai and interact with us. would you mind share more info about what's the major usage for you when considering openPAI for yourself or your organization. if you don't mind, would you please share the org name? so that we can clustering issues together by org names.

PS: may we know better why your organization is stay with 0.17? do you have plan to switch to v1.x soon?

**Comment by fanyangCS** [comment]
closed as no further response.
