### ISSUE TITLE
Can't create the admin user for dashboard service

### ISSUE THREAD

**Issue by andrewsen13** [microsoft/pai#4479]
**OpenPAI Environment**:
- OpenPAI version: 0.14.0
- OS (e.g. from /etc/os-release): Ubuntu 18.0

**The main problem**:

I'm trying to create the admin user for dashboard service using the instruction here: 
https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md

but each time when I use:

-`kubectl apply -f dashboard-adminuser.yaml` 
-`kubectl -n kubernetes-dashboard describe secret $(kubectl -n kubernetes-dashboard get secret | grep admin-user | awk '{print $1}')` 

it shows me kubernetes-dashboard-key-holder:

![image](https://user-images.githubusercontent.com/56435717/80760945-5f3a9a80-8b42-11ea-84cf-0abc0cff1c52.png)

I can't get a token for this and my dashboard is free to use.

**Comment by Binyang2014** [comment]
@andrewsen13, which version of PAI do you use. I remember we don't enable https for k8s-dashboard in 0.14 release.
Add please provide the `dashboard-adminuser.yaml`, seems it doesn't take effect.

**Comment by andrewsen13** [comment]
@Binyang2014 , I'm sorry for the delay with my answer. My version of PAI is 0.14 release. 

`dashboard-adminuser.yaml` contains:

![image](https://user-images.githubusercontent.com/56435717/81701771-1ef8e780-9473-11ea-8a9d-63e781fa9bfe.png)

**Comment by Binyang2014** [comment]
@andrewsen13 , please make sure this is `kubernetes-dashboard` namespace in the k8s.
You can run `kubectl get ns` to get all namespaces.

If you can find  `kubernetes-dashboard` namespace. Please show me the result of `kubectl get secret -n kubernetes-dashboard`.

If there is not namespace named `kubernetes-dashboard`, please change the namespace to `kube-system` in `dashboard-adminuser.yaml`

**Comment by andrewsen13** [comment]
@Binyang2014 , I changed my config file `dashboard-adminuser.yaml` and added `kube-system` namespace. At this moment it looks like this:

![image](https://user-images.githubusercontent.com/56435717/81927854-057bab00-95ed-11ea-9333-78b013ccb9e8.png)

After this I applied the config using `kubectl apply -f dashboard-adminuser.yaml`. And then tried to get the token using `kubectl -n kube-system describe secret $(kubectl -n kube-system get secret | grep admin-user | awk '{print $1}')`. The output:

![image](https://user-images.githubusercontent.com/56435717/81928307-b97d3600-95ed-11ea-8d6e-83ec78e250fd.png)

And the result after `kubectl get secret -n kube-system`:

![image](https://user-images.githubusercontent.com/56435717/81928387-d6196e00-95ed-11ea-8cb8-c5d10264a0be.png)

**Comment by andrewsen13** [comment]
UP

**Comment by andrewsen13** [comment]
I didn't solve the problem with a dashboard.

**By the way I've met another problem with Hadoop (I guess)**

**The main problem**:
I deployed the cluster for 4 nodes (1 master and 3 workers) and anything works fine. However, there are one node which can't connect to OpenPAI properly. I can see this node in Kubernetes - anything is good, the same in hdfs - I see all data nodes. By the way, I can see this node in services tab on Webportal, but can't see in the hardware. 
If I have this node in the cluster, I can't submit a job, the following error appears:
![image](https://user-images.githubusercontent.com/56435717/82918335-3ceb3f80-9f7d-11ea-9033-8b7d2a2adb60.png)

I've checked all containers - no errors, the same logs as in other worker machines.

Do you know how to solve this problem? Where does this Service tab come from?

**Comment by Binyang2014** [comment]
@andrewsen13 sorry for late reply. I checked the code, in 0.14 release, we don't enable k8s RBAC in this release. So I think you can access k8s-dashboard through: `your_master_ip"9090`. 

If it ask token to login. Please provide `dashboard` yaml.
You can run `kubectl get deployment  kubernetes-dashboard -n kube-system -o yaml` and provide the output.

For the `hdfs` issue. Please provide node full spec by running ``kubectl get node problem-node-name -o yaml`

**Comment by andrewsen13** [comment]
@Binyang2014, yes, I can reach  k8s-dashboard through: `my_master_ip:9090`, but I want to make it more securely.

- It doesn't ask me for token. The output of `kubectl get deployment kubernetes-dashboard -n kube-system -o yaml`:

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","k8s-app":"kubernetes-dashboard","kubernetes.io/cluster-service":"true"},"name":"kubernetes-dashboard","namespace":"kube-system"},"spec":{"selector":{"matchLabels":{"k8s-app":"kubernetes-dashboard"}},"template":{"metadata":{"annotations":{"scheduler.alpha.kubernetes.io/critical-pod":""},"labels":{"k8s-app":"kubernetes-dashboard"}},"spec":{"containers":[{"args":["--apiserver-host=http://master_ip:8080"],"image":"gcr.io/google_containers/kubernetes-dashboard-amd64:v1.8.3","livenessProbe":{"httpGet":{"path":"/","port":9090},"initialDelaySeconds":30,"timeoutSeconds":30},"name":"kubernetes-dashboard","ports":[{"containerPort":9090}],"resources":{"requests":{"cpu":"1000m","memory":"1000Mi"}}}],"hostNetwork":true,"nodeSelector":{"kubernetes.io/hostname":"master_ip"},"tolerations":[{"key":"CriticalAddonsOnly","operator":"Exists"}]}}}}
  creationTimestamp: "2020-03-02T18:19:00Z"
  generation: 1
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: kubernetes-dashboard
    kubernetes.io/cluster-service: "true"
  name: kubernetes-dashboard
  namespace: kube-system
  resourceVersion: "8617819"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/kubernetes-dashboard
  uid: 4a184574-5cb2-11ea-9c72-2cfda1baec29
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: kubernetes-dashboard
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      creationTimestamp: null
      labels:
        k8s-app: kubernetes-dashboard
    spec:
      containers:
      - args:
        - --apiserver-host=http://master_ip:8080
        image: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.8.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        name: kubernetes-dashboard
        ports:
        - containerPort: 9090
          hostPort: 9090
          protocol: TCP
        resources:
          requests:
            cpu: "1"
            memory: 1000Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: master_ip
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
status:
  availableReplicas: 1
  conditions:
    lastTransitionTime: "2020-03-02T18:19:00Z"
    lastUpdateTime: "2020-03-02T18:19:18Z"
    message: ReplicaSet "kubernetes-dashboard-5b6c487f76" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
    lastTransitionTime: "2020-05-26T15:24:43Z"
    lastUpdateTime: "2020-05-26T15:24:43Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1


- For the `hdfs` issue, I've matched 2 nodes (1 is in good condition, 1 is wrong) and they are the same in the configuration.
`The output of kubectl get node problem-node-name -o yaml`:

apiVersion: v1
kind: Node
metadata:
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2020-05-26T14:09:37Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/hostname: ip_of_the node
    pai-worker: "true"
  name: node_name
  resourceVersion: "version"
  selfLink: /api/v1/nodes/ip_of_the node
  uid: id_of_the node
spec:
  externalID: id_of_the node
status:
  addresses:
  - address: ip_of_the node
    type: InternalIP
  - address: ip_of_the node
    type: Hostname
  allocatable:
    cpu: "24"
    memory: memory
    pods: "110"
  capacity:
    cpu: "24"
    memory: memory
    pods: "110"
  conditions:
  - lastHeartbeatTime: "2020-05-27T08:05:38Z"
    lastTransitionTime: "2020-05-26T14:08:30Z"
    message: kubelet has sufficient disk space available
    reason: KubeletHasSufficientDisk
    status: "False"
    type: OutOfDisk
  - lastHeartbeatTime: "2020-05-27T08:05:38Z"
    lastTransitionTime: "2020-05-26T14:08:30Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2020-05-27T08:05:38Z"
    lastTransitionTime: "2020-05-26T14:08:30Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2020-05-27T08:05:38Z"
    lastTransitionTime: "2020-05-26T14:08:41Z"
    message: kubelet is posting ready status
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images:
.......
  nodeInfo:
    architecture: amd64
    bootID: id_of_the node
    containerRuntimeVersion: docker://19.3.9
    kernelVersion: 4.15.0-96-generic
    kubeProxyVersion: v1.9.9
    kubeletVersion: v1.9.9
    machineID: id_of_the node
    operatingSystem: linux
    osImage: Debian GNU/Linux 9 (stretch)
    systemUUID: id_of_the node

> Changed some special info - id_of_the node, ip_of_the node, memory

**Comment by Binyang2014** [comment]
@andrewsen13 For 0.14 version, we don't enable k8s RBAC, so you can not use token to login k8s-dashbaord.
If you want to use token to login k8s, please upgrade to 1.0 release. (You need to redeploy k8s to enable RBAC)

For hdfs issue, can you create another issue to track this?

**Comment by Binyang2014** [comment]
Moreover, to use token for k8s-dashboard, you should enable https for PAI. You need to provide cert (self-signed cert is OK) for this.

**Comment by andrewsen13** [comment]
@Binyang2014 , I have seen that 1.0 release doesn't support Single-Box deployment at this moment or am I wrong? 
Okay, I got it. I will check how https can work for PAI.

For hdfs issue, I've created another one issue (don't know why I couldn't): https://github.com/microsoft/pai/issues/4571

**Comment by Binyang2014** [comment]
@andrewsen13, for 1.0 release, we don't officially support single box. At least 1 master and 1 workers  is recommended (Since some services will request many cpu/mem in master node). If you already have a k8s deployed in one node. You can try to deploy PAI on this. (Need `layout.yaml` and `services-configuration.yaml` be provided).

**Comment by andrewsen13** [comment]
@Binyang2014, do I understand correctly, if I have some thin PC as a DevBox (8 RAM, basic CPU, only for deployment), 1 master node (64Gb RAM and 12 CPU cores) and 1 worker node, I can deploy it for only 1 master node and I won't use the DevBox after the deployment? Or should I control anything using the DevBox machine and the master machine only using as a server?

**Comment by Binyang2014** [comment]
You can use thin PC as the devBox. After the deployment, the devbox is only used to run `kubectl` and `paictl` command for maintenance, it doesn't run any service.

**Comment by andrewsen13** [comment]
@Binyang2014, Thank you so much for the explanation and the help. I will try to use this tempting version of PAI. 

I'm closing this issue. I will try to enable https for PAI and will feedback about it here when open again.
