### ISSUE TITLE
Wrong hivedscheudler config is generated in quick start script

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#4485]
The following config is generated in quick start script:

![image](https://user-images.githubusercontent.com/7499023/81040869-ec814480-8ede-11ea-8a2a-fdd7561a4e63.png)

However each node should have 4 GPUs.

**Comment by yqwang-ms** [comment]
The min gpus of all nodes should be 1, pls check your cluster.

**Comment by hzy46** [comment]
> The min gpus of all nodes should be 1, pls check your cluster.
> See
> 
> https://github.com/microsoft/pai/blob/4acfccf89bbe9738752aae766e2c559828e71f09/contrib/kubespray/script/openpai-generator.py#L172-L199

OK, I found actually there are 2 nodes with only 1 GPU:

![image](https://user-images.githubusercontent.com/7499023/81133695-01b0ae80-8f85-11ea-834d-1459cefdb960.png)
