### ISSUE TITLE
Refine README.md

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#4492]
There are many outdated links in [`README.md`](https://github.com/microsoft/pai/blob/master/README.md):
  
  - deployment-related: such as [single-box.md](https://github.com/microsoft/pai/blob/master/docs/pai-management/doc/single-box.md), [distributed-deploy.md](https://github.com/microsoft/pai/blob/master/docs/pai-management/doc/distributed-deploy.md), [how-to-generate-cluster-config.md](https://github.com/microsoft/pai/blob/master/docs/pai-management/doc/how-to-generate-cluster-config.md#Optional-Step-3.-Customize-configure-OpenPAI), [faq.md](https://github.com/microsoft/pai/blob/master/docs/faq.md#deploy-and-maintenance-related-faqs). They are installation guide for yarn version.
  - submit job: [job submission doc]( https://github.com/microsoft/pai/blob/master/docs/user/job_submission.md) is outdated.
  - storage: [storage.md](https://github.com/microsoft/pai/blob/master/docs/user/storage.md) is for V1 schema.
  - others
    - [paictl-manual.md](https://github.com/microsoft/pai/blob/master/docs/paictl/paictl-manual.md) still mentions yarn quick-start config.
    - [Resource-Requirement](https://github.com/Microsoft/pai/wiki/Resource-Requirement)

We can refine the above information with 3 sections:
  - For administrator: deployment, faqs, etc.
  - For data scientists: job submission, monitoring jobs, etc.
  - Developers who want to contribute: document reference, how to contribute, etc.

In section for `administrator` and `data scientists`, we can reference https://openpai.readthedocs.io/

**Comment by mydmdm** [comment]
Could we add a basic summary of versions in README like 

|                   | `0.14.0`                | `1.0.0`                |
| ----------------- | ----------------------- | ---------------------- |
| Architecture      | Kubernetes + Yarn       | Kubernetes             |
| Scheduler         | Yarn scheduler          | HiveD / K8s default    |
| Job Orchestrating |                         | Framework Controller   |
| RESTful API       | v1 + v2                 | pure v2                |
| Storage           | Teamwise storage plugin | PV/PVC storage sharing |
| Marketplace       | marketplace v2          | new marketplace        |
| SDK               | Python                  | JS / TS                |
