### ISSUE TITLE
Error: failed to run Kubelet: Running with swap on is not supported, please disable swap! or set --fail-swap-on flag to false.

### ISSUE THREAD

**Issue by chivee** [Microsoft/pai#450]
Hi,

I've encountered an issue during the deploy procedure,

`I0410 08:57:54.409320   15727 server.go:428] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /

Error: failed to run Kubelet: Running with swap on is not supported, please disable swap! or set --fail-swap-on flag to false. /proc/swaps contained: [Filename                         Type            Size  Used     Priority /dev/sda5                               partition      536740860       0       -1]
Flag --require-kubeconfig has been deprecated, You no longer need to use --require-kubeconfig. This will be removed in a future version. Providing --kubeconfig enables API server mode, omitting --kubeconfig enables standalone mode unless --require-kubeconfig=true is also set. In the latter case, the legacy default kubeconfig path will be used until --require-kubeconfig is removed.

I0410 08:58:54.847081   39842 server.go:182] Version: v1.9.4
`
which can be fixed by disable swap using `swapoff -a`

issue from k8s: https://github.com/kubernetes/kubernetes/issues/50373

**Comment by fanyangCS** [comment]
Thanks for the report. I assume you have resolve this by disable swapping?
