### ISSUE TITLE
GPU drivers-one-shot failed to work on 0.14.0

### ISSUE THREAD

**Issue by victorming** [microsoft/pai#4507]
**Organization Name**:
EduCloud

**Short summary about the issue/question**:
GPU drivers-one-shot failed to work on 0.14.0 after rebooting the node. 
We choose not to install the GPU driver since the driver has already been installed before deploying OpenPai.  So we set "pre-installed-nvidia-path" to "/usr/lib/nvidia" where the driver is installed. The   service-configuration.yaml file below:
```
drivers:
    pre-installed-nvidia-path: /usr/lib/nvidia
```
But we don't konw why the drivers-one-shot servie still try to re-install GPU driver and get the follow errors:
2020-05-09T07:27:55.90509924Z + echo ======== If NVIDIA driver already running uninstall it =========
2020-05-09T07:27:55.905109932Z ======== If NVIDIA driver already running uninstall it =========
2020-05-09T07:27:55.905448438Z + lsmod
2020-05-09T07:27:55.905724049Z + grep -qE '^nvidia'
2020-05-09T07:27:55.910648708Z ++ tr -s ' '
2020-05-09T07:27:55.910840657Z ++ lsmod
2020-05-09T07:27:55.910950936Z ++ grep -E '^nvidia'
2020-05-09T07:27:55.911173242Z ++ cut -f 4 -d ' '
2020-05-09T07:27:55.915784158Z + DEP_MODS='
2020-05-09T07:27:55.915796527Z 
2020-05-09T07:27:55.915800868Z nvidia_drm
2020-05-09T07:27:55.915804356Z nvidia_uvm,nvidia_modeset'
2020-05-09T07:27:55.915807841Z + for mod in '${DEP_MODS//,/ }'
2020-05-09T07:27:55.915811374Z + rmmod nvidia_drm
2020-05-09T07:27:55.916770307Z rmmod: ERROR: Module nvidia_drm is in use
2020-05-09T07:27:55.916833317Z + echo 'The driver nvidia_drm is still in use, can'\''t unload it.'
2020-05-09T07:27:55.916845613Z + exit 1
2020-05-09T07:27:55.916854387Z The driver nvidia_drm is still in use, can't unload it.
2020-05-09T07:27:55.917124926Z + exit 1
**Brief what process you are following**:
Redeployed the drivers-one-shot service, but the failure remains.

**How to reproduce it**:

**OpenPAI Environment**:  
- OpenPAI version: 0.14.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Ubuntu 16.04 64bit
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.): GTX 1080Ti
- Others:

**Anything else we need to know**:

**Comment by ShawnNew** [comment]
You might want to try this [fix](https://github.com/ShawnNew/pai/commit/79baa2b48d0a8796069a0fb5bbad0f9c0b2b1a63), which replaces the pre-installed driver location in driver deployment code.

**Comment by victorming** [comment]
@ShawnNew , OK, I also doubted the wrong setting of "pre-installed-nvidia-path" caused this issue. I will fix the setting and redeploy the driver-one-shot service.

**Comment by victorming** [comment]
I changed the "pre-installed-nvidia-path" to "/var/drivers/nvidia/410.73" where the NVIDIA driver is pre-installed and /var/drivers/nvidia/410.73/bin/nvidia-smi is found under this directory. But unfortunately, the driver containers still failed to start. I checked the bash script install-all-drivers.sh in this container and executed it on the host node, and the result is "pre installed nvidia driver detectived, skip driver installation". 
However the container seems not found the environment variable PRE_INSTALLED_NV_DRIVER_PATH and  go driectly to "/bin/bash -x install-nvidia-drivers", which will failed due to the error of reload nvidia modules: "rmmod: ERROR: Module nvidia_drm is in use". Following is the YAML of the failed container:

`{
  "kind": "Pod",
  "apiVersion": "v1",
  "metadata": {
    "name": "drivers-one-shot-9xs4g",
    "generateName": "drivers-one-shot-",
    "namespace": "default",
    "selfLink": "/api/v1/namespaces/default/pods/drivers-one-shot-9xs4g",
    "uid": "ff5d686f-940a-11ea-95e8-44a842479863",
    "resourceVersion": "4278614",
    "creationTimestamp": "2020-05-12T04:42:34Z",
    "labels": {
      "app": "drivers-one-shot",
      "controller-revision-hash": "2675810400",
      "pod-template-generation": "1"
    },
    "ownerReferences": [
      {
        "apiVersion": "extensions/v1beta1",
        "kind": "DaemonSet",
        "name": "drivers-one-shot",
        "uid": "ff59ec53-940a-11ea-95e8-44a842479863",
        "controller": true,
        "blockOwnerDeletion": true
      }
    ]
  },
  "spec": {
    "volumes": [
      {
        "name": "driver-path",
        "hostPath": {
          "path": "/var/drivers",
          "type": ""
        }
      },
      {
        "name": "device-path",
        "hostPath": {
          "path": "/dev",
          "type": ""
        }
      },
      {
        "name": "modules-path",
        "hostPath": {
          "path": "/lib/modules",
          "type": ""
        }
      },
      {
        "name": "drivers-log",
        "hostPath": {
          "path": "/var/log/drivers",
          "type": ""
        }
      },
      {
        "name": "kernel-head",
        "hostPath": {
          "path": "/usr/src",
          "type": ""
        }
      },
      {
        "name": "etc-path-ld",
        "hostPath": {
          "path": "/etc/ld.so.conf.d",
          "type": ""
        }
      },
      {
        "name": "etc-path-docker",
        "hostPath": {
          "path": "/etc/docker",
          "type": ""
        }
      },
      {
        "name": "pre-install-nv-driver-path",
        "hostPath": {
          "path": "/usr/lib/nvidia-410",
          "type": ""
        }
      }
    ],
    "containers": [
      {
        "name": "nvidia-drivers",
        "image": "docker.io/openpai/drivers-410.73:v0.14.0",
        "command": [
          "bash",
          "-x",
          "./install-all-drivers"
        ],
        "env": [
          {
            "name": "DRIVER_PATH",
            "value": "/var/drivers/nvidia"
          },
          {
            "name": "PRE_INSTALLED_NV_DRIVER_PATH",
            "value": "/var/drivers/nvidia/410.73"
          },
          {
            "name": "POD_IP",
            "valueFrom": {
              "fieldRef": {
                "apiVersion": "v1",
                "fieldPath": "status.podIP"
              }
            }
          }
        ],
        "resources": {
          "limits": {
            "memory": "2Gi"
          },
          "requests": {
            "memory": "256Mi"
          }
        },
        "volumeMounts": [
          {
            "name": "driver-path",
            "mountPath": "/var/drivers"
          },
          {
            "name": "device-path",
            "mountPath": "/dev"
          },
          {
            "name": "modules-path",
            "mountPath": "/lib/modules"
          },
          {
            "name": "drivers-log",
            "mountPath": "/var/log"
          },
          {
            "name": "kernel-head",
            "mountPath": "/usr/src"
          },
          {
            "name": "etc-path-ld",
            "mountPath": "/etc/ld.so.conf.d"
          },
          {
            "name": "etc-path-docker",
            "mountPath": "/etc/docker"
          },
          {
            "name": "pre-install-nv-driver-path",
            "mountPath": "/var/drivers/nvidia/410.73"
          }
        ],
        "readinessProbe": {
          "exec": {
            "command": [
              "cat",
              "/jobstatus/jobok"
            ]
          },
          "initialDelaySeconds": 5,
          "timeoutSeconds": 1,
          "periodSeconds": 3,
          "successThreshold": 1,
          "failureThreshold": 3
        },
        "terminationMessagePath": "/dev/termination-log",
        "terminationMessagePolicy": "File",
        "imagePullPolicy": "Always",
        "securityContext": {
          "capabilities": {
            "add": [
              "ALL"
            ]
          },
          "privileged": true
        }
      }
    ],
    "restartPolicy": "Always",
    "terminationGracePeriodSeconds": 30,
    "dnsPolicy": "ClusterFirst",
    "nodeName": "192.168.101.245",
    "hostNetwork": true,
    "hostPID": true,
    "securityContext": {},
    "imagePullSecrets": [
      {
        "name": ""
      }
    ],
    "affinity": {
      "nodeAffinity": {
        "requiredDuringSchedulingIgnoredDuringExecution": {
          "nodeSelectorTerms": [
            {
              "matchExpressions": [
                {
                  "key": "no-drivers",
                  "operator": "NotIn",
                  "values": [
                    "true"
                  ]
                }
              ]
            }
          ]
        }
      }
    },
    "schedulerName": "default-scheduler",
    "tolerations": [
      {
        "key": "node.kubernetes.io/not-ready",
        "operator": "Exists",
        "effect": "NoExecute"
      },
      {
        "key": "node.kubernetes.io/unreachable",
        "operator": "Exists",
        "effect": "NoExecute"
      },
      {
        "key": "node.kubernetes.io/disk-pressure",
        "operator": "Exists",
        "effect": "NoSchedule"
      },
      {
        "key": "node.kubernetes.io/memory-pressure",
        "operator": "Exists",
        "effect": "NoSchedule"
      }
    ]
  },
  "status": {
    "phase": "Running",
    "conditions": [
      {
        "type": "Initialized",
        "status": "True",
        "lastProbeTime": null,
        "lastTransitionTime": "2020-05-12T04:42:34Z"
      },
      {
        "type": "Ready",
        "status": "False",
        "lastProbeTime": null,
        "lastTransitionTime": "2020-05-12T04:42:34Z",
        "reason": "ContainersNotReady",
        "message": "containers with unready status: [nvidia-drivers]"
      },
      {
        "type": "PodScheduled",
        "status": "True",
        "lastProbeTime": null,
        "lastTransitionTime": "2020-05-12T04:43:25Z"
      }
    ],
    "hostIP": "192.168.101.245",
    "podIP": "192.168.101.245",
    "startTime": "2020-05-12T04:42:34Z",
    "containerStatuses": [
      {
        "name": "nvidia-drivers",
        "state": {
          "waiting": {
            "reason": "CrashLoopBackOff",
            "message": "Back-off 5m0s restarting failed container=nvidia-drivers pod=drivers-one-shot-9xs4g_default(ff5d686f-940a-11ea-95e8-44a842479863)"
          }
        },
        "lastState": {
          "terminated": {
            "exitCode": 1,
            "reason": "Error",
            "startedAt": "2020-05-12T06:15:26Z",
            "finishedAt": "2020-05-12T06:15:27Z",
            "containerID": "docker://633315bd23115a456ce08c739d4ceadda17380fb672a027d55c9d1f20e9d9af1"
          }
        },
        "ready": false,
        "restartCount": 21,
        "image": "openpai/drivers-410.73:v0.14.0",
        "imageID": "docker-pullable://openpai/drivers-410.73@sha256:dd201c113ba09ad95489e08fc5deefd90bd35fd77155ea665665681d15d73938",
        "containerID": "docker://633315bd23115a456ce08c739d4ceadda17380fb672a027d55c9d1f20e9d9af1"
      }
    ],
    "qosClass": "Burstable"
  }
}`

**Comment by victorming** [comment]
I found the root cause of the error: "hostPath" for "pre-install-nv-driver-path" in drivers.yarml.template should be changed to "/var/drivers/nvidia/410.73" which is corresponding to the directory on the host node. Otherwise the script will fail to find nvidia-smi and attempt to reinstall the driver.
