### ISSUE TITLE
[Kubespray] Failed to deploy k8s cluster upon waiting weave

### ISSUE THREAD

**Issue by JosephKang** [microsoft/pai#4515]
**Short summary about the issue/question**:

Failed to deploy k8s cluster upon waiting weave step by step.

**Brief what process you are following**:
Deploy 1 master and 1 worker with step by step: (https://github.com/microsoft/pai/blob/master/contrib/kubespray/doc/step-by-step-k8s.md)

**Similar issue**:

https://github.com/microsoft/pai/issues/4480

**How to reproduce it**:

Follow the step on https://github.com/microsoft/pai/blob/master/contrib/kubespray/doc/step-by-step-k8s.md until https://github.com/microsoft/pai/blob/master/contrib/kubespray/doc/step-by-step-k8s.md#deploy-k8s

**OpenPAI Environment**:
- OpenPAI version: 0.17.0
- Kubespray version: release-2.11
- OS (e.g. from /etc/os-release): ubuntu 16.04.6 
- Kernel: 4.4.0-150-generic
- Hardware: 8 Cores, 64GB, 100GB
- Others:

**Anything else we need to know**:

- ansible_playbook log:
```
FAILED - RETRYING: Weave | Wait for Weave to become available (1 retries left).
fatal: [master-969205-iaas]: FAILED! => {"attempts": 180, "changed": false, "connection": "close", "content": "        Version: 2.5.2 (version check update disabled)\n\n        Service: router\n       Protocol: weave 1..2\n           Name: 6e:25:67:91:86:f0(master-969205-iaas)\n     Encryption: enabled\n  PeerDiscovery: enabled\n        Targets: 2\n    Connections: 2 (2 failed)\n          Peers: 1\n TrustedSubnets: none\n\n        Service: ipam\n         Status: awaiting consensus (quorum: 2, known: 1)\n          Range: 10.200.0.0/13\n  DefaultSubnet: 10.200.0.0/13\n", "content_length": "446", "content_type": "text/plain; charset=utf-8", "cookies": {}, "cookies_string": "", "date": "Tue, 12 May 2020 06:31:52 GMT", "msg": "OK (446 bytes)", "redirected": false, "status": 200, "url": "http://127.0.0.1:6784/status"} NO MORE HOSTS LEFT 
        to retry, use: --limit @/home/ubuntu/kubespray/cluster.retry

PLAY RECAP 
localhost                  : ok=1    changed=0    unreachable=0    failed=0
master-969205-iaas         : ok=589  changed=78   unreachable=0    failed=1
worker1-969211-iaas        : ok=375  changed=44   unreachable=0    failed=0
```
- container log(Image weaveworks/weave-kube images )
```
DEBU: 2020/05/12 06:16:31.747121 [kube-peers] Checking peer "6e:25:67:91:86:f0" against list &{[]}
Peer not in list; removing persisted data
INFO: 2020/05/12 06:16:31.843992 Command line options: map[http-addr:127.0.0.1:6784 ipalloc-init:consensus=2 no-masq-local:true docker-api: ipalloc-range:10.200.0.0/13 name:6e:25:67:91:86:f0 conn-limit:100 expect-npc:true host-root:/host metrics-addr:0.0.0.0:6782 nickname:master-969205-iaas port:6783 datapath:datapath db-prefix:/weavedb/weave-net mtu:1376 no-dns:true]
INFO: 2020/05/12 06:16:31.844046 weave  2.5.2
INFO: 2020/05/12 06:16:31.925469 Bridge type is bridged_fastdp
INFO: 2020/05/12 06:16:31.925487 Communication between peers via untrusted networks is encrypted.
INFO: 2020/05/12 06:16:31.958363 Our name is 6e:25:67:91:86:f0(master-969205-iaas)
INFO: 2020/05/12 06:16:31.958392 Launch detected - using supplied peer list: [192.168.211.9 192.168.211.6]
INFO: 2020/05/12 06:16:31.966493 Using "no-masq-local" LocalRangeTracker
INFO: 2020/05/12 06:16:31.966509 Checking for pre-existing addresses on weave bridge
INFO: 2020/05/12 06:16:31.969847 [allocator 6e:25:67:91:86:f0] No valid persisted data
INFO: 2020/05/12 06:16:31.972371 [allocator 6e:25:67:91:86:f0] Initialising via deferred consensus
INFO: 2020/05/12 06:16:31.972410 Sniffing traffic on datapath (via ODP)
INFO: 2020/05/12 06:16:31.972593 ->[192.168.211.9:6783] attempting connection
INFO: 2020/05/12 06:16:31.972669 ->[192.168.211.6:6783] attempting connection
INFO: 2020/05/12 06:16:31.972734 ->[192.168.211.9:57135] connection accepted
INFO: 2020/05/12 06:16:31.973293 ->[192.168.211.9:57135|6e:25:67:91:86:f0(master-969205-iaas)]: connection shutting down due to error: cannot connect to ourself
INFO: 2020/05/12 06:16:31.973352 ->[192.168.211.9:6783|6e:25:67:91:86:f0(master-969205-iaas)]: connection shutting down due to error: cannot connect to ourself
INFO: 2020/05/12 06:16:31.974092 Listening for HTTP control messages on 127.0.0.1:6784
INFO: 2020/05/12 06:16:31.974171 ->[192.168.211.6:6783] error during connection attempt: dial tcp4 :0->192.168.211.6:6783: connect: connection refused
INFO: 2020/05/12 06:16:31.974264 Listening for metrics requests on 0.0.0.0:6782
INFO: 2020/05/12 06:16:32.822275 [kube-peers] Added myself to peer list &{[{6e:25:67:91:86:f0 master-969205-iaas}]}
DEBU: 2020/05/12 06:16:32.829435 [kube-peers] Nodes that have disappeared: map[]
INFO: 2020/05/12 06:16:33.280402 ->[192.168.211.6:6783] attempting connection
INFO: 2020/05/12 06:16:33.281371 ->[192.168.211.6:6783] error during connection attempt: dial tcp4 :0->192.168.211.6:6783: connect: connection refused
INFO: 2020/05/12 06:16:35.287770 ->[192.168.211.6:6783] attempting connection
INFO: 2020/05/12 06:16:35.288328 ->[192.168.211.6:6783] error during connection attempt: dial tcp4 :0->192.168.211.6:6783: connect: connection refused
```
- netstat: _netstat -tulpn | grep 6784_
```
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:6784          0.0.0.0:*               LISTEN      -
udp        0      0 0.0.0.0:6784            0.0.0.0:*                           -
udp6       0      0 :::6784                 :::*                                -
```
- Weave driver status: _docker exec -it f41a3dac4171 /home/weave/weave --local status_
``` 
Version: 2.5.2 (version check update disabled)
        Service: router
       Protocol: weave 1..2
           Name: 6e:25:67:91:86:f0(master-969205-iaas)
     Encryption: enabled
  PeerDiscovery: enabled
        Targets: 2
    Connections: 2 (2 failed)
          Peers: 1
 TrustedSubnets: none
        Service: ipam
         Status: awaiting consensus (quorum: 2, known: 1)
          Range: 10.200.0.0/13
  DefaultSubnet: 10.200.0.0/13
```

**Comment by JosephKang** [comment]
The weave port on master host seems available.
- @master-969205-iaas:~/kubespray⟫ curl -v telnet://192.168.211.9:6783
`Rebuilt URL to: telnet://192.168.211.9:6783/
   Trying 192.168.211.9...
 Connected to 192.168.211.9 (192.168.211.9) port 6783 (#0)`
- @worker1-969211-iaas:~⟫ curl -v telnet://192.168.211.9:6783
`Rebuilt URL to: telnet://192.168.211.9:6783/
   Trying 192.168.211.9...
 Connected to 192.168.211.9 (192.168.211.9) port 6783 (#0)`

**Comment by ydye** [comment]
What's your env. physical or cloud

**Comment by JosephKang** [comment]
> What's your env. physical or cloud

The master and worker hosts are both in the cloud.
- Master(master-969205-iaas): 192.168.211.9
- Worker(worker1-969211-iaas): 192.168.211.6

**Comment by ydye** [comment]
- Azure ?
- check the output of this command ```lsof -i 6783````

**Comment by JosephKang** [comment]
> * Azure ?
> * check the output of this command `lsof -i:6783`

- The cloud env is a private cloud built by OpenStack.
- lsof -i 6783
`master-969205-iaas:~/kubespray> lsof -i 6783
lsof: unknown protocol name (783) in: -i 6783
lsof 4.89
`

**Comment by ydye** [comment]
- can you try to use calico instead. Because in azure, we have to use weave. But in fact, calico will be better.
- Maybe you miss the ```:``` after ```-i```

**Comment by JosephKang** [comment]
> * can you try to use calico instead. Because in azure, we have to use weave. But in fact, calico will be better.
> * Maybe you miss the `:` after `-i`
- OK. I will change **kube_network_plugin** from _weave_ to _calico_ in ~/kubespray/inventory/mycluster/openpai.yml to redeploy the k8s
- @master-969205-iaas:> lsof -i:6783
1 ubuntu@master-969205-iaas:>

**Comment by JosephKang** [comment]
The k8s cluster deployment seems complete after change kube_ntework_plugin to calico
- `PLAY RECAP 
...
localhost                  : ok=1    changed=0    unreachable=0    failed=0
master-969205-iaas         : ok=621  changed=89   unreachable=0    failed=0
worker1-969211-iaas        : ok=388  changed=50   unreachable=0    failed=0
Tuesday 12 May 2020  10:15:31 +0000 (0:00:00.043)       0:05:54.966 ***********

Thanks

**Comment by ydye** [comment]
@fanyangCS Should we change the default network plugin to calico? Because azure is a special case.

**Comment by fanyangCS** [comment]
@ydye, agree. Let's change it.  Please make sure the update the document to explicitly call out how to handle Azure.

**Comment by ydye** [comment]
#4519
