### ISSUE TITLE
Some network problems encountered during installation

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#4516]
After trying installing PAI in Azure China, I encounter some problems during installation. Most of them are network-related. The installation uses the quick start script. This issue is a record.

1. [during k8s deployment] Cannot download `kubeadm` and `hyperkube`

    Solution: Modify `kubeadm_download_url` and `hyperkube_download_url` in [config](https://github.com/microsoft/pai/blob/master/contrib/kubespray/example/config.yml)

2. [during k8s deployment] Cannot pull images from gcr.io

    Solution: Modify `gcr_image_repo` and `kube_image_repo` to a mirror repo. I tried `gcr.azk8s.cn` and it worked. But, surprisingly, kubespray still tries to pull `gcr.io` after the modification. After some investigation, I found it is a problem with kubespray 2.11. In [this file](https://github.com/kubernetes-sigs/kubespray/blob/release-2.11/roles/download/defaults/main.yml), some images are hard coded to use `gcr.io` and `k8s.gcr.io` (e.g. tiller_image_repo). I fixed this issue manually then the k8s deployment succeeded.

3. [during PAI service deployment] Downloading speed from docker.io is slow
 
     I exprienced very slow downloading speed from docker.io. I tried some mirrors, but they didn't work. To address this problem, I set up a local registry and used a machine outside China to push images to the local registry.

4. [during PAI service deployment] Cannot access `raw.githubusercontent.com`

   We use file from `raw.githubusercontent.com` in [device-plugin](https://github.com/microsoft/pai/blob/master/src/device-plugin/deploy/start.sh.template#L28). Unfortunately, this site is blocked for me. I added a dns record for `githubusercontent.com` to `/etc/hosts`, then it worked.

**Comment by ydye** [comment]
Issue 1: I think u should updated it in doc
Issue 2: Have you try to use this configuration to overwirte the default value https://github.com/microsoft/pai/blob/master/contrib/kubespray/example/config.yml#L56
Issue 3: Use local cloud provider's container registry service
Issue 4: @abuccts

**Comment by hzy46** [comment]
> Issue 1: I think u should updated it in doc
> Issue 2: Have you try to use this configuration to overwirte the default value https://github.com/microsoft/pai/blob/master/contrib/kubespray/example/config.yml#L56
> Issue 3: Use local cloud provider's container registry service
> Issue 4: @abuccts

I have included solution for issue 1 and issue 2 in maunal.

For issue 2, modifying https://github.com/microsoft/pai/blob/master/contrib/kubespray/example/config.yml#L56 will help but as I mentioned, some images kubespray ignore this setting, such as https://github.com/kubernetes-sigs/kubespray/blob/release-2.11/roles/download/defaults/main.yml#L281 . I think it is a problem with kubespray 2.11.

**Comment by abuccts** [comment]
> [during PAI service deployment] Cannot access `raw.githubusercontent.com`
We use file from raw.githubusercontent.com in device-plugin. Unfortunately, this site is blocked for me. I added a dns record for githubusercontent.com to /etc/hosts, then it worked.

It's dns pollution from your ISP, you can either
* add a dns record
* or change your dns server to `114.114.114.114`

**Comment by VitoRazor** [comment]
> 尝试在Azure中国安装PAI后，在安装过程中遇到一些问题。它们大多数与网络有关。安装使用快速入门脚本。这个问题是一个记录。
> 
> 1. [在k8s部署期间]无法下载`kubeadm`和`hyperkube`
>    解决方案：修改`kubeadm_download_url`并`hyperkube_download_url`在[配置中](https://github.com/microsoft/pai/blob/master/contrib/kubespray/example/config.yml)
> 2. [在k8s部署期间]无法从gcr.io拉取映像
>    解决方案：修改`gcr_image_repo`并`kube_image_repo`复制到镜像存储库。我尝试了`gcr.azk8s.cn`，它起作用了。但是，令人惊讶的是，`gcr.io`修改后的kubespray仍然尝试拉。经过一番调查，我发现kubespray 2.11存在问题。在[此文件中](https://github.com/kubernetes-sigs/kubespray/blob/release-2.11/roles/download/defaults/main.yml)，一些图像被硬编码为使用`gcr.io`和`k8s.gcr.io`（例如，tiller_image_repo）。我手动解决了此问题，然后k8s部署成功。
> 3. [在PAI服务部署期间]从docker.io的下载速度很慢
>    我从docker.io遇到了非常慢的下载速度。我尝试了一些镜子，但是它们没有用。为了解决这个问题，我建立了一个本地注册表，并使用中国以外的计算机将映像推送到本地注册表。
> 4. [在PAI服务部署期间]无法访问 `raw.githubusercontent.com`
>    我们`raw.githubusercontent.com`在[device-plugin中](https://github.com/microsoft/pai/blob/master/src/device-plugin/deploy/start.sh.template#L28)使用from文件。不幸的是，这个网站对我来说被封锁了。我添加了DNS记录`githubusercontent.com`到`/etc/hosts`，然后它的工作。

Hello, I am currently blocked in the configuration of kubeadm_download_url and hyperkube_download_url. I don't know where to download these two tools in china. I hope you can help me. Thank you very much

**Comment by VitoRazor** [comment]
@hzy46
Hello, I am currently blocked in the configuration of kubeadm_download_url and hyperkube_download_url. I don't know where to download these two tools in china. I hope you can help me. Thank you very much

**Comment by hzy46** [comment]
> @hzy46
> Hello, I am currently blocked in the configuration of kubeadm_download_url and hyperkube_download_url. I don't know where to download these two tools in china. I hope you can help me. Thank you very much

Could you follow
https://openpai.readthedocs.io/en/latest/manual/cluster-admin/installation-faqs-and-troubleshooting.html#cannot-download-kubeadm-or-hyperkube  , and find a way to download the two files?

**Comment by VitoRazor** [comment]
> > @hzy46
> > Hello, I am currently blocked in the configuration of kubeadm_download_url and hyperkube_download_url. I don't know where to download these two tools in china. I hope you can help me. Thank you very much
> 
> Could you follow
> https://openpai.readthedocs.io/en/latest/manual/cluster-admin/installation-faqs-and-troubleshooting.html#cannot-download-kubeadm-or-hyperkube , and find a way to download the two files?

Thank you very much. I benefited a lot from your answer

**Comment by hzy46** [comment]
Closed. For china users, refer to https://openpai.readthedocs.io/en/latest/manual/cluster-admin/configuration-for-china.html
