### ISSUE TITLE
In quick start script, sometimes modifying `config` don't have effects

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#4521]
This happens in PAI service deployment. 

For example, the user finds he has a wrong branch name setting in [config](https://github.com/microsoft/pai/blob/4acfccf89bbe9738752aae766e2c559828e71f09/contrib/kubespray/example/config.yml#L3). After he modifies it,  running `quick-start-service.sh` ignores the changes. It still uses the previous config.

**Comment by fanyangCS** [comment]
closed and tracked in #5321
