### ISSUE TITLE
installation script doesn't stop when requirement check failed

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#4535]
Log:
![image](https://user-images.githubusercontent.com/7499023/81891176-61890400-95da-11ea-99c6-823a798ca3a2.png)

The environment checker failed and output an error message: "Failed: please blah blah", but the installation script continues with "setup k8s cluster".

The code is in:
https://github.com/microsoft/pai/blame/pai-0.18.y/contrib/kubespray/quick-start-kubespray.sh#L51

**Comment by ydye** [comment]
https://github.com/microsoft/pai/pull/4537/files
