### ISSUE TITLE
[Openpai service] Cannot start Openpai services (Node not found error)

### ISSUE THREAD

**Issue by JosephKang** [microsoft/pai#4539]
**Organization Name**: Advantech

**Short summary about the issue/question**:
Cannot start Openpai service at https://github.com/microsoft/pai/blob/master/contrib/kubespray/doc/step-by-step-openpai.md#start-openpai-service step

**Brief what process you are following**:
1. ./paictl.py service start
2. [pai_start.log](https://github.com/microsoft/pai/files/4627025/pai_start.log)
2.1. Node not found is shown, but the host is reachable via ssh as shown in the script log file.

**How to reproduce it**:
https://github.com/microsoft/pai/blob/master/contrib/kubespray/doc/step-by-step-openpai.md#start-openpai-service
1. Start up dev-box
2. Login the dev-box
3. Clone OpenPAI Code (v0.17.0)
4. Create layout.yaml and service-configuration.yaml under ~/pai-config/
5. Execute: ./paictl.py config push -p ~/pai-config/ -m service
6. Execute: ./paictl.py service start

**OpenPAI Environment**:
- OpenPAI version: v0.17.0
- Cloud provider or hardware configuration: OpenStack VM
- OS (e.g. from /etc/os-release): ubuntu 16.04.6
- Kernel (e.g. `uname -a`): 4.4.0-150-generic
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
Master: 192.168.211.11, 0 GPU, 8 Cores, 64GB RAMs
Worker: 192.168.211.22, 1 GPU, 4 Cores, 90GB RAMs,
- Others: Distributed step by step in https://github.com/microsoft/pai/blob/master/contrib/kubespray/doc/step-by-step.md

**Comment by fanyangCS** [comment]
This is because of the failure of the execution of this line:
 https://github.com/microsoft/pai/blob/a1332d361206f45e6c3180d9c334d47714e54c44/src/cluster-configuration/deploy/start.sh.template#L36

This is not because the worker node 192.168.211.22 is not reachable, but because k8s cannot see the node. 

@ydye, maybe you should add a precheck to ensure what k8s sees is the same as those in the cluster configuration file.

**Comment by JosephKang** [comment]
The role for worker(192.168.211.22) isn't shown correctly...
- ~/kubespray⟫ kubectl get nodes
NAME                     STATUS   ROLES    AGE   VERSION
pai2master-971908-iaas   Ready    master   23h   v1.15.11
pai2worker-971911-iaas   Ready    <none>   23h   v1.15.11

Did I mis-configure on of the following yaml files?
- worker.yml for https://github.com/microsoft/pai/blob/v0.17.0/contrib/kubespray/doc/step-by-step-k8s.md#create-docker-configuration-for-openpai ([worker.yml.txt](https://github.com/microsoft/pai/files/4632767/worker.yml.txt) , worker.yml.txt => worker.yml) 
- host.yml for https://github.com/microsoft/pai/blob/v0.17.0/contrib/kubespray/doc/step-by-step-k8s.md#deploy-k8s ( [host.yml.txt](https://github.com/microsoft/pai/files/4632787/host.yml.txt) , host.yml.txt => host.yml)

**Comment by fanyangCS** [comment]
I do not suggest to try v0.17, which is an internal release. The next release will be a major external release, which is due in a few days. I suggest to wait a while to try the next public version.

**Comment by hzy46** [comment]
Hi Joseph, could you provide your `layout.yaml`? I think the hostname in `layout.yaml` is wrong.

**Comment by JosephKang** [comment]
Please refer to the layout.yaml.txt for layout.yaml.
[layout.yaml.txt](https://github.com/microsoft/pai/files/4633178/layout.yaml.txt) 
In addition, I use **kubectl label** to label node pai2worker-971911-iaas role as worker and the do start pai service, but the error message is still the same.

**Comment by hzy46** [comment]
> Please refer to the layout.yaml.txt for layout.yaml.
> [layout.yaml.txt](https://github.com/microsoft/pai/files/4633178/layout.yaml.txt)
> In addition, I use **kubectl label** to label node pai2worker-971911-iaas role as worker and the do start pai service, but the error message is still the same.

`nodename: "192.168.211.11"` -> This should be `nodename: "pai2master-971908-iaas"`, and the same for the worker node.

**Comment by hzy46** [comment]
@JosephKang, by the way, the document you are following is actually obsoleted. We will have a formal v1.0.0 release next week. You can wait until it is released and follow our new [installation guide](https://openpai.readthedocs.io/).

**Comment by JosephKang** [comment]
@hzy46.

Thanks for point the incorrect setting in layout.yaml. Right now I am not blocked in the issue.

By the way, the installation guide in new release seems to be synced with the quick start of kubespray deployment. I tested it but still have some following issues. Might put the above issues if it still the same in the new release.
- Need to setup dev-box pkg dependency
- Some script reference is missed while executing quick-start-kubespray.sh and requirement.sh
- The deployment will still need some missing *.yml files in ~/pai-deploy/
