### ISSUE TITLE
[kubespray] api server was refused

### ISSUE THREAD

**Issue by edenbuaa** [microsoft/pai#4551]
Where to config the api-server of k8s deployed with kubespray? It reports:
```
 $ kubectl get namespace

The connection to the server localhost:8080 was refused - did you specify the right host or port? 
```

There seems not an item to config the api-server :(

**Comment by abuccts** [comment]
check [`~/.kube/config`](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#the-kubeconfig-environment-variable)

https://github.com/microsoft/pai/blob/a8585bfe8648bae8d06ea2429c9a8811f9a4dc01/contrib/kubespray/script/service-boot.sh#L31
