### ISSUE TITLE
When I run requirement.sh，error occurred

### ISSUE THREAD

**Issue by mtzfei** [microsoft/pai#4559]
**Organization Name**:

**Short summary about the issue/question**:
![微信图片_20200525140932](https://user-images.githubusercontent.com/60864045/82783649-7777ae00-9e91-11ea-8155-c0d3d946f164.png)

**Brief what process you are following**:
when i run "/bin/bash requirement.sh -m /home/ouc/master.csv -w /home/ouc/worker.csv -c /home/ouc/config",error occurred

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:v1.0.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by mtzfei** [comment]
Thanks，I already know the problem

**Comment by xuluanlin** [comment]
> Thanks，I already know the problem

I met the same problem. How do you solve it?

**Comment by mtzfei** [comment]
> > Thanks，I already know the problem
> 
> I met the same problem. How do you solve it?
- hosts: all
  gather_facts: false
  tasks:
    - name: setup
      setup:
      delegate_to: localhost

    - name: set ansible control host IP fact
      set_fact:
        ansible_control_host_address: "{{ hostvars[inventory_hostname]['ansible_eno1']['ipv4']['address'] }}"
      delegate_to: 127.0.0.1

    - name: "SSH test from dev-box to all machine of infra and worker"
      ping:

- hosts: localhost
  become: true
  become_user: root
  roles:
    - { role: requirement/devbox }
  vars:
    ansible_connection: local

- hosts: infra
  become: true
  become_user: root
  gather_facts: true
  roles:
    - { role: requirement/infra }

- hosts: worker
  become: true
  become_user: root
  gather_facts: true
  roles:
    - { role: requirement/worker }

**Comment by mtzfei** [comment]
> > Thanks，I already know the problem
> 
> I met the same problem. How do you solve it?

Modify "environment- check.yml ”Network card 
“ansible_control_host_address: "{{ hostvars[inventory_hostname]['ansible_eno1']['ipv4']['address'] }}"”

**Comment by k1ngcyk** [comment]
I think the wide available solution is to modify `GRUB_CMDLINE_LINUX=""` to `GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"` in `/etc/default/grub`, and then `sudo grub-mkconfig -o /boot/grub/grub.cfg`.
After that, the network interface name should be back to old school `eth0`

**Comment by abuccts** [comment]
@ydye @hzy46 

for the default ip address, https://github.com/microsoft/pai/blob/55a0b862bd897759f6c80aeb849be1fdde721406/contrib/kubespray/environment-check.yml#L11

could you check whether the following works?
```python
{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] | default(hostvars[inventory_hostname]['ansible_all_ipv4_addresses'][0]) }}
```
