### ISSUE TITLE
Should master node different with worker node?

### ISSUE THREAD

**Issue by k1ngcyk** [microsoft/pai#4566]
**Organization Name**: EnjoyMusic Technology

**Short summary about the issue/question**:

Should master node different with worker node? In other words, master node can only use CPU but can't with GPUs?

```
2020-05-26 06:28:21,485 [INFO] - openpai-generator.py:120 : AMD-Device-Plugin is not ready.
2020-05-26 06:28:21,485 [INFO] - openpai-generator.py:121 : Total: 1
2020-05-26 06:28:21,485 [INFO] - openpai-generator.py:122 : Ready: 0
2020-05-26 06:28:21,485 [INFO] - openpai-generator.py:168 : AMD-Device-Plugin is not ready yet. Please wait for a moment!
2020-05-26 06:28:31,588 [ERROR] - openpai-generator.py:196 : No worker node is detected. username and password to log in.
```

**Brief what process you are following**:

The handbook's installation guide

**How to reproduce it**:

Provide only one machine with GPU

**OpenPAI Environment**:
- OpenPAI version: v1.0.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): ubuntu 18.04
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by scarlett2018** [comment]
@k1ngcyk - would you mind share your Org's name? we are clustering issues with org names to better manage issues.

**Comment by hzy46** [comment]
According to the [installation guide](https://openpai.readthedocs.io/en/latest/manual/cluster-admin/installation-guide.html), you should have 3 separate machines: dev box, master and worker. The worker should have GPU. For dev box and master machine, you can use CPU-only nodes.

**Comment by k1ngcyk** [comment]
> @k1ngcyk - would you mind share your Org's name? we are clustering issues with org names to better manage issues.

ok, edited

**Comment by k1ngcyk** [comment]
> According to the [installation guide](https://openpai.readthedocs.io/en/latest/manual/cluster-admin/installation-guide.html), you should have at least 3 separate machines: dev box, master and worker. The worker should have GPU. For dev box and master machine, you can use CPU-only nodes.

ok, though I use this one machine for test. What I really care is that if I have GPU on the master machine, would these gpu be available in the PAI?

**Comment by hzy46** [comment]
You will not be able to use the GPU within PAI system. Because all computing jobs submitted in PAI will be scheduled to workers (not master.)

**Comment by k1ngcyk** [comment]
> You will not be able to use the GPU within PAI system. Because all computing jobs submitted in PAI will be scheduled to workers (not master.)

thanks for declaration. But I found same master and worker in your add node example in handbook: [here](https://openpai.readthedocs.io/en/latest/manual/cluster-admin/how-to-add-and-remove-nodes.html#how-to-add-nodes) which contains lines like 

```
...
  children:
    kube-master:
      hosts:
        origin1:
    kube-node:
      hosts:
        origin1:
        origin2:
...
```

so the master machine can also be a worker machine?

**Comment by hzy46** [comment]
It is k8s master & nodes, not PAI master & worker. PAI should have separate master and worker. They are different.

**Comment by k1ngcyk** [comment]
ok, thanks again for your reply.

**Comment by fanyangCS** [comment]
I hereby close the issue. Feel free to reopen it if you have further questions.
