### ISSUE TITLE
v1.0.0 install with nvidia-device-plugin not ready

### ISSUE THREAD

**Issue by xulzee** [microsoft/pai#4572]
Hi ,
   Today I tried to install v1.0.0, but there was an error all the time, I do n’t know what it did.
The ready one is master node.
  Is there any way to solve it? Or what exactly did this step do, I can do it manually

2020-05-27 12:52:07,565 [INFO] - openpai-generator.py:121 : Nvidia-Device-Plugin is not ready.
2020-05-27 12:52:07,565 [INFO] - openpai-generator.py:122 : Total: 3
2020-05-27 12:52:07,565 [INFO] - openpai-generator.py:123 : Ready: 1
2020-05-27 12:52:07,566 [INFO] - openpai-generator.py:159 : Nvidia-Device-Plugin is not ready yet. Please wait for a moment!

**Organization Name**:

**Short summary about the issue/question**:

**Brief what process you are following**:

- OpenPAI version:1.0.0
- OS (e.g. from /etc/os-release):ubuntu 16.04

**Comment by abuccts** [comment]
it [creates a device plugin](https://github.com/microsoft/pai/blob/d33d039b173ec954271533b5732d55ad92a03a7d/contrib/kubespray/script/service-boot.sh#L60) and checks the status [here](https://github.com/microsoft/pai/blob/d33d039b173ec954271533b5732d55ad92a03a7d/contrib/kubespray/script/service-boot.sh#L67)

could you find the pod names by `kubectl get --namespace=kube-system pods | grep nvidia-device-plugin` and get error logs by `kubectl logs --namespace=kube-system [POD NAME]` in the [dev-box](https://github.com/microsoft/pai/blob/d33d039b173ec954271533b5732d55ad92a03a7d/contrib/kubespray/script/service-boot.sh#L41)?

**Comment by xulzee** [comment]
Hi, I got this:

Error from server (BadRequest): container "nvidia-device-plugin-ctr" in pod "nvidia-device-plugin-daemonset-mjwnq" is waiting to start: ContainerCreating

Does this look like I didn't create this container?

**Comment by abuccts** [comment]
could you paste the output of pod description?
```sh
kubectl describe pod nvidia-device-plugin-daemonset-mjwnq -n kube-system
```

**Comment by xulzee** [comment]
Name:                 nvidia-device-plugin-daemonset-mjwnq
Namespace:            kube-system
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 gtx1080-2/192.168.1.94
Start Time:           Wed, 27 May 2020 17:42:51 +0800
Labels:               controller-revision-hash=74b655f448
                      name=nvidia-device-plugin-ds
                      pod-template-generation=1
Annotations:          scheduler.alpha.kubernetes.io/critical-pod: 
Status:               Pending
IP:                   
IPs:                  <none>
Controlled By:        DaemonSet/nvidia-device-plugin-daemonset
Containers:
  nvidia-device-plugin-ctr:
    Container ID:   
    Image:          nvidia/k8s-device-plugin:1.0.0-beta4
    Image ID:       
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/lib/kubelet/device-plugins from device-plugin (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-f7qch (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  device-plugin:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/device-plugins
    HostPathType:  
  default-token-f7qch:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-f7qch
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
                 nvidia.com/gpu:NoSchedule
Events:
  Type     Reason                  Age                     From                Message
  ----     ------                  ----                    ----                -------
  Warning  FailedCreatePodSandBox  48m (x1714 over 16h)    kubelet, gtx1080-2  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "836acf97f9d564a0f5dbb36a119505284833ee09ca69c9cd96df93abc45e6442" network for pod "nvidia-device-plugin-daemonset-mjwnq": NetworkPlugin cni failed to set up pod "nvidia-device-plugin-daemonset-mjwnq_kube-system" network: Get https://[10.192.0.1]:443/api/v1/namespaces/kube-system: dial tcp 10.192.0.1:443: i/o timeout
  Warning  FailedMount             42m                     kubelet, gtx1080-2  MountVolume.SetUp failed for volume "default-token-f7qch" : couldn't propagate object cache: timed out waiting for the condition
  Warning  FailedCreatePodSandBox  42m                     kubelet, gtx1080-2  Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "e5c3a25c8c9beec0c3bd4944d0de2175694e3e2fe15cd01569d03ed49daa1e70" network for pod "nvidia-device-plugin-daemonset-mjwnq": NetworkPlugin cni failed to set up pod "nvidia-device-plugin-daemonset-mjwnq_kube-system" network: fork/exec /opt/cni/bin/calico: text file busy, failed to clean up sandbox container "e5c3a25c8c9beec0c3bd4944d0de2175694e3e2fe15cd01569d03ed49daa1e70" network for pod "nvidia-device-plugin-daemonset-mjwnq": NetworkPlugin cni failed to teardown pod "nvidia-device-plugin-daemonset-mjwnq_kube-system" network: fork/exec /opt/cni/bin/calico: text file busy]
  Warning  FailedCreatePodSandBox  41m                     kubelet, gtx1080-2  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "685d05ce25006c8532eaa6de4f4c22d68ce336b72d5ebae1b12cf5447b238014" network for pod "nvidia-device-plugin-daemonset-mjwnq": NetworkPlugin cni failed to set up pod "nvidia-device-plugin-daemonset-mjwnq_kube-system" network: Get https://[10.192.0.1]:443/api/v1/namespaces/kube-system: dial tcp 10.192.0.1:443: i/o timeout
  Warning  FailedCreatePodSandBox  40m                     kubelet, gtx1080-2  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "a5699ec8f944aba16588baba3f94d06a25505010c08f690295df09b65462cc74" network for pod "nvidia-device-plugin-daemonset-mjwnq": NetworkPlugin cni failed to set up pod "nvidia-device-plugin-daemonset-mjwnq_kube-system" network: Get https://[10.192.0.1]:443/api/v1/namespaces/kube-system: dial tcp 10.192.0.1:443: i/o timeout
  Warning  FailedCreatePodSandBox  40m                     kubelet, gtx1080-2  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "b8e32bdbcebb1ab372b58d722d013da27c1a0e80f72a56def802734d90ede85d" network for pod "nvidia-device-plugin-daemonset-mjwnq": NetworkPlugin cni failed to set up pod "nvidia-device-plugin-daemonset-mjwnq_kube-system" network: Get https://[10.192.0.1]:443/api/v1/namespaces/kube-system: dial tcp 10.192.0.1:443: i/o timeout
  Warning  FailedCreatePodSandBox  39m                     kubelet, gtx1080-2  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "4990b663a1dc8cf3301636eccd958d0ff71c4a95ec83f88e1a4cdc6b4115cd20" network for pod "nvidia-device-plugin-daemonset-mjwnq": NetworkPlugin cni failed to set up pod "nvidia-device-plugin-daemonset-mjwnq_kube-system" network: Get https://[10.192.0.1]:443/api/v1/namespaces/kube-system: dial tcp 10.192.0.1:443: i/o timeout
  Warning  FailedCreatePodSandBox  39m                     kubelet, gtx1080-2  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "c1ff329216d17fa9a69d5501a6c872523352e304c26841dfa8cf1def1e0a4f3b" network for pod "nvidia-device-plugin-daemonset-mjwnq": NetworkPlugin cni failed to set up pod "nvidia-device-plugin-daemonset-mjwnq_kube-system" network: Get https://[10.192.0.1]:443/api/v1/namespaces/kube-system: dial tcp 10.192.0.1:443: i/o timeout
  Warning  FailedCreatePodSandBox  38m                     kubelet, gtx1080-2  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "3cecdd4d189a4ea5eae80fdd4f56ed40039c930a2f4954d30fa98138b6e07529" network for pod "nvidia-device-plugin-daemonset-mjwnq": NetworkPlugin cni failed to set up pod "nvidia-device-plugin-daemonset-mjwnq_kube-system" network: Get https://[10.192.0.1]:443/api/v1/namespaces/kube-system: dial tcp 10.192.0.1:443: i/o timeout
  Warning  FailedCreatePodSandBox  38m                     kubelet, gtx1080-2  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "05cde1578212207512e5f825a55edcc79693233e574be70a2802e7e2c19376dd" network for pod "nvidia-device-plugin-daemonset-mjwnq": NetworkPlugin cni failed to set up pod "nvidia-device-plugin-daemonset-mjwnq_kube-system" network: Get https://[10.192.0.1]:443/api/v1/namespaces/kube-system: dial tcp 10.192.0.1:443: i/o timeout
  Warning  FailedCreatePodSandBox  37m                     kubelet, gtx1080-2  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "7f1092795a16a443ca5c8873665f29f52755b5dec3c8c9f77bedea8d9104d7d2" network for pod "nvidia-device-plugin-daemonset-mjwnq": NetworkPlugin cni failed to set up pod "nvidia-device-plugin-daemonset-mjwnq_kube-system" network: Get https://[10.192.0.1]:443/api/v1/namespaces/kube-system: dial tcp 10.192.0.1:443: i/o timeout
  Normal   SandboxChanged          36m (x13 over 42m)      kubelet, gtx1080-2  Pod sandbox changed, it will be killed and re-created.
  Warning  FailedCreatePodSandBox  16m (x39 over 37m)      kubelet, gtx1080-2  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "4d75f8b6f22d84413ef82cb8d404860aa08a5a1187fecad2fb7482f2cc055111" network for pod "nvidia-device-plugin-daemonset-mjwnq": NetworkPlugin cni failed to set up pod "nvidia-device-plugin-daemonset-mjwnq_kube-system" network: Get https://[10.192.0.1]:443/api/v1/namespaces/kube-system: dial tcp 10.192.0.1:443: i/o timeout
  Warning  FailedCreatePodSandBox  13m                     kubelet, gtx1080-2  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "b1cd041003d4b0518023476c1c6e79825e980d3b3a3a3ad36d8ad197b4f4aae3" network for pod "nvidia-device-plugin-daemonset-mjwnq": NetworkPlugin cni failed to set up pod "nvidia-device-plugin-daemonset-mjwnq_kube-system" network: Get https://[10.192.0.1]:443/api/v1/namespaces/kube-system: dial tcp 10.192.0.1:443: i/o timeout
  Warning  FailedCreatePodSandBox  12m                     kubelet, gtx1080-2  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "aaa8ff4c88674b4fb58342ff6d2fba0fa2be6c61607ef64372c057b937d478ae" network for pod "nvidia-device-plugin-daemonset-mjwnq": NetworkPlugin cni failed to set up pod "nvidia-device-plugin-daemonset-mjwnq_kube-system" network: Get https://[10.192.0.1]:443/api/v1/namespaces/kube-system: dial tcp 10.192.0.1:443: i/o timeout
  Warning  FailedCreatePodSandBox  11m                     kubelet, gtx1080-2  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "d61f0d8d7aa2d52c91b5d033faa3f7a59df7c9c15fdbd39bb7c895961c48cc4d" network for pod "nvidia-device-plugin-daemonset-mjwnq": NetworkPlugin cni failed to set up pod "nvidia-device-plugin-daemonset-mjwnq_kube-system" network: Get https://[10.192.0.1]:443/api/v1/namespaces/kube-system: dial tcp 10.192.0.1:443: i/o timeout
  Warning  FailedCreatePodSandBox  11m                     kubelet, gtx1080-2  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "53c3b474dcec03124693383cb976d6e0979111eb83b42515ee7d945208b81a3f" network for pod "nvidia-device-plugin-daemonset-mjwnq": NetworkPlugin cni failed to set up pod "nvidia-device-plugin-daemonset-mjwnq_kube-system" network: Get https://[10.192.0.1]:443/api/v1/namespaces/kube-system: dial tcp 10.192.0.1:443: i/o timeout
  Warning  FailedCreatePodSandBox  10m                     kubelet, gtx1080-2  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "f3f4ac690311d4a738586ffc9c72e786365def2c62d551724306d9da48266473" network for pod "nvidia-device-plugin-daemonset-mjwnq": NetworkPlugin cni failed to set up pod "nvidia-device-plugin-daemonset-mjwnq_kube-system" network: Get https://[10.192.0.1]:443/api/v1/namespaces/kube-system: dial tcp 10.192.0.1:443: i/o timeout
  Warning  FailedCreatePodSandBox  10m                     kubelet, gtx1080-2  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "8287c42c85c20218533baeb02895881cd5c4f8ccf8d2ccdcf8908f70b83773a3" network for pod "nvidia-device-plugin-daemonset-mjwnq": NetworkPlugin cni failed to set up pod "nvidia-device-plugin-daemonset-mjwnq_kube-system" network: Get https://[10.192.0.1]:443/api/v1/namespaces/kube-system: dial tcp 10.192.0.1:443: i/o timeout
  Warning  FailedCreatePodSandBox  9m49s                   kubelet, gtx1080-2  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "071f181ecb3089d559c29ec19ce71d2096591504ef88d018c6083d484bfb7548" network for pod "nvidia-device-plugin-daemonset-mjwnq": NetworkPlugin cni failed to set up pod "nvidia-device-plugin-daemonset-mjwnq_kube-system" network: Get https://[10.192.0.1]:443/api/v1/namespaces/kube-system: dial tcp 10.192.0.1:443: i/o timeout
  Warning  FailedCreatePodSandBox  9m17s                   kubelet, gtx1080-2  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "ce68f4ff5fe4ae690dbec8a705a97fa768c39f63b786830e92fd4e9c61f4fa8a" network for pod "nvidia-device-plugin-daemonset-mjwnq": NetworkPlugin cni failed to set up pod "nvidia-device-plugin-daemonset-mjwnq_kube-system" network: Get https://[10.192.0.1]:443/api/v1/namespaces/kube-system: dial tcp 10.192.0.1:443: i/o timeout
  Warning  FailedCreatePodSandBox  8m45s                   kubelet, gtx1080-2  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "0e96d9aa3ff3e69ffb6242c3cbe104cdeb6398873db1e5fb0720c4490a8ec4d9" network for pod "nvidia-device-plugin-daemonset-mjwnq": NetworkPlugin cni failed to set up pod "nvidia-device-plugin-daemonset-mjwnq_kube-system" network: Get https://[10.192.0.1]:443/api/v1/namespaces/kube-system: dial tcp 10.192.0.1:443: i/o timeout
  Normal   SandboxChanged          7m6s (x13 over 13m)     kubelet, gtx1080-2  Pod sandbox changed, it will be killed and re-created.
  Warning  FailedCreatePodSandBox  3m21s (x10 over 8m13s)  kubelet, gtx1080-2  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "c3d951d197a5d9dad90847ba11c09307a21257774d70d9c892f90ab4567ab6e5" network for pod "nvidia-device-plugin-daemonset-mjwnq": NetworkPlugin cni failed to set up pod "nvidia-device-plugin-daemonset-mjwnq_kube-system" network: Get https://[10.192.0.1]:443/api/v1/namespaces/kube-system: dial tcp 10.192.0.1:443: i/o timeout

**Comment by abuccts** [comment]
> Warning FailedCreatePodSandBox 48m (x1714 over 16h) kubelet, gtx1080-2 (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "836acf97f9d564a0f5dbb36a119505284833ee09ca69c9cd96df93abc45e6442" network for pod "nvidia-device-plugin-daemonset-mjwnq": NetworkPlugin cni failed to set up pod "nvidia-device-plugin-daemonset-mjwnq_kube-system" network: Get https://[10.192.0.1]:443/api/v1/namespaces/kube-system: dial tcp 10.192.0.1:443: i/o timeout

seems a k8s cni issue, @ydye could you help to have a look?

**Comment by ydye** [comment]
What's your network plugin. Calico or Weave

**Comment by xulzee** [comment]
Hi, I use calico. And my environment is physical(with two worker and one master). thanks

**Comment by ydye** [comment]
Can you check the output of kubeproxy?
You can find the service with command 
```
kubectl get pod -n kube-system | grep proxy
```

I guess that's the same problem as you come accross. https://github.com/projectcalico/calico/issues/2695

**Comment by xulzee** [comment]
Hello, after I cleaned up kubespreay and rerun quick start kuberpray and quick start service, there is no problem.

**Comment by abuccts** [comment]
Glad to hear.

Close this issue, please feel free to reopen if you have additional questions.

**Comment by HaoLiuHust** [comment]
> Hello, after I cleaned up kubespreay and rerun quick start kuberpray and quick start service, there is no problem.

Hello, how to clean up kubespray?
