### ISSUE TITLE
Machine-sku issue

### ISSUE THREAD

**Issue by andrewsen13** [microsoft/pai#4573]
**OpenPAI Environment**:
- OpenPAI version: v0.14.0
- OS (e.g. from /etc/os-release): Ubuntu 18.04

**The main problem**:
During the installation we create `layout.yaml` where we add information about worker machines. I'm interested in knowing, can we allocate different worker nodes the same `machine-type`? 
For example, I have 1 master and 6 worker nodes (3 of them with Tesla K80 and 3 of them Tesla V100). My question is can I add the same `machine-type` for these 3 Tesla K80 and another one `machine-type` for Tesla V100? Will be there something wrong?

Another issue is how to manage an allocation of my job to the certain GPU type? 
For example, I'm submitting a job and I want to allocate it to Tesla V100 with 32 Gb, not to Tesla K80 with 24 Gb, how to choose it? Should I create individual cluster (dedicated cluster) for each GPU type?

**Comment by abuccts** [comment]
> During the installation we create layout.yaml where we add information about worker machines. I'm interested in knowing, can we allocate different worker nodes the same machine-type?

It's OK, the `machine-type` isn't actually used in YARN scheduler.

> Another issue is how to manage an allocation of my job to the certain GPU type?

For v0.14.0 which uses YARN scheduler, we didn't support different GPU types, using dedicated vc is a workaround.

We suggest you to use the latest [v1.0.0](https://github.com/microsoft/pai/releases/tag/v1.0.0) which includes a [GPU scheduler](https://github.com/microsoft/hivedscheduler) and fits your need.

**Comment by andrewsen13** [comment]
@abuccts, I have some problem with dedicated vc.
I use the command `python node_maintain.py dedicated-vc add -m {master_ip} -v {added_vc_name}` and it shows me output with error:

    - HTTPError: 400 Client Error: Bad Request for url: http://master-ip:9186/api/v1/token

The page `http://master-ip:9186/api/v1/token`:

    - {"code":"NoApiError","message":"API /api/v1/token is not found."}

**Comment by abuccts** [comment]
could you change the following line https://github.com/microsoft/pai/blob/2472b37792092e448b4050c776b35acb3e6ffafb/src/tools/operator_wrapper/restserver_operator.py#L53 to `api_path = "/api/v1/authn/basic/login"` and try again?

**Comment by andrewsen13** [comment]
@abuccts, There are the same error and the output on the web page:

    - {"code":"NoApiError","message":"API /api/v1/authn/basic/login is not found."}

**Comment by abuccts** [comment]
the api is `POST /api/v1/authn/basic/login` instead of `GET /api/v1/authn/basic/login`, the second one does not exist indeed if you only tried to send a http get request in your browser

**Comment by andrewsen13** [comment]
@abuccts, do you mean this POST?

![image](https://user-images.githubusercontent.com/56435717/83139410-01738100-a0f5-11ea-9d0b-32a9f7ccf9cf.png)

How to reach it properly?
`HTTPError: 400 Client Error: Bad Request for url: http://master-ip:9186/api/v1/authn/basic/login`

**Comment by abuccts** [comment]
could you get result from the following command?
```sh
curl -X POST -d "username=USERNAME" -d "password=PASSWORD" http://master-ip:9186/api/v1/authn/basic/login 
```

**Comment by scarlett2018** [comment]
> @abuccts, do you mean this POST?
> 
> ![image](https://user-images.githubusercontent.com/56435717/83139410-01738100-a0f5-11ea-9d0b-32a9f7ccf9cf.png)
> 
> How to reach it properly?
> `HTTPError: 400 Client Error: Bad Request for url: http://master-ip:9186/api/v1/authn/basic/login`

Hi @andrewsen13 - would you mind share the Org name to us? we are adding tags to the issues to clustering issues by user's org.

**Comment by andrewsen13** [comment]
@abuccts,
> could you get result from the following command?
> 
> ```shell
> curl -X POST -d "username=USERNAME" -d "password=PASSWORD" http://master-ip:9186/api/v1/authn/basic/login 
> ```

I tried curl command with my new user which I created using command `python node_maintain.py user set -u {admin_username} -p {admin_password} -m {master_ip}`, but there was an error: `{"code":"NoUserError","message":"User undefined is not found."}`. 

After this, I tried login and password for rest server which `admin` and `admin-password` as default, and there was a good connection, output:
 
`{"user":"admin","token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiYWRtaW4iOnRydWUsImlhdCI6MTU5MTAxMzg1NiwiZXhwIjoxNTkxNjE4NjU2fQ.dZxJ3WHPcF0NOojVRKW6V2mJhl661OVEaVuIeX3Pc0o","admin":true,"hasGitHubPAT":false}`

However, there is the same error:

    - HTTPError: 400 Client Error: Bad Request for url: http://master-ip:9186/api/v1/authn/basic/login

**Comment by abuccts** [comment]
I think there're some misunderstandings.

1. The account in `python node_maintain.py user set -u {admin_username} -p {admin_password} -m {master_ip}` is your **rest server/webportal account**, which is used to login webportal. I don't know which account you used before.

2. `/bin/sh: 1: yarn: not found` means **hadoop yarn** cli instead of yarnpkg in nodejs, pls run the script in dev-box docker. You could use the following command to check it exists:
    ```sh
    $ which yarn
    /usr/local/hadoop/bin/yarn
    ```

**Comment by andrewsen13** [comment]
@abuccts,
1. I've just read [here](https://github.com/microsoft/pai/blob/v0.14.0/docs/tools/dedicated_vc.md)  how to create a dedicated VC and there are no information that I should use credentials from the rest server/webportal, only that I have to create a user. By the way, I understood this information and I will use the admin account for rest server in the future. Thanks!
2. I use a SingleBox deployment using [this instruction](https://github.com/microsoft/pai/blob/v0.14.0/docs/pai-management/doc/how-to-install-depdencey.md) where I didn't create a dev-box docker image or container. I only installed basic components. 
I had an output of `which yarn` when I installed yarn using `npm install -g yarn` like this: `/usr/local/bin/yarn`. However, after your message here I've deleted yarn using `npm uninstall -g yarn` and now my output `which yarn` is empty.


How to define yarn to `/usr/local/hadoop/bin/yarn`?

**Comment by abuccts** [comment]
You could refer to dev-box's Dockerfile to install hadoop
https://github.com/microsoft/pai/blob/2472b37792092e448b4050c776b35acb3e6ffafb/src/dev-box/build/dev-box.dockerfile#L67-L79
then export the binary directory to `PATH` and check
```sh
$ export PATH=$PATH:/usr/local/hadoop/bin
$ which yarn
```

**Comment by andrewsen13** [comment]
@abuccts,

Oh my god... /_- 
I just didn't add `export PATH=$PATH:/usr/local/hadoop/bin`, but my configuration of hadoop was the same.
At this moment, I see the path of yarn like this:

     /usr/local/hadoop/bin/yarn

Also, finally, I've created dedicated VC and everything is working fine.

Thank you so much for your help and your time!
