### ISSUE TITLE
Paictl usage in OpenPAI v1.0.0 

### ISSUE THREAD

**Issue by JosephKang** [microsoft/pai#4583]
**Organization Name**:
Advantech

**Short summary about the issue/question**:
Fail to use paictl.py script after  v1.0.0 cluster installation.

**Brief what process you are following**:
1. Follow the installation in https://openpai.readthedocs.io/en/release-1.0.0/manual/cluster-admin/installation-guide.html
2. Try to use "paictl.py config get-id" on dev-box but failed due to python library not found error.

**How to reproduce it**:
Deploy a v1.0.0 cluster. 

**OpenPAI Environment**:
- OpenPAI version: v1.0.0
- Cloud provider or hardware configuration: Private OpenStack VMs
- OS (e.g. from /etc/os-release): Ubuntu 16.04.6 LTS
- Kernel (e.g. `uname -a`): 4.4.0-150-generic 
- Hardware (e.g. core number, memory size, storage size, GPU type etc.): 2CPU/16GRAM/100G SSD
- Others: 

**Anything else we need to know**:

A priori host library upgrading for paictl.py installation that works for OpenPAI v0.10.1 and v0.17.0 but failed in V1.0.0 installed platform

sudo apt-get -y install \
      nano \
      vim \
      joe \
      wget \
      curl \
      jq \
      gawk \
      psmisc \
      python \
      python-yaml \
      python-jinja2 \
      python-urllib3 \
      python-tz \
      python-nose \
      python-prettytable \
      python-netifaces \
      python-dev \
      python-pip \
      python-mysqldb \
      openjdk-8-jre \
      openjdk-8-jdk \
      openssh-server \
      openssh-client \
      git \
      bash-completion \
      inotify-tools \
      rsync \
      realpath \
      net-tools \
      python3-pip

pip install --upgrade pip
pip install --upgrade python-etcd docker kubernetes paramiko==2.6.0 GitPython future urllib3 ipaddress
sudo -H pip3 install --upgrade pip
sudo python -m easy_install --upgrade pyOpenSSL
pip3 install kubernetes pyasn1

**Comment by hzy46** [comment]
Could you provide detailed error content? I think the dependency for paictl.py shouldn't change too much.

**Comment by abuccts** [comment]
what's the output of `python -V`? you need to use python2 for `paictl.py`

**Comment by JosephKang** [comment]
:~/pai⟫ python -V
Python 2.7.12

- Error message before installing host dependency
ubuntu@devbox0529-996541-iaas:~/pai⟫ ./paictl.py config get-id
Traceback (most recent call last):
  File "./paictl.py", line 29, in <module>
    from deployment.paiLibrary.common import file_handler
  File "/home/ubuntu/pai/deployment/paiLibrary/common/file_handler.py", line 19, in <module>
    import yaml
ImportError: No module named yaml

- Host dependency installation steps
sudo apt-get -y install \
      nano \
      vim \
      joe \
      wget \
      curl \
      jq \
      gawk \
      psmisc \
      python \
      python-yaml \
      python-jinja2 \
      python-urllib3 \
      python-tz \
      python-nose \
      python-prettytable \
      python-netifaces \
      python-dev \
      python-pip \
      python-mysqldb \
      openjdk-8-jre \
      openjdk-8-jdk \
      openssh-server \
      openssh-client \
      git \
      bash-completion \
      inotify-tools \
      rsync \
      realpath \
      net-tools \
      python3-pip
pip install --upgrade pip
pip install --upgrade python-etcd docker kubernetes paramiko==2.6.0 GitPython future urllib3 ipaddress
sudo -H pip3 install --upgrade pip
sudo python -m easy_install --upgrade pyOpenSSL
sudo apt-get install libblas-dev libatlas-base-dev
sudo apt-get install python-paramiko
sudo apt-get install python-etcd

- Error message after installing host dependency
~/pai⟫ ./paictl.py config get-id
Traceback (most recent call last):
  File "./paictl.py", line 32, in <module>
    from deployment.checkCmd import CheckCmd
  File "/home/ubuntu/pai/deployment/checkCmd.py", line 1, in <module>
    from clusterObjectModel.cluster_object_model import cluster_object_model
  File "/home/ubuntu/pai/deployment/clusterObjectModel/cluster_object_model.py", line 30, in <module>
    from .mainParser import kubernetes as pai_com_kubernetes
  File "/home/ubuntu/pai/deployment/clusterObjectModel/mainParser/kubernetes.py", line 22, in <module>
    from ...k8sPaiLibrary.maintainlib import common as pai_k8s_common
  File "/home/ubuntu/pai/deployment/k8sPaiLibrary/maintainlib/common.py", line 32, in <module>
    import etcd
  File "/usr/lib/python2.7/dist-packages/etcd/__init__.py", line 290, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 54, in <module>
    import OpenSSL.SSL
  File "build/bdist.linux-x86_64/egg/OpenSSL/__init__.py", line 8, in <module>
  File "build/bdist.linux-x86_64/egg/OpenSSL/crypto.py", line 15, in <module>
  File "build/bdist.linux-x86_64/egg/OpenSSL/_util.py", line 152, in <module>
TypeError: from_buffer() cannot return the address of the raw string within a str or unicode or bytearray object

**Comment by abuccts** [comment]
you installed the wrong paramiko by `sudo apt-get install python-paramiko`,
pls remove all related packages
```sh
apt-get purge python-paramiko
pip uninstall paramiko
```
then install it again
```sh
pip install paramiko==2.6.0
python -m easy_install --upgrade pyOpenSSL
```

**Comment by JosephKang** [comment]
@abuccts ,

Thanks for the library patching suggestion, and the paictl.py works after some additional steps with your suggestion.
- sudo -H pip2 install --upgrade pip  #It recovers some previous incorrect pip binding.
- pip install kubernetes
- pip install gitpython
