### ISSUE TITLE
v1.0.0 Doc error

### ISSUE THREAD

**Issue by xulzee** [microsoft/pai#4588]
In `https://openpai.readthedocs.io/en/latest/manual/cluster-admin/how-to-add-and-remove-nodes.html` ,the remove nodes part.

current run code is 
```
ansible-playbook -i inventory/mycluster/hosts.yml upgrade-cluster.yml --become --become-user=root  --limit=a,b -e "@inventory/mycluster/openpai.yml"
```

I think maybe it should be
```
ansible-playbook -i inventory/mycluster/hosts.yml remove-node.yml --become --become-user=root  --limit=a,b -e "@inventory/mycluster/openpai.yml"
```

**Comment by hzy46** [comment]
I think `upgrade-cluster`.yaml also works. @ydye Do you have any suggestion?

**Comment by fanyangCS** [comment]
close as no further response.
