### ISSUE TITLE
No need to use template here. it should be removed.

### ISSUE THREAD

**Issue by ydye** [Microsoft/pai#459]
https://github.com/Microsoft/pai/blob/857787807bf8a4e343d0c6ddf6f0c5dd89634ef8/service-deployment/src/gpu-exporter/start.sh.template#L20

**Comment by ydye** [comment]
1) Image should be stateless
2) If this image is relative to a specific cluster-configuration, if a user with a different cluster-configuration want to pull from a public registry, it will cause an error

**Comment by YanjieGao** [comment]
after use new exporter and deprecated

**Comment by YanjieGao** [comment]
removed
