### ISSUE TITLE
Error starting openpai service

### ISSUE THREAD

**Issue by mtzfei** [microsoft/pai#4590]
**Organization Name**:qingdoaxinuozhineng

**Short summary about the issue/question**:
Error starting openpai service
/bin/bash quick-start-service.sh -m /path/to/master.csv -w /path/to/worker.csv -c /path/to/config
![w2](https://user-images.githubusercontent.com/60864045/83399451-d4480b00-a433-11ea-9e6a-44a6e2ca0943.png)

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by k1ngcyk** [comment]
Same here. Since error is `svn` not found, a simple solution is to add `apt-get install subversion` in `script/service-boot.sh`, for example, at Line 44.

**Comment by abuccts** [comment]
`apt-get install subversion` could fix it, but the `svn` is only included in `master` and `v1.0.1` instead of `v1.0.0`.

@mtzfei @k1ngcyk Could you share the [`branch_name`](https://github.com/microsoft/pai/blob/v1.0.0/contrib/kubespray/example/config.yml#L3) you used in config?

**Comment by k1ngcyk** [comment]
@abuccts branch_name: pai-1.0.y

**Comment by abuccts** [comment]
> branch_name: pai-1.0.y

Thanks for reporting. It's suggested to use `v1.0.0` which points to a specific commit and won't change, instead of `pai-1.0.y`.

@hzy46 pls help to fix your docs accordingly.

**Comment by hzy46** [comment]
OK, I will fix the doc accordingly.

**Comment by hzy46** [comment]
@abuccts I found this problem can't be resolved by changing the doc. Because in quick start script config, there is setting like `branch_name: pai-1.0.y`. So the code used during deployment is always `pai-1.0.y`.

Add @ydye for help.

**Comment by ydye** [comment]
> @abuccts I found this problem can't be resolved by changing the doc. Because in quick start script config, there is setting like `branch_name: pai-1.0.y`. So the code used during deployment is always `pai-1.0.y`.
> 
> Add @ydye for help.

That‘s my design. If you change to v1.0.0, than this version will be used.

**Comment by fanyangCS** [comment]
close as no further response.
