### ISSUE TITLE
Error when build dev-box

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#4593]
How to reproduce:

```bash
docker build -t dev-box -f src/dev-box/build/dev-box.common.dockerfile src/dev-box
```

![image](https://user-images.githubusercontent.com/7499023/83475324-b1b00380-a4c0-11ea-9b0c-7c7d89c36128.png)

**Comment by fanyangCS** [comment]
https://github.com/microsoft/pai/pull/4595
