### ISSUE TITLE
rest-service start error

### ISSUE THREAD

**Issue by zlwzlwzlw** [microsoft/pai#4594]
**Short summary about the issue/question**:
![image](https://user-images.githubusercontent.com/33961256/83476292-e58c2880-a4c2-11ea-8067-6c84d3b9a2eb.png)

i check rest-service error is:
2020-06-02T03:12:02.846Z [INFO] Create admin group configured in configuration. 
[HPM] Proxy created: /  ->  Url {
  protocol: 'http:',
  slashes: true,
  auth: null,
  host: '192.168.33.119:8080',
  port: '8080',
  hostname: '192.168.33.119',
  hash: null,
  search: null,
  query: null,
  pathname: '/',
  path: '/',
  href: 'http://192.168.33.119:8080/' }
2020-06-02T03:12:03.436Z [INFO] config: {"env":"production","logLevel":"debug","serverPort":8080,"jwtSecret":"pai-secret"} 
2020-06-02T03:12:03.444Z [INFO] RESTful API server starts on port 8080 
2020-06-02T03:12:03.464Z [ERROR] Failed to create admin group configured in configuration. 
{ Error: connect EHOSTUNREACH 192.168.33.119:8080
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.33.119',
  port: 8080,
  config: 
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,

**Brief what process you are following**:
using "python paictl.py service start " and rest-service error

**OpenPAI Environment**:
- OpenPAI version:0.14.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):centos7.6
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):24cpu,46G
- Others:

**Anything else we need to know**:

**Comment by abuccts** [comment]
seems apiserver is unavailable, is `192.168.33.119` master ip?
pls try the following to check healthiness
```sh
curl 192.168.33.119:8080/healthz
```

@ydye could you help to take a look?

**Comment by zlwzlwzlw** [comment]
I curl 192.168.33.119:8080/healthz is ok
and curl http://192.168.31.119:8080/api/v1/namespaces/pai-group/secrets
![QQ图片20200602173904](https://user-images.githubusercontent.com/33961256/83505266-1e92c000-a4f8-11ea-892b-3157f35e101f.png)

**Comment by ydye** [comment]
How did you deploy kubernetes?

**Comment by zlwzlwzlw** [comment]
first start docker:  docker run -itd \
        -e COLUMNS=$COLUMNS -e LINES=$LINES -e TERM=$TERM \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v /pathConfiguration:/cluster-configuration  \
        -v /hadoop-binary:/hadoop-binary \
        -v /etc/localtime:/etc/localtime:ro \
        --pid=host \
        --privileged=true \
        --net=host \
        --name=dev-box \
        docker.io/openpai/dev-box:v0.14.0

second config:  python paictl.py config generate -i /pai/deployment/quick-start/quick-start.yaml -o ~/pai-config -f

third start kubernetes:  python paictl.py cluster k8s-bootup -p ~/pai-config
start rest-service and curl http://192.168.31.119:8080/api/v1/namespaces/pai-group/secrets the item is empty

**Comment by ydye** [comment]
Can you show me the output of the following command in your master node
```
sudo docker ps -a
```

**Comment by zlwzlwzlw** [comment]
i solve it that is a Network connection problem, thanks
