### ISSUE TITLE
set imagePullPolicy = always.

### ISSUE THREAD

**Issue by ydye** [Microsoft/pai#460]
https://github.com/Microsoft/pai/blob/857787807bf8a4e343d0c6ddf6f0c5dd89634ef8/service-deployment/bootstrap/prometheus/node-exporter-ds.yaml.template#L1

like this: https://github.com/Microsoft/pai/blob/master/service-deployment/bootstrap/hadoop-service/hadoop-name-node.yaml.template#L35

**Comment by YanjieGao** [comment]
added
