### ISSUE TITLE
Submitting job setting GPU count to 0 result in error

### ISSUE THREAD

**Issue by k1ngcyk** [microsoft/pai#4601]
**Organization Name**: EnjoyMusic Technology

**Short summary about the issue/question**:
Submitting CPU only job by setting GPU count to 0 result in error: 
Error: Exceed GPU quota in default VC.

If there is no CPU only VC set up, how to submit CPU only jobs?

<img width="758" alt="Screen Shot 2020-06-03 at 3 48 55 PM" src="https://user-images.githubusercontent.com/65638404/83611070-0b90f600-a5b3-11ea-8ac9-ea21e2d660c6.png">
**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version: v1.0.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by yqwang-ms** [comment]
> If there is no CPU only VC set up, how to submit CPU only jobs?
For now, you cannot. But you can submit jobs with both GPU and CPU > 0, but do not use the GPUs.
We will improve this in future release.

Below error msg is confusing (since your job GPU = 0), we will fix it in WebUI ASAP
> ![image](https://user-images.githubusercontent.com/32826762/83635848-7f44fa00-a5d7-11ea-85db-1c8690915909.png)

**Comment by fanyangCS** [comment]
closed and tracked in #4602
