### ISSUE TITLE
Swapoff exception

### ISSUE THREAD

**Issue by andrewsen13** [microsoft/pai#4611]
**OpenPAI Environment**:
- OpenPAI version: 0.14.0
- OS (e.g. from /etc/os-release): Ubuntu 18.04

**The main problem**:
I want to add few machines which support a swap space, because any developer should have an opportunity to work using a machine with GPU in some dev environment (PyCharm, Android Studio etc.). 
However, I remember that in kubelet is a `swapoff -a` command.
Do you know how to avoid it correctly?

Also, I've faced a problem with a machine with `swapon`. I can see this machine in k8s, webportal - services, hardware, but I don't see it in the cluster and the same on the Grafana (webportal - dashboard).

How to use properly a machine with some swap space in OpenPAI?

**Comment by ydye** [comment]
In our code, the command to close swap is here: https://github.com/microsoft/pai/blob/d019b5af35b8ea8903038fae3837a806d0fedae8/deployment/k8sPaiLibrary/maintaintool/kubelet-start.sh#L27

The kubelet configuration is here:  https://github.com/microsoft/pai/blob/aaf3ac80d4204af7b14b48e8a38d41218b07349c/deployment/k8sPaiLibrary/template/kubelet.sh.template#L53


According to this [issue](https://github.com/NixOS/nixpkgs/issues/50443), you could try to delete  this [line](https://github.com/microsoft/pai/blob/d019b5af35b8ea8903038fae3837a806d0fedae8/deployment/k8sPaiLibrary/maintaintool/kubelet-start.sh#L27).

**Comment by ydye** [comment]
And did you add the label to the new added machine? I guess the machine which can't see from the grafana is a new node

**Comment by andrewsen13** [comment]
@ydye, I just commented it and it's working. I've read it [here](https://github.com/kubernetes/kubernetes/issues/50373) too.

Thank you a lot for your help and your quick responses, as usual! 👍
