### ISSUE TITLE
Tensorboard logdir not right

### ISSUE THREAD

**Issue by lbin** [microsoft/pai#4618]
Data location: path:/mnt/tensorboard

`/opt/conda/bin/python /opt/conda/bin/tensorboard --logdir=path:/mnt/tensorboard --port=12148 --bind_all`

> path: 

mightbe not required

and I killed 
`/opt/conda/bin/python /opt/conda/bin/tensorboard --logdir=path:/mnt/tensorboard --port=12148 --bind_all`

and rerun 
`/opt/conda/bin/python /opt/conda/bin/tensorboard --logdir=/mnt/tensorboard --port=12148 --bind_all`

Tensorboard worked

**Comment by scarlett2018** [comment]
@lbin are you suggesting a bug fix? would you like to submit a PR for this fix?

**Comment by hzy46** [comment]
Hi lbin, where did you see the command `/opt/conda/bin/python /opt/conda/bin/tensorboard --logdir=path:/mnt/tensorboard --port=12148 --bind_all`?

I think the usage of `--logdir=path:/mnt/tensorboard` is wrong.

**Comment by lbin** [comment]
> Hi lbin, where did you see the command `/opt/conda/bin/python /opt/conda/bin/tensorboard --logdir=path:/mnt/tensorboard --port=12148 --bind_all`? Is it a part of OpenPAI's document? I think the usage of `--logdir=path:/mnt/tensorboard` is wrong.

I used ssh to login into the container, and 'htop' to get this command

**Comment by hzy46** [comment]
What is the version of your OpenPAI?

**Comment by lbin** [comment]
> What is the version of your OpenPAI?

v1.0.1

**Comment by hzy46** [comment]
Can you share your job configuration? I'm going to reproduce this bug.

**Comment by lbin** [comment]
protocolVersion: 2
name: face_detector_with_data_aug_f310d520
type: job
jobRetryCount: 0
prerequisites:
  - type: dockerimage
    name: docker_image_0
    auth:
      registryuri: '192.168.231.192:5000'
    uri: '192.168.231.192:5000/pytorch:latest'
taskRoles:
  taskrole:
    instances: 1
    completion:
      minFailedInstances: 1
      minSucceededInstances: -1
    taskRetryCount: 0
    dockerImage: docker_image_0
    resourcePerInstance:
      gpu: 8
      cpu: 32
      memoryMB: 241850
    commands:
      - git clone ssh://out_private_address
      - git checkout -b data_aug origin/data_aug
      - 'pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple'
      - pip install opencv-python
      - pip install -e .
      - cd projects/facetron
      - mkdir datasets
      - python train_net.py --config-file
        configs/r_50_3x.yaml --num-gpus 8
secrets: '******'
defaults:
  virtualCluster: default
extras:
  com.microsoft.pai.runtimeplugin:
    - plugin: ssh
      parameters:
        jobssh: true
        userssh:
          type: custom
          value: >-
            ssh-rsa
            AAAAB3NzaC1yc2EAAAADAQABAAACAQDdbk0A/bP90VdsaXU9HD0W2rxb0eOKoy71ExmoDIjYpyLk32CEmL8MWYxU6WamDRHUvw6BMduiuabwawQM1zMRi+AGOGMoxg/Rm0gNs5fOKBtNVOIEq9+JVQg5GukjSOTbVwzmXoBnO2I9h6mHPael2mzPz2+Df/TxFR1Mo8etWRNCsSKgDBp8Wkz6FBaSy+yulIOfLNJi8SaOUjAmptF5eGX+xW+aMSXakgl4pK5rFl2Bve5YtHHR/2qej5yMzAmlQImuoK5QBSx2+7nHl21aykmVCR24sBG1Rnu2Ms716CnGd1CkHuyuXeSGlLp287Id0oWBBIblvWbia4kRtD79an0FrTjgp9xu6iqeA+KyExIVDpiNtXoRGgWbgyg/pkavPryZPtbCAQ0pAzwB3jbmxTNmJMjdwwR161CUUphjbmqvNZHvwpe2Q+iWoaYr30pK5+/Lad+d0dG2Ks5cTTVybi9+Gv9EvIgwO6zrKd0/mATeeXp80lZQJj0MH7ThmXycE0jCMvqWh3OWQu/St/RzBGm37Ek4hm1kge881hUoFIog+9AuEHuBhGosx4TMrEP8bAKozS1bkKX8n7qq+DhAo8D0sXs3ncTWxKpfYu4eNXweGNyekwQFbP+E//S9ct0GQ+UhfRHP1FoX/KXuT87pjg8yrRlL1l5leFqaJh6WCw==
            lbin@outlook.com
    - plugin: teamwise_storage
      parameters:
        storageConfigNames:
          - nfs-storage
    - plugin: tensorboard
      parameters:
        port: 12148
        logdir:
          path: /mnt/tensorboard

**Comment by lbin** [comment]
> @lbin are you suggesting a bug fix? would you like to submit a PR for this fix?

https://github.com/microsoft/pai/blob/v1.0.1/contrib/submit-job-v2/src/App/TensorBoard.tsx#L408  maybe here give the wrong path, but i am not familiar with tsx or pai framwork @scarlett2018 @hzy46

**Comment by lbin** [comment]
https://github.com/microsoft/pai/blob/v1.0.1/contrib/submit-job-v2/src/App/TensorBoard.tsx#L385

`Object.keys(logDirectories).forEach((key) => {
      logPathList.push(`${logDirectories[key]}`);
    });`
@hzy46 is this right?

**Comment by hzy46** [comment]
@lbin, after a careful check of tensorboard command, I find `--logdir=path:/mnt/tensorboard` is not wrong. It is a proper setting.

Here is the help for `tensorboard`:

![image](https://user-images.githubusercontent.com/7499023/84633330-d1b0df80-af22-11ea-9669-5ecf31fb1ffc.png)

You can see `tensorboard` allows formats like `--logdir=name1:/path/to/logs/1,name2:/path/to/logs/2`. I tried `--logdir=path:/mnt/tensorboard` and it worked. I'm not sure whether it is a problem of tensorboard version. My tensorboard version is `1.15.0`.

**Comment by lbin** [comment]
my tensorboard version is 2.2.2

**Comment by lbin** [comment]
optional arguments:
  -h, --help            show this help message and exit
  --helpfull            show full help message and exit
  --logdir PATH         Directory where TensorBoard will look to find
                        TensorFlow event files that it can display.
                        TensorBoard will recursively walk the directory
                        structure rooted at logdir, looking for .*tfevents.*
                        files. A leading tilde will be expanded with the
                        semantics of Python's os.expanduser function.
  --logdir_spec PATH_SPEC
                        Like `--logdir`, but with special interpretation for
                        commas and colons: commas separate multiple runs,
                        where a colon specifies a new name for a run. For
                        example: `tensorboard --logdir_spec=name1:/path/to/log
                        s/1,name2:/path/to/logs/2`. This flag is discouraged
                        and can usually be avoided. TensorBoard walks log
                        directories recursively; for finer-grained control,
                        prefer using a symlink tree. Some features may not
                        work when using `--logdir_spec` instead of `--logdir`.

**Comment by hzy46** [comment]
Thanks, I found it is a breaking change of tensorboard v2.0.0. Refer to https://github.com/tensorflow/tensorboard/releases/tag/2.0.0:

The --logdir flag no longer supports passing multiple comma-delimited paths,

> which means that it now supports paths containing literal comma and colon
> characters, like ./logs/m=10,n=20,lr=0.001 or ./logs/run_12:30:15. To
> mimic the old behavior, prefer using a tree of symlinks as it works with more
> plugins, but as a fallback the flag --logdir_spec exposes the old behavior.
> See PR 2664.
> 

I think our tensorboard plugin should use `--logdir_spec` when tensorboard >= `v2.0.0`

**Comment by hzy46** [comment]
@Binyang2014 Could you help modify https://github.com/microsoft/openpai-runtime/blob/master/src/plugins/tensorboard/tensorboard.sh.template#L28 ?

**Comment by Binyang2014** [comment]
As the describe above `for --logdir_spec. This flag is discouraged and can usually be avoided`. @lbin can you use `symlinks` as the command suggested to avoid using `--logdir_spec`?

**Comment by lbin** [comment]
> As the describe above `for --logdir_spec. This flag is discouraged and can usually be avoided`. @lbin can you use `symlinks` as the command suggested to avoid using `--logdir_spec`?

I downgraded my tensorboard~

**Comment by Binyang2014** [comment]
Fixed by: #4658
