### ISSUE TITLE
Unable to use V1.0.0 dev-box container to deploy v1.0.0 cluster

### ISSUE THREAD

**Issue by JosephKang** [microsoft/pai#4619]
**Organization Name**:  Advantech

**Short summary about the issue/question**:
Unable to use V1.0.0 dev-box container to deploy v1.0.0 cluster

**Brief what process you are following**:
_1. Create dev-box container_
sudo docker run -itd         -e COLUMNS=$COLUMNS -e LINES=$LINES -e TERM=$TERM         -v /var/run/docker.sock:/var/run/docker.sock         -v /pathConfiguration:/cluster-configuration          -v /hadoop-binary:/hadoop-binary          --pid=host         --privileged=true         --net=host         --name=dev-box-1.0.0         docker.io/openpai/dev-box:v1.0.0

_2. Execution in dev-box containrer_
rm -rf /pai
git clone -b v1.0.0 https://github.com/Microsoft/pai.git
cd pai
cd contrib/kubespray
vim /pai/contrib/kubespray/environment-check.yml
/bin/bash quick-start-kubespray.sh -m /root/cfg/master.csv -w /root/cfg/worker.csv -c /root/cfg/config

_3, Dependency error_
Traceback (most recent call last):
  File "/root/pai-deploy/pai/contrib/kubespray/script/k8s-generator.py", line 7, in <module>
    import jinja2
ImportError: No module named 'jinja2'

_4. ansible command not found error after fixing the package dependency_ 
quick-start-kubespray.sh: line 49: ansible: command not found

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:
https://stackoverflow.com/questions/62185724/single-v1-0-0-devbox-for-multiple-deployment/62274224#62274224

**Comment by ydye** [comment]
Hi, you can only maintain openpai service with paictl in the dev-box container. If you wanna use kubespray you should in the path ```${HOME}/pai-deploy/kubespray/```` on your host, which is prepared as the [answer](https://stackoverflow.com/questions/62185724/single-v1-0-0-devbox-for-multiple-deployment/62274224#62274224)

And in this [answer](https://stackoverflow.com/questions/62185724/single-v1-0-0-devbox-for-multiple-deployment/62274224#62274224), before steps 3 (start up a dev-box), all the tasks is on the host environment. So the kubespray env is setup in your host env not in the container.
