### ISSUE TITLE
Weave-net slow down MPI job

### ISSUE THREAD

**Issue by Binyang2014** [microsoft/pai#4622]
PAI Version: 1.0.1
weave-net version: 2.5.2

We notice the weave-net in `rr` bed is using `sleeve connection mode`.
By default, weave-net using `fastdp` to connect each other, and the performance impact is less than 10%, according to https://www.weave.works/blog/weave-net-performance-fast-datapath/.
If it switch to `sleeve` mode, it can only use about 20% host network bandwidth.

In `rr` bed, we notice the weave net `connection mode` is switched to `sleeve` mode for unknown reason and never switch back. We saw related issue:  https://github.com/weaveworks/weave/issues/1737 but it already fixed in weave-net 2.5 version.

We need to investigate why it switch to `sleeve` mode,
And we need to find a way to clean  remove weave cni plugin.

**Comment by fanyangCS** [comment]
fixed by this PR https://github.com/microsoft/pai/pull/4672

**Comment by fanyangCS** [comment]
related https://github.com/microsoft/pai/issues/4603
