### ISSUE TITLE
Docker version upgraded to incorrect version

### ISSUE THREAD

**Issue by JosephKang** [microsoft/pai#4641]
**Organization Name**: Advantech

**Short summary about the issue/question**: Docker version upgraded to incorrect version during executing quick-start-kubespray.sh

**Brief what process you are following**:
Based on https://openpai.readthedocs.io/en/latest/manual/cluster-admin/installation-guide.html
1. Prepare devbox, master and worker environment as describe
2. Docker version
---
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        2d0083d
 Built:             Fri Aug 16 14:19:38 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       2d0083d
  Built:            Thu Aug 15 15:12:41 2019
  OS/Arch:          linux/amd64
  Experimental:     false
---
3. Execute "/bin/bash quick-start-kubespray.sh -m /path/to/master.csv -w /path/to/worker.csv -c /path/to/config"

4. Deployment script is failed because docker issue on master and worker
---
RUNNING HANDLER [container-engine/docker : Docker | reload docker] **************************************************************************************************************************************************************************
Tuesday 23 June 2020  15:09:26 +0000 (0:00:00.059)       0:00:56.943 **********
fatal: [testworker1-1039180-iaas]: FAILED! => {"changed": false, "msg": "Unable to restart service docker: Job for docker.service failed because the control process exited with error code. See \"systemctl status docker.service\" and \"journalctl -xe\" for details.\n"}
fatal: [testmaster-1039177-iaas]: FAILED! => {"changed": false, "msg": "Unable to restart service docker: Job for docker.service failed because the control process exited with error code. See \"systemctl status docker.service\" and \"journalctl -xe\" for details.\n"}

RUNNING HANDLER [container-engine/docker : Docker | wait for docker] ************************************************************************************************************************************************************************
Tuesday 23 June 2020  15:09:27 +0000 (0:00:00.390)       0:00:57.334 **********

NO MORE HOSTS LEFT **************************************************************************************************************************************************************************************************************************
        to retry, use: --limit @/root/pai-deploy/kubespray/cluster.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
testmaster-1039177-iaas    : ok=111  changed=23   unreachable=0    failed=1
testworker1-1039180-iaas   : ok=95   changed=23   unreachable=0    failed=1

Tuesday 23 June 2020  15:09:27 +0000 (0:00:00.003)       0:00:57.337 **********
===============================================================================
---

5. Docker version upon failed deployment 
---
ubuntu@testworker1-1039180-iaas:~$ sudo docker version
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
---

**How to reproduce it**:
Just repeat the above Installation From Scratch steps

**OpenPAI Environment**:
- OpenPAI version: 1.0.0

**Anything else we need to know**:
1. Ref: https://github.com/kubernetes-sigs/kubespray/issues/6160, https://github.com/docker/for-linux/issues/1004
2. It used to happened before Jun 8. The deployment is OK between Jun 8 until now.

**Comment by JosephKang** [comment]
Cannot downgrade docker version API to 1.39 successfully even after follow the steps on References, and hope that the docker checking and installation can be skip since the docker installation is outside quick-start-kubespray.sh.

**Comment by scarlett2018** [comment]
@hzy46 - may you take a look at this issue? thanks.

**Comment by hzy46** [comment]
It seems your docker doesn't work well. Could you please remove docker on your machine, and follow the instruction below to install docker 18.09?

```bash
sudo apt-get update
sudo apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
sudo apt-get update
sudo apt-get install -y docker-ce=5:18.09.9~3-0~ubuntu-xenial docker-ce-cli=5:18.09.9~3-0~ubuntu-xenial containerd.io
```

**Comment by JosephKang** [comment]
Hope to specify the correct docker version without fix the version after  quick-start-kubespray.sh
May I set the configuration in  ~/pai//contrib/kubespray/example/openpai.yml ?

E.g. 
Uncomment and set **docker_version: 18.09.7** in ~/pai//contrib/kubespray/example/openpai.yml

**Comment by hzy46** [comment]
> Hope to specify the correct docker version without changing the version after executing quick-start-kubespray.sh
> May I set the configuration in ~/pai//contrib/kubespray/example/openpai.yml ?
> 
> E.g.
> Uncomment and set **docker_version: 18.09.7** in ~/pai//contrib/kubespray/example/openpai.yml

You don't neet to modify openpai.yml.

**Comment by JosephKang** [comment]
kubespray version release-2.11 specifies the docker-ce version in the following link:
https://github.com/kubernetes-sigs/kubespray/blob/release-2.11/roles/container-engine/docker/vars/ubuntu-amd64.yml#L6L16
