### ISSUE TITLE
Feedback v1.0.1 How to restore the platform after an unexpected power failure?

### ISSUE THREAD

**Issue by xulzee** [microsoft/pai#4647]
My computing cluster is powered down unexpectedly. After power supply is restored, it is found that all nodes except the master node are in the not ready state. I tried
```
/ paictl.py service stop and start,
```
 than cannot see the gpu nodes when enter the web.

**Comment by ydye** [comment]
What's the status of kubelet on your worker node. Please investigate it with the command ```systemctl status kubelet ```

**Comment by xulzee** [comment]
My master node displays READY, and GPU node displays NOT READY

**Comment by ydye** [comment]
What's your cluster version.

**Comment by xulzee** [comment]
v1.0.1

**Comment by ydye** [comment]
Please paste the output on your worker node with the following command
```
sudo systemctl status kubelet
```

**Comment by xulzee** [comment]
I may not be able to provide this information now, because I have restored the cluster by using the delete and add nodes

**Comment by ydye** [comment]
kubelet is started by systemd and will be restarted by systemd. If next time, the same issue occurs, you could check the kubelet status by systemd. 

And this is the service file: ```/etc/systemd/system/kubelet.service ```

**Comment by fanyangCS** [comment]
Not sure what happened. If the deployment is correct, the cluster should be able to auto recover. We have experienced a power shutdown event before. Feel free to reopen the issue if running into it again.
