### ISSUE TITLE
Restore openpai webportal from https to http

### ISSUE THREAD

**Issue by JosephKang** [microsoft/pai#4677]
**What would you like to be added**:
Ref: https://github.com/microsoft/pai/issues/4582
Hope to restore openpai in http service

**Why is this needed**:
Have some services on https port. Hope to use those services in https and restore openpai via http 

**Components that may involve changes**:

**Steps**:
May I know if I can achieve the goal with the following steps?
 
1. _Execute:_ kubectl delete configmap https-config
2. _Comment all pylon setting_ in ~/pai-deploy/cluster-cfg/services-configuration.yaml (So only the default port 80 will be available..)
3. _Execute:_ ./paictl.py config push -p ~/pai-deploy/cluster-cfg -m service
4. Restart pylon
python paictl.py service stop -n pylon k8s-dashboard rest-server
python paictl.py service start -n k8s-dashboard rest-server pylon

**Comment by JosephKang** [comment]
@abuccts ,

May I know your suggestion for the approach?

Thanks,

**Comment by abuccts** [comment]
just remove `ssl` section in `pylon` config and restart pylon service.

**Comment by JosephKang** [comment]
Thanks for reply.

1. Remove pylon setting in  ~/pai-deploy/cluster-cfg/services-configuration.yaml
2. Execute:  ./paictl.py config push -p ~/pai-deploy/cluster-cfg -m service
3. Use paictl.py to restart pylon

The OpenPAI service is available on http instead of https.
