### ISSUE TITLE
如果zk上data达到一定量级了，FL如何缓存节点数据呢？

### ISSUE THREAD

**Issue by damon008** [microsoft/pai#4679]
目前看到的是缓存所有的根节点的数据:zkClient.getChildren(zkStruct.getLauncherRequestPath())
```
public AggregatedLauncherRequest getAggregatedLauncherRequest() throws Exception {
    AggregatedLauncherRequest aggregatedLauncherRequest = new AggregatedLauncherRequest();

    aggregatedLauncherRequest.setLauncherRequest(getLauncherRequest());
    aggregatedLauncherRequest.setAggregatedFrameworkRequests(new HashMap<>());
    for (String frameworkName : zkClient.getChildren(zkStruct.getLauncherRequestPath())) {
      try {
        aggregatedLauncherRequest.getAggregatedFrameworkRequests().put(frameworkName, getAggregatedFrameworkRequest(frameworkName));
      } catch (KeeperException.NoNodeException ignored) {
      }
    }

    return aggregatedLauncherRequest;
  }
```
但数据量很大时，比如20万，则启动FL时，缓存的数据很占用cpu、memory，这个有很好的办法解决么？目前想到唯一的方式是根据firstRequestTimestamp来限制节点数据的多少。

**Comment by yqwang-ms** [comment]
Suggest to use current pure k8s version PAI.
If you insist to use previous yarn version PAI and FL, you can reduce the frameworkCompletedRetainSec and maxTotalTaskNumber, to reduce/limit the total jobs on ZK and cache.

**Comment by scarlett2018** [comment]
Hi @damon008, thanks for following openpai and interact with us. would you mind share more info about what's the major usage for you when considering openPAI for yourself or your organization. if you don't mind, would you please share the org name? so that we can clustering issues together by org names.

**Comment by yqwang-ms** [comment]
Close as no response, pls reopen if unclear.
