### ISSUE TITLE
Do not expose all ports to pod

### ISSUE THREAD

**Issue by shiyemin** [microsoft/pai#4681]
I understand that PAI expose whole network to all jobs for performance. However, this will cause serious port conflict when users are not aware of this issue or when some of the ports can not be fully controlled (some code select port randomly).

So is there any way to only expose the selected ports for each job?

**Comment by fanyangCS** [comment]
you can choose not to use hostNetwork when lauching a pod. especially when the job only uses one pod, there is no need to expose hostNetwork.

**Comment by scarlett2018** [comment]
> I understand that PAI expose whole network to all jobs for performance. However, this will cause serious port conflict when users are not aware of this issue or when some of the ports can not be fully controlled (some code select port randomly).
> 
> So is there any way to only expose the selected ports for each job?

Thanks for raising the question, feel free to close the issue if @fanyangCS's answer works for you, thanks.

**Comment by shiyemin** [comment]
@fanyangCS Sorry for the late reply. How to turn off hostNetwork？Maybe I should also modify port mapping for each pod? Otherwise, k8s has no way to know which port is using.

**Comment by fanyangCS** [comment]
@ydye, could you help?

**Comment by yqwang-ms** [comment]
We can already auto avoid port conflicts (by retrying with new rand ports) in next release. See https://github.com/microsoft/pai/issues/4384

If you still need to disable hostnetwork, 
set hostnetwork=false and set required ports in containerPort
see example:
https://github.com/microsoft/frameworkcontroller/blob/896761acc2f6968363e11d2432799d4f4109dfd1/example/framework/scenario/tensorflow/cpu/tensorflowdistributedtrainingwithcpu.yaml#L29-L37

**Comment by shiyemin** [comment]
> We can already auto avoid port conflicts (by retrying with new rand ports) in next release. See #4384
> 
> If you still need to disable hostnetwork,
> set hostnetwork=false and set required ports in containerPort
> see example:
> https://github.com/microsoft/frameworkcontroller/blob/896761acc2f6968363e11d2432799d4f4109dfd1/example/framework/scenario/tensorflow/cpu/tensorflowdistributedtrainingwithcpu.yaml#L29-L37

Thanks. I will study and try it!
