### ISSUE TITLE
PUT Request becomes GET

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#4685]
How to reproduce:

1. PUT http://\<url\>/rest-server/api/v2/groups

![image](https://user-images.githubusercontent.com/7499023/86994989-71882300-c1da-11ea-9936-1ea0cfe30abd.png)

2. The rest-server receives a GET:

![image](https://user-images.githubusercontent.com/7499023/86995068-ab592980-c1da-11ea-9393-426634573bba.png)

Https doesn't have this problem.

**Comment by fanyangCS** [comment]
is it related to Pylon? @abuccts

**Comment by abuccts** [comment]
It's the client which changed http method from PUT to GET after received 301 status, [reference](https://serverfault.com/a/434210).

**Comment by hzy46** [comment]
> It's the client which changed http method from PUT to GET after received 301 status, [reference](https://serverfault.com/a/434210).

This behavior is confusing for api users. Can we return a 404 not found for those who are using http?

**Comment by abuccts** [comment]
301 is the http standard for [redirecting http to https](https://en.wikipedia.org/wiki/HTTP_301#:~:text=The%20HTTP%20response%20status%20code,received%20for%20should%20be%20updated.&text=The%20301%20redirect%20is%20considered,users%20from%20HTTP%20to%20HTTPS.), 404 is more confusing for other users.

**Comment by debuggy** [comment]
Is it better if pylon only redirect http GET request and return error when user http other methods
