### ISSUE TITLE
Read-only storage's permission is still `RW`

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#4688]
How to reproduce:

1. Set up a read-only storage by setting `PersistentVolume.Spec.<PersistentVolumeSource>.ReadOnly=true`:

<img width="40%" height="40%" src="https://user-images.githubusercontent.com/7499023/87006771-d1d78e80-c1f3-11ea-8762-01018fd907ec.png" />

2. In webportal, the permission for this new storage is `RW`:
![image](https://user-images.githubusercontent.com/7499023/87006916-00ee0000-c1f4-11ea-8df2-6d4a2185905f.png)

**Comment by fanyangCS** [comment]
is it just an UI issue or you can write to the ro path?

**Comment by hzy46** [comment]
> is it just an UI issue or you can write to the ro path?

A UI issue. The read-only storage in container works fine.
