### ISSUE TITLE
Job submission authorization issue

### ISSUE THREAD

**Issue by JosephKang** [microsoft/pai#4699]
**Organization Name**: Advantech

**Short summary about the issue/question**: Job submission authorization become invalid. Should I change the authentication token information weekly?

**Brief what process you are following**:
1. Submit a job on openpai webportal 1 week ago
2. Use chrome develop tool to record the authentication information in the header. (authorization: Bearer ${token} )
3. Write a job submission task script with the recorded authentication.
4. Use crontab to repeat the sub submission test with the recorded token successfully.
5. After 1 weeks later the job task is failed due to the error information: {"code":"UnauthorizedUserError","message":"Your token is invalid."}
6. The job is submitted successfully as soon as I change the authentication information in the header.

**How to reproduce it**:
The steps mentioned above,

**OpenPAI Environment**: OpenStack VM
- OpenPAI version: V1.0.1

**Comment by fanyangCS** [comment]
you need to create an application token for the RESTful API call. 
https://openpai.readthedocs.io/en/latest/manual/cluster-admin/how-to-set-up-storage.html#2-use-restful-api

**Comment by JosephKang** [comment]
Thanks @fanyangCS ,

I create an application token on user profile and use it inside API header field for testing now.

**Comment by JosephKang** [comment]
Thanks, the application token created on admin webpage profile is not expired after 1 week.
