### ISSUE TITLE
webportal api/v1 and yarn fallback test

### ISSUE THREAD

**Issue by debuggy** [microsoft/pai#4704]
1. AAD login: /api/v1/authn/oidc/login, no error
2. AAD logout: /api/v1/authn/oidc/logout, no error
3. Basic login: /api/v1/authn/basic/login, no error
4. submit job: webhdfs api, not used
5. token: /api/v1/token, /api/v1/token/application, no error
6. deprecated config: 
   - yarnWebPortalUri
   - config.logType === 'yarn'
   - config.launcherType === 'yarn'
7. deprecated storage:
   - router.use('/storages', storageRouter);
   - router.use('/storage', storageDeprecatedRouter)

**Comment by fanyangCS** [comment]
@yiyione, please replace the old apis with the ones in the sdk.

**Comment by yiyione** [comment]
Job APIs: #4669
Authn APIs: #4687
Storage APIs: #4660

**Comment by scarlett2018** [comment]
@yiyione - is this target to the August release?

**Comment by yiyione** [comment]
> @yiyione - is this target to the August release?

Yes
