### ISSUE TITLE
Nginx cannot listen on 443 at master

### ISSUE THREAD

**Issue by JosephKang** [microsoft/pai#4707]
**Organization Name**:
 Advantech

**Short summary about the issue/question**:
If we have additional nginx configured on listening port 443 at master, the nginx cannot receive anything. 
Please refer to the nginx config: [nginx_ex.conf.txt](https://github.com/microsoft/pai/files/4911918/nginx_ex.conf.txt)
It didn't happened on openpai V1.10.1 or V1.17.0 in the same openstack environment
Should I add any additional nginx configuration?

**Brief what process you are following**:
1. Install OpenPAI V1.0.1
2. Install Nginx on master and set nginx on port 443.
3. The nginx cannot listen any incoming request on 443.

**How to reproduce it**:
Repeat the above process.

**OpenPAI Environment**:  Ubuntu 16.04
- OpenPAI version: V1.0.1
- Cloud provider or hardware configuration: OpenStack

**Anything else we need to know**:
The same nginx config can work on devbox host.

**Comment by ydye** [comment]
Can u check the status of 443 port wit ```sudo lsof -i:443```

**Comment by JosephKang** [comment]
- On V1.0.1 master without /etc/init.d/nginx running
>  sudo lsof -i:443
COMMAND     PID   USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
prometheu  2313 nobody    8u  IPv4  136598      0t0  TCP 10.192.0.1:45380->10.192.0.1:https (ESTABLISHED)
kube-cont 23446   root    5u  IPv4   92167      0t0  TCP 10.192.0.1:43756->10.192.0.1:https (ESTABLISHED)
dashboard 31206   root    3u  IPv4 1353330      0t0  TCP 10.192.0.1:38518->10.192.0.1:https (ESTABLISHED)

>sudo ps aux | grep nginx
ubuntu    3657  0.0  0.0  12944   908 pts/0    S+   03:13   0:00 grep --color=auto nginx
root     22498  0.0  0.0   8932  7612 ?        Ss   03:09   0:00 nginx: master process /usr/local/openresty/bin/openresty -g daemon off;
nobody   22521  0.0  0.0   9388  2512 ?        S    03:09   0:00 nginx: worker process
root     24133  0.0  0.0  23712  5348 ?        S    03:10   0:00 nginx: master process nginx -g daemon off;
www-data 24135  0.0  0.0  23712  2940 ?        S    03:10   0:00 nginx: worker process

- On V1.0.1 master with/etc/init.d/nginx running
>sudo lsof -i:443
COMMAND     PID     USER   FD   TYPE    DEVICE SIZE/OFF NODE NAME
prometheu  2313   nobody    8u  IPv4    136598      0t0  TCP 10.192.0.1:45380->10.192.0.1:https (ESTABLISHED)
watchdog  13903     root    6u  IPv4 637753393      0t0  TCP 10.192.0.1:54824->10.192.0.1:https (ESTABLISHED)
nginx     20195     root    6u  IPv4 637750474      0t0  TCP *:https (LISTEN)
nginx     20196 www-data    6u  IPv4 637750474      0t0  TCP *:https (LISTEN)
nginx     20197 www-data    6u  IPv4 637750474      0t0  TCP *:https (LISTEN)
nginx     20198 www-data    6u  IPv4 637750474      0t0  TCP *:https (LISTEN)
nginx     20199 www-data    6u  IPv4 637750474      0t0  TCP *:https (LISTEN)
nginx     20200 www-data    6u  IPv4 637750474      0t0  TCP *:https (LISTEN)
nginx     20202 www-data    6u  IPv4 637750474      0t0  TCP *:https (LISTEN)
nginx     20203 www-data    6u  IPv4 637750474      0t0  TCP *:https (LISTEN)
nginx     20204 www-data    6u  IPv4 637750474      0t0  TCP *:https (LISTEN)
kube-cont 23446     root    5u  IPv4     92167      0t0  TCP 10.192.0.1:43756->10.192.0.1:https (ESTABLISHED)
dashboard 31206     root    3u  IPv4   1353330      0t0  TCP 10.192.0.1:38518->10.192.0.1:https (ESTABLISHED)

> sudo ps aux | grep nginx
root     20195  0.0  0.0 125080  2328 ?        Ss   03:17   0:00 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
www-data 20196  0.0  0.0 125444  3136 ?        S    03:17   0:00 nginx: worker process
www-data 20197  0.0  0.0 125444  3136 ?        S    03:17   0:00 nginx: worker process
www-data 20198  0.0  0.0 125444  3136 ?        S    03:17   0:00 nginx: worker process
www-data 20199  0.0  0.0 125444  3136 ?        S    03:17   0:00 nginx: worker process
www-data 20200  0.0  0.0 125444  3136 ?        S    03:17   0:00 nginx: worker process
www-data 20202  0.0  0.0 125444  3136 ?        S    03:17   0:00 nginx: worker process
www-data 20203  0.0  0.0 125444  3136 ?        S    03:17   0:00 nginx: worker process
www-data 20204  0.0  0.0 125444  3136 ?        S    03:17   0:00 nginx: worker process
ubuntu   22369  0.0  0.0  12944  1032 pts/0    S+   03:18   0:00 grep --color=auto nginx
root     22498  0.0  0.0   8932  7612 ?        Ss   03:09   0:00 nginx: master process /usr/local/openresty/bin/openresty -g daemon off;
nobody   22521  0.0  0.0   9388  2512 ?        S    03:09   0:00 nginx: worker process
root     24133  0.0  0.0  23712  5348 ?        S    03:10   0:00 nginx: master process nginx -g daemon off;
www-data 24135  0.0  0.0  23712  3716 ?        S    03:10   0:00 nginx: worker process

**Comment by JosephKang** [comment]
Currently the used kubespray deployment script set api server on 6443
- https://github.com/kubernetes-sigs/kubespray/blob/master/inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml#L95L98
- https://github.com/kubernetes-sigs/kubespray/blob/master/inventory/sample/group_vars/all/all.yml#L32

I changed the kube_apiserver_port and loadbalancer_apiserver_port to 9285 (There is error while setting kube_apiserver_port to 0 ) and set kube_apiserver_insecure_port to 8080 but the 443 port is still unavailable after kubespray deployment. I am not sure if it is the correct approach.

Any suggestion?

**Comment by JosephKang** [comment]
It is observed that port 443 is used by containerPort, hostPort and nginx port in pylon 
https://github.com/microsoft/pai/blob/v1.0.1/src/pylon/deploy/pylon.yaml.template#L87L88
https://github.com/microsoft/pai/blob/v1.0.1/src/pylon/deploy/pylon-config/nginx.conf.template#L78

I just change all the above setting to 10443 and the host nginx can receive incoming request.

May I know if any concern to change the pylon setting?

**Comment by ydye** [comment]
Hi, pylon is a proxy of openpai. And it handle the url rule to proxy the request to coressponding component of openpai. If you prefer local nginx, I think you should make your nginx support our requst from webportal. And our api document is based on the url before pylon's parse


An example

web  --- https://x.x.x.x/rest-server/v2/...  ---> pylon --- http://x.x.x.x/v2/... -----> rest-server.

**Comment by fanyangCS** [comment]
closed as no further reponse.

**Comment by JosephKang** [comment]
Any incoming traffic via port 443 will be intercepted by pylon if the `pylon-https` is still 443 (Configuration since version v0.13.0 so I don't have the issue on version v0.10.1) so that I cannot do anything on master host. Therefore I still changed pylon-https to 10443 and pylon still listen on port 80. The nginx configuration is configured as below:
```
    server {
        listen       443 ssl;
        ...
        location / {
            proxy_pass http://192.168.1.1;
        }
    }
```
The rest API on master node work fine as usual(Similar to the proxy mentioned above) so it might be OK to use.
