### ISSUE TITLE
Deployment is blocked at AMD-Device-Plugin Checking

### ISSUE THREAD

**Issue by JosephKang** [microsoft/pai#4710]
**Organization Name**: Advantech

**Short summary about the issue/question**: 
Infinite looping in kubespray/script/openpai-generator.py

**Brief what process you are following**:
1. Setup cluster with only one Nvidia GPU worker
2. /bin/bash quick-start-kubespray.sh -m /path/to/master.csv -w /path/to/worker.csv -c /path/to/config pass
3, Create a container with https://github.com/microsoft/pai/blob/v1.0.1/contrib/kubespray/script/service-boot.sh#L26-#L36
4. Run https://github.com/microsoft/pai/blob/v1.0.1/contrib/kubespray/script/service-boot.sh#L37-L68 sequentially  except https://github.com/microsoft/pai/blob/v1.0.1/contrib/kubespray/script/service-boot.sh#L47  
5. python3 /root/pai/contrib/kubespray/script/openpai-generator.py -m /quick-start-config/master.csv -w /quick-start-config/worker.csv -c /quick-start-config/config.yml -o /cluster-configuration || exit $?
6. Step 5. will enter infinite looping 
> 2020-07-13 23:18:18,757 [INFO] - openpai-generator.py:168 : AMD-Device-Plugin is not ready yet. Please wait for a moment!
2020-07-13 23:18:28,794 [INFO] - openpai-generator.py:120 : AMD-Device-Plugin is not ready.
2020-07-13 23:18:28,795 [INFO] - openpai-generator.py:121 : Total: 2
2020-07-13 23:18:28,795 [INFO] - openpai-generator.py:122 : Ready: 1

**How to reproduce it**:
Just follow the process steps

**OpenPAI Environment**: Ubuntu16.04
- OpenPAI version: V1.0.1
- Cloud provider or hardware configuration: OpenStack VM

**Anything else we need to know**:
Currently I skip AMD GPU checking by commenting https://github.com/microsoft/pai/blob/v1.0.0/contrib/kubespray/script/openpai-generator.py#L226 and am not sure if it is OK.

**Comment by abuccts** [comment]
It's OK to skip the line you commented.

If you want to know why the deployment hung, you need to get the name for unready pod and check its log.
```sh
kubectl -n kube-system get pods
kubectl -n kube-system logs amdgpu-device-plugin-daemonset-xxxxxx 
```

**Comment by JosephKang** [comment]
The testing environment is offline and blocked

**Comment by JosephKang** [comment]
The testing environment is offline and blocked upon image downloading
---
kubectl get pods --all-namespaces
NAMESPACE     NAME                                              READY   STATUS             RESTARTS   AGE     IP               NODE                      NOMINATED NODE   READINESS GATES
kube-system   amdgpu-device-plugin-daemonset-fbp94              0/1     ImagePullBackOff   0          6m49s   10.205.224.223   master0709   <none>           <none>
kube-system   amdgpu-device-plugin-daemonset-vfs22              1/1     Running            0          6m49s   10.202.83.9      worker0709   <none>           <none>
---
The docker image is already loaded on master and https://raw.githubusercontent.com/RadeonOpenCompute/k8s-device-plugin/master/k8s-ds-amdgpu-dp.yaml file is downloaded but he imagePullPolicy field specified at devbox. 
I added **imagePullPolicy** as **IfNotPresent** and rerun .The AMD-Device-Plugin checking process is not blocked.

PS: I also add the same imagePullPolicy in https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/1.0.0-beta4/nvidia-device-plugin.yml to avoid the possibled similar error.

**Comment by abuccts** [comment]
The behavior is by design. Kubernetes will use `imagePullPolicy: Always` policy when `imagePullPolicy` is omitted and `latest` image tag is used.

Besides, those device plugins are from third parties, you can modify by your own.
