### ISSUE TITLE
Device plugin configuration enhancement

### ISSUE THREAD

**Issue by JosephKang** [microsoft/pai#4715]
**What would you like to be added**:
Add imagePullPolicy under https://github.com/microsoft/pai/blob/v1.0.1/src/device-plugin/deploy/device-plugin.yaml#L41
 
**Why is this needed**:
Sometimes the user need to configure the imagePullPolicy

**Without this feature, how does the current module work**:
It always need to connect to a repo instead of using local images.

**Components that may involve changes**:
NA

**Comment by abuccts** [comment]
This is by design, current deployment uses `imagePullPolicy: Always` policy explicitly or in default. We don't provide an offline deployment option.
