### ISSUE TITLE
[Feature] Does the webportal remove the allocated GPU data from dashboard in v1.0?

### ISSUE THREAD

**Issue by edenbuaa** [microsoft/pai#4718]
I see the allocated GPU data is missing in v1.0. Is it a new feature？ Where can I get them back?

![image](https://user-images.githubusercontent.com/16248697/87524761-24fd8580-c6bb-11ea-9e0f-175eed3a73c6.png)

**Comment by fanyangCS** [comment]
yes. the UI has been removed. you can set the GPU allocation per VC in home page.

**Comment by edenbuaa** [comment]
Got it. thanks @fanyangCS
