### ISSUE TITLE
Webportal docker image build failure

### ISSUE THREAD

**Issue by JosephKang** [microsoft/pai#4736]
**Organization Name**: Advantech

**Short summary about the issue/question**:  Webportal docker image build failure

**Brief what process you are following**:
1. git clone -b v1.0.1 https://github.com/Microsoft/pai.git
2. cd pai/src/webportal/
3. sudo docker build -t openpai/webportal:v1.0.1-2 -f build/webportal.common.dockerfile .
4. Error
>Sending build context to Docker daemon  1.994MB
Step 1/12 : FROM node:carbon
 ---> 8eeadf3757f4
Step 2/12 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 7941589613b7
Step 3/12 : ENV NODE_ENV=production     SERVER_PORT=8080
 ---> Using cache
 ---> b5f9d1b7d009
Step 4/12 : COPY dependency/ ../../
COPY failed: stat /afs/docker/tmp/docker-builder063902618/dependency: no such file or directory

**How to reproduce it**:
Repeat the image build process...

**OpenPAI Environment**: OpenStack VM
- OpenPAI version: v1.0.1
- OS (e.g. from /etc/os-release): ubuntu 16.04.4
- Kernel (e.g. `uname -a`): 4.4.0-150-generic
- Others: docker version: 18.09.3

**Comment by abuccts** [comment]
pls run the following to build:
```sh
cd pai
python build/pai_build.py build -s webportal -c /path/to/cluster-config
```

**Comment by JosephKang** [comment]
@abuccts ,

Could we build webportal in an environment without a running openpai environment?

**Comment by abuccts** [comment]
We do not provide such an option, it will need some modifications like copy path in Dockerfile if you want to build it alone.

**Comment by JosephKang** [comment]
I use the pai_build.py script and get unauthorized error..
> buntu@devbox0709-1061473-iaas:~/src/img_build/pai⟫ sudo docker login
Authenticating with existing credentials...
WARNING! Your password will be stored unencrypted in /home/ubuntu/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
Login Succeeded

> ubuntu@devbox0709-1061473-iaas:~/src/img_build/pai⟫ sudo python build/pai_build.py build -s webportal -c ~/pai-deploy/cluster-cfg/
2020-07-20 23:48:57,029 - __main__ - INFO - Pai build starts at 2020-07-20 23:48:57.029285
2020-07-20 23:48:57,040 - core.build_utility - INFO - Begin to execute the command: docker login -u None -p None docker.io
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password
2020-07-20 23:48:58,930 - core.build_utility - ERROR - Executing command failed: docker login -u None -p None docker.io
---

May I know how to resolve the error?

**Comment by abuccts** [comment]
It requires an account for Docker Hub in `~/pai-deploy/cluster-cfg/service-configuration.yaml`.

https://github.com/microsoft/pai/blob/55a0b862bd897759f6c80aeb849be1fdde721406/examples/cluster-configuration/services-configuration.yaml#L53-L60

**Comment by JosephKang** [comment]
Currently we attach running webportal docker instance and run **yarn build** and  **yarn start** to make some modification taking in place. Then the instance is committed the instance into local repo and save as tar file for future usage. 

Will try the build method with docker login information in service-configuration.yaml, thanks

**Comment by JosephKang** [comment]
Thanks @abuccts ,

Command 'python build/pai_build.py build -s webportal -c /path/to/cluster-config' works fine after setting correct docker account information in **service-configuration.yaml**
