### ISSUE TITLE
Can we Assign Job to a Particular IP

### ISSUE THREAD

**Issue by zhenhuahu** [microsoft/pai#4740]
**Organization Name**:

**Hi. Currently we have 16 machines with different ip addresses under OpenPAI. Now I want to run my code on specific ip addresses. Is there any way we can do it? Thanks. **:

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**: 
- OpenPAI version:v1.0.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by fanyangCS** [comment]
The short answer is yes. https://github.com/microsoft/hivedscheduler/blob/master/example/feature/README.md#Pinned-Cells

**Comment by zhenhuahu** [comment]
> The short answer is yes. https://github.com/microsoft/hivedscheduler/blob/master/example/feature/README.md#Pinned-Cells
> 
> The document is a bit outdated and some config files need change later.

I'll check it out! Thank you so much!

**Comment by scarlett2018** [comment]
Closing as the solution has been provided, feel free to reopen if there are follow up questions or comments against the issue.
