### ISSUE TITLE
Questions on horovod-pytorch-synthetic-benchmark.yaml

### ISSUE THREAD

**Issue by zhenhuahu** [microsoft/pai#4742]
**Organization Name**:

**Hi, I'm quite new to OpenPAI and Horovod.  I have a question on the example https://github.com/microsoft/pai/blob/master/marketplace-v2/horovod-pytorch-synthetic-benchmark.yaml command.

In this line  -mca btl_tcp_if_exclude lo,docker0 <% $parameters.nccl %>, what does the docker0 mean? Also, how does it find the file 'pytorch_synthetic_benchmark.py' to run? I didn't see where it imported the file！.

Thanks**:

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version: v1.0.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by scarlett2018** [comment]
Hi @zhenhuahu - thanks for following openpai, and interact with us. would you mind share more info about what's the major usage for you when considering openPAI for yourself or your organization. if you don't mind, would you please share the org name? so that we can clustering issues together by org names.

**Comment by abuccts** [comment]
> what does the docker0 mean

pls refer to [horovod's docs](https://github.com/horovod/horovod/blob/v0.16.4/docs/mpirun.rst#hangs-due-to-non-routed-network-interfaces)

> Also, how does it find the file 'pytorch_synthetic_benchmark.py' to run

pls refer to [horovod's dockerfile](https://github.com/horovod/horovod/blob/v0.16.4/Dockerfile#L66-L71)

**Comment by zhenhuahu** [comment]
> > what does the docker0 mean
> 
> pls refer to [horovod's docs](https://github.com/horovod/horovod/blob/v0.16.4/docs/mpirun.rst#hangs-due-to-non-routed-network-interfaces)
> 
> > Also, how does it find the file 'pytorch_synthetic_benchmark.py' to run
> 
> pls refer to [horovod's dockerfile](https://github.com/horovod/horovod/blob/v0.16.4/Dockerfile#L66-L71)

Thank you so much!

**Comment by zhenhuahu** [comment]
> Hi @zhenhuahu - thanks for following openpai, and interact with us. would you mind share more info about what's the major usage for you when considering openPAI for yourself or your organization. if you don't mind, would you please share the org name? so that we can clustering issues together by org names.

Hi Scarlett. Thanks for the question. Actually my company has been using OpenPAI for deep learning before I joined. I work at SenseBrain Technology. Thanks.
