### ISSUE TITLE
Can OpenPAI work with Apex and PyTorch to do multi-node GPU training?

### ISSUE THREAD

**Issue by zhenhuahu** [microsoft/pai#4743]
**Organization Name**:

**I'm new to Apex and OpenPAI. I read that Apex is very efficient with PyTorch. So I was wondering if there's an example to show Apex with OpenPAI on multi-node training. Thanks!**:

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version: v1.0.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by scarlett2018** [comment]
related to: https://github.com/NVIDIA/apex

**Comment by abuccts** [comment]
you can use [apex's docker](https://github.com/NVIDIA/apex/tree/master/examples/docker) and try [its distributed example](https://github.com/NVIDIA/apex/tree/master/examples/simple/distributed)

**Comment by scarlett2018** [comment]
> you can use [apex's docker](https://github.com/NVIDIA/apex/tree/master/examples/docker) and try [its distributed example](https://github.com/NVIDIA/apex/tree/master/examples/simple/distributed)

closing the issue as solution has been provided. @zhenhuahu feel free to reopen the issue if there are other questions or feedbacks related to the solution. thanks.

**Comment by zhenhuahu** [comment]
> you can use [apex's docker](https://github.com/NVIDIA/apex/tree/master/examples/docker) and try [its distributed example](https://github.com/NVIDIA/apex/tree/master/examples/simple/distributed)

Thanks. This is for 1 node only. Do you have more examples with multi-node and pytorch-lightning?

**Comment by zhenhuahu** [comment]
> you can use [apex's docker](https://github.com/NVIDIA/apex/tree/master/examples/docker) and try [its distributed example](https://github.com/NVIDIA/apex/tree/master/examples/simple/distributed)

Hi. I tried to run the example you showed me, but kept getting the error message:
"You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 libpython3.6 : Depends: libpython3.6-stdlib (= 3.6.9-1~18.04ubuntu1) but 3.6.9-1~18.04 is installed"

I tried the command 'apt --fix-broken install' but still get the same error message. Do you have any ideas what might cause this?
Thanks.

**Comment by zhenhuahu** [comment]
I have found that I can use horovod to do multi-node training. Thanks
