### ISSUE TITLE
Hived Reconfig Devops is wrong

### ISSUE THREAD

**Issue by yqwang-ms** [microsoft/pai#4744]
Current doc is wrong:
https://github.com/microsoft/pai/blob/master/docs/manual/cluster-admin/how-to-set-up-virtual-clusters.md

Previous correct doc is deleted unexpectedly:
https://github.com/microsoft/pai/blob/513d0104cb38b56cf6f6b4226d70d2db1536ee71/docs/hivedscheduler/devops.md
Delete in PR https://github.com/microsoft/pai/pull/4545 without any HiveD dev reviewed

Pls note the operation order is important.
+Release manager @Binyang2014 to aware

**Comment by hzy46** [comment]
#4746 #4748 #4749
