### ISSUE TITLE
Feedback v0.17.0

### ISSUE THREAD

**Issue by ypbustc** [microsoft/pai#4754]
job结束后 stdout和stderr 点开都提示 not found是怎么回事？谢谢

**Comment by fanyangCS** [comment]
it may because the container didn't produce any output. or the output is too short that the container exits w/o flushing the output to the disk.

**Comment by ypbustc** [comment]
根据您的分析，我增加输出肯定超过40k bytes，但依然是&nbsp;Not Found。另外“Go to Application Tracking Page” 点击后也报{"message":"Page not found","error":{}}，盼回复，谢谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/pai"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月21日(星期二) 晚上9:45
收件人:&nbsp;"microsoft/pai"<pai@noreply.github.com&gt;;
抄送:&nbsp;"甲骨文"<825223581@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/pai] Feedback v0.17.0 (#4754)





 
it may because the container didn't produce any output. or the output is too short that the container exits w/o flushing the output to the disk.

**Comment by fanyangCS** [comment]
Are you deploying YARN in v0.17? YARN is not supported in v0.17. Please do *not* use v0.17 as it is an internal version. Please use v1.x.

**Comment by fanyangCS** [comment]
https://github.com/microsoft/pai/issues/4675

**Comment by ypbustc** [comment]
找到原因了，谢谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/pai"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月21日(星期二) 晚上10:25
收件人:&nbsp;"microsoft/pai"<pai@noreply.github.com&gt;;
抄送:&nbsp;"甲骨文"<825223581@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/pai] Feedback v0.17.0 (#4754)





 
Are you deploying YARN in v0.17? YARN is not supported in v0.17. Please do not use v0.17 as it is an internal version. Please use v1.x.

**Comment by scarlett2018** [comment]
> job结束后 stdout和stderr 点开都提示 not found是怎么回事？谢谢

Hi @ypbustc thanks for following openpai and interact with us. would you mind share more info about what's the major usage for you when considering openPAI for yourself or your organization. if you don't mind, would you please share the org name? so that we can clustering issues together by org names.

**Comment by scarlett2018** [comment]
> > job结束后 stdout和stderr 点开都提示 not found是怎么回事？谢谢
> 
> Hi @ypbustc thanks for following openpai and interact with us. would you mind share more info about what's the major usage for you when considering openPAI for yourself or your organization. if you don't mind, would you please share the org name? so that we can clustering issues together by org names.

Closing the issue as the problem has been addressed according to the comment history. But looking forward for feedback on the Org info and usage scenario sharing. thanks.

**Comment by ypbustc** [comment]
USTC ，openPAI主要用于管理AI集群。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/pai"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月22日(星期三) 下午2:45
收件人:&nbsp;"microsoft/pai"<pai@noreply.github.com&gt;;
抄送:&nbsp;"甲骨文"<825223581@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/pai] Feedback v0.17.0 (#4754)





   
job结束后 stdout和stderr 点开都提示 not found是怎么回事？谢谢
  
Hi @ypbustc thanks for following openpai and interact with us. would you mind share more info about what's the major usage for you when considering openPAI for yourself or your organization. if you don't mind, would you please share the org name? so that we can clustering issues together by org names.
  
Closing the issue as the problem has been addressed according to the comment history. But looking forward for feedback on the Org info and usage scenario sharing. thanks.

**Comment by scarlett2018** [comment]
> USTC ，openPAI主要用于管理AI集群。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "microsoft/pai" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月22日(星期三) 下午2:45 收件人:&nbsp;"microsoft/pai"<pai@noreply.github.com&gt;; 抄送:&nbsp;"甲骨文"<825223581@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [microsoft/pai] Feedback v0.17.0 (#4754) job结束后 stdout和stderr 点开都提示 not found是怎么回事？谢谢 Hi @ypbustc thanks for following openpai and interact with us. would you mind share more info about what's the major usage for you when considering openPAI for yourself or your organization. if you don't mind, would you please share the org name? so that we can clustering issues together by org names. Closing the issue as the problem has been addressed according to the comment history. But looking forward for feedback on the Org info and usage scenario sharing. thanks. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

收到，是BITA的deploy还是新的Deploy?如果是BITA的我就重用之前的tag了。@ypbustc

**Comment by ypbustc** [comment]
是新的集群，不是bita。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Scarlett Li"<notifications@github.com&gt;; 
发送时间: 2020年7月22日(星期三) 下午2:58
收件人: "microsoft/pai"<pai@noreply.github.com&gt;; 
抄送: "甲骨文"<825223581@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [microsoft/pai] Feedback v0.17.0 (#4754)





  
USTC ，openPAI主要用于管理AI集群。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "microsoft/pai" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月22日(星期三) 下午2:45 收件人:&nbsp;"microsoft/pai"<pai@noreply.github.com&gt;; 抄送:&nbsp;"甲骨文"<825223581@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [microsoft/pai] Feedback v0.17.0 (#4754) job结束后 stdout和stderr 点开都提示 not found是怎么回事？谢谢 Hi @ypbustc thanks for following openpai and interact with us. would you mind share more info about what's the major usage for you when considering openPAI for yourself or your organization. if you don't mind, would you please share the org name? so that we can clustering issues together by org names. Closing the issue as the problem has been addressed according to the comment history. But looking forward for feedback on the Org info and usage scenario sharing. thanks. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
  
收到，是BITA的deploy还是新的Deploy?如果是BITA的我就重用之前的tag了。@ypbustc
