### ISSUE TITLE
Can the v1.0 support to deploy on an existing k8s cluster

### ISSUE THREAD

**Issue by edenbuaa** [microsoft/pai#4779]
Is there a guide for openpai v1.0 deployment with an existing k8s cluster?

**Comment by fanyangCS** [comment]
related to https://github.com/microsoft/pai/issues/4030. 
We do not recommend to deploy v1.0 to an existing k8s cluster, unless you know very well about OpenPAI and what it requires. 
Here is an example showing how to deploy OpenPAI on an existing (clean) k8s cluster using AKS-engine. #4735

**Comment by edenbuaa** [comment]
thanks @fanyangCS
