### ISSUE TITLE
Etcd cert not found during adding node.

### ISSUE THREAD

**Issue by JosephKang** [microsoft/pai#4790]
**Organization Name**: 
Advantech

**Short summary about the issue/question**:

The following error happened during adding CPU or GPU node
> TASK [network_plugin/calico : Calico | Link etcd certificates for calico-node] *******************************************************************************************************************************
Thursday 06 August 2020  05:26:54 +0000 (0:00:00.232)       0:00:43.849 *******
failed: [testcpu0-1111972-iaas] (item={'s': 'etcd/ca.crt', 'd': 'ca_cert.crt'}) => {"changed": false, "item": {"d": "ca_cert.crt", "s": "etcd/ca.crt"}, "msg": "Error while linking: [Errno 2] No such file or directory", "path": "/etc/calico/certs/ca_cert.crt", "state": "absent"}
failed: [testcpu0-1111972-iaas] (item={'s': 'apiserver-etcd-client.crt', 'd': 'cert.crt'}) => {"changed": false, "item": {"d": "cert.crt", "s": "apiserver-etcd-client.crt"}, "msg": "Error while linking: [Errno 2] No such file or directory", "path": "/etc/calico/certs/cert.crt", "state": "absent"}
failed: [testcpu0-1111972-iaas] (item={'s': 'apiserver-etcd-client.key', 'd': 'key.pem'}) => {"changed": false, "item": {"d": "key.pem", "s": "apiserver-etcd-client.key"}, "msg": "Error while linking: [Errno 2] No such file or directory", "path": "/etc/calico/certs/key.pem", "state": "absent"}
---

**Brief what process you are following**:
1. prepare node with the steps in https://openpai.readthedocs.io/en/latest/manual/cluster-admin/how-to-add-and-remove-nodes.html

2. Error happened while executing: ansible-playbook -i inventory/pai/hosts.yml upgrade-cluster.yml --become --become-user=root  --limit=testcpu0-1111972-iaas -e "@inventory/pai/openpai.yml"

**How to reproduce it**:
Please follow the above 2 steps

**OpenPAI Environment**: 
- OpenPAI version: v1.0.1
- Cloud provider or hardware configuration: openstack vm
- OS (e.g. from /etc/os-release): ubuntu 16.04

**Anything else we need to know**:
The whole deployment is OK with the steps in https://openpai.readthedocs.io/en/latest/manual/cluster-admin/installation-guide.html in the same environment,

**Comment by hzy46** [comment]
hi JosephKang, please findout 1. What's the network plugin your cluster uses now?  2. What's the cluster configuration for kubespray?

For `1`, you can find it out by using `kubectl get po -n kube-system`. If you find there are something like `weave-net-hrm5j`, it indicates you are using `weave` as K8S's network plugin. Otherwise you are using calico.

For `2`, please paste the configuration in `~/pai-deploy/kubespray/inventory/pai/openpai.yml`.

**Comment by JosephKang** [comment]
1. It should be the calico in existing cluster
> root@testdevbox-1111981-iaas:~/pai-deploy/kubespray# kubectl get po -n kube-system -o wide
NAME                                              READY   STATUS    RESTARTS   AGE     IP               NODE                      NOMINATED NODE   READINESS GATES
calico-kube-controllers-659b6c5957-vb4m5          1/1     Running   0          6h49m   192.168.211.31   testgpu0-1111945-iaas     <none>           <none>
calico-node-pzr9h                                 1/1     Running   0          6h49m   192.168.211.26   testmaster-1111978-iaas   <none>           <none>
calico-node-rvs26                                 1/1     Running   1          6h49m   192.168.211.44   testgpu1-1112050-iaas     <none>           <none>
calico-node-vjrc4                                 1/1     Running   1          6h49m   192.168.211.31   testgpu0-1111945-iaas     <none>           <none>
coredns-584bf4786-6rxrt                           1/1     Running   0          6h48m   10.205.51.129    testmaster-1111978-iaas   <none>           <none>
dns-autoscaler-6998cb94ff-wq4n2                   1/1     Running   0          6h48m   10.205.51.130    testmaster-1111978-iaas   <none>           <none>
...
nvidia-device-plugin-daemonset-pd8xh              1/1     Running   0          6h37m   10.203.48.4      testgpu0-1111945-iaas     <none>           <none>

2. Please refer to [openpai.yml.txt](https://github.com/microsoft/pai/files/5033670/openpai.yml.txt)

**Comment by hzy46** [comment]
The root cause is here: https://github.com/kubernetes-sigs/kubespray/blob/release-2.11/roles/network_plugin/calico/tasks/install.yml#L26-L36 The command wants to create a link file in `/etc/calico/certs/cert.crt` (linking to `{{ etcd_cert_dir }}/cert.crt` ) but failed. I'm not sure whether it is an issue with kubespray. 

Maybe you could try to check (on `testcpu0-1111972-iaas`):

1. Does the ansible command [`Calico | Create calico certs directory`](https://github.com/kubernetes-sigs/kubespray/blob/release-2.11/roles/network_plugin/calico/tasks/install.yml#L17-L24) succeed? Is the directory `/etc/calico/certs/` successfully created?

2. Does file `{{ etcd_cert_dir }}/cert.crt` exist? By default, `{{ etcd_cert_dir }}` is `/etc/ssl/etcd/ssl`, according to [here](https://github.com/kubernetes-sigs/kubespray/blob/release-2.11/roles/etcd/defaults/main.yml#L13-L14).

**Comment by JosephKang** [comment]
Hello @hzy46 

1. The /etc/calico/certs/ in new node is created successfully.

2. cert.crt is not in /etc/calico/certs/.

**Comment by hzy46** [comment]
Are there any files in `/etc/ssl/etcd/ssl` ?

**Comment by JosephKang** [comment]
Hello @hzy46 ,

**/etc/ssl/etcd/ssl** directory doesn't exist in the new node upon adding node failure. 

However, **/etc/ssl/etcd/ssl** also doesn't exist in the existing working GPU node but the /etc/calico/certs/ contains the following files
> testgpu0-1111945-iaas:/$ sudo ls -al /etc/calico/certs
total 20
drwxr-x--- 2 root root 4096 Aug  6 11:35 .
drwxr-x--- 3 root root 4096 Aug  6 09:49 ..
-rw------- 2 root root 1017 Aug  6 09:49 ca_cert.crt
-rw-r--r-- 2 root root 1090 Aug  6 09:49 cert.crt
-rw------- 2 root root 1675 Aug  6 09:49 key.pem

I checked the deployed kubespray, and the setting is the same as [default](https://github.com/kubernetes-sigs/kubespray/blob/release-2.11/roles/etcd/defaults/main.yml#L13-L14)
> ~/pai-deploy/kubespray# grep -n -r etcd_config_dir .
./roles/etcd/defaults/main.yml:13:etcd_config_dir: /etc/ssl/etcd
./roles/etcd/defaults/main.yml:14:etcd_cert_dir: "{{ etcd_config_dir }}/ssl"

Please let me know if any suggestion.

**Comment by hzy46** [comment]
It's strange that you can't find the etcd's cert on worker node.

I suggest:

1. check the file `~/pai-deploy/kubespray/inventory/pai/hosts.yml`. You can attach it here if it is convenient.
2. check the kubespray script log, are these tasks run or skipped? You can run ansible-playbook with flag `-vvv`, and attach detailed log here.

**Comment by JosephKang** [comment]
Hello @hzy46 ,

1. Please refer to [host.yaml.txt](https://github.com/microsoft/pai/files/5054352/host.yaml.txt). The testgpu0-1111945-iaas and testgpu1-1112050-iaas are already deployed while **testcpu0-1111972-iaas** and **testcpu1-1111975-iaas** are the CPU nodes to be added.

2. The log of running command, **ansible-playbook -i inventory/pai/hosts.yml upgrade-cluster.yml --become --become-user=root --limit=testcpu0-1111972-iaas -e "@inventory/pai/openpai.yml" -vvv**, is shared in [add_cpu.log](https://github.com/microsoft/pai/files/5054364/add_cpu.log). The step for **Link etcd certificates for calico-node** is executed and failed bur not sure if any required step is missing.

**Comment by hzy46** [comment]
I assume you want to add 2 nodes. Why you use `--limit testcpu0-1111972-iaas`? I think it should be `--limit testcpu0-1111972-iaas,testcpu1-1111975-iaas`.

**Comment by JosephKang** [comment]
@hzy46 ,

The previous example is used to simple only 1 failed node since sometimes one of the two added node won't show the same error at the same time(But eventually they have the same errors.) 

The error ansible deploy log for adding 2 nodes is put here: [add_2cpu.log](https://github.com/microsoft/pai/files/5054466/add_2cpu.log)

**Comment by hzy46** [comment]
I have checked your log and can't get a good idea. The etcd cert generation steps are skipped in kubespray. In all, I think it is not an issue with OpenPAI. Since you got this problem in kubespray script, it may be a problem of kubespray. I suggest you to submit an issue in kubespray repo (or search for related issues). If you are familiar with ansible, you can modify the ansible playbook code to debug. In my opinion, I think there is something wrong in this file: https://github.com/kubernetes-sigs/kubespray/blob/release-2.11/roles/etcd/tasks/gen_certs_script.yml

**Comment by JosephKang** [comment]
@hzy46 ,

Based on the Ln. 1838 in [add_2cpu.log](https://github.com/microsoft/pai/files/5054466/add_2cpu.log), **etcd_cert_dir** is "_/etc/kubernetes/ssl_" instead of "_/etc/ssl/etcd/ssl_" defined [here](https://github.com/kubernetes-sigs/kubespray/blob/release-2.11/roles/etcd/defaults/main.yml#L13-L14)

Should I check any strange items?

**Comment by hzy46** [comment]
Is there any file in `/etc/kubernetes/ssl`?

**Comment by JosephKang** [comment]
ubuntu@testgpu0-1111945-iaas:~$ ls -alR /etc/kubernetes/ssl
/etc/kubernetes/ssl:
total 32
drwxr-xr-x 3 kube root 4096 Aug  6 09:49 .
drwxr-xr-x 4 kube root 4096 Aug  6 09:49 ..
-rw-r--r-- 2 root root 1090 Aug  6 09:49 apiserver-etcd-client.crt
-rw------- 2 root root 1675 Aug  6 09:49 apiserver-etcd-client.key
-rw-r--r-- 1 root root 1099 Aug  6 09:49 apiserver-kubelet-client.crt
-rw------- 1 root root 1679 Aug  6 09:49 apiserver-kubelet-client.key
-rw-r--r-- 1 root root 1025 Aug  6 09:49 ca.crt
drwxr-xr-x 2 root root 4096 Aug  6 09:49 etcd

/etc/kubernetes/ssl/etcd:
total 12
drwxr-xr-x 2 root root 4096 Aug  6 09:49 .
drwxr-xr-x 3 kube root 4096 Aug  6 09:49 ..
-rw------- 2 root root 1017 Aug  6 09:49 ca.crt

**Comment by hzy46** [comment]
Please show your files on the CPU node you want to add.

**Comment by JosephKang** [comment]
It seems that the cpu node directory is empty in /etc/kubernetes/ssl/

ubuntu@testcpu0-1111972-iaas:~$ ls -alR /etc/kubernetes/
/etc/kubernetes/:
total 16
drwxr-xr-x   4 kube root 4096 Aug 11 02:32 .
drwxr-xr-x 100 root root 4096 Aug 11 02:33 ..
drwxr-xr-x   2 kube root 4096 Aug 11 02:32 manifests
lrwxrwxrwx   1 root root   19 Aug 11 02:32 pki -> /etc/kubernetes/ssl
drwxr-xr-x   2 kube root 4096 Aug 11 02:32 ssl

/etc/kubernetes/manifests:
total 8
drwxr-xr-x 2 kube root 4096 Aug 11 02:32 .
drwxr-xr-x 4 kube root 4096 Aug 11 02:32 ..

/etc/kubernetes/ssl:
total 8
drwxr-xr-x 2 kube root 4096 Aug 11 02:32 .
drwxr-xr-x 4 kube root 4096 Aug 11 02:32 ..

**Comment by hzy46** [comment]
So it is strange that the cert is not generated. I suggest check the task in this https://github.com/kubernetes-sigs/kubespray/blob/release-2.11/roles/etcd/tasks/gen_certs_script.yml

**Comment by JosephKang** [comment]
I checked the [gen_certs_script.yml](https://github.com/kubernetes-sigs/kubespray/blob/release-2.11/roles/etcd/tasks/gen_certs_script.yml) but cannot find the task name shown in the log(E.g. Gen_certs | write openssl config). It is my assumption that current configuration for adding node will not execute **gen_certs_script.yml**

In the first deployment, I enable kubeadm by setting the following configuration as true
- https://github.com/kubernetes-sigs/kubespray/blob/release-2.11/inventory/sample/group_vars/all/all.yml#L6
- https://github.com/kubernetes-sigs/kubespray/blob/release-2.11/inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml#L163

I can see the task in **gen_certs_script.yml** is traversed after resetting the previous two configuration as false upon adding node though the adding result is still failed due to some missing scripts shown in [add_node_kubeadm_disable.log](https://github.com/microsoft/pai/files/5060901/add_node_kubeadm_disable.log).

Should I try redeploy the cluster and add nodes with disable kubeadm?

**Comment by hzy46** [comment]
I'm not sure whether this problem is with `kubeadm`. Instead, I can find the same issue about calico plugin like https://github.com/kubernetes-sigs/kubespray/issues/2883 . I suggest you to clean the environment, install OpenPAI using weave network plugin (Set `openpai_kube_network_plugin: weave` [in installation config](https://openpai.readthedocs.io/en/latest/manual/cluster-admin/installation-guide.html#config-example)). Then try to add node.

**Comment by JosephKang** [comment]
@hzy46 ,
Thanks for helping the survey. The change CNI from calico to weave still work in deployment and resolve cert generation issue during adding node. 

On the other hand I used to have weave plugin issue in https://github.com/microsoft/pai/issues/4515 in V0.17.0 deployment. Is it ok to change the default CNI from calico to weave?

@ydye , @fanyangCS 
Do you have any comment for weave capability and limitation?

**Comment by JosephKang** [comment]
@hzy46 

I did another test by keeping kubeadm parameter as false in the following default configuration
- https://github.com/kubernetes-sigs/kubespray/blob/release-2.11/inventory/sample/group_vars/all/all.yml#L6
- https://github.com/kubernetes-sigs/kubespray/blob/release-2.11/inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml#L163

The cluster can be deployed and the new node update-cluster flow can be executed successfully without changing CNI from **calico** to **weave**. Therefore I might prefer to keep calico as CNI.

**Comment by hzy46** [comment]
> @hzy46
> 
> I did another test by keeping kubeadm parameter as false in the following default configuration
> 
> * https://github.com/kubernetes-sigs/kubespray/blob/release-2.11/inventory/sample/group_vars/all/all.yml#L6
> * https://github.com/kubernetes-sigs/kubespray/blob/release-2.11/inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml#L163
> 
> The cluster can be deployed and the new node update-cluster flow can be executed successfully without changing CNI from **calico** to **weave**. Therefore I might prefer to keep calico as CNI.
> 
> Thanks a lot for the help.

Thanks for the information!
