### ISSUE TITLE
"Too many requests, please try again later." through job submission API

### ISSUE THREAD

**Issue by JosephKang** [microsoft/pai#4797]
**Organization Name**: Advantech

**Short summary about the issue/question**:
Get "Too many requests, please try again later." in different job submission API usage cases.

**Brief what process you are following**:
Get "Too many requests, please try again later." in the following 2 job submission cases:
1. Using API in bash script to submit 120 1 GPU jobs in an 8 GPU resource (Two 4 GPU VMs) environment. 60 of them will be places into waiting status and 60 of them will be rejected with "Too many requests, please try again later." response.
2. After the completion all the running job in case 1, I still get "Too many requests, please try again later." response even if I submit 1 job through API within certain time.

**How to reproduce it**:
Just follow step 1 and step 2 in the above description

**OpenPAI Environment**:
- OpenPAI version: v1.0.1
- Cloud provider or hardware configuration: OpenStack VMs
- OS (e.g. from /etc/os-release): ubuntu 16.04 LTS
- Hardware (e.g. core number, memory size, storage size, GPU type etc.): 8 GPUs

**Comment by JosephKang** [comment]
Hope to know how to change  the above limitation if the above issues are raised by some configurable limitation.

**Comment by abuccts** [comment]
https://github.com/microsoft/pai/blob/fbba438da73a4c9c9050b9d747fc9dfc6fbda51e/src/rest-server/config/rest-server.yaml#L21-L23

**Comment by JosephKang** [comment]
@abuccts 

The capacity of concurrent job submission can be changed with the above variables. 

Thanks to sharing.
