### ISSUE TITLE
[Design] Multiple clusters supporting

### ISSUE THREAD

**Issue by mydmdm** [microsoft/pai#4801]
[Design] Multiple clusters supporting
====

# User stories

- **Cluster-management**. User could manage clusters' configuration 
- **Job-discovering**. User could query (list) all his/her jobs from all clusters
- **Job-specialization**. User could render a job template for a specific cluster and submit it
- **Job-scheduling**. Job could be scheduled to a cluster according to user's preference and clusters' availability

## Job discovering
Users need to know the job status on all clusters when we provide multiple clusters. Therefore, we provide an interface to query the status of each job on the related cluster. Status includes: `WAITING`, `RUNNING`, `SUCCESS` and `FAILED`.

## Job specialization
When users submit jobs, they can submit to any cluster. Since every cluster may have customized configurations, e.g., storages, a job configuration (`yaml`) working well on a cluster may fail on another cluster. Thus we propose a `job template` based on template language (e.g. `Jinja`) to describe the common part of the job, and a cluster specific setting. 

For example, storages are often required to be rendered per cluster.
```yml
extras:
  com.microsoft.pai.runtimeplugin:
    - plugin: teamwise_storage
      parameters:
        storageConfigNames:
          - {{ storage }}
``` 
the `{{ storage }}` could be replaced by the target cluster's storage (e.g. by giving a dictionary as below or passing by key-value pairs)
```yml
cluster-a:
  storage: nfs-storage
cluster-b:
  storage: blob-storage
```

## Job scheduling
It is inconvenient to depend on user to select which cluster before submitting a job. However, it is neither reasonable to design a super scheduler taking over all the clusters. A practical way is to put a light weighted scheduler (arbitrator) above the clusters, which could make a final decision based on the scheduling result from each cluster. 

The simplest goal is to let jobs run on the cluster that could serve earliest. However, user may have preference on different clusters, e.g., given a K80 cluster and V100 cluster, user may prefer jobs to run on V100 cluster even if it is started some time later. 

To satisfy the requirements, a light weighted black-box scheduling algorithm is adopted as below.

**Presumption** Cluster *i* has a initial priority (*`a[i]`*) and a priority slop (*`b[i]`*), which indicate user's preference. Sort the list of clusters by the descending of initial priority, thus we have *`a[i] >= a[j]`* if *`i < j`*.

**Init** *`k = 0`*, and log current time as *`t0 = time()`*

**step-1** If *`time() - t0 == k * T`*, submit the job to *k*-th cluster and *`k += 1`*; Otherwise, skip. Here *`T`* is a buffering time. 

**step-2** Inventory the submitted jobs periodically and update their scores accordingly. For job on *i*-th cluster (*`i<=k`*), its score (*`p[i]`*) is modeled by

***`p[i] = a[i] + b[i] * max(0, time()-s[i])`***

here *s[i]* is the launched time of job *i*, set to a max positive number if the job is not started yet.

**step-3** Exit scheduling successfully if 

***`time() - s[c] > 0 where c = argmax_i{ p[i] }`***

Otherwise goto **step-1**.

Given the K80-cluster and V100-cluster scenario, user could give a larger *a* and *b* parameter for V100 cluster, and the guard time is 
***`GuardTime = (a[V100] - a[K80]) / b[K80]`***

# Implementations and Action items

- [ ] MVP - cli tool running in local env
    - [ ] SDK enhancement
        - [ ] basic
            - [x] manage a list of clusters (store / restore)
            - [ ] query jobs from all clusters
        - [ ] job template
            - [ ] define job template format (based on `jinja`?)
            - [ ] support template rendering 
                - [ ] parameter / secret rendering in SDK (?)
            - [ ] sub job to a manually specified cluster
        - [ ] scheduling based on job inventory
    - [ ] cli interface

- [ ] stand-alone service for multiple users
    - [ ] REST api
        - [ ] cluster management
        - [ ] job viewing
        - [ ] job submitting
    - [ ] web ui
        - based on webportal plugin (??)
    - [ ] backend
        - [ ] user system
        - [ ] cluster / token storage
        - [ ] job system

**Comment by hzy46** [comment]
Close this to use #4929 instead.
