### ISSUE TITLE
how to realize this sentence: "please use RESTful API to assign storage to the groups of the user"? 

### ISSUE THREAD

**Issue by yingunjun** [microsoft/pai#4806]
I'm not familiar with k8s. In the Admin Mannual, there is a sentence with words "please use RESTful API to assign storage to the groups of the user" in "Assign Storage to PAI Groups" part, I don't know how to handle it. Could you give me some examples?

**Comment by hzy46** [comment]
Do you know about HTTP request? It means you send several requests to PAI's rest server. The rest-server url is `http(s)://<pai-master-ip>/rest-server`

**Comment by yingunjun** [comment]
> Do you know about HTTP request? It means you send several requests to PAI's rest server. The rest-server url is http(s)://<pai-master-ip>/rest-server

Thank you very much for your answer. I'm not good at http request, but I used Postman to send GET request with token, I got the result as flow:
{
  "groupname": "default",
  "description": "group for default vc",
  "externalName": "",
  "extension": {
    "acls": {
      "admin": false,
      "virtualClusters": ["default"]
    }
  }
}
no  "storageConfigs": [], line exist.  Could you tell me what the problem with it?

**Comment by hzy46** [comment]
No problem, just add it by your self.

**Comment by yingunjun** [comment]
> No problem, just add it by your self.

Could you tell me how to add storage? I used Postman to send post request as follow, but got error message. Please check the picture as follow for detail. 

![图片](https://user-images.githubusercontent.com/50563443/90086997-4b602080-dd4e-11ea-854f-3bb77afe134a.png)

**Comment by yingunjun** [comment]
> No problem, just add it by your self.

Could you tell me how to add storage? I used Postman to send post request as follow, but got error message. Please check the picture as follow for detail.
![002](https://user-images.githubusercontent.com/50563443/90087272-ee189f00-dd4e-11ea-8293-5136258780d6.png)

if you cannot open image above. Please refer to the information below.

post Params:
    key: storageConfigs
    value: nfs-storage
post was sent like this: http://node11/rest-server/api/v2/groups/default/?storageConfigs=nfs-storage
result body:
{
    "code": "NoApiError",
    "message": "API /api/v2/groups/default/?storageConfigs=nfs-storage is not found."
}

**Comment by hzy46** [comment]
Add it to your request body, 

```
{
  "data": {
    "groupname": "default",
    "extension": {
      "acls": {
        "storageConfigs": ["nfs-storage"],
        "admin": false,
        "virtualClusters": ["default"]
      }
    }
  },
  "patch": true
}
```

**Comment by yingunjun** [comment]
> Add it to your request body, like:
> 
> ```
> {
>   "data": {
>     "groupname": "default",
>     "extension": {
>       "acls": {
>         "storageConfigs": ["nfs-storage"],
>         "admin": false,
>         "virtualClusters": ["default"]
>       }
>     }
>   },
>   "patch": true
> }
> ```

Thank you very much for your advice. please help me to check the POST setting. it still has some problem result.

![post图片 ](https://user-images.githubusercontent.com/50563443/90098260-63de3400-dd6a-11ea-9d6e-0eb57107dfac.png)

**Comment by hzy46** [comment]
Use PUT, not post, and the URL should be `http://node1/rest-server/api/v2/groups`. You can see the api here: https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/microsoft/pai/master/src/rest-server/docs/swagger.yaml#operation/updateGroup

**Comment by yingunjun** [comment]
> Use PUT, not post, and the URL should be `http://node1/rest-server/api/v2/groups`. You can see the api here: https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/microsoft/pai/master/src/rest-server/docs/swagger.yaml#operation/updateGroup

Aha, thank you a lot, I made a mistake, I saw the 'PUT' as 'POST'. That's very kind of you to remind me. Thank you again. It works.
![put图片](https://user-images.githubusercontent.com/50563443/90099169-6d689b80-dd6c-11ea-94b6-e13ae1282b6a.png)

**Comment by hzy46** [comment]
Thanks for the information. I think this function should have a UI to make it more easy-to-use.
