### ISSUE TITLE
Running jobs on a master node

### ISSUE THREAD

**Issue by zlf0625** [microsoft/pai#4812]
Hi,

I wonder how I can run jobs on the master node of a PAI cluster? I have a few GPU machines, and currently, one node as PAI master cannot assign jobs even when I set SKU for it.

Also, is there single-node / single-box installation guide for 1.x version? I can only find such a guide for 0.x version.

Thank you!

**Comment by fanyangCS** [comment]
https://github.com/microsoft/pai/issues/4566.

**Comment by debuggy** [comment]
Close the issue. Feel free to reopen it if you have further questions.
