### ISSUE TITLE
HiveScheduler dispatch behavior configuration

### ISSUE THREAD

**Issue by JosephKang** [microsoft/pai#4813]
**Organization Name**: Advantech

**Question description**:
The hivescheduler seems to dispatch task to new *Physical placement* only until the GPU/CPU resource in the previous  *Physical placement* is exhausted by default. For example, In a VC with 2 4-GPU workers named worker0 and worker1, the hive scheduler will place the task to worker1 only until all 4-GPU in worker0 are used.

Could I change the scheduling behavior to *load-balancing* dispatching so that the hivescheduler will do *Physical placement* based on the current maximum resources? E.g. At first all 4 GPU are available in both worker0 and worker1, and 1-GPU task will be placed on worker0. Upon the next task is given and worker0 has 3 free GPU and worker1 has 4 free GPU, the hivescheduler will dispatch the task to worker1.

**OpenPAI Environment**:
- OpenPAI version: v1.0.1
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
2 4-GPU workers and 2 16-CPU workers

**Comment by fanyangCS** [comment]
This is the default behavior of our intra-VC scheduler. https://github.com/microsoft/hivedscheduler/blob/fbff5b09b49f3373b192e3eead9cede2634a4732/pkg/algorithm/intra_vc_scheduler.go.

Currently the VC scheduler does not support anti-affinity scheduling policy. 

Can you explain why do you need such behavior?

**Comment by JosephKang** [comment]
In openpai v0.10.1, the scheduling seems to distribute jobs among available instead of occupying jbos to worker node one by one.
Just curious that why the default scheduling policy is not as same as before.

**Comment by yqwang-ms** [comment]
Compared with previous policy, current default policy is generally better for deep learning batch jobs, such as improved training perf, and reduced intra-VC resource fragments.
We can add more policys in future.

Pls reopen if any unclear :)
