### ISSUE TITLE
Local PV support

### ISSUE THREAD

**Issue by zlf0625** [microsoft/pai#4815]
Does OpenPAI support local persistent volumes?

I successfully created a local PV storage, local StorageClass (for node affinity), and local PVC storage, but when I use PUT to update the rest-server, I cannot find it in the job submission page. I tried NFS storage before and it works well. 

I also tried to not set `volumeBindingMode: WaitForFirstConsumer` for PVC node affinity (so the status is `Bound` like NFS's PVCs, instead of `pending`), and then I can find it in the submission page immediately, but this would break the PV's affinity.

Thanks

**Comment by Binyang2014** [comment]
Hi @zlf0625. Can you clarify your requirement? Remove  `volumeBindingMode: WaitForFirstConsumer` will not break the PV's affinity, but may cause pod unschedulable. Refer to https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode

For example, if you let two nodes (`node1` and `node2`) offer local storage. You need to create two PV such as `local-pv-1`, `local-pv-2`. 

If you are using `volumeBindingMode: WaitForFirstConsumer`. You **DO NOT** need to create PVC. But define PVC spec in pod spec. These blog has an example: https://kubernetes.io/blog/2019/04/04/kubernetes-1.14-local-persistent-volumes-ga/#:~:text=What%20is%20a%20Local%20Persistent,file%20storage%20to%20persist%20data. 
In the spec you need to set `storageClassName`. Then k8s will help you select a node which has bounded to local PV also has sufficient resource (CPU/Mem).
PVC object will be created by k8s automatically. 

If you create PVC manually, such as `pvc-local-1`, bounded to `local-pv-1`, you don't need to use `storageClass`. Your pod will always scheduled to `node1` . But the node may can not meet your CPU/Memory requirement.  Even though `node2` can meet your requirement.

**Comment by zlf0625** [comment]
Yes, I am creating a Local Persistent Volume in Kubernetes and trying to use it in OpenPAI like other storage such as NFS (`Assign Storage to PAI Groups` in `https://openpai.readthedocs.io/en/latest/manual/cluster-admin/how-to-set-up-storage.html`). I created (1) PV, (2) StorageClass and (3) PVC, but now I think I understand what you mean thanks to your explanation. 

Can I also do `Assign Storage to PAI Groups` like an NFS storage? If not, how do I add such parameters to OpenPAI jobs through the UI, since I think it follows OpenPAI's own protocol?

**Comment by Binyang2014** [comment]
Yes, you can assign local PV to PAI groups. I think you can use RestAPI to update the group. Then you can use the storage just like `NFS`.
But the `profile` page in pai may broken, since the frontend can not recognize this `storage type`. Other pages should be OK

**Comment by zlf0625** [comment]
Thanks. How do I add a local PV via RestAPI? Should I expect to see the storage in the submission page? Now I only create (1) a Local PV and (2) a StorageClass, but no PVC. I tried to PUT the name of the Local PV or the name of the StorageClass, but they didn't work (not seen in the submission page).

**Comment by Binyang2014** [comment]
Sorry, I don't understand your question.

You can create (1) Local PV without StorageClass. (2) Create PVC bound this PV. (3) update pai group using PVC name.
But you cannot using PV/StorageClass name directly in PAI. And PAI doesn't support that. Either though PAI API or protocol. Currently, pai doesn't support `dynamic binding`

Hope this can answer your question.

**Comment by zlf0625** [comment]
Thanks. I got what you mean and successfully configured it. I just figured out that `(2) Create PVC bound this PV` can be easily done with the same names of a PV and PVC.

**Comment by lbin** [comment]
@Binyang2014 When will pai support **dynamic binding**?

**Comment by Binyang2014** [comment]
@lbin, Currently, we don't have such requirement. If you think this feature is important, please fire a requirement issue. Explain why this feature is needed and provide the use cases. Then we  will investigate and make a plan.
BTW, contribution is welcome!

**Comment by lbin** [comment]
> @lbin, Currently, we don't have such requirement. If you think this feature is important, please fire a requirement issue. Explain why this feature is needed and provide the use cases. Then we will investigate and make a plan.
> BTW, contribution is welcome!

If we have many nodes and each node has a local pv(for faster data transfer), before press submit button, we donot know which node will be used.

**Comment by Binyang2014** [comment]
@lbin, Please create another issue for this. Since this issue already close, we need another issue to track this.
