### ISSUE TITLE
How to use https to access OpenPai

### ISSUE THREAD

**Issue by guningbo** [microsoft/pai#4820]
**Organization Name**: Hangzhou Innovation Institute, Beihang University

**Short summary about the issue/question**: 
I have installed the OpenPai with v1.1.1. Now I want to access k8s dashboard in the OpenPai Webportal. But, the tutorial prompt "To use it, you should first set up https access (Using http://<ip> won't work) for OpenPAI. "  I have no idea how to use https to access OpenPai

**Brief what process you are following**: 

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version: v1.1.1
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): ubuntu1604
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by hzy46** [comment]
You can refer to this (old) document: https://github.com/microsoft/pai/blob/v0.17.0/docs/aad-e2e/aad-e2e.md#pylon-prepare-your-certificate-for-https-self-sign-cert-as-an-example

I will move it into the OpenPAI handbook for easy access in the future.

**Comment by hzy46** [comment]
Fixed in #5078 and #5076
