### ISSUE TITLE
How to install SSL certificate in OpenPAI？

### ISSUE THREAD

**Issue by wangzhao123456** [microsoft/pai#4825]
**Organization Name**:

**Short summary about the issue/question**:
Hello, I installed OpenPAI v0.13.0 and it works fine. But now I want to access to OpenPAI using https protocal. I don't know how to install SSL certificates and modify OpenPAI codes to make it support https.  I would greatly appreciate if someone gives a little guides. Thanks in advance!

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by hzy46** [comment]
You can refer to this document: https://github.com/microsoft/pai/blob/v0.17.0/docs/aad-e2e/aad-e2e.md#pylon-prepare-your-certificate-for-https-self-sign-cert-as-an-example

**Comment by fanyangCS** [comment]
I suggest you use our latest version.

**Comment by wangzhao123456** [comment]
> I suggest you use our latest version.

Thanks
