### ISSUE TITLE
Could default VC allows CPU only?

### ISSUE THREAD

**Issue by debuggy** [microsoft/pai#4847]
It might be a common requirement for a CPU only sku, maybe default vc should allows it.

![image](https://user-images.githubusercontent.com/8444268/91407964-a6793380-e875-11ea-82f3-ff2480c03be7.png)

**Comment by fanyangCS** [comment]
yes it does support it, as long as admin config the right sku in the cluster.

**Comment by debuggy** [comment]
close as by design
