### ISSUE TITLE
Fix quick start resource calculate

### ISSUE THREAD

**Issue by Binyang2014** [microsoft/pai#4848]
For quick start script. The resource calculate is not accurate. Need to calculate based on PAI config

**Comment by fanyangCS** [comment]
we need to document the resource requirement of each PAI service, starting from those deployed in worker nodes.

**Comment by Binyang2014** [comment]
Double checked the PAI deploy script. For quick start, the `qos-switch` for PAI service is `false`. So if we use default config, we won't suffer this issue.(The QOS class for PAI daemonSet will be BestEfforts) But seems we changed the config when deploying INT bed,

Still working on quick start script, but seems not a blocking issue

**Comment by Binyang2014** [comment]
Quick-start script change: https://github.com/microsoft/pai/pull/4855
