### ISSUE TITLE
About the kubernetes-boot.sh

### ISSUE THREAD

**Issue by 123toorc** [microsoft/pai#4869]
**Short summary about the issue/question**:   

**This is my guess, if it is wrong just ignore it:** My master node(VM) is running on a private cloud, its network interface IP is not the floating IP that was assigned. 
**Fail log:**
***********************************************************************************************************
TASK [kubernetes/preinstall : Stop if ip var does not match local ips] ******************************
Thursday 03 September 2020  05:46:11 +0000 (0:00:00.257)       0:00:17.214 ****
fatal: [node]: FAILED! => {
    "assertion": "ip in ansible_all_ipv4_addresses",
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}
***********************************************************************************************************

**OpenPAI Environment**: passed requirement.sh except I can't access the gcr.io, which brings another question: I encountered problems during the ansible-downloading (the Azure China mirror server was down), the images were distributed to different repo, clearly to configure this is impossible. **My solution is I pull the necessary docker images my self, is that Ok? I'm not sure really!** Because there is no problem and I passed the download period smoothly. 
- OpenPAI version: v1.0.0
- Others: ** another short question, does the **ip does not match local ip** affect the later installation part of the etcd? I try to ignore this assertion(commented), while unfortunately later the **etcd check healthy** was failed(try just comment it, then the Kubernets master init was failed too). I do believe that fatal error is come from here. Please any solutions?**

**Anything else we need to know**: Thank you very much! Very great job, A mighty TEAM! Please save my life!

Thanks, 
Tong
BBD intern

**Comment by hzy46** [comment]
1. For IP address problem: I suggest you to use the private cloud IP (local ip) to set up OpenPAI system. If you need a gateway, you can setup it yourself.

2. For network issue, I suppose you are deploying PAI in China. If so, please read https://openpai.readthedocs.io/en/latest/manual/cluster-admin/configuration-for-china.html first. Please check if `gcr.azk8s.cn` works for you. If it doesn't, you could find another gcr.io mirror. I don't suggest to pull the image yourself, it is a bit messy.

**Comment by 123toorc** [comment]
Thank you! My friend! Really appreciate!
Two more questions:
1. Except for your suggestion, is there any other way to do it? I'm afraid that I don't have enough privilege to do so on the private cloud. I will try to ask somebody if it is possible to let my worker machine's router set a gateway in order to find the master machine(**I really don't think I can do it**), but is there any other solution? and it did relate to the later etcd stuff, right? Sorry, I'm not familiar with this. 
2. If I passed the downloading(because I have pulled some images), is this means it is worked? I just afraid I did the wrong thing. To be honest, finding a mirror is a bit messy too. 
Thank you very much!

**Comment by hzy46** [comment]
1. You must use a static IP, otherwise it will cause problem both for k8s and openpai.
2. If you make sure the command `docker pull gcr.io/xxxx` will work on every node, there will be no problem. Just have a try.

**Comment by 123toorc** [comment]
Thanks, I believe I know what I need to do, for the summary: My worker node and the master node is in different private cloud. What you mean is that I can't use the external IP that binds with the internal IP of the Master node, the only solution is to fix the router and iptable to export the internal IP of the master node to the worker node right?  
Please confirm or correct it. I need to report to my supervisor, thank you very much, my dear friend!!

**Comment by hzy46** [comment]
Yes, please put them in the same private cloud, and use local IP to deploy PAI. If you need external network access, assign a external IP to the master node.

**Comment by 123toorc** [comment]
Thank you very much!
