### ISSUE TITLE
How to run CPU tasks on GPU Workers

### ISSUE THREAD

**Issue by IamSunGuangzhi** [microsoft/pai#4871]
How to run CPU tasks on GPU Workers?
I submit a job (gpu=0) on gpu worker, the task occupy all gpu on gpu node. 

**OpenPAI Environment**:
- OpenPAI version: v1.0.1

**Comment by IamSunGuangzhi** [comment]
When can this problem be fixed?

**Comment by fanyangCS** [comment]
related to https://github.com/microsoft/pai/issues/4602.

**Comment by abuccts** [comment]
@IamSunGuangzhi Could you describe your question more clearly? Which scheduler did you use, k8s default scheduler or HiveD scheduler? And what configuration did you use?

If you are using HiveD scheduler, you could always submit a job with 1 GPU and run CPU only process in that job. There's no way to submit CPU only job on GPU nodes if you also want to run GPU jobs on that node which will break cell assignment in scheduler.

You can either set up CPU nodes and corresponding VC for CPU jobs, or change to k8s default scheduler.

**Comment by fanyangCS** [comment]
closed as no further response.
