### ISSUE TITLE
Resource allocation visualization is out-of-sync

### ISSUE THREAD

**Issue by JosephKang** [microsoft/pai#4905]
**Organization Name**:
Advantech

**Short summary about the issue/question**:
1. Sometimes the usedCapacity is out of sync(E.g. Snapshot below indicates 12.5% usage on API response and 25% usage on Web)
![vc_resource_unsync](https://user-images.githubusercontent.com/3213161/93063619-1aef0780-f6a9-11ea-8d32-3585d8a580f7.jpg)

2. Sometimes the resource is marked as invalid 0(E.g. Snapshot below that the average resource for each node is marked as 0)
![vc_zero_resource](https://user-images.githubusercontent.com/3213161/93063818-60abd000-f6a9-11ea-99c9-e1dbbabc1a33.jpg)

**Brief what process you are following**:
NA

**How to reproduce it**:
NA

**OpenPAI Environment**:
- OpenPAI version:
V1.0.1
- OS (e.g. from /etc/os-release):
ubuntu 16.04.6 LTS

**Comment by yqwang-ms** [comment]
The percentage 25% = 1 (used) / 4 (guarrenteed), instead of 1 (used) / 4 (total).
The 0 means bad nodes, instead of free resource.

Anyway, the webportal here is confusing, @abuccts to give more info

**Comment by JosephKang** [comment]
The following two snapshot are captured with the same resource usage and about 5 seconds difference.

![1](https://user-images.githubusercontent.com/3213161/93209066-1fdab680-f790-11ea-8bee-aeac9730a9ea.png)
![2](https://user-images.githubusercontent.com/3213161/93209069-223d1080-f790-11ea-8704-0e9962088bf7.png)

Not sure how to explain the guarrenteed, total and bad node situation for the **devgpu** cluster.

**Comment by yqwang-ms** [comment]
Pls check all your 2 nodes on k8s dashboard, maybe one of them frequently switch between unhealthy and healthy

**Comment by JosephKang** [comment]
> Pls check all your 2 nodes on k8s dashboard, maybe one of them frequently switch between unhealthy and healthy

Thanks. The unhealthy status is tracked in another issue, https://github.com/microsoft/pai/issues/4910.

**Comment by JosephKang** [comment]
@yqwang-ms 

Yap. It seems that one nginx-proxy pod is not in ready status and tracked in another ticket: https://github.com/microsoft/pai/issues/4910
