### ISSUE TITLE
Multi Cluster Load Balance 

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#4929]
## Motivation
A user can access to multiple clusters, and the clusters may vary significantly in availability, cost, and congestion. For example, there may be an expensive powerful cluster with V100 GPUs, but always busy, while another cheap K80 cluster is much idle. It is reasonable to balance the workloads (jobs) to the most appropriate cluster to reduce total waiting time or cost. Since different customers may have diverse needs, the policies to direct the load balance must be highly customizable. (***Note: Only waiting jobs could be balanced, running jobs will not be touched.***)
 
- **Scenario A**: The user has one on-prem cluster (limited resource) and an on-cloud cluster (scalable). If the on-prem cluster is too congested (too many long-waiting jobs), some of the long-waiting jobs may be balanced to the on-cloud cluster to reduce the total waiting time.

- **Scenario A+ (generalization of A)**: The user has access to multiple clusters. If some clusters are too congested (too many long-waiting jobs), some of the long-waiting jobs could be balanced to another (free) cluster to reduce total waiting time.

## Proposal - multiple cluster load balance service

**Design Goal**: Provide a mechanism (service) to empower users take full advantage of multiple clusters automatically, thus meet users' custom requirement (e.g. reduce completed time, reduce waiting time, reduce cost, etc.)

The service provides the following functions to users:
1. monitor the congestion of multiple clusters, and filter the _balanceable_ jobs per the **job-selection policies** (e.g. jobs waiting for a given time in a cluster)

1. for each selected job, find the most appropriate target cluster according to **cluster-selection policies** (e.g. available and most powerful, or cheapest) and _clone_ the job from current cluster to target cluster

1. after cloning the job to target cluster, stop the original job intermediately or let the old/new jobs compete (until one of them is started) according to **post-action policies**

Notes:
- All the policies mentioned above would be ***customizable*** by users (admins), there may be also other polies such as 
    - **historical policies** to setup the historical (or stateful) constraints for a job (e.g. max times of migrations for a job, max number of clones allowed at the same time)
    - policies are defined when service starting, not support dynamic changing in the first; per-job policy setting could be an option for further discussion

- To support above policies, the scheduling service may communicate with each cluster for 
    - cluster status, such as available sku types and # of skus in the VC ...
    - job status, such as job status, submitting time, job tags ...
    - (future) job execution statistics and estimations for advanced scheduling, e.g. estimated data throughput, estimated job execution time, ...

- A job is _balanceable_ means a job is in `WAITING` state and defined by a template (and cluster specific context). The format of template and context will be in a separate issue

- The balancing attempts (history) will be traced in database or by job tagging

- This service is backend only. A webportal to view, manage multiple clusters, nodes, and jobs will be in a separate issue

**Comment by mydmdm** [comment]
back up current proposal before editing. 
----
1. **Background**: One customer may have access to multiple clusters, and they may want their job to be scheduled to the most appropriate cluster to reduce total waiting time or cost. Different customers may have different needs.
    - **Scenario A**: The customer has one on-prem cluster, and he also has access to one on-cloud cluster. The on-cloud cluster will charge him some fees when he uses it. If the job in the on-prem cluster exceeds certain waiting time, he wants his job to be scheduled to the on-cloud cluster.
    - **Scenario B**: The customer has one on-prem cluster, and he also has access to one on-cloud cluster. The on-cloud cluster will charge him some fees when he uses it. He wants his high-priority job to be scheduled to the on-cloud cluster if the on-prem cluster doesn't have enough resource. He doesn't want his low-priority job to be scheduled to the on-cloud cluster because it will charge him extra money.
   - **Scenario C** : The customer has one K80 cluster, and one V100 cluster. He wants his job to be scheduled on the V100 cluster in preference to the K80 cluster. However, if the job sticks in `WAITING` status for some time, he wants his job to be scheduled to the K80 cluster.


2. **Design Goal**: Empower the customer to set up a scheduling policy between different clusters to achive certain goal (e.g. reduce completed time, reduce waiting time, reduce cost, etc.)

3. **Proposal**: Multi Cluster Scheduling Service

    The service has the following interface:

    - Customer can submit multiple cluster job to it.
    - Customer can query the multiple cluster job's status (selected cluster, migration times, etc.)

    The service should generate different configs for different clusters.

    Customer can define a ***Selection Function***  in the scheduling service:

     - Input: 
       - previous selected history 
       - current cluster available resource
       - job status history in different cluster
       - job config 
     - Output: [selected clusters, if the job should be finished] 
       - selected clusters: The service will compare the output with the previous one. If previous selected clusters contain A, but this time we don't select A, we will try to stop the job on A. If previous selected clusters don't contain A, but this time we select A, we will try to submit the job on A. If there is no difference, no-op.
       - if the job should be finished: whether the multi-cluster job is finished.

Selection Function will be called periodically.  After it is called, the scheduler will do certain operation (stop / submit job). The operation has a timeout. Job status includes both normal openpai job status (waiting, running, succedded, stopped, stopping, failed), missing (somehow we cannot find the corresponding job), unreachable (network error).

The main execution loop for a job looks like: Selection Function -> Operation -> Selection Function -> Operation ..... -> Selection Function

4. **How the proposal solves the above scenarios?**
    - **Scenario A**

    ```
    If (previous selected history is None) {
       return ["on-prem"], false
    } else if (all jobs are in `missing` status) {
       return [""], true
    }  else if (job is in the on-prem cluster) {
      if (it is waiting too long) {
        return ["on-cloud"], false
      } else {
        return ["on-prem"], job_status is "Completed"
      }
    } else if (job is in the on-cloud cluster) {
      return ["on-cloud"], job_status is "Completed"
    }
    ```

    - **Scenario B**
    ```
    If (previous selected history is None) {
        if (on-prem cluster has enough resource or the job is low-priority)  {
           return ["on-prem"], false
        } else {
           return ["on-cloud"], false
        }
    } else if (all jobs are in `missing` status) {
       return ["<previous selected cluster>"], true
    }  else {
       return ["<previous selected cluster>"], job_status is "Completed"
    }
    ```

   - **Scenario C**: very like scenario A.


5. **Future Work**: When migration happens, enable the customer to set some preprocessing / postprocessing.

**Comment by hzy46** [comment]
Final Design:

1. a section on user profile page to let users register bounded clusters (change the name to Bounded Clusters in the following pic)

![image](https://user-images.githubusercontent.com/7499023/97150031-80560e00-17a8-11eb-9e14-5494b4f5df79.png)

2. User can click a transfer button to transfer job on job detail page

3. The transfer page looks like:

![image](https://user-images.githubusercontent.com/7499023/97150156-b1364300-17a8-11eb-90be-62533d8118e7.png)

4. After job is transferred, show the message to user:

![image](https://user-images.githubusercontent.com/7499023/97150202-c14e2280-17a8-11eb-874a-2b3613ac774c.png)
