### ISSUE TITLE
set up an https self-signed certificate during installation if user desires so

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#4931]
1. Currently, we have a shortcut to the k8s dashboard in the webportal. However, after the user installs a fresh new openpai cluster, he/she cannot access the dashboard by default. Because it requires he/she set up an https certificate. 

   ![image](https://user-images.githubusercontent.com/7499023/93959214-c6bfe380-fd8a-11ea-8c1d-ec34e8d92326.png)

2. we can make openpai generates a self-signed certificate to let the fresh users access the k8s dashboard

**Comment by hzy46** [comment]
After discussion, we think that the self-signed certificate is not safe and it should not be made as a default. So we should add an explicit flag. If user sets the flag, we make the self-signed certificate for him.

Also, the doc needs a re-org.

**Comment by sumeng1024** [comment]
@hzy46 It is not clear in the guide, I created an https self-signed certificate follow the doc but don`t know how to use it.

**Comment by hzy46** [comment]
Thanks, the doc problem is known. We will fix it recently.

**Comment by hzy46** [comment]
Fixed in #5078 and #5076
