### ISSUE TITLE
Virtual cluster and node mapping

### ISSUE THREAD

**Issue by JosephKang** [microsoft/pai#4932]
**Organization Name**: Advantech

**Short summary about the issue/question**:
Do we have virtual cluster and node mapping APIs? 
Ref: https://github.com/microsoft/openpaisdk/blob/master/docs/rest-api.md

**OpenPAI Environment**:
- OpenPAI version:
v1.0.1

- OS (e.g. from /etc/os-release):
ubuntu 16.04

**Comment by yqwang-ms** [comment]
You can call the http://{master-node-address}:30096/v1/inspect/clusterstatus/physicalcluster, which is the hived API.

See:
https://github.com/microsoft/pai/blob/master/src/hivedscheduler/deploy/hivedscheduler-service.yaml.template
https://github.com/microsoft/hivedscheduler/blob/df185eecde3b23a0cb780e6ce5b4828acc98db0f/pkg/api/constants.go#L91

**Comment by fanyangCS** [comment]
please note that this is an internal API and may subject to change in the future. We are working on a more complete support to HiveD.
