### ISSUE TITLE
Core-DNS miss config lead to storage-manager samba access failed

### ISSUE THREAD

**Issue by Binyang2014** [microsoft/pai#4943]
For user who use AD. We got an issue when user using samba to access storage-manager.
The reason is in storage-manager the Domain Controller dns can not be resolved. After adding nameserver to
/etc/resolv.conf in pod. This issue seems fixed.

The maybe can solved by reconfigure the Core-dns. refer: https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#configuration-of-stub-domain-and-upstream-nameserver-using-coredns

**Comment by fanyangCS** [comment]
archived. core dns related.
