### ISSUE TITLE
I want to use CPU-only worker, How do I install quick start- service.sh script

### ISSUE THREAD

**Issue by youxingtian** [microsoft/pai#4945]
**Organization Name**:

**Short summary about the issue/question**:

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by fanyangCS** [comment]
The Quick-start tool only supports GPU servers currently.

**Comment by youxingtian** [comment]
> The Quick-start tool only supports GPU servers currently.

How do I modify quick start- service.sh Script to meet  install  CPU-only worker

**Comment by fanyangCS** [comment]
https://openpai.readthedocs.io/en/latest/manual/cluster-admin/installation-guide.html#tips-to-use-cpu-only-worker

**Comment by youxingtian** [comment]
> The Quick-start tool only supports GPU servers currently.

![image](https://user-images.githubusercontent.com/49486786/95093238-22ab4480-075b-11eb-9e70-fe56e2343d5f.png)

**Comment by youxingtian** [comment]
> > The Quick-start tool only supports GPU servers currently.
> > How can I solve this problem when I'm using quick start- service.sh script
> > ![image](https://user-images.githubusercontent.com/49486786/95093238-22ab4480-075b-11eb-9e70-fe56e2343d5f.png)
