### ISSUE TITLE
Built error, internal-storage-create is not ready yet. Please wait for a moment!

### ISSUE THREAD

**Issue by cdd1993** [microsoft/pai#4951]
Hi，All:
When I execute the  quick-start-kubespray.sh, the following error appears:
![WeChat Screenshot_20201012171623](https://user-images.githubusercontent.com/28085921/95729051-da39dc80-0cae-11eb-8f4d-c0d1d1b95ce2.png)
![WeChat Screenshot_20201012171640](https://user-images.githubusercontent.com/28085921/95729060-ddcd6380-0cae-11eb-9c7f-9a188104d8c4.png)

Hope to get answers from everyone, very grateful

**Comment by hchoi405** [comment]
I met the same error for v1.2.0...

**Comment by hzy46** [comment]
Hi, could you provide the following material?

1. On your master node, run `df -h` and give me the result.

2. On your dev box machine, run `kubectl logs `kubectl get po  | grep internal-storage | awk '{print $1}'`` and give me the log.

**Comment by cdd1993** [comment]
> 嗨，您能提供以下材料吗？
> 
> 1. 在您的主节点上，运行`df -h`并给我结果。
> 2. 在开发机上运行
> 
> ```
> kubectl logs `kubectl get po  | grep internal-storage | awk '{print $1}'`
> ```
> 
> 并给我日志。
Hi,hzy46,the output of the commands are as follows,i am not sure the second one is what you want or not
![master](https://user-images.githubusercontent.com/28085921/95842292-f4d88800-0d78-11eb-8694-532b7aecdf65.png)
![dier](https://user-images.githubusercontent.com/28085921/95842294-f5711e80-0d78-11eb-8712-bf985fa76113.png)

**Comment by hzy46** [comment]
Could you run `kubectl get ds`? Maybe the pod is not created yet.

**Comment by cdd1993** [comment]
> 你可以跑步`kubectl get ds`吗？可能尚未创建广告连播。
Hi,zhiyuan,the outputs are as follows:
![Uploading output.png…]()

**Comment by hzy46** [comment]
I can't see your output. It's broken..

![image](https://user-images.githubusercontent.com/7499023/95843517-5fd68e80-0d7a-11eb-9dbb-0f1e3240f94e.png)

**Comment by hzy46** [comment]
The ds is created but the pod is not created. Maybe your nodes are not correctly labeled. Please help me confirm by `kubectl get node --show-labels`.

**Comment by cdd1993** [comment]
> kubectl get node --show-labels
Hi,zhiyuan,thanks for your reply, the outputs of kubectl get node --show-labels are as follows:
![output1](https://user-images.githubusercontent.com/28085921/95846180-b5f90100-0d7d-11eb-8676-e3bda14d647f.png)

**Comment by hzy46** [comment]
The root cause is the nodes are not correctly labeled. I have fixed this issue in #4925. Are you installing `v1.2.0`? I think `v1.2.0` won't have this problem.

**Comment by cdd1993** [comment]
> The root cause is the nodes are not correctly labeled. I have fixed this issue in #4925. Are you installing `v1.2.0`? I think `v1.2.0` won't have this problem.

I think the version i installed is V1.0.0,so I need to change the branch_name and docker_image_tag in the config?

**Comment by hzy46** [comment]
Yes, please change them and re-run the installation script.

**Comment by cdd1993** [comment]
> Yes, please change them and re-run the installation script.

Hi,zhiyuan, I have change the version to V1.2.0, but got an another error, the detail are shown in the picture
![output3](https://user-images.githubusercontent.com/28085921/95955060-d6cd5f00-0e2e-11eb-9f64-11d70d637c57.png)

**Comment by hzy46** [comment]
@Binyang2014 Could you have a look this issue? I think it has relation to the resource calculation.

**Comment by Binyang2014** [comment]
@cdd1993 This is a bug, Could change the code like this:
https://github.com/microsoft/pai/blob/4ed5a2a9aba851dcd48ba5e8b26dd08d9926cb72/contrib/kubespray/script/openpai-generator.py#L288-L289.
Here is the related PR #4962

**Comment by hzy46** [comment]
@cdd1993  So basically you can use the branch `binyli/config-generate` in your config for a workaround.

@Binyang2014 Please correct me if this comment is wrong.

**Comment by Binyang2014** [comment]
@hzy46 created a branch named `binyli/pai-1.2-config-generate`.
@cdd1993 Please try branch `binyli/pai-1.2-config-generate` to deploy PAI. You can

**Comment by fanyangCS** [comment]
@Binyang2014 , should we deploy a hotfix?

**Comment by Binyang2014** [comment]
@fanyangCS will sync with @yiyione about this. Since it's a deploy issue and 1.3 release still under development, it's better to provide a hot-fix.

**Comment by fanyangCS** [comment]
ok. please do so.

**Comment by Binyang2014** [comment]
@cdd1993 We provide a hot-fix in 1.2.1 release. Please try to use this version

**Comment by fanyangCS** [comment]
Feel free to reopen this if running into further issues.
