### ISSUE TITLE
All-in-one deployment for v1.x.x

### ISSUE THREAD

**Issue by JosephKang** [microsoft/pai#4952]
**Organization Name**: 
Advantech

**Short summary about the issue/question**:
OpenPAI v1.x.x all-in-one deployment. 

**Brief what process you are following**:
Can we deploy OpenPAI version after v1.x.x in one physical node without virtual machine?

**OpenPAI Environment**: 
- OpenPAI version: v1.x.x

**Comment by fanyangCS** [comment]
yes.

**Comment by JosephKang** [comment]
There is no clear all-in-one deployment step in https://openpai.readthedocs.io/en/latest/manual/cluster-admin/installation-guide.html#installation-from-scratch. May I know more information about it? (E.g. Have the same one node setting in master.csv and worker.csv) 
Thanks

**Comment by fanyangCS** [comment]
Do you mean you would like to deploy OpenPAI on a single box? 

We do not provide support to this case yet.

**Comment by JosephKang** [comment]
Refer to https://github.com/microsoft/pai/issues/4967#issuecomment-708916495
1. Same setting in master.csv and worker.csv.
2. I remove some Dup. node checking and some docker restart mechanism case by case.
3. When k8s cluster is ready, I set both pai-worker=true and pai-master=true in this node.

Just finish collocating devbox, master and worker on one node. The task can submit successfully and still check if any additional issues.
