### ISSUE TITLE
Wrong requirement check

### ISSUE THREAD

**Issue by hchoi405** [microsoft/pai#4957]
**Short summary about the issue/question**: 
A wrong unmet requirement of default runtime.

**OpenPAI Environment**:
- OpenPAI version: v1.2.0
- Cloud provider or hardware configuration: custom hardware
- OS (e.g. from /etc/os-release): Ubuntu 18.04
- Kernel (e.g. `uname -a`): 5.4.0
- Hardware (e.g. core number, memory size, storage size, GPU type etc.): varying
- Others: 

**Anything else we need to know**:
When I execute the `quick-start-kubespray.sh`, it says default runtime is not set but in my opinion, two lines of the error checking are wrong in the file below:

`contrib/kubespray/roles/requirement/worker/tasks/ubuntu-docker.yml`
At line 39, `item` &#8594; `"{{ item }}"`
At line 50, `is`  &#8594; `is not`

Then it succeeds to meet the requirement.
How do you guys think about this?

**Comment by hzy46** [comment]
I notice there is an PR already. I will take a look.
