### ISSUE TITLE
[duplicate hostname in kubernetes-configuration] How to force master node also is a worker node? 

### ISSUE THREAD

**Issue by tanrobotix** [microsoft/pai#4967]
**Organization Name**:

VinAI Research

**Short summary about the issue/question**:

I want the master node also is the worker node

**Brief what process you are following**:

2020-10-14 11:51:57,397 [ERROR] - deployment.clusterObjectModel.cluster_object_model : duplicate hostname [kubernetes-master-xxxx-xxxx, kubernetes-master-yyyy-yyyy] in kubernetes-configuration

Please point me to do this
Thank you

**OpenPAI Environment**: Kubernetes v1.19 OnPremise
- OpenPAI version: v1.2.0
- Cloud provider or hardware configuration: On Premise
- OS (e.g. from /etc/os-release): Ubuntu 18.04 LTS
- Kernel (e.g. `uname -a`): 4.15.0-118-generic
- Hardware (e.g. core number, memory size, storage size, GPU type etc.): Tesla, Geforce

**Anything else we need to know**:
The quick-start-service is check duplicated hostname. Is there anyway for me to force master node is also a worker node

**Comment by fanyangCS** [comment]
related. https://github.com/microsoft/pai/issues/4952

**Comment by tanrobotix** [comment]
@fanyangCS No, my situation isn't relate with #4952, for example we have 3 node, 2 masters and 1 worker. I want these 2-master node also can run job as a worker.

**Comment by fanyangCS** [comment]
@tanrobotix , got it. we do not recommend codeploying master and worker together. the job running on worker could interfere with master.

**Comment by tanrobotix** [comment]
@fanyangCS Yes I understand, because our cluster all have GPU. I don't have any machine just only have CPU for master role. Is there any way to skip that checking. Anyway, I want to force master is also tobe a worker.

**Comment by fanyangCS** [comment]
@hzy46 , could you help?

**Comment by hzy46** [comment]
First, you shouldn't use two master nodes. There must be only one master node. And, currently we don't have support that let a master node to be a worker node. But if you insist, you can try the following:

- in Kuberentes, label `pai-worker=true` for your master node.
- in hived config, configure your master into a vc.

**Comment by tanrobotix** [comment]
Thank you @hzy46, I'm going to do following your guide. I'll update if there is anything new.

**Comment by hzy46** [comment]
You are welcome. And I recommend you to set a new vc for the master node. Also be careful with the resource allocation in hived config: you shouldn't allocate all resource on the master node, otherwise PAI service will be unable to run.

**Comment by fanyangCS** [comment]
closed as no further response.
