### ISSUE TITLE
internal-storage-create blocked

### ISSUE THREAD

**Issue by JosephKang** [microsoft/pai#4984]
**Organization Name**:
Advantech

**Short summary about the issue/question**:
internal-storage-create pod creation is blocked

**Brief what process you are following**:
`
1. Run python paictl.py service start -n alert-manager cluster-configuration device-plugin fluentd frameworkcontroller grafana hivedscheduler internal-storage job-exporter k8s-dashboard log-manager openpai-runtime postgresql prometheus pylon rest-server storage-manager watchdog webportal
(skip node-exporter since it is already started by other k8s module)
2. Blocked in internal-storage-create
2020-10-16 10:21:09,900 [INFO] - deployment.paiLibrary.paiService.service_management_start : Begin to start service: [ internal-storage ]
2020-10-16 10:21:09,900 [INFO] - deployment.paiLibrary.paiService.service_management_start : Begin to execute service internal-storage's start script.
daemonset.apps/internal-storage-create-ds configured
internal-storage-create is not ready yet. Please wait for a moment!
internal-storage-create is not ready yet. Please wait for a moment!
internal-storage-create is not ready yet. Please wait for a moment!
`
3. internal-storage-create pod description event
`
Events:
  Type     Reason     Age                      From             Message
  Warning  Unhealthy  3m42s (x2598 over 133m)  kubelet, ainode  Readiness probe failed: ls: cannot access '/paiInternal/storage/READY': No such file or directory
`

**How to reproduce it**:
Just do python paictl.py service start

**OpenPAI Environment**:
- OpenPAI version:
v1.0.1
- Cloud provider or hardware configuration:
Physical host
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
48 vCPU/4 GPU
- Others:

**Anything else we need to know**:
Master and 1 worker are located in single host.

**Comment by hzy46** [comment]
Could you provide the log of the internal storage pod?

You can use:
```
kubectl logs `kubectl get po | grep internal-storage | awk '{print $1}'`
```

**Comment by JosephKang** [comment]
- At host
```
 kubectl logs `kubectl get po | grep internal-storage | awk '{print $1}'`
```
>Skip storage.ext4 creation.
mount: /dev/loop0 is write-protected, mounting read-only
mount: wrong fs type, bad option, bad superblock on /dev/loop0,
       missing codepage or helper program, or other error
       In some cases useful info is found in syslog - try
       dmesg | tail or so.
mount failed!

- At  internal-storage container
```
dmesg | tail
```
> [1902865.542730] [3218476]   998 3218476   131518    71447     271       4        0           979 bundle
[1902865.542752] [3418725]     0 3418725     1126      196       8       3        0           979 gitlab-logrotat
[1902865.542763] [3426286]   998 3426286   131518    70744     255       4        0           979 bundle
[1902865.542770] [3454327]     0 3454327     1094      175       8       3        0           979 sleep
[1902865.542849] [3541247]   998 3541247     4524      741      14       3        0           979 gitlab-unicorn-
[1902865.542866] [3544555]   998 3544555   161182   101203     334       4        0           979 bundle
[1902865.542880] [3547800]   998 3547800     4524       83      13       3        0           979 gitlab-unicorn-
[1902865.542886] [3547865]     0 3547865     1060       21       5       3        0           979 runsv
[1902865.542890] Memory cgroup out of memory: Kill process 3544555 (bundle) score 1075 or sacrifice child
[1902865.545601] Killed process 3544555 (bundle) total-vm:644728kB, anon-rss:390316kB, file-rss:14496kB

- At host
```
 free -h
```
```
              total        used        free      shared  buff/cache   available
Mem:           187G         22G         56G        2.2G        107G        158G
Swap:            0B          0B          0B
```
In addition, I set ```qos-switch: "true"``` in ~/pai-deploy/cluster-cfg/service-configuration.yaml, but I didn't see any limit configuraiton in ~/pai/src/internal-storage/deploy/*.yaml.template so I think it is ok to set qos-switch to be true.

**Comment by hzy46** [comment]
It seems that `storage.ext4` is broken. In `v1.0.1`, we only save job retry history (e.g. if a job fails and there are several retries) in it. If you don't need them, you can delete the old one and recreate this file by:

```
./paictl.py service delete -n internal-storage
./paictl.py service start -n internal-storage
```

**Comment by JosephKang** [comment]
Another log shows up after starting the deleted internal-storage service, the service pod is still not in READY status
``` kubectl logs `kubectl get po | grep internal-storage | awk '{print $1}'` ```
>Creating storage.ext4 of 10G, please wait...
fallocate: fallocate failed: Operation not supported
allocation failed!

**Comment by hzy46** [comment]
I see there is a `10.233.64.1:/afs/nfsshare/paiInternal`. 

Actually we will create a file under `/mnt/paiInternal/storage.ext4` file on the master node.

Is the path `/mnt` on the master node a remote nfs server?

**Comment by JosephKang** [comment]
@hzy46 
Good catch!  
**/mnt** is used to test remote nfs path and should not be mounted in production.
The internal-storage pod is created successfully after umounting the nfs path.
