### ISSUE TITLE
job is always waiting

### ISSUE THREAD

**Issue by sumeng1024** [microsoft/pai#4985]
**Organization Name**:

**Short summary about the issue/question**: 
I submit a job OpenPAI webportal, but it is always waiting, nothing is output. This is my first job.

**Brief what process you are following**:
 download [hello-world-job.yaml](https://openpai.readthedocs.io/en/latest/manual/cluster-user/examples/hello-world-job.yaml).
Then login to OpenPAI webportal, click Submit Job -> Import Config, select the downloaded hello-world-job.yaml file, and submit the job:

**How to reproduce it**:

**OpenPAI Environment**: 
- OpenPAI version: v1.2.0
- Cloud provider or hardware configuration: hardware
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Kernel (e.g. `uname -a`): 4.15.0-118-generic
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by sumeng1024** [comment]
If I submit the job with 2 GPUs, the job status is always waiting. But if I clone the same job and submit it with 1 GPU, it will succeed. I`m not sure what causes the problem. 
Here is my configuration:
**layout.yaml**
```shell
machine-sku:
  GENERIC-MASTER:
    mem: 1
    gpu:
      type: generic
      count: 1
    cpu:
      vcore: 1
    os: ubuntu16.04
  GENERIC-WORKER:
    mem: 1
    gpu:
      type: generic
      count: 1
    cpu:
      vcore: 1
    os: ubuntu16.04
  AMD-2950X:
    mem: 128
    gpu:
      type: geforce2080Ti
      count: 2
    cpu:
      vcore: 32
    os: ubuntu16.04
  AMD-3970X:
    mem: 128
    gpu:
      type: geforce2080Ti
      count: 2
    cpu:
      vcore: 64
    os: ubuntu16.04
  INTEL-I9-10940X:
    mem: 128
    gpu:
      type: geforce2080Ti
      count: 2
    cpu:
      vcore: 28
    os: ubuntu16.04

machine-list:
    - hostname: node001
      nodename: node001
      hostip: 172.16.10.13
      machine-type: AMD-2950X
      dashboard: "true"
      pai-master: "true"
    - hostname: node002
      nodename: node002
      hostip: 172.16.10.14
      machine-type: INTEL-I9-10940X
      pai-worker: "true"
    - hostname: node003
      nodename: node003
      hostip: 172.16.10.15
      machine-type: AMD-2950X
      pai-worker: "true"
    - hostname: node004
      nodename: node004
      hostip: 172.16.10.16
      machine-type: AMD-3970X
      pai-worker: "true"
```

**services-configuration.yaml**

```shell
hivedscheduler:
  config: |
    physicalCluster:
      skuTypes:
        2080TI:
          gpu: 1
          cpu: 14
          memory: 64315Mi
      cellTypes:

        2080TI-NODE:
          childCellType: 2080TI
          childCellNumber: 2
          isNodeLevel: true
        2080TI-NODE-POOL:
          childCellType: 2080TI-NODE
          childCellNumber: 3
      physicalCells:
      - cellType: 2080TI-NODE-POOL
        cellChildren:
        - cellAddress: gpu-cluster-node002
        - cellAddress: gpu-cluster-node003
        - cellAddress: gpu-cluster-node004
    virtualClusters:
      default:
        virtualCells:
        - cellType: 2080TI-NODE-POOL.2080TI-NODE
          cellNumber: 1
      vc1:
        virtualCells:
        - cellType: 2080TI-NODE-POOL.2080TI-NODE
          cellNumber: 2
```

**Comment by yqwang-ms** [comment]
The celladdress should be the nodename, such as the gpu-cluster-node002 should be renamed to node002.
Pls check our doc to config it, and provide hivedscheduler-hs statefulset log.

@abuccts    to see if other problems with the conf

**Comment by abuccts** [comment]
Hi @sumeng1024, could you reduce the memory for `2080TI` in `skuTypes`, e.g. change to `memory: 60000Mi`, run following commands to restart scheduler:
```sh
python paictl.py service stop -n rest-server hivedscheduler
python paictl.py config push -p /your-config-path -m service
python paictl.py service start -n rest-server hivedscheduler
```
then try again?

If the 2 GPUs job is still keep waiting, pls visit [k8s dashboard](https://openpai.readthedocs.io/en/latest/manual/cluster-admin/basic-management-operations.html#access-kubernetes-dashboard) and provide the abnormal pod's event.

**Comment by sumeng1024** [comment]
> The celladdress should be the nodename, such as the gpu-cluster-node002 should be renamed to node002.
> Pls check our doc to config it, and provide hivedscheduler-hs statefulset log.
> 
> @abuccts to see if other problems with the conf

Sorry， I paste the wrong config. The celladdress is the same as the nodename.

**Comment by sumeng1024** [comment]
> Hi @sumeng1024, could you reduce the memory for `2080TI` in `skuTypes`, e.g. change to `memory: 60000Mi`, run following commands to restart scheduler:
> 
> ```shell
> python paictl.py service stop -n rest-server hivedscheduler
> python paictl.py config push -p /your-config-path -m service
> python paictl.py service start -n rest-server hivedscheduler
> ```
> 
> then try again?
> 
> If the 2 GPUs job is still keep waiting, pls visit [k8s dashboard](https://openpai.readthedocs.io/en/latest/manual/cluster-admin/basic-management-operations.html#access-kubernetes-dashboard) and provide the abnormal pod's event.

I have changed the memory, but it didn`t work.

**Comment by sumeng1024** [comment]
> > Hi @sumeng1024, could you reduce the memory for `2080TI` in `skuTypes`, e.g. change to `memory: 60000Mi`, run following commands to restart scheduler:
> > ```shell
> > python paictl.py service stop -n rest-server hivedscheduler
> > python paictl.py config push -p /your-config-path -m service
> > python paictl.py service start -n rest-server hivedscheduler
> > ```
> > 
> > 
> > then try again?
> > If the 2 GPUs job is still keep waiting, pls visit [k8s dashboard](https://openpai.readthedocs.io/en/latest/manual/cluster-admin/basic-management-operations.html#access-kubernetes-dashboard) and provide the abnormal pod's event.
> 
> I have changed the memory, but it didn`t work. And I want to visit but I don`t know how to set up the https access.

@abuccts Thanks, It works now. It`s really caused by the wrong memory setting. Do you know how to set up the https access in the configuration?

**Comment by abuccts** [comment]
> Do you know how to set up the https access in the configuration?

pls refer to [this section](https://openpai.readthedocs.io/en/latest/manual/cluster-admin/how-to-manage-users-and-groups.html#pylon-prepare-your-certificate-for-https-self-sign-cert-as-an-example) (only [pylon] part is needed) to create a self-sign certificate and update configuration, then restart pylon service by:
```sh
python paictl.py service stop -n pylon
python paictl.py config push -p /your-config-path -m service
python paictl.py service start -n pylon
```

**Comment by sumeng1024** [comment]
> > Do you know how to set up the https access in the configuration?
> 
> pls refer to [this section](https://openpai.readthedocs.io/en/latest/manual/cluster-admin/how-to-manage-users-and-groups.html#pylon-prepare-your-certificate-for-https-self-sign-cert-as-an-example) (only [pylon] part is needed) to create a self-sign certificate and update configuration, then restart pylon service by:
> 
> ```shell
> python paictl.py service stop -n pylon
> python paictl.py config push -p /your-config-path -m service
> python paictl.py service start -n pylon
> ```

The certificate should be generated in the dev box or in the container?

**Comment by sumeng1024** [comment]
What does `pylon address` mean? IP address or Domain name?

**Comment by abuccts** [comment]
dev box; ip address

**Comment by sumeng1024** [comment]
> dev box; ip address

@abuccts I can`t start **pylon** service, please help me check my configuration, thank you.

```shell
openpai@dev-box:~/ssl$ echo $DOMAIN
172.16.10.13
openpai@dev-box:~/ssl$ ls /home/openpai/ssl/
172.16.10.13.crt  172.16.10.13.csr  172.16.10.13.key  172.16.10.13.origin.key
```

pylon
```shell
pylon:
    port: 80
    uri: "http://172.16.10.13:80"
    ssl:
      # self-sign
      crt_name: 172.16.10.13.crt
      crt_path: /home/openpai/ssl/
      key_name: 172.16.10.13.key
      key_path: /home/openpai/ssl/
```

**Comment by abuccts** [comment]
could you try:
```yaml
pylon:
    port: 80
    uri: "http://172.16.10.13:80"
    ssl:
      # self-sign
      crt_name: 172.16.10.13.crt
      crt_path: /home/openpai/ssl/172.16.10.13.crt
      key_name: 172.16.10.13.key
      key_path: /home/openpai/ssl/172.16.10.13.key
```

then run the following again:
```sh
python paictl.py service stop -n pylon
python paictl.py config push -p /your-config-path -m service
python paictl.py service start -n pylon
```

**Comment by sumeng1024** [comment]
> could you try:
> 
> ```yaml
> pylon:
>     port: 80
>     uri: "http://172.16.10.13:80"
>     ssl:
>       # self-sign
>       crt_name: 172.16.10.13.crt
>       crt_path: /home/openpai/ssl/172.16.10.13.crt
>       key_name: 172.16.10.13.key
>       key_path: /home/openpai/ssl/172.16.10.13.key
> ```
> 
> then run the following again:
> 
> ```shell
> python paictl.py service stop -n pylon
> python paictl.py config push -p /your-config-path -m service
> python paictl.py service start -n pylon
> ```

It works. Thank you so much.
