### ISSUE TITLE
internal-storage-create is not ready yet. Please wait for a moment!

### ISSUE THREAD

**Issue by youxingtian** [microsoft/pai#4994]
when I install OpenPAI, I get this error!
![image](https://user-images.githubusercontent.com/49486786/96585355-10f89e00-1312-11eb-9ef1-961f1c9cc73a.png)

**Organization Name**:

**Short summary about the issue/question**:

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:
I use Azure cloud, and the openpai_kube_network_plugin: weave

**Comment by fanyangCS** [comment]
please state the version you use. is it related to this https://github.com/microsoft/pai/issues/4984?

**Comment by youxingtian** [comment]
> please state the version you use. is it related to this #4984?

The version is :
branch_name: pai-1.0.y
docker_image_tag: v1.0.0

**Comment by youxingtian** [comment]
> please state the version you use. is it related to this #4984?

I use Azure cloud, and the openpai_kube_network_plugin: weave

**Comment by youxingtian** [comment]
> please state the version you use. is it related to this #4984?

The problem is whether azure cloud does not assign static IP addresses？

**Comment by hzy46** [comment]
This may be related to #4920 .

I recommend you to deploy our latest version `v1.2.1` to get rid of it.
