### ISSUE TITLE
how to set up LDAP other than Azure Active Directory

### ISSUE THREAD

**Issue by MengS1024** [microsoft/pai#4998]
**Organization Name**:

**Short summary about the issue/question**:
from the [doc](https://openpai.readthedocs.io/en/latest/manual/cluster-admin/how-to-manage-users-and-groups.html) I know how to use Azure Active Directory (AAD) for user authentication instead of the default basic authentication. But now I want to use other LDAP servers(such as FreeIPA) for authentication, how to realize my target.
**Brief what process you are following**:

**OpenPAI Environment**:
- OpenPAI version: v1.2.0
- Cloud provider or hardware configuration: hardware configuration
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Kernel (e.g. `uname -a`):4.15.0-118-generic

**Comment by fanyangCS** [comment]
As of v1.2, OpenPAI does not support LDAP. Contribution welcome.

**Comment by fanyangCS** [comment]
closed and tracked in #5288

**Comment by suiguoxin** [comment]
@MengS1024 Hi, we are considering LDAP support as a feature candidate in future releases. Could you please provide more details about your LDAP server ? To make sure the feature will answer your request. 
- the version / components of FreeIPA you are using
- what kind of protocol should we use to interact with your Authorization Server ? SAML ? OAuth 2 ?
- other information necessary
