### ISSUE TITLE
job tag test issues

### ISSUE THREAD

**Issue by debuggy** [microsoft/pai#5009]
1. Better to add an api for getting tags
When adding tags, user might want to check the tags.

2. When send wrong api body, the api endpoint did not reponse.
![image](https://user-images.githubusercontent.com/8444268/97144662-ceb2df00-179f-11eb-8f52-cae391b6491f.png)
![image](https://user-images.githubusercontent.com/8444268/97144683-da060a80-179f-11eb-8fea-19d0636e87c0.png)

**Comment by suiguoxin** [comment]
For the two issues pointed out above: 
1. Get tags list: deferred. 
2. Fixed in #5025.
