### ISSUE TITLE
Alert email template miss cluster ID

### ISSUE THREAD

**Issue by Binyang2014** [microsoft/pai#5010]
![image](https://user-images.githubusercontent.com/9415966/97148004-6109b180-17a5-11eb-9562-0ddd17c84d14.png)
We don't have cluster Id in the title. It's hard to classify alert when have multi-clusters.

Please put cluster ID in the title

**Comment by Binyang2014** [comment]
Refer #5020

**Comment by suiguoxin** [comment]
Fixed in #5020
