### ISSUE TITLE
No module named 'kubernetes'

### ISSUE THREAD

**Issue by zerozakiihitoshiki** [microsoft/pai#5016]
**Short summary about the issue/question**:

**Brief what process you are following**:
I try to deploy openpai on one node. when I use `python3 openpai-generator.py -m /home/xxx/pai_configurations/master.csv -w /home/xxx/pai_configurations/worker.csv -c /home/xxx/pai_configurations/config.yml -o /home/xxx/pai_configurations/output
`, I meet this problem.
I  try to use `pip3 install kubernetes` to solve this problem, but it dosen't work.

**Error Log**:
```
Traceback (most recent call last):
  File "script/openpai-generator.py", line 14, in <module>
    from kubernetes import client, config
ModuleNotFoundError: No module named 'kubernetes'
```

**OpenPAI Environment**:
- OpenPAI version: 1.2.1
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Kernel (e.g. `uname -a`): 4.4.0-190-generic

**Comment by abuccts** [comment]
What's the output of the followings?
```sh
python3 -V
python3 -m pip -V
pip3 -V
```

**Comment by zerozakiihitoshiki** [comment]
> What's the output of the followings?
> 
> ```shell
> python3 -V
> python3 -m pip -V
> pip3 -V
> ```

```
xxx@openpai-master-01:~$ python3 -V
Python 3.7.3

xxx@openpai-master-01:~$ python3 -m pip -V
pip 19.0.3 from /usr/local/anaconda3/lib/python3.7/site-packages/pip (python 3.7)

xxx@openpai-master-01:~$ pip3 -V
pip 20.2.4 from /usr/local/lib/python3.5/dist-packages/pip (python 3.5)
```

**Comment by abuccts** [comment]
So you have multiple python3 versions, pls use `python3 -m pip install kubernetes` to install and try again.

**Comment by zerozakiihitoshiki** [comment]
> So you have multiple python3 versions, pls use `python3 -m pip install kubernetes` to install and try again.

Thank you, it works.
