### ISSUE TITLE
alert handler stop-job notice not clear to end user

### ISSUE THREAD

**Issue by Binyang2014** [microsoft/pai#5021]
When enable `stop-job` and `email-user`. User only get email about this alert such as:
![image](https://user-images.githubusercontent.com/9415966/97398817-d224a280-1926-11eb-9b8e-197f557a5e70.png)

But doesn't get notice that the job will be stopped by alert manager.
This will confuse `end user`. When he found the job is stopped.

**Comment by suiguoxin** [comment]
Fixed in #5064
