### ISSUE TITLE
CoreDNS pod will affect resource calculation for hived scheduler

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#5056]
1. Kubernetes deploys the coreDNS pods in nodes within the cluster. It is not guaranteed that Kubernetes will/won't deploy the coreDNS pod in a certain node. Some PAI worker nodes may have it, while others may not.

2. The coreDNS pod requests 1 CPU and 500MiB memory. It will affect resoure calculation for hived scheduler.

     e.g. One cluster has one master node and two worker nodes. Every worker node has 10 allocatable CPUs. In the beginning, the coreDNS pod is deployed in the master node. So the admin configures 10 CPUs in every worker node in hived scheduler. But, for some reasons, one coreDNS pod is deployed in one worker node. Thus the worker node's allocatable CPU number becomes 9. It may cause infinite job retries because hived may always schedule job to this worker node.

    ![image](https://user-images.githubusercontent.com/7499023/98205372-fb6eaf80-1f72-11eb-96e8-6ca538593ba0.png)

**Comment by Binyang2014** [comment]
Remove `coredns` may cause pod which not using hostNetwork failed to access internet. May need to move it to master node.
I'm not sure about the AKS env. If we can control the coredns in AKS

**Comment by hzy46** [comment]
I set the coredns requests to zero, and tested the following items:

  - if the pod can access internet
  - if `Service` works in cluster

The tests were OK.

@Binyang2014 Please help review #5071 .

**Comment by hzy46** [comment]
For those who have already installed k8s, I suggest to use `kubectl edit` to set coreDNS requests to zero. Details:

1. `kubectl edit deployment/coredns -n kube-system`

2. set `spec.template.spec.containers[0].resources.cpu` to `0m`, and  `spec.template.spec.containers[0].resources.memory` to `0Mi`

![image](https://user-images.githubusercontent.com/7499023/98630233-9c83ae80-2355-11eb-9af0-b6315b35108a.png)


3. save the config, and wait a few minutes.
