### ISSUE TITLE
Failed to fetch job logs

### ISSUE THREAD

**Issue by TobeyQin** [microsoft/pai#5094]
1. Submit any job template from Marketplace.

2. Click 'stdout' or 'stderr' after job started.

3. Show "Failed to fetch" message.

![image](https://user-images.githubusercontent.com/32830091/99494072-5361d900-29ab-11eb-847b-160d8bbbae93.png)

![image](https://user-images.githubusercontent.com/32830091/99494012-3decaf00-29ab-11eb-910f-5ab308a8a7d1.png)

**Comment by Binyang2014** [comment]
@TobeyQin Please try again? Maybe cause by deploy issue

**Comment by fanyangCS** [comment]
@Binyang2014 , could you check why the deployment issue happens and whether we could remove it in the future?

**Comment by suiguoxin** [comment]
We were upgrading int bed this afternoon until 16:00, some services may be stopped when you test this feature. Please try out the latest version. @TobeyQin @fanyangCS
