### ISSUE TITLE
Incorrect node label in Services Page and worker node is missing in Hardware Utilization Page

### ISSUE THREAD

**Issue by WalkerLYU** [microsoft/pai#5099]
**Organization Name**:

**Short summary about the issue/question**:
After following the [installation guide](https://openpai.readthedocs.io/en/latest/manual/cluster-admin/installation-guide.html), the webportal is successfully launched. However, the master node is labeled with pai-worker, which is incorrect as what I expect, in the Services Page. Besides, the worker node is missing in Hardware Utilization Page. 
![service](https://github.com/WalkerLYU/issue/blob/main/pai-service.png)
![hardware](https://github.com/WalkerLYU/issue/blob/main/pai-hardware.png)
**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version: pai-1.3.y
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Kernel (e.g. `uname -a`): 4.15.0-45-generic
- Hardware (e.g. core number, memory size, storage size, GPU type etc.): 8 GPUs, 64 CPUs, mem: 527758948Ki
- Others:

**Anything else we need to know**:
layout.yaml:
```bash
# kubernetes api server and dashboard
kubernetes:
  api-servers-url: https://10.3.2.90:6443
  dashboard-url: https://10.3.2.90:9090

# TODO please modify it according to your own hardware
machine-sku:
  GENERIC-MASTER:
    mem: 49000Mi
    cpu:
      vcore: 8
    os: ubuntu16.04

  GENERIC-WORKER:
    mem: 250000Mi
    gpu:
      type: generic
      count: 8
    cpu:
      vcore: 64
    os: ubuntu16.04

machine-list:
    - hostname: openpai-master-01
      nodename: openpai-master-01
      hostip: 10.3.2.90
      machine-type: GENERIC-MASTER
      dashboard: "true"
      pai-master: "true"
    - hostname: openpai-001
      nodename: openpai-001
      hostip: 10.3.1.1
      machine-type: GENERIC-WORKER
      pai-worker: "true"
```
hivedscheduler in services-configuration.yaml
```bash
#If you want to customize the scheduling config, such add more virtual clusters or more gpu types, check:
#https://github.com/microsoft/pai/blob/master/docs/hivedscheduler/devops.md
hivedscheduler:
  config: |
    physicalCluster:
      skuTypes:
        DT:
          gpu: 1
          cpu: 7
          memory: 64215Mi
      cellTypes:
        DT-NODE:
          childCellType: DT
          childCellNumber: 8
          isNodeLevel: true
        DT-NODE-POOL:
          childCellType: DT-NODE
          childCellNumber: 1
      physicalCells:
      - cellType: DT-NODE-POOL
        cellChildren:
        - cellAddress: openpai-001
    virtualClusters:
      default:
        virtualCells:
        - cellType: DT-NODE-POOL.DT-NODE
          cellNumber: 1
```

**Comment by abuccts** [comment]
What's the output of `kubectl get node --show-labels` in your dev box?

**Comment by WalkerLYU** [comment]
```bash
NAME                STATUS   ROLES    AGE   VERSION    LABELS
openpai-001         Ready    <none>   30h   v1.17.2    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=openpai-001,kubernetes.io/os=linux,pai-worker=true
openpai-master-01   Ready    master   47h   v1.15.11   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=openpai-master-01,kubernetes.io/os=linux,node-role.kubernetes.io/master=,pai-master=true,pai-worker=true
```

**Comment by abuccts** [comment]
Seems you deployed k8s several times and used different versions? We didn't test on v1.17.2.

You can try the following to restart OpenPAI services to fix the label issue:
```sh
python paictl.py service stop
kubectl label node openpai-master-01 pai-worker-
python paictl.py service start
```

**Comment by WalkerLYU** [comment]
Thank you, abuccts. I have indeed deployed K8s several times on openpai-001. I will clean up the k8s on openpai-001 and deploy pai again. The result will be announced in next week.

**Comment by WalkerLYU** [comment]
After redeploying the pai with k8s on v1.15.11, the label of mater become normal. During the redeployment, I find that the calico pods are not ready since the ufw service is active on openpai-001. The missing work node in Hardware Utilization Page is found by closing the ufw service.
