### ISSUE TITLE
Cannot specify storage mount path

### ISSUE THREAD

**Issue by siaimes** [microsoft/pai#5102]
**Organization Name**:

**Short summary about the issue/question**:
Cannot specify storage mount path
**Brief what process you are following**:
Configuration files include something like this cannot be used
![image](https://user-images.githubusercontent.com/34199488/99665405-9489e400-2aa4-11eb-9eeb-1c46a7c556aa.png)
Openpai prompt message
![image](https://user-images.githubusercontent.com/34199488/99666012-5c36d580-2aa5-11eb-897a-02768ae27012.png)

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version: v1.3.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by debuggy** [comment]
Refine prompt error message

**Comment by hzy46** [comment]
You do not have permission to the storage. Please refer to https://openpai.readthedocs.io/en/latest/manual/cluster-admin/how-to-set-up-storage.html#assign-storage-to-pai-groups .

**Comment by siaimes** [comment]
@hzy46 Thank you for your reply, but maybe I didn't express my meaning clearly, you didn't understand. Suppose, I have a storage called `/mnt/k80`, this name is generated through `pv/pvc` and cannot be modified. Now I want to mount it in my container with the path `/data` instead of `/mnt/k80`. From this document: [how-to-manage-data](https://openpai.readthedocs.io/en/latest/manual/cluster-user/how-to-manage-data.html#use-job-configuration-file), I specified extras.sotrages.name=/mnt/k80, extras.storages.mountPath: /data in the job configuration file. But when import the file, openpai will prompt: `Some storage configs is invalid, please check`.

**Comment by siaimes** [comment]
![image](https://user-images.githubusercontent.com/34199488/102593637-14f93e80-4150-11eb-9743-dd6174a1745e.png)

I wonder if it is possible to make this text box editable to allow users to enter a custom storage mount path.

**Comment by hzy46** [comment]
> @hzy46 Thank you for your reply, but maybe I didn't express my meaning clearly, you didn't understand. Suppose, I have a storage called `/mnt/k80`, this name is generated through `pv/pvc` and cannot be modified. Now I want to mount it in my container with the path `/data` instead of `/mnt/k80`. From this document: [how-to-manage-data](https://openpai.readthedocs.io/en/latest/manual/cluster-user/how-to-manage-data.html#use-job-configuration-file), I specified extras.sotrages.name=/mnt/k80, extras.storages.mountPath: /data in the job configuration file. But when import the file, openpai will prompt: `Some storage configs is invalid, please check`.

cc @Binyang2014 Please have a look. It may be an issue with storage plugin.

**Comment by Binyang2014** [comment]
@siaimes Can you provide the whole job config yaml? You can remove the confidential info

**Comment by siaimes** [comment]
> @siaimes Can you provide the whole job config yaml? You can remove the confidential info

```
extras:
  storages:
    - name: k80
      mountPath: /data
```

Hello, for me, this configuration file works. In this way, I can mount the storage named `/mnt/k80` on the profile page as `/data`. I checked all the web interfaces carefully, but I couldn't find the relevant setting items.

**Comment by Binyang2014** [comment]
This related to this issue: https://github.com/microsoft/pai/issues/4858, it's a UI change

**Comment by siaimes** [comment]
> This related to this issue: #4858, it's a UI change

Thank you loyally for your reply, I know what the situation is, and look forward to the next update.
