### ISSUE TITLE
Keep the public key used by the user last time, and automatically fill in the form when the SSH button is enabled next time

### ISSUE THREAD

**Issue by siaimes** [microsoft/pai#5107]
**What would you like to be added**:
Keep the public key used by the user last time, and automatically fill in the form when the SSH button is enabled next time.
Expect to provide a function similar to github adding ssh key. Then when the user enables the ssh button, the input box is no longer required to enter the public key. At this point, openpai directly registers the public key reserved for the user in the system to the container. Of course, the existing functions can be retained, that is, the user can generate a key pair when the SSH function is enabled for the first time and prompt the user to keep the private key for the next use.

ref. [adding-a-new-ssh-key-to-your-github-account](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account)

**Why is this needed**:
A key is generated every time a task is submitted, which brings a great management burden to the user. In fact, a user only needs to manage one key pair, and then use it anywhere, such as [github](github.com), [GCP](https://cloud.google.com) etc.

**Without this feature, how does the current module work**:
A key is generated every time a task is submitted or the user must open the public key file every time and copy it to openpai.

**Components that may involve changes**:

**Comment by mydmdm** [comment]
Good suggestion. Actually, keys management has been discussed for times. I make a summary here. 

- User could manage (list/add/remove) his/her own public keys in user profile page (similar to the bounded clusters)
- All registered public keys will be enabled in job container automatically (unless user explicitly disable it)
- (optional) User could add temporary (one-time) public key in job-submission 

we could consider this feature in the following releases.

**Comment by siaimes** [comment]
> Good suggestion. Actually, keys management has been discussed for times. I make a summary here.
> 
> * User could manage (list/add/remove) his/her own public keys in user profile page (similar to the bounded clusters)
> * All registered public keys will be enabled in job container automatically (unless user explicitly disable it)
> * (optional) User could add temporary (one-time) public key in job-submission
> 
> we could consider this feature in the following releases.

I am grateful that you can reply to my issue and adopt my feature request.

**Comment by siaimes** [comment]
[resolved ](https://github.com/microsoft/pai/pull/5223)
