### ISSUE TITLE
Web portal still show inhibited alert

### ISSUE THREAD

**Issue by Binyang2014** [microsoft/pai#5108]
Currently web-portal use `https://master-name/alert-manager/api/v1/alerts?silenced=false` to get alerts. It will show inhibited alerts.
Need to change it to `https://int.openpai.org/alert-manager/api/v1/alerts?silenced=false&inhibited=false`
![image](https://user-images.githubusercontent.com/9415966/99897665-67bd1300-2cd6-11eb-9439-92996741313a.png)

**Comment by suiguoxin** [comment]
Fixed in #5115
