### ISSUE TITLE
Can we mount 2 NFS folder in the container

### ISSUE THREAD

**Issue by MengS1024** [microsoft/pai#5130]
**Short summary about the issue/question**: 
I want to mount 2 different NFS folders in the container, is it supported?

**OpenPAI Environment**:
- OpenPAI version: v1.2.0

**Comment by hzy46** [comment]
It is supported. Please refer to https://openpai.readthedocs.io/en/latest/manual/cluster-admin/how-to-set-up-storage.html to set up multiple nfs storage.

**Comment by MengS1024** [comment]
@hzy46 
I have created 2 different PVs, But I can only see 1 storage on the Job submission page.
![微信截图_1607330675150](https://user-images.githubusercontent.com/40521156/101329100-e5267d00-38ab-11eb-81a9-b598b53e2cd3.png)

**Comment by hzy46** [comment]
You should create 2 PVCs. And assign them to your group.

See: https://openpai.readthedocs.io/en/latest/manual/cluster-admin/how-to-set-up-storage.html#assign-storage-to-pai-groups

**Comment by MengS1024** [comment]
@hzy46 
Great, It works. 
Thanks!
