### ISSUE TITLE
Log manager: Parent directory has insecure permissions

### ISSUE THREAD

**Issue by tanrobotix** [microsoft/pai#5136]
**Short summary about the issue/question**:
Log manager DS raise an issue
`error: skipping "/usr/local/pai/logs/admin/xxxxxxxxxxxxxxxxx/taskrole/xxxxxxxxxxxxxxxxx/user.pai.all" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.`

**Brief what process you are following**:

`ls -la /var/log/pai/admin/xxxxxxxxxxxxxxxx/taskrole/`
`drwxrwxrwx 2 root root 4096 Nov 28 00:22 xxxxxxxxxxxxxxxxx/`

The permission of directory is not right!

**OpenPAI Environment**:
- OpenPAI version: 1.3.0
- Cloud provider or hardware configuration: Onpremise
- OS (e.g. from /etc/os-release): Ubuntu 18.04
- Kernel (e.g. `uname -a`): 5.3.0-42-generic
- Hardware (e.g. core number, memory size, storage size, GPU type etc.): DGX1 - Tesla V100

I think we should take another look at log manager ds provision the log dir

**Comment by tanrobotix** [comment]
@hzy46 Do you have any idea?

**Comment by hzy46** [comment]
cc @Binyang2014

**Comment by Binyang2014** [comment]
@tanrobotix Please check the folder `/usr/local/pai/logs/admin/xxxxxxxxxxxxxxxxx/taskrole/xxxxxxxxxxxxxxxxx/` is own by user `root` and group `root`

**Comment by tanrobotix** [comment]
@Binyang2014 PAI auto create log folder with with that incorrect mod. It is a bug?

**Comment by Binyang2014** [comment]
@tanrobotix This maybe caused by this line
https://github.com/microsoft/openpai-runtime/blob/75e4559758a809b064c7bdb0a506da278071136b/src/init#L94,

Since we removed logrotate in 1.4.0 release. This error will be fixed in next release

**Comment by Binyang2014** [comment]
Close as 1.4.0 already released.
