### ISSUE TITLE
No module named 'jinja2' error when run pai service

### ISSUE THREAD

**Issue by TobeyQin** [microsoft/pai#5147]
## Environments
dev-box: `pai master branch`

deploy config file: 
```
   branch_name: pai-1.3.y
   docker_image_tag: v1.3.0
```

## Issue
Meet error when run `quick-start-service.sh`: 

![image](https://user-images.githubusercontent.com/32830091/100958623-a7e28800-3557-11eb-881d-cc31d2a67b21.png)

## Root cause
PAI version mismatch. local dev-box uses `master branch`, while docker images in config file is `v1.3.0`. 
So the `branch_name` in config file is useless??? 

## Hot fix
Switch local pai version to 1.3.0, to match the version indicated in config file.

**Comment by suiguoxin** [comment]
This issue is resolved in v1.5. `pai_branch_name` is removed from config files and only local pai version matters.
