### ISSUE TITLE
Deploy: paictl add skip services options

### ISSUE THREAD

**Issue by Binyang2014** [microsoft/pai#5149]
Currently, when running paictl, we can not skip to deploy some services.
But some services are critical and can not be stopped, such as `storage-manager` and `dshuttle`. Seems we should try to skip this type of services.

**Comment by suiguoxin** [comment]
Proposals:

#### Add an argument parser:
parser.add_argument("-n", "--service-list", default=None, help="Service list to manage")
**- parser.add_argument("-k", "--skip-service-list", default=None, help="Service list to skip")**

#### constraints:
- return error if the service name is included both args
