### ISSUE TITLE
tensorboard command issue

### ISSUE THREAD

**Issue by lbin** [microsoft/pai#5157]
Is here right https://github.com/microsoft/pai/blob/pai-1.4.y/contrib/submit-job-v2/src/App/TensorBoard.tsx#L408 ?

missing a & at the end of the line

After I upgraded to 1.4.0, I could not submit a job with tensorboard opened, but I login with ssh to the job containter and kill the tensorboard with pid num, everything is ok

**Comment by ReyRen** [comment]
> After I upgraded to 1.4.0, I could not submit a job with tensorboard opened, but I login with ssh to the job containter and kill the tensorboard with pid num, everything is ok

My issue is : 
container inner logs(`kubectl get logs podID`) stuck in "TensorBoard 1.14.0 at http://node4:10236/ (Press CTRL+C to quit)", and nothing in web stdout/stderr. The tensorboard view button is appeared, but the "/mnt/tensorboard" dir is not exist in container. BTW, I specified "--log-dir" with tensorboard installed

**Comment by ReyRen** [comment]
logs in container (following https://openpai.readthedocs.io/en/latest/manual/cluster-user/how-to-debug-jobs.html#how-to-use-tensorboard-plugin)
```
[Fri Dec 11 07:16:58 UTC 2020] [openpai-runtime] [INFO] Starting to exec precommands
[Fri Dec 11 07:16:58 UTC 2020] [openpai-runtime] [package_cache] Skip installation of group ssh.
[Fri Dec 11 07:16:58 UTC 2020] [openpai-runtime] [INFO] start ssh service
[Fri Dec 11 07:16:58 UTC 2020] [openpai-runtime] * Restarting OpenBSD Secure Shell server sshd
[Fri Dec 11 07:16:58 UTC 2020] [openpai-runtime] ...done.
TensorBoard 1.15.0 at http://node4:12111/ (Press CTRL+C to quit)

```
I thought the tensorboard plugin should execute `tensorboard` in the background, because it's a block process. Did I miss configure something? Thanks.

**Comment by lbin** [comment]
@debuggy Is this not a bug?

**Comment by lbin** [comment]
@ReyRen Is your issue still exist with 1.4.0/1.4.1?

**Comment by ReyRen** [comment]
@lbin 1.4.0 Yes, the bug still there!! Did you upgrade to 1.4.1 successfully? I got 
```

Error from server (NotFound): configmaps "pai-version" not found
2020-12-28 10:58:37,068 [WARNING] - deployment.utility.pai_version : Can't fetch cluster version!
2020-12-28 10:58:37,069 [INFO] - deployment.utility.pai_version : Cluster version: , paictl version: v1.4.1
2020-12-28 10:58:37,069 [WARNING] - deployment.utility.pai_version : !!! Paictl version is different from the cluster version:  != v1.4.1
2020-12-28 10:58:37,106 [INFO] - deployment.paiLibrary.common.kubernetes_handler : configmap named pai-configuration is updated.

```

**Comment by lbin** [comment]
I didnot upgrade to 1.4.1, maybe everyone have holiday on chrismas and new year~  @ReyRen

**Comment by lbin** [comment]
Issue still here, @debuggy @fanyangCS @scarlett2018

**Comment by Binyang2014** [comment]
Close this issue. Fixed by https://github.com/microsoft/openpai-runtime/pull/41
