### ISSUE TITLE
Administrators can access the Kubernetes dashboard without entering a token

### ISSUE THREAD

**Issue by siaimes** [microsoft/pai#5203]
**What would you like to be added**:
Administrators can access the Kubernetes dashboard without entering a token
**Why is this needed**:
The Kubernetes dashboard is a powerful tool for diagnosing system failures, but most of the time you need to enter a token to open the dashboard. This situation is inconsistent with user habits, because the administrator has already logged in to openpai, and there is no reason that a subsystem in openpai needs to log in again.
**Without this feature, how does the current module work**:
Opening the Kubernetes dashboard often requires entering a token.
**Components that may involve changes**:

**Comment by siaimes** [comment]
> However, it needs special authentication for security issues.

I did a test on pai version v1.4.1, the results show that all links that directly access the dashboard address (i.e. https://IP/cluster-view/k8s.html) without the administrator token will be redirected to the login page.  

I want to know what kind of security issue you are talking about? So maybe we can solve this problem through discussion.

**Comment by fanyangCS** [comment]
closed and tracked in #5216
