### ISSUE TITLE
paictl will check version alignment when push config

### ISSUE THREAD

**Issue by debuggy** [microsoft/pai#5208]
What is the function of this behavior? If we want to upgrade the cluster, the version will be always different with current cluster version. So this check might be meaningless.

reproduce step:
1. current cluster version is 1.5.0
2. change the version number in /version/PAI.VERSION to 1.4.1
3. run command `./paictl.py push -p /cluster-configuration -m service`
4. the error log is belowed:

![image](https://user-images.githubusercontent.com/8444268/103204789-0e7a7c00-4933-11eb-81f4-3231414d0f95.png)

**Comment by ReyRen** [comment]
```
Error from server (NotFound): configmaps "pai-version" not found
```

**Comment by suiguoxin** [comment]
@debuggy @ReyRen Yes these logs are confusing. Please ignore them for instance & we'll refine the logging soon.

**Comment by suiguoxin** [comment]
Proposals:
- Remind users to ignore the warning message when upgrade / downgrade 
    - `pai-version` check
    - `cluster-id` check
 - do not print error log, warning only
