### ISSUE TITLE
export csv not work

### ISSUE THREAD

**Issue by debuggy** [microsoft/pai#5225]
## Bug Description
Clicking export csv button will cause error

## Reproduce Steps
1. go to any job detail page
2. click export csv button, there is no response. the console will print an error

## Screenshots
![image](https://user-images.githubusercontent.com/8444268/103738708-6f8b0980-502f-11eb-8ec7-ef34cfe6cc48.png)

**Comment by suiguoxin** [comment]
Will this be fixed by #5222  @yiyione ?
