### ISSUE TITLE
Can "View Full Log" display the log in a new tab?

### ISSUE THREAD

**Issue by ultmaster** [microsoft/pai#5243]
![image](https://user-images.githubusercontent.com/8463288/104271584-3ee71c00-54d6-11eb-8c7d-4b6dfad244dc.png)

It's inconvenient to have "view full log" directly download the log, especially when the downloaded log doesn't have file extensions for OS like Windows.

**Comment by Binyang2014** [comment]
It's by design for download behavior. If you want to set default application to view log, we could add file extensions for the log file.

**Comment by ultmaster** [comment]
@Binyang2014 Thanks for reply. I think that's true but again it's quite inconvenient. My download looks like:

![image](https://user-images.githubusercontent.com/8463288/104274987-f67f2c80-54dc-11eb-9350-c1a690024bc5.png)

When I click to open it, it always asks me to choose application:

![image](https://user-images.githubusercontent.com/8463288/104275013-039c1b80-54dd-11eb-88ee-b2c485f221d7.png)

I remember the design used to be opened in browser in previous versions. May I ask why that design has been abandoned?

**Comment by Binyang2014** [comment]
The user log maybe quiet large. Render large file in browser may cause browser using much CPU/Mem and cause other pages slow down. Using download method will avoid this problem.
We can change download file name to `user-stdout.log` and `user-stderr.log`. Then you can choose vs code to open file with `.log` extension.

**Comment by ultmaster** [comment]
Sounds reasonable to me. Thanks!
