### ISSUE TITLE
deployment failed due to network issues : no access to gcr.azk8s.cn

### ISSUE THREAD

**Issue by lirq-q** [microsoft/pai#5246]
**OpenPAI Environment**:
- OpenPAI version:1.4.1
- OS (e.g. from /etc/os-release):ubuntu 16.04.6
- Kernel (e.g. `uname -a`):4.15.0-129-generic
- Hardware :cpu:64 core ,memory   128G .storage: 480G. GPU type: nvidia  1080TI
I run the following script is  OK
/bin/bash requirement.sh -m /master.csv -w /work.csv -c /config 

> TASK [display unmet requirements] ***********************************************************************
skipping: [tjgd-163]
skipping: [tjgd-164]
skipping: [tjgd-162]
skipping: [localhost]

PLAY RECAP **********************************************************************************************
localhost                  : ok=9    changed=0    unreachable=0    failed=0   
tjgd-162                   : ok=16   changed=0    unreachable=0    failed=0   
tjgd-163                   : ok=22   changed=0    unreachable=0    failed=0   
tjgd-164                   : ok=22   changed=0    unreachable=0    failed=0   

Pass: Cluster meets the requirements
root@tjgd-161:/home/user/pai/contrib/kubespray# 

i run  </bin/bash quick-start-kubespray.sh -m /master.csv -w /work.csv -c /config >   appear the following error 

> TASK [download : download_container | Download image if required] ***************************************
Tuesday 12 January 2021  17:37:27 +0800 (0:00:00.232)       0:03:18.164 ******* 
FAILED - RETRYING: download_container | Download image if required (4 retries left).
FAILED - RETRYING: download_container | Download image if required (4 retries left).
FAILED - RETRYING: download_container | Download image if required (4 retries left).
FAILED - RETRYING: download_container | Download image if required (3 retries left).
FAILED - RETRYING: download_container | Download image if required (3 retries left).
FAILED - RETRYING: download_container | Download image if required (3 retries left).
FAILED - RETRYING: download_container | Download image if required (2 retries left).
FAILED - RETRYING: download_container | Download image if required (2 retries left).
FAILED - RETRYING: download_container | Download image if required (1 retries left).
FAILED - RETRYING: download_container | Download image if required (2 retries left).
FAILED - RETRYING: download_container | Download image if required (1 retries left).
fatal: [tjgd-162 -> 172.31.164.162]: FAILED! => {"attempts": 4, "changed": true, "cmd": ["/usr/bin/docker", "pull", "gcr.azk8s.cn/google-containers/kube-apiserver:v1.15.11"], "delta": "0:00:00.486282", "end": "2021-01-12 17:37:43.068457", "msg": "non-zero return code", "rc": 1, "start": "2021-01-12 17:37:42.582175", "stderr": "Error response from daemon: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: \"<html>\\r\\n<head><title>403 Forbidden</title></head>\\r\\n<body bgcolor=\\\"white\\\">\\r\\n<center><h1>403 Forbidden</h1></center>\\r\\n<hr><center>nginx/1.14.0 (Ubuntu)</center>\\r\\n</body>\\r\\n</html>\\r\\n\"", "stderr_lines": ["Error response from daemon: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: \"<html>\\r\\n<head><title>403 Forbidden</title></head>\\r\\n<body bgcolor=\\\"white\\\">\\r\\n<center><h1>403 Forbidden</h1></center>\\r\\n<hr><center>nginx/1.14.0 (Ubuntu)</center>\\r\\n</body>\\r\\n</html>\\r\\n\""], "stdout": "", "stdout_lines": []}
fatal: [tjgd-163 -> 172.31.164.162]: FAILED! => {"attempts": 4, "changed": true, "cmd": ["/usr/bin/docker", "pull", "gcr.azk8s.cn/google-containers/kube-apiserver:v1.15.11"], "delta": "0:00:00.490218", "end": "2021-01-12 17:37:47.148555", "msg": "non-zero return code", "rc": 1, "start": "2021-01-12 17:37:46.658337", "stderr": "Error response from daemon: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: \"<html>\\r\\n<head><title>403 Forbidden</title></head>\\r\\n<body bgcolor=\\\"white\\\">\\r\\n<center><h1>403 Forbidden</h1></center>\\r\\n<hr><center>nginx/1.14.0 (Ubuntu)</center>\\r\\n</body>\\r\\n</html>\\r\\n\"", "stderr_lines": ["Error response from daemon: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: \"<html>\\r\\n<head><title>403 Forbidden</title></head>\\r\\n<body bgcolor=\\\"white\\\">\\r\\n<center><h1>403 Forbidden</h1></center>\\r\\n<hr><center>nginx/1.14.0 (Ubuntu)</center>\\r\\n</body>\\r\\n</html>\\r\\n\""], "stdout": "", "stdout_lines": []}
FAILED - RETRYING: download_container | Download image if required (1 retries left).
fatal: [tjgd-164 -> 172.31.164.162]: FAILED! => {"attempts": 4, "changed": true, "cmd": ["/usr/bin/docker", "pull", "gcr.azk8s.cn/google-containers/kube-apiserver:v1.15.11"], "delta": "0:00:00.494459", "end": "2021-01-12 17:37:55.116742", "msg": "non-zero return code", "rc": 1, "start": "2021-01-12 17:37:54.622283", "stderr": "Error response from daemon: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: \"<html>\\r\\n<head><title>403 Forbidden</title></head>\\r\\n<body bgcolor=\\\"white\\\">\\r\\n<center><h1>403 Forbidden</h1></center>\\r\\n<hr><center>nginx/1.14.0 (Ubuntu)</center>\\r\\n</body>\\r\\n</html>\\r\\n\"", "stderr_lines": ["Error response from daemon: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: \"<html>\\r\\n<head><title>403 Forbidden</title></head>\\r\\n<body bgcolor=\\\"white\\\">\\r\\n<center><h1>403 Forbidden</h1></center>\\r\\n<hr><center>nginx/1.14.0 (Ubuntu)</center>\\r\\n</body>\\r\\n</html>\\r\\n\""], "stdout": "", "stdout_lines": []}

NO MORE HOSTS LEFT **************************************************************************************
	to retry, use: --limit @/root/pai-deploy/kubespray/cluster.retry

PLAY RECAP **********************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
tjgd-162                   : ok=178  changed=6    unreachable=0    failed=1   
tjgd-163                   : ok=125  changed=4    unreachable=0    failed=1   
tjgd-164                   : ok=125  changed=4    unreachable=0    failed=1

**Comment by debuggy** [comment]
Hi, it is recommended to follow [this new installation guide](https://github.com/microsoft/pai/blob/master/docs/manual/cluster-admin/installation-guide.md) to deploy pai cluster. You could notice that the master.csv and worker.csv files are deprecated.

**Comment by lirq-q** [comment]
i  use  chinese user's  example , as follows
user: user
password: 123.com
branch_name: pai-1.4.y
docker_image_tag: v1.4.1

gcr_image_repo: "gcr.azk8s.cn"
kube_image_repo: "gcr.azk8s.cn/google-containers"
kubeadm_download_url: "https://shaiictestblob01.blob.core.chinacloudapi.cn/share-all/kubeadm"
hyperkube_download_url: "https://shaiictestblob01.blob.core.chinacloudapi.cn/share-all/hyperkube"

openpai_kubespray_extra_var:
  pod_infra_image_repo: "gcr.azk8s.cn/google_containers/pause-{{ image_arch }}"
  dnsautoscaler_image_repo: "gcr.azk8s.cn/google_containers/cluster-proportional-autoscaler-{{ image_arch }}"
  tiller_image_repo: "gcr.azk8s.cn/kubernetes-helm/tiller"
  registry_proxy_image_repo: "gcr.azk8s.cn/google_containers/kube-registry-proxy"
  metrics_server_image_repo: "gcr.azk8s.cn/google_containers/metrics-server-amd64"
  addon_resizer_image_repo: "gcr.azk8s.cn/google_containers/addon-resizer"
  dashboard_image_repo: "gcr.azk8s.cn/google_containers/kubernetes-dashboard-{{ image_arch }}"

**Comment by hzy46** [comment]
Seems `gcr.azk8s.cn` doesn't work in your network. Please find another alternative docker mirror and replace `gcr.azk8s.cn` here.

**Comment by lirq-q** [comment]
now the file  is as  follows:
user: user
password: 123.com
branch_name: pai-1.4.y
docker_image_tag: v1.4.1

gcr_image_repo: "gcr.io"
kube_image_repo: "gcr.io/google-containers"
quay_image_repo: "quay.io"
docker_image_repo: "docker.io"
kubeadm_download_url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubeadm_version }}/bin/linux/{{ image_arch }}/kubeadm"
hyperkube_download_url: "https://storage.googleapis.com/kubernetes-release/release/{{ kube_version }}/bin/linux/{{ image_arch }}/hyperkube"

The following error has occurred,

> TASK [download : download_container | Download image if required] ***************************************
Wednesday 13 January 2021  10:46:25 +0800 (0:00:00.268)       0:02:18.083 ***** 
FAILED - RETRYING: download_container | Download image if required (4 retries left).
FAILED - RETRYING: download_container | Download image if required (4 retries left).
FAILED - RETRYING: download_container | Download image if required (4 retries left).
FAILED - RETRYING: download_container | Download image if required (3 retries left).
FAILED - RETRYING: download_container | Download image if required (3 retries left).
FAILED - RETRYING: download_container | Download image if required (3 retries left).
FAILED - RETRYING: download_container | Download image if required (2 retries left).
FAILED - RETRYING: download_container | Download image if required (2 retries left).
FAILED - RETRYING: download_container | Download image if required (2 retries left).
FAILED - RETRYING: download_container | Download image if required (1 retries left).
FAILED - RETRYING: download_container | Download image if required (1 retries left).
FAILED - RETRYING: download_container | Download image if required (1 retries left).
fatal: [tjgd-164 -> 172.31.164.162]: FAILED! => {"attempts": 4, "changed": true, "cmd": ["/usr/bin/docker", "pull", "gcr.io/google-containers/kube-scheduler:v1.15.11"], "delta": "0:00:15.087823", "end": "2021-01-13 10:47:53.811252", "msg": "non-zero return code", "rc": 1, "start": "2021-01-13 10:47:38.723429", "stderr": "Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)", "stderr_lines": ["Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"], "stdout": "", "stdout_lines": []}
fatal: [tjgd-162 -> 172.31.164.162]: FAILED! => {"attempts": 4, "changed": true, "cmd": ["/usr/bin/docker", "pull", "gcr.io/google-containers/kube-scheduler:v1.15.11"], "delta": "0:00:15.082269", "end": "2021-01-13 10:48:05.681146", "msg": "non-zero return code", "rc": 1, "start": "2021-01-13 10:47:50.598877", "stderr": "Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)", "stderr_lines": ["Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"], "stdout": "", "stdout_lines": []}
fatal: [tjgd-163 -> 172.31.164.162]: FAILED! => {"attempts": 4, "changed": true, "cmd": ["/usr/bin/docker", "pull", "gcr.io/google-containers/kube-scheduler:v1.15.11"], "delta": "0:00:15.085360", "end": "2021-01-13 10:48:13.719390", "msg": "non-zero return code", "rc": 1, "start": "2021-01-13 10:47:58.634030", "stderr": "Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)", "stderr_lines": ["Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"], "stdout": "", "stdout_lines": []}

NO MORE HOSTS LEFT **************************************************************************************
	to retry, use: --limit @/root/pai-deploy/kubespray/cluster.retry

PLAY RECAP **********************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
tjgd-162                   : ok=160  changed=7    unreachable=0    failed=1   
tjgd-163                   : ok=124  changed=6    unreachable=0    failed=1   
tjgd-164                   : ok=124  changed=6    unreachable=0    failed=1

**Comment by hzy46** [comment]
Can you access `gcr.io` on your machine? Please confirm it.

**Comment by lirq-q** [comment]
i  try it  , i  can't  access  gcr.io  ,Do you have any recommended access methods?

**Comment by hzy46** [comment]
It changes all the time. Maybe aliyun works. Please search `gcr.io` in the search engine.

**Comment by lirq-q** [comment]
K8S is not installed through a script. Is it feasible to install it manually？

**Comment by hzy46** [comment]
We recommend you to install it from kubespray. It is well-tested. So my suggestion is to set up a local proxy to use kubespray.

K8s has a lot of settings so manual setup is easy to cause problems.  If you insist, please install Kubernetes 1.14 and have a try.

**Comment by lirq-q** [comment]
Ok ,thanks  ,we  try

**Comment by siaimes** [comment]
@lirq-q [https://blog.siaimes.me/2020/11/12/p53.html](https://blog.siaimes.me/2020/11/12/p53.html) 

I solved this problem by using a proxy server, you can refer to my blog for some inspiration. But I can't tell how to start the proxy server in my blog, otherwise, my blog will be blocked by the GFW.

**Comment by lirq-q** [comment]
@siaimes ok,thank you,

**Comment by riokaa** [comment]
If:
1. Your master and workers are in a LAN, for example, in a university;
2. Your own pc, which running a proxy(for me, it's clash for windows, you can also use ssr) and access `gcr.io`, also in this LAN;

You can open "allow LAN access" on clash, get your pc's ip and proxy's port(101.76.215.113:7890 for me), and set docker proxy on master and all workers:

```shell
# open docker proxy on master and workers
# proxy ip will change, so only for temporary use
mkdir -p /etc/systemd/system/docker.service.d
sudo tee /etc/systemd/system/docker.service.d/http-proxy.conf <<EOF
[Service]
Environment="HTTP_PROXY=http://101.76.215.113:7890/"
Environment="HTTPS_PROXY=http://101.76.215.113:7890/"
EOF

sudo systemctl daemon-reload
systemctl show --property=Environment docker
sudo systemctl restart docker

# test if succeed
docker pull gcr.io/google_containers/pause-amd64:3.1

# close proxy after installed k8s and pai
rm /etc/systemd/system/docker.service.d
sudo systemctl daemon-reload
sudo systemctl restart docker
```
