### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by JosephKang** [microsoft/pai#5248]
**Organization Name**:
Advantech

**Short summary about the issue/question**:
The announced deployed method seems to be unable to deploy openpai version on v1.4.1.
https://openpai.readthedocs.io/en/latest/manual/cluster-admin/installation-guide.html#installation-from-scratch

https://github.com/microsoft/pai/blob/v1.3.0/contrib/kubespray/quick-start-kubespray.sh

**Brief what process you are following**:
1. Checkout v1.4.1 openpai
2. Create worker.csv, master.csv and config 
3. Deploy k8s via command: 
  `/bin/bash quick-start-kubespray.sh -m /path/to/master.csv -w /path/to/worker.csv -c /path/to/config` 
4. The deploy script have some error upon fetching ~/pai/contrib/kubespray/config/config.yaml
`
Clone OpenPAI source code from github to /home/ubuntu/pai-deploy
Cloning into '/home/ubuntu/pai-deploy/pai'...
fatal: Remote branch pai-1.5.y not found in upstream origin
`
5. Should we configure ~/pai/contrib/kubespray/config/config.yaml and ~/pai/contrib/kubespray/config/layout.yaml instead?

**How to reproduce it**:
Just follow the steps listed above.

**OpenPAI Environment**:
- OpenPAI version:
v1.4.1

**Comment by suiguoxin** [comment]
@JosephKang Thanks for raising this issue. 

For v1.4.1, please make sure that the following `versions` are the same:
- the version you specified in `path/to/config`, including `branch_name` and `docker_image_name`
- the branch of the pai source code you are using locally 
- the document version

`~/pai/contrib/kubespray/config/config.yaml` & `~/pai/contrib/kubespray/config/layout.yaml` are only involved in the upcoming v1.5.0 version (very soon).  The deploy process will be refined in v1.5.0.

**Comment by JosephKang** [comment]
@suiguoxin 
It seems that `~/pai/contrib/kubespray/config/config.yaml` and `~/pai/contrib/kubespray/config/layout.yaml` configurations are involved in v1.3.0 and  v1.4.1. 
- https://github.com/microsoft/pai/blob/v1.4.1/contrib/kubespray/quick-start-kubespray.sh
- https://github.com/microsoft/pai/blob/v1.4.1/contrib/kubespray/quick-start-service.sh

Should I use the two configurations directly for the for v1.4.1 deployment?

> @JosephKang Thanks for raising this issue.
> 
> For v1.4.1, please make sure that the following `versions` are the same:
> 
> * the version you specified in `path/to/config`, including `branch_name` and `docker_image_name`
> * the branch of the pai source code you are using locally
> * the document version, including `readthedocs` link and github markdown files
> 
> `~/pai/contrib/kubespray/config/config.yaml` & `~/pai/contrib/kubespray/config/layout.yaml` are only involved in the upcoming v1.5.0 version (very soon). The deploy process will be refined in v1.5.0.

**Comment by suiguoxin** [comment]
@JosephKang  There is potentially an issue with github webportal, we will look into it. Currently please refer to [pai-1.4.y branch](https://github.com/microsoft/pai/blob/pai-1.4.y/contrib/kubespray/quick-start-kubespray.sh) instead of [v1.4.1 tag](https://github.com/microsoft/pai/blob/v1.4.1/contrib/kubespray/quick-start-kubespray.sh) for v1.4.1 doc.

**Comment by suiguoxin** [comment]
@JosephKang The tag issue is fixed by removing accidently created branch. You can use the doc with tags : [v1.4.1 tag](https://github.com/microsoft/pai/blob/v1.4.1/contrib/kubespray/quick-start-kubespray.sh) safely now.

**Comment by JosephKang** [comment]
@suiguoxin 

Thanks. It seems that https://github.com/microsoft/pai/tree/v1.4.1 is synced with the current document and can be deployed successfully.
