### ISSUE TITLE
Feedback v1.4.1 gpu utilization suddenly drops to 0

### ISSUE THREAD

**Issue by guningbo** [microsoft/pai#5263]
**Organization Name**:
Hangzhou Innovation Institute, Beihang university

**Short summary about the issue/question**:
After I upgraded the cluster version from 1.2.1 to 1.4.1, the gpu utilization of all tasks on a host suddenly dropped to 0, but this phenomenon did not occur in the previous version. When viewing the physical host, no abnormalities were found. When I forcibly restart the host, the problematic gpu can be used normally again.

![image](https://user-images.githubusercontent.com/7578703/105660112-43172e80-5f05-11eb-8f6a-342f375383f8.png)
![image](https://user-images.githubusercontent.com/7578703/105660120-49a5a600-5f05-11eb-9c40-e28f2ed35b83.png)

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**: 
- OpenPAI version: 1.4.1
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release): ubuntu1604
- Kernel (e.g. `uname -a`): 
- Hardware (e.g. core number, memory size, storage size, GPU type etc.): 8card v100
- Others:

**Anything else we need to know**:

**Comment by hzy46** [comment]
Please confirm if `node-exporter` is working properly by: `kubectl get po | grep node-exporter`.

Also, is the problem solved after you restart the host?

**Comment by guningbo** [comment]
sorry,I have restarted the machine. This problem does not appear after restarting, and it has not reproduced yet

**Comment by hzy46** [comment]
OK. Close this issue for now.
