### ISSUE TITLE
Unable to submit task because no node resource is available

### ISSUE THREAD

**Issue by JosephKang** [microsoft/pai#5265]
**Organization Name**:
Advantech

**Short summary about the issue/question**:
Unable to submit task because no node resource is available

**Brief what process you are following**:
1. Deploy openpai v1.0.1 to 1 GPU node environment with postgresql port=5430 in services-configuration.yaml
2. Submit a GPU task with minimum resource requirement
3. The task kept in waiting 
`
root@ai:~/pai/src# kubectl describe pod 584817d663eb0fe2b47da42473496e2a-taskrole-0 | grep Events -A10
Events:
  Type     Reason            Age                   From                       Message
  ----     ------            ----                  ----                       -------
  Warning  FailedScheduling  2m37s (x53 over 78m)  hivedscheduler-ds-default  0/1 nodes are available: 1 Insufficient github.com/fuse.
`

**K8s Pod  hivedscheduler-hs log**
`
I0125 06:42:44.151436       9 hived_algorithm.go:546] Cell type DT-NODE (chain DT-NODE-POOL level 2) now has sufficient healthy cells (healthy 1, bad 0) for allocating the total free cells of all the VCs (1).
I0125 06:42:44.151457       9 hived_algorithm.go:567] Cell type DT-NODE (chain DT-NODE-POOL level 2) now has sufficient healthy cells (healthy 1, bad 0) for allocating the free cells of the VC default (1).
I0125 06:42:44.151500       9 cell.go:301] Cell 0 is set to Healthy
I0125 06:42:44.151505       9 cell.go:301] Cell 0/e100-aifs/1 is set to Healthy
I0125 06:42:44.151512       9 utils.go:321] [e100-aifs]: addNode: Succeeded
I0125 06:42:44.240703       9 webserver.go:119] Running webserver
I0125 06:42:44.240726       9 scheduler.go:211] Running hivedscheduler
I0125 06:55:35.923681       9 scheduler.go:342] [388c5d96-003a-4076-9ecb-54049a3bfc78(default/584817d663eb0fe2b47da42473496e2a-taskrole-0)]: addUnboundPod: Started
I0125 06:55:35.923703       9 utils.go:321] [388c5d96-003a-4076-9ecb-54049a3bfc78(default/584817d663eb0fe2b47da42473496e2a-taskrole-0)]: addUnboundPod: Succeeded
`

**K8s Pod hivedscheduler-ds-default-0 log**
`
**I0125 08:21:45.616175       6 reflector.go:370] k8s.io/client-go/informers/factory.go:133: Watch close - *v1.Node total 54 items received
I0125 08:21:45.619674       6 scheduling_queue.go:908] About to try and schedule pod default/584817d663eb0fe2b47da42473496e2a-taskrole-0
I0125 08:21:45.619697       6 scheduler.go:453] Attempting to schedule pod: default/584817d663eb0fe2b47da42473496e2a-taskrole-0
I0125 08:21:45.619934       6 factory.go:647] Unable to schedule default/584817d663eb0fe2b47da42473496e2a-taskrole-0: no fit: 0/1 nodes are available: 1 Insufficient github.com/fuse.; waiting
I0125 08:21:45.619989       6 factory.go:742] Updating pod condition for default/584817d663eb0fe2b47da42473496e2a-taskrole-0 to (PodScheduled=False, Reason=Unschedulable)
I0125 08:21:45.622099       6 generic_scheduler.go:1118] Node e100-aifs is a potential node for preemption.
**
`

**How to reproduce it**:
1. Stop and Start service the services will still result the same waiting behavior and error log

**OpenPAI Environment**:
- OpenPAI version: v1.0.1
- Cloud provider or hardware configuration:

**Anything else we need to know**:
It might be related to https://github.com/microsoft/pai/issues/5197#issuecomment-750722167 but more this issue happened without any task being submitted successfully..

**Comment by yqwang-ms** [comment]
It seems caused by the "Insufficient github.com/fuse"
Make sure you have installed the https://github.com/microsoft/pai/blob/master/src/device-plugin/README.md

@abuccts to help

**Comment by JosephKang** [comment]
Thanks @yuqyang ,

I found that `nvidia-device-plugin` and `k8s-host-device-plugin` daemonsets fail to start due to the resourcequota set to kube-system namespace. The scheduling is OK after I remove the resourcequota to let nvidia-device-plugin and k8s-host-device-plugin to start successfully.
