### ISSUE TITLE
travis-ci.org is shutting down

### ISSUE THREAD

**Issue by abuccts** [microsoft/pai#5275]
> Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information.

possible solutions:
* migrating this repository to travis-ci.com, [reference](https://docs.travis-ci.com/user/migrate/open-source-repository-migration)
* use GitHub Action to replace travis

**Comment by yiyione** [comment]
I think we can use GitHub Action to replace travis.
