### ISSUE TITLE
Token validation API for PAI client

### ISSUE THREAD

**Issue by qfyin** [microsoft/pai#5285]
Verify if the user token is valid.
PAI client (web portal, vs code extension, cli, marketplace, etc.) may cache the token and use it in REST API request.

**Comment by yiyione** [comment]
Test cases:
1. Test verify success
    1. Call API `GET /rest-server/api/v2/tokens/check` with header
        `{ "Authorization": "<correct token>", "Content-Type": "application/json" }`
    2. Should return 200 with body
        ```json
        {
            "username": "<username>",
            "application": false,
            "iat": 1612250730,
            "exp": 1612855530,
            "admin": true
        }
        ````
2. Test invalid token
    1. Call API `GET /rest-server/api/v2/tokens/check` with header
        `{ "Authorization": "<invalid token>", "Content-Type": "application/json" }`
    2. Should return 401 with body
        ```json
        {
            "code": "UnauthorizedUserError",
            "message": "Your token is invalid."
        }
        ````
