### ISSUE TITLE
Pod Rest-server failed to restart

### ISSUE THREAD

**Issue by JosephKang** [microsoft/pai#5308]
**Organization Name**:
Advantech

**Short summary about the issue/question**:
Unable to restart rest-server pod

**Brief what process you are following**:
1. Deploy openpai cluster v1.5.0 
2. The rest-server pod works fine
3. Start openpai/dev-box:v1.5.0 container and attach the container
4. Enter /pai 
5. Execute ./paictl.py service stop -n rest-server
6. Execute ./paictl.py service start -n rest-server
7. The rest-server pod keeps **CrashLoopBackOff** and the log observed
```
~/pai$ kubectl logs rest-server-ds-4lt7q

> pai-rest-server@1.5.0 start /usr/src/app
> node index.js

(node:18) UnhandledPromiseRejectionWarning: Error: launcher config error
ValidationError: child "restServerUri" fails because ["restServerUri" is required]
    at Object.<anonymous> (/usr/src/app/src/config/launcher.js:112:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/src/app/src/controllers/index.js:19:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**How to reproduce it**:
Repeat step 5. 6.

**OpenPAI Environment**:
- OpenPAI version: V1.5.1

**Comment by hzy46** [comment]
I think someone may mis-updated v1.5.0 container of openpai.

https://hub.docker.com/r/openpai/rest-server/tags?page=1&ordering=last_updated

Will check this.

**Comment by debuggy** [comment]
hi @JosephKang. Thanks for the feedback. The openpai/rest-server:v1.5.0 image has been reset currently, could you try it again?

**Comment by JosephKang** [comment]
@debuggy and @hzy46 
Thanks for the help. The latest rest-server image v1.5.0 works fine without *restServerUri* issue.
