### ISSUE TITLE
Key Error when run /bin/bash quick-start-service.sh

### ISSUE THREAD

**Issue by HaoLiuHust** [microsoft/pai#5317]
Version: v1.5.0
After run quick-start-kuberspary.sh with below outputs, 
![image](https://user-images.githubusercontent.com/7233091/108931371-8094e600-7682-11eb-82c0-7ce468e3c99f.png)
I execute /bin/bash quick-start-service.sh according to the install guidelines, but an error occured 
![image](https://user-images.githubusercontent.com/7233091/108931452-a8844980-7682-11eb-947c-58662908e2d8.png)
seems the worker node can not be found

**Comment by hzy46** [comment]
Could you use `kubectl get node` to confirm `uniubi-alg057` is a Ready node in Kubernetes.

You may run `ansible-playbook -i ${HOME}/pai-deploy/kubespray/inventory/pai/hosts.yml set-kubectl.yml --ask-become-pass` to set up kubectl on your dev box machine.

**Comment by HaoLiuHust** [comment]
> Could you use `kubectl get node` to confirm `uniubi-alg057` is a Ready node in Kubernetes?
> 
> You may run `ansible-playbook -i ${HOME}/pai-deploy/kubespray/inventory/pai/hosts.yml set-kubectl.yml --ask-become-pass` to set up kubectl on your dev box machine.

![image](https://user-images.githubusercontent.com/7233091/108938903-d4f09380-768b-11eb-8860-053b5acec01f.png)

uniubi-alg057 can not be found..why,

**Comment by hzy46** [comment]
There might be a lot of reasons for this. Actually OpenPAI is using https://github.com/kubernetes-sigs/kubespray to set up k8s. You can check:

1. On the dev box machine, use `cat ~/pai-deploy/kubespray/inventory/pai/hosts.yml` to see if the worker is included in kubespray's inventory file.
2. On the worker node, use `sudo systemctl status kubelet` to confirm whether the kubelet is set correctly.

**Comment by HaoLiuHust** [comment]
1. on dev box, hosts.yml, uniubi-alg057 is in it:
![image](https://user-images.githubusercontent.com/7233091/108939584-e7b79800-768c-11eb-8129-356a6d178a22.png)
2. on the worker node, seems it is running:
![image](https://user-images.githubusercontent.com/7233091/108939702-1170bf00-768d-11eb-8cfd-aae321727350.png)

**Comment by hzy46** [comment]
Sure. The hosts.yml is OK, and the kubelet is running. But it seems k8s master doesn't recognize node `uniubi-alg057`. I don't know whether is is a bug with Kubespray. You may run quick-start-kubespray again to retry.

**Comment by HaoLiuHust** [comment]
delete uniubi-057 and add another server as work node, this step is OK now...even thougn did not find out the reason. However another problem occurred, log-manager has some problem:
![image](https://user-images.githubusercontent.com/7233091/108967944-15b3d100-76bb-11eb-9cd5-1e0afe20d3d9.png)

**Comment by hzy46** [comment]
Use the following commands to check:
```bash
# get pod name
kubctl get po | grep log-manager

kubectl describe po <pod-name-of-log-manager>
kubectl logs <pod-name-of-log-manager>
``

**Comment by HaoLiuHust** [comment]
1. kubctl get po | grep log-manager
![image](https://user-images.githubusercontent.com/7233091/108968899-56f8b080-76bc-11eb-87b7-b04a4f6822d7.png)
2.kubectl describe po log-manager-ds-t72pb 
![image](https://user-images.githubusercontent.com/7233091/108968954-6677f980-76bc-11eb-89ee-83fe57010c35.png)
3.kubectl logs log-manager-ds-t72pb 
![image](https://user-images.githubusercontent.com/7233091/108969019-7abbf680-76bc-11eb-9416-31db437943f4.png)
error: a container name must be specified for pod log-manager-ds-t72pb, choose one of: [log-cleaner log-manager-nginx]

**Comment by hzy46** [comment]
Pod log-manager-ds-k9wqv is Evicted. Please use `kubectl describe po log-manager-ds-k9wqv` to find out why.

**Comment by HaoLiuHust** [comment]
![image](https://user-images.githubusercontent.com/7233091/108971038-0df52c00-76bd-11eb-99f1-d0ca420a05ba.png)

**Comment by hzy46** [comment]
You have a DiskPressure, please check the disk.

![image](https://user-images.githubusercontent.com/7499023/108971834-af7c7d80-76bd-11eb-9146-08c6f81ac493.png)

**Comment by HaoLiuHust** [comment]
Thanks, how many disk storage should I leave and on which disk?

**Comment by hzy46** [comment]
I suggest that there should be at least 50% left space. OpenPAI will reserve 30G on your master machine. Please take this into consideration.

**Comment by HaoLiuHust** [comment]
I have set it up with version 1.4.0, close this issue for now
