### ISSUE TITLE
Is python is the main develop language?

### ISSUE THREAD

**Issue by HaoLiuHust** [microsoft/pai#5350]
I want to use OpenPAI in our company and then develop some feature in need, is python is the main develop language? and what kind of software developers we need to do this work

**Comment by fanyangCS** [comment]
It depends on the feature you plan to add. 
![image](https://user-images.githubusercontent.com/5820832/110070956-17b21a00-7db6-11eb-9272-7fe6d4985219.png)

**Comment by HaoLiuHust** [comment]
thanks, how to debug when we developing some new feature, just reconfigure the OpenPAI again?

**Comment by fanyangCS** [comment]
different modular has different way of debugging.

**Comment by HaoLiuHust** [comment]
Thanks
