### ISSUE TITLE
API document for v1.x

### ISSUE THREAD

**Issue by edenbuaa** [microsoft/pai#5352]
It seems the rest-server api documents is missing after v1.0.0.  Where we can find it? 

thanks.

**Comment by suiguoxin** [comment]
> It seems the rest-server api documents is missing after v1.0.0. Where we can find it?
> 
> thanks.

@edenbuaa https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/microsoft/pai/master/src/rest-server/docs/swagger.yaml#operation/getAllGroup

**Comment by edenbuaa** [comment]
great, thanks @suiguoxin
