### ISSUE TITLE
could we choose the type of GPU when we create job

### ISSUE THREAD

**Issue by HaoLiuHust** [microsoft/pai#5354]
if we have some server with different kind of GPU, such as one server has 8 RTX 3090 and another one has 8 1080Ti, could we choose the type of GPU when we create job?

**Comment by fanyangCS** [comment]
In this case, we suggest to create different VCs, each hosting one type of GPU. https://openpai.readthedocs.io/en/latest/manual/cluster-admin/how-to-set-up-virtual-clusters.html#different-hardwares-in-worker-nodes
