### ISSUE TITLE
failed to fetch logs after use https

### ISSUE THREAD

**Issue by HaoLiuHust** [microsoft/pai#5377]
version 1.4.0
before set up https according to https://openpai.readthedocs.io/en/pai-1.4.y/manual/cluster-admin/basic-management-operations.html , I can get stdout logs in job page, after set it up, I can only get "failed to fetch "

**Comment by Binyang2014** [comment]
@HaoLiuHust Can you using F12 to track log request url? Need to known which url web-portal trying to access

**Comment by HaoLiuHust** [comment]
```
Request URL: http://10.1.9.53/log-manager/10.1.9.55:9103/api/v1/logs/user-stdout?username=admin&framework-name=d13e798d0e7b976906851d2719f349b1&pod-uid=be2955b8-80f7-4704-a217-0c3222d288d3&taskrole=taskrole&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTU3NzgyNzgsInN1YiI6ImxvZy1tYW5hZ2VyLXVmYWNlLWdwdS1zZXJ2ZXIiLCJpYXQiOjE2MTU3NzgxNTh9.Qv0uda56AGXec6ana3TJyt8H7STceE5vSl1Zq0X5z0Y&tail-mode=true
```

**Comment by Binyang2014** [comment]
Please try to access `http://10.1.9.53/log-manager/10.1.9.55:9103/api/v1/logs/user-stdout?username=admin&framework-name=d13e798d0e7b976906851d2719f349b1&pod-uid=be2955b8-80f7-4704-a217-0c3222d288d3&taskrole=taskrole&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTU3NzgyNzgsInN1YiI6ImxvZy1tYW5hZ2VyLXVmYWNlLWdwdS1zZXJ2ZXIiLCJpYXQiOjE2MTU3NzgxNTh9.Qv0uda56AGXec6ana3TJyt8H7STceE5vSl1Zq0X5z0Y&tail-mode=true` in your browser, and  ignore the security warning.

Then try to access log from the webportal.

If still not fix this issue, I recommend you  upgrade PAI to the latest version. We have refactored the log collection pipeline

**Comment by HaoLiuHust** [comment]
```
Access to 10.1.9.53 was deniedYou don't have authorization to view this page.
HTTP ERROR 403
```
I was using 1.5.0...but can not set it up successfully, that's why I use v1.4.0 instead

**Comment by HaoLiuHust** [comment]
is there a way to roll back to http instead of https?

**Comment by Binyang2014** [comment]
@HaoLiuHust I recommend you using https. Please try to redeploy rest-server and see if this issue is fixed.
You can run:
`./paictl.py service stop -n rest-server` 
`./paictl.py service start -n rest-server` 

To redeploy rest server

**Comment by Binyang2014** [comment]
@HaoLiuHust BTW, I wonder why 1.5 is failed to deploy. If there is some bugs for the 1.5 version, feel free to open an issue

**Comment by HaoLiuHust** [comment]
> @HaoLiuHust BTW, I wonder why 1.5 is failed to deploy. If there is some bugs for the 1.5 version, feel free to open an issue
#5306 
#5317 

I have already opened 2 issues about it, from other's comment, he also set up v1.3.0 successfully but failed to upgrade, so I decided to use v1.4.0...

**Comment by Binyang2014** [comment]
This issue should be fixed in latest version, if still has problem, feel free to reopen it
