### ISSUE TITLE
Is there a convenient way to change the node name and host name?

### ISSUE THREAD

**Issue by siaimes** [microsoft/pai#5380]
**Organization Name**:

**Short summary about the issue/question**:
Since there were fewer machines before, there is no organizational rule for naming. Now there are more machines and the names are confusing, so I want to rename all nodes, including the host name and node name.
**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version: v1.5.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by hzy46** [comment]
I recommend this:

https://docs.ansible.com/ansible/latest/collections/ansible/builtin/hostname_module.html

**Comment by siaimes** [comment]
> I recommend this:
> 
> https://docs.ansible.com/ansible/latest/collections/ansible/builtin/hostname_module.html

This seems to be directly going to the system to modify the hostname information, then can OpenPai recognize it after I modify it like this?

**Comment by hzy46** [comment]
I'm not sure. Better modify hostname first, then install PAI.

**Comment by siaimes** [comment]
> I'm not sure. Better modify hostname first, then install PAI.

Thank you for your reply. But I have already installed OpenPai. Maybe I have to delete the node, change the hostname, and add it again.
