### ISSUE TITLE
Failed to connect to github.com at port 443: [Errno 110] Connection timed out.

### ISSUE THREAD

**Issue by siaimes** [microsoft/pai#5399]
**Organization Name**:

**Short summary about the issue/question**:

Even if I can access github.com by git clone, curl and wget, running the following commands to add nodes often fails.

```
ansible-playbook -i inventory/pai/hosts.yml cluster.yml -b --become-user=root --limit=rzxt-openpai-104 -e "@inventory/pai/openpai.yml"
```

```
ansible-playbook -i inventory/pai/hosts.yml upgrade-cluster.yml --become --become-user=root  --limit=rzxt-openpai-104 -e "@inventory/pai/openpai.yml"
```
![image](https://user-images.githubusercontent.com/34199488/112723309-ba3e6280-8f48-11eb-87e3-075a55cba941.png)

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by hzy46** [comment]
It's a network issue. Please check whether you can access "https://www.github.com". If not, please set up a local proxy.

**Comment by fanyangCS** [comment]
This also could be a reliability issue. please check whether your connection to Github is reliable.

**Comment by siaimes** [comment]
> This also could be a reliability issue. please check whether your connection to Github is reliable.

Thank you for your reply. This may be the case, because I keep running it repeatedly and it will work.
