### ISSUE TITLE
from hardware view, no data points

### ISSUE THREAD

**Issue by YanjieGao** [Microsoft/pai#541]
Hardware page:
There is an issue of no data data points. http://10.151.40.234:9286/cluster-view/hardware/detail.html?instance=10.151.40.241:9100

seems remove url instance's var port will make it work. 
https://github.com/Microsoft/pai/blob/e4244ee08d29f33d914a2648049247171efbaf7d/webportal/src/app/cluster-view/hardware/hardware-detail.component.ejs

Call Grafana from url
Not work:
http://10.151.40.234:3000/dashboard/db/pai_nodeview?var-node=10.151.40.241:9100
Work:
http://10.151.40.234:3000/dashboard/db/pai_nodeview?var-node=10.151.40.241

**Comment by hwuu** [comment]
Fixing in https://github.com/Microsoft/pai/pull/543
