### ISSUE TITLE
Build job-exporter image error

### ISSUE THREAD

**Issue by liuli03** [microsoft/pai#5435]
**Organization Name**:

**Short summary about the issue/question**: When I built the job exporter image, the following error occurred:` dpkg-query: package 'rocm-smi' is not installed.` I checked the log,  may be caused by the update of romc-smi. Changing 
  `cp -R $(dpkg -L rocm-smi | grep bin$) /opt/rocm && \ `
in dockerfile to 
`cp -R $(dpkg -L rocm-smi-lib | grep bin$) /opt/rocm && \`
can solve this problem

**Brief what process you are following**:

build image

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version: 0.16.y
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):Ubuntu 16.04.7 
- Kernel (e.g. `uname -a`): 4.4.0-186-generic
- Hardware (e.g. core number, memory size, storage size, GPU type etc.): 8core,16GB memory,no GPU
- Others:

**Anything else we need to know**:

**Comment by Binyang2014** [comment]
Please feel free to reopen it
