### ISSUE TITLE
v0.4.1 deployment issue

### ISSUE THREAD

**Issue by abuccts** [Microsoft/pai#546]
v-0.4.1 deployment following readme causes some issues on node-exporter.

1. node-exporter pod error
```
level=error msg="Error reading textfile collector directory /datastorage/prometheus: open /datastorage/prometheus: no such file or directory" source="textfile.go:81"
```
Creating directory `/datastorage/prometheus` manually can solve this problem.

2. gpu-exporter containers are created on each node and log `/bin/sh: 1: nvidia-smi: not found` on nodes which do not have gpu. Shouldn't the container be created on nodes with gpu, just the same as `drivers-one-shot`?

**Comment by ydye** [comment]
1) Is it an error when node-exporter has been started?
2)  It's a known issue, I think. 

@YanjieGao

**Comment by abuccts** [comment]
yes

**Comment by YanjieGao** [comment]
hi yifan, 
for 
q1 deploy on which bed? i will check the reason
q2  Currently the gpu-exporter contains gpu metrics + job docker metrics function. if no gpu, it will write a error log. As the container also contains job metrics exporter function, it need continues running.
