### ISSUE TITLE
[v1.6.0] The histogram of available GPU resources does not seem to work.

### ISSUE THREAD

**Issue by siaimes** [microsoft/pai#5463]
**Organization Name**:

**Short summary about the issue/question**:
![image](https://user-images.githubusercontent.com/34199488/116491555-b9447c00-a8cc-11eb-91bf-a88154d826b9.png)

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**: v1.6.0
- OpenPAI version: v1.6.0
- Cloud provider or hardware configuration: ubuntu 16.04
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by Binyang2014** [comment]
@siaimes Still has this problem? If so, can you open developer mode (press `F12`) in browser and check which API failed

**Comment by siaimes** [comment]
> @siaimes Still has this problem? If so, can you open developer mode (press `F12`) in browser and check which API failed

Related to [this issue](https://github.com/microsoft/pai/issues/5465).

**Comment by siaimes** [comment]
The version of `/pai/paictl.py` is the latest version. `quickstart_xxx.sh` has been switched to `/mnt/pai/paictl.py`, but the document has not been modified yet, so I encountered several version inconsistencies, and finally run `/mnt/pai/paictl.py` instead of `/pai/ paictl.py` has been resolved those issues.
