### ISSUE TITLE
Will the new version of the code affect the execution logic of the old version?

### ISSUE THREAD

**Issue by siaimes** [microsoft/pai#5465]
**Organization Name**:

**Short summary about the issue/question**: I encountered some version problems. Currently, the openpai I deployed is v1.6.0, but on the k8s dashboard, I see it is pulling the cert-expeiration-checker image, which is a feature introduced in v1.7.0.
![image](https://user-images.githubusercontent.com/34199488/116782639-04bd7c80-aabd-11eb-8b9a-9f887ce96bd7.png)

**Brief what process you are following**: 

**How to reproduce it**:

**OpenPAI Environment**: ubuntu 16.04
- OpenPAI version: v1.6.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by Binyang2014** [comment]
Please make sure your code is checked out to v1.6.0 tag. Seems you use the latest code

**Comment by siaimes** [comment]
![image](https://user-images.githubusercontent.com/34199488/116800093-88648100-ab30-11eb-808c-115217fad23b.png)

**Comment by siaimes** [comment]
```
csip@csip-dev-box:~$ sudo docker run -itd         -e COLUMNS=$COLUMNS -e LINES=$LINES -e TERM=$TERM         -v /var/run/docker.sock:/var/run/docker.sock         -v ${HOME}/pai-deploy/cluster-cfg:/cluster-configuration          -v ${HOME}/pai-deploy/kube:/root/.kube         --pid=host         --privileged=true         --net=host         --name=dev-box         openpai/dev-box:v1.6.0
915741461e98630ddadb9a29c6061778f18059906c0bc484ba83a2c68249ac9c
csip@csip-dev-box:~$ sudo docker exec -it dev-box bash
root@csip-dev-box:/# ls
bin  boot  cluster-configuration  dev  etc  home  lib  lib64  media  mnt  opt  pai  proc  root  run  sbin  srv  sys  tmp  usr  var
root@csip-dev-box:/# cd pai
root@csip-dev-box:/pai# git status
HEAD detached at v1.7.0
nothing to commit, working directory clean
root@csip-dev-box:/pai# 
```

**Comment by siaimes** [comment]
Checkout v1.6.0 manually solved this issue. This [issue](https://github.com/microsoft/pai/issues/5466) is also caused by the version problem.

**Comment by Binyang2014** [comment]
@suiguoxin Please help to take a look?

**Comment by siaimes** [comment]
The Dockerfile that builds the images does not seem to be open source, so I can not do any further analysis.

**Comment by Binyang2014** [comment]
Code is here, https://github.com/microsoft/pai/blob/master/src/dev-box/build/dev-box.common.dockerfile. Welcome for further  analysis

**Comment by siaimes** [comment]
> Code is here, https://github.com/microsoft/pai/blob/master/src/dev-box/build/dev-box.common.dockerfile. Welcome for further analysis

From the start script of dev-box, I do some checks as follows.

```
csip@csip-dev-box:~$ sudo docker run -itd \
>         -e COLUMNS=$COLUMNS -e LINES=$LINES -e TERM=$TERM \
>         -v /var/run/docker.sock:/var/run/docker.sock \
>         -v ${HOME}/pai-deploy/cluster-cfg:/cluster-configuration  \
>         -v ${HOME}/pai-deploy/kube:/root/.kube \
>         --pid=host \
>         --privileged=true \
>         --net=host \
>         --name=dev-box_1 \
>         openpai/dev-box:v1.6.0
bc633ff4766ad05cdce4bd658ba1b15ddc4988ae143b6de6ac908a6f67674852
csip@csip-dev-box:~$ sudo docker logs dev-box_1
Checkout to latest release tag
csip@csip-dev-box:~$ sudo docker exec -it dev-box_1 bash
root@csip-dev-box:/# echo $OPENPAI_BRANCH_NAME

root@csip-dev-box:/# cd pai
root@csip-dev-box:/pai# git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
```

So, the env `OPENPAI_BRANCH_NAME` do not set up correctly.

**Comment by suiguoxin** [comment]
@siaimes To install OpenPAI version v1.6, please:
- checkout local pai repo to `pai-1.6.y` branch
- set `docker_image_tag: v1.6.0` in `config.yaml`

For detailed doc, pls refer to [here](https://openpai.readthedocs.io/en/pai-1.6.y/manual/cluster-admin/installation-guide.html)

We do download the pai repo and reset the code to the latest tag in dev-box, but we won't use it. 
Instead, we'll [mount the local pai repo to the dev-box](https://github.com/microsoft/pai/blob/pai-1.6.y/contrib/kubespray/script/service-boot.sh#L34) and use this copy.

We made this change in v1.6 to make sure that only the local source code matters so that the admin user don't need to specify `OPENPAI_BRANCH_NAME` anymore.

I'll close this issue, feel free to re-open it for further questions.

**Comment by siaimes** [comment]
> @siaimes To install OpenPAI version v1.6, please:
> 
> * checkout local pai repo to `pai-1.6.y` branch
> * set `docker_image_tag: v1.6.0` in `config.yaml`
> 
> For detailed doc, pls refer to [here](https://openpai.readthedocs.io/en/pai-1.6.y/manual/cluster-admin/installation-guide.html)
> 
> We do download the pai repo and reset the code to the latest tag in dev-box, but we won't use it.
> Instead, we'll [mount the local pai repo to the dev-box](https://github.com/microsoft/pai/blob/pai-1.6.y/contrib/kubespray/script/service-boot.sh#L34) and use this copy.
> 
> We made this change in v1.6 to make sure that only the local source code matters so that the admin user don't need to specify `OPENPAI_BRANCH_NAME` anymore.
> 
> I'll close this issue, feel free to re-open it for further questions.

```bash
sudo docker run -itd \
        -e COLUMNS=$COLUMNS -e LINES=$LINES -e TERM=$TERM \
        -v /var/run/docker.sock:/var/run/docker.sock \
        --pid=host \
        --privileged=true \
        --net=host \
        --name=dev-box \
        openpai/dev-box:<openpai version tag>
```

So, the start script of dev-box should need to be updated, right?

**Comment by suiguoxin** [comment]
@siaimes Do you mean [basic management operations](https://openpai.readthedocs.io/en/pai-1.6.y/manual/cluster-admin/basic-management-operations.html#pai-service-management-and-paictl) ? Users are free to mount anything they want. The existing pai repo should also work.

**Comment by Binyang2014** [comment]
Reopen it, seems we need to update doc

**Comment by siaimes** [comment]
[4675](https://github.com/microsoft/pai/issues/4675)

I found that this issue was introduced in v1.0.0, but it did not get the attention of developers at that time.

**Comment by siaimes** [comment]
PR #5567 conflict with PR #5240, I will close it, a better solution needs further discussion.

**Comment by hlyf-xs** [comment]
> Please make sure your code is checked out to v1.6.0 tag. Seems you use the latest code



> ```
> csip@csip-dev-box:~$ sudo docker run -itd         -e COLUMNS=$COLUMNS -e LINES=$LINES -e TERM=$TERM         -v /var/run/docker.sock:/var/run/docker.sock         -v ${HOME}/pai-deploy/cluster-cfg:/cluster-configuration          -v ${HOME}/pai-deploy/kube:/root/.kube         --pid=host         --privileged=true         --net=host         --name=dev-box         openpai/dev-box:v1.6.0
> 915741461e98630ddadb9a29c6061778f18059906c0bc484ba83a2c68249ac9c
> csip@csip-dev-box:~$ sudo docker exec -it dev-box bash
> root@csip-dev-box:/# ls
> bin  boot  cluster-configuration  dev  etc  home  lib  lib64  media  mnt  opt  pai  proc  root  run  sbin  srv  sys  tmp  usr  var
> root@csip-dev-box:/# cd pai
> root@csip-dev-box:/pai# git status
> HEAD detached at v1.7.0
> nothing to commit, working directory clean
> root@csip-dev-box:/pai# 
> ```
> 
> I started a v1.6.0 deb-box, but found that the version number was v1.7.0.


> ```
> csip@csip-dev-box:~$ sudo docker run -itd         -e COLUMNS=$COLUMNS -e LINES=$LINES -e TERM=$TERM         -v /var/run/docker.sock:/var/run/docker.sock         -v ${HOME}/pai-deploy/cluster-cfg:/cluster-configuration          -v ${HOME}/pai-deploy/kube:/root/.kube         --pid=host         --privileged=true         --net=host         --name=dev-box         openpai/dev-box:v1.6.0
> 915741461e98630ddadb9a29c6061778f18059906c0bc484ba83a2c68249ac9c
> csip@csip-dev-box:~$ sudo docker exec -it dev-box bash
> root@csip-dev-box:/# ls
> bin  boot  cluster-configuration  dev  etc  home  lib  lib64  media  mnt  opt  pai  proc  root  run  sbin  srv  sys  tmp  usr  var
> root@csip-dev-box:/# cd pai
> root@csip-dev-box:/pai# git status
> HEAD detached at v1.7.0
> nothing to commit, working directory clean
> root@csip-dev-box:/pai# 
> ```
> 
> I started a v1.6.0 deb-box, but found that the version number was v1.7.0.

I also want to deploy the dev-box in a docker ubuntu container, but I can't install docker sucessful, It shows "docker: Cannot connect to Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" And Do you have some suggestions?
