### ISSUE TITLE
Cannot open web portal after installation

### ISSUE THREAD

**Issue by 0x8A63F77D** [microsoft/pai#5468]
**Short summary about the issue/question**:
After the installation, I can't open the web portal. The 80, 443, and 9820 ports are not been listened to on the master machine. 
[ports.txt](https://github.com/microsoft/pai/files/6428145/ports.txt)

**Brief what process you are following**:

- Operating type: Initial deployment 
- Brief what deployment process you are following: Just following the [guide](https://openpai.readthedocs.io/en/latest/manual/cluster-admin/index.html).

**OpenPAI Environment**:
- OpenPAI version:v1.6.0
- Cloud provider or hardware configuration: Dell T640
- OS (e.g. from /etc/os-release): Ubuntu 20.04
- Kernel (e.g. `uname -a`): 5.4.0-72-generic
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by yiyione** [comment]
can you run `kubectl get pods` to see if the webportal is running ?
![image](https://user-images.githubusercontent.com/17357108/117257835-e53ca000-ae7e-11eb-9a71-1366c1fa9824.png)

**Comment by 0x8A63F77D** [comment]
> can you run `kubectl get pods` to see if the webportal is running ? Thanks
> ![image](https://user-images.githubusercontent.com/17357108/117257835-e53ca000-ae7e-11eb-9a71-1366c1fa9824.png)

8080
I tried to use kubectl portforward and the web portal can be opened. But I cannot log in. The error message is

> Cannot read property 'message' of undefined openpai

**Comment by 0x8A63F77D** [comment]
Well, it's working now. It seems to be related to [this](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#letting-iptables-see-bridged-traffic). Please add this to the installation guide.

**Comment by JohanOu** [comment]
> > can you run `kubectl get pods` to see if the webportal is running ? Thanks
> > ![image](https://user-images.githubusercontent.com/17357108/117257835-e53ca000-ae7e-11eb-9a71-1366c1fa9824.png)
> 
> Yes it is running.
> I tried to use kubectl portforward and the web portal can be opened. But I cannot log in. The error message is
> 
> > Cannot read property 'message' of undefined openpai

how to solve this problem?Could you please give some details?Thanks

**Comment by 0x8A63F77D** [comment]
> > > can you run `kubectl get pods` to see if the webportal is running ? Thanks
> > > ![image](https://user-images.githubusercontent.com/17357108/117257835-e53ca000-ae7e-11eb-9a71-1366c1fa9824.png)
> > 
> > 
> > Yes it is running.
> > I tried to use kubectl portforward and the web portal can be opened. But I cannot log in. The error message is
> > > Cannot read property 'message' of undefined openpai
> 
> how to solve this problem?Could you please give some details?Thanks
Check [Letting iptables see bridged traffic](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#letting-iptables-see-bridged-traffic). Run the commands on the master and slave nodes (I forget whether it's only needed on the master node or master and slave nodes, just in case.

**Comment by JohanOu** [comment]
> > > > can you run `kubectl get pods` to see if the webportal is running ? Thanks
> > > > ![image](https://user-images.githubusercontent.com/17357108/117257835-e53ca000-ae7e-11eb-9a71-1366c1fa9824.png)
> > > 
> > > 
> > > Yes it is running.
> > > I tried to use kubectl portforward and the web portal can be opened. But I cannot log in. The error message is
> > > > Cannot read property 'message' of undefined openpai
> > 
> > 
> > how to solve this problem?Could you please give some details?Thanks
> 
> Check [Letting iptables see bridged traffic](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#letting-iptables-see-bridged-traffic). Run the commands on the master and slave nodes (I forget whether it's only needed on the master node or master and slave nodes, just in case).

I have tried,but i doesnt work
![image](https://user-images.githubusercontent.com/64004740/128331092-8259f374-1534-41e3-ba27-3e36aacaf76e.png)

**Comment by JohanOu** [comment]
> > > > can you run `kubectl get pods` to see if the webportal is running ? Thanks
> > > > ![image](https://user-images.githubusercontent.com/17357108/117257835-e53ca000-ae7e-11eb-9a71-1366c1fa9824.png)
> > > 
> > > 
> > > Yes it is running.
> > > I tried to use kubectl portforward and the web portal can be opened. But I cannot log in. The error message is
> > > > Cannot read property 'message' of undefined openpai
> > 
> > 
> > how to solve this problem?Could you please give some details?Thanks
> 
> Check [Letting iptables see bridged traffic](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#letting-iptables-see-bridged-traffic). Run the commands on the master and slave nodes (I forget whether it's only needed on the master node or master and slave nodes, just in case).

I visit http://localhost:9286/.   Is it right?

**Comment by 0x8A63F77D** [comment]
> > > > > can you run `kubectl get pods` to see if the webportal is running ? Thanks
> > > > > ![image](https://user-images.githubusercontent.com/17357108/117257835-e53ca000-ae7e-11eb-9a71-1366c1fa9824.png)
> > > > 
> > > > 
> > > > Yes it is running.
> > > > I tried to use kubectl portforward and the web portal can be opened. But I cannot log in. The error message is
> > > > > Cannot read property 'message' of undefined openpai
> > > 
> > > 
> > > how to solve this problem?Could you please give some details?Thanks
> > 
> > 
> > Check [Letting iptables see bridged traffic](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#letting-iptables-see-bridged-traffic). Run the commands on the master and slave nodes (I forget whether it's only needed on the master node or master and slave nodes, just in case).
> 
> I visit http://localhost:9286/. Is it right?

The port is 8080.

**Comment by Binyang2014** [comment]
Close this. Feel free to reopen

**Comment by HaoLiuHust** [comment]
> > > > > can you run `kubectl get pods` to see if the webportal is running ? Thanks
> > > > > ![image](https://user-images.githubusercontent.com/17357108/117257835-e53ca000-ae7e-11eb-9a71-1366c1fa9824.png)
> > > > 
> > > > 
> > > > Yes it is running.
> > > > I tried to use kubectl portforward and the web portal can be opened. But I cannot log in. The error message is
> > > > > Cannot read property 'message' of undefined openpai
> > > 
> > > 
> > > how to solve this problem?Could you please give some details?Thanks
> > 
> > 
> > Check [Letting iptables see bridged traffic](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#letting-iptables-see-bridged-traffic). Run the commands on the master and slave nodes (I forget whether it's only needed on the master node or master and slave nodes, just in case).
> 
> I visit http://localhost:9286/. Is it right?

Have you solved the problem?
