### ISSUE TITLE
Does pai support some like oversold?

### ISSUE THREAD

**Issue by cxys1133** [microsoft/pai#5472]
I am trying to deploy pai on a small cluster (two 8-GPU servers). We have 8~10 users, and want to split resources equally, but don't assume everyone is online at the same time. I think the way that pai supports  is to use VC, one VC for each person. (Am I right?) I read these two documents: https://github.com/microsoft/pai/blob/master/docs/manual/cluster-admin/how-to-set-up-virtual-clusters.md, https://github.com/microsoft/hivedscheduler/blob/master/doc/user-manual.md, but I don't know whether it can support this idea: on the premise of a total of 16 cards, set up 16 physicalcells, set up 10 VCs, and allocate 2 virtualcells for each VC.

**Comment by hzy46** [comment]
We support opportunistic jobs. It is like over selling but not the same thing. Take the following picture for reference:

![image](https://user-images.githubusercontent.com/7499023/117916099-130b6400-b319-11eb-9bc2-ed8d055a2af3.png)

![image](https://user-images.githubusercontent.com/7499023/117916161-2dddd880-b319-11eb-8ed2-327012f3827a.png)

**Comment by cxys1133** [comment]
Thanks for reply. It partly solves my problem.
