### ISSUE TITLE
virtualcluster name and groupname conflict in hivescheduler and rest-server

### ISSUE THREAD

**Issue by edenbuaa** [microsoft/pai#5505]
**OpenPAI Environment**:
- OpenPAI version: v1.7.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

I have a vitual cluster named 'vc_cpu' in  hivedscheduler config. the hivedscheduler gives a invalid metadata.name error:
![image](https://user-images.githubusercontent.com/16248697/119772529-e7c86d80-bef1-11eb-91c4-eacc60984f82.png)

Then I changed it to 'vc-cpu', the rest-server throw a error too:
![image](https://user-images.githubusercontent.com/16248697/119772753-41c93300-bef2-11eb-97d1-931ed883e0f2.png)

So, Does it mean I can't use '-' or '_' in my virutal cluster name ?

**Comment by abuccts** [comment]
virtual cluster name cannot contain `_` and group name cannot contain `-`, they are two different configurations.
If you want to use the same name for both virtual cluster and group names, you can only use lowercase alphanumeric chars.

**Comment by edenbuaa** [comment]
@abuccts  thanks. In my case, I config the `virtualCluster` and `grouplist`  name for each ("vc-cpu" for virutal cluster, "xxyy" for group). this error still arises. Am I missing anything ?

**Comment by abuccts** [comment]
did you update config and restart related services?
```sh
python paictl.py service stop rest-server hivedscheduler
kubectl delete -n pai-group --all configmap

python paictl.py config push -m service -p /path/to/config
python paictl.py service start rest-server hivedscheduler
```
