### ISSUE TITLE
Some questions about the time cost of executing code between pai and without it

### ISSUE THREAD

**Issue by gxfun** [Microsoft/pai#552]
Thanks

We carry out some controlled experiments based on same code, data and machine with same docker image `pai.run.tensorflow`

In local machine, we execute the code in `pai.run.tensorflow` with hdfs and without hdfs respectively. Both the speed is `5 images/sec,  9.8 images/sec, 14.6 images/sec, 18.9images/sec`，corresponding to the setting of  `single  computer single gpu, single  computer two gpus, single  computer three gpus， single  computer four gpus` .  while in `pai`, the speed is `1.4 images/sec,  1.6 images/sec, 1.9 images/sec, 2.1 images/sec` with hdfs and without hdfs. So we have ruled out the impact of hdfs.

We turn to you and want to know which aspect affects the speed of code execution.

**Comment by fanyangCS** [comment]
Sorry. We are not able to answer this kind of question. Millions of possibility. 
here is the log of a resnet20/cif10 8-GPU job on our cluster:
Step	Img/sec	loss
1	images/sec: 654.3 +/- 0.0 (jitter = 0.0)	2.514
10	images/sec: 701.7 +/- 33.5 (jitter = 66.5)	2.114
20	images/sec: 711.5 +/- 22.0 (jitter = 55.5)	2.012
30	images/sec: 712.7 +/- 16.6 (jitter = 55.5)	2.173
40	images/sec: 716.6 +/- 13.2 (jitter = 59.6)	1.826
50	images/sec: 706.8 +/- 11.5 (jitter = 55.5)	2.008
60	images/sec: 697.4 +/- 12.0 (jitter = 60.1)	1.980
70	images/sec: 703.6 +/- 11.0 (jitter = 60.0)	1.804
80	images/sec: 707.2 +/- 9.8 (jitter = 55.5)	1.739
90	images/sec: 711.1 +/- 9.4 (jitter = 53.9)	1.641
100	images/sec: 711.3 +/- 9.1 (jitter = 55.5)	1.696
----------------------------------------------------------------
total images/sec: 1416.35
----------------------------------------------------------------

**Comment by gxfun** [comment]
@abuccts
Thanks, we use same commands to execute all experiments.  In order to easily compare the experimental results, we only conducted fast-RCNN experiments on single computer . Follow-up we will perform more code to verify various probabilities.

Thanks

**Comment by scarlett2018** [comment]
@gxfun - I'm cleaning old issues without any follow-ups. Please feel free to reopen the issue if this issue is still an problem on your side. When reopenning the issue, please also fill in with more status updates.
