### ISSUE TITLE
Anasible-playbook is not installed in the openpai/dev-box:v1.7.0 container 

### ISSUE THREAD

**Issue by guningbo** [microsoft/pai#5535]
**Organization Name**: Hangzhou Innovation Institute, Beihang university

**Short summary about the issue/question**:
I follow the tutorial to use the dev-box:v1.7.0 container  and add nodes to cluster. It  display the following error

2021-06-16 11:01:24,317 [INFO] - deployment.paiLibrary.paiOrchestration.change_node : Begin to add nodes: pai-worker3,pai-worker4
/bin/sh: 1: ansible-playbook: not found
2021-06-16 11:01:24,320 [ERROR] - deployment.paiLibrary.common.linux_shell : Failed to add nodes: pai-worker3,pai-worker4
Traceback (most recent call last):
  File "./paictl.py", line 107, in <module>
    main(sys.argv[1:])
  File "./paictl.py", line 99, in main
    parserd.handler(parserd)
  File "/pai/deployment/nodeCmd.py", line 49, in _add_node
    change_node.ChangeNode(args.kube_config_path, args.silence).run(mode="add", node_list=args.node_list)
  File "/pai/deployment/paiLibrary/paiOrchestration/change_node.py", line 61, in run
    error_msg="Failed to {} nodes: {}".format(mode, node_list_string)
  File "/pai/deployment/paiLibrary/common/linux_shell.py", line 31, in execute_shell_raise
    subprocess.check_call( shell_cmd, shell=True )
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd /tmp/.kubespray-a11Wxm && export ANSIBLE_DISPLAY_OK_HOSTS=yes && export ANSIBLE_DISPLAY_SKIPPED_HOSTS=yes && export ANSIBLE_CALLBACK_WHITELIST="profile_tasks" && ansible-playbook -i /tmp/.pai-config-eSwk8o/hosts.yml scale.yml -b --become-user=root -e @/tmp/.pai-config-eSwk8o/openpai.yml --limit=pai-worker3,pai-worker4' returned non-zero exit status 127
2021-06-16 11:01:24,336 [INFO] - deployment.paiLibrary.paiOrchestration.temp_kubespray : Remove temporary downloaded Kubespray folder
2021-06-16 11:01:24,356 [INFO] - deployment.paiLibrary.paiOrchestration.temp_config : Remove temporary config folder

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:  
- OpenPAI version: v1.7.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): ubuntu 1604
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by guningbo** [comment]
I installed the service manually with the following command
```
apt-get update
apt-get install software-properties-common
apt-add-repository --yes --update ppa:ansible/ansible
apt-get install ansible
```

and the next operation encountered the following problems:

```
> TASK [kubernetes/preinstall : Check that kube_service_addresses is a network range] *************************************************************************************************
> Wednesday 16 June 2021  11:25:57 +0000 (0:00:00.045)       0:00:10.571 ******** 
> fatal: [pai-worker3]: FAILED! => {"msg": "The conditional check 'kube_service_addresses | ipaddr('net')' failed. The error was: The ipaddr filter requires python's netaddr be installed on the ansible controller"}
```

**Comment by Binyang2014** [comment]
@hzy46 @suiguoxin Can you help to take a look?

**Comment by suiguoxin** [comment]
@guningbo Are you performing these operations in the dev box docker container  ?

**Comment by Starmys** [comment]
@guningbo Thank you for raising the issue. It is a known problem that our docker image needs to be updated. But we may not be able to fix it recently.

You can try installing ansible-2.9.7 in the dev-box docker container using following commands:

```bash
apt-get update
apt-get install software-properties-common
add-apt-repository ppa:deadsnakes/ppa
apt update
apt install python3.6
rm /usr/bin/python3
ln -s /usr/bin/python3.6 /usr/bin/python3
python3 -m pip install pip==20.3.4
python3 -m pip install ansible==2.9.7
```
