### ISSUE TITLE
Failed to assign PVC to specific user groups in v1.7.0

### ISSUE THREAD

**Issue by guningbo** [microsoft/pai#5536]
**Organization Name**:

**Short summary about the issue/question**:
I plan to mount the nfs storage into the cluster，and success to create PV and PVC as PAI storage on Kubernetes, and success to confirm the worker nodes have the proper package to mount the PVC.
when I assign PVC to specific user groups ,It returns the following error

> {
>     "code": "InvalidParametersError",
>     "message": "\"groupname\" is not allowed. \"description\" is not allowed. \"externalName\" is not allowed. \"extension\" is not allowed"
> }

![image](https://user-images.githubusercontent.com/7578703/122333084-2fc73700-cf6a-11eb-9802-dc56363f5dce.png)

![image](https://user-images.githubusercontent.com/7578703/122333118-3e155300-cf6a-11eb-926f-ac5da223fd54.png)

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version: v1.7.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): ubuntu 1604
- Kernel (e.g. `uname -a`): 
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by luxius-luminus** [comment]
The request body is 

```
{
  "data": {
    "groupname": "default",
    "extension": {
      "acls": {
        "storageConfigs": ["nfs-storage"],
        "admin": false,
        "virtualClusters": ["default"]
      }
    }
  },
  "patch": true
}
```

but not simply 
```
 {
    "groupname": "default",
    "extension": {
      "acls": {
        "storageConfigs": ["nfs-storage"],
        "admin": false,
        "virtualClusters": ["default"]
      }
    }
  }
```
