### ISSUE TITLE
The Configuration for china  can not to Use

### ISSUE THREAD

**Issue by gaoyangcaiji** [microsoft/pai#5537]
the Configuration  seems out of date，we can't access the address:
`user: <ssh用户>
password: <ssh密码>
docker_image_tag: v1.5.0

gcr_image_repo: "gcr.azk8s.cn"
kube_image_repo: "gcr.azk8s.cn/google-containers"
kubeadm_download_url: "https://shaiictestblob01.blob.core.chinacloudapi.cn/share-all/kubeadm"
hyperkube_download_url: "https://shaiictestblob01.blob.core.chinacloudapi.cn/share-all/hyperkube"

openpai_kubespray_extra_var:
  pod_infra_image_repo: "gcr.azk8s.cn/google_containers/pause-{{ image_arch }}"
  dnsautoscaler_image_repo: "gcr.azk8s.cn/google_containers/cluster-proportional-autoscaler-{{ image_arch }}"
  tiller_image_repo: "gcr.azk8s.cn/kubernetes-helm/tiller"
  registry_proxy_image_repo: "gcr.azk8s.cn/google_containers/kube-registry-proxy"
  metrics_server_image_repo: "gcr.azk8s.cn/google_containers/metrics-server-amd64"
  addon_resizer_image_repo: "gcr.azk8s.cn/google_containers/addon-resizer"
  dashboard_image_repo: "gcr.azk8s.cn/google_containers/kubernetes-dashboard-{{ image_arch }}"
`

**Comment by lsw214** [comment]
me too

**Comment by hzy46** [comment]
Got it.

**Comment by hzy46** [comment]
For a workaround, please set up local proxy on all nodes to get the resource, and ignore this the configuration for china.

**Comment by siaimes** [comment]
My practice is:
1. Download the files that cannot be downloaded in advance and saved them on each node;
2. Load the unavailable images to each node in advance.

I have stored these files in my OneDrive and provided a sharing link, guys can download them for free, visit my blog for more details.

**Comment by siaimes** [comment]
https://blog.siaimes.me/2021/06/07/p57.html

**Comment by siaimes** [comment]
Guys, never use a proxy, it will cause the system to be very unstable.

**Comment by gaoyangcaiji** [comment]
> https://blog.siaimes.me/2021/06/07/p57.html

**Comment by gaoyangcaiji** [comment]
@siaimes 感谢 已经按您给的方案解决了

**Comment by siaimes** [comment]
@gaoyangcaiji Glad to hear this news.
