### ISSUE TITLE
OpenPAI docker reached pull rate limit

### ISSUE THREAD

**Issue by qingdo** [microsoft/pai#5554]
**When setting up kubespray, we encountered the following error**:
We are setting up a OpenPAI server with 16 machines, however, when we run "quick-start-kubespray.sh -m /home/pai/master.csv -w /home/pai/worker.csv -c /home/pai/config". We encountered this error. 

fatal: [pai16 -> xx.xx.xx.xx]: FAILED! => {"attempts": 4, "changed": true, "cmd": ["/usr/bin/docker", "pull", "docker.io/calico/node:v3.7.3"], "delta": "0:00:01.039317", "end": "2021-07-09 12:43:23.857546", "msg$: "non-zero return code", "rc": 1, "start": "2021-07-09 12:43:22.818229", "stderr": "Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticat$ng and upgrading: https://www.docker.com/increase-rate-limit", "stderr_lines": ["Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating $nd upgrading: https://www.docker.com/increase-rate-limit"], "stdout": "", "stdout_lines": []}

From this page https://www.docker.com/increase-rate-limit. We can know that anonymous user only have 100 times pull every 6 hour. However, I have a pro account and logged into all machines including dev-box, master and worker nodes. This error continues to appear. I have no idea how to resolve it. 

- Operating type: Initial deployment

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:v1.0.y
- Cloud provider or hardware configuration: GPU Servers
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`): Linux pai03 4.4.0-193-generic #224-Ubuntu SMP Tue Oct 6 17:15:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Hardware (e.g. core number, memory size, storage size, GPU type etc.): Not relevant

**Comment by Binyang2014** [comment]
@hzy46 @suiguoxin @yiyione Any comments for this? I'm not familiar with this part

**Comment by siaimes** [comment]
https://openpai.readthedocs.io/en/latest/manual/cluster-admin/how-to-set-up-docker-image-cache.html

**Comment by qingdo** [comment]
Thanks! I have solved this problem by logging in to docker hub account under "root"
`sudo su
docker login`
instead of 
`sudo docker login` under normal username.
