### ISSUE TITLE
Login webportal with "Token Invalid" error

### ISSUE THREAD

**Issue by JosephKang** [microsoft/pai#5569]
**Organization Name**:
Advantech

**Short summary about the issue/question**:
Login the webportal with correct username/password. However, the portal pop up error window shows that `UnauthorizedError. Your token is invalid. ` and `Your token is invalid`  error messages.

**Brief what process you are following**:
1. Browse the web portal
2. Try to login with correct username / password.
3. The ` token is invalid ` window shows up.
4. Use will be redirect to the login portal after 
5. k8s log and portal error UI are depicted below
![error1](https://user-images.githubusercontent.com/3213161/126116158-b8465679-2495-4329-be23-2da3ab5634f5.png)
![error2](https://user-images.githubusercontent.com/3213161/126116172-1ba93558-bb76-4714-a412-ec032d0c92b3.png)
[login_error.log](https://github.com/microsoft/pai/files/6838590/login_error.log)

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
v1.0.1
- Cloud provider or hardware configuration:
OpenStack VMs
- OS (e.g. from /etc/os-release):
ubuntu 16.04.6
- Kernel (e.g. `uname -a`):
 4.4.0-194-generic
- Others:

**Anything else we need to know**:
It is a sudden event. We can use the same username/password to login in the morning and then failed the same action in the afternoon.

**Comment by JosephKang** [comment]
I can create a maintain devbox container and the service pods are still alive.

The 'token error' status still exist after restarting rest-server, portal, pylon and grafana pod.

Could I to create a new admin user in devbox container to work-around the issue?

**Comment by hzy46** [comment]
You can delete the old user info by:

```
./paictl.py service delete -n rest-server
./paictl.py service start -n rest-server
```

Please notice it will remove all current user accounts, and set the admin user/password to the default one (specified in `services-configuration.yaml`).

**Comment by JosephKang** [comment]
> You can delete the old user info by:
> 
> ```
> ./paictl.py service delete -n rest-server
> ./paictl.py service start -n rest-server
> ```
> 
> Please notice it will remove all current user accounts, and set the admin user/password to the default one (specified in `services-configuration.yaml`).

Thanks to reply quickly.

Does the rest-server recreation action impact anything except recreate default user on web service?

Thanks again.

**Comment by hzy46** [comment]
All current user accounts will be deleted.

Jobs won't be affected.

**Comment by JosephKang** [comment]
@hzy46 

Thanks and it works.

I create another admin user on portal to avoid the situation happened again. 

The root cause for the `token invalid` error is still unknown.

**Comment by hzy46** [comment]
You can check the secrets in `pai-user-v2` namespace in Kubernetes if the issue happens again. We stored the user information there.

**Comment by JosephKang** [comment]
@hzy46 

Thanks a lot for your information. I saw several secrets in the pai-user-v2 namespace. How to check the validness of those secret/user account ?

**Comment by hzy46** [comment]
1. In pai-user-v2 namespace, the key of the secert is a hex encoding of the username. So you can use a hex decoder tool like https://www.convertstring.com/EncodeDecode/HexDecode to decode it.
2. The value of the secert contains the base64 encoding value of the user's password.
3. You can also check the tokens of the users in the secrets of the pai-user-token namespace.

**Comment by Binyang2014** [comment]
close this. Feel free to reopen

**Comment by Binyang2014** [comment]
close this. Feel free to reopen
