### ISSUE TITLE
Failed to start job due to failed scheduling 

### ISSUE THREAD

**Issue by edenbuaa** [microsoft/pai#5577]
**OpenPAI Environment**:
- OpenPAI version: v1.7.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

job pod can not be scheduled with the following event:

`0/2 nodes are available: 1 Insufficient memory, 1 Pod is waiting for preemptible or free resource to appear: have to use at least one bad node 1/xx.xx.xx.xx when scheduling in VC default, 1 node(s) didn't match node selector.
`
 
my k8s cluster has only one gpu node, and doesn't run other task. Any suggestions?

**Comment by siaimes** [comment]
The log shows that the memory you requested exceeds the quota, not the GPU.

**Comment by hzy46** [comment]
Looks like there are unhealthy nodes. Please use `kubectl get nodes` to check.

**Comment by edenbuaa** [comment]
@hzy46 The two of nodes( one master and  one worker) are all ready status.

**Comment by hzy46** [comment]
have to use at least one bad node 1/xx.xx.xx.xx when scheduling in VC default,

The message shows you have bad nodes. Can you restart hivedscheduler to have a try?

**Comment by hzy46** [comment]
And, please provide the log of "kubectl get node <your worker node name> -o yaml" and "kubectl describe node <your worker node name>"

**Comment by siaimes** [comment]
I have encountered this situation before. Assuming that my node has 16G memory, after deducting the system and k8s reservation, it is actually only about 15G. If you fill in 16G or close to 16G in `layout.yaml` or `services-configuration.yaml` , this error will be reported.

**Comment by edenbuaa** [comment]
@hzy46 `kubectl get node -o yaml`

apiVersion: v1
items:
- apiVersion: v1
  kind: Node
  metadata:
    annotations:
	  kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
	  volumes.kubernetes.io/controller-managed-attach-detach: "true"
	createionTimestamp: "2021-07-27T07:13:51Z"
	labels:
	  beta.kubernetes.io/arch: amd64
	  beta.kubernetes.io/os: linux
	  kubernetes.io/arch: amd64
	  kubernetes.io/hostname: master
	  kubernetes.io/os: linux
	  node-role.kubernetes.io/master: ""
	  pai-master: "true"
	  pai-worker: "false"
	name: master
	resourceVersion: "233495"
	selfLin: /api/v1/nodes/master
	uid: 65c55182-b920-4051-82b1-4de835570b8
  spec:
    podCIDR: 10.200.0.0/25
  status:
    addresses:
	- address: 10.10.47.1
	  type: InternalIP
	- address: master
	  type: Hostname
	allocatable:
	  cpu: 7800m
	  ephemeral-storage: "22024378332"
	  github.com/fuse: "110"
	  hugepages-1Gi: "0"
	  hugepages-2Mi: "0"
	  memory: 32344621Ki
	  pods: "110"
	capacity:
	  cpu: "8"
	  ephemeral-storage: 23897980Ki
	  github.com/fuse: "110"
	  hugepages-1Gi: "0"
	  hugepages-2Mi: "0"
	  memory: 32947012Ki
	  pods: "110"
	conditions:
	- lastHeartbeatTime: "2021-07-27T07:15:59Z"
	  lastTransitionTime: "2021-07-27T07:15:59Z"
	  message: Calico is running on this node
	  reason: CalicoIsUp
	  status: "False"
	  type: NetworkUnavailable
	- lastHeartbeatTime: "2021-07-29T03:11:23Z"
	  lastTransitionTime: "2021-07-27T07:13:47Z"
	  message: kubelet has sufficient memory available
	  reason: KubeletHasSufficientMemory
	  status: "False"
	  type: MemoryPressure
	- lastHeartbeatTime: "2021-07-29T03:11:23Z"
	  lastTransitionTime: "2021-07-27T07:13:47Z"
	  message: kubelet has no disk pressure
	  reason: KubeletHasNoDiskPressure
	  status: "False"
	  type: DiskPressure
	- lastHeartbeatTime: "2021-07-29T03:11:23Z"
	  lastTransitionTime: "2021-07-27T07:13:47Z"
	  message: kubelet has sufficient PID available
	  reason: KubeletHasSufficientPID
	  status: "False"
	  type: PIDPressure
	- lastHeartbeatTime: "2021-07-29T03:11:23Z"
	  lastTransitionTime: "2021-07-27T07:13:47Z"
	  message: kubelet has is posting ready status. AppArmor enabled
	  reason: KubeletReady
	  status: "True"
	  type: Ready
    daemonEndpoints:
      kubeletEndpoint:
        Port: 10250	  
	images:
	<...>
	nodeInfo:
	  architecture: amd64
	  bootID: ec7fs2c2-8d76-46bc-9f9c-2f11422dc720
	  containerRuntimeVersion: docker://18.6.1
	  kernelVersion: 4.4.0-112-generic
	  kubeProxyVersion: v1.15.11
	  kubeletVersion: v1.15.11
	  machineID: ba9e4caf3644c2984358f357f0ee123
	  operatingSystem: linux
	  osImage: Ubuntu 16.04.2 LTS
	  systemUUID: B68E45A1-180F-4775-9D35-83311Bf8932
apiVersion: v1
items:
- apiVersion: v1
  kind: Node
  metadata:
    annotations:
	  kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
	  volumes.kubernetes.io/controller-managed-attach-detach: "true"
	createionTimestamp: "2021-07-27T07:15:51Z"
	labels:
	  beta.kubernetes.io/arch: amd64
	  beta.kubernetes.io/os: linux
	  kubernetes.io/arch: amd64
	  kubernetes.io/hostname: worker
	  kubernetes.io/os: linux
	  pai-worker: "true"
	name: worker
	resourceVersion: "233496"
	selfLin: /api/v1/nodes/worker
	uid: e3da4965-7191-4b69-a94f-759ae33bd23
  spec:
    podCIDR: 10.200.0.128/25
  status:
    addresses:
	- address: 10.10.47.2
	  type: InternalIP
	- address: worker
	  type: Hostname
	allocatable:
	  cpu: 63900m
	  ephemeral-storage: "5981457513604"
	  github.com/fuse: "110"
	  hugepages-1Gi: "0"
	  hugepages-2Mi: "0"
	  memory: 527663108Ki
	  pods: "110"
	capacity:
	  cpu: "64"
	  ephemeral-storage: 6490296792Ki
	  github.com/fuse: "110"
	  hugepages-1Gi: "0"
	  hugepages-2Mi: "0"
	  memory: 528015508Ki
	  nvidia.com/gpu: "8"
	  pods: "110"
	conditions:
	- lastHeartbeatTime: "2021-07-28T07:15:59Z"
	  lastTransitionTime: "2021-07-27T07:15:59Z"
	  message: Calico is running on this node
	  reason: CalicoIsUp
	  status: "False"
	  type: NetworkUnavailable
	- lastHeartbeatTime: "2021-07-29T03:11:23Z"
	  lastTransitionTime: "2021-07-28T07:13:47Z"
	  message: kubelet has sufficient memory available
	  reason: KubeletHasSufficientMemory
	  status: "False"
	  type: MemoryPressure
	- lastHeartbeatTime: "2021-07-29T03:11:23Z"
	  lastTransitionTime: "2021-07-28T07:13:47Z"
	  message: kubelet has no disk pressure
	  reason: KubeletHasNoDiskPressure
	  status: "False"
	  type: DiskPressure
	- lastHeartbeatTime: "2021-07-29T03:11:23Z"
	  lastTransitionTime: "2021-07-28T07:13:47Z"
	  message: kubelet has sufficient PID available
	  reason: KubeletHasSufficientPID
	  status: "False"
	  type: PIDPressure
	- lastHeartbeatTime: "2021-07-29T03:11:23Z"
	  lastTransitionTime: "2021-07-28T07:13:47Z"
	  message: kubelet has is posting ready status. AppArmor enabled
	  reason: KubeletReady
	  status: "True"
	  type: Ready
    daemonEndpoints:
      kubeletEndpoint:
        Port: 10250	  
	images:
	<...>
	nodeInfo:
	  architecture: amd64
	  bootID: 3fd536cb-73a0-4199-a075-64bd93826664
	  containerRuntimeVersion: docker://18.6.1
	  kernelVersion: 4.4.0-131-generic
	  kubeProxyVersion: v1.15.11
	  kubeletVersion: v1.15.11
	  machineID: ba9e4caf3644c2984358f357f0ee123
	  operatingSystem: linux
	  osImage: Ubuntu 16.04.2 LTS
	  systemUUID: D6BF926C-8B8c-03E0-B211-D21D40F7FF1B
kind: List
metadata:
   resourceVersion: ""
   selfLin: ""

**Comment by edenbuaa** [comment]
@hzy46 It doesn't work after restart hivescheduer.  

@siaimes I also tried to use your solution, but it not work for me :(

**Comment by edenbuaa** [comment]
@hzy46 by the way, another question: Can we use different namespaces for specific job pods?

**Comment by hzy46** [comment]
@edenbuaa It is not supported yet.

From your log, the worker has the following allocatable resource:

```
Allocatable:
  cpu: 				 63900m
  ephemeral-storage: 5981457513604
  github.com/fuse: 	 110
  hugepages-1Gi: 	 0
  hugepages-2Mi: 	 0
  memory: 			 527663108Ki
```

What is your hived scheduler setting?

**Comment by edenbuaa** [comment]
@hzy46 ```

Q1:
hivescheduler:
    config: |
    physicalCluster:
        skuTypes:
            gputypes:
                    gpu: 1
                    cpu: 6
                    memory: 50000Mi
```

Q2:  what's the security isolation method between job pods if all the pods in one namespace?

**Comment by hzy46** [comment]
Q1: Please provide the full hived config, including the vc. You may use `kubectl logs` to see the log of hivedscheduler. If the problem is caused by over-setting memory or cpu, you can decrease the memory or cpu setting a little bit.

Q2:  Although the pods are in the same namespace, users cannot connect to other pods.

**Comment by edenbuaa** [comment]
@hzy46 thanks. Could you explain more detail about 'users cannot connect to other pods'?

**Comment by hzy46** [comment]
Hi edenbuaa, 

Suppossing user A submits job A, and user B submits job B. Job A launches pod A, and Job B launches pod B. User A can access pod A through SSH. However, he/she cannot connect to pod B from pod A.

**Comment by edenbuaa** [comment]
@hzy46 How to insure the pod A cannot connect pod B from itself?

**Comment by hzy46** [comment]
This kind of isolation is provided by k8s.

**Comment by siaimes** [comment]
@hzy46 Hi, zhiyuan, The concern of @edenbuaa may be correct.

![image](https://user-images.githubusercontent.com/34199488/128965471-f03f5b8b-08cb-4915-8af0-2c33ba570b5b.png)

`172.17.175.91:25996` and `172.17.175.91:28500` are jobs of different users on the same node.

**Comment by siaimes** [comment]
![image](https://user-images.githubusercontent.com/34199488/128969240-06218c0f-d126-408b-ad1b-812dbc85598a.png)

Furthermore, the jobs of different users on different machines can be ssh.

**Comment by siaimes** [comment]
But, this issue should be caused by the SSH plugin not k8s.

**Comment by siaimes** [comment]
I can see that there is a dev-box`s public key in `/root/.ssh/authorized_keys` in the container. If I remove the public key, the above problem will be solved.


A strange thing is that since the problem is that the container accidentally mounts the public key distributed by dev-box when the cluster is installed, the client should have its corresponding private key to connect. There is indeed an `id_rsa` in `/root/.ssh` in the container, but I opened `/root/.ssh/id_rsa` to view, the private key is different from the one in dev-box.

**Comment by siaimes** [comment]
In this way, I know that the solution should be to optimize the ssh plug-in so that it only mounts the public key submitted by the user and the public key provided in the job.

**Comment by siaimes** [comment]
> A strange thing is that since the problem is that the container accidentally mounts the public key distributed by dev-box when the cluster is installed, the client should have its corresponding private key to connect. There is indeed an `id_rsa` in `/root/.ssh` in the container, but I opened `/root/.ssh/id_rsa` to view, the private key is different from the one in dev-box.


After I removed the private key, the above problem can also be solved. So, why is there a private key that is not paired with the public key, but can be trusted? Furthermore, shouldn't this private key exist in the container?

**Comment by siaimes** [comment]
https://github.com/microsoft/openpai-runtime/blob/4ab72398d404ec8b18d0eace9a27d954f46404f7/src/plugins/ssh/sshd.sh#L48-L62

This issue is introduced here.
