### ISSUE TITLE
Dose openpai storage support oss?such as minio.

### ISSUE THREAD

**Issue by gaoyangcaiji** [microsoft/pai#5585]
my backhand storage is minio . i integrated minio to k8s with "csi-s3". After me  create a pvc,i want Assign Storage to PAI Groups,there's a error happened  "Invalid storage server type"

so how can i to solve the problem

**Comment by hzy46** [comment]
Which PAI version does you use? I think we support PVC mounting in the latest version.

**Comment by gaoyangcaiji** [comment]
@hzy46  my version is v1.7.0

**Comment by gaoyangcaiji** [comment]
my csi driver named "ch.ctrox.csi.s3-driver".I have readed the openpai sourcecode,  should  i change the name "ch.ctrox.csi.s3-driver"  to  "dshuttle"?@hzy46

**Comment by hzy46** [comment]
Dshuttle doesn't have relation with your issue. Your storage type will be unknown .

Please check the code here: https://github.com/microsoft/pai/blob/7cf1ae351dd15d7228d2675212c1036c0aea8745/src/rest-server/src/models/v2/storage.js#L101-L103

**Comment by gaoyangcaiji** [comment]
no,my storage type will be "",because    pv.spec.csi.driver === 'ch.ctrox.csi.s3-driver' , the "ch.ctrox.csi.s3-driver" is my custom  CSI plugin.  What confuses me is that “dshuttle” is also a csi plugin? So I'm not sure if I changed the name of the csi plugin from “ch.ctrox.csi.s3-driver”  to  "dshuttle",i will solve my probelm. @hzy46

**Comment by gaoyangcaiji** [comment]
@hzy46 ok ,thank you very much. I will try.

**Comment by Binyang2014** [comment]
Close it, free feel to reopen
