### ISSUE TITLE
Request support deployment and services do not rely on the Internet.

### ISSUE THREAD

**Issue by siaimes** [microsoft/pai#5596]
**What would you like to be added**:

Request support deployment and services do not rely on the Internet.

**Why is this needed**:

1. In mainland China, gcr.io is inaccessible, Github is unstable, and nvidia.github.io in many areas suffers from DNS pollution.
2. The intranet of some enterprises is isolated from the Internet for the protection of intellectual property.

**Without this feature, how does the current module work**:

Now, the deployment of OpenPAI, service startup, and jobs startup all rely heavily on the network. This causes the OpenPAI of users with the above-mentioned issue 1 to be very unstable, and the users with the above-mentioned issue 2 cannot use OpenPAI.

**Components that may involve changes**:

1. Apt related: we need to start a mirror on the LAN and modify the apt source of all nodes in the cluster accordingly.
2. Releases and Images: all release files and images are provided with offline zip packages and loaded using ansible-playbook.
3. Network file related: Store the related files required by the service in the node in advance, and modify the related code to use local files.
4. User image related: Provide a debugging environment that allows users to install the software in the container, and then save the container as an image for subsequent use.
5. .........

**Comment by mtzfei** [comment]
+1
