### ISSUE TITLE
Is it possbile to make personal storage within group

### ISSUE THREAD

**Issue by edenbuaa** [microsoft/pai#5606]
**OpenPAI Environment**:
- OpenPAI version: v1.7
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

I created a nfs pv/pvc and set the `share:"false"` label to pvc. then all the user can use this pvc as their personal storage. Cloud I use the personal storage only for one group?

**Comment by siaimes** [comment]
```
{
  "data": {
    "groupname": "rtx2080ti",
    "extension": {
      "acls": {
        "storageConfigs": ["rtx2080ti"],
        "admin": false,
        "virtualClusters": ["rtx2080ti"]
      }
    }
  },
  "patch": true
}
```

**Comment by edenbuaa** [comment]
@siaimes I mean,  using the `personal storage`  within group.

**Comment by siaimes** [comment]
@edenbuaa I know what your mean, I also thought you would know what I meant by that piece of code.

Just change `data.groupname` and `data.extension.acls.virtualClusters` to your group name, then push the configure to rest server, also you need to revoke previse pushed configure from default group.

Push `nfs-storage` to group `rtx2080ti`:

```
{
  "data": {
    "groupname": "rtx2080ti",
    "extension": {
      "acls": {
        "storageConfigs": ["nfs-storage"],
        "admin": false,
        "virtualClusters": ["rtx2080ti"]
      }
    }
  },
  "patch": true
}
```

revoke `nfs-storage` from default group:
```
{
  "data": {
    "groupname": "default",
    "extension": {
      "acls": {
        "storageConfigs": [],
        "admin": false,
        "virtualClusters": ["default"]
      }
    }
  },
  "patch": true
}
```
then, just users in group rtx2080ti can use this `nfs-storage`.

**Comment by edenbuaa** [comment]
@siaimes great, thanks.
