### ISSUE TITLE
After openpai restart，WebPortal API Request 502

### ISSUE THREAD

**Issue by EdwardNewgate1** [microsoft/pai#5607]
Restart the whole cluster, and then  WebPortal API Request 502
```bash
# restart cluster
./paictl.py service stop
./paictl.py service start
```

**Comment by suiguoxin** [comment]
> Restart the whole cluster, and then WebPortal API Request 502
> 
> ```shell
> # restart cluster
> ./paictl.py service stop
> ./paictl.py service start
> ```

@EdwardNewgate1 Hi, could you please check if the `webportal` & `rest-server` docker containers are running ? And please check the logs if possible

**Comment by Binyang2014** [comment]
Close this. Free feel to reopen
