### ISSUE TITLE
About hard disk usage restrictions

### ISSUE THREAD

**Issue by GuoYingLong** [microsoft/pai#5611]
- OpenPAI version: v1.7.0

Does openpai not limit the size of the disk? After the disk exceeds the limit, the job fails.

![image](https://user-images.githubusercontent.com/40883280/131315148-1d39c2e8-a99f-4de3-b798-79d8d93ae192.png)
![image](https://user-images.githubusercontent.com/40883280/131315195-182a9d0a-6e53-4f7e-8e22-9e08c512a548.png)

The data is not stored in the storage, which will lead to the loss of user data

**Comment by siaimes** [comment]
OOMKill refers to the memory exceeding the quota, not the hard disk.

**Comment by GuoYingLong** [comment]
I used the dd command to test at the time. I ran a dd command without running other software.

**Comment by Binyang2014** [comment]
Please refer https://serverfault.com/questions/516074/why-are-applications-in-a-memory-limited-lxc-container-writing-large-files-to-di. In Linux, write to disk will cached in memory first.
