### ISSUE TITLE
How can I deploy OpenPAI on single-box?

### ISSUE THREAD

**Issue by hlyf-xs** [microsoft/pai#5613]
**Organization Name**:

**Short summary about the issue/question**:

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by Binyang2014** [comment]
Sorry, we don't support deploy openPAI in single box yet
