### ISSUE TITLE
Problems about Job transfer.

### ISSUE THREAD

**Issue by siaimes** [microsoft/pai#5619]
**Organization Name**:

**Short summary about the issue/question**:
When the virtual clusters of the two clusters are not the same configuration (CPU, GPU, memory), job transfer may fail or the job cannot be started.
**Brief what process you are following**:
1. When the node names of the two clusters are inconsistent, it will fail:
![image](https://user-images.githubusercontent.com/34199488/133605311-c2cb9d7e-3cfb-450d-9cc8-b62724a4ad24.png)

2. When the SKU of the target virtual cluster is different from the current virtual cluster, the task will not apply for a resource as large as just one SKU. At this time, if the quota of the target virtual cluster is smaller, the task cannot be started, and if the quota of the original virtual cluster is smaller, the resource utilization rate will decrease:
![image](https://user-images.githubusercontent.com/34199488/133615113-597f9717-f243-4e79-b9cb-d313954d50e8.png)

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version: v1.8.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:
Where is the problem: Job transfer just change `defaults.virtualCluster` failed of YAML, in my opinion, it should modify  `taskRoles.taskrole.resourcePerInstance` and `extras.hivedScheduler.taskRoles.taskrole.skuType` correspondingly based on the information of the target virtual cluster.

**Comment by Binyang2014** [comment]
@hzy46 Can you help to take a look?

**Comment by hzy46** [comment]
Hi @siaimes, job transfer will not look at the skuType in the target cluster. It is by design. The reason is: If we consider the skuType transformation, sometimes it will be very complex and hard to understand e.g. there're multiple skuTypes in both the job and the target cluster.

I don't quite under the other question:

```
When the SKU of the target virtual cluster is different from the current virtual cluster, the task will not apply for a resource as large as just one SKU. At this time, if the quota of the target virtual cluster is smaller, the task cannot be started, and if the quota of the original virtual cluster is smaller, the resource utilization rate will decrease:
```

Could you please describe it in detail or by example?

**Comment by siaimes** [comment]
@Binyang2014 @hzy46 Thank you for your reply.

Source job SKU: `gpu-machine-k80 (1 GPU, 6 CPU, 73994 memory)`
Target job SKU: `gpu-machine-titanxp (1 GPU, 6 CPU, 28672 memory)`

Then, this Job transfer process will fail, see figure 1 of this issue.

Source job SKU: `gpu-machine-titanxp (1 GPU, 6 CPU, 61440 memory)`
Target job SKU: `gpu-machine-titanxp (1 GPU, 6 CPU, 28672 memory)`

Then this Job transfer process will succeed, but the target job will not be start up, see figure 2 for detail.


Source job SKU: `gpu-machine-titanxp (1 GPU, 6 CPU, 28672 memory)`
Target job SKU: `gpu-machine-titanxp (1 GPU, 6 CPU, 61440 memory)`

Then this Job transfer process will succeed, but the target job will meet OOMKill because it only applies 28672 of 61440 memory.

**Comment by hzy46** [comment]
If you use SKU, the memory and CPU request should be omitted. So I think it shouldn't happen. Could you share with us:

  - The job config 
  - The hivedconfig of the source cluster and target cluster

**Comment by siaimes** [comment]
@hzy46 Solved, thank you.

1. Must manually modify the `hiddenScheduler.taskRoles.taskrole.skuType` field in the `yml` file;
2. Maybe it was a problem with my previous operation, which can no longer be reproduced now.
