### ISSUE TITLE
different user can not submit the job with same jobname, and the job is not deleted when the user delete.

### ISSUE THREAD

**Issue by feng257** [Microsoft/pai#562]
As the title says, 
1. I submitted the jobs with same jobname but belong to different user, PAI throws "duplicated job" error.  
2. I delete the user, but find out the job which submitted by the user is not deleted.
I think user name and job name should be combined as a keyword for job, instead of only job name. And when the user has been deleted, all information of the user should be deleted.

**Comment by fanyangCS** [comment]
We are aware of this issue. We have introduced a concept: "namespace". Each user can only submit the job under the user's own namespace. This way, it is fine for different user to submit a job with the same name. 
The feature has been implemented by this [PR ](https://github.com/Microsoft/pai/pull/320) but it is disabled for now. We will enable this feature by default once it's been tested.
