### ISSUE TITLE
always get this  error: fatal: [pai-worker1]: FAILED! => {"changed": false, "msg": "The following requirements are not met: The default runtime is not set correctly"}

### ISSUE THREAD

**Issue by poetryben88** [microsoft/pai#5622]
when I install  quick-start-kubespray.sh, always get this error:

TASK [display unmet requirements] ************************************
fatal: [pai-worker1]: FAILED! => {"changed": false, "msg": "The following requirements are not met: The default runtime is not set correctly"}
skipping: [pai-master]
skipping: [localhost]

PLAY RECAP *****************
localhost                  : ok=11   changed=0    unreachable=0    failed=0    skipped=7    rescued=0    ignored=0
pai-master                 : ok=20   changed=0    unreachable=0    failed=0    skipped=13   rescued=0    ignored=0
pai-worker1                : ok=28   changed=0    unreachable=0    failed=1    skipped=15   rescued=0    ignored=0

who know how to solve it?

pai-worker1 is GPU worker, and 【nvidia-smi】 is ok.
【sudo docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi】 is also  OK!

/etc/docker/daemon.json
{
    "runtimes": {
        "nvidia": {
            "path": "/usr/bin/nvidia-container-runtime",
            "runtimeArgs": []
        }
    }
}

**Comment by siaimes** [comment]
[https://openpai.readthedocs.io/en/pai-1.8.y/manual/cluster-admin/installation-faqs-and-troubleshooting.html](https://openpai.readthedocs.io/en/pai-1.8.y/manual/cluster-admin/installation-faqs-and-troubleshooting.html)

![image](https://user-images.githubusercontent.com/34199488/135953128-ece6aeb3-86ed-4429-bf1d-a5091cebc03c.png)
