### ISSUE TITLE
Deploying on a private cloud

### ISSUE THREAD

**Issue by graham-brian-chapman** [Microsoft/pai#5630]
Hi!

**Short summary about the issue/question**:

I'm trying to install PAI on a private cloud. All machines (i.e. devbox, master, worker) in this private cloud have internal IPs which they can use to talk to each other inside the private network. The internal IP from the master is printed at the end of the `quick-start-service.sh` script:

`You can go to http://xxx.xx.xx.xxx, then use the default username and password to log in.`

However, this internal IP *can't* be used to access the cluster from outside of the private network. When I replace the internal IP of the master with it's external one, I am able to access the webportal. However, I can't login, as the REST API call to validate the user credentials is calling the internal IP of the master again.

Using the _external_ IP of the master in the `config/layout.yaml` during installation results in an `ip in ansible_all_ipv4_addresses` violation and error. So currently, I'm using the _internal_ IPs for all machines in the `config/layout.yaml`.

What can I do? Help would be highly appreciated!

**Brief what process you are following**: Official guide for initial deployment

**OpenPAI Environment**:
- OpenPAI version: 1.8
- Cloud provider or hardware configuration: Private OpenStack cloud
- OS (e.g. from /etc/os-release): Ubuntu 20
- Kernel (e.g. `uname -a`): `Linux pai-devbox 5.4.0-86-generic #97-Ubuntu SMP Fri Sep 17 19:19:40 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by siaimes** [comment]
My solution is to start another Nginx to listen to the Internet IP and reverse proxy to the internal IP.

**Comment by graham-brian-chapman** [comment]
Hi @siaimes,

thanks for your input. So, if I understood correctly, you would then also specify the Internet IP in the `config/layout.yaml`, and because of the reverse proxy with Nginx, the ansible error I described above won't occur?

**Comment by siaimes** [comment]
> Hi @siaimes,
> 
> thanks for your input. So, if I understood correctly, you would then also specify the Internet IP in the `config/layout.yaml`, and because of the reverse proxy with Nginx, the ansible error I described above won't occur?


The deployment of Nginx is independent of the cluster.

But with the help of this [PR](https://github.com/microsoft/pai/pull/5495), you can deploy Nginx on the master node.
