### ISSUE TITLE
What's the difference between prod and oppo of the JobPriorityClass ?

### ISSUE THREAD

**Issue by JohanOu** [microsoft/pai#5644]
**Short summary about the issue/question**:
The JobPriorityClass has 4 built-in values: Product,Test,Opportunistic,default.What's the difference？
![image](https://user-images.githubusercontent.com/64004740/139585953-eb719def-f7bb-4889-8d56-91f68ffc89e6.png)

**Comment by Binyang2014** [comment]
It's the concept of hived, Please refer to https://github.com/microsoft/hivedscheduler/blob/66f26ac47b/example/feature/README.md#opportunistic-job for more details
