### ISSUE TITLE
Stdout: Not Found

### ISSUE THREAD

**Issue by poetryben88** [microsoft/pai#5650]
I submit a job, but not any job  be running. The only stdout is : not found.    @ @

![image](https://user-images.githubusercontent.com/15098245/140920172-e44afa58-12a5-4372-bf32-7041f8a1ce2c.png)

![image](https://user-images.githubusercontent.com/15098245/140920233-90b60779-caa4-4e4b-bca7-1cdd1868cb43.png)

**Comment by Binyang2014** [comment]
Please go to `Show all logs` to get more info
![image](https://user-images.githubusercontent.com/9415966/141416125-20be3076-c3ac-485d-95f5-71d54b617474.png)

**Comment by Binyang2014** [comment]
Close since no update for 30 days
