### ISSUE TITLE
How many machines can be supported at most？

### ISSUE THREAD

**Issue by goatbjh** [microsoft/pai#5655]
Hello, we now want to expand the cluster node, how many machines can 0.14.0 maximum support? Can I support more than 700 nodes? Can the latest version support more? Thanks!

**Organization Name**:

**Short summary about the issue/question**:

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version: 0.14.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by Binyang2014** [comment]
We have an internal bed which hosts more than 200 nodes. We don't test 700 nodes scale. 
It depends on many things such as k8s scalabilities, machine performance and the  max number of your active jobs.
