### ISSUE TITLE
Problems of v1.8.0

### ISSUE THREAD

**Issue by wangxianglang** [microsoft/pai#5661]
When I install v1.8.0 on ubuntu20.04, I encounter the following problem:

"msg": "E:Conflicting values set for option Signed-By regarding source https://download.docker.com/linux/ubuntu/ focal: /usr/share/keyrings/docker-archive-keyring.gpg != , E:The list of sources could not be read.

**OpenPAI Environment**:
- OpenPAI version: 1.8.0
- OS (e.g. from /etc/os-release): ubuntu20.04

**Anything else we need to know**:
anybody who knows how to solve the problem？

**Comment by siaimes** [comment]
Delete the apt list and key that you added when you installed docker. Because the script will be added again when installing k8s, which will cause conflicts.
