### ISSUE TITLE
stdout & stderr of  job details : Log folder can not be retrieved

### ISSUE THREAD

**Issue by wangxianglang** [microsoft/pai#5665]
**Short summary about the issue/question**:

The  stdout & stderr page of submitted job (success or failed job)  shows:  Log folder can not be retrieved
And when clicking the Stdout or Stderr, the response is slow (it takes about few minutes).

**OpenPAI Environment**:
- OpenPAI version: v1.8.0
- OS (e.g. from /etc/os-release): Ubuntu 20.04 LTS

![image](https://user-images.githubusercontent.com/41845679/143597583-456c38d0-718c-4b90-a545-21f17793d031.png)

**Anything else we need to know**:

**Comment by hzy46** [comment]
Hi @wangxianglang , could you please follow the steps below and paste your log?

1. Use `F12` to open debug console.
2. Clear existing log in the `Network` and `Console` tab.
3. Click the button to show the log.
4. In the `network` tab, you can see a request. Please paste the request (including the url) and the response here. If there's any error in the `console` tab, please paste it, too.

**Comment by wangxianglang** [comment]
> Hi @wangxianglang , could you please follow the steps below and paste your log?
> 
> 1. Use `F12` to open debug console.
> 2. Clear existing log in the `Network` and `Console` tab.
> 3. Click the button to show the log.
> 4. In the `network` tab, you can see a request. Please paste the request (including the url) and the response here. If there's any error in the `console` tab, please paste it, too.

I got a 502 error
![image](https://user-images.githubusercontent.com/41845679/143799910-38b7cc9c-b3a3-40c4-8c5f-6ef89c8fa685.png)

![image](https://user-images.githubusercontent.com/41845679/143799979-257540e7-6229-4408-b495-fa173ab5e867.png)

**Comment by Binyang2014** [comment]
@wangxianglang Can you check the `log-manager` status? Please run `kubectl  get po | grep log-manager` in your dev-box and check if all log-manager is running correctly.
If some container is crashed, please provide the related logs for log-manager.

**Comment by wangxianglang** [comment]
> 

I just checked the log-manager status, it seems that nothing wrong with it.
![image](https://user-images.githubusercontent.com/41845679/143801766-5825294e-ebcc-46da-b6bd-b00a7919198e.png)

I checked the logs of rest-server container. and there is a ETIMEDOUT error.
2021-11-29T02:32:08.607Z [ERROR] Got error when retrieving log list, error: Error: connect ETIMEDOUT 10.126.56.9:9103

**Comment by Binyang2014** [comment]
Can you provide logs from `log-manager`, And check if folder `/usr/local/pai/logs` exists inside the log-manger. 
And please check if you can access 10.126.56.9:9103 from the master node. Seems there is network issue between master node and 10.126.56.9

**Comment by wangxianglang** [comment]
> Can you provide logs from `log-manager`, And check if folder `/usr/local/pai/logs` exists inside the log-manger. And please check if you can access 10.126.56.9:9103 from the rest-server container. Seems there is network issue between rest-server and node manager in 10.126.56.9. You can use `curl 10.126.56.9:9103/healthz` to check the network is OK.
> 
> **You need to check the network issue inside the rest-server container, not in the node**


Here's log from `log-manager` container in node `10.126.56.9`.
10.126.56.9 - - [29/Nov/2021:05:57:44 +0000] "GET /healthz HTTP/1.1" 200 18 "-" "kube-probe/1.15"
10.126.56.9 - - [29/Nov/2021:05:58:44 +0000] "GET /healthz HTTP/1.1" 200 18 "-" "kube-probe/1.15"
10.126.56.9 - - [29/Nov/2021:05:59:44 +0000] "GET /healthz HTTP/1.1" 200 18 "-" "kube-probe/1.15"
10.126.56.9 - - [29/Nov/2021:06:00:44 +0000] "GET /healthz HTTP/1.1" 200 18 "-" "kube-probe/1.15"
10.126.56.9 - - [29/Nov/2021:06:01:44 +0000] "GET /healthz HTTP/1.1" 200 18 "-" "kube-probe/1.15"
10.126.56.9 - - [29/Nov/2021:06:02:44 +0000] "GET /healthz HTTP/1.1" 200 18 "-" "kube-probe/1.15"
10.126.56.9 - - [29/Nov/2021:06:03:44 +0000] "GET /healthz HTTP/1.1" 200 18 "-" "kube-probe/1.15"
10.126.56.9 - - [29/Nov/2021:06:04:44 +0000] "GET /healthz HTTP/1.1" 200 18 "-" "kube-probe/1.15"

`curl 10.126.56.9:9103/healthz` in the `rest-server` container :
url: (7) Failed to connect to 10.126.56.9 port 9103: Connection timed out
`ping 10.126.56.9` is ok in the  `rest-server` container  so it seems the port 9103 is unreachable

**Comment by wangxianglang** [comment]
> 
And the folder /usr/local/pai/logs and related task info exist inside the log-manger

**Comment by Binyang2014** [comment]
Can you check why port `9103 ` is unreachable? Please make sure the node-manage is using default port number and the port is mark as hostPort.
 Refer these lines for details. Make sure the hostPort number is 9103
https://github.com/microsoft/pai/blob/ea19af183e1a5e26ccd9fc2a410ffefd6ada9d52/src/log-manager/deploy/log-manager.yaml.template?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L65-L67

**Comment by wangxianglang** [comment]
> Can you check why port `9103 ` is unreachable? Please make sure the node-manage is using default port number and the port is mark as hostPort. Refer these lines for details. Make sure the hostPort number is 9103 https://github.com/microsoft/pai/blob/ea19af183e1a5e26ccd9fc2a410ffefd6ada9d52/src/log-manager/deploy/log-manager.yaml.template?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L65-L67

My ip range is `x.xxx.xx.2` -- `x.xxx.xx.14`
I use `curl x.xxx.xx.x:9103/healthz` to check all `log manager` services.
I found `log-manager` of the `x.xx.xxx.2` and `x.xx.xxx.14` is ok .  Other machines can only get `Log manager ready.` from localhost.
But..... I don't know what's going wrong with my network

**Comment by Binyang2014** [comment]
So this issue not related to PAI service. If `curl x.xxx.xx.x:9103/healthz` works in master node but not in container, then it's container network issue. Otherwise it's host network issue.
For container network issue, you can check IPtables and docker doc for troubleshooting.
For host network issue,  you maybe need to check the firewall and some network config.

Close it since it not related to OpenPAI. Feel free to reopen if need other help.
