### ISSUE TITLE
Is it possible to assign different nodeport range for different nodes in the cluster?

### ISSUE THREAD

**Issue by RomanShen** [microsoft/pai#5666]
**Organization Name**:

NJUST

**Short summary about the issue/question**:

We’re having four gpu workers in the cluster whose IP addresses are assigned by the router (wan: 192.10.10.10, lan: 10.1.1.1). 

For example, 1080 on host 10.1.1.11, 1080ti on host 10.1.1.12, etc. When a user commit a job using 1080, pai will return the ssh info in a format of 10.1.1.11:random_port. 

We need to use l2tp (l2tp service on the router) in order to connect to the container with ssh using 10.1.1.11:random_port, because we are in the same local network of router (192.10.10.10). 

Is it possible to restrict the node port range of different worker so that we can do a port forwarding from 192.10.10.10:port to worker_ip:port. 

For example, for 1080 with internal IP address 10.1.1.11, can we restrict 1080 worker using ports 30000-30100, so that the router knows to forward 192.10.10.10:30000-30100 to 10.1.1.10. In the end, the router forward different ranges of ports to different workers and we can connect the container without using l2tp.

 Thanks. 

**OpenPAI Environment**: v1.8.0
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by siaimes** [comment]
It may not be possible at the moment. In order to reduce conflicts as much as possible, the port is completely randomly generated.

**Comment by RomanShen** [comment]
> It may not be possible at the moment. In order to reduce conflicts as much as possible, the port is completely randomly generated.

Okay. Thanks!
