### ISSUE TITLE
502 Bad Gateway when access http://masterip,pylon logs connection time out

### ISSUE THREAD

**Issue by JohanOu** [microsoft/pai#5669]
**Short summary about the issue/question**:
After I installed openpai,I try to access http://master_ip,but it return a 502 Bad Gateway,http://master_ip:9286 can return a static html.
**Brief what process you are following**:
![35f613b84157d5dc8e7d0621d25981e](https://user-images.githubusercontent.com/64004740/144707482-42e57495-ee7e-4dbc-9d71-06e2c96bff3e.png)

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:v1.8.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):Ubuntu 20.04
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by Binyang2014** [comment]
Can you access `http://master_ip:9286` inside pylon container?  You can try to change pylon to use hostNetwork, this may solve the problem.

**Comment by JohanOu** [comment]
> Can you access `http://master_ip:9286` inside pylon container? You can try to change pylon to use hostNetwork, this may solve the problem.

How to change the pylon Network Mode?I try to change the hostconfig.json:NetworkMode of pylon container,it doesn't flush,i restart the container,it regain to the default NetworkMode

**Comment by Binyang2014** [comment]
Please run: `kubectl edit ds pylon-ds`. Update the k8s daemonset config to change the netowork mode

**Comment by JohanOu** [comment]
> Please run: `kubectl edit ds pylon-ds`. Update the k8s daemonset config to change the netowork mode

it works.But when I apply for 1 gpu sku,I can use all gpu in the container,why?
I had installed a same v1.8.0 opanpai in another cluster,it can seperate gpu
