### ISSUE TITLE
GPU seperate doesn't work

### ISSUE THREAD

**Issue by JohanOu** [microsoft/pai#5672]
**Short summary about the issue/question**:
when I apply for 1 gpu sku,I can use all gpu in the container,why?
For example:I use nvidai-smi in command,it will print all gpu information.
I had installed a same v1.8.0 opanpai in another cluster,it can seperate gpu.
**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:v1.8.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Comment by JohanOu** [comment]
> **Short summary about the issue/question**: when I apply for 1 gpu sku,I can use all gpu in the container,why? For example:I use nvidai-smi in command,it will print all gpu information. I had installed a same v1.8.0 opanpai in another cluster,it can seperate gpu. **Brief what process you are following**:
> 
> **How to reproduce it**:
> 
> **OpenPAI Environment**:
> 
> * OpenPAI version:v1.8.0
> * Cloud provider or hardware configuration:
> * OS (e.g. from /etc/os-release):
> * Kernel (e.g. `uname -a`):
> * Hardware (e.g. core number, memory size, storage size, GPU type etc.):
> * Others:

I see environment "NVIDIA_VISIBLE_DEVICES=all" when docker inspect container

**Comment by Binyang2014** [comment]
Sorry for late response. Can you run `printenv` inside the container and paste the result here? And please make sure you use the nvidia-runtime not default runc for docker daemon.
