### ISSUE TITLE
How to exclude the waiting time from the job duration time

### ISSUE THREAD

**Issue by zhangxydlut** [microsoft/pai#5673]
Just a question: 
    I noticed that the duration time of the jobs is counted right after the job is created. But I'm more interested in how long the job is running. Is there any way to exclude the waiting time from the duration time? Thanks

**Comment by Binyang2014** [comment]
From PAI rest API, there is two field: `currentAttemptCreatedTime` and `currentAttemptLaunchedTime`. The `currentAttemptLaunchedTime` is the timestamp job starts to run. You can use `currentAttemptCompletedTime` - `currentAttemptLaunchedTime` to get the running time

**Comment by zhangxydlut** [comment]
Got it! Great thanks! In addition, I hope these information can be viewed more conveniently if possible. Thanks again!

**Comment by siaimes** [comment]
![image](https://user-images.githubusercontent.com/34199488/146384165-34d99e6f-30e1-4f67-a310-f485d24aa150.png)

Is this what you need?

**Comment by zhangxydlut** [comment]
> ![image](https://user-images.githubusercontent.com/34199488/146384165-34d99e6f-30e1-4f67-a310-f485d24aa150.png)
> 
> Is this what you need?

Yes! It's my fault for not noticing this page. Thanks!
