### ISSUE TITLE
can I use external website as webportal plugin?

### ISSUE THREAD

**Issue by HaoLiuHust** [microsoft/pai#5771]
**Organization Name**:

**Short summary about the issue/question**:
for example, I have a external website to do training visualization, can I use this site url as webportal plugin ? according to the document, webportal plugin can set with absolute url. But when I set it in config, webportal can not show plugin

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version: v1.8.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by hlyf-xs** [comment]
I also meet the problem, have you solved it yet?

**Comment by HaoLiuHust** [comment]
> I also meet the problem, have you solved it yet?

no, I am not famillar with frontend, I am not sure whether the web plugin can do this.. so I gave up to try it
