### ISSUE TITLE
can not  use curl to access api, it returns"UnauthorizedUserError"

### ISSUE THREAD

**Issue by jdl3000** [microsoft/pai#5782]
**OpenPAI Environment**: kubernetes
- OpenPAI version: V1.7.0
my k8s  environment is below:
![image](https://user-images.githubusercontent.com/27041487/170819501-26940ec0-6c44-48bc-a3e2-1cbab18ea0ad.png)

after I deployed opnepai in k8s, I want to set PVC storage  for VC,so I use curl to access the api, the token for admin user is from dashboard, it turns out below:

![image](https://user-images.githubusercontent.com/27041487/170819603-01465202-a290-45cc-a1d1-ca8adc8357e2.png)
and if i use admin user and it's password,it turns out below:
![image](https://user-images.githubusercontent.com/27041487/170819675-858398b3-c53d-4430-b76e-5366937efc21.png)

anybody knows how to deal with it please help me ,If I did not give some useful message ,you can contact me , I will continue focus on this

**Comment by Binyang2014** [comment]
![image](https://user-images.githubusercontent.com/9415966/170936888-24b8a0cc-7192-41c5-a9f3-121b9f58c289.png)

Please make sure you can admin user. You can get the token under Application->Cookies. And the `admin` field should be true

**Comment by jdl3000** [comment]
finall I figure out it，here is the solution below
1. find the rest-server service port
 kubectl describe  pods rest-server-ds-rvqlk
![image](https://user-images.githubusercontent.com/27041487/172774674-c2f510ba-e759-4d93-a439-458d0ae4221f.png)
2. curl the api server with the port number
 curl -X PUT 192.168.13.160:9186/api/v2/groups
