### ISSUE TITLE
[feature request] Mapping HDFS into docker container per job

### ISSUE THREAD

**Issue by chivee** [Microsoft/pai#586]
Hi Pai,

Thanks again for your great work. could you please add the feature that automatically mapping $some_dir to the hdfs so that any program could access hdfs without HDFS knowledge?

Qiwei

**Comment by fanyangCS** [comment]
You can do that by customizing a docker image. [here ](https://github.com/Microsoft/pai/blob/master/job-tutorial/Dockerfiles/cuda8.0-cudnn6/Dockerfile.run.cntk) is an example of using hdfs mount to do that.
However, our experience shows hdfs mount is not stable enough. It is recommended to use native hdfs reader/writer for the hdfs access.

An alternative is to deploy an NFS (or other file system like FS) server on your own and mount to the NFS from inside the docker instance.
