### ISSUE TITLE
run job fail if cluster no gpu when skip Hadoop-AI during installation

### ISSUE THREAD

**Issue by ueqt** [Microsoft/pai#592]
In document it said use Hadoop-AI can ignore, if not use Hadoop-AI, it will use hadoop-2.7.2, so I installed without Hadoop-AI, everything works great, but when I submit job, and run it, it failed, and said `this hadoop library doesn't support Port scheduling, please use the hadoop-AI library`, can I run job without GPU?

```
Start Time: 5/21/2018, 4:12:15 PM

Finish Time: 5/21/2018, 4:12:28 PM

Exit Diagnostics:


[ExitStatus]: AM_INTERNAL_NON_TRANSIENT_ERROR
[ExitCode]: 184
[ExitDiagnostics]:
AM internal non-transient error
[ExitType]: NON_TRANSIENT
________________________________________________________________________________________________________________________________________________________________________________________________________
[ExitCustomizedDiagnostics]:
NonTransientException occurred in com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster. Framework will be stopped.
Exception:
com.microsoft.frameworklauncher.common.exceptions.NonTransientException: this hadoop library doesn't support Port scheduling, please use the hadoop-AI library
at com.microsoft.frameworklauncher.applicationmaster.RequestManager.checkHadoopLibrary(RequestManager.java:249)
at com.microsoft.frameworklauncher.applicationmaster.RequestManager.pullRequest(RequestManager.java:195)
at com.microsoft.frameworklauncher.applicationmaster.RequestManager.recover(RequestManager.java:122)
at com.microsoft.frameworklauncher.common.service.AbstractService.start(AbstractService.java:38)
at com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster.recover(ApplicationMaster.java:195)
at com.microsoft.frameworklauncher.common.service.AbstractService.start(AbstractService.java:38)
at com.microsoft.frameworklauncher.applicationmaster.Bootstrap.main(Bootstrap.java:23)
```

ps. old version support only cpu, and submit job can work, I think maybe current version is not tested on only cpu env.

**Comment by yqwang-ms** [comment]
Sorry for this breaking change. 
It is because in current PAI, a default port request for ssh will be made when submit job. But your local hadoop does not support Port scheduling.
We will make a fix in future release: if your local hadoop does not support Port scheduling, we will just random a port for ssh. So, the ssh port conflict rate is increased, but should be still very small.

**Comment by yqwang-ms** [comment]
For now, you can use Hadoop-AI also supports no gpu cluster, but it is more compatible with PAI. So, even we support other version hadoop, it would be better to use Hadoop-AI.

**Comment by ueqt** [comment]
Ok, I've tried Hadoop-AI, and it works. Thanks.

**Comment by scarlett2018** [comment]
Hadoop-AI is needed for current design, @qinchen123 to verify whether documentation are updated with this pre-requisite.

**Comment by fanyangCS** [comment]
we have update the doc accordingly.
