### ISSUE TITLE
watch disk usage on host machine

### ISSUE THREAD

**Issue by fanyangCS** [Microsoft/pai#606]
better alert when usage is close to full

**Comment by ydye** [comment]
Can we add logic to triggle email-alerts on prom?

**Comment by xudifsd** [comment]
`node_filesystem_avail_bytes` already exported via node-exporter, for example in [INT bed](http://10.151.40.234:9091/graph?g0.range_input=15m&g0.expr=node_filesystem_avail_bytes&g0.tab=0).

**Comment by xudifsd** [comment]
closed as already solved in above PR.
