### ISSUE TITLE
manage hdfs folder in a more structured way

### ISSUE THREAD

**Issue by fanyangCS** [Microsoft/pai#607]
an example: introduce an environment variable $PAI_HOME to each user, who only has the permission to write to $PAI_HOME

**Comment by jingruhou** [comment]
请问这个权限问题解决没？

**Comment by ydye** [comment]
@fanyangCS

**Comment by fanyangCS** [comment]
@jingruhou , we have deployed a fix to mitigate this issue. https://github.com/Microsoft/pai/pull/584. However, it is up to the operator to manage the storage system, including the permission issue of code, data, and output path.

**Comment by fanyangCS** [comment]
close and track the issue in #902
