### ISSUE TITLE
Support kubernetes internal DNS service in k8s-deployment.

### ISSUE THREAD

**Issue by ydye** [Microsoft/pai#627]

**Comment by xudifsd** [comment]
Currently, all pai service uses hostNetwork. I already checked that if a pod is using hostNetwork, it can not use k8s DNS.

So if we want to use DNS, we have to adopt [kubernetes network model](https://kubernetes.io/docs/concepts/cluster-administration/networking/), and change our network model from hostNetwork to k8s network. This requires a lot of effort to change already existed service.

I also did some benchmark to check the overhead of k8s network model. In default setting, k8s model's network is two times slower than host network.

I am strongly in favor of enabling k8s network model. We do not have to coordinate port allocation in different service, and can leverage DNS to do service discovery. But network overhead make it impossible for us to enable k8s network model for jobs.

So I'm thinking we can enable k8s network model and DNS, and adopt it in our service. But do not enable them in jobs.

**Comment by ydye** [comment]
@xudifsd 
The clusterDns and k8sDns solution could be compitable.
Pod’s DNS Policy
DNS policies can be set on a per-pod basis. Currently Kubernetes supports the following pod-specific DNS policies. These policies are specified in the dnsPolicy field of a Pod Spec.

“Default“: The Pod inherits the name resolution configuration from the node that the pods run on. See related discussion for more details.
“ClusterFirst“: Any DNS query that does not match the configured cluster domain suffix, such as “www.kubernetes.io”, is forwarded to the upstream nameserver inherited from the node. Cluster administrators may have extra stub-domain and upstream DNS servers configured. See related discussion for details on how DNS queries are handled in those cases.
“ClusterFirstWithHostNet“: For Pods running with hostNetwork, you should explicitly set its DNS policy “ClusterFirstWithHostNet”.
“None“: A new option value introduced in Kubernetes v1.9 (Beta in v1.10). It allows a Pod to ignore DNS settings from the Kubernetes environment. All DNS settings are supposed to be provided using the dnsConfig field in the Pod Spec. See DNS config subsection below.

REF : https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/

**Comment by ydye** [comment]
And I am also  strongly  in favor of enabling k8s network model too.

**Comment by xudifsd** [comment]
From k8s doc, pod with hostNetwork and `ClusterFirstWithHostNet` will still be able to use k8s dns?

What bad experiences do you have on flannel? I only know it has a lot of performance penalty.

If we want to enable k8s networking and DNS, we should do this earlier, later design and code can benefit from this.

**Comment by fanyangCS** [comment]
Coordinating ports among services isn't hard since the designer knows all the services before deployment. The hard part is for jobs to coordinate ports, which is currently done by Yarn. I do not feel the necessity of this feature.

**Comment by xudifsd** [comment]
@fanyangCS DNS is useful for service discovery.

We do not need this right now is because we get around this by requiring user to statically assign each service to node via node label. This obvious added burden on user when first booting up the cluster and later maintenance. This also prevent k8s from scheduling these services to other nodes when node is failed or under disk/memory pressure.

In other words, we may not needs this if we continue using static service deployment/discovery. But dynamic deployment/discovery requires this.

**Comment by xudifsd** [comment]
static service deployment/discovery also added burden of configuration maintenance and increased code complexity as shown in #1191

**Comment by fanyangCS** [comment]
static service deployment is to avoid interference between k8s and yarn. this should be a long term solution. For service discovery, if you would like to use it for fault tolerance, we have other solution that has actually already been tested before.
