### ISSUE TITLE
Submit job throws error "PortDefinitions is not empty, but local hadoop library doesn't support Port, please patch YARN-7481"

### ISSUE THREAD

**Issue by feng257** [Microsoft/pai#643]
I installed PAI first, submitted job and then find this error. After that I followed your tutorial to patch hadoop-2.7.2.gpu-port.patch exactly,  then rebuilt hadoop image, and re-deployed. But when I submit job, error still there. And I try re-deploy all service, still not work.    
Could you guys give some advise about this issue?  thx.

PS:  
I find two patches in https://issues.apache.org/jira/browse/YARN-7481  
hadoop-2.7.2.gpu-port.patch  and  hadoop-2.7.2.port-gpu.patch  
I choose hadoop-2.7.2.gpu-port.patch, because this one is a newer version.

**Comment by feng257** [comment]
Hi, thanks for your advice.  
I'm sure I set the value in services-configuration.yaml.  
I followed your tutorial to complied hadoop file, and put it in the directory which I set in yaml.  
But the error is still there.  
@ydye

**Comment by ydye** [comment]
Hi,

Did you build pai services' docker image on the dev-box container ,or your local host machine ?
If you worked on the container, have you mounted the hadoop-binary path correctly?


@qinchen123 @yqwang-ms

**Comment by feng257** [comment]
I deployed PAI on my own local host machine, and patched  fellowed your tutorial:  
https://github.com/Microsoft/pai/blob/master/pai-management/README-zh.md  
https://github.com/Microsoft/pai/blob/master/hadoop-ai/README-zh.md  
Can you give some detail about mounted the hadoop-binary path? thanks.

**Comment by ydye** [comment]
Hi @feng257 
This step:
https://github.com/Microsoft/pai/blob/master/pai-management/README-zh.md#%E5%87%86%E5%A4%87-dev-box

```
sudo docker run -itd \
        -e COLUMNS=$COLUMNS -e LINES=$LINES -e TERM=$TERM \
        -v /path/to/configuration/directory:/cluster-configuration  \
        -v /var/lib/docker:/varl/lib/docker \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v /hadoop/binary/path:/hadoop/binary/path \
        --pid=host \
        --privileged=true \
        --net=host \
        --name=deployment \
        kubernetes-deployment
```

In this line ```  -v /hadoop/binary/path:/hadoop/binary/path \```

After the dev-box is setup，you should build image and deploy service in it.

**Comment by feng257** [comment]
Hi, thanks for you answer.  
I checked the service-ip:8088, and I saw the values:  
![_001](https://user-images.githubusercontent.com/16338017/41022985-b46e1d60-699d-11e8-9e78-a9d57798066f.png)  
the hadoop configuration in service-configuration.yaml:  
`custom-hadoop-binary-path:` `/home/ubuntu/hadoop-2.7.2.tar.gz`

I re-complied hadoop, put it in the path as configuration and rebuilt the image.

**Comment by feng257** [comment]
does frameworklauncher also need to be pathed ?

**Comment by ydye** [comment]
@feng257 You build process is okay.
##My Questions.
1) Which branch of pai are you working on now?
2) Can you share us your json file which you submit your job.

## My Answer：
Launcher only need port configuration.
frameworklauncher:
  frameworklauncher-port: 9086


@qinchen123 @abuccts @yqwang-ms Can you follow this issue. The user's build process is okay. And hadoop-run is based on our hadoop-ai binary.

**Comment by feng257** [comment]
1. the branch I used is master branch of yesterday.  
2. json file:  
```
{
  "jobName": "jobName_4",
  "image": "192.168.2.212:5000/pai-images/demo4pai:chenc1.4",
  "dataDir": "$PAI_DEFAULT_FS_URI/demo4pai/data",
  "outputDir": "$PAI_DEFAULT_FS_URI/demo4pai/output",
  "codeDir": "$PAI_DEFAULT_FS_URI/demo4pai/code",
  "taskRoles": [
    {
      "name": "demo4pai",
      "taskNumber": 1,
      "cpuNumber": 1,
      "memoryMB": 512,
      "gpuNumber": 0,
      "portList": [
        {
          "label": "http",
          "beginAt": 20000,
          "portNumber": 1
        },
        {
          "label": "ssh",
          "beginAt": 20001,
          "portNumber": 1
        }
      ],
      "command": "sleep 12000;"
    }
  ]
}
```

**Comment by qinchen123** [comment]
by default, the port range is 1-19999,  "beginAt": 20000 will fail at port allocation.

**Comment by ydye** [comment]
@qinchen123 Do we have any document to notify user about this?

**Comment by feng257** [comment]
Hi, @qinchen123. Thanks for your answer.  I changed the port to 9000 & 9001, but error still there.  
'''
[Launcher] 400 {"exception":"BadRequestException","message":"com.microsoft.frameworklauncher.common.exceptions.BadRequestException: javax.validation.ConstraintViolationException: taskRoles[demo4pai].taskService.resource: PortDefinitions is not empty, but local hadoop library doesn't support Port, please patch YARN-7481 first: PortDefinitions: [{<http = 9000,1>, <ssh = 9001,1>}]\n\tat com.microsoft.frameworklauncher.common.validation.CommonValidation.validate(CommonValidation.java:49)\n\tat com.microsoft.frameworklauncher.webserver.LauncherModule.putFramework(LauncherModule.java:318)\n\tat sun.reflect.GeneratedMethodAccessor123.invoke(Unknown Source)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)\n\tat com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)\n\tat com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)\n\tat com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288)\n\tat com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)\n\tat com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)\n\tat com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)\n\tat com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)\n\tat com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1469)\n\tat com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1400)\n\tat com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349)\n\tat com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339)\n\tat com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)\n\tat com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)\n\tat com.sun.jersey.spi.container.servlet.ServletContainer.doFilter(ServletContainer.java:886)\n\tat com.sun.jersey.spi.container.servlet.ServletContainer.doFilter(ServletContainer.java:834)\n\tat com.sun.jersey.spi.container.servlet.ServletContainer.doFilter(ServletContainer.java:795)\n\tat com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)\n\tat com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)\n\tat com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)\n\tat com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)\n\tat org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)\n\tat org.apache.hadoop.http.HttpServer2$QuotingInputFilter.doFilter(HttpServer2.java:1243)\n\tat org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)\n\tat org.apache.hadoop.http.NoCacheFilter.doFilter(NoCacheFilter.java:45)\n\tat org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)\n\tat org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)\n\tat org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)\n\tat org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)\n\tat org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)\n\tat org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)\n\tat org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)\n\tat org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)\n\tat org.mortbay.jetty.Server.handle(Server.java:322)\n\tat org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)\n\tat org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945)\n\tat org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)\n\tat org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)\n\tat org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)\n\tat org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410)\n\tat org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)\nCaused by: javax.validation.ConstraintViolationException: taskRoles[demo4pai].taskService.resource: PortDefinitions is not empty, but local hadoop library doesn't support Port, please patch YARN-7481 first: PortDefinitions: [{<http = 9000,1>, <ssh = 9001,1>}]\n\t... 46 more\n","javaClassName":"com.microsoft.frameworklauncher.common.exceptions.BadRequestException"}
'''

**Comment by ydye** [comment]
@feng257 
In the address service-ip:8088/conf,
check whether this property exists or not.
```
<property>
     <name>yarn.ports_as_resource.enable</name>
    <value>true</value>
    <source>yarn-default.xml</source>
</property>
```

**Comment by ydye** [comment]
@feng257 Can you re-build frameworklauncher's binary with hadoop-run? And then have a try?

**Comment by feng257** [comment]
Do you mean re-bulid frameworklauncher and hadoop?  
the command like this:  
```
sudo ./docker_build.py -p ../cluster-configuration -n frameworklauncher  
sudo ./docker_build.py -p ../cluster-configuration -n hadoop-run
 ```

**Comment by ydye** [comment]
Yes, and then restart hadoop and frameworklauncher with the command
```
1) stop service
sudo ./bootstrap/service/clean.sh
2) start service
sudo ./deploy -p /path/to/configuration/directory -d -s your_service_name
```

**Comment by ydye** [comment]
@feng257  
The relation of hadoop-run and frameworklauncher.
base-image -> hadoop-run -> frameworklauncher.

launcher will check hadoop-version by the local hadoop binary on the container.
So if you use the old version launcher based on other hadoop version. It will throw this error.

This issue is solved. I will close this it.
