### ISSUE TITLE
PAI service deployed on existing k8s deployment

### ISSUE THREAD

**Issue by fanyangCS** [Microsoft/pai#653]
e.g., AKS. currently there exists some configuration issues that need manually resolvement.

**Comment by jingruhou** [comment]
请问：咱们这个PAI可以部署在没有GPU的环境上吗？

**Comment by ydye** [comment]
Sure, Because hadoop-ai is our patched version, and it is based the official hadoop. so in theory, there won't be any problem to run app or job without GPU. But when deploying pai, it is still recommended to build hadoop-ai.

**Comment by jingruhou** [comment]
@ydye Thank you for your answer

**Comment by jingruhou** [comment]
i have another question,how to plan hadoop cluster and k8s cluster ? this pai，does it have cluster environment planning example for readme.md?

**Comment by fanyangCS** [comment]
@jingruhou , we are working on it. will release a new deployment version, including more detailed document.

**Comment by jingruhou** [comment]
thank you for your answer ，I will consider using the pai in the near future and follow up @fanyangCS

**Comment by YanjieGao** [comment]
related to https://github.com/Microsoft/pai/issues/1324
