### ISSUE TITLE
Virtual Clusters shows 'NaN %' Utilization for default vc

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#709]
Steps to reproduce:

1.  'default' VC not specified.
2.  Install and start PAI.
3.  Open the PAI dashboard and navigate to 'Virtual Clusters' tab.

See the below.
![image](https://user-images.githubusercontent.com/1547343/41270904-39baf2b2-6e40-11e8-8299-1749ffbe8324.png)

**Comment by fanyangCS** [comment]
this has been addressed by this PR: https://github.com/Microsoft/pai/pull/692

**Comment by hao1939** [comment]
I see, and noticed this PR had merged into master branch.
And I checked the code, maybe missing a 'None' check.
https://github.com/Microsoft/pai/blob/a5b6d063ad0fe1f9b6f4ac3b6d56aa081b38f1ab/webportal/src/app/vc/vc.component.ejs#L32

**Comment by hao1939** [comment]
It's a 'divided by zero' error.
Here's default vc: {capacity: 0, maxCapacity: 100, usedCapacity: 0, numActiveJobs: 0, numJobs: 0, numPendingJobs: 0}

**Comment by hao1939** [comment]
I will close it later after some check, can reproduce it now.

**Comment by fanyangCS** [comment]
@hao1939, please check if the PR has been included in the new release branch. if not, you can cherry pick it

**Comment by hao1939** [comment]
Confirmed.
It already in the 'master' branch, and will into the release branch.
