### ISSUE TITLE
Permission deny if not use the container

### ISSUE THREAD

**Issue by qyyy** [Microsoft/pai#716]
I just start the installing process without installing the container(ignore the [container installment step](https://github.com/Microsoft/pai/blob/master/pai-management/doc/how-to-setup-dev-box.md)), then I meet with a "Permission Denied" error at the second step---Boot up Kubernetes. I have already known that there is no problem by using the container to install the PAI, but I wonder if it is necessary to install the container? If the answer is yes, I propose to point it out in the document, if not, I think it's maybe a bug?

**Comment by ydye** [comment]
Prefer to point it out, I think in working on a container with all package dependency will be better. Because in this environment, you don't need to install some software which you don't like.
And what's your opinion?

**Comment by qyyy** [comment]
I think it's necessary to point it out that our user would better use docker in the [cluster boostrap documents](https://github.com/Microsoft/pai/blob/master/pai-management/doc/cluster-bootup.md) to avoid the permission problems.

**Comment by scarlett2018** [comment]
Closing as @qyyy had responded the recommended approach.
