### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by pczchen** [Microsoft/pai#722]
1、系统安装至少需要几台服务器？
2、如果只有两台服务器，已经搭建好了K8S集群了， 如何进行手工安装与配置？

**Comment by fanyangCS** [comment]
1. One
2. we currently do not provide support to deploy PAI on an existing k8s cluster. we plan to release the guide in the future. it is possible to figure out the details through https://github.com/Microsoft/pai/blob/master/pai-management/doc/cluster-bootup.md#step-3-start-all-pai-services-
https://github.com/Microsoft/pai/issues/653
