### ISSUE TITLE
vulnerable issue: password printed into stdout

### ISSUE THREAD

**Issue by hao1939** [microsoft/pai#729]
When install k8s cluster, there would print the password a lot of times.

For example:

> 2018-06-14 03:33:46,820 [INFO] - k8sPaiLibrary.maintainlib.common : Executing the command on host [10.11.2.38]: sudo ./worker-deployment/docker-ce-install.sh
> **_password_here_**
> [sudo] password for user:

**Comment by fanyangCS** [comment]
redirect stdout to /dev/null. https://stackoverflow.com/questions/12027170/shell-redirect-stdout-to-dev-null-and-stderr-to-stdout 
@ydye

**Comment by ydye** [comment]
@fanyangCS  Redirecting stdout to /dev/null will cause our command failure. Because this issue is not critical, pending it.
