### ISSUE TITLE
virtual-clusters can't display. Internal request should by pass restserver

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#736]
Scenario:

1. PAI deployed in internal net, pai dashboard is on port 9286
2. Nat the internal port 9286 to internet.
3. User view pai virtual-clusters info: http://public_ip:9286/virtual-clusters.html
4. Page shows blank, and gets network error from the console: 
> GET http://10.11.3.2:9186/api/v1/virtual-clusters 0 ()

Obviously, the 9186 port is not accessible.

**Comment by sterowang** [comment]
If you deployed pylon, pylon can proxy the all ports to port 80, so visit ttp://public_ip/ should work.

**Comment by hao1939** [comment]
👍 Thanks!
It's working.
