### ISSUE TITLE
error on “paictl.py cluster k8s-bootup -p /pathtoconfig”

### ISSUE THREAD

**Issue by boozyguo** [Microsoft/pai#754]
when run  “paictl.py cluster k8s-bootup -p /pathtoconfig”, I got a eror report:

[sudo] password for user: 
cf3338eb47776f0d5b25ef243f16e271a430504d6341b7053abc8145f5d9f623
docker: Error response from daemon: service endpoint with name kubelet already exists.

and

2018-06-22 09:09:45,622 [ERROR] - k8sPaiLibrary.maintainlib.common : There will be a delay after installing, please wait.
error: the server doesn't have a resource type "node"
2018-06-22 09:09:45,765 [ERROR] - k8sPaiLibrary.maintainlib.common : There will be a delay after installing, please wait.
error: the server doesn't have a resource type "node"
2018-06-22 09:09:45,929 [ERROR] - k8sPaiLibrary.maintainlib.common : There will be a delay after installing, please wait.
error: the server doesn't have a resource type "node"
2018-06-22 09:09:46,049 [ERROR] - k8sPaiLibrary.maintainlib.common : There will be a delay after installing, please wait.
error: the server doesn't have a resource type "node"
……………………

the container at server is:
user@user:~$ sudo docker ps --all
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS              PORTS               NAMES
cf3338eb4777        docker.io/openpai/hyperkube:v1.9.4   "/hyperkube kubele..."   3 minutes ago       Created                                 kubelet

Please help to fix the question. Thanks.

**Comment by ydye** [comment]
Hi, if you wanna redeploy k8s, you should clean k8s deployment first. And note, this action will delete data on etcd where storing your pai's user information data.
Command:
```
./k8sClusterManagement.py -p /path/to/configuration/directory -a clean
```

**Comment by abuccts** [comment]
@boozyguo Please track your new network issues in #813.

**Comment by boozyguo** [comment]
@abuccts thank you. I will check #813.
