### ISSUE TITLE
PAI cluster: Howto release GPUs occupied by hanging jobs?

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#762]
Here's case:
1. A PAI cluster has 72 GPUs.
2. After ran many jobs, which hung because of the 'out-of-memory'(or any other problem), 36 of the GPUs are occupied.
3. User want to release those GPUs.

What's the best approach? Maybe:
1. Backup HDFS
2. Uninstall PAI
3. Manually kill all the hung jobs
4. Reinstall PAI

The question is step 1 and 3. It's not easy to achieve. Any suggestion?

**Comment by fanyangCS** [comment]
this is a bug, which is fixed by https://github.com/Microsoft/pai/pull/735.
I expect no more hanging docker instances in the future.
