### ISSUE TITLE
questions of GPU scheduling

### ISSUE THREAD

**Issue by zhaojiabin123** [Microsoft/pai#778]
1.细粒度的GPU调度可以做到什么程度，最小单位是多少？与每个节点的资源量有关吗(64 GPUs per node)？
2.k8s与YARN是如何结合的，有相关的说明文档吗？
3.k8s中的容器可以请求1个或多个GPU，但不能只请求一部分，造成资源浪费，PAI能否解决，是如何解决的？

**Comment by qinchen123** [comment]
1. GPU最小调度单位是 单个GPU,  与节点GPU资源无关，单个容器的最大资源 与节点资源有关。 
2. k8s 负责管理和部署服务， job 调度由yarn 负责。 
3. 这个问题是咨询 请求单个节点的部分GPU，还是请求单个GPU部分计算能力 ？ 
    PAI 支持一个 job 请求单个节点的部分GPU资源，该节点的其余GPU资源可以调度给其他job, 所以， 在PAI里面，不存在GPU的大量浪费问题。 PAI 不支持请求单个GPU 的部分计算能力。

**Comment by zhaojiabin123** [comment]
第三个问题可能我没有问明确，假如一个服务器中只安装了一块NVIDIA的P4显卡，可不可以分配两个或多个任务给它？

**Comment by qinchen123** [comment]
两个任务不能共享一个GPU, 如果你的显卡只有一块GPU单元，那就只能服务一个任务。 如果有多个GPU单元，就可以服务多个任务。
