### ISSUE TITLE
Vary kinds of service pods show: Waiting: ContainerCreating

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#779]
Haven't figure out the reproducing steps.
List the examples here.

![image](https://user-images.githubusercontent.com/1547343/41955324-26e1a482-7a12-11e8-8f3f-4767ca0103b0.png)

Add one more screenshot, the node exporter failure was cause by the driver issue.
![image](https://user-images.githubusercontent.com/1547343/41966909-e6a748d8-7a32-11e8-8742-939187ce68e5.png)

Below is the driver's log.
```
++ uname -r
+ KERNEL_FULL_VERSION=4.15.0-1013-azure
+ CURRENT_DRIVER=/var/drivers/nvidia/current
+ echo ======== If NVIDIA present exit early =========
======== If NVIDIA present exit early =========
+ nvidiaPresent
+ [[ -f /proc/driver/nvidia/version ]]
+ grep -q 384.111 /proc/driver/nvidia/version
+ lsmod
+ grep -qE '^nvidia'
+ lsmod
+ grep -qE '^nvidia_uvm'
+ [[ -e /dev/nvidia0 ]]
+ [[ -e /var/drivers/nvidia/384.111/lib64/libnvidia-ml.so ]]
+ return 0
+ [[ -L /var/drivers/nvidia/current ]]
+ exit 0
NVIDIA gpu detected, drivers installed
=== Enable nvidia persistenced mode
=== Recall nvidia-smi
Unable to determine the device handle for GPU 8786:00:00.0: The NVIDIA kernel module detected an issue with GPU interrupts.Consult the "Common Problems" Chapter of the NVIDIA Driver README for
details and steps that can be taken to resolve this issue.
```

**Comment by sterowang** [comment]
@YanjieGao Why Grafana ConfigMap not created? Can you help to investigate the root cause?

**Comment by YanjieGao** [comment]
Need double check, but maybe hao first remove the service then quick deploy, the remove process is running may accidentally  remove the new deployment of some service or configmap

**Comment by YanjieGao** [comment]
The service has recovered, lost the env to identify

**Comment by hao1939** [comment]
Finally, fix the driver issues via following steps:
1. unlabel the node `kubectl label node 10.151.40.236 machinetype-`
2. label the node `kubectl label node 10.151.40.236 machinetype=gpu`
3. reboot
4. hours later, it turns fine

**Comment by hao1939** [comment]
Actually, many kinds of container failure would cause the pod 'Waiting: ContainerCreating'.
I will close this ticket and create new ones for every single case.
