### ISSUE TITLE
Single box installation: failed to install drivers 

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#784]
Steps to reproduce:
1. Install a single box using generated template config
2. After the PAI startup, the node was not labeled with 'machinetype: gpu'.
So I manually label it: `kubectl label node 10.0.1.6 machinetype=gpu
3. When install the driver, I got the error messages below:
```
======== If NVIDIA present exit early =========
+ KERNEL_FULL_VERSION=4.4.0-128-generic
+ CURRENT_DRIVER=/var/drivers/nvidia/current
+ echo ======== If NVIDIA present exit early =========
+ nvidiaPresent
+ [[ -f /proc/driver/nvidia/version ]]
+ grep -q 384.111 /proc/driver/nvidia/version
+ lsmod
+ grep -qE '^nvidia'
+ lsmod
+ grep -qE '^nvidia_uvm'
+ return 3
+ echo ======== If NVIDIA driver already running uninstall it =========
+ lsmod
======== If NVIDIA driver already running uninstall it =========
+ grep -qE '^nvidia'
++ lsmod
++ tr -s ' '
++ grep -E '^nvidia' 
```

**Comment by hao1939** [comment]
@ydye advised to stop the 'Node Manager' and 'prometheus' temporarily, bring them back after driver is ready.
It works.

**Comment by fanyangCS** [comment]
This is the service dependency we should capture in the deployment process
