### ISSUE TITLE
Custom config option for Docker Run

### ISSUE THREAD

**Issue by chivee** [Microsoft/pai#787]
Hi,

Could you please provide a custom option for the `docker run` script in 
https://github.com/Microsoft/pai/blob/9655bed1ebcc28c2577157e588393ecd110ccfbb/rest-server/src/templates/yarnContainerScript.mustache#L203-L226

Considering that there are more option we'd like to change of the container such as --shm-size for the shared memory.

**Comment by abuccts** [comment]
1. User may set privilege or host capabilities for Docker if custom `docker run` option is enabled, which is hard to control in system level.
2. I have added `--shm-size` in #791, this option is needed by pytorch for multiprocessed data reading at present.
