### ISSUE TITLE
Some way to prevent yarn to schedule jobs to particular machine?

### ISSUE THREAD

**Issue by xwzheng1020** [Microsoft/pai#789]
When one or some of GPUs of a server are corrupted, is PAI  can automatically or manually label machine as unavailable and no longer run new tasks on this machine? So the operation personnel can repair the machine after all other tasks completed.

Or the manager can submit a job that will be scheduled to a designated machine？

**Comment by yqwang-ms** [comment]
YARN Graceful Decommission may help you, see.
https://issues.apache.org/jira/browse/YARN-914

However, current PAI's hadoop-ai is based on Hadoop 2.7.2 which does not support at least the basic features of Graceful Decommission.
We will upgrade the Hadoop to 2.9 soon, and after that, the basic Graceful Decommission should be ready for you to use.

@qinchen123 who is working on GPU scheduling and Hadoop upgrade.

**Comment by fanyangCS** [comment]
we have upgraded yarn to 2.9.0 in 0.7.y
