### ISSUE TITLE
ETCD 4001 port

### ISSUE THREAD

**Issue by ydye** [microsoft/pai#805]
AS the etcd log says:
```
2018-07-04 02:18:16.844316 N | embed: serving insecure client requests on [::]:4001, this is strongly discouraged!

```

**Comment by fanyangCS** [comment]
@DongZhaoYu , does your fix resolve this issue?

**Comment by scarlett2018** [comment]
@fanyangCS - what's the impact of this issue? is it still an issue in 0.11.0?

**Comment by fanyangCS** [comment]
Close this issue as we will rely on third party tools (e.g., kubespray and AKS) to deploy k8s.
