### ISSUE TITLE
What's the default username and password for webportal

### ISSUE THREAD

**Issue by Beyyes** [Microsoft/pai#823]
![image](https://user-images.githubusercontent.com/6756545/42363653-fd9ed0de-812a-11e8-8fcf-c808c010e371.png)

**Comment by fanyangCS** [comment]
for quick start template, it is here: 
https://github.com/Microsoft/pai/blob/master/pai-management/quick-start/services-configuration.yaml.template#L91
https://github.com/Microsoft/pai/blob/master/pai-management/quick-start/services-configuration.yaml.template#L93

if you use our example cluster config yaml files: 
it is here:
https://github.com/Microsoft/pai/blob/master/cluster-configuration/services-configuration.yaml#L92
https://github.com/Microsoft/pai/blob/master/cluster-configuration/services-configuration.yaml#L94

**Comment by Beyyes** [comment]
@fanyangCS 
I have tried ```admin : admin-password```, but it didn't take effect.
And when I input wrong username and password, the User Login interface doesn't show any hints.

**Comment by Beyyes** [comment]
Maybe the reason is that some services are down...
![image](https://user-images.githubusercontent.com/6756545/42365498-396f0380-8131-11e8-8ab9-d230485377eb.png)
