### ISSUE TITLE
Support master/worker co-exists

### ISSUE THREAD

**Issue by squirrelsc** [Microsoft/pai#827]
There may be dead lock in some race condition, if master/worker coexists. It blocks single-box, and raises deployment bar for small machine set. So it should be addressed.

**Comment by mzmssg** [comment]
Dead lock means service start and stop for insufficient resource repeatedly? We will check every service's resource demand and give a minimum configuration.

**Comment by fanyangCS** [comment]
close this issue and track it in another one.
