### ISSUE TITLE
Why hadoop-data-node service could not be started?

### ISSUE THREAD

**Issue by Beyyes** [Microsoft/pai#833]
After I run the command ```python paictl.py cluster k8s-bootup -p /path/to/cluster-configuration/dir```,
hadoop-data-node service is always in waiting status, just like picture below show.
![image](https://user-images.githubusercontent.com/6756545/42431651-79717482-8379-11e8-8629-246ffcbfa6e9.png)

The logs of hadoop-data-node pod is shown as the picture below.
![image](https://user-images.githubusercontent.com/6756545/42431680-95924fd8-8379-11e8-9a59-f190fb7ac76c.png)

![image](https://user-images.githubusercontent.com/6756545/42431602-2f49605e-8379-11e8-8668-d031f85afd58.png)

How to solve this problem?

**Comment by ydye** [comment]
May be the reason
- You have deployed hadoop once, and clean namenode data. But datanode data still in the disk.
Solution.
- Running following command. And this solution will cleanup your hdfs
```
./paictl.py service delete -p /path/to/config -n hadoop-data-node
```

```
./paictl.py service delete -p /path/to/config -n hadoop-name-node
```

- Before deploying service. SSH to the node which failed to start dn. Manually delete the hadoop data in the [storage path](https://github.com/Microsoft/pai/blob/master/cluster-configuration/services-configuration.yaml#L31)

**Comment by ydye** [comment]
Not continue to update. Close this issue.
