### ISSUE TITLE
Not able to see the previous retry from the job view

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#834]
This job has been retried 35 times.
http://10.151.40.179/view.html?jobName=tensorflow-cifar10-test_v8

I don’t seem to be able to see the previous retry from the job view.

**Comment by yqwang-ms** [comment]
This is planed to be handled by:
Launcher's HistoryServer:
Store all the history of Framework Request and Status for each previous versions and attempts.

**Comment by fanyangCS** [comment]
will do some quick fix in job view by @Gerhut

**Comment by wangcan0329** [comment]
Already do quick fix in job view. if job retry count > 0 you can click retry number in job detail page then will jump to Yarn portal which will show job history automatically.
