### ISSUE TITLE
rest-server error

### ISSUE THREAD

**Issue by kenqxcheng** [Microsoft/pai#843]
> pai-rest-server@0.1.0 start /usr/src/app
> node index.js

/usr/src/app/src/config/index.js:59
  throw new Error(`config error\n${error}`);
  ^

Error: config error
ValidationError: child "jwtSecret" fails because ["jwtSecret" is required]
    at Object.<anonymous> (/usr/src/app/src/config/index.js:59:9)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/src/server.js:25:16)
    at Module._compile (module.js:577:32)

npm ERR! Linux 4.4.0-128-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.14.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! pai-rest-server@0.1.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pai-rest-server@0.1.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pai-rest-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pai-rest-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pai-rest-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log

**Comment by abuccts** [comment]
@kenqxcheng Can you share your configuration? It seems that you didn't set `jwt-secret` in [service configuration](https://github.com/Microsoft/pai/blob/master/cluster-configuration/services-configuration.yaml#L90).

**Comment by fanyangCS** [comment]
close as no further input.
