### ISSUE TITLE
Pylon service failed to start

### ISSUE THREAD

**Issue by kenqxcheng** [Microsoft/pai#851]
pylon logs
![image](https://user-images.githubusercontent.com/4695796/42561876-ddea9f24-852c-11e8-9e86-2bf1701bba41.png)

What settings do I need to make?

Thanks!

**Comment by fanyangCS** [comment]
from the log, it is not a failure. the service will start in a while, depending on the network speed to docker registry

**Comment by fanyangCS** [comment]
no further comment. will close for now.
