### ISSUE TITLE
what is the HA plan for service like resource manager

### ISSUE THREAD

**Issue by weiranzhixin** [Microsoft/pai#852]
* pod related  is like:  zoom-keeper, name-node, resource-manager, frameworklauncher, rest-server,webportal 
* these pods are deployed by daemon-set
* numble of these pod is 1(is this numble correct ? ), what if the host machine of the pod like name-node is down ?

**Comment by fanyangCS** [comment]
Please refer to Hadoop community for its HA setup. e.g., https://hadoop.apache.org/docs/r2.7.2/hadoop-project-dist/hadoop-hdfs/HDFSHighAvailabilityWithNFS.html

As for Hadoop k8s deployment, it is straightforward. taking name node as an example, deploy name node as daemonset, label two nodes as namenode. and have the two config in HA mode. 

HA deployment is in our plan, but no ETA yet.

**Comment by ydye** [comment]
A history branch you could refer to: https://github.com/Microsoft/pai/tree/hadoop-ha-branch

**Comment by fanyangCS** [comment]
close and track in this issue. https://github.com/Microsoft/pai/issues/724.
