### ISSUE TITLE
Is there any way to display jobs of queuing and running in the head of list?

### ISSUE THREAD

**Issue by shishaochen** [Microsoft/pai#876]
Currently, the sort of the status column is using the literal sequence. If the job count is very large, the running ones may be displayed after tens of pages.
**Could we sort them by a status code like QUEUE=1, RUNNING=2, COMPLETED=3?**
![image](https://user-images.githubusercontent.com/17514649/42681347-00452dd0-86ba-11e8-9061-bb5e92e270fd.png)

**Comment by YitongFeng** [comment]
Set the Datatable's column.type, https://datatables.net/reference/option/columns.type may help you.

**Comment by shishaochen** [comment]
@YitongFeng I am not the owner of PAI web portal......
Just a suggestion on user experience.

**Comment by YitongFeng** [comment]
Sorry, I thought you ask the question for Hackthon. 😄
