### ISSUE TITLE
The Reason to add this configuration file to the docker image

### ISSUE THREAD

**Issue by ydye** [Microsoft/pai#895]
Hi,

I'm little confused about file in the watchdog's docker image (paste the link following). 

- Why should we add this file? 
- Can we 
   - create a template file in the bootstrap/watchdog
   - generated by cluster-configuration
   - mount the file to the docker container by configmap.  

https://github.com/Microsoft/pai/blob/64161acd14e3dac25acc9b2ca666e9d5fa8360ff/pai-management/src/watchdog/image.yaml#L23

**Comment by YanjieGao** [comment]
once use this file to get cluster's node and ssh info. 
If we deployment phase could generate and give watchdog temp file contains this info is better.

**Comment by ydye** [comment]
@YanjieGao I wanna clarify one thing the file ```cluster-configuration/cluster-configuration``` is only an example. User could put the configuration anywhere, and pass the path through the parameter ```-p``` when executing paictl. So you should use configmap to pass the detail configuration.

Please refer to this [file](https://github.com/Microsoft/pai/blob/master/pai-management/bootstrap/cluster-configuration/host-configuration/host-configuration.yaml.template)

**Comment by YanjieGao** [comment]
OK, let's make a watchdog's template file at watchdog folder and it could let PAI auto parse user config and replace the watchdog's template file as server ip and ssh info. @xudifsd

**Comment by xudifsd** [comment]
The only way we need configuration is due to monitoring docker.

Another way to solve this is through [this](https://docs.docker.com/config/thirdparty/prometheus/), let docker exports its metrics, and let prometheus scrape them.

With docker exporting its own metrics, there should be no needs for watchdog to ssh into machine.
