### ISSUE TITLE
PAI doesn't move dataDir to docker?

### ISSUE THREAD

**Issue by SongBiu** [Microsoft/pai#897]
I find that there isn't dataDir I write in config.json in docker.
So how can I move data in dataDir to docker?

**Comment by scarlett2018** [comment]
dataDir is just an Env parameter for current PAI design, we will update the documentation for clarity.

You will need to copy the data to docker by yourself for now.

**Comment by SongBiu** [comment]
Thanks!
How about ouputDir?
Need I copy the output data from docker to HDFS?

**Comment by squirrelsc** [comment]
@hao1939 @scarlett2018   It would be a great feature, if PAI can mount such folders into docker. It's convenient to users, and also address part of security concerns.

**Comment by fanyangCS** [comment]
Except codeDir, PAI will not move data specified in the environment. PAI assume docker image is owned by customers, so it is up to customer to see if he/she would like to mount to the path from within the docker container.
