### ISSUE TITLE
better support for on-demand apply resource

### ISSUE THREAD

**Issue by squirrelsc** [microsoft/pai#903]
In some scenario, user want to have a dedicated docker for a while. For example, user is using jupyter notebook, he need response immediately, and save some scripts persistent in a pod. It has some initial support now, and it can be better.

Details,
1. Support user to mount some folder like home. It can be persistent, and download/upload in storage. So that user can work on some scripts in a pod, and save/upload them out of pod.
2. Limit count of on-demand request for each user. It avoid all resources are occupied by several users.
3. provide timeout and return mechanism to make sure idle resource can be recycled.
4. Provide better experience and make sure it e2e works for jupyter. For example, provide a page that user can request a on-demand machine with resource requirement, time range (with maximum limitation) for jupyter.

**Comment by fanyangCS** [comment]
the feature requirement has been decoupled into jupyter notebook support and storage support. closed.
