### ISSUE TITLE
Support to manage virtual cluster in runtime.

### ISSUE THREAD

**Issue by squirrelsc** [Microsoft/pai#906]
Virtual cluster is used to allocate resource. But it can be updated in config only. It's not easy to use. So it's better to be able to add/delete/update virtual cluster and update capacity in runtime.

**Comment by mzmssg** [comment]
The bot of virtual cluster is Yarn scheduler queue, which support update actually.  This feature in PAI needs some refactor and may be added in future.

**Comment by mzmssg** [comment]
Finished in https://github.com/Microsoft/pai/pull/1985
