### ISSUE TITLE
Can not stop the job by using rest API

### ISSUE THREAD

**Issue by qyyy** [Microsoft/pai#909]
When I use rest API to stop my job, though the response code is 202 and data is ''{"message":"execute job autoML_2018-07-18_10-57-06 successfully"}", the job in web portal is still running.
This is my code:
```python
response = self.http.request(
            'PUT',
            self.rest_server_socket + 'jobs/' + job_name + '/executionType',
            headers={
                'Authorization': 'Bearer ' + self.token,
            },
            body=json.dumps({'value': 'STOP'}),
        )
        if response.status == 202:
            print(response.data)
            return True
        else:
            print(response.status, response.data)
            return False
```
And this is my job url.
http://10.151.40.179/view.html?jobName=autoML_2018-07-18_10-57-06

**Comment by qyyy** [comment]
I have solved this issue by adding 'Content-Type': 'application/json' to the request header. However, when I check the rest server log and launcher log, I found that although the parameter can not be interpreted correctly, the launcher and rest server still return true. So, I think it's better to return false if the parameter can not be interpreted.

**Comment by Gerhut** [comment]
Will add parameter validation to this controller.
