### ISSUE TITLE
Will PAI kill or stop the job automatically if the GPU of the job is free for a long time

### ISSUE THREAD

**Issue by qyyy** [Microsoft/pai#912]
If I submit a job with a request of a GPU, will PAI kill or stop the job automatically if the GPU of the job is free for a long time? For example, The process I start only uses GPU for 10 minutes per hour.

**Comment by yqwang-ms** [comment]
No. 
To improve the GPU utilization, you may need to seperate the non-GPU workload from GPU workload to different job or different taskrole.
