### ISSUE TITLE
--require-kubeconfig deprecated in kubernetes 1.10.0

### ISSUE THREAD

**Issue by DongZhaoYu** [Microsoft/pai#918]
Kubernetes deprecated --require-kubeconfig parameter in v1.10.0 . So we need to change our launching script when starting kubelet.

**Comment by YitongFeng** [comment]
**K8s version >= 1.10, need to remove --require-kubeconfig and specify config file path with --kubeconfig.**

In old K8s version, there are two ways to specify the master (refer to v1.7 doc https://v1-7.docs.kubernetes.io/docs/admin/kubelet/ ):

1.	With flag –api-servers
2.	With flags --require-kubeconfig + --kubeconfig.  --kubeconfig is path to a kubeconfig file (default is "/var/lib/kubelet/kubeconfig", specifying how to connect to the API server, if --require-kubeconfig is not set, --api-servers will be used.

In higher version of K8s, the --api-servers and --require-kubeconfig are both deprecated.
Currently PAI use k8s v1.9, it just throw a warning, in >=v1.10, they are totally removed in this PR (https://github.com/kubernetes/kubernetes/pull/58367 ), note that it also removed the default path of –kubeconfig, which means we must specify --kubeconfig in >= 1.10 version

**Comment by fanyangCS** [comment]
We can keep our current k8s version for now. as I do not see a reason to upgrade. We can come back to his issue when we need to upgrade.

**Comment by fanyangCS** [comment]
@YitongFeng would be good to provide a reason to close this issue.
