### ISSUE TITLE
Provide email notification

### ISSUE THREAD

**Issue by squirrelsc** [microsoft/pai#921]
As OpenPAI is an async platform. It's better to notify users when job started, completed or error. So that users don't need to visit web portal frequently.

**Comment by squirrelsc** [comment]
@xudifsd It's about to provide notification for PAI users. When job started, completed, user can get notification. Is it implemented?

**Comment by xudifsd** [comment]
Oh, I misunderstood this issue. I thought it was about providing email notification about system performance and fault.

**Comment by yqwang-ms** [comment]
Thanks squirrelsc, @scarlett2018 could you please help to triage this?

**Comment by fanyangCS** [comment]
it seems that this feature can be implemented in launcher, where job state can be tracked accurately? @yqwang-ms , what do you think?

**Comment by yqwang-ms** [comment]
I know launcher can track accurately, but it would be better to let high level service to send the email.
launcher would be better to keep pure as container orchestrator and others should leverage it to detect state change events.
https://github.com/Microsoft/pai/tree/master/subprojects/frameworklauncher

**Comment by yqwang-ms** [comment]
And our system is already level triggered instead of edge triggered, even for Launcher itself. So, miss event change event should be acceptable.

**Comment by fanyangCS** [comment]
@yqwang-ms, is it possible for a job to know the state of itself? e.g., we provide an optional hook or callback for system call in case of job completion? this could provide enough flexibility for user to customize their own behavior (sending email, sms, or whatever he/she prefers.)

**Comment by yqwang-ms** [comment]
It is possible, but that introduces interop with a potential unreliable service. Such as, should launcher best effort call the callback or block on the success of the callback? We provide at least once call or exactly once or etc? So, for the simplest and reliable solution is the external service monitor the rest api, then take actions, this is aligned with k8s design principle.

**Comment by yqwang-ms** [comment]
The simliar offerings in k8s is https://github.com/bitnami-labs/kubewatch
It is also just a controller which monitors the api server, and it may miss events.

**Comment by yqwang-ms** [comment]
AM is a system components, it has admin privilege, we cannot directly execute the shell script (i.e. YARN cannot isolate everything). The shell script also make AM different from each other and hard to debug.
Compared with very long running time AI jobs, we can poll the frameworks api in every min, it should be fine and not heavy weight

**Comment by fanyangCS** [comment]
After some discussion, this feature is better implemented outside of OpenPAI's core infrastructure code base. 
OpenPAI provides REST APIs to query a job status. User can develop and deploy a watchdog to watch the jobs and define any actions in case of job status changes. The watchdog can be deployed to OpenPAI as a job. But the core PAI platform will not treat it as a system component, so no liability about its liveness, etc.

And the easiest way for a user to implement (a part of) this feature is to add some script at the end of the command line input. But this approach can only work when there is no exception raised in the user code. But I assume this would work for most cases.

**Comment by xinase** [comment]
do we need to support multiple language support (e.g. Chinese and English) in email text?

**Comment by xudifsd** [comment]
@xinase No, we current do not have such option, You can configure email text [here](https://github.com/Microsoft/pai/tree/pai-0.9.y/src/prometheus/deploy/alerting) by changing the summary of each alerting rule.

**Comment by sterowang** [comment]
Is it possible we expose job status as a metrics, and define an alert rule to be triggered when status changed? I suppose Prometheus alert server is able to send out this kind of email alerts to job owner's email. @xudifsd is it possible?

**Comment by xudifsd** [comment]
@sterowang Yes, it is possible to send to job owner via alert-manage as long as we enrolled the user's email info. We can also send alert email about low resource usage the same way.

**Comment by scarlett2018** [comment]
> Is it possible we expose job status as a metrics, and define an alert rule to be triggered when status changed? I suppose Prometheus alert server is able to send out this kind of email alerts to job owner's email. @xudifsd is it possible?

Good ones, we should combine these set of features with the "User Home Page" and "Job Metrics for User".

**Comment by fanyangCS** [comment]
closed and track in https://github.com/microsoft/pai/issues/2235
