### ISSUE TITLE
Why from hadoop2.7.2-cuda8.0-cudnn6-devel-ubuntu16.04

### ISSUE THREAD

**Issue by pkuyym** [Microsoft/pai#932]
https://github.com/Microsoft/pai/blob/master/job-tutorial/Dockerfiles/cuda9.0-cudnn7/Dockerfile.run.tensorflow#L26

**Comment by fanyangCS** [comment]
tensorflow relies on some Hadoop lib to access hdfs

**Comment by pkuyym** [comment]
Thanks for your reply. I mean why not from hadoop2.7.2-cuda9.0-cudnn7-devel-ubuntu16.04.

**Comment by fanyangCS** [comment]
@pkuyym thanks for pointing it out. @abuccts can you take a look and fix it?
