### ISSUE TITLE
[deploy] after deploy successful, console log tail pint OpenPAI main page url

### ISSUE THREAD

**Issue by YanjieGao** [microsoft/pai#965]
For user, it is helpful to show OpenPAI main page url (http://IP:9286) at the console log tail.
position:
![image](https://user-images.githubusercontent.com/5576848/43118779-08f077a2-8f46-11e8-88f5-eb87f184fee6.png)

Ref software:
Jupyter: after run jupyter notebook, it will show the main page url.

**Comment by fanyangCS** [comment]
close as we will rely on third party tool to deploy k8s.
