### ISSUE TITLE
[dev-box] dev-box image's paictl.py's k8s-clean part is commented and can't be used

### ISSUE THREAD

**Issue by YanjieGao** [Microsoft/pai#966]
When deploy found that: dev-box image's paictl.py's k8s-clean part is commented and can't be used.
When i deploy at the test bed, need to clean pai at first. 
Found run sudo python paictl.py cluster k8s-clean -p path, not work. Find this part is commented. For master branch this part no problem. 
![image](https://user-images.githubusercontent.com/5576848/43118923-cf602f22-8f46-11e8-951a-e3b51ffbe1e8.png)

**Comment by hao1939** [comment]
I will build and push a latest dev-box.

**Comment by hao1939** [comment]
Done.
