### ISSUE TITLE
It's not user-friendly to show the code error info when input the password

### ISSUE THREAD

**Issue by Beyyes** [Microsoft/pai#967]
It's not user-friendly to show the code error info when input the password which has no 6 characters long :）

![image](https://user-images.githubusercontent.com/6756545/43119247-31a2d436-8f48-11e8-988d-e394183cc958.png)

**Comment by Gerhut** [comment]
We will refine error messages in next release by #807

![image](https://user-images.githubusercontent.com/2500247/43497281-f1f17248-9573-11e8-9c82-dfbe57071a06.png)
